### ISSUE TITLE
Install without v8/shinystan dependency

### ISSUE THREAD

**Issue by mguzmann** [paul-buerkner/brms#1001]
Is it possible to install brms without the shinystan dependency? I ask because I have a server where it is basically impossible to install v8 and the V8 package, which are required for shinystan. Is it possible to install brms without this dependency?

Thanks!

**Comment by jgabry** [comment]
Sorry you're having installation trouble. V8 isn't actually a direct dependency of shinystan, but maybe it's a dependency of one of the dependencies? Are you sure it's shinystan that's the problem? The only V8 issues I've seen reported relate to rstan, for example: https://github.com/stan-dev/rstan/issues/831

**Comment by rok-cesnovar** [comment]
Its a dependecy of rstan (to run the stanc3 compatibility check for now, but will be used for Stan-to-C++ in 2.23+).

**Comment by mguzmann** [comment]
So no way around this, right?

**Comment by rok-cesnovar** [comment]
Maybe installing rstan 2.19 is a temporary solution, but in the long run unfortunately no. Except if we find another javascript engine to replace V8.
