### ISSUE TITLE
Problem with grouped stat options in pp_check with some models

### ISSUE THREAD

**Issue by fseaton** [paul-buerkner/brms#1007]
Hello,

With my model the pp_check function with type = "stat_grouped" is returning the wrong group statistics for the data. I think this is because the get_y function is being used to return the response and it isn't always in the same order as the data.

Reproducible example:
```
library(brms)
set.seed(3)
x <- gl(3,100)
y <- rnorm(300, as.numeric(x), 0.2)
gr <- as.character(rep(1:100, 3))

dat <- data.frame(x,y,gr)
dat$x_num <- as.numeric(dat$x)

mod <- brm(y ~ x + ar(time = x_num, gr = gr), data = dat)
pp_check(mod, "stat_grouped", group = "x")

```

**Comment by paul-buerkner** [comment]
Thanks! This is now fixed on github.
