### ISSUE TITLE
brms seem to compile Stan but never fits the model

### ISSUE THREAD

**Issue by KennethEnevoldsen** [paul-buerkner/brms#1008]
Hi had the issue that a fit a BRMS model and it does not crash but it also does not produce a result as you see in the following:
```r
> # retry again
> library(brms)
> formula <- brmsformula(resonance ~  novelty + (1|news))
> bprior <- c(prior(student(3, 0, 1), class = b, coef=novelty),
+             prior(student(3, 0, 1), class = Intercept)) # set some priors
> fit <- brm(formula,
+            prior = bprior,
+            data = res, 
+            chains = 2, cores = 2, iter = 4000)
Compiling Stan program...
> fit # does not work
Error: object 'fit' not found
```

I have tested Rcpp works using
```
Rcpp::sourceCpp('helloworld.cpp') # work
```
where `helloworld.cpp` is the following file
```
#include <RcppArmadillo.h>   

// [[Rcpp::depends(RcppArmadillo)]]

// [[Rcpp::export]]
void hello_world() {
  Rcpp::Rcout << "Hello World!" << std::endl;  
}

// After compile, this function will be immediately called using
// the below snippet and results will be sent to the R console.

/*** R
hello_world() 
*/
```

Similarly, have I tested that stan words using the following code
```r
library(rstan)

schools_data <- list(
  J = 8,
  y = c(28,  8, -3,  7, -1,  1, 18, 12),
  sigma = c(15, 10, 16, 11,  9, 11, 10, 18)
)
fit1 <- stan(
  file = "schools.stan",  # Stan program
  data = schools_data,    # named list of data
  chains = 4,             # number of Markov chains
  warmup = 1000,          # number of warmup iterations per chain
  iter = 2000,            # total number of iterations per chain
  cores = 1,              # number of cores (could use one per chain)
  refresh = 0             # no progress shown
)

fit1 # it works
```

where `schools.stan` is the following:
```
data {
  int<lower=0> J;          // number of schools 
  real y[J];               // estimated treatment effects
  real<lower=0> sigma[J];  // s.e. of effect estimates 
}
parameters {
  real mu; 
  real<lower=0> tau;
  vector[J] eta;
}
transformed parameters {
  vector[J] theta;
  theta = mu + tau * eta;
}
model {
  target += normal_lpdf(eta | 0, 1);
  target += normal_lpdf(y | theta, sigma);
}
```

Some specs:
- MacOS Catalina 10.15.6
- R version 4.0.2 (2020-06-22)
- stan installed using `remotes::install_github("stan-dev/rstan", ref = "develop", 
                        subdir = "rstan/rstan", build_opts = "")` following the [stan install guide](https://github.com/stan-dev/rstan/wiki/Installing-RStan-from-source-on-a-Mac)
- rcpp installed using `install.packages(c('Rcpp', 'RcppArmadillo'))` following [this guide](https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos/)

**Comment by torkar** [comment]
@KennethEnevoldsen , could you post this on: https://discourse.mc-stan.org and in the meantime close this report? Please also produce a minimum example we can use to try this out on our laptops (I have basically the same setup as you :)

**Comment by KennethEnevoldsen** [comment]
Well seems like trying to reduce it to a minimal example I found the culprit. A misspelling of `student_t` as `student`. Why this cause the error I have no idea, but fixing it does solve the issue.

You would have expected it to raise an error something like this (which does happen some times not always, haven't been able to figure out why yet)
```
Compiling Stan program...
SYNTAX ERROR, MESSAGE(S) FROM PARSER:
No matches for: 

  student_lpdf(real, int, int, int) 
(...)
```

**Comment by KennethEnevoldsen** [comment]
@torkar would you still want me to post this on discourse?

**Comment by torkar** [comment]
No need to now :) Just close this report. Thanks!
