### ISSUE TITLE
improvements for threading with mixed models

### ISSUE THREAD

**Issue by wds15** [paul-buerkner/brms#1011]
As already discussed, it would be better for the performance of threading models with random effects to slice over the random effect of a group level.

Below is some example model and code which demonstrates how that could be coded up. The code is written in a hopefully generic enough way that it can be fit into the brms code generation machinery.

Essentially the code resorts the entire data set along one grouping level and then the `reduce_sum` is done over levels of the grouping factor instead of data rows.

The resorting seems to be beneficial for single core performance as well (at least in this examples, but that's not huge though still there is a speedup).

```R
> ## base model brms, 1 core
> stime1b
   user  system elapsed 
180.172   0.614 180.434 
> ## optimized model, 1 core
> stime1c
   user  system elapsed 
167.554   0.473 168.505 
> ## base model brms, 3 cores
> ptime1b
   user  system elapsed 
324.204   2.862 109.954 
> ## optimized model, 3 core
> ptime1c
   user  system elapsed 
282.691   1.989  95.492 
> ## base model brms speedup 1 core vs 3 cores
> stime1b / ptime1b
    user   system  elapsed 
2.142594 1.731050 1.640995 
> ## optimized model speedup 1 core vs 3 cores
> stime1c / ptime1c
    user   system  elapsed 
2.235256 1.905097 1.764598 
> ## optimized model 3 core vs 1 core base model
> stime1b / ptime1c
    user   system  elapsed 
2.475910 1.991306 1.889520 
> 
```

[horseshoe-scale_R.txt](https://github.com/paul-buerkner/brms/files/5318580/horseshoe-scale_R.txt)

**Comment by paul-buerkner** [comment]
Thank you! As you know I have some reservations with regard to this approach but perhaps they are unwarrented or we can find good solutions. In the next couple of days, I will write down all my thoughts and potential problems I see on the way towards this feature so that we can work together to resolve them.

**Comment by wds15** [comment]
Interesting - I just reran the above benchmark with 2.26.0 which introduce some improvements to reduce_sum which help to get down the overhead brms is suffering from due to not using the slicing argument. Looks as if these improvements really made a difference (at least for this model):

```R
> ## base model brms, 1 core
> stime1b
   user  system elapsed 
207.954   0.678 208.108 
> ## optimized model, 1 core
> stime1c
   user  system elapsed 
204.968   0.802 205.962 
> ## base model brms, 3 cores
> ptime1b
   user  system elapsed 
351.927   3.672 119.975 
> ## optimized model, 3 core
> ptime1c
   user  system elapsed 
322.050   3.728 110.167 
> ## base model brms speedup 1 core vs 3 cores
> stime1b / ptime1b
    user   system  elapsed 
2.138378 1.591372 1.734595 
> ## optimized model speedup 1 core vs 3 cores
> stime1c / ptime1c
    user   system  elapsed 
2.275799 1.727044 1.869544 
> ## optimized model 3 core vs 1 core base model
> stime1b / ptime1c
    user   system  elapsed 
2.247637 1.656521 1.889023 
> 
```

So the speed gain by manually tuning the code is not really large here. I will try once more with an intercept + slope model to see what happens then.

FYI: In 2.26.0 we avoid copying shared arguments *per partial sum evaluation* and instead copy the shared arguments *per thread using them* (while allowing each thread to recycle them as needed for many partial sum evals).

**Comment by paul-buerkner** [comment]
These are very encouraging results! And great solution to the problem from within Stan!

**Comment by wds15** [comment]
Indeed, the 2.26.0 version improves things. Now I went back to the example and checked details. The simulated data set counted 10^4 data rows and I simulated 10^3 groups (so 10 data rows per random effect). If we now bump up the number of groups to fit to 5k (2 data rows per random effect), then we stress things more and the tuned model gains again more advantage:

```R
> ## base model brms, 1 core
> stime1b
   user  system elapsed 
300.324   1.186 301.837 
> ## optimized model, 1 core
> stime1c
   user  system elapsed 
295.953   0.822 295.824 
> ## base model brms, 3 cores
> ptime1b
   user  system elapsed 
619.854  10.654 253.871 
> ## optimized model, 3 core
> ptime1c
   user  system elapsed 
510.929   9.468 208.726 
> 
> ## base model brms speedup 1 core vs 3 cores
> stime1b / ptime1b
    user   system  elapsed 
1.673321 1.372899 1.188938 
> ## optimized model speedup 1 core vs 3 cores
> stime1c / ptime1c
    user   system  elapsed 
1.874862 1.369613 1.417284 
> ## optimized model 3 core vs 1 core base model
> stime1b / ptime1c
    user   system  elapsed 
1.902745 1.460459 1.446092 
> 
```

So it looks as if 2.26.0 did definitely help here, but there is still more to get for problems with many random variables.

**Comment by paul-buerkner** [comment]
After further in-person discussing today, I decided to close this issue. I agree that they speed improvement is relevant but the amount of work it would require and the resulting maintenence burden is not worth it at the moment.
