### ISSUE TITLE
Treat random intercept/effects as "fixed" effects in conditional_effects 

### ISSUE THREAD

**Issue by StaffanBetner** [paul-buerkner/brms#1012]
In some cases I use random intercepts for the pooling properties, instead of no pooling which is the effect of the standard fixed effect approach, so in these cases it would be useful to be able to treat random intercept/effects as "fixed" effects in conditional_effects.

**Comment by paul-buerkner** [comment]
Can you elaborate at bit more. I am not sure what you mean.

**Comment by StaffanBetner** [comment]
Easier to describe with an example.

Model setup:
```
lme4::sleepstudy -> sleepstudy
sleepstudy_brm <- brm(data=sleepstudy, formula = Reaction ~ 1+Days+(1+Days|Subject), backend="cmdstanr")
sleepstudy_brm_fixed <- brm(data=sleepstudy, formula = Reaction ~ 1+Days+Days*Subject+Subject, backend="cmdstanr")
```

```
sleepstudy_brm %>%  conditional_effects(effect="Days:Subject")
sleepstudy_brm_fixed %>% conditional_effects(effect="Days:Subject")
```

The first plotting line gives the error (as expected):
"Error: All specified effects are invalid for this model.
Valid effects are (combinations of): 'Days'"

And the second line gives the interaction plot:
![image](https://user-images.githubusercontent.com/8129424/95334070-e9cfb480-08ad-11eb-9329-04418253d5e6.png)

It would be useful with an argument to conditional_effects, say something like random_as_fixed, that makes "Days:Subject" a valid effect to plot for the model `sleepstudy_brm`. 

I know it is possible with something like
```
sleepstudy_brm %>%
  conditional_effects(effect="Days", 
                      conditions = data.frame(Subject = sleepstudy$Subject), 
                      re_formula = NULL)
```

but I cannot figure out a way for conditional_effects to plot random intercepts.

**Comment by StaffanBetner** [comment]
Fantastic, will try out!

**Comment by StaffanBetner** [comment]
Doesn't seem to work for models with only random intercepts. 

Example:
```
sleepstudy_brm_rintercept <- brm(data=sleepstudy, formula = Reaction ~ (1|Subject), backend="cmdstanr")

sleepstudy_brm_rintercept %>% conditional_effects(effect = "Subject", re_formula = NULL)
```
Error: 
"Error: All specified effects are invalid for this model.
Valid effects are (combinations of): ''"

**Comment by paul-buerkner** [comment]
Thanks. Should be fixed now.
