### ISSUE TITLE
bind() fails with long variables names

### ISSUE THREAD

**Issue by JackCaster** [paul-buerkner/brms#1016]
While creating a dirichlet regression, I noticed that `bind()` fails if the response variables have long names (or there are too many variables).

For example, this will fail:
```
bf(bind(very_long_variable_name_0, 
        very_long_variable_name_1, 
        very_long_variable_name_3, 
        very_long_variable_name_4) ~ 0)
```
with the error:
```
Error in parse(text = str_lhs) : <text>:2:0: unexpected end of input
1: bind(very_long_variable_name_0, very_long_variable_name_1, very_long_variable_name_3, 
```
while this will work:
```
 bf(bind(variable_name_0, 
         variable_name_1, 
         variable_name_3, 
         variable_name_4) ~ 0)
```
I am using `brms` (v. 2.13.3) and Windows 10.

**Comment by paul-buerkner** [comment]
Thanks. Shoud now be fixed.

**Comment by JackCaster** [comment]
Hej Paul,
I updated brms to master. Now, `bind()` does not complain but `bmrs` does. For example:
```
f <- bf(bind(very_long_variable_name_0, 
        very_long_variable_name_1, 
        very_long_variable_name_3, 
        very_long_variable_name_4) ~ 0)

get_prior(
  f,
  data = data.frame(
    'very_long_variable_name_0' = 0,
    'very_long_variable_name_1' = 0,
    'very_long_variable_name_3' = 0,
    'very_long_variable_name_4' = 0
  )
)
```
results in
```
Error in bind(very_long_variable_name_0, very_long_variable_name_1, very_long_variable_name_3,  : 
  could not find function "bind"
```
Am I missing something?

**Comment by paul-buerkner** [comment]
Use mvbind instead of bind.

JackCaster <notifications@github.com> schrieb am Do., 15. Okt. 2020, 17:10:

**Comment by JackCaster** [comment]
That's so weird. I reverted to brms 2.13.3 and it fails there too (cannot find `bind`). It was working before with short variable names.

Anyhow, is `mvbind` the right way for the dirichlet family distribution? It does not seems to be equivalent to bind as it creates a formula for each response variable (here https://discourse.mc-stan.org/t/dirichlet-regresion-using-brms/8591/2 you were suggesting to use `bind` for dirichlet regression). Also, I get the error `Error: At least 2 response categories are required.` if I use `mvbind`

**Comment by paul-buerkner** [comment]
For dirichlet, the right way would be `cbind` theoretically, but this is still in use for multivariate models although deprecated. Rather, go for the workaround of, say,

```
bind <- cbind
```

and then use bind.

**Comment by JackCaster** [comment]
It works! Thanks for help and patience
