### ISSUE TITLE
Specifying order restrictions of random effects

### ISSUE THREAD

**Issue by StaffanBetner** [paul-buerkner/brms#1018]
For some weakly identifiable models (such as IRT/factor/scaling models) it would be useful to be able to specify some order restrictions on random effects, typically to avoid sign invariance. 

A case where this is applicable is outlined here: https://discourse.mc-stan.org/t/non-linear-formula-trick-for-restriction-on-sign/18155

**Comment by paul-buerkner** [comment]
So you mean to avoid explicite non-linear transformations such as `exp(x)`?

**Comment by StaffanBetner** [comment]
No, e.g. in cases we have an or several items in a IRT/factor model where the "factor loading" with the response differs in sign. That doesn't include the case in the Discourse thread, but it is one example where it is applicable.

**Comment by paul-buerkner** [comment]
So you would want to hard-code the sign of the factor loading into the model? Can you please clarify with some math equation or something else that would help me better understand the situation?

**Comment by StaffanBetner** [comment]
Sure. I can describe the model I want to use.

The response $y_{ij}$ is binary data of whether a party $i$ is tagged with a ideology $j$.

The model is $logit(Pr(y_{ij}=1)) = \alpha_j-\beta_j(o_j-x_i)^2$, so the logit of the response is modeled linearly as a function of the distance in the latent space between the ideology tag and the party. 

The priors and restrictions for identification:
$o \sim Normal(0,1)$
$x \sim Normal(0,1)$
$\beta > 0$
$o_{\text{conservatism}}>o_{\text{socialism}}$

In the Discourse post I specify the model like this (without priors):

**Comment by StaffanBetner** [comment]
Sure. I can describe the model I want to use.

The response $y_{ij}$ is binary data of whether a party $i$ is tagged with a ideology $j$.

The model is $logit(Pr(y_{ij}=1)) = \alpha_j-\beta_j(o_j-x_i)^2$, so the logit of the response is modeled linearly as a function of the distance in the latent space between the ideology tag and the party.

The priors and restrictions for identification:
$o \sim Normal(0,1)$
$x \sim Normal(0,1)$
$\beta > 0$
$o_{\text{conservatism}}>o_{\text{socialism}}$

In the Discourse post I specify the model like this (without priors):
```
nl(binary ~ a + exp(b)*(o-x)^2,
a ~ 1 + (1|ideology), # ideology tag specific constant (prevalence)
b ~ 1 + (1|ideology), # ideology tag discrimination parameter
o ~ (1|ideology), # ideology tag location
x ~ (1|party)) # party location
```

The SD for o and x can be set to 1 with brms, that's simple, but the one restriction of order that is needed to get a non-mirrored posterior for o and x, $o_{\text{conservatism}}>o_{\text{socialism}}$ can't be set in a nice way, I think.

I think one way to formulate it in some kind of pseudo math code would be something like:
$o_{\text{conservatism}} = o_{\text{socialism}} + exp(delta), delta ~ Normal(0,1)$, or a flat prior for delta

**Comment by paul-buerkner** [comment]
I see. Thanks for the explanation. I am afraid, this feature is too specific to be implemented in brms, but I would agree that using the approach you highlighted at the end could be a viable solution, that can even be writting directly in brms' non-linear syntax already.

**Comment by StaffanBetner** [comment]
I agree it might be too specific, however, I think being able to expose a specific random effect in a non-linear formula should be a suitable alternative, As in #931. Is this possible at this moment?

**Comment by paul-buerkner** [comment]
if a non-linear parameter just contains the random effect, that you can expose it.
