### ISSUE TITLE
pars incorrectly parsed in mcmc_plot

### ISSUE THREAD

**Issue by andymilne** [paul-buerkner/brms#1019]
Simple repro

```
fit <- brm(count ~ (zAge + zBase) * Trt,
            data = epilepsy, family = poisson())
mcmc_plot(fit, pars = c("b_Trt1", "b_zBase", "b_zAge:Trt1"))
```
Note that the plot incorrectly includes ` b_zBase:Trt1`

**Comment by paul-buerkner** [comment]
`pars` is evaluated as a vector of regular expressions unless `fixed = TRUE`

**Comment by andymilne** [comment]
Perhaps this could be mentioned directly in the `pars` section of the help for `mcmc_plot`?

**Comment by paul-buerkner** [comment]
I will check the doc.
