### ISSUE TITLE
Off estimations from Zero_Inflated_Poisson models

### ISSUE THREAD

**Issue by andechner** [paul-buerkner/brms#102]
Hello,

First, thanks for the great package. I am writing because I have been trying to use the zero_inflated_Poisson models but for some reason the results are very off when compared with the results obtained from other software/packages using exactly the same data-set and non-informative priors. Any idea why it may be happening?. Thanks! A.

**Comment by paul-buerkner** [comment]
Can you please show me the code you used to fit the model with brms?

**Comment by andechner** [comment]
cer.zi.l <- brm(cer~natcov+disroad, data=fdata, family ="zero_inflated_poisson",
                set_prior("normal(0,10)"), chains = 3, iter=10000)

**Comment by paul-buerkner** [comment]
I recommend that you read the details section of help(brm). There you find an explanation of how to correctly specify zero-inflated models. For your data, the model should look like this:

```R
cer.zi.l <- brm(cer~0 + trait + trait:(natcov+disroad), data=fdata, family ="zero_inflated_poisson",
set_prior("normal(0,10)"), chains = 3, iter=10000)
```

**Comment by andechner** [comment]
Solved :) Thank you very much!, sorry for not heading to the help section first. Thanks again! A.

**Comment by paul-buerkner** [comment]
You are welcome! :-)
