### ISSUE TITLE
extending pp_average to work with posterior_epred

### ISSUE THREAD

**Issue by JakeJing** [paul-buerkner/brms#1022]
I am using `pp_average` to get the posterior predictive values across different models via Bayesian model stacking. But it seems that `pp_average` calls `posterior_predict` by default, which makes it hard to specify other dependent parameters in a distributional model. 

It would be better to extend `pp_average` to work with `posterior_epred` as well, which will allow, for example, predictions of `sigma` to be averaged in a normal regression. Thanks!

**Comment by paul-buerkner** [comment]
I realized this is already possible via the `method` argument. Just the doc wasn't up to date because it said `pp_expect` rather than `posterior_epred` but the latter worked already. Closing this issue.
