### ISSUE TITLE
Non-conformable arrays error for `brms`-generated nonlinear model

### ISSUE THREAD

**Issue by tomwallis** [paul-buerkner/brms#103]
Hi, 

I'm trying to fit a nonlinear model with the `brm` function. The model compiles fine, then I get the following error:

```r
Error: Error in log(x) - m: non-conformable arrays
```

`x` is a variable (found in the data frame passed to `brm` and `m` is a model parameter. I'm afraid the model is a bit complicated to produce a minimal working example, so I'm sending Paul some data and code off Github.

In the `.stan` file generated by `brm`, where the nonlinear predictor is computed, the covariate `x` is produced by an indexed matrix:

`C[n, 1]`

But there's only one covariate in the model. So I think this returns a matrix whereas

`eta_m[n]`

is a scalar (or length one vector) -- and hence non-conformable.

**Comment by paul-buerkner** [comment]
Thanks for reporting this issue. Whatever it was, it appears to work with the current dev version of brms from github. Can you see if it also works for you?

**Comment by paul-buerkner** [comment]
Ahh now I get the error. It happens when you try to call LOO, not at the time of fitting the model, right?

**Comment by tomwallis** [comment]
Ah, could be. I'm not sure sorry -- I was running it on a command line interface to a workstation, so the location of the error was ambiguous.

**Comment by paul-buerkner** [comment]
The problem was a bug in the pointwise evaluation (automatically activated for large models) of the non-linear predictor. I have already fixed it, but need to test it more thoroughly. I will upload the fix on github tomorrow.

**Comment by tomwallis** [comment]
Awesome, thanks Paul.

**Comment by paul-buerkner** [comment]
It should be working correctly now.

**Comment by tomwallis** [comment]
I get the following error when installing the dev version from github:

```r
install_github("paul-buerkner/brms")
...
Error : 'smooth2random' is not an exported object from 'namespace:mgcv'
Error : unable to load R code in package ‘brms’
ERROR: lazy loading failed for package ‘brms’
```

**Comment by paul-buerkner** [comment]
Please install the latest version of mgcv (1.8-13)

**Comment by tomwallis** [comment]
That seems to be fixed, apart from the following warning messages:

```r
Warning messages:
1: Rows containing NAs were excluded from the model 
2: Rows containing NAs were excluded from the model 
3: Rows containing NAs were excluded from the model 
4: Rows containing NAs were excluded from the model 
```

I'm not sure what could be causing this, but I can investigate further.

Thanks Paul.

**Comment by paul-buerkner** [comment]
If your dataset has rows with NAs in relevant variables, they will be removed. This is no new behavior, just the warning is new.
