### ISSUE TITLE
Removal of group-level samples after fitting to reduce model size

### ISSUE THREAD

**Issue by kauttoj** [paul-buerkner/brms#1031]
I know it's possible to omit saving group-level parameters when fitting a model by setting "_save_pars = save_pars(group = FALSE)_", however then one cannot make predictions for new subjects with option "_allow_new_levels=TRUE_".

Is there way to remove group-level parameters AFTER model has been fitted (after predictions are done)? If there is no function for that, is there some hack?

My problem is that I have a huge model (~10GB model file) with lots of group-levels terms. I would like to make predictions, but also use **emmeans** package. If I set "_save_pars(group = FALSE)_", I can use the latter, but not the first. If I set "_save_pars(group = TRUE)_", I can use the first one, but not the latter (out of memory). If I can remove group-level terms after fitting, I could probably do both.

**Comment by paul-buerkner** [comment]
Hmm. emmeans does not use the random effects I think. So there must be something else in the process that accidentally accesses the random effects and leads to the memory problems. Let me check.

**Comment by paul-buerkner** [comment]
I don't really see where the memory problem comes from. Can you run the code through debug mode and tell me where it fails for you?

**Comment by kauttoj** [comment]
It's difficult to debug my huge model as I can only handle it with cluster, but here is an example that might help to demonstrate and replicate the problem:

```
require(profmem)
require(emmeans)
require(brms)

data("rent99", package = "gamlss.data")
rent99$yearc = scale(rent99$year) # convert to numeric
fit_rent <- brm(rentsqm ~ area*location*yearc + (location|district), data = rent99,chains = 4, cores = 4,iter = 4000,seed=1)
fit_rent_small <- brm(rentsqm ~ area*location*yearc + (location|district), data = rent99,chains = 4, cores = 4,save_pars = save_pars(group = FALSE),seed=1,iter=4000)

meanstest_full <- profmem({
  emmeans(fit_rent,pairwise ~ location)
})
meanstest_small <- profmem({
  emmeans(fit_rent_small,pairwise ~ location)
})
trendstest_full <- profmem({
  emtrends(fit_rent,pairwise ~ location,var="yearc")
})
trendstest_small <- profmem({
  emtrends(fit_rent_small,pairwise ~ location,var="yearc")
})

object.size(fit_rent) = 133269792 # 38x compared to smaller model
object.size(fit_rent_small) = 3502384
total(meanstest_full) = 4290941096 # 210x compared to smaller model, 32x compared to model itself
total(meanstest_small) = 20390208 # 6x compared to model itself
total(trendstest_full) = 8554182232 # 312x compared to smaller model, 64x compared to model itself
total(trendstest_small) = 27423696 # 8x compared to model itself

```
Above results were obtained with R 4.0.2 (Win10) and emmeans_1.5.2-0010001, profmem_0.5.0, brms_2.14.0. Results for both full and small model are the same, as they should. 

So the memory usage of **emmeans** with **brms** does not seem optimal. Removal of group-level data might be a fast (temporal) solution for this.

**Comment by paul-buerkner** [comment]
Thanks! I don't want to implement a temporal solution but rather fix the issue right away. At the moment, I don't see why the object becomes so big but perhaps @rvlenth has some ideas?

**Comment by rvlenth** [comment]
I do have an idea, in fact. I became aware fairly recently that the `dffun` slot in the object returned by `emmeans` carries with it the environment of whatever is in the `emm_basis` method. That can be quite bulky and it is unnecessary. In the latest CRAN version of **emmeans** (version 1.5.2-1), I added a chaser after that method is called that sets `environment(dffun) <- baseenv()`.

So one thing I learned, in general, is that anytime you define a function as, say, part of an object, you are really creating a closure with a potentially huge environment attached to it. Seems to me this could cause a whole lot of R things to blow up, when in the hands of relatively naive programmers like me (I'm slightly less so, now).

Anyway, I think it's possible (not guaranteed) that you can alleviate the object-size issue if you install the latest **emmeans**. It of course wouldn't hurt to add the above environment assignment to `emm_basis.brmsfit`.

**Comment by paul-buerkner** [comment]
Thank you so much! Added the environment assignment to the brms github version.

**Comment by paul-buerkner** [comment]
@kauttoj can you check if that solves the issue?

**Comment by kauttoj** [comment]
Ok, thanks. I updated to 4.0.3 with emmeans_1.5.2-1 (from CRAN) and brms_2.14.5 (from github, few minutes ago). Re-ran above code and got:

```
object.size(fit_rent) = 133787552
object.size(fit_rent_small) = 4020176
total(meanstest_full) = 6147989112
total(meanstest_small) = 30149392
total(trendstest_full) = 12272128872
total(trendstest_small) = 40478472
```
which is very similar to my previous results. So it seems not fixed yet.

**Comment by rvlenth** [comment]
Hmmm, I wonder if the `call` slot is bloated. This could happen if somehow the elements of the model call got evaluated somewhere along the line. What happens if you try, e.g.,
```r
meanstest_full@model.info$call <- NULL
```

**Comment by kauttoj** [comment]
Where I should put that line exactly?

In the meantime, I did an ugly hack to get rid of all non-population samples/parameters from **brms** object. It's based on Shredder package, which can do most of the work:

```
# first load two files from Shredder package:
source("stan_utils.R")
source("utils.R")
# function to retain population variables (modified from stan_select.R)
reduce_model <- function(object){
  #on.exit({clear_summary(object$fit)},add = TRUE) # does not seem to have any effect...
  all_pars <- union(object$fit@sim$pars_oi,object$fit@sim$fnames_oi)
  assign('pars',all_pars,envir = pars_env)
  pars=c()
  for (x in object$fit@sim$pars_oi) {
    if (x == "b" || startsWith(x,"b_")) pars = c(pars,x) # keep population params
  }
  stopifnot(length(pars)>0,"no parameters!")
  pars <- unique(pars)
  fnames_object <- find_fnames(object$fit,pars)
  object$fit <- fnames_object$object
  pars <- fnames_object$pars
  object$fit@sim$pars_oi <- intersect(object$fit@sim$pars_oi,pars)
  object$fit@sim$dims_oi <- object$fit@sim$dims_oi[object$fit@sim$pars_oi]
  object$fit@sim$n_flatnames <- length(object$fit@sim$fnames_oi)
  object$fit@model_pars <- intersect(object$fit@model_pars,pars)
  object$fit@inits <- purrr::map(object$fit@inits,.f=function(x,y) x[y], y = object$fit@model_pars)
  pars <- intersect(pars,names(object$fit@par_dims))
  stopifnot(length(pars)>0,"no parameters!")
  object$fit@par_dims <- object$fit@par_dims[pars]
  this <- grep(paste0(pars,collapse = '|'),object$fit@sim$fnames_oi,value = TRUE)
  new_samples <- purrr::map(object$fit@sim$samples,.f=function(x,y) x[y], y = this)
  for(i in seq_len(length(new_samples)))
    attr(new_samples[[i]],'sampler_params') <- attr(object$fit@sim$samples[[i]],'sampler_params')
  object$fit@sim$samples <- new_samples
  object
}
mymodel = reduce_model(mymodel) # a reduced model that works with emmeans and emtrends
```

I tested this with above example and also with my huge model and it works (faster, no memory issues and same results). Wouldn't use that butchered model with anything else though as I could have broken something in the process...

**Comment by paul-buerkner** [comment]
You can put `meanstest_full@model.info$call <- NULL` before checking the object size and see if that reduces the size.

**Comment by paul-buerkner** [comment]
@kauttoj did you find out where the large object size came from, that is, where in the object the apparently redundant stuff was stored?

**Comment by paul-buerkner** [comment]
I am closing this issue now but feel free to reopen it when there are any updates on where the large model size comes from in your example.
