### ISSUE TITLE
set_rescor not working?

### ISSUE THREAD

**Issue by strengejacke** [paul-buerkner/brms#1035]
Hi Paul,
I get following error:

``` r
library(brms)
#> Lade nötiges Paket: Rcpp
x <- rnorm(10, 0)
b <- runif(2)
s <- ifelse(diag(2) == 0, 0.23, 1)
er <- cbind(rnorm(10, 0, s), rnorm(10, 0, s))
y <- apply(t(b), 2, `*`, x) + er
d <- data.frame(y1 = y[,1], y2 = y[,2], x)
m1 <- brm(mvbind(y1, y2) ~ 1 + x + set_rescor(TRUE), data = d, chains = 2, iter = 500)
#> Setting 'rescor' to TRUE by default for this model
#> Warning: In the future, 'rescor' will be set to FALSE by default for all models.
#> It is thus recommended to explicitely set 'rescor' via 'set_recor' instead of
#> using the default.
#> Error in model.frame.default(all_terms, data, na.action = na.pass, drop.unused.levels = drop.unused.levels): Variablenlängen sind unterschiedlich (gefunden für 'set_rescor(TRUE)')
```

<sup>Created on 2020-11-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I came across this issue because brms now recommends setting `rescor` explicitely:

> Warning: In the future, 'rescor' will be set to FALSE by default for all models.
> It is thus recommended to explicitely set 'rescor' via 'set_recor' instead of
> using the default.

(`set_recor` is a typo, shouldn't it be `set_rescor`?)

**Comment by paul-buerkner** [comment]
You need to specify rescor differently, not directly within the formula. Instead, for example:

```
bf(mvbind(y1, y2) ~ 1 + x) + set_rescor(TRUE)
```

I have also fixed the typo.

**Comment by strengejacke** [comment]
Great, thanks!
