### ISSUE TITLE
varying truncation points

### ISSUE THREAD

**Issue by Atan1988** [paul-buerkner/brms#104]
Hi Paul,

Thank you for this awesome project that made learning and applying stan easier. My analyses are mostly based on insurance data, affected by sources of truncation(deductibles) and censoring(policy limit). Within the brm framework, is it possible to specify vector lower bounds(various deductibles) of the trunc function?

Thanks,
Allen

**Comment by paul-buerkner** [comment]
You mean that different observations may have different truncation points? This is not yet possible, but I will be implementing it in the future.

**Comment by Atan1988** [comment]
Yes, exactly! Policy deductibles vary from 0 - 250K in general.  Is it possible to use brms::stancode to creat a model file that's almost there, using yi | trunc(lb = N, ub = M) + cens(censored)~ predictors, and then modify the model file to allow for varying truncation points(it seems possible within the stan language)? I am new to Stan, and I find that brms using the lme4-like formula builds an important and amazing bridge. Thank you again for this fantastic project!

**Comment by paul-buerkner** [comment]
Specifying varying truncation points should now be possible in the dev version of brms. Just pass variables of your dataset, which contain the truncation points, to the `trunc` function. Feel free to close this issue after verifying that it is also working for you.

**Comment by Atan1988** [comment]
I have tested the develop version, and it works nicely! Thanks, Paul!

**Comment by paul-buerkner** [comment]
Great! Thanks for testing!
