### ISSUE TITLE
Problem loo, moment_matching= TRUE

### ISSUE THREAD

**Issue by quantumlinguist** [paul-buerkner/brms#1049]
I have the following model, where Transitivity05 is a continous variable and the rest are all binary predictors. The dependent variable is also binary.

model2_trans_PART= brm(Case~Transitivity05+ Causative+Tense+
Person+NumberSubj+Group+
(1+AnimacyObj+Causative|Verb), data=training,
family=bernoulli(link="logit"),iter=6000,
cores=4, seed=123, save_all_pars = TRUE,
control = list(max_treedepth = 15),
prior=set_prior("cauchy(0,2.5)", class="b")+
set_prior("cauchy(0,10)", class="Intercept"))

I calculated loo and I got a warning that there were 9 observations with a pareto k higher than 0.7 so I tried using moment match. However, when I do that, I get the following error:

loo_trans_PART= loo(model2_trans_PART, cores= 7, moment_match = TRUE)
Error : $ operator is invalid for atomic vectors
In addition: Warning message:
In parallel::mclapply(X = I, mc.cores = cores, FUN = function(i) loo_moment_match_i_fun(i)) :
all scheduled cores encountered errors in user code
Error: Moment matching failed. Perhaps you did not set 'save_all_pars' to TRUE when fitting your model?

savel_all_pars is set to TRUE so that is not the problem. I then ran loo with only one core and got this error:

loo_trans_PART= loo(model2_trans_PART, cores=1, moment_match = TRUE)
Error in .update_pars(x, upars = upars, ...) :
length(new_samples) == nrow(pars) is not TRUE
Error: Moment matching failed. Perhaps you did not set 'save_all_pars' to TRUE when fitting your model?

I'm using Brms version 2.13.5 and R version 4.0.3, loo version 2.3.1.9000 on MacOs 10.15.6

Thanks.

**Comment by paul-buerkner** [comment]
Can you try it out with the latest brms version from either CRAN or github?

**Comment by quantumlinguist** [comment]
Hi, yeah that worked thanks!

**Comment by paul-buerkner** [comment]
Ok. Closing this now.
