### ISSUE TITLE
brms::brm output: element "version" has useless nestings

### ISSUE THREAD

**Issue by alesantuz** [paul-buerkner/brms#1054]
Windows 10 x64 build 19042
R version 4.0.3 (2020-10-10)
brms version 2.14.4
rstan 2.21.2
stanHeaders 2.21.0.6

Any call of brms::brm such as those in the examples:

```
fit2 <- brm(rating ~ period + carry + cs(treat),
            data = inhaler, family = sratio("logit"),
            prior = set_prior("normal(0,5)"), chains = 2)

fit3 <- brm(time | cens(censored) ~ age * sex + disease + (1|patient),
            data = kidney, family = lognormal())

...
```

returns deep nesting of the element "version" in the resulting list due to utils::packageVersion(). This only takes 1792 more bytes of allocated memory, but I thought it made sense to report it. A naive solution could be to exchange, in [brmsfit-class.R](https://github.com/paul-buerkner/brms/blob/3b8727b4f76be32f8e825e6908d87655763742d3/R/brmsfit-class.R)
```
version <- list(
    brms = utils::packageVersion("brms"),
    rstan = utils::packageVersion("rstan"),
    stanHeaders = utils::packageVersion("StanHeaders")
  )
```
with
```
version <- list(
    brms = as.character(utils::packageVersion("brms")),
    rstan = as.character(utils::packageVersion("rstan")),
    stanHeaders = as.character(utils::packageVersion("StanHeaders"))
  )
```
Didn't want to create a new pull request for such a small thing that might be well known anyway to the developer(s).

**Comment by paul-buerkner** [comment]
Thanks! Can you explain where this nesting is coming from? I am not sure I understand right now, why storing `utils::packageVersion()` results directly is problematic.

**Comment by alesantuz** [comment]
When I call `utils::packageVersion("brms")`, the output is `‘2.14.4’`, but class is `"package_version" "numeric_version"`. So if I try to assign `test <- utils::packageVersion("brms")`, `test` is a list of 1, but with multiple nestings. Its `object.size()` is 424 bytes. However, `test <- as.character(utils::packageVersion("brms"))` is only 112 bytes, since this is now an object of class `"character"`. Honestly I don't know why this happens, but it seems that the issue is with storing `utils::packageVersion()` results directly.

This is easily replicable:
```
fit2 <- brm(rating ~ period + carry + cs(treat),
            data = inhaler, family = sratio("logit"),
            prior = set_prior("normal(0,5)"), chains = 2)

fit2$version$brms
[1] ‘2.14.4’

fit2$version$brms[[1]]
[1] ‘2.14.4’

fit2$version$brms[[1]][[1]][[1]][[1]][[1]][[1]][[1]][[1]][[1]][[1]][[1]][[1]][[1]]
[1] ‘2.14.4’

# And so on...
```
Is this understandable? Otherwise sorry if I am not being clear.

**Comment by paul-buerkner** [comment]
Thanks. So this long nesting is basically caused by the `utils::packageVersion()` and is unrelated to brms, right? Does it make sense to ask on R-devel on why this nesting is necessary. I am not sure it causes any issues for brms to be honest as it is just a few more bytes as you say.

**Comment by alesantuz** [comment]
You are right, I was just thinking that allocating those variables as characters would not have impacted the brm function performance, while slightly reducing allocation size.

**Comment by paul-buerkner** [comment]
But it potentially breaks backwards compatibility for anyone having used these version numbers in the current form.

**Comment by alesantuz** [comment]
Absolutely, apologies!

**Comment by paul-buerkner** [comment]
No worries. Thank you for opening this issue and the related discussion.
