### ISSUE TITLE
Error in Setting Priors in Distributional Models

### ISSUE THREAD

**Issue by rosskempner** [paul-buerkner/brms#1055]
Hi, I am using the following distributional model. The code below has the model formula, priors and the prior predictive check code. I may have found a bug in how the priors are set in distirbutional models (although possibly this comes from a misunderstanding of how distributional models work). The picture below will show that the parameters which share part of their name with each other such as b_Intercept  and b_sigma_Intercept  come out completely wrong, so there seems to be an error with specifying priors for distributional models.

Below should be "normal(5.8,0.3)" based on how priors were set.
<img width="673" alt="Screen Shot 2020-12-04 at 10 53 34 AM" src="https://user-images.githubusercontent.com/37561408/101184646-f6a72500-361e-11eb-93be-9eb549645288.png">

Below should be "gamma(0.1,1)" based on how priors were set.
<img width="662" alt="Screen Shot 2020-12-04 at 10 55 41 AM" src="https://user-images.githubusercontent.com/37561408/101184920-4259ce80-361f-11eb-9ca5-45d88f248fcc.png">

```
formula_lognorm2_distributional = bf(formula = reaction_time  ~ 
                        1 + 
                        block_num + 
                        bigram_ideal_first_surprisal  +  
                        (1 + block_num + bigram_ideal_first_surprisal | participant_id),
                        sigma ~ 1 + bigram_ideal_first_surprisal
                      )
get_prior(formula_lognorm2_distributional, family = lognormal(), data = experiment_df)
priors_lognorm2_distributional = c(
    set_prior("normal(5.8,0.3)", class = "Intercept"),
    set_prior("normal(0,0.00000001)", class = "b", coef = "block_num"),
    set_prior("normal(0,1)", class = "b", coef = "bigram_ideal_first_surprisal"),
    set_prior("gamma(0.001,1)", class = "sd", coef = "bigram_ideal_first_surprisal", group = "participant_id"),
    set_prior("gamma(0.00000001,1)", class = "sd", coef = "block_num", group = "participant_id"),
    set_prior("gamma(0.01,1)", class = "sd", coef = "Intercept", group = "participant_id"),
    set_prior("lkj(2)", class = "cor"),
    set_prior("normal(0,0.0000001)", class = "b", coef = "bigram_ideal_first_surprisal", dpar = "sigma"),
    set_prior("gamma(0.1,1)", class = "Intercept", dpar = "sigma")
) 


fit_lognorm2_distributional_prior <- brm(formula = formula_lognorm2_distributional,
  data = experiment_df_remove_low_rts_remove_inaccurate,
  family = lognormal(),
  prior = priors_lognorm2_distributional,
  sample_prior = "only"
)


```

**Comment by paul-buerkner** [comment]
The intercept is not directly paramerized but rather the prior is put on a "centered intercept" by default. See ?set_prior.
