### ISSUE TITLE
Category-specific effects in ordinal regression not found by hypothesis()

### ISSUE THREAD

**Issue by gongcastro** [paul-buerkner/brms#1056]
Hi! I am fitting an ordinal regression model with category-specific effects (brms 2.13.5, R 4.0.2, reprex below). Using `hypothesis()` to test any contrasts involving category-specific, population-level effects throws the error below. Testing the intercepts works fine.

```
d <- data.frame(age = round(runif(50, min = 18, max = 90)),
                response = factor(sample(c(0, 1, 2), size = 50, replace = TRUE), ordered = TRUE))
fit <- brm(response ~ cs(age), data = d, family = acat(link = "logit")) 
hypothesis(fit, "age[1] = 0")
Error: Some parameters cannot be found in the model: 
'b_age'
```
I suspect this is due to `brm()` adding the prefix "bcs_" to `age`, while `hypothesis()` adds "b_" to the parameter name indicated in the input, so no parameters in the model match the input:
```
parnames(fit)
[1] "b_Intercept[1]" "b_Intercept[2]" "bcs_age[1]"     "bcs_age[2]"     "disc"          
[6] "lp__" 
```
Would adding a "bcs_" class to `hypothesis()` solve the issue? Thanks!

**Comment by paul-buerkner** [comment]
Yes, so all you have to do is to change the `class` argument of `hypothesis` to `bcs`. I understand this case is confusing and might be changed in brms 3.0.
