### ISSUE TITLE
Feature: Don't use stored fit when model or data changes

### ISSUE THREAD

**Issue by martinmodrak** [paul-buerkner/brms#1058]
Currently, when using the `file` the argument, the saved fit is always loaded. It could be useful to extend this feature to recognize when model and/or data changes and discard the stored fit if this is the case. This issue describes some design considerations for further discussion. This is based on using a handmade implementation of this for quite a while.

1) Backwards compatibility: The feature should probably use a new argument to avoid changing behavoir of the `file` argument. To me the most sense would be to add something like `file_options` / `file_format` / `file_contents` with allowed values `fit_only` (default) and `everything` (I don't think it makes sense to let users choose to store only data or only model code).

2) How to store model data? I think it is best to not save the full data but instead use something like the `digest` package to compute a hash and store it. I also wouldn't hash the full dataset as passed to the `data` argument, but rather base the refitting on the result of `make_standata`, which let's us easily ignore changes to irrelevant parts of the dataset (and includes all other data passed to the model e.g. via `stanvars`).

3) How to store model specification/code? There are two options: 
   a) We could store the generated Stan code (or its hash but code is small so easy to store/read). This is easy to implement and would always reliably signal a change. Problem is that with updates to `brms` there are often inconsequential changes to the Stan code - so far I've seen whitespace changes, a function that was never called added and a change from `x'` to `transpose(x)`. While the whitespace changes are easy to handle with some simple normalization procedure for the code stirng, I don't think we could reasonably avoid the latter two changes from triggering a refit. Also would probably not work well with the within-chain parallelization support that makes the Stan code change despite the model staying the same.
   b) We could collect all the relevant parameters to `brm` (formula, prior, stanvars, rescor, ....) and store those. This would add some maintanence burden (whenever a new parameter that influences the model is added, it would need to be added into the file cache code). It is also possible that there would be bugs or improvements/changes in brms that would mean that the model sampled actually changed despite the arguments to `brm` being exactly the same. Is it desriable or a problem if we don't trigger a refit in this case?

4) Large models. For large models it might be disadvantegous to store the data/model info in the same file as the fit as when model/data changes the user will unnecessarily load the whole fit only to discard it. It might make sense to store the info in a separate file. But I think here the added complexity does not outweigh the benefits.

What are you thoughts?

**Comment by paul-buerkner** [comment]
Thank you for opening this issue! I may need a few more days before I respond but I haven't overlooked it.

**Comment by martinmodrak** [comment]
Just bumping this up - will be happy to implement this, but wanted to hear your thoughts on the design considerations.

**Comment by paul-buerkner** [comment]
We probably need to compare both the `stancode` and `standata` of the old with the new model to make sure we really have the same model I would say. The problem is that even the same Stan code and the same original data may imply a different model depending on the formula, so generation of `standata` is likely required. All other options create too much of a maintainence burden and are likely unsafe, I would say. So we should really focus on what safely indicates that this is the same model. One could do hashing of course to avoid regenerating stan code and data for the old model, but for the new model, this would be necessary anyway.

Perhaps we should add an option that says whether to use the file from disc intelligentely or always if the file exists.

**Comment by wds15** [comment]
The idea of the issue is great. The pattern I am using myself by now is this:

```R
model <- brm(..., file="model", chains=0)
fit <- update(model, newdata=data, ...)
```

Whenever the `update` is triggering a rebuild, then it's time to remove the model.rds file so that the model compilation caching step is working again.

Is there anything wrong with this approach?

The need to recreate the rds file can then probably be automated by checking if the hash of the stan model changed (I guess).

Since this all happens in user space code - should we add this scheme to the documentation maybe?

**Comment by paul-buerkner** [comment]
Rebuilding is only triggered for stan code changes but a lot of changes in
the data don't imply a change in the stan code.

wds15 <notifications@github.com> schrieb am Mi., 27. Jan. 2021, 15:49:

**Comment by wds15** [comment]
I am not sure I understand. Isn't the whole point about this in that we want to avoid model recompiles? The model recompiles are only needed whenever there is a change in the stan code.

I hope the pattern above is safe to use as I have otherwise misunderstood something.

**Comment by paul-buerkner** [comment]
The point of this issue is to only load a previously saved model if the input (formula, data etc.) stayed the same.

**Comment by martinmodrak** [comment]
@wds15 The point is not to avoid recompilation, but to avoid refitting. However, the current approach (the `file` argument) will not notice that your model/data changed and will happily load an obsolete fit. After spending some time debugging issues that were caused by loading such a bad fit, I wanted a feature that automatically prevents this while still allowing me to cache results of large models. So the use case is different.

**Comment by wds15** [comment]
Ahhh... I misread. To me this was always about avoiding recompiling, but you want more. Sorry for the confusion.

**Comment by paul-buerkner** [comment]
It think standata(fit) should be stable enough for our purposes. Thanks for
working on this issue!

Martin Modrák <notifications@github.com> schrieb am Fr., 5. Feb. 2021,
16:57:

**Comment by paul-buerkner** [comment]
Now implemented thank to @martinmodrak.
