### ISSUE TITLE
(Ordered) Category specific effects for cumulative ordinal model

### ISSUE THREAD

**Issue by StaffanBetner** [paul-buerkner/brms#1060]
In van der Ark (2001) it is stated that "Moreover, a GRM’s β_{jx} must satisfy the ordering β_{j1} < β_{j2} < ... < β_{jm}" (with reference to Samejima (1969, p. 23), which I think lays out the necessary conditions for category specific effects for a cumulative ordinal model (COM). I think it would be good to separate the current function `cs` and a function for category specific effects for COMs, since there is no necessary restriction of this type for sequential and adjacent-category models, maybe something like `ocs` (ordered category specific). 

References:

Samejima, F. (1969). Estimation of latent ability using a response pattern of graded scores. Psychometrika Monograph Supplement.

Van Der Ark, L. A. (2001). Relationships and Properties of Polytomous Item Response Theory Models. Applied Psychological Measurement, 25(3), 273–282. https://doi.org/10.1177/01466210122032073

**Comment by paul-buerkner** [comment]
Fair, but how would you enfore this restriction in practice?

**Comment by StaffanBetner** [comment]
That's a good question. Something similar to monotonic effects maybe? But varying effects are tricky to combine with this restriction.

**Comment by StaffanBetner** [comment]
Peterson and Harrell (@harrelfe) (1990) calls it an unconstrained partial proportional odds model, see page 5 in the reference. Seems to be implemented in a Bayesian way in the package rmsb. 


Peterson, B., & Harrell Jr, F. E. (1990). Partial proportional odds models for ordinal response variables. Journal of the Royal Statistical Society: Series C (Applied Statistics), 39(2), 205-217. http://hbiostat.org/papers/feh/pet90par.pdf

**Comment by paul-buerkner** [comment]
I checked the code of the rmsb package, and it doesn't seem to constrain the category specific effects at all. 

I have decided to experimentally allow `cs()` for cumulative models (with a warning).
