### ISSUE TITLE
problem with code for model block in stanvars due to new position of "if (!prior_only) {" in generated Stan code

### ISSUE THREAD

**Issue by gbiele** [paul-buerkner/brms#1061]
Until recently it was possible to add stan-code via the `stanvar` functionality to modified intermediate variables created in the model block.

This was possible because 

```
if (!prior_only) {
...
}
```

wrapped only calls to log-pdf for the outcome variable (e.g. `target += normal_lpdf(Y | mu, sigma);`)

Now the generation of all intermediate variables, e.g. `mu` where the fixed effects are calculated and random effects are added, is wrapped into  `if (!prior_only)`, so that trying to modify one of these intermediate variable with stan code submitted via the `stanvar` functionality results in the error 

> Variable "mu" does not exist.

because the definition of the variable `mu` is wrapped into `if (!prior_only)`, whereas the standcode sumbitted with `stanvar` is pasted before the `if (!prior_only)` wrapper.

**Comment by paul-buerkner** [comment]
Thanks for opening this issue. The reason for this change was the addition of reduce_sum functionality, which made this change necessary for consistency. I am sure we find a good solution though. Can you show an example of what you are trying to achieve that has worked previously?

**Comment by gbiele** [comment]
First, I think reduce_sum is really more important, and I found a solution that works for me*.

The example is a hack, where I work around the fact that brms doesn't impute missing data for non-normal variables.

```
my_stanvars = stanvar(n_miss_g, name = "n_miss_g") +
              stanvar(idx_miss_g, name = "idx_miss_g") +
              stanvar(scode = "vector<lower=0,upper=1>[n_miss_g] imp_gender;",  "block = "parameters") + 
              stanvar(scode = "mu[idx_miss_g] += imp_gender * b[2];", block = "model") 
```

The first two lines are data with info about missing data (which I give the value 0 in the data.frame with the data), the third line defines the parameter for the imputed values, and the last line adds the effect of the covariate given the imputed value to the vector mu, which automatically generated by brms.

I think a solution to this problem could be to change where model code submitted with stanvar is put. I think a reasonable position is to put it just before the log-posterior for the data is calculated (I mean just before `target += normal_lpdf(Y | mu, sigma)` or similar). But I imagine that this can be hard with multivariate models. This solution might als not work with  reduce_sum, if the additional stancode uses additional variables as in my use case.

But as I said, I can work around this issue for the particular problem I had and while it would be nice if brms could support additional model code as before, this is not an urgent issue for me.

 *(I make a model-object without the additional code, change the stancode with gsub, recompile the stan-model and put it into the model object, and finally update the fit without recompilation).

**Comment by paul-buerkner** [comment]
I have just implemented a solution by adding `block = "likelihood"`. Works with both threaded and non-threaded models. Example:

```R
stanvars <- stanvar(scode = "mu += 1.0;", block = "likelihood", position = "start")
make_stancode(count ~ Trt + (1|patient), data = epilepsy, 
                         stanvars = stanvars)
```

Based on your description, I think this should do the trick.
