### ISSUE TITLE
Clarify sigma/sd prior defaults in the reference manual

### ISSUE THREAD

**Issue by ASKurz** [paul-buerkner/brms#1062]
At the moment, the [reference manual (version 2.14.4)](https://cran.r-project.org/web/packages/brms/brms.pdf) appears to give the incorrect information on the default setting for priors of `class = sigma`. 

In the *Parameters for specific families* subsection of the `set_prior` section, we read: “By default, `sigma` has a half student-t prior that scales in the same way as the group-level standard deviations.” Further up in the *Standard deviations of group-level (’random’) effects* subsection, we read: “These parameters are restricted to be non-negative and, by default, have a half student-t prior with 3 degrees of freedom and a scale parameter that depends on the standard deviation of the response after applying the link function. Minimally, the scale parameter is 10.”

However, based on responses to the [Default student_t priors in brms](https://discourse.mc-stan.org/t/default-student-t-priors-in-brms/17197) thread on the Stan Forums, it appears **brms** currently uses the formula `max(2.5, mad(data$y))` to set the scale parameter, where `y` is the response variable in the `data`. Based on the model I'm currently working with, I can confirm **brms** seems to use the formula `max(2.5, mad(data$y))` to calculate the scale parameter for the default.

It'd be helpful if this was clarified in the reference manual.

**Comment by paul-buerkner** [comment]
This is true. Thank you. I changed doc accordingy.
