### ISSUE TITLE
Combining addition terms fails as invalid

### ISSUE THREAD

**Issue by JCruk** [paul-buerkner/brms#1064]
Is it possible to pass more than one addition term within a brms formula?

I have tried:

```
bf(y | list("cat" = cat(gr = 4), "weight" = weights(Weight)) ~ 1)
bf(y | cat = cat(gr = 4), weights = weights(Weight) ~ 1)
bf(y | c(cat = cat(gr = 4), weights = weights(Weight)) ~ 1)
bf(y | c(resp_cat(gr = 4), resp_weights(Weight)) ~ 1) 
```

But all fail as invalid addition terms.

Is my syntax incorrect or is only one addition term permitted?

**Comment by paul-buerkner** [comment]
Combine them with +  :-)

JCruk <notifications@github.com> schrieb am Mi., 23. Dez. 2020, 17:25:

**Comment by JCruk** [comment]
Brilliant! Thank you!
