### ISSUE TITLE
Better handling of interval censoring at distributional bounds

### ISSUE THREAD

**Issue by StaffanBetner** [paul-buerkner/brms#1070]
This is really two issues, but they belong together:

I have a fairly simple interval censored dataset I want to fit a Gamma distribution to. The intervals are open in the lower end and closed at the upper end, as stated as they should be in the `brmsformula` help page. However, when the lowest bound is at the distributional bound (i.e. 0 for Gamma distribution) I get the warning `Family 'gamma' requires response greater than 0.` 

If I then specify a left censoring with 50 as upper bound and NA in the y2 (upper censoring bound) they all get excluded, as I get the warning `Rows containing NAs were excluded from the model. `

If I then replace NA with, say, 0, then it works. 

My suggestions are:
1. Fix so interval censoring works when the interval bounds are at the distributional bounds. I guess the same issue would appear if I want to use the Beta distribution and have interval censoring say (0.9, 1).
2. Ignore NA check for additional response information.

Code: 
```
library(tidyverse)
library(brms)


tibble::tribble(
  ~y,  ~y2, ~count, ~censoring,
    0,  50,  9L,   "interval",
   50, 100, 63L,   "interval",
  100, 150, 173L,  "interval",
  150, 200, 261L,  "interval",
  200, 250, 265L,  "interval",
  250, 300, 216L,  "interval",
  300, 350, 119L,  "interval",
  350, 400,  55L,  "interval",
  400, 450,  21L,  "interval",
  450, 500,   5L,  "interval"
) %>% uncount(count) -> 
  dat1

brm(bf(y | cens(censoring, y2) ~ 1), data = dat1, backend = "cmdstanr", family=Gamma(link="log"), cores=4) -> brm_model1
# Error: Family 'gamma' requires response greater than 0.
## Makes this incorrect: "Intervals are assumed to be open on the left and closed on the right: (y, y2]." (from help page for brmsformula)

tibble::tribble(
  ~y,  ~y2, ~count, ~censoring,
  50,  NA,  9L,      "left",
  50, 100, 63L,  "interval",
  100, 150, 173L, "interval",
  150, 200, 261L, "interval",
  200, 250, 265L, "interval",
  250, 300, 216L, "interval",
  300, 350, 119L, "interval",
  350, 400,  55L, "interval",
  400, 450,  21L, "interval",
  450, 500,   5L, "interval"
) %>% uncount(count) -> 
  dat2

brm(bf(y | cens(censoring, y2) ~ 1), data = dat2, backend = "cmdstanr", family=Gamma(link="log"), cores=4) -> brm_model2
# Warning message: Rows containing NAs were excluded from the model. 
## i.e. the (0,50] observations are excluded

tibble::tribble(
  ~y,  ~y2, ~count, ~censoring,
  50,   0,  9L,      "left",
  50, 100, 63L,  "interval",
  100, 150, 173L, "interval",
  150, 200, 261L, "interval",
  200, 250, 265L, "interval",
  250, 300, 216L, "interval",
  300, 350, 119L, "interval",
  350, 400,  55L, "interval",
  400, 450,  21L, "interval",
  450, 500,   5L, "interval"
) %>% uncount(count) -> 
  dat3

brm(bf(y | cens(censoring, y2) ~ 1), data = dat3, backend = "cmdstanr", family=Gamma(link="log"), cores=4) -> brm_model3

# Works fine
```

**Comment by paul-buerkner** [comment]
I am a little confused. Interval censored data, which is open at one end is not interval censored but rather left or right censored (depending on which end is open). Perhaps I am misunderstanding something though.

**Comment by StaffanBetner** [comment]
If it is open towards infinity (infinity, b] or [a, infinity), then it is left or right censored or could be regarded as interval censored with those bounds as left and right censoring are special cases of interval censoring. But the problem in this case is that the behaviour of brms goes against the specified behaviour that censoring intervals are specified as (a, b]. If a is at the boundary of the distribution I suppose it could be regarded as left censored, but if it is specified as left censoring then we get to the behaviour in the second example in the code: that those rows are removed by default if y2 (which is needed for the interval censoring) are NA.

**Comment by paul-buerkner** [comment]
Yeah, ok. brms could be more clever to not remove redundant NA values in `y2`. I take that. With regard to the rest, I don't see an issue there.

**Comment by StaffanBetner** [comment]
The reason I regard it as an issue is that is makes experimenting with different regression families a bit tedious. A typical case is when working with binned data, where the distributional bounds may not be obvious.

**Comment by paul-buerkner** [comment]
I have enabled ignoring NAs in `y2` as long as they are unused. I do see your point now with regard to censoring boundaries being at the boundaries of the family. However, allowing these values requires too much code changes and special case coding that I don't think is worth it, since, as you show above, we can easily work around it.
