### ISSUE TITLE
Error or warning when compilation fails

### ISSUE THREAD

**Issue by bwiernik** [paul-buerkner/brms#1072]
I was recently trying to fit this model:
```{r}
mod_brms <- 
  brm(
    bf(
      wellbeing ~ b0 + b1 * n_sessions + b2 * (n_sessions - k) * (n_sessions > k),
      b0 + b1 + b2 + k ~ 1,
      nl = TRUE
    ),
    data = therapy,
    prior = prior(normal(0, 4), nlpar = "b0") + 
      prior(normal(0, 4), nlpar = "b1") +
      prior(normal(0, 4), nlpar = "b2") +
      prior(nromal(6, 3), nlpar = "k")
  )
```

Notice the typo `nromal` in the last line. When brm() tries to compile the Stan program, it fails silently. It would be nice if an ERROR or at least WARNING could be returned in this case instead.

**Comment by paul-buerkner** [comment]
Does the same problem occur in the current brms github version?

**Comment by bwiernik** [comment]
Nope. Now it gives an informative error message. Thanks!
