### ISSUE TITLE
Seed setting not honored in posterior_predict in 2.14.4

### ISSUE THREAD

**Issue by svats2k** [paul-buerkner/brms#1073]
I am using the Howell1 dataset from rethinking package.

```
require(brms)
require(rethinking)

data("Howell1")
d <- Howell1
d2 <- d[d$age > 18,]

d2$hs <- (d2$height - mean(d2$height))/ sd(d2$height)
d2$ws <- (d2$weight - mean(d2$weight))/ sd(d2$weight)
```
Built a simple brms model with one (scaled) predictor

```
priors <- c(prior(normal(0,2), class = "Intercept"),
            prior(normal(0,2), class = 'b'),
            prior(cauchy(0,2), class = "sigma"))

m4.4 <- brm(formula = hs ~ 1 + ws, data = d2, family = gaussian, prior = priors, backend = "rstan")
```
I was trying to compare the outcome of posterior_predict and tidybayes::add_predicted_draws. But the results weren't matching. After further debug, with help of Dr. Mathew Kay, we saw that the seed setting wasn't being honored.

```
set.seed(1234)
yp1 <- posterior_predict(m4.4)
set.seed(1234)
yp2 <- posterior_predict(m4.4)

summary(as.vector(yp1 - yp2))
```
The summary output is as follows
```
     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
-4.792724 -0.631688 -0.001637 -0.001589  0.629033  4.542365 
```

I expected the results to exactly match between the 2 invocation of posterior_predict with the seed setting.  Please let me know if I am missing anything fundamentally.

This doesn't seem to be the issue with posterior_epred. Even without the seed setting there is no difference between subsequent invocation, I guess it is possibly because of the conditional averaging.  

The session info is as follows:
```
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.1 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] gridExtra_2.3        bayesplot_1.8.0      cmdstanr_0.1.3       rethinking_2.13      gganimate_1.0.7      RColorBrewer_1.1-2  
 [7] ggrepel_0.9.1        brms_2.14.4          Rcpp_1.0.6           rstan_2.21.2         StanHeaders_2.21.0-7 cowplot_1.1.1       
[13] ggplot2_3.3.3        tidybayes_2.3.1      ggdist_2.4.0         modelr_0.1.8         tidyr_1.1.2          forcats_0.5.0       
[19] purrr_0.3.4          dplyr_1.0.3          magrittr_2.0.1

**Comment by paul-buerkner** [comment]
Thanks! Let me check what is going wrong.

**Comment by paul-buerkner** [comment]
If you have set `options(mc.cores = <more than 1>)`, posterior_predict will evaluat in parallel by default, unless you change the `core` argument. On windows, parallel excution is done via `parallel::parLapply` and I don't know how that function respects seeds, if at all. When executing the code in serial (with 1 core) the results are reproducible.

**Comment by svats2k** [comment]
Thanks for getting back on this @paul-buerkner. Once I set the mc.cores option to 1, I no longer see the discrepancy on subsequent calls of posterior_predict with the same seed setting.
