### ISSUE TITLE
Feature: Very custom likelihoods

### ISSUE THREAD

**Issue by martinmodrak** [paul-buerkner/brms#1075]
As discussed at https://discourse.mc-stan.org/t/fitting-hmms-with-time-varying-transition-matrices-using-brms-a-prototype/19645 I would love `brms` to have better support to really hack around and connect linear predictors from `brms` with all sorts of complex models. 

After some thoughts here is my proposal how this could look like and I would love to hear feedback. It is something I should be able to implement, but want your feedback on the design.

The design aims at maximal flexibility - this is a power user/package developer feature.

In this setting, we no longer have a 1-1 connection from a row in the input dataset and the outcome (otherwise the current custom family feature would be sufficient). So the main idea is to introduce a `very_custom_family` (maybe there is a better name) that would:

- be given a string for he full likelihood (no loop for likelihood, the code has access to all data and to all computed linear predictors)
- have no outcome, only `dpars` 
- throws error when used with threading
- throws error when used with multivariate formula
- (optionally) allows using `subset` for the `dpars`
- (optionally) allows adding `links` to `dpars`

Since the likelihood only has `dpars` and multivariate formulas are avoided, I know exactly how the Stan variables representing the linear predictors will be named and can use them as I like. 

So a simple usage would be:

```r
my_ode_code <- "
  for(n in 1:N_odes) {
      vector x = compute_ode(a[n], b[n]);
      .....
  }
"
my_ode <- very_custom_family(code = my_ode_code, dpars = c("a", "b"))
f <- bf(a ~ 1 + (1|group), b ~ 1 + x + (1|group), family = my_ode)
brm(f, lot_of_stanvars, data = ...)
```

Does that make sense?

**Comment by paul-buerkner** [comment]
Thank you Martin! I am a little hesitant with this because I cannot yet forsee how much special case coding this will require in brms for this very specific feature. I understand its merits but still I am a little bit worried since it breaks so much structure that brms usually has in place. 

My current concerns are for example:
- If/How to support post-processing functions aush as `log_lik`=
- How to implement subsetting for the individual dpars?
- How to get around the fact that brms always requires the parameter `mu` as one of the distributional parameters?
- How to get around requring a response variable on the left-hand side of the main formula.

My gut feeling tells me that we are moving a little bit too far outside of the comfort zone of brms and thus will require lots of hacks that will then need to be maintained. I am happy to stand corrected on that but right now, I cannot yet fully foresee all the trouble we may run into with such custom families. Perhaps the trouble is muss less than I think right now, though.

**Comment by paul-buerkner** [comment]
Perhaps it would me sense for us to have a call, discuss the details more interactively and figure out potential problems and their solutions more easily that way.

**Comment by martinmodrak** [comment]
So I thought about it and I realized 99% of the functionality I want can be achieved by:

1) Creating `custom_family` with empty body of the Stan function in use
2) Using `stanvars(..., block = "model", position = "end")`

Without any changes to `brms` - the design really is already very flexible.

I presume this would address @seabbs 's use case as well...

**Comment by paul-buerkner** [comment]
That sounds nice indeed. It wouldn't cover the the post-processing though, would it?

**Comment by martinmodrak** [comment]
Yes, but all the use cases I have in mind require heavily customized post-processing anyway, so a reasonable method is IMHO to wrap the resulting `brms` fit in a new object that provides its own post-processing capabilities, using the default brms post-processing as a starting point. That's what I did in the HMM code - because I no longer have direct correspondance between elements of the `mu` array and observations, there is little code to reuse from `brms` anyway.

The only annoying thing about this solution is that it still requires to create a dummy response column which is passed to Stan, but then ignored and I have to call one of my parameters `mu`. But that's something one can IMHO live with quite easily. Especially if it spares us from having to make major changes to `brms`.

**Comment by paul-buerkner** [comment]
Thanks! That makes a lot of sense and I appreciate a solution that doesn't require major changes to brms. Shall we close this issue then or keep it open for the time being?

**Comment by martinmodrak** [comment]
Closing. Thanks for helping me think through this!

**Comment by martinmodrak** [comment]
So I got to actually try to implement this idea and stumbled on two problems that probably still not require major changes, but wanted to discuss how to do it best.

First is that when using `stanvar(..., block = "model", position = "end")` I get: 

```
Error: Position 'end' is not sensible for block 'model'.
```

But that is probably not the biggest problem. The biggest problem is that I need access to the `mu` array(s), but this is defined only within the scope of the `if(!prior_only) { ... } ` conditional. So even injecting the code at the end of the `model` block would not help, as I need way to inject Stan code within this conditional. 

I think it could be sensible to either define this as a new "virtual" block (that would then have both `start` and `end` positions) or as a new position valid only for the `model` block. I think this should be easy to implement... What do you think?

**Comment by paul-buerkner** [comment]
Have you tried `block = "likelihood"`, it is a newly added position.

**Comment by paul-buerkner** [comment]
I also just allowed to combined `model` and `end`. It was actually already supported in the code base just a check prevented it for some reason.

**Comment by martinmodrak** [comment]
Oh, that was exactly what I thought needs implementing. After udpating to 2.15 I can use it and it seems to solve my problem! 

Thanks!
