### ISSUE TITLE
Make silent option to be really silent

### ISSUE THREAD

**Issue by avehtari** [paul-buerkner/brms#1076]
`brm` says
```
  silent: Logical; If TRUE (the default), most of the informational
          messages of compiler and sampler are suppressed. The actual
          sampling progress is still printed. Set ‘refresh = 0’ to turn
          this off as well. If using ‘backend = "rstan"’ you can also
          set ‘open_progress = FALSE’ to prevent opening additional
          progress bars.
```
I wish `silent` option could be used to suppress all possible messages, especially the ones generated by brms package itself or the ones that can be easily suppressed when calling other packages. Specifically, I was surprised that `silent=TRUE` still prints `Start sampling` and I would prefer that it would already be suppressed with `silent=TRUE`. For suppressing messages from other packages I'm open for `silent` to have additional possible values.

**Comment by hsbadr** [comment]
I vote for verbosity level (e.g., `0-2`) where `0` suppresses everything [NONE], `1` keeps main/important info messages [INFO], and `2` verbose all messages for debugging [DEBUG]. The number of levels can change depending on what you want to show, but if it ends up with 2 levels, then `silent` logical is obviously enough.

**Comment by paul-buerkner** [comment]
I agree using verbosity levels (3 or even 4 levels) is a good idea!

**Comment by paul-buerkner** [comment]
I just implemented `silent = 2` for more silence.
