### ISSUE TITLE
Use Stan 2.26 functions

### ISSUE THREAD

**Issue by hsbadr** [paul-buerkner/brms#1077]
Now that the development version of `rstan` supports `Stan` version `2.26`, it may be more efficient to use the new functions, such as `log_inv_logit_diff`:
https://github.com/paul-buerkner/brms/blob/6c604e194952da7311b28ebb8bac00c7958806bc/R/stan-response.R#L528

Also, since version `2.25` won't exist, as mentioned by @rok-cesnovar in https://github.com/paul-buerkner/brms/pull/1074#discussion_r563610132, it'd be cleaner to use version `2.26`.

**Comment by paul-buerkner** [comment]
We will need to wait until that rstan version is on CRAN.

Hamada S. Badr <notifications@github.com> schrieb am Di., 26. Jan. 2021,
23:55:

**Comment by hsbadr** [comment]
> We will need to wait until that rstan version is on CRAN.

Yes, just preparing for it. I'll open a PR and leave it until the new version is published on CRAN.

**Comment by hsbadr** [comment]
> We will need to wait until that rstan version is on CRAN.

@paul-buerkner Please help in replacing the functions in https://github.com/paul-buerkner/brms/pull/1078. We can still make this conditional:

```r
if (rstan::stan_version() >= 2.26) {
  # Use the new functions
} else {
  # Keep the current code.
}
```

**Comment by paul-buerkner** [comment]
I am sorry but I have so much stuff on my hands right now that won't be
able to do much on this at the moment. But I will come back to it when I
can. Thank you for opening this issue and taking the first steps.

Hamada S. Badr <notifications@github.com> schrieb am Mi., 27. Jan. 2021,
00:08:

**Comment by hsbadr** [comment]
> I am sorry but I have so much stuff on my hands right now that won't be able to do much on this at the moment. But I will come back to it when I can.

No problem. Take your time! None of this is urgent. The performance may or may not change, but it'd be great to follow the `Stan` development anyway.

**Comment by paul-buerkner** [comment]
Most of this is now implemented. Only categorical_logit_glm is missing, but that will be added too for the 2.21 release.

**Comment by paul-buerkner** [comment]
Completed now.
