### ISSUE TITLE
Thresholds for ordinal brms model in emmeans

### ISSUE THREAD

**Issue by rpetrovska** [paul-buerkner/brms#1080]
Dear Paul,

I wonder why an ordinal mixed effect model in brms does not have thresholds in emmeans/emmip? In my case, the outcome is some mean probability over all thresholds, i.e. response range. Is it possible to get the marginal probability for each threshold? For example, in the package "ordinal" all thresholds are coded as "cut" variables and can be identified in ref_grid in emmeans (https://cran.r-project.org/web/packages/emmeans/vignettes/sophisticated.html) 

How can I identify thresholds in emmeans providing my model is fitted in brms? I address this issue on brms/Stan forum - (https://discourse.mc-stan.org/t/thresholds-for-ordinal-brms-model-in-emmeans/20448) and to Russell Length. His brief suggestion is:

"What would be needed is similar to the routines for clm models, in that it would be necessary to set things up in terms of a multivariate response and, in some modes, some post-processing; but simpler than for clm because we only have to manage the posterior samples,  and obtain means and covariances from those ". 

I hope, brms would be more convenient once emmeans issue will be fixed. Thank you in advance for your attention.

Cheers,
Roksolana

**Comment by paul-buerkner** [comment]
Is this the same issue as #980?

**Comment by rpetrovska** [comment]
Yes, marginal mean per threshold in emmeans for the model fitted in brms.
Conditional_effects and fitted() can do this but they do not account for
offsets. I need the marginal mean for different thresholds at a different
level of offset values. Emmeans does it in a simple and quick way.

Thank you for your quick response!

Cheers,
Roksolana

**Comment by paul-buerkner** [comment]
Ok, as it is the same issue as #980 I will close this one here.

**Comment by paul-buerkner** [comment]
Just want to briefly add that a solution to this is non-trivial and I may need some time to work on this from the brms side at least.
