### ISSUE TITLE
Indexing errors with multi-level GPs

### ISSUE THREAD

**Issue by Reece844** [paul-buerkner/brms#1081]
When specifying a model with something like gp(x,y, by=factor) in the formula, the code generated in the partial log likelihood function will result in a run-time error. 

For example, the error occurs due to the way indexing is done without threads, using Igp_1_* and the slicing.

`
mu[Igp_1_1[start:end]] += Cgp_1_1[start:end] .* gp_pred_1_1[Jgp_1_1[start:end]]; `
`mu[Igp_1_2[start:end]] += Cgp_1_2[start:end] .* gp_pred_1_2[Jgp_1_2[start:end]];`
`mu[Igp_1_3[start:end]] += Cgp_1_3[start:end] .* gp_pred_1_3[Jgp_1_3[start:end]];`
`mu[Igp_1_4[start:end]] += Cgp_1_4[start:end] .* gp_pred_1_4[Jgp_1_4[start:end]];
`
    
 There are a couple different workarounds I can think of, the easiest being to have separate reduce_sum calls for each factor, but I don't know how that would affect speed.

**Comment by paul-buerkner** [comment]
Thanks! Multiple reduce_sum may not be a good option at the moment because
it has too many implications on too much other stuff. I will think of
something that works in the current structure. Ideas are very welcome!

Reece Willoughby <notifications@github.com> schrieb am Fr., 29. Jan. 2021,
22:17:

**Comment by paul-buerkner** [comment]
This should now be fixed on github. Thanks again for opening this issue.
