### ISSUE TITLE
Average outcome value for the ordinal mixed models in brms

### ISSUE THREAD

**Issue by rpetrovska** [paul-buerkner/brms#1082]
Dear Paul, 

I think, ordinal mixed effect models, especially with counts, can be improved if either predict or fitted function can assess also an average outcome value. This graph I find particularly important and simple - https://bookdown.org/content/3890/monsters-and-mixtures.html#bonus-figure-11.3-alternative.

![image](https://user-images.githubusercontent.com/76253379/106355743-3d9d5800-62fa-11eb-9ce8-23855c821c6f.png)

In simple models without random effects, it is possible to use functions developed by S. Kurz but much more difficult in complex models. 

Thank you for brms, I start learning Bayesian because of the simplicity of this package.

Cheers,
Roksolana

**Comment by JCruk** [comment]
One way to accomplish this could be through a weighted mean of expected probabilities for each MCMC step. Where the weighted mean of ordinal categories (e.g., 1...5 ratings). This produces a single number:

```
sum(probs * (1:5))
```
where "probs" is a vector of fitted/expected probabilities of responses 1...5. 

For all equal probabilities of a 5-category scale:

```
 (sum(1:5 * rep(1/5, 5)))
[1] 3
```

**Comment by paul-buerkner** [comment]
Thank for opening this issue. I am deliberatly not supporting average outcome values for ordinal models natively in brms as the ordinality, by definition, does not guarantee equidistance, an assumption required for averaging. You can still compute it manually yourself as sketched out by @JCruk

**Comment by andymilne** [comment]
Surely there is nothing unprincipled about graphing the results on the latent scale? That might provide a different alternative for visualisation, and one which does not require possibly inappropriate averaging between unequal categories?

**Comment by paul-buerkner** [comment]
I agree! For that purpose we have posterior_linpred.

Andrew Milne <notifications@github.com> schrieb am Mo., 1. Feb. 2021, 22:58:

**Comment by andymilne** [comment]
Yes, indeed. And that method can be called directly from within the `conditional_effects()` function, which make it super easy to do.

**Comment by paul-buerkner** [comment]
Thank you for bringing that up!

Andrew Milne <notifications@github.com> schrieb am Mo., 1. Feb. 2021, 23:03:

**Comment by JCruk** [comment]
> Yes, indeed. And that method can be called directly from within the `conditional_effects()` function, which makes it super easy to do.

Is that done by passing `method = "predict"` and `ordinal = FALSE` to `conditional_effects()`?

**Comment by andymilne** [comment]
As far as I know it should be just `conditional_effects(mdl, method = "posterior_linpred"`). I note that this gives the warning `Predictions are treated as continuous variables in 'conditional_effects' by default which is likely invalid for ordinal families. Please set 'categorical' to TRUE.` which is probably not appropriate when using `method = "posterior_linpred"` (because it is not invalid in this instance and `categorical = TRUE` is not valid when `method = "posterior_linpred"` ). Maybe the warnings could be updated if they are inappropriate?

**Comment by paul-buerkner** [comment]
The code is correct. I will check the warning.

Andrew Milne <notifications@github.com> schrieb am Di., 2. Feb. 2021, 00:25:

**Comment by andymilne** [comment]
Also within the standard case -- i.e., `conditional_effects(ordinal_mdl)` -- it might be worth amending the warning to suggest using `categorical = TRUE` or by using `method = "posterior_linpred"`
