### ISSUE TITLE
Models hang after completion

### ISSUE THREAD

**Issue by JCruk** [paul-buerkner/brms#1083]
I occasionally have models hang after the final chain reports a summary.

I can recover the session by hitting `Esc` but that results in losing the model object.

Is there any way to recover from the hang without losing the model?

**Comment by paul-buerkner** [comment]
Please ask brms related questions on https://discourse.mc-stan.org/. In order to have a chance of receiving helpful responses, you may need to provide some more details about the models for which this occurse.
