### ISSUE TITLE
cov_exp_quad is deprecated

### ISSUE THREAD

**Issue by torkar** [paul-buerkner/brms#1089]
Running latest `brms`/`cmdstan` with a GP term and a varying intercept. Now I get this after each compilation:
```
cov_exp_quad is deprecated and will be removed in the future. Use gp_exp_quad_cov instead.
```

**Comment by rok-cesnovar** [comment]
Proper handling of deprecated functions was added for 2.26, which is why this pops up juts now. 

`gp_exp_quad_cov` has been around since at least 2.21 and is also supported with stanc2 that is part of the current rstan on CRAN.
