### ISSUE TITLE
Specify random effects of one response as predictors of another

### ISSUE THREAD

**Issue by Jordan-Scott-Martin** [paul-buerkner/brms#1093]
Hello Paul,

My feature request is related to issue https://github.com/paul-buerkner/brms/issues/931 , though I believe it is sufficiently distinct as it concerns multi-response models. I am interested in simultaneously estimating random effects specified in one response model as fixed effect predictors in another response model. The intended application is to use personality scores estimated with random intercepts and slopes from repeated measures of `y` to predict individual-level outcome `z`, with a potentially non-linear functional form. Something like
`     bf(y ~ a,  a ~ (1|ID), nl = TRUE) + bf(z ~ b1*a + b2*I(a^2), b1 + b2 ~ 1, nl = TRUE)` in a simple case for the quadratic effect of random intercepts.

I'm not sure how random slopes could also be efficiently specified in the syntax, but even just having functionality for random intercepts would be great. I've tried coding this but currently brms does not seem to recognize that `a` is being carried over into the second response model. It is straightforward to accomplish this in Stan, but I'm hoping that my colleagues can do the same with the more user-friendly experience of brms.

My apologies ahead of time if I've missed something obvious. Thank you for your time!

**Comment by paul-buerkner** [comment]
This is a reasonable feature request and basically covered in the SEM feature described in #304. Hence, I am closing this issue here to avoid duplication.
