### ISSUE TITLE
Offsets are ignored in emmeans support

### ISSUE THREAD

**Issue by rvlenth** [paul-buerkner/brms#1096]
I have found that if a model includes an offset term, that offset gets ignored when using `emmeans()` or related functions.

To fix that, the code for `recover_data.brmsfit` needs some modification. Currently we have
```r
> brms:::recover_data.brmsfit
function (object, data, resp = NULL, dpar = NULL, nlpar = NULL, ...) 
{
    bterms <- .extract_par_terms(object, resp, dpar, nlpar)
    trms <- attr(model.frame(bterms$fe, data = object$data), "terms")
    emmeans::recover_data(call("brms"), trms, "na.omit", object$data, ...)
}
```
If you trace and look at `trms`, the formula excludes the `offset` term, and `attr(trms, "offset")` is not present. I'd think it would be a fairly simple matter to fix that. I note that `bterms` includes an `$offset` slot; so that needs to be incorporated in `trms`.

Including the offset is important to make `emmeans()` work as documented. Normally, any variables involved in the offset are included in the reference grid, and when the `offset` argument is not specified manually, the offset is computed based on the model formula and added to the predictions. 

Here's the example I tested:
```r
require(foreign)
require(brms)
require(emmeans)

dat <- read.dta("https://stats.idre.ucla.edu/stat/data/hsbdemo.dta")

f0 <- brmsformula(awards ~ prog + (1|cid))
mod0 <- brm(f0, family = poisson(), data = dat, seed = 123)

f1 <- brmsformula(awards ~ prog + (1|cid) + offset(log(math)))
mod1 <- brm(f1, family = poisson(), data = dat, seed = 123)

ref_grid(mod0)@grid

##       prog .wgt.
## 1  general    45
## 2 academic   105
## 3 vocation    50

ref_grid(mod1)@grid

##       prog .wgt.
## 1  general    45
## 2 academic   105
## 3 vocation    50
```
The reference grid for `mod1` should include `math` as a variable (with one value, set to its mean), and its `@grid` slot should have an additional column named `.offset` (with one value, set to `log(math)`).

**Comment by paul-buerkner** [comment]
Thanks. I will fix it soon.

**Comment by paul-buerkner** [comment]
This should now be fixed. Thank you again for opening this issue!

**Comment by rvlenth** [comment]
Thanks Paul. Finally got a chance to update everything and check it for myself.

**Comment by mbg-unsw** [comment]
Looking at 2.17.0, it looks to me that there's been a regression for this problem since 2.15.0, e.g. rvlenth's example above shows no evidence of .offset

Maybe something got missed when the fixes to #907 and #1134 were added in 2.16.0?

**Comment by paul-buerkner** [comment]
can you show a reprex and check if it fails with the latest brms version
from github?

Malcolm Gillies ***@***.***> schrieb am Mo., 18. Juli 2022,
09:02:

**Comment by mbg-unsw** [comment]
Here's a reprex:
```R
remotes::install_github("paul-buerkner/brms")
library(brms)
library(foreign)
library(emmeans)
library(lme4)

dat<-read.dta("https://stats.idre.ucla.edu/stat/data/hsbdemo.dta")
f1 <- brmsformula(awards ~ prog + (1|cid) + offset(log(math)))
mod.brm <- brm(f1, family=poisson(), data=dat, seed=123)
gr<-ref_grid(mod.brm)
mod.glmer <- glmer(awards ~ prog + (1|cid) + offset(log(math)), family=poisson(), data=dat)
gr2 <- ref_grid(mod.glmer)
emmeans(gr, "prog")
emmeans(gr2, "prog")
emmeans(gr, "prog", offset=0)
emmeans(gr2, "prog", offset=0)
```

Output:
```
> emmeans(gr, "prog")
 prog       emmean lower.HPD upper.HPD
 general   0.00442    -0.590     0.583
 academic  0.04162    -0.565     0.548
 vocation -0.08883    -0.706     0.516

Point estimate displayed: median 
Results are given on the log (not the response) scale. 
HPD interval probability: 0.95 
> emmeans(gr2, "prog")
 prog      emmean    SE  df asymp.LCL asymp.UCL
 general   0.0415 0.268 Inf    -0.484     0.567
 academic  0.0708 0.250 Inf    -0.419     0.561
 vocation -0.0514 0.277 Inf    -0.595     0.492

Results are given on the log (not the response) scale. 
Confidence level used: 0.95 
> emmeans(gr, "prog", offset=0)
 prog       emmean lower.HPD upper.HPD
 general   0.00442    -0.590     0.583
 academic  0.04162    -0.565     0.548
 vocation -0.08883    -0.706     0.516

Point estimate displayed: median 
Results are given on the log (not the response) scale. 
HPD interval probability: 0.95 
> emmeans(gr2, "prog", offset=0)
 prog     emmean    SE  df asymp.LCL asymp.UCL
 general   -3.92 0.268 Inf     -4.45     -3.40
 academic  -3.89 0.250 Inf     -4.38     -3.40
 vocation  -4.01 0.277 Inf     -4.56     -3.47

Results are given on the log (not the response) scale. 
Confidence level used: 0.95 
```
Note that the glmer() model gives different emmeans when the ```offset0``` arg is used.

**Comment by rvlenth** [comment]
I have not looked at this yet, but offsets are determined when `ref_grid` is run, by looking at the `attr(trms, "offset")`. This should be an attribute there whenever the model formula has an offset. So the first place to look at is whether `trms` has that offset. I don't think it is necessary for any special handling of the offset in the `recover_data` or `emm_basis` methods, as long as `trms` is right.

**Comment by rvlenth** [comment]
Indeed, the offsets are not even computed in the brms model. The quickest way to check is just to look at the `grid` slot:
```
> gr@grid
      prog   math .wgt.
1  general 52.645    45
2 academic 52.645   105
3 vocation 52.645    50

> gr2@grid
      prog   math .offset. .wgt.
1  general 52.645 3.963571    45
2 academic 52.645 3.963571   105
3 vocation 52.645 3.963571    50
```
The point being that there is no `.offset.` column in `gr`.

**Comment by rvlenth** [comment]
I created a local substitute for the `recover_data` method which seems to work:
```r
recover_data.brmsfit <- function (object, data, resp = NULL, dpar = NULL, nlpar = NULL, 
    re_formula = NA, epred = FALSE, ...) 
{
    bterms <- brms:::.extract_par_terms(object, resp = resp, dpar = dpar, 
        nlpar = nlpar, re_formula = re_formula, epred = epred)
    trms <- attr(model.frame(bterms$formula, data = object$data), 
        "terms")
    emmeans::recover_data(call("brms"), trms, "na.omit", data = object$data, 
        ...)
}
```
... compared with
```r
> brms:::recover_data.brmsfit
function (object, data, resp = NULL, dpar = NULL, nlpar = NULL, 
    re_formula = NA, epred = FALSE, ...) 
{
    bterms <- .extract_par_terms(object, resp = resp, dpar = dpar, 
        nlpar = nlpar, re_formula = re_formula, epred = epred)
    trms <- attr(model.frame(bterms$allvars, data = object$data), 
        "terms")
    emmeans::recover_data(call("brms"), trms, "na.omit", data = object$data, 
        ...)
}
```
Testing with my alternative recover_data method, I get
```
> ref_grid(mod.brm)@grid
      prog   math .offset. .wgt.
1  general 52.645 3.963571    45
2 academic 52.645 3.963571   105
3 vocation 52.645 3.963571    50
```
The only difference between the above and `brms:::recover_data.brmsfit` are
  1. Hard reference to `brms:::` needed because my function is not in brms's namespace (so this change would not be needed in the brms code)
  2. In second line, we use `bterms$formula` instead of `bterms$allvars`. 

Can we remember why we used `$allvars`??? For this model, we have
```
> bterms$formula
~prog + offset(log(math))
attr(,"nl")
[1] FALSE
attr(,"loop")
[1] TRUE

> bterms$allvars
~++1 + prog + prog + math + prog + math
```
We lost the `offset` attribute in `$allvars`. Are there more complicated models where the `$formula` slot does not give us what we need?

**Comment by paul-buerkner** [comment]
Thank you for looking into this! 

As far as I remember, we need `allvars` to put all the variables together that the model has. Of course, formula works just fine for simple models consistent of a single formula, but this won't be the case with distributional or non-linear models. Those may need allvars. I will go check out `.extract_par_terms` to see if I can include the right offset terms without breaking the rest of the code.

**Comment by paul-buerkner** [comment]
Hmm. I implemented a fix but I am not sure we get what we want. Here is what I see with the reprex above:

```R
> emmeans(gr, "prog")
 prog     emmean lower.HPD upper.HPD
 general    3.98      3.36      4.60
 academic   4.01      3.38      4.55
 vocation   3.88      3.29      4.54

Point estimate displayed: median 
Results are given on the log (not the response) scale. 
HPD interval probability: 0.95 

> emmeans(gr2, "prog")
 prog      emmean    SE  df asymp.LCL asymp.UCL
 general   0.0415 0.268 Inf    -0.484     0.567
 academic  0.0708 0.250 Inf    -0.419     0.561
 vocation -0.0514 0.277 Inf    -0.595     0.492

Results are given on the log (not the response) scale. 
Confidence level used: 0.95 

> emmeans(gr, "prog", offset=0)
 prog      emmean lower.HPD upper.HPD
 general   0.0160    -0.603     0.636
 academic  0.0469    -0.586     0.590
 vocation -0.0829    -0.669     0.577

Point estimate displayed: median 
Results are given on the log (not the response) scale. 
HPD interval probability: 0.95 

> emmeans(gr2, "prog", offset=0)
 prog     emmean    SE  df asymp.LCL asymp.UCL
 general   -3.92 0.268 Inf     -4.45     -3.40
 academic  -3.89 0.250 Inf     -4.38     -3.40
 vocation  -4.01 0.277 Inf     -4.56     -3.47

Results are given on the log (not the response) scale. 
Confidence level used: 0.95 
```

The offsets are not there are least:

```R
> gr@grid
      prog   math .offset. .wgt.
1  general 52.645 3.963571    45
2 academic 52.645 3.963571   105
3 vocation 52.645 3.963571    50
```

What is emmeans doing exactly with the offsets? Is it including them manually? I am asking because brms takes care of offsets fully internally so I am wondering why emmeans needs to know about the offsets at all?

**Comment by rvlenth** [comment]
OK; well, the short answer is that I think the **brms** interface to **emmeans** should produce comparable *post hoc* results as a comparable model fitted to the same data by another package. That clearly did not happen here. 

That also answers (by "no") the idea of "disabling offset support" for `brmsfit` models, since that would imply non-comparable results. Keep in mind that once the reference grid is obtained, any subsequent analysis is completely out of **brms**'s hands. So if we are going to do different things with offsets, **emmeans** has to handle it because it can't be done by the model-fitting package.

It comes down to what we mean by "handling an offset." I think there's more than one possibility. In a Poisson model like this example, we might want to estimate means, or rates; see the illustration in [one of the emmeans vignettes](https://cran.r-project.org/web/packages/emmeans/vignettes/sophisticated.html#offsets). Sometimes we might want offsets to not be constant, e.g.,
```
> ref_grid(mod.brm, cov.reduce = math ~ prog)
'emmGrid' object with variables:
    prog = general, academic, vocation
    math = (predicted by other variables)
Transformation: “log” 
> .Last.value@grid
      prog     math .offset. .wgt.
1  general 50.02222 3.912467    45
2 academic 56.73333 4.038362   105
3 vocation 46.42000 3.837730    50
```
It appears that currently, what we are getting from the brms interfaces is predictions with the offset already added. *If we are returning something on the link scale*, we instead want to have predictions with offset 0, so that the `.offset.` column can be added to obtain the predictions. That makes it possible for the user to opt to set `offset = 0` as in the reprex as well as the example I linked to. When we have some other kind of prediction, i.e., `epred = TRUE`, the offset should indeed be handled by **brms** because it makes no sense otherwise; and in that case, the offset should *not* be included in `trms` and therefore we will not get an `.offset.` column in the grid. Unfortunately, I see that this may be adding further complexity to `recover_data`, but perhaps not if `bterms` only has an `offset` slot when it is appropriate.

Does this make sense?

**Comment by rvlenth** [comment]
FWIW, it *is* possible to "fix up" what we have now to remove the offsets... For example:
```
> gr = ref_grid(mod.brm, cov.reduce = math ~ prog)
```
What we have now is
```
> gr@grid
      prog     math .offset. .wgt.
1  general 50.02222 3.912467    45
2 academic 56.73333 4.038362   105
3 vocation 46.42000 3.837730    50
> gr@linfct
     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    1    0
[3,]    0    0    1
```
The `linfct` slot is the identity matrix. We can remove the offsets by adding more regression coefficients to allow for subtracting the offsets
```r
grr = gr
grr@linfct = cbind(grr@linfct, diag(3))
grr@bhat = c(grr@bhat, -grr@grid$.offset.)
grr@V = kronecker(matrix(c(1,0,0,0), nrow = 2), grr@V)
grr@post.beta = cbind(grr@post.beta, 
    matrix(rep(-grr@grid$.offset., each = nrow(grr@post.beta)), 
           ncol = nrow(grr@grid)))
```           
So here's the test run:
```
> emmeans(grr, "prog")
 prog      emmean lower.HPD upper.HPD
 general  -0.0293    -0.598     0.568
 academic  0.1322    -0.506     0.609
 vocation -0.1902    -0.879     0.375

Point estimate displayed: median 
Results are averaged over the levels of:  
Results are given on the log (not the response) scale. 
HPD interval probability: 0.95 
> emmeans(grr, "prog", offset = 0)
 prog     emmean lower.HPD upper.HPD
 general   -3.94     -4.51     -3.34
 academic  -3.91     -4.54     -3.43
 vocation  -4.03     -4.72     -3.46

Point estimate displayed: median 
Results are averaged over the levels of:  
Results are given on the log (not the response) scale. 
HPD interval probability: 0.95 
```
In the (usual) case where the offset is the same for the whole grid, we only have to add  one extra coefficient, so that case is probably worth separating out.

**Comment by mbg-unsw** [comment]
Thanks @paul-buerkner I just tried the latest on github and it works for my simple use case (per the reprex).

**Comment by rvlenth** [comment]
The update [0bf0bb6](https://github.com/paul-buerkner/brms/commit/0bf0bb6bbd94566f98ef9954eacefd94d4d2ed64) looks good to me. In testing it with `gr.new <- ref_grid(mod.brm, cov.reduce = math ~ prog)`, I get identical results to what I show previously with my "fixed-up" grid `grr`. And all the examples with `? recover_data.brmsfit` seem to run correctly.

**Comment by paul-buerkner** [comment]
Perfect, thank you too for testing and @rvlenth for helping me to understand emmeans better every time!
