### ISSUE TITLE
Include option to control behavior of normalize

### ISSUE THREAD

**Issue by storopoli** [paul-buerkner/brms#1097]
Please include an option to control the default behavior of `normalize` inside `brm()` with the new feature in `brms` 2.14.11 (requires Stan version 2.25) as described in #1017 and #1053.

A suggestion (for `.Rprofile` and similar):

```r
options(brms.normalize = FALSE)
```

**Comment by paul-buerkner** [comment]
This is now possible in the brms dev version.

**Comment by storopoli** [comment]
Great! Thank you!
