### ISSUE TITLE
document use of hypothesis on a data.frame

### ISSUE THREAD

**Issue by petrelharp** [paul-buerkner/brms#1100]
It's explained in #261 that you can use `hypothesis()` to do hypothesis tests of (apparently) whatever you want, as long as what you pass in for `x` looks like a data frame of posterior samples with columns labelled appropriately. This is very nice! But [it doesn't seem to be documented](http://paul-buerkner.github.io/brms/reference/hypothesis.brmsfit.html), at least, the docs say that:
```
x  An R object. If it is no brmsfit object, it must be coercible to a data.frame.
```
... but don't explain what happens if you pass in something that's not a brmsfit object. I could draft a paragraph explaining it, if that's helpful - but, maybe there's a preferred way of doing the same thing somewhere else?

**Comment by paul-buerkner** [comment]
I added some documention on github.
