### ISSUE TITLE
emmeans support - regrid using an 'exp' transform argument?

### ISSUE THREAD

**Issue by nahorp** [paul-buerkner/brms#1101]
Hello,

I'm wanting to regrid an emmGrid object that has `mu` estimates that was modelled as a natural log with an identity link function (using the shifted lognormal distribution). I am wanting these estimates on the response scale and hence want to exponentiate them but can't see a transform = "exp" (or thereofs) in the accepted inputs for the `regrid` function.

Thank you!

**Comment by paul-buerkner** [comment]
It seems to me that this should be an emmeans issue because `regrid` is not a brms function.

**Comment by rvlenth** [comment]
This isn't really about `regrid()`. I think the situation here is that with a shifted lognormal, then there are two parts of the model, the portion that estimates the lognormal parameters, and another portion that estimates the shift. So to put this together, there would need to be an argument in `recover_data.brmsfit` and `emm_basis.brmsfit` to allow for recovering the data needed for both parts of the model (`in recover_data`), and then (in `emm_basis`) combining these estimates and combining them into one estimate. This is impossible to do with `emmeans::regrid()`. 

What's needed is more akin to what is done to support `ordinal::clm()` with `mode = "response"` -- if there is a scale model in addition to the location model, we have to combine the two models. 

The upside is you wouldn't have to deal with the delta-method stuff. Just do the posterior predictions and then use summary stats to obtain the `bhat` and `V` slots to use if somebody wants a frequentist summary.

**Comment by paul-buerkner** [comment]
I see. Thanks. Not sure if that will make it into brms, but I reopen the issue for now and see how it goes.

**Comment by paul-buerkner** [comment]
I think the initial goal of the OP can be achieved by setting `transform = "log"` such that the link function is set to `log` and, as such, the inverse link is set to `exp`.  I agree that this may not be the ideal option given the mixture-style of the shifted lognormal distribution. To get the combined mean of the two parts I recommend using `epred = TRUE` a soon to be implemented feature of brms' emmeans support, that will replace the soon to be deprecated feature `dpar = "mean"`.
