### ISSUE TITLE
Handle frequency weights with loo

### ISSUE THREAD

**Issue by StaffanBetner** [paul-buerkner/brms#1102]
I don't know whether this is the right place (or if the loo repo is more suitable), but some adjustment seems to be needed when using loo on a model where the data have been compressed by frequency weights. Otherwise Pareto k's indicates that all observations are heavily influencing the posterior, which of course it true on the aggregated level, but may not be true in the disaggregated leve.

**Comment by paul-buerkner** [comment]
Yeah, that should probably be a loo issue (and discussion) first before it makes it into the interfaces.
