### ISSUE TITLE
no samples after chain 4 when random structure declared

### ISSUE THREAD

**Issue by alecristia** [paul-buerkner/brms#1109]
I'm fitting a model with random slopes and using 4 chains, with code that worked circa July 2020. (By that I mean: no warnings, no errors, no funny business in the resulting priors/posteriors).

The same code now fails, and I've found that it fails when two conditions are met: 1. there is some random structure; 2. 4 or more chains are specified (regardless of whether core = 1 or 2).

I'm attaching code and data. Notice:

- mod1_4chains (4 chains and random structure) fails due to no samples in chain 4
- mod1_3chains (3 chains and random structure) yields a warning
- mod1_4chains_noRS (4 chains, no random structure) succeeds
- mod1_4chains_simplerRS (4 chains, simpler random structure) fails due to no samples in chain 4

Session info in txt also attached
[BFfixed-random.zip](https://github.com/paul-buerkner/brms/files/6042272/BFfixed-random.zip)

I do realize three packages are not updated to the most recent version:

- quantreg, I get "fatal error: 'complex' file not found"
- fftwtools, I get "fatal error: 'fftw3.h' file not found"
- data.table, I get "fatal error: 'complex' file not found"

**Comment by alecristia** [comment]
- I downloaded a new version of [fortran](https://github.com/fxcoudert/gfortran-for-macOS/releases/download/8.2/gfortran-8.2-Mojave.dmg)
- I restarted RStudio
- update for quantreg successful, the other two still fail
- refitting mod1_4chains still yields error in chain 4

**Comment by alecristia** [comment]
- `brew install fftw`
- update for fftw now successful
- refitting mod1_4chains still yields error in chain 4

**Comment by alecristia** [comment]
- error when installing data.table refers to Rcppeigen
- dead end: “macos-rtools-4.0.0.pkg” can’t be opened because Apple cannot check it for malicious software.
- dead end: (cli tools & fortran already installed): https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos/`

Actually, the full error is: 

> In file included from <built-in>:1:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp:13:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppEigen/include/Eigen/Dense:1:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppEigen/include/Eigen/Core:88:
/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppEigen/include/Eigen/src/Core/util/Macros.h:613:1: error: unknown type name 'namespace'
namespace Eigen {
^
/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppEigen/include/Eigen/src/Core/util/Macros.h:613:16: error: expected ';' after top level declarator
namespace Eigen {
               ^
               ;
In file included from <built-in>:1:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp:13:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppEigen/include/Eigen/Dense:1:
/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppEigen/include/Eigen/Core:96:10: fatal error: 'complex' file not found
#include <complex>
         ^~~~~~~~~
3 errors generated.
make: *** [assign.o] Error 1

which means that a c rather than c++ compiler is being used, right? 

Not sure how to proceed at this stage, all help is welcome!

**Comment by andrjohns** [comment]
R3.6 on Mac doesn't play too well with RStan 2.21 unfortunately. I'd try updating to R4.0, if possible.

Alternatively, try installing the [cmdstanr package](https://mc-stan.org/cmdstanr/articles/cmdstanr.html) and running your `brms` models with the `backend="cmdstanr"` option. `cmdstanr` is generally more stable.

**Comment by paul-buerkner** [comment]
Since this is not directly related to brms, I am closing this issue, but perhaps this question can be answered on https://discourse.mc-stan.org/ if Andrew's suggestion not already solves it.

**Comment by alecristia** [comment]
installing macos-rtools-4.0.0.pkg didn't help

Then I updated to R4.0.4, which led to updating many packages - and that fixed the issue!

Thank you @andrjohns !

If there are others reading this, my advice may come too late, but checkout the groundhog package: http://datacolada.org/95
