### ISSUE TITLE
Multivariate predictions

### ISSUE THREAD

**Issue by aforren1** [paul-buerkner/brms#111]
I think the behavior of `update_data` has changed for multivariate models, and the predict function assumes a different structure.

```{r}
library(brms)
set.seed(1)
N <- 50
y1 <- rnorm(N, 0, 1)
y2 <- rnorm(N, 10, 2)
dat <- data.frame(y1 = y1, y2 = y2, x1 = rnorm(N, -10, 2))
formula_cran <- formula(cbind(y1, y2) ~ 0 + trait + trait:x1)
formula_github <- update(formula_cran, . ~ x1)

mod <- brm(formula_github, data = dat, 
    family = 'gaussian', chains = 1,
    seed = 1)
# or
# mod <- brm(formula_cran, data = dat, 
#    family = 'gaussian', chains = 1,
#    seed = 1)
```

On the Github version, `predict(mod)` tries to access the `K_trait` slot (which should now be `nresp`? I have a branch with the change [here](https://github.com/aforren1/brms/tree/multivariate_predict)). However (with the fix), the number of rows in the returned are different.
```{r}
# CRAN
dim(predict(mod))
[1] 100   4

# Github
[1] 50  4
```
The difference is because `N` slot in the output of `standata` has changed. It gets `N` from the number of rows in the data returned from `make_standata` [here](https://github.com/paul-buerkner/brms/blob/eba536363ba72b583877db0cc2f37189f670932b/R/make_standata.R#L83), and `data` comes from `update_data`.

```{r}
# CRAN
head(brms:::update_data(dat, family = 'gaussian',
                   effects = brms:::extract_effects(formula_cran,
                                                    family = 'gaussian')), 2)
##  response      y1     y2 trait      x1
##1  -0.6265 -0.6265 10.796    y1 -11.241
##2   0.1836  0.1836  8.776    y1  -9.916

# Github
head(brms:::update_data(dat, family = 'gaussian', 
                   effects = brms:::extract_effects(formula_github,
                                                    family = 'gaussian')), 2)
##  cbind(y1, y2).y1 cbind(y1, y2).y2         y1        y2         x1
##1       -0.6264538       10.7962118 -0.6264538 10.796212 -11.240733
##2        0.1836433        8.7759472  0.1836433  8.775947  -9.915768
```

I think `predict.brmsfit` still assumes the melted version of the data (starting at [this line](https://github.com/paul-buerkner/brms/blob/master/R/brmsfit-methods.R#L1471)). Hope this helps!

**Comment by paul-buerkner** [comment]
@aforren1 Thanks for reporting and investigating this issue! I will try to fix it asap.

**Comment by paul-buerkner** [comment]
I have fixed it locally, but need to test it also with old multivariate models. I will push the commit tomorrow when I am sure that everything works smoothly.

**Comment by paul-buerkner** [comment]
It should be working correctly now. Again thanks for reporting this issue!
