### ISSUE TITLE
Average result of conditional effects

### ISSUE THREAD

**Issue by mountaingoat19** [paul-buerkner/brms#1112]
Hi,

 I saw that emmeans average the result over the levels of differents factors when conditionnal_effects select the first one by default.

Can  conditionnal effects do the same thing ? Also can conditionnal effects compare contrast like emmeans does ?

Thanks

**Comment by paul-buerkner** [comment]
Is this related to #552?

**Comment by mountaingoat19** [comment]
Yes,

It's something like jackobailey ask at the end.

**Comment by paul-buerkner** [comment]
I prefer brms-related questions to be asked on https://discourse.mc-stan.org/ rather than on github.

Since your issue seems to be closely related to #552 I am closing this issue here.
