### ISSUE TITLE
Generalized Pareto Distribution

### ISSUE THREAD

**Issue by JackCaster** [paul-buerkner/brms#1113]
Hi,

is there any plan to implement the Generalized Pareto Distribution in `brms` (https://github.com/paul-buerkner/brms/issues/110#issuecomment-348161747)? I am playing around with an extreme values analysis and it looks like extremes collected as Peak Over Threshold are better represented by the GPD instead of the generalized extreme value distribution, which I am so happy to see already in `brms`. 

All the best, JC

**Comment by paul-buerkner** [comment]
No specific plan but could be worth considering in the future.

**Comment by geveh** [comment]
May I kindly ask if there is any progress on the implementation of the Generalized Pareto distribution in `brms`? It might make sense to use the same density as in `extRemes`, see p.27-28 in the [reference manual](https://cran.r-project.org/web/packages/extRemes/extRemes.pdf). Thanks a lot!

**Comment by JackCaster** [comment]
> May I kindly ask if there is any progress on the implementation of the Generalized Pareto distribution in `brms`? It might make sense to use the same density as in `extRemes`, see p.27-28 in the [reference manual](https://cran.r-project.org/web/packages/extRemes/extRemes.pdf). Thanks a lot!

I opened a ticket in the Stan math library repository and there is an interest in implementing the distribution in the standard library (https://github.com/stan-dev/math/issues/2661). Then, I think it will be much easier to incorporate the generalized pareto distribution into brms.

**Comment by paul-buerkner** [comment]
After giving it some thought, I don't think I want to implement the generalized Pareto distribution in brms. The main reason is that the distributions support is parameter dependent, which makes it very awkward for regression modeling. The only family in brms so far that has variable support is the generalized extreme value distribution, which I consider deprecating for this very reason.
