### ISSUE TITLE
Proposal: "mock" backend

### ISSUE THREAD

**Issue by martinmodrak** [paul-buerkner/brms#1115]
Doing full integration tests of calls to `brm` or `brm_multiple` is currently hard as it requires compiling and fitting actual models. However the multiple backend feature should let us easily implement a "mock" backend for testing that would skip compilation and fitting but still go through all the other codepaths, e.g.:

- make standata
- generate Stan code
  - optionally check it for correctness
- cache results / load results from cache

This arised due to needs to test #1114

**Comment by paul-buerkner** [comment]
That is a great idea!
