### ISSUE TITLE
Estimating Phylogenetic Multilevel Models with brms error

### ISSUE THREAD

**Issue by orlinst** [paul-buerkner/brms#1118]
I am trying to follow the example in the vignette "Estimating Phylogenetic Multilevel Models with brms" but I get an error 

```
Error in brm(phen ~ cofactor + (1 | gr(phylo, cov = A)), data = data_simple,  : 
  unused arguments (data = data_simple, family = gaussian(), data2 = list(A = A), prior = c(prior(normal(0, 10), "b"), prior(normal(0, 50), "Intercept"), prior(student_t(3, 0, 20), "sd"), prior(student_t(3, 0, 20), "sigma")))
```
  
  I was first using my own data/tree and was getting this error, so decided to reproduce your example, unsuccessfully.
  
  I hope you have a solution for this?

**Comment by torkar** [comment]
I run the example from the vignette and I don't encounter this (using `cmdstan` as a backend for `brms`, which is the latest version from GitHub.

**Comment by paul-buerkner** [comment]
I assume you have loaded another package that masks brms' `brm` function without another function of the same name.
