### ISSUE TITLE
get_prior shows (flat) priors on some priors that are not flat

### ISSUE THREAD

**Issue by mjskay** [paul-buerkner/brms#1120]
Ran into this on the most recent version of brms and the github version as of today. When I use `get_prior()` on a model spec, priors on some coefficients are listed as "(flat)" even though I have set them:

```r
get_prior(mpg ~ cyl, data = mtcars, prior = prior(normal(0,1), class = b))
```
```
                   prior     class coef group resp dpar nlpar bound       source
                  (flat)         b                                       default
                  (flat)         b  cyl                             (vectorized)
 student_t(3, 19.2, 5.4) Intercept                                       default
    student_t(3, 0, 5.4)     sigma                                       default
```

Previously (not sure when it changed), this would have listed `normal(0,1)` as having been set on the `b` class coefs.

But then if I actually run the model and look at `prior_summary()`, the priors *do* seem to have been set correctly:

```r
m = brm(mpg ~ cyl, data = mtcars, prior = prior(normal(0,1), class = b))

prior_summary(m)
```
```
                   prior     class coef group resp dpar nlpar bound       source
            normal(0, 1)         b                                          user
            normal(0, 1)         b  cyl                             (vectorized)
 student_t(3, 19.2, 5.4) Intercept                                       default
    student_t(3, 0, 5.4)     sigma                                       default
```

Is this intended behavior or am I missing something? Makes it a bit hard to verify priors are correctly set without running the whole model.

**Comment by paul-buerkner** [comment]
`get_prior` has no `prior` argument itself. Perhaps this is why you were confused?

**Comment by mjskay** [comment]
Oooh got it, sorry! Yeah I guess before I was just inspecting the constructed prior object directly instead of passing it through get_prior. My bad!
