### ISSUE TITLE
Add offset either in conditional_effects or make_conditions

### ISSUE THREAD

**Issue by rpetrovska** [paul-buerkner/brms#1122]
Dear Paul,

I am not aware if offset option is included in `conditional_effects` or `make_conditions`, so it would be possible to plot results at different level of offset. Maybe there is already a workaround but it is not included into package description?

I would  appreciate your help.

Cheers,
Roksolana

**Comment by paul-buerkner** [comment]
This works via the `conditions` argument as for all other variables. In the future, please ask brms related questions on https://discourse.mc-stan.org/ unless it is a specific feature request of something you know is not implemented or a bug report.
