### ISSUE TITLE
Allow resp_weights to take a matrix of weights

### ISSUE THREAD

**Issue by jackobailey** [paul-buerkner/brms#1123]
Hi,

In some contexts -- i.e. causal inference -- we sometimes need to weight cases in a second stage model based on inverse probability weights estimated in an initial model. In a Bayesian context, this would produce a distribution of possible weights for each case in the data.

It would be great to be able to pass this on to brms by allowing resp_weights() to take a matrix of weights, not just a vector of point estimates. That way, we could propagate our uncertainty in the weights through to the second stage estimates.

**Comment by paul-buerkner** [comment]
Thanks for this suggestion. How should this matrix of weights be represented in the model?

**Comment by jackobailey** [comment]
It would be exactly the same as now, but the weights term in the data block would be `matrix<lower=0>[N, ~draws~] weights;  // model weights` and I think part in the model block where you multiply the likelihood by the weights would need to include a comma (though could be wrong!) `target += weights[n,] * (normal_lpdf(Y[n] | mu[n], sigma));`

**Comment by paul-buerkner** [comment]
I see what you mean, but what would that imply? There would just be a lot of weights multiply with the likelihood on the nth observations, but that wouldn't really do anything to take into account their uncertainty, would it?

**Comment by jackobailey** [comment]
You're the expert here, but my assumption is that if you have estimated inverse probability weights for N cases, then the distribution of weights for case N would characterise the uncertainty in that case's inverse probability weights. So, multiplying the likelihood by the entire posterior distribution of weights would be like running the analysis over and over and over to see what effect the *probabilistic* weights that we've estimated in the first stage have on the coefficients we estimate in the second, but all at once.

The more general point here is that weights are often themselves uncertain and propagating that uncertainty forward is good.

**Comment by jackobailey** [comment]
A super simple idea with no covariates and summary statistics rather than the whole posterior distribution of weights would be something like this:

```{r}


# Load packages

library(tidyverse)
library(brms)


# Set sample size

N <- 100


# Simulate data

dta <- 
  tibble(
    y = rnorm(N),
    p = sample(0:1, size = N, replace = TRUE)
  )


# First stage model

m1 <- 
  brm(
    formula = p ~ 1,
    family = bernoulli(),
    dta,
    chains = 1,
    iter = 500
  )


# Produce estimate of weights

wts <- 
  fitted(m1) %>% 
  data.frame() %>% 
  select(
    Estimate,
    Est.Error
  )


# Second stage model

m2 <- 
  brm(
    formula = y | weights(mean = wts$Estimate, sd = wts$Est.Error) ~ 1,
    data = dta
  )

```

**Comment by paul-buerkner** [comment]
This is unfortunately not how it works. If you multiply the nth likelihood contribution each with a set of weights (row of the matrix in your case). You effectively add that nth likelihood contribution the the log-posterior `sum(weights[n, ])` times. If that is what you wanted, you could achieve this with just a vector of weights.

My point here is that this is not a way to propagate uncertainty in the weights. A sensible way would be to run `brm_multiple` with the different weights, which is basically what you decribed as "running the analysis over and over and over to see what effect the probabilistic weights that we've estimated in the first stage have on the coefficients we estimate in the second, but all at once."
