### ISSUE TITLE
string - priors for non linear parameters always get checked

### ISSUE THREAD

**Issue by wds15** [paul-buerkner/brms#1124]
I am intending to define priors for non-linear parameters using a string, but I am not allowed to according to brms which complains about population priors not being defined. Here is an example:

```R
library(OncoBayes2)
library(brms)

example_model("single_agent")


bprior_alt <- prior_string("target += beta_lpdf(inv_logit(b_logalpha) | 10, 5) + log_inv_logit(b_logalpha) +  log_inv_logit(-1*b_logalpha)", nlpar="logalpha", check=FALSE) +
    prior(normal(0, 1), nlpar="logbeta", check=FALSE)

make_stancode(bf(num_toxicities | trials(num_patients) ~ logalpha + exp(logbeta) * log(drug_A / 50),
                    logalpha ~ 1,
                    logbeta ~ 1, nl=TRUE), family=binomial, data=hist_SA,
                 prior=bprior_alt)
```

I can probably work around this with the stanvar facility, but it does not look like this is meant to be like it is.

**Comment by paul-buerkner** [comment]
Thanks for opening this issue. I will have to think how to best solve it.

**Comment by wds15** [comment]
Great. Here is my workaround:

```R
bprior_alt <- prior(beta_logit(0.1, 10.0), nlpar="logalpha") + prior(normal(0, 1), nlpar="logbeta")

rprior  <- stanvar(name="response_prior",
                   scode="
real beta_logit_lpdf(vector l, real mu, real kappa) {
   real a = mu * kappa;
   real b = (1.0-mu) * kappa;
   return beta_lpdf(inv_logit(l) | a, b) + sum(log_inv_logit(l) +  log_inv_logit(-1*l));
}
",
                   block="functions")


make_stancode(bf(num_toxicities | trials(num_patients) ~ logalpha + exp(logbeta) * log(drug_A / 50),
                    logalpha ~ 1,
                    logbeta ~ 1, nl=TRUE), family=binomial, data=hist_SA,
              prior=bprior_alt,
              stanvars=rprior)
```

this works fine, but I would have expected that check=FALSE let's me get away with this first approach which is more direct.

**Comment by paul-buerkner** [comment]
Yeah, check = FALSE means something else in this regard. But one way to solve this would be to deactivate the "prior on non-linear parameter check" if at least one prior was set with check = FALSE. Assuming that if someone uses the check = FALSE option, they know what they are doing with regard to priors.

**Comment by wds15** [comment]
As I user I was surprised to see that brms runs checks against my code when I request not to... as you say.

Nothing super urgent, but for a consistent user "handling" shutting off the checks would have been my expectation here.

**Comment by paul-buerkner** [comment]
Should now be fixed. Can you double check?

**Comment by wds15** [comment]
works now! Thanks!
