### ISSUE TITLE
Data "compression"

### ISSUE THREAD

**Issue by StaffanBetner** [paul-buerkner/brms#1125]
In some cases I use data where many observations are identical, and today I use weights to handle that, but since that messes with e.g. LOO it would be useful to have either an option to "compress" the data by number of observation and handle the "decompression" in the transformed data block so that the end result doesn't differ with regard to the data, or set it as a default, since it speeds up the fitting if there are many identical observations.

**Comment by jackobailey** [comment]
Quick question: If I were to use @StaffanBetner's compression technique, could I compute the LOO scores correctly by passing the original data to add_criterion via prepare_predictions' newdata argument?

**Comment by paul-buerkner** [comment]
Yes, I think that might actually work.

**Comment by StaffanBetner** [comment]
I have done some experiments with LOO with compressed data, i.e. dividing the log-likelihood by the numbers of observations (integer) and then repeating them. Seems to work!

**Comment by paul-buerkner** [comment]
I will close this issue for now to clean up the issue tracker a bit since this isn't high priority.
