### ISSUE TITLE
Change default `cores` for `posterior_predict` on Windows

### ISSUE THREAD

**Issue by martinmodrak** [paul-buerkner/brms#1129]
On Windows, setting up new R processes is much more expensive than on Linux  as the new processes need to pass data and setup. This makes running `posterior_predict` in parallel mostly very slow. I would suggest that the default `cores` argument should be `1` on Windows and `getOption("mc.cores", 1)` elsewhere, as I really need to have `mc.cores` high for fitting, but it really does not pay off for `posterior_predict`. In fact, the higher I set `mc.cores`, the slower I get predictions and the slowdown is _substantial_.

Here's an example timing from a recent project of mine:

```
> system.time({print(pp_check(fit_auc1, "stat_grouped", stat = "sd", group = "type", nsamples = 4000, binwidth = 20, 
  cores = 1))})
   user  system elapsed 
   2.23    0.07    2.39 
Warning message:
The following arguments were unrecognized and ignored: cores 
> system.time({print(pp_check(fit_auc1, "stat_grouped", stat = "sd", group = "type", nsamples = 4000, binwidth = 20, 
  cores = 4))})
   user  system elapsed 
   2.15    0.11   13.78 
Warning message:
The following arguments were unrecognized and ignored: cores 
> system.time({print(pp_check(fit_auc1, "stat_grouped", stat = "sd", group = "type", nsamples = 4000, binwidth = 20, 
  cores = 12))})
   user  system elapsed 
   2.35    0.36   35.88 
Warning message:
The following arguments were unrecognized and ignored: cores 
```

Additionally, `pp_check` should not pass the `cores` argument to the `ppc_XXX` functions to avoid the warning...

As usual, happy to file a pull request if you agree with the overall idea.

**Comment by paul-buerkner** [comment]
I agree with the overall idea and I would appreciate a PR to fix it!

**Comment by martinmodrak** [comment]
Note to self - do the same for `log_lik`

**Comment by paul-buerkner** [comment]
I actually happend to fix this myself today in an effort to track down problem with crashes on windows when running posterior prediction functions.
