### ISSUE TITLE
How do I view the control arguments to Stan once brms model is built?

### ISSUE THREAD

**Issue by openpencil** [paul-buerkner/brms#113]
Dear Paul,

Is there a way to view the control arguments passed to Stan from saved brms model objects? Specifically, I want to find the `treedepth` and `adaptdelta` values that were used to build the model. Thanks for any guidance!

best regards,
Jyoti

**Comment by paul-buerkner** [comment]
The control arguments are stored deeply within the `stanfit` object. If `model` is your `brmsfit` object, you can write

````R
attr(model$fit@sim$samples[[1]], "args")$control
```

**Comment by openpencil** [comment]
That's awesome and super-helpful! Thank you for the speedy reply!!
