### ISSUE TITLE
Consider exposing `get_dpar`

### ISSUE THREAD

**Issue by martinmodrak** [paul-buerkner/brms#1131]
Maybe I missed something obvious, but if I understand it correctly, when implementing a custom distribution, one has to suppose that `dpars` are not themselves predicted or manually write code to detect and handle both the "one global value" and "predicted" cases in their `posterior_predict_xx`, `log_lik_xx` implementations. 

The built-in distributions use `get_dpar` that seems to handle this distinction automatically. Maybe it could be exposed to users? 

If so, then the custom families vignette should be updated to reflect this.

As usual, if you like then I will (at some point :-) be happy to file a pull request implementing this.

**Comment by paul-buerkner** [comment]
exposing it sounds like a good idea.

Martin Modrák ***@***.***> schrieb am Do., 1. Apr. 2021,
15:08:

**Comment by paul-buerkner** [comment]
Implemented via #1140.
