### ISSUE TITLE
"error in compileCode" when calling brm()

### ISSUE THREAD

**Issue by kdarras** [paul-buerkner/brms#1132]
After updating all my R packages as well as RStudio today, using Ubuntu 20.04. When I call the brm() function, I get the following error:

make cmd is
  make -f '/usr/lib/R/etc/Makeconf' -f '/usr/share/R/share/make/shlib.mk' CXX='$(CXX14) $(CXX14STD)' CXXFLAGS='$(CXX14FLAGS)' CXXPICFLAGS='$(CXX14PICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX14LDFLAGS)' SHLIB_LD='$(SHLIB_CXX14LD)' SHLIB='filee0b38d717e9.so' OBJECTS='filee0b38d717e9.o'

make would use
if test  "zfilee0b38d717e9.o" != "z"; then \
  echo g++ -std=gnu++14 -shared -L"/usr/lib/R/lib" -Wl,-Bsymbolic-functions -Wl,-z,relro -o filee0b38d717e9.so filee0b38d717e9.o  '/home/kdarras/R/x86_64-pc-linux-gnu-library/3.6/rstan/lib//libStanServices.a' -L'/home/kdarras/R/x86_64-pc-linux-gnu-library/3.6/StanHeaders/lib/' -lStanHeaders -L'/home/kdarras/R/x86_64-pc-linux-gnu-library/3.6/RcppParallel/lib/' -ltbb  -L"/usr/lib/R/lib" -lR; \
  g++ -std=gnu++14 -shared -L"/usr/lib/R/lib" -Wl,-Bsymbolic-functions -Wl,-z,relro -o filee0b38d717e9.so filee0b38d717e9.o  '/home/kdarras/R/x86_64-pc-linux-gnu-library/3.6/rstan/lib//libStanServices.a' -L'/home/kdarras/R/x86_64-pc-linux-gnu-library/3.6/StanHeaders/lib/' -lStanHeaders -L'/home/kdarras/R/x86_64-pc-linux-gnu-library/3.6/RcppParallel/lib/' -ltbb  -L"/usr/lib/R/lib" -lR; \
fi
Error in compileCode(f, code, language = language, verbose = verbose) : 
  /home/kdarras/R/x86_64-pc-linux-gnu-library/3.6/StanHeaders/include/src/stan/model/model_base_crtp.hpp:149:20:   required from here/home/kdarras/R/x86_64-pc-linux-gnu-library/3.6/RcppEigen/include/Eigen/src/Core/DenseCoeffsBase.h:55:30: warning: ignoring attributes on template argument ‘Eigen::internal::packet_traits<double>::type’ {aka ‘__vector(2) double’} [-Wignored-attributes]/usr/bin/ld: /home/kdarras/R/x86_64-pc-linux-gnu-library/3.6/rstan/lib//libStanServices.a(stan_fit.o): relocation R_X86_64_PC32 against undefined hidden symbol `_ZTCN5boost10wrapexceptINS_4math14rounding_errorEEE0_NS_16exception_detail10clone_implINS4_19error_info_injectorIS2_EEEE' can not be used when making a shared object/usr/bin/ld: final link failed: bad valuecollect2: error: ld returned 1 exit statusmake: *** [/usr/share/R/share/make/shlib.mk:6: filee0b38d717e9.so] Error 1
In addition: Warning message:
Rows containing NAs were excluded from the model. 
Error in sink(type = "output") : invalid

**Comment by paul-buerkner** [comment]
This is probably an (r)stan issue. Please ask on https://discourse.mc-stan.org/

**Comment by kdarras** [comment]
thanks, done. Found someone there with apparently the same issue.
