### ISSUE TITLE
Update with cmdstan backend throws error, or requires recompilation

### ISSUE THREAD

**Issue by jflournoy** [paul-buerkner/brms#1135]
If I attempt to `update` a brms object that uses `backend = cmdstan` it either throws the following error:

```
Start sampling
Error: Model not compiled. Try running the compile() method first.
```

or requires recompilation even with trivial changes to the data.

Here is a reproducible example:

```
library(brms)
library(cmdstanr)
cmdstanr::cmdstan_version()
# [1] "2.26.1"
packageVersion('brms')
# [1] ‘2.15.0’

data <- data.frame(y = rnorm(500))
threads <- threading(threads = 4)

compiled <- brms::brm(y ~ 1, data = data, 
                      chains = 1, iter = 100,
                      backend = 'cmdstan',
                      file = 'compiled')

#Clear env and restart R
library(brms)
library(cmdstanr)

newdata <- data.frame(y = rnorm(500, mean = 10))
compiled <- readRDS('compiled.rds')
fit <- update(compiled, newdata = newdata, 
              chains = 1, iter = 1000, warmup = 500)
#Start sampling
#Error: Model not compiled. Try running the compile() method first.

fit2 <- update(compiled, newdata = newdata, 
               chains = 1, iter = 1000, warmup = 500,
               backend = 'cmdstan')
#The desired updates require recompiling the model
#Compiling Stan program...
#Start sampling
```

**Comment by paul-buerkner** [comment]
There are two things going on:

1) The second model needs recompilation because you misspecified the backend. It should be `"cmdstanr"` not `"cmdstan"`. I just pushed a minor fix to github to return an informative error in case of a misspecified backend (or a valid backend when partial matching is possible) instead of a recompilation trigger.

2) cmdstanr seems to be unable to run a model compiled in another R session. @jgabry do you have any idea how to fix this from the brms or cmdstanr side?

**Comment by jgabry** [comment]
Hmm, in general cmdstanr shouldn't need to recompile if it can find the
compiled executable. Is brms doing compilation in a temporary directory? If
so then that would require recompiling if there's a new R session because
it wouldn't be able to find the compiled executable.

>

**Comment by paul-buerkner** [comment]
It seems to write to a tmp-directory indeed. At least this is what str(<CmdStanModel>) tells me. I am not sure I specify that explicitely though somewhere. Here is the code I used to compile cmdstanr model:

```R
# compile Stan model with cmdstanr
# @param model Stan model code
# @return model compiled with cmdstanr
.compile_model_cmdstanr <- function(model, threads, silent = 1, ...) {
  require_package("cmdstanr")
  args <- list(...)
  args$stan_file <- cmdstanr::write_stan_file(model)
  if (use_threading(threads)) {
    args$cpp_options$stan_threads <- TRUE
  }
  eval_silent(
    do_call(cmdstanr::cmdstan_model, args),
    type = "message", try = TRUE, silent = silent >= 2
  )
}
```

**Comment by rok-cesnovar** [comment]
`write_stan_file` will by default store the file in the tmp directory: https://mc-stan.org/cmdstanr/reference/write_stan_file.html

I guess we could compile it to the current directory? Not sure on the name?

**Comment by rok-cesnovar** [comment]
This will however generate a .stan file in the current directory. The other option is to only store the .exe file in the current directory. You can do that by specifying the `dir` argument to `cmdstan_model` (doc for that arg is here: https://mc-stan.org/cmdstanr/reference/model-method-compile.html)

**Comment by jflournoy** [comment]
If the user specifies the `file` option in the brm call, would it make
sense to put the exe file in that same directory, named similarly?

**Comment by paul-buerkner** [comment]
When specifying the file option, it might be ok to store in that directory. Otherwise, I don't think brms should write in a non-temporary directory without the user's permission. 

Perhaps a strange question but I wanted to ask it anyway: Is there a sensible way to store the executible inside the model so that it can be reused immdiately?

**Comment by jgabry** [comment]
> Perhaps a strange question but I wanted to ask it anyway: Is there a sensible way to store the executible inside the model so that it can be reused immdiately?

Can you clarify what you mean by that? Do you mean store the path to the executable inside the brmsfit object? Or am I misunderstanding?

**Comment by jflournoy** [comment]
My guess is he means is there a way to store the actual binary in a slot of
the brms object so it goes wherever the object goes.

**Comment by paul-buerkner** [comment]
yes exactly. sorry for not responding earlier. I know this is a weird
request but perhaps there could be a solution like this in the future.

John Flournoy ***@***.***> schrieb am Fr., 9. Apr. 2021,
16:59:

> My guess is he means is there a way to store the actual binary in a slot of
> the brms object so it goes wherever the object goes.
>

**Comment by jgabry** [comment]
That would be nice, but I'm not sure how to do that since the executable
isn't an R object. How could we store an object that isn't an R object
inside of an R object? Or am I just unaware of some technique that allows
doing that sort of thing (totally possible).

**Comment by jflournoy** [comment]
There are ways to read in binary files like readBin I think. Could read in
the executable but I think you'd have to write it out before using it to
sample.

**Comment by jgabry** [comment]
Yeah good point, I suppose brms could try using readBin and writeBin. I
have no idea if that will work (looking at the doc for readBin it's not
clear to me what settings to use) but it's probably worth trying.

**Comment by rok-cesnovar** [comment]
Great idea @jflournoy! 

This works on Linux:
```r
library(cmdstanr)

file <- file.path(cmdstan_path(), "examples", "bernoulli", "bernoulli.stan")
mod <- cmdstan_model(file)
con <- file(mod$exe_file(), "rb")
bin <- readBin(con, what = raw(), 10e7)
close(con)

# ...

tmpbin <- tempfile()
stantmp <- paste0(tmpbin, ".stan")
file.create(stantmp)
con <- file(tmpbin, "wb")
writeBin(bin, con)
close(con)

processx::run("chmod", args = c("+x", tmpbin))

mod2 <- cmdstan_model(stantmp) # this would need cpp_options specified if threading is on

data_list <- list(N = 10, y = c(0,1,0,0,0,0,0,0,0,1))

fit <- mod2$sample(
  data = data_list,
  seed = 123,
  chains = 4,
  parallel_chains = 2,
  refresh = 500
)
```

**Comment by jgabry** [comment]
Very cool! Works for me on mac too.

**Comment by paul-buerkner** [comment]
works on windows as well, once I replace

```R
con <- file(tmpbin, "wb")
```

with 

```R
con <- file(paste0(tmpbin, ".exe"), "wb")
```

I think it my be worth implementing this workflow somewhere. I would say that cmdstanr itself may be a better place than brms and I would be very interested in your opinion about such a feature.

**Comment by rok-cesnovar** [comment]
> works on windows as well, once I replace

Nice! Makes sense it needs .exe yes.

> I would say that cmdstanr itself may be a better place than brms and I would be very interested in your opinion about such a feature.

I agree, this is something that should be done in cmdstanr. Step 1 is adding support for: 
```
mod <- cmdstan_model(exe_file = "...")
```

Then add something like
```
obj <- mod$serialize()
```
`obj` could then be stored in a brms object and then reused
```
mod <- cmdstan_model(exe_file = obj)
```

Other way would be to read the executable in CmdStanModel  (with `mod$read_exe()` and the brms object would then store that. I think I prefer the serialize approach, but I have to think about it some more.

**Comment by jgabry** [comment]
Great, glad it works on windows too. And yeah I agree that we should add this to cmdstanr.

**Comment by paul-buerkner** [comment]
Do we have a corresponding issue on cmdstanr already, so that this idea doesn't get lost?

**Comment by rok-cesnovar** [comment]
We do not have one in cmdstanr, will make one shortly.

**Comment by rok-cesnovar** [comment]
Added https://github.com/stan-dev/cmdstanr/issues/512

**Comment by paul-buerkner** [comment]
Perfect, thanks! Closing this issue here since there is nothing to be done on the brms side to enable this feature.

**Comment by fweber144** [comment]
It seems like https://github.com/stan-dev/cmdstanr/issues/512 is going to take a while until it is implemented. Until then, would it make sense to implement the suggestion [above](https://github.com/paul-buerkner/brms/issues/1135#issuecomment-815002178) as a workaround? I could try to create a PR for that.

**Comment by rok-cesnovar** [comment]
Yeah, https://github.com/stan-dev/cmdstanr/issues/512 was not given a big priority, as I got the impression that it was not a big necessity for brms, more of a niche thing. I can bump the priority if it would be a bigger gain than I thought.

**Comment by fweber144** [comment]
In my opinion, that would be great, but how does @paul-buerkner think about that?

**Comment by paul-buerkner** [comment]
I think this is actually a good idea! thank you for being willing to
prepare a PR for it.

Frank Weber ***@***.***> schrieb am Di., 5. Juli 2022, 09:41:

**Comment by rok-cesnovar** [comment]
Another, way simpler solution, is for cmdstanr to have a global option "cmdstanr_exe_dir" or something like that, with which the user could point to a non-temp directory to store the executables. That way, the users would explicitly state that they want the executables in a specific folder. This fix I could get in today probably.

**Comment by fweber144** [comment]
Great idea! Thanks

**Comment by wds15** [comment]
Have you tried using the global option `"cmdstanr_write_stan_file_dir"` from cmdstan 0.5.0? That way all brms models will be written to that directory and the compiled models will be stored there as well. Caching of the models like this works like a charm for me with brms. No new feature is needed.

**Comment by fweber144** [comment]
Thank you very much, I haven't been aware of that option. And it works nicely, as you said. A short example for others stumbling across this:

First, run:
```r
library(brms)
options(mc.cores = parallel::detectCores(logical = FALSE))
# Without the following "cmdstanr_write_stan_file_dir" option, an update() call
# in a fresh R session will recompile (which it will not when setting the
# option):
options(cmdstanr_write_stan_file_dir = getwd())
fit_cmdstanr <- brm(rate ~ conc + state,
                    data = Puromycin,
                    backend = "cmdstanr",
                    file = "fit_cmdstanr",
                    file_refit = "on_change",
                    seed = 11403)
```
Now restart the R session and call:
```r
library(brms)
options(mc.cores = parallel::detectCores(logical = FALSE))
# Without the following "cmdstanr_write_stan_file_dir" option, the update() call
# recompiles (which it does not when setting the option):
options(cmdstanr_write_stan_file_dir = getwd())
fit_cmdstanr <- brm(rate ~ conc + state,
                    data = Puromycin,
                    backend = "cmdstanr",
                    file = "fit_cmdstanr",
                    file_refit = "on_change",
                    seed = 11403)
upd_cmdstanr <- update(fit_cmdstanr,
                       formula. = rate ~ conc,
                       newdata = Puromycin,
                       seed = 5933)
```

I only noticed that relative file paths don't seem to be working for the `cmdstanr_write_stan_file_dir` option (I tried `"."` instead of `getwd()` and it didn't work), but that's not a big deal.

So @rok-cesnovar, that `cmdstanr_write_stan_file_dir` option is what you were proposing [above](https://github.com/paul-buerkner/brms/issues/1135#issuecomment-1174747867), right?

**Comment by rok-cesnovar** [comment]
Ah yes, I forgot we added that already. I really thought it was already there, but could not find it. I guess I named it badly :) Embarrassing :)

@fweber144 yeah, no need for an extra option then of course. If Sebastian is using it and says it works great, that is enough proof for me.

**Comment by fweber144** [comment]
No, not embarrassing at all :) Thank you for your help!

Now the only question to @paul-buerkner is if you want this to be documented (at `update.brmsfit()`).

**Comment by paul-buerkner** [comment]
I think it would be nice to document it. Perhaps in the details section of the update function and with a simple example? Would you mind adding that?

**Comment by fweber144** [comment]
No, I can do that :)

**Comment by rok-cesnovar** [comment]
> (I tried `"."` instead of `getwd()` and it didn't work), but that's not a big deal.

Will be fixed in https://github.com/stan-dev/cmdstanr/pull/665
