### ISSUE TITLE
projpred not working with gr() grouping variables

### ISSUE THREAD

**Issue by jonnations** [paul-buerkner/brms#1138]
Hi Paul,

I noticed that the `varsel()` function (from the projpred package) doesn't work with grouping variables that use the `gr()` function. For example:
`fit1 <- brm(count ~ Trt + Age + (1|patient), data = epilepsy)`
`varsel(fit1)`
[1] "30% of terms selected."
[1] "60% of terms selected."
[1] "100% of terms selected."
  size    elpd elpd.se
2    0 -927.35   37.66
3    1 -726.41   25.32
4    2 -726.41   25.32
5    3 -726.41   25.32

Then:
`fit2 <- brm(count ~ Trt + Age + (1|gr(patient)), data = epilepsy)`
`varsel(fit2)`
Error in model.frame.default(data = data, weights = weights, drop.unused.levels = TRUE,  : 
  invalid type (list) for variable 'gr(patient)'

I first noticed this when working with some phylogenetic regression models similar to those in the brms phylogenetic vignette.

I realize this may be a complicated issue with projpred, but I wanted to let you know just in case it is a simple fix.

Thanks!

**Comment by paul-buerkner** [comment]
Thanks! Not sure how to fix this at the moment because the formulas are passed to lme4 and the like who don't understand the `gr` syntax. This issue may become a wontfix..

**Comment by paul-buerkner** [comment]
I don't think that there is actually a fix for this at the moment. Not sure if there is even a fix for it at all given that we need something like ML estimation for models in projpred that need to support the full brms formula. Perhaps there may eventually be a fix from the projpred side. I will close this issue and give it a "wontfix".
