### ISSUE TITLE
Using a predictor as both a fixed effect and (part of) random effect breaks prediction

### ISSUE THREAD

**Issue by martinmodrak** [paul-buerkner/brms#1141]
When I use the same categorical predictor in both fixed eff. and a random eff., prediction breaks in a "fun" way. What happens is that the categorical predictor in `newdata` does NOT get converted to the old factor levels, instead the values are treated as if `factor` was called directly on the values in `newdata`, so the predictions do not match the predictors in `newdata`. First an example, then results of my investigation on why that happens.

```r
set.seed(5454622)
N <- 30
data <- data.frame( y = rnorm(N), 
                    x1 = rep(c("A","B", "C"), length.out = N), 
                    x2 = rep(c("P", "Q"), each = N / 2))
fit <- brm(bf(y ~ x1 + (1 | x1:x2)), data = data)




pred1 <- posterior_epred(fit, newdata = data.frame(x1 = c("A","B")), re_formula = NA)
pred2 <- posterior_epred(fit, newdata = data.frame(x1 = c("B","C")), re_formula = NA)

# Expected: Compute the difference between predictions for x1 = "A", x2 = "P" and x1 = "B", x2 = "P"
unique(pred1[,1] - pred2[,1]) 
# 0 !!! Because both "A" and "B" get separately recoded to the baseline level.

pred3 <- posterior_epred(fit, newdata = data.frame(x1 = "A", x2 = "P"))
# Throws error:
# Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : 
# contrasts can be applied only to factors with 2 or more levels 
```

The error above originates in https://github.com/paul-buerkner/brms/blob/e890376f526444ae477ff961dd8080796c5bc2fd/R/data-predictor.R#L895 where an attempt is made to build the model matrix with the non-recoded factor.

One can work around this by setting the old levels already in `newdata`. Another workaround is to not use `x1:x2` in the model but instead create a new interaction factor `x1_x2 = interaction(x1, x2)` and have `y ~ x1 + (1 | x1_x2)`.

What I believe happens is that the logic to set the `dontcheck` variable at 
https://github.com/paul-buerkner/brms/blob/e890376f526444ae477ff961dd8080796c5bc2fd/R/data-helpers.R#L470 
(which then determines columns that don't get translated to the old data levels) is faulty and should explicitly exclude all fixed effects (instead of just including all grouping terms).

**Comment by paul-buerkner** [comment]
Thanks for opening this issue. I agree on the suggested fix and will think a bit about to check set up `dont_check` correctly.

**Comment by paul-buerkner** [comment]
Should now be fixed on github.
