### ISSUE TITLE
Error when trying to fit a model with a custom beta-binomial family

### ISSUE THREAD

**Issue by quantitative-ecologist** [paul-buerkner/brms#1144]
Hi,

First, thank you for this amazing package. I would also like to say that I am not used to posting issues so I will try to make my post and questions as reproducible as possible.

I have successfully fitted a mixed model with the custom beta-binomial family on a subset of my data following the example provided in this vignette : https://cran.r-project.org/web/packages/brms/vignettes/brms_customfamilies.html#fitting-custom-family-models
The model was run on a laptop under Windows 10 OS. 

However, my dataset is very large, and so, I have to run the model on a remote server with multiple cores and within-chain parallelization. The remote server runs on Cent OS Linux 7. Here is the structure of my model :

`priors <- set_prior("normal(0, 5)", class = "b")`

`model_formula <- brmsformula(hunting_success | vint(4) ~
                                        Zspeed +
                                        Zspace_covered_rate +
                                        Zprox_mid_guard +
                                        Zhook_start_time +
                                        Zsurv_speed +
                                        Zsurv_space_covered_rate +
                                        (1 | map_name) +
                                        (1 | mirrors_id))`

`system.time(beta_binom_mod <- brm(formula = model_formula,
                              family = beta_binomial2,
                              warmup = 3000, 
                              iter = 153000,
                              thin = 100,
                              chains = 4, 
                              inits = "0", 
                              threads = threading(10),
                              backend = "cmdstanr",
                              seed = 20210414,
                              stanvars = stanvars,
                              prior = priors,
                              control = list(adapt_delta = 0.95),
                              data = data))`

For an unknown reason, I get the following error :
 Compiling Stan program...
 
 Semantic error in
 '/localscratch/maxime11.18202117.0/Rtmpzdtb72/model-eede2bbff12.stan', line 34,
 column 17 to column 66:
    -------------------------------------------------
     32:      for (n in 1:N) {
     33:        int nn = n + start - 1;
     34:        ptarget += beta_binomial2_lpmf(Y[nn] | mu[n], phi, vint1[n]);
                           ^
     35:      }
     36:      return ptarget;
    -------------------------------------------------
 
 A returning function was expected but an undeclared identifier
 'beta_binomial2_lpmf' was supplied.
 
 make: *** [make/program:53:
 /localscratch/maxime11.18202117.0/Rtmpzdtb72/model-eede2bbff12.hpp] Error 1
 Error: An error occured during compilation! See the message above for more
 information.
 Timing stopped at: 0.831 1.085 73.23
 Execution halted

When I run the same model with an observation-level random effect using the native binomial family on the same remote server, I don't get an error.

I am sorry if this is a simple error, but I am quite new to using Bayesian models with STAN on remote servers, so I am still learning.

Thank you very much for your help.

**Comment by paul-buerkner** [comment]
Hi, brms related questions would be better suited to be asked on https://discourse.mc-stan.org/ rather than on the brms github page.

**Comment by quantitative-ecologist** [comment]
Ok thank you I will post it there then.
