### ISSUE TITLE
QR decomposition for zero inflation probabilities

### ISSUE THREAD

**Issue by andd3r5** [paul-buerkner/brms#1145]
When trying to use QR decomposition in a ZIP model I noticed it doesn't support QR decomposition when trying to model the zero inflation probability. Is there a way around this or could you please integrate this feature?

**Comment by paul-buerkner** [comment]
This should work I think. Could you please post a minimal reproducible example?

**Comment by andd3r5** [comment]
Thank you for the quick response

```
library(MASS)
library(VGAM)
library(brms)

n <- 100
set.seed(12345)
dat <- data.frame(xc = rnorm(n), xb = rbinom(n, 1, .5))
dat <- within(dat, y <- rzipois(n=n, lambda=exp(.5 * xc + xb), pstr0=0.8))

fit <- brm(bf(y ~ xc + xb, zi~xc+xb, decomp = "QR") , data = dat, family=zero_inflated_poisson())

stancode(fit)
```

looking at the stancode, it doesn't introduce coefficients on the QR scale for zi but only for mu.
```
// initialize linear predictor term
    vector[N] mu = Intercept + XQ * bQ;
    // initialize linear predictor term
    vector[N] zi = Intercept_zi + Xc_zi * b_zi;
```
When trying to formulate it differently I ran into this error
```
form <- bf(y ~., decomp = "QR") + bf(zi ~., decomp = "QR")
fit <- brm(form, data = dat,family=zero_inflated_poisson())
Setting 'rescor' to FALSE by default for this model
Error: The following variables can neither be found in 'data' nor in 'data2':
'zi'
```

**Comment by paul-buerkner** [comment]
You have to use, for example, `bf(y ~., decomp = "QR") + lf(zi ~ ., decomp = "QR")`
