### ISSUE TITLE
Error in loo_R2: validate_ll(log_ratios): All input values must be finite

### ISSUE THREAD

**Issue by brochhagen** [paul-buerkner/brms#1147]
I'm trying to use `loo_r2()` on a logistic regression model fit with `brms`, but this raises:

`Error in validate_ll(log_ratios) : All input values must be finite.`
`Calls: loo_R2 ... psis.matrix -> importance_sampling.matrix -> validate_ll`
`Execution halted`

I'm not sure if this a bug or if there's something wrong with my fit. Do you pointers of what may causing this, or known workarounds?

For the sake of completeness, the offending fit can be downloaded from here, but it's quite large (168MB)
https://drive.google.com/file/d/1yuHD1HX6Lh4g3O8MioOxqi4oFkis7QAQ/view?usp=sharing

This is in a conda environment with r-brms (2.14.4, r40he524a50_0, conda-forge)

[UPDATE]
I just noticed that the same issue crops up with `loo()`. Here's the model summary

[1] "### Summary ###"
 Family: bernoulli 
  Links: mu = logit 
Formula: colex ~ tmetric + tDP + tDG 
   Data: df (Number of observations: 286721) 
Samples: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
         total post-warmup samples = 4000

Population-Level Effects: 
          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
Intercept     5.35      0.05     5.25     5.45 1.01     2031     2007
tmetric       2.08      0.03     2.02     2.13 1.00     1981     1696
tDP           7.94      0.14     7.67     8.22 1.01     1685     1916
tDG           7.39      0.14     7.13     7.65 1.00     1990     2180

**Comment by paul-buerkner** [comment]
This may be because of numerical issues and I would prefer you to ask this question on https://discourse.mc-stan.org/ unless it can be verified as a bug in brms.
