### ISSUE TITLE
file_refit = "on_change" after changing priors

### ISSUE THREAD

**Issue by clementbbp** [paul-buerkner/brms#1148]
Hi,

I'm a relatively new user to brms and bayesian statistics, so please excuse if my request is already implemented in the package somewhere, or is unfeasible. 

Would it make sense to implement a feature, perhaps similar to file_refit = "on_change", which updates the model not only after changing the formula, but also after calibrating the priors? In my short experience, you may find the priors too wide or constraining on the posterior and want to calibrate them, but you don't have the benefit of being able to save the model immediately using file = " ", as this would simply load the old model. I think it would be a nice addition to the workflow, but I might be wrong since I can also imagine that you want to think very hard about choosing your priors before finally "saving" the model. 

Any answer would be greatly appreciated!

//Clem

**Comment by paul-buerkner** [comment]
changes to the prior should already be recognized by file_refit =
"on_change". if you don't think that's the case please provide a minimal
reproducible example.

clementbbp ***@***.***> schrieb am Sa., 24. Apr. 2021, 10:00:
