### ISSUE TITLE
correlated random effects in nonlinear models

### ISSUE THREAD

**Issue by schmettow** [paul-buerkner/brms#116]
currently, i am using brms to fit exponential learning curves. As I have multiple learning curves, I use participant-level random effects on all three parameters. While I was using | and not ||, a correlation between random effects seems not to be estimated. Am I missing something? Otherwise, that would be (another) great feature of brms.

`F_nonlinear <-
  formula(Duration ~ exp(etamaxp) + exp(-inv_logit(etarate) * (trial + pexp)))

F_priors <-
  c(set_prior("normal (0, 10)", nlpar = "etamaxp"),
    set_prior("normal (0, 100)", nlpar = "pexp"),
    set_prior("normal (0, 3)", nlpar = "etarate"))

F_ME <- 
  list(etamaxp  ~ VSA + (1|Part),
       etarate ~ SM + (1|Part),
       pexp ~ (1|Part))

`

**Comment by paul-buerkner** [comment]
For **brms** <= 0.10.0, it is not possible to estimate correlations between random effects of different non-linear parameters. However, with the soon to be released **brms** 1.0.0 update (already available via the github dev version ), you can do it as follows:

 ```R
`F_nonlinear <-
formula(Duration ~ exp(etamaxp) + exp(-inv_logit(etarate) * (trial + pexp)))

F_priors <-
c(set_prior("normal (0, 10)", nlpar = "etamaxp"),
set_prior("normal (0, 100)", nlpar = "pexp"),
set_prior("normal (0, 3)", nlpar = "etarate"))

F_ME <-
list(etamaxp ~ VSA + (1|ID1|Part),
etarate ~ SM + (1|ID1|Part),
pexp ~ (1|ID1|Part))
```

The name `ID1` is arbitrary. You can put in anything you like as long as it is the same across the terms for which you want to estimate correlations.

**Comment by schmettow** [comment]
brilliant! See if i can set up the tool chain to compile your package.

**Comment by paul-buerkner** [comment]
If you can compile brms models, compiling brms itself should work as well.

Am 09.09.2016 18:18 schrieb "schmettow" <notifications@github.com>:

**Comment by paul-buerkner** [comment]
Just in case you are unsure how to install the dev version, here is the relevant line:

```R
devtools::install_github("paul-buerkner/brms")
```

Feel free to close this issue after successfully fitting the desired model.

**Comment by schmettow** [comment]
Great! Many thanks!
