### ISSUE TITLE
make_standata error in validate_prior

### ISSUE THREAD

**Issue by julianquandt** [paul-buerkner/brms#1161]
I think this might be related to / occuring after fixing #1124 

when using `make_standata` recently I get the following error:

```
Error in validate_prior_special.btl(x$dpars[[dp]], prior = prior, data = data,  : 
  formal argument "require_nlpar_prior" matched by multiple actual arguments
```

example:

```
formula_test <- bf(weight ~ Time)

d_stan <- make_standata(formula_test, 
                         family = gaussian(),
                         data = ChickWeight)
```

When running `debug(make_standata)` and manually executing

```
  prior <- .validate_prior(prior, bterms = bterms, data = data, 
    sample_prior = sample_prior)
``` 

in the console instead of 

``` 
  prior <- .validate_prior(prior, bterms = bterms, data = data, 
    sample_prior = sample_prior, require_nlpar_prior = FALSE)
```

it works, so I guess is that this is something along the lines of `require_nlpar_prior` here getting passed on to `validate_prior_special` and conflicts with the argument there or something?

**Comment by paul-buerkner** [comment]
Did you try it with the latest github version already?

**Comment by julianquandt** [comment]
well, I thought so (I was on 2.15.0) but I wasn't. In any case, it works with 2.15.5, sorry for bothering you before updating!
