### ISSUE TITLE
Using Stan's OpenCL support in brms 

### ISSUE THREAD

**Issue by rok-cesnovar** [paul-buerkner/brms#1166]
The same way `brms` can take advantage of threading, it could also take advantage of the OpenCL backend in Stan. This backend is still evolving, but there are models that could benefit right now with more to come later.

A few points bullet points to start the discussion:

 - the model must be compiled with `cpp_options = list("STAN_OPENCL"=TRUE)`, similar to how threading needs STAN_THREADS https://github.com/paul-buerkner/brms/blob/b59c4b10d71abb1e23128c6a0ae4f0ceb6871350/R/backends.R#L94

 - Instead of [threads_per_chain](https://github.com/paul-buerkner/brms/blob/b59c4b10d71abb1e23128c6a0ae4f0ceb6871350/R/backends.R#L225), you need to specify the OpenCL platofrm and device IDs via the `opencl_ids` argument. This is just a vector with w integers, `c(0,1)` specifies that we are using the plaftorm 0 and device 1. For 90%+ of cases this will be c(0,0) as users tend to only have a single GPU and dont have OpenCL drivers for the CPU.

  - the OpenCL backend would for now use the non-threaded brms generated code (the mix of threading and OpenCL is very promising but not well tested or explored for now)

  - for better performance and GPU utilization the model should be written with vectorized calls (I think @paul-buerkner mentioned that he would like to avoid different code-gen for different backends so this might have to wait for rstan 2.26 to hit CRAN). 

There is a vignette on how to use OpenCL with cmdstanr available here: https://mc-stan.org/cmdstanr/articles/opencl.html

I will post some "motivation" results in the next few days.

**Comment by paul-buerkner** [comment]
Thank you! I am existed for your "motivation" results! :-)

**Comment by rok-cesnovar** [comment]
Here is one simple if a bit farfetched :)

```
library(brms)
library(cmdstanr)

n <- 300000
k <- 10
X <- matrix(rnorm(n * k), ncol = k)
y <- rbinom(n, size = 1, prob = plogis(10 * X[,1] + 9 * X[,2] + 8 * X[,3] + 7 * X[,4] + 6 * X[,5] + 5 * X[,6] + 4 * X[,7] + 3 * X[,8] + 2 * X[,9] + 2 * X[,10] + 1))

code <- make_stancode(y ~ X1 + X2 + X3 + X4 + X5 + X6 + X7 + X8 + X9 + X10 , data = data.frame(y, X), family = bernoulli(), refresh = 0)
data <- make_standata(y ~ X1 + X2 + X3 + X4 + X5 + X6 + X7 + X8 + X9 + X10, data = data.frame(y, X), family = bernoulli(), refresh = 0)
class(data) <- NULL

file_cpu <- write_stan_file(code, hash_salt = "cpu")
file_cl <- write_stan_file(code, hash_salt = "opencl")

mod_cpu <- cmdstan_model(file_cpu)
mod_cl <- cmdstan_model(file_cl, cpp_options = list(stan_opencl=TRUE))

fit_cl <- mod_cl$sample(data = data, seed = 123, parallel_chains = 4, opencl_ids = c(0,0))
fit_cpu <- mod_cpu$sample(data = data, seed = 123, parallel_chains = 4)
```

The timing:
```
> fit_cl$time()$total
[1] 174.8288
> fit_cpu$time()$total
[1] 1216.565
```
So around 7 times faster for 4 chains.

One aspect of the OpenCL backend is also that you can run more chains in almost the same time:
```
> fit_cl <- mod_cl$sample(data = data, seed = 123, chains = 8, parallel_chains = 8, opencl_ids = c(0,0))
> fit_cl$time()$total
[1] 183.737
```
But not sure how much running 8, 16 or more chains is useful.

**Comment by paul-buerkner** [comment]
Brilliant. This looks easy enough to implement. My first intuition would be to add an `opencl` (or otherwise named) argument to `brm` which is conveniently specified by a call to a function such as `use_opencl()` (or otherwise named) that takes information such as `opencl_ids` and other stuff OpenCl might need. Bascially, the same structure as for threading. Is there anything additional we need to take into account?

**Comment by rok-cesnovar** [comment]
Compiling with STAN_OPENCL and providing the IDs is the only thing a user can do and will probably remain so for the foreseeable future.

Other than that I would just document to have a look at the cmdstanr vignette and Stan docs on parallelization with OpenCL: 
- https://mc-stan.org/docs/2_26/cmdstan-guide/parallelization.html#opencl
- https://mc-stan.org/docs/2_26/stan-users-guide/opencl.html

Those should guide the users through installing OpenCL for the most common cases. If not, I (we) want to know where there is anything missing. I have to add a few Windows-specific lines to the vignette based on @bachlaw's feedback but otherwise these docs should cover all of the most common cases (NVIDIA & AMD GPUs on Linux and Windows).

**Comment by wds15** [comment]
Can this be combined with threading?

**Comment by wds15** [comment]
I mean the threading argument of brms which brings within-chain parallelization, yes. So for now @paul-buerkner would have to allow only one of them... fair point. Combining this would be great, but that can wait, of course.

**Comment by rok-cesnovar** [comment]
>  I ran OpenCL with both 1 chain of 8 parallel chains and Rok's combo of 4 chains with 4 parallel chains, as well as the plain CPU example.

To clarify, `chains = 1` with `parallel_chains = 8` is the same as `chains = 1` with `parallel_chains = 1`. This `parallel_chains` argument in cmdstanr basically has the same meaning as cores in brms/rstan. We wanted to avoid the name `cores` as its name is not really appropriate in the world of within-chain parallelization and GPUs and such. `chains = 4, parallel_chains = 2 ` means that we start 2 chains and only start the 3rd one once one of the first two finishes.

>  It offers an GTX 760 

This is a solid low to mid-level GPU a few years back and the performance here is expected. I failed to mention above that I was running an AMD Radeon VII, a mid to high range GPU from 2 or 3 years back that at the time sold for about 600$ before all this crypto nonsense.

With higher-end GPUs its very unlikely you will be able to utilize it fully, because we have parameter values moving from the CPU global memory to the GPU global memory and the gradients moving back. At the very least, the NUTS sampling is still running on the CPU and if you are lucky the entire gradient is calculate on the GPU. You will get nice speedups as shown above, but if you open the GPU system monitor you will probably not see 70%+ utilization with a single chain.

If we oversubscribe the GPU (run a lot of chains) you are able to mask these data transfers to and from the GPU. So for example when we are computing the GLM for chain 1 and 2, chains 3 and 4 are transferring parameter values. This is the ideal case. Obviously, once you hit the GPUs limit, oversubscribing is no longer productive.

What number of chains will be ideal is really hard to say as it depends on the problem and the GPU being used.
