### ISSUE TITLE
possible typo when defining the lognormal density

### ISSUE THREAD

**Issue by ASKurz** [paul-buerkner/brms#1169]
In the `brms_families.Rmd` file, you define the **lognormal** density as 

$$f(y) = \frac{1}{\sqrt{2\pi}\sigma x} \exp\left(-\frac{1}{2}\left(\frac{\log(y) - \mu}{\sigma}\right)^2\right).$$ 

If I have followed your notational style correctly, I believe there's a typo where the $x$ in the equation should be a $y$. The revised equation would be:

$$f(y) = \frac{1}{\sqrt{2\pi}\sigma y} \exp\left(-\frac{1}{2}\left(\frac{\log(y) - \mu}{\sigma}\right)^2\right).$$

**Comment by paul-buerkner** [comment]
Indeed. Thank you. Should now be fixed.
