### ISSUE TITLE
Boundaries and random effects

### ISSUE THREAD

**Issue by plogacev** [paul-buerkner/brms#117]
Thanks a lot for this great package. I've found brms extremely useful.
I was wondering how brms handles (upper and lower) boundaries on parameters in the presence of random effects. 
For example, in a brm() call such as the one below, is there a canonical way to make sure that the value of 'asymptote' is never smaller than zero, even in the presence of random effects?
The reason I ask is that some more complex models of this form produce a substantial number of divergent transitions, unless I constrain the parameters asymptote and invrate within the stan code.

```R
m <- brm(formula = dprime ~ asymptote * (1 - exp(-1/invrate * (time_ms - intercept)) ),
                nonlinear = list(asymptote ~ 1 + (1|subject), 
                                        invrate ~ 1 + (1|subject), 
                                        intercept ~ 1 + (1|subject)),
                prior = list(set_prior(nlpar = "asymptote", "lognormal(1.5, 0.5)", class = "b", lb = 0),
                                 set_prior(nlpar = "intercept", "lognormal(6.5, 0.5)", class = "b", lb = 0, ub = 3000),
                                 set_prior(nlpar = "invrate", "normal(7, .8)", class = "b", lb = 10, ub = 3000)),
                ...)
```

**Comment by paul-buerkner** [comment]
The boundaries are just affecticing the "fixed" effects, unfortunately. I did not come up with a solution yet how to *reasonably* put boundaries on "random" effects. How do you constrain the random effects parameters within the Stan code?

What you could do is putting more informative priors on the random effects standard deviations (`class = sd` in `set_prior`) to constrain parameters to more reasonable values without having to use hard boundaries. 

I also have some suggestions how to get around all this for your particular model. How about
```R
formula = dprime ~ exp(asymptote) * (1 - exp(-1/exp(invrate) * (time_ms - exp(intercept))))
```
That way you ensure positivity of all 3 parameters (it seems you want all of them to be positive) and then just model things on the "log" scale. 

Also, the prior of `invariate` seems strange to me. A lower bound of 10 but a prior with a mean of 7. Why did use such a prior?

**Comment by plogacev** [comment]
I was afraid that's what you'd say. :) I'll try the random effects standard deviation solution.

I constrain the parameters pretty much the same way you suggested, i.e., by using exp() where the constraint is one-sided, and logit() where the parameter needs to be in a particular range. This, of course, becomes somewhat cumbersome in situations where one of the parameters needs to be 0 in some conditions. In such situations, I don't transform when all predictors are 0.

The prior of invrate is indeed strange - it should have been a lognormal distribution. Thanks for catching it. And thanks again for this great package!
