### ISSUE TITLE
FR for robust = TRUE argument in hypothesis

### ISSUE THREAD

**Issue by andymilne** [paul-buerkner/brms#1170]
`hypothesis` is a very convenient function for obtaining the posterior distributions of effects of interest, which may be some (nonlinear) combination of the model's raw output, and is much easier (and less prone to user-error) than doing this by hand with `posterior_epred` or `posterior_linpred`. When `hypothesis()` is used in this way, it would be useful for there to be an option to return the median, rather than the mean, of the effect of interest. My request is for a `robust = TRUE` argument in hypothesis, with the default being `robust = FALSE`.

**Comment by paul-buerkner** [comment]
Good idea! Will add this in the next release.

**Comment by paul-buerkner** [comment]
Done :-)
