### ISSUE TITLE
Support 'log_prob' and friends for CmdStanR backend

### ISSUE THREAD

**Issue by paul-buerkner** [paul-buerkner/brms#1184]
Currently, cmdstanr does not support `log_prob` and friends but #1176 gave me an idea.

Since, except for threading, brms generated Stan code is fully compatible with rstan 2.19+, we can just compile the Stan code with rstan before using `log_prob` etc. when needed. And even threaded models would be easy to support by just recreating the Stan code with threading deactivated. 

@wds15 @jgabry @rok-cesnovar do you think that could work?

**Comment by wds15** [comment]
That sounds like a plan. The only thing that comes to my mind worth considering are the film functions. I am not sure if all of these wer already in 2.19 compared to what we have now in cmdstan…but if you anyway regenerate the model on the fly even that cane be solved. Btw, why 2.19? Rstan is at 2.21 on cran…and hopefully it will move to 2.27 (a miracle we wait for a while as it’s so hard).

**Comment by paul-buerkner** [comment]
Thanks for your feedback! I am not sure I understand what the "film" functions are. Can you explain? The reason I am ensuring compatibility with rstan 2.19 is that on some of my machine 2.21 wasn't stable enough so I keep using rstan 2.19 whenever I have to use rstan and cmdstanr otherwise.

**Comment by wds15** [comment]
Oh…I meant glm

**Comment by paul-buerkner** [comment]
I see :-D Yes, most of them already work in rstan 2.19.

**Comment by rok-cesnovar** [comment]
2.19 supported:
```
bernoulli_logit_glm_lpmf(array[] int, matrix, real, vector) => real
bernoulli_logit_glm_lpmf(array[] int, matrix, vector, vector) => real
neg_binomial_2_log_glm_lpmf(array[] int, matrix, real, vector, real) => real
neg_binomial_2_log_glm_lpmf(array[] int, matrix, vector, vector, real) => real
neg_binomial_2_log_glm_lpmf(array[] int, matrix, real, vector, real) => real
neg_binomial_2_log_glm_lpmf(array[] int, matrix, vector, vector, real) => real
normal_id_glm_lpdf(vector, matrix, real, vector, real) => real
normal_id_glm_lpdf(vector, matrix, vector, vector, real) => real
poisson_log_glm_lpmf(array[] int, matrix, real, vector) => real
poisson_log_glm_lpmf(array[] int, matrix, vector, vector) => real
```

2.21 supports the same as 2.19

2.22 and newer additionally support a few more. The 4 GLM functions above gained new signatures
```stan
bernoulli_logit_glm_lpmf(int, matrix, real, vector) => real
bernoulli_logit_glm_lpmf(int, matrix, vector, vector) => real
bernoulli_logit_glm_lpmf(array[] int, row_vector, real, vector) => real
bernoulli_logit_glm_lpmf(array[] int, row_vector, vector, vector) => real
neg_binomial_2_log_glm_lpmf(int, matrix, real, vector, real) => real
neg_binomial_2_log_glm_lpmf(int, matrix, vector, vector, real) => real
neg_binomial_2_log_glm_lpmf(array[] int, row_vector, real, vector, real) => real
neg_binomial_2_log_glm_lpmf(array[] int, row_vector, vector, vector, real) => real
normal_id_glm_lpdf(real, matrix, real, vector, vector) => real
normal_id_glm_lpdf(real, matrix, vector, vector, vector) => real
normal_id_glm_lpdf(vector, row_vector, real, vector, vector) => real
normal_id_glm_lpdf(vector, row_vector, vector, vector, vector) => real
poisson_log_glm_lpmf(int, matrix, real, vector) => real
poisson_log_glm_lpmf(int, matrix, vector, vector) => real
poisson_log_glm_lpmf(array[] int, row_vector, real, vector) => real
poisson_log_glm_lpmf(array[] int, row_vector, vector, vector) => real
```
Essentially, the first args can be a scalar (real for normal_id, int elsewhere) and the second arg can be a row_vector. There are 2 additional GLM functions:
```stan
categorical_logit_glm_lpmf(int, row_vector, vector, matrix) => real
categorical_logit_glm_lpmf(int, matrix, vector, matrix) => real
categorical_logit_glm_lpmf(array[] int, row_vector, vector, matrix) => real
categorical_logit_glm_lpmf(array[] int, matrix, vector, matrix) => real
ordered_logistic_glm_lpmf(int, row_vector, vector, vector) => real
ordered_logistic_glm_lpmf(int, matrix, vector, vector) => real
ordered_logistic_glm_lpmf(array[] int, row_vector, vector, vector) => real
ordered_logistic_glm_lpmf(array[] int, matrix, vector, vector) => real
```

**Comment by paul-buerkner** [comment]
Thanks @rok-cesnovar for your insights!

I have now added this featur to the brms dev version.
