### ISSUE TITLE
Use the 'bayesplot' package on the backend of most plotting functions

### ISSUE THREAD

**Issue by paul-buerkner** [paul-buerkner/brms#119]
This is mostly already done with the implementation of the `pp_check` method and in PR #84, which can be merged as soon as **bayesplot** is on CRAN.

**Comment by jgabry** [comment]
Soon, I promise! Sorry for the delay. Thanks for being patient. I've had
way too much going on recently to be able to finalize everything.

**Comment by paul-buerkner** [comment]
All good, I could have done more for the finalization myself. ;-)
