### ISSUE TITLE
Different behavior with (un)loaded brms package with backend cmdstanr

### ISSUE THREAD

**Issue by mutlusun** [paul-buerkner/brms#1193]
Dear Paul,

Many thanks for your great package and all the effort you put in this.

In the latest version, I noticed a different behavior when the brms package is loaded or not and using the cmdstanr backend. AFAIK, this does not happen with the rstan backend.

First script / file:

```r
library("brms")

myd <- epilepsy
myd$count1 <- myd$count + round(runif(nrow(myd), 0, +4), 0)

fit0 <- brm(
  mvbind(count, count1) ~ 1 + zAge + zBase * Trt + (1|patient), 
  data = myd, 
  family = poisson(),
  backend = "cmdstanr",
  save_model = "loaded"
)
```

This works as intended and produces the following stan code: 
[loaded.txt](https://github.com/paul-buerkner/brms/files/6741062/loaded.txt)

Second script / file:

```r
data("epilepsy", package = "brms")
myd <- epilepsy
myd$count1 <- myd$count + round(runif(nrow(myd), 0, +4), 0)

fit0 <- brms::brm(
  brms::mvbind(count, count1) ~ 1 + zAge + zBase * Trt + (1|patient), 
  data = myd, 
  family = poisson(),
  backend = "cmdstanr",
  save_model = "not-loaded"
)
```

This script produces the following stan code:
[not-loaded.txt](https://github.com/paul-buerkner/brms/files/6741406/not-loaded.txt)

But results in the following errors:

```
 Warning: Chain 1 finished unexpectedly!

Warning: Chain 2 finished unexpectedly!

Warning: Chain 3 finished unexpectedly!

Warning: Chain 4 finished unexpectedly!

Warning: Use read_cmdstan_csv() to read the results of the failed chains.
Error in rstan::read_stan_csv(out$output_files()) :
  csvfiles does not contain any CSV file name
In addition: Warning messages:
1: All chains finished unexpectedly! Use the $output(chain_id) method for more information.

2: No chains finished successfully. Unable to retrieve the fit.
```

Unfortunately, I don't know which output file I could read in to examine the problem further. Neither in the working directory nor in the home directory a csv file was created.

I think loading or not loading the brms package should not result in different stan code.

Thanks for your help!

**Comment by paul-buerkner** [comment]
This may be a cmdstanr issue. Did you already try it with the latest github version of brms and cmdstanr?

**Comment by mutlusun** [comment]
Dear Paul,

Many thanks for your fast response. I executed the following commands, but results did not change:

```r
remotes::install_github("paul-buerkner/brms", force=TRUE)
remotes::install_github("stan-dev/cmdstanr", force=TRUE)
cmdstanr::install_cmdstan(cpp_options = list("ARCH" = "arm64"), cores = 4, overwrite=TRUE)
```

I am working on a Mac M1 laptop. I'm not sure whether the hardware has an effect on this. So far, I have experienced this issue only with multivariate models.

**Comment by jgabry** [comment]
If I fit this in CmdStanR directly I get an error from Stan about mismatched dimensions (maybe brms is suppressing these messages?): 

```r
library(cmdstanr)
data("epilepsy", package = "brms")
myd <- epilepsy
myd$count1 <- myd$count + round(runif(nrow(myd), 0, +4), 0)

code <- brms::make_stancode(
  brms::mvbind(count, count1) ~ 1 + zAge + zBase * Trt + (1|patient), 
  data = myd
)
data <- brms::make_standata(
  brms::mvbind(count, count1) ~ 1 + zAge + zBase * Trt + (1|patient), 
  data = myd
)

mod <- cmdstan_model(write_stan_file(code))
fit <- mod$sample(data = data)
```
```
Chain 1 Exception: mismatch in number dimensions declared and found in context; processing stage=data initialization; variable name=Y; dims declared=(236); dims found=(236,2) (in '/var/folders/s0/zfzm55px2nd2v__zlw5xfj2h0000gn/T/RtmpIjVnI4/model-e37e79362adf.stan', line 6, column 2 to column 14)
Warning: Chain 1 finished unexpectedly!

Chain 2 Exception: mismatch in number dimensions declared and found in context; processing stage=data initialization; variable name=Y; dims declared=(236); dims found=(236,2) (in '/var/folders/s0/zfzm55px2nd2v__zlw5xfj2h0000gn/T/RtmpIjVnI4/model-e37e79362adf.stan', line 6, column 2 to column 14)
Warning: Chain 2 finished unexpectedly!

Chain 3 Exception: mismatch in number dimensions declared and found in context; processing stage=data initialization; variable name=Y; dims declared=(236); dims found=(236,2) (in '/var/folders/s0/zfzm55px2nd2v__zlw5xfj2h0000gn/T/RtmpIjVnI4/model-e37e79362adf.stan', line 6, column 2 to column 14)
Warning: Chain 3 finished unexpectedly!

Chain 4 Exception: mismatch in number dimensions declared and found in context; processing stage=data initialization; variable name=Y; dims declared=(236); dims found=(236,2) (in '/var/folders/s0/zfzm55px2nd2v__zlw5xfj2h0000gn/T/RtmpIjVnI4/model-e37e79362adf.stan', line 6, column 2 to column 14)
Warning: Chain 4 finished unexpectedly!
```

**Comment by paul-buerkner** [comment]
Thanks Jonah. I think it looks like a bug and I think I now see why. The reason is that the `mvbind` pattern is searched but `brms::mvbind` is present, so this leads to trouble in setting up the multivariate model. In short, even when brms is not loaded, you don't need `brms::` in front of `mvbind` as the latter is used merely as a symbol not actually as a function here. I do see of course that this is confusing and will adjust the code accordingly.

**Comment by paul-buerkner** [comment]
Should now be fixed on github.

**Comment by mutlusun** [comment]
@jgabry : Many thanks for your further investigation!
@paul-buerkner : Thank you for your fix! I haven't been aware that `mvbind` is not a function but a pattern :)

**Comment by paul-buerkner** [comment]
brms pattern matches `mvbind` at the right place instead of evaluating the function. `mvbind` is also a function but outside of its primary use-case, it just behaves as `cbind`.
