### ISSUE TITLE
Persistent storage of compiled cmdstan models

### ISSUE THREAD

**Issue by StaffanBetner** [paul-buerkner/brms#1194]
In the latest cmdstan version recompilation is avoided if it is already compiled (within that R session). Since a lot models I fit are quite similar across R projects it would be useful to be able to set a persistent location of compiled cmdstan models. Perhaps as an option variable.

**Comment by paul-buerkner** [comment]
Wouldn't that be more of a cmdstanr rather than a brms feature?

**Comment by StaffanBetner** [comment]
Not necessarily, since `brms:::.compile_model_cmdstanr` calls `cmdstanr::write_stan_file`, where the second argument is `dir` with default `tempdir()`.

**Comment by StaffanBetner** [comment]
I did a test in a fork, and it seems to work. https://github.com/StaffanBetner/brms/commit/d9627e6a096104790ac9235ea472cc9f8e3969ab#diff-cc4b551bd32fdb7c1607d3eec6cf29ff4d7e8c1abab05651d704191a8123821c

**Comment by StaffanBetner** [comment]
I made an issue at the cmdstanr repo instead, as I think it is better suited there. I will close this one. https://github.com/stan-dev/cmdstanr/issues/535

**Comment by StaffanBetner** [comment]
It is now implemented in cmdstanr!
