### ISSUE TITLE
Retrieve parameter names corresponding to each prior

### ISSUE THREAD

**Issue by DominiqueMakowski** [paul-buerkner/brms#1195]
Hi Paul, we are in the process of [re-working](https://github.com/easystats/insight/pull/394) one of our easystats postprocessing function that retrieves priors from models and matches them with their respective parameters (the aim is to have a table with each parameter, their posterior summary, and their prior summary on the same line).

However, I couldn't find in brms/rstan a pre-existing way to obtain the one to one correspondence between a given prior and a parameter name, so I started writing a helper function that does the following:

1. Takes the `prior_summary` table
2. Attempts at reconstructing the parameter's name by pasting the columns in the right order
3. Rematches the priors to the parameters

This works ok for simpler models, but it seems to be a bit more tricky for more complex models. Anyway, you will find the "reconstructing" code below, but my question was, before I dive deeper into this, whether there was something already existing that I might have missed. Something that bridges the priors with each parameter? Or that can help making the correspondence?

Thanks!

```r
.match_brms_priors_to_params <- function(prior_summary) {
  # Rename for easier manipulation
  pr <- prior_summary
  
  # Initialize empty string
  p <- rep("", nrow(pr))
  
  # class == Intercept -------------------------
  p <- ifelse(pr$class == "Intercept",
              paste0(
                "b",
                ifelse(pr$dpar != "", paste0("_", pr$dpar), ""),
                "_Intercept"
              ),
              p
  )
  
  # class == b ------------------------------
  # Are there other possible parameters?
  p <- ifelse(
    pr$class == "b",
    paste0("b_",
           ifelse(pr$dpar != "", paste0(pr$dpar, "_"), ""),
           pr$coef),
    p)
  
  # class == L ------------------------------
  p <- ifelse(pr$class == "L", paste0("cor_", pr$group, "_"), p)
  
  
  # class == sigma ------------------------------
  # TODO: I only saw it alone, but possibly can have other parameters
  p <- ifelse(pr$class == "sigma", "sigma", p)
  
  # class == sd  -------------------------------
  p <- ifelse(
    pr$class == "sd",
    paste0("sd_",
           pr$group,
           "__",
           ifelse(pr$dpar != "", paste0(pr$dpar, "_"), ""),
           pr$coef),
    p)
  
  # class == sds  -------------------------------
  # TODO: Fix coef for sds_
  # TODO: Fix beta for smooth term (bs_coef instead of b_coef)
  # p <- ifelse(
  #   pr$class == "sds",
  #   paste0("sds", ifelse(pr$coef  != "", paste0("_", pr$coef), "")),
  #   p)
  
  p
}
```

Example on simple model:
```r
library(brms)

model <- brms::brm(mpg ~ vs + (1|cyl), data = mtcars, refresh = 0)

insight::find_parameters(model)
```
```
$conditional
[1] "b_Intercept" "b_vs"       

$random
[1] "r_cyl.4.Intercept." "r_cyl.6.Intercept." "r_cyl.8.Intercept." "sd_cyl__Intercept" 

$sigma
[1] "sigma"
```

```r
priors <- brms::prior_summary(model)
priors$Param <- .match_brms_priors_to_params(priors)
as.data.frame(priors)
```
```
                    prior     class      coef group resp dpar nlpar bound  source             Param
1                                 b                                       default                b_
2                                 b        vs                             default              b_vs
3 student_t(3, 19.2, 5.4) Intercept                                       default       b_Intercept
4    student_t(3, 0, 5.4)        sd                                       default             sd___
5                                sd             cyl                       default          sd_cyl__
6                                sd Intercept   cyl                       default sd_cyl__Intercept
7    student_t(3, 0, 5.4)     sigma                                       default             sigma
```

**Comment by paul-buerkner** [comment]
Unfortunately, the correspondence between priors and parameter names is only implictely defined via the `stan_prior()` calls all over the Stan code generating functions of brms. What is more, this correspondence is a little bit inconsistent at times because the structure was not designed to make it easy to trace back priors: It is comparably easy for `stan_prior()`  to figure out which prior(s) to use but the inverse of this correspondence is much harder.

**Comment by DominiqueMakowski** [comment]
Thanks for the answer, we'll then move forward and slowly implement our code that tries to do that, keeping in mind the likely caveats and edge-cases :) At least we know that we're not reinventing the wheel or missing an easy solution!
