### ISSUE TITLE
posterior_epred() does not retain level names from an ordinal model

### ISSUE THREAD

**Issue by mjskay** [paul-buerkner/brms#1196]
I have noticed that `posterior_epred()` does not retain the level names from ordinal models in the way that `posterior_predict()` does. For example:

``` r
library(brms)

d = data.frame(
  x = ordered(c(rep("a", 20), rep("b", 10), rep("c", 5)))
)

m = brm(x ~ 1, data = d, family = cumulative)

# posterior_predict retains the level names
str(posterior_predict(m))
#>  num [1:4000, 1:35] 2 3 2 1 2 1 3 1 1 1 ...
#>  - attr(*, "dimnames")=List of 2
#>   ..$ : NULL
#>   ..$ : NULL
#>  - attr(*, "levels")= chr [1:3] "a" "b" "c"

# posterior_epred does not, replacing them with c("1", "2", "3")
str(posterior_epred(m))
#>  num [1:4000, 1:35, 1:3] 0.597 0.481 0.65 0.514 0.579 ...
#>  - attr(*, "dimnames")=List of 3
#>   ..$ : NULL
#>   ..$ : NULL
#>   ..$ : chr [1:3] "1" "2" "3"
```

<sup>Created on 2021-07-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

For some reason I thought it did, but neither the CRAN nor github version seems to. This would be nice to have especially once posterior hits cran, since wrapping the output of `posterior_epred()` in an `rvar` would result in an array-like rvar with rows as predicted probabilities and columns as categories.

**Comment by paul-buerkner** [comment]
Thanks This should now be fixed, i.e., the third output dimension of `posterior_epred` now has appropriate dimnames.

**Comment by mjskay** [comment]
Awesome, thanks!
