### ISSUE TITLE
RcppEigen installed but not registered

### ISSUE THREAD

**Issue by DrVangsness** [paul-buerkner/brms#1198]
Am planning to run a truncated regression using brms, but am hitting some error messages along the way. Here are some key pieces of information regarding the error:

Running **R version 4.1.0** in **RStudio 1.4.1717**
Updated all libraries and dependencies

I'm experiencing the following error message:

> Compiling Stan program... 
Error in .fun(model_code = .x1) : 
Eigen not found; call install.packages('RcppEigen') 

In response, I ran **install.packages("RcppEigen")** and ensured that it was active using both the **library(RcppEigen)** command and RStudio's **active packages window**. Can confirm that **RcppEigen 0.3.3.9.1** is active.

Still, the same error message appears.

**Comment by paul-buerkner** [comment]
I don't think this is related to brms but rather that R or Stan cannot find Eigen properly. You may want to ask this question on https://discourse.mc-stan.org/ and provide more details with regard to operating system and general setup.
