### ISSUE TITLE
r-universe.dev

### ISSUE THREAD

**Issue by aaelony-catasys** [paul-buerkner/brms#1199]
Learned about the opensci site https://r-universe.dev/ at useR 2021 and didn't see a `brms` footprint there yet.  

Might be interesting to consider as a(nother) place to promote this amazing package (?) .

**Comment by aaelony-catasys** [comment]
nevermind, I see it there already in https://r-universe.dev/builds/

**Comment by paul-buerkner** [comment]
I like the idea. Right now it's hidden somewhere where it is not easy to find. I would think that add a "Stanverse" of Stan-related R packages (including brms) could be very sensible. @jgabry @rok-cesnovar @martinmodrak  would you think?

**Comment by aaelony-catasys** [comment]
yes, I also like the idea that r-universe.dev will _automatically render package vignettes_ :)

**Comment by paul-buerkner** [comment]
I will close this issue for now to clean up the issue tracker a bit since I don't this this has high priority.
