### ISSUE TITLE
Lasso over different groups of parameters

### ISSUE THREAD

**Issue by jlevy44** [paul-buerkner/brms#1201]
Hi there! I've been looking to add a lasso prior for one of my models, for a moderately high dimensional omics dataset (order of 100 markers). I am looking add interactions to the model, but wanted to penalize interactions differently than the main effects (mostly keep main effects, but zero out many interactions; two different lasso penalties). I noticed that the lasso penalty needs to be applied across all class "b_" coefficients, but only one penalization can be specified https://discourse.mc-stan.org/t/help-with-lasso-example-in-brms/3987. Is there any way to add separate lasso priors here for main effects and interactions? I've tried a few implementations, but having some trouble here. Thanks!

**Comment by paul-buerkner** [comment]
Hi, please continue asking brms related questions on Stan discourse.
