### ISSUE TITLE
Ordinal models and tidy output

### ISSUE THREAD

**Issue by moleps** [paul-buerkner/brms#1202]
I am having trouble outputting ordinal models to gtsummary. The authors of gtsummary and broom.mixed suggested filing an issue here. 

```
data(mtcars)
mtcars$cyl <- factor(mtcars$cyl,ordered = T)
mtcars$gear <- factor(mtcars$gear,ordered=F)

test <- brm(cyl~gear+hp+wt,
    family = cumulative(link = "logit", threshold = "flexible"),
    data=mtcars)

gtsummary::tbl_regression(test)
```
throws errors and doesn't capture variable names.

Adding a random effect allowed variable names to be captured,  but still throws errors.

```
test2 <- brm(cyl~(1|gear)+hp+wt,
            family = cumulative(link = "logit", threshold = "flexible"),
            data=mtcars)
> broom.mixed::tidy(test2)
```

I could not recreate the errors using linear models, neither just fixed nor both fixed and random models. Thus something funky is going on with the tidier not capturing the ordinal models correctly. 

```
test3 <- brm(mpg~gear+hp+disp+cyl,
             data=mtcars)

test4 <- brm(mpg~gear+disp+hp+(1|cyl),
             data=mtcars)

broom.mixed::tidy(test3)
broom.mixed::tidy(test4)

tbl_regression(test3)
tbl_regression(test4) 
```

Please also see [link](https://github.com/ddsjoberg/gtsummary/issues/935)

**Comment by paul-buerkner** [comment]
This doesn't look like a brms issue to me, or is there something you think needs to be fixed from the brms side?

**Comment by paul-buerkner** [comment]
Closing this as I don't see how this should be fixed from the brms side. Please feel free to reopen is you have the feeling that this is incorrect.
