### ISSUE TITLE
Installation and Running on Big Sur 11.3.1

### ISSUE THREAD

**Issue by davidjohnbaker1** [paul-buerkner/brms#1203]
I recently installed `brms`  and tried to run the first example in the vignette with the following session information:

```
R version 4.1.0 (2021-05-18)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Big Sur 11.3.1

rstan_2.21.2        
ggplot2_3.3.5        
StanHeaders_2.21.0-7 
brms_2.15.0          
Rcpp_1.0.7 
```

After loading the package then fitting the first model `fit1`, I get the following error:

```
Compiling Stan program...
recompiling to avoid crashing R session
Start sampling

SAMPLING FOR MODEL 'd9869b1d2d63e6b2ea0cb42ec5ba5e22' NOW (CHAIN 1).
[1] "Error in sampler$call_sampler(args_list[[i]]) : "               
[2] "  VECTOR_ELT() can only be applied to a 'list', not a 'promise'"
error occurred during calling the sampler; sampling not done
```
I have yet to be able to find a solution to this problem. Any help would be greatly appreciated.

**Comment by paul-buerkner** [comment]
This does not look like a brms issue but more like a problem of getting Stan to run. I suggest you ask for help at https://discourse.mc-stan.org/. Perhaps this question has already been answered there even.

**Comment by adamhsparks** [comment]
I see that this is closed, can I ask where the solution was found? I'm now having the same issue with brms whereas before the models ran fine, suddenly they don't now and I can't find a solution to this but I see this is closed, which makes me think a solution was found somewhere else, possibly? I didn't find any solution at the suggested link above.

**Comment by adamhsparks** [comment]
For anyone else who stumbles upon this issue like I did. I seem to have found a way. I reinstalled _rstan_ and installed from source, not binary, on one of my M1 MacBooks and it works.
