### ISSUE TITLE
emmeans: multivariate support

### ISSUE THREAD

**Issue by mattansb** [paul-buerkner/brms#1207]
I know we've discussed this elsewhere, and I know that due to `brms`' complex multivariate modeling it can be difficult to support multivariate models in `emmeans`, but perhaps this support can be extended *only* to models using the `mvbind(y1, y2) ~ x1 + x2` formulation?

**Comment by paul-buerkner** [comment]
It wouldn't be worth the effort to just implemenet it for such simple models. I must admit though that I forgot again why we benefit from some multivariate version if we can just run emmeans for all the univariate submodels of a multivariate submodel already.

**Comment by mattansb** [comment]
I'm currently working on a tutorial for APIM models in `brms` - being able to compare slopes between outcomes is useful in such cases (I'm sure there are more).

Then again, the estimates' posteriors can be extracted from the `emmGrid` object and compared manually.

**Comment by paul-buerkner** [comment]
I see. I will check what is necessary to support that. Can you give me any hints on where to start?

**Comment by mattansb** [comment]
1. `.extract_par_terms` will need to be able to work with a vector of `resp`s.

2. The internal to `emm_basis.brmsfit` would need to add /change this:
```R
post.beta <- posterior_linpred(m, newdata = grid, resp = resp, ...) # resp is a vector

# Reshape to 2-d matrix
post.beta <- matrix(post.beta, ncol = nrow(grid) * length(resp))

X <- matrix(replicate(length(resp), diag(length(bhat))), nrow = nrow(grid))

misc$ylevs = list(rep.meas = resp)
```

(I tried to get a working example going, but I can't get it without (1) first)
