### ISSUE TITLE
Running Problem with BRMS

### ISSUE THREAD

**Issue by william-denault** [paul-buerkner/brms#121]
Hello, I have tried to run the exemple 

library("brms")
data("kidney")
fit1 <- brm(formula = time | cens(censored) ~ age * sex + disease
+ (1 + age|patient),
data = kidney, family = lognormal(),
prior = c(set_prior("normal(0,5)", class = "b"),
set_prior("cauchy(0,2)", class = "sd"),
set_prior("lkj(2)", class = "cor")),
warmup = 1000, iter = 2000, chains = 4,
control = list(adapt_delta = 0.95))

(from the vignette) So it launch the C++ code, however I got this error:

Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! file56c5a902950.cpp:8:39: fatal error: stan/model/model_header.hpp: No such file or directory
 #include <stan/model/model_header.hpp>
                                       ^
compilation terminated.
make: *** [file56c5a902950.o] Error 1
Warning message:
running command 'make -f "C:/PROGRA~1/R/R-33~1.1/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-33~1.1/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="file56c5a902950.dll" OBJECTS="file56c5a902950.o"' had status 2 
In addition: Warning messages:
1: In if (nchar(CXX) > 0) return(TRUE) :
  the condition has length > 1 and only the first element will be used
2: running command 'C:/PROGRA~1/R/R-33~1.1/bin/i386/R CMD SHLIB file56c5a902950.cpp 2> file56c5a902950.cpp.err.txt' had status 1 

Do you have any idea from could it come from ?
Regards William

**Comment by paul-buerkner** [comment]
This is likely because you do not have a C++ compiler installed. See the FAQ section of the **brms** Readme (bottom of https://github.com/paul-buerkner/brms) for instructions on how to get one.
