### ISSUE TITLE
Multiple response variables in meta-analysis.

### ISSUE THREAD

**Issue by dmcalli2** [paul-buerkner/brms#1212]
# Motivation

Where original (ie derived from individual-participant data - IPD)
effect estimates are to be meta-analysed, this is straighforward in brms
provided these estimates relate to a single response variable with a
single predictor. The `se()` function can be used to specify the known
standard errors. However, where there are 2 or more response variables,
and the correlation is available (eg from the outputs of a bivariate
regression model where the effect of treatment on two outcomes has been
estimated), this does not appear to be easy to specify. I think that a
similar situation arises where a single response variable has been
regressed on multiple predictor variables and more than one of the
coefficients is of interest (since the standard errors for these are
also correlated).

I have had a look at the `fcor()` function, wondering if I could treat
the responses as correlated repeated outcomes to address this problem, but I think it would be
difficult to specify the right hand side of the model. This might get
particularly complicated if the meta-analysis has a hierarchical
structure.

Would it be possible/desirable to add a function to allow users to specify known
correlations on the LHS of the model, a bit like `se()`?

Here is a minimal example where there are two trials. For each
trial, the effect estimate, standard error for the effect estimate, and
correlation between the standard errors are known (from some notional
IPD analysis)

``` r
library(brms)
```

    ## Loading required package: Rcpp

    ## Loading 'brms' package (version 2.15.0). Useful instructions
    ## can be found by typing help('brms'). A more detailed introduction
    ## to the package is available through vignette('brms_overview').

    ## 
    ## Attaching package: 'brms'

    ## The following object is masked from 'package:stats':
    ## 
    ##     ar

``` r
mydf <- data.frame(trial = 1:2, 
             response_1 = c(1.405, 0.047), 
             response_2 = c(-1.652, -0.169), 
             se_1 = c(0.642, 0.055), 
             se_2 = c(0.697, 0.114), 
             cor = c(-0.921, -0.480))

mydf
```

    ##   trial response_1 response_2  se_1  se_2    cor
    ## 1     1      1.405     -1.652 0.642 0.697 -0.921
    ## 2     2      0.047     -0.169 0.055 0.114 -0.480

## Specifying the formulae using the brms code

``` r
form1 <- brmsformula(response_1 | se(se_1) ~ 1)
form2 <- brmsformula(response_2 | se(se_2) ~ 1)
```

### Assume independence - currently possible

``` r
mod_indep <- brm(formula = form1 + form2 + set_rescor(FALSE), data = mydf)
```

``` r
summary(mod_indep)
```

    ##  Family: MV(gaussian, gaussian) 
    ##   Links: mu = identity; sigma = identity
    ##          mu = identity; sigma = identity 
    ## Formula: response_1 | se(se_1) ~ 1 
    ##          response_2 | se(se_2) ~ 1 
    ##    Data: mydf (Number of observations: 2) 
    ## Samples: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
    ##          total post-warmup samples = 4000
    ## 
    ## Population-Level Effects: 
    ##                     Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
    ## response1_Intercept     0.06      0.05    -0.05     0.16 1.00     3711     2756
    ## response2_Intercept    -0.21      0.11    -0.43     0.02 1.00     3772     2611
    ## 
    ## Family Specific Parameters: 
    ##                 Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
    ## sigma_response1     0.00      0.00     0.00     0.00 1.00     4000     4000
    ## sigma_response2     0.00      0.00     0.00     0.00 1.00     4000     4000
    ## 
    ## Samples were drawn using sampling(NUTS). For each parameter, Bulk_ESS
    ## and Tail_ESS are effective sample size measures, and Rhat is the potential
    ## scale reduction factor on split chains (at convergence, Rhat = 1).

### Assume correlation same across all trials, but estimate this - currently possible, but not necessary as know the correlations from the IPD analysis

``` r
mod_estim <- brm(formula = form1 + form2 + set_rescor(TRUE), data = mydf)
```

``` r
summary(mod_estim)
```

    ## Warning: There were 345 divergent transitions after warmup. Increasing
    ## adapt_delta above 0.8 may help. See http://mc-stan.org/misc/
    ## warnings.html#divergent-transitions-after-warmup

    ##  Family: MV(gaussian, gaussian) 
    ##   Links: mu = identity; sigma = identity
    ##          mu = identity; sigma = identity 
    ## Formula: response_1 | se(se_1) ~ 1 
    ##          response_2 | se(se_2) ~ 1 
    ##    Data: mydf (Number of observations: 2) 
    ## Samples: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
    ##          total post-warmup samples = 4000
    ## 
    ## Population-Level Effects: 
    ##                     Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
    ## response1_Intercept     0.06      0.05    -0.04     0.17 1.01      617     1128
    ## response2_Intercept    -0.20      0.11    -0.41     0.00 1.01      594     1136
    ## 
    ## Family Specific Parameters: 
    ##                 Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
    ## sigma_response1     0.00      0.00     0.00     0.00 1.00     4000     4000
    ## sigma_response2     0.00      0.00     0.00     0.00 1.00     4000     4000
    ## 
    ## Residual Correlations: 
    ##                             Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS
    ## rescor(response1,response2)    -0.74      0.26    -0.99    -0.03 1.00      241
    ##                             Tail_ESS
    ## rescor(response1,response2)       86
    ## 
    ## Samples were drawn using sampling(NUTS). For each parameter, Bulk_ESS
    ## and Tail_ESS are effective sample size measures, and Rhat is the potential
    ## scale reduction factor on split chains (at convergence, Rhat = 1).

### Proposed, provide observed correlations.

For a bivariate response, could provide correlations as a vector where
each element is the correlation (as in the example below). For &gt;2
responses can be a list where each element of the list is a matrix. If
using tidyr, it would be easy to store the matrices in a list column
within a tibble.

```
mod_known <- brm(form_arm + form_inter + set_rescor(cor), data = mydf)
```

**Comment by paul-buerkner** [comment]
Thank you for opening this issue. Although a bit cluncy in syntax, the `fcor()` correlation structure was written with this use case in mind. You can handle multivariate responses by bringing them in long format and using a factor variable to indicate different response variables. I do not intend to add another feature to support these kind of models. Accordingly, I will close this issue.

**Comment by dmcalli2** [comment]
Thanks Paul,
That is fair enough. Congratulations on a great package!
