### ISSUE TITLE
Bug: control_params not working with cmdstanr as backend

### ISSUE THREAD

**Issue by agranholm** [paul-buerkner/brms#1215]
A minor bug report:
control_params (or rather, control_params.brmsfit) works with brms models fit with rstan, but not with models fit with cmdstanr as the backend - it appears to be due to different organisation of the stanfit object.

Example based on the first example model from brm documentation:
`
prior1 <- prior(normal(0,10), class = b) + prior(cauchy(0,2), class = sd)
fit1 <- brm(count ~ zAge + zBase * Trt + (1|patient), data = epilepsy, family = poisson(), prior = prior1, backend = "rstan", control = list(adapt_delta = 0.99))
control_params(fit1)
`

Gives valid output, whereas backend = "cmdstanr" outputs NULL, despite the control parameters being stored in the fit1$fit object at a different place than in the same fit object from rstan.
Using latest non-development versions of R/RStan/cmdstanr/cmdstan/brms.

**Comment by paul-buerkner** [comment]
I think this works in the dev version(s). At least for me.
