### ISSUE TITLE
stanvars before likelihood

### ISSUE THREAD

**Issue by jsocolar** [paul-buerkner/brms#1216]
Would it be hard or a Very Bad Idea to allow `stanvar(block = model, postion = 'pre_likelihood')` to accept a string that would insert Stan code immediately before the likelihood function?

The reason I ask is because this would enable linear-predictor-munging to coerce structures that currently require unlooped custom likelihoods to structures that enable looping (for example, reformatting the linear predictor for detection in an occupancy model into an array structure where rows are single sites; now the likelihood can be written to loop over sites).

I have no pressing need for being able to do this, by the way; if it feels clumsy then I'm happy for you to just close.  I just thought it might be a cheaper way to increase the flexibility of what's possible for users working with custom likelihoods.

**Comment by paul-buerkner** [comment]
Did you try out `block = "likelihood"`?

**Comment by jsocolar** [comment]
Can't believe I overlooked this!  When I skimmed the documentation I thought that the `block` argument accepted exactly the blocks of a `Stan` program, and then within block my options were start or end.  Didn't see `likelihood` sitting as an option between `model` and `genquant`!
