### ISSUE TITLE
`.extract_model_data()`: Offsets bug

### ISSUE THREAD

**Issue by fweber144** [paul-buerkner/brms#1220]
Doesn't line https://github.com/paul-buerkner/brms/blob/8cb2d4b9277f41390542d463f9b8b42a682a6ef2/R/projpred.R#L197 have to read `offset <- as.vector(sdata[[paste0("offsets", usc_resp)]])`, i.e. with `"offsets"` instead of `"offset"`? Otherwise, the offsets are not written to the projpred `"refmodel"`:
```r
library(brms)
set.seed(5687)
epilepsy$offs_col <- rnorm(nrow(epilepsy))
fit <- brm(count ~ zAge + zBase * Trt + offset(offs_col),
           data = epilepsy, family = poisson(),
           chains = 2, iter = 500, seed = 802)
ref <- get_refmodel(fit)
all(ref$offset == 0)
```
gives `TRUE`.

**Comment by paul-buerkner** [comment]
Thanks. Should now be fixed.
