### ISSUE TITLE
Strange behavior with scale() and poly()

### ISSUE THREAD

**Issue by Aisa2** [paul-buerkner/brms#1221]
First noted in: https://discourse.mc-stan.org/t/strange-behavior-with-scale-and-poly-in-brms-model/24164

Attached data file provides data for minimal reprex. This is a simulated word recall task where 24 lists of 10 words each are presented to participants; each list is followed immediately by free recall.
[wordDataFake.csv](https://github.com/paul-buerkner/brms/files/7086560/wordDataFake.csv)

- PID = participant's ID
- block = list of words presented
- position = position of the word in its list
- recalled = whether the word was recalled or not.

We expect primacy and recency effects for each list, this is modeled here by a quadratic effect of position.

To run the model:

`
mypriors <- c(set_prior("normal(0.27, 0.5)", 
                        class = "Intercept"),
              set_prior("normal(0, 1)", class = "b")
)
mod.logitBayesRecall0_scalepoly <- brm(formula = recalled ~ 1 +
                         scale(poly(position, 2)) + (1 | PID),  
                     data=wordDataFake, 
                     family = bernoulli(link = "logit"),
                     prior = mypriors,
                     sample_prior = "yes",
                     warmup = 500, 
                     iter = 3000, 
                     chains = 2,
                     inits= "0",
                     seed = 123)
`

The summary function works:

`
summary(mod.logitBayesRecall0_scalepoly)
`

But conditional_effects does not:
`
conditional_effects(mod.logitBayesRecall0_scalepoly)
`
`
Error in poly(position, 2) : 
  'degree' must be less than number of unique points
`

**Comment by paul-buerkner** [comment]
Thanks. Will look into this.

**Comment by paul-buerkner** [comment]
This is not a bug in brms actually because brms uses post-processing methods of the stats package for special functions such as `scale` and `poly` that require the original data when evaluating the new data to work correctly. This seems to fail when multiple such functions are nested within one another and even happens for `lm`:

```
mod <- lm(recalled ~ 1 + scale(poly(position, 2)), wordDataFake)
predict(mod, newdata = data.frame(position=1))
Error in poly(position, 2) : 
  'degree' must be less than number of unique points
```

Perhaps you can ask if there is a fix on some of the R help mailing lists?

**Comment by Aisa2** [comment]
Ah, I see. Thanks for looking into it!

**Comment by n-kall** [comment]
I have run into something similar, but the same formula works fine in lme4. @paul-buerkner do you think this is brms issue?

``` r
library(brms)
library(lme4)
data(sleepstudy, package = "lme4")

cubic_formula <- bf(
  Reaction ~ poly(Days, 3) + (poly(Days, 3) | Subject)
)

cubic_lmer <- lmer(
  formula = cubic_formula,
  data = sleepstudy
)

predict(cubic_lmer, newdata = sleepstudy[1,])
#>        1 
#> 254.4158

cubic_fit <- brm(
  formula = cubic_formula,
  data = sleepstudy, seed = 123,
  refresh = 0
)
#> Start sampling

posterior_predict(cubic_fit, newdata = sleepstudy[1,])
#> Error in poly(Days, 3): 'degree' must be less than number of unique points
```

<sup>Created on 2024-11-08 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by paul-buerkner** [comment]
Thanks! This should now be fixed.
