### ISSUE TITLE
Using cmdstanr with loo on brms models?

### ISSUE THREAD

**Issue by 4CCoxAU** [paul-buerkner/brms#1224]
Hi,

I posted this on StanForum, but thought it relevant here too:

"When fitting a brms model with backend = “cmstanr”, I don’t seem to be able to perform loo cross-validation. I get the following error: “Error: Backend ‘rstan’ is required for this method.” As the cmdstanr backend provides such an efficient speed-up, I’d love to be able to use this backend with loo.

Is there a specific reason why this backend can’t be used with loo? Are there any workarounds, or is it in development? Thanks to anyone who knows anything!"

**Comment by paul-buerkner** [comment]
Please update to the latest brms version and it will likely work.

**Comment by 4CCoxAU** [comment]
Should it also work when performing loo(x, moment_match = T)?

**Comment by paul-buerkner** [comment]
That is what I ment.

4CCoxAU ***@***.***> schrieb am Fr., 3. Sept. 2021, 11:27:

**Comment by rok-cesnovar** [comment]
Though, at least as far as I understand, this will still use rstan right?  cmdstanr needs to support the `log_prob` functionalities of rstan before we can support this natively. Its in the works but there are a few other more urgent features before that.

**Comment by 4CCoxAU** [comment]
Hmm, I only get the error when loo(x, moment_match = T), not for loo(x) alone.

**Comment by paul-buerkner** [comment]
yes. brms implements moment matching for cmdstanr by recompiling with rstan
first.

4CCoxAU ***@***.***> schrieb am Fr., 3. Sept. 2021, 11:31:

**Comment by 4CCoxAU** [comment]
I see - well that explains it! Thanks for your time and responses!
