### ISSUE TITLE
Export all the required function for multi-core loo

### ISSUE THREAD

**Issue by zfarley** [paul-buerkner/brms#1225]
Hi,

This is my first post here so my apologies if I miss something.
Windows 10, brms 2.16.1, loo 2.4.1, R 4.0.3, Rstudio 1.4.1106

@martinmodrak suggested creating this post after our discussion here: https://discourse.mc-stan.org/t/brms-loo-moment-match-t-does-not-appear-to-work/24013/6.

When setting `moment_match = TRUE` with either `loo` or `add_criterion` with a brms model with family  = "dirichlet", I get the following error (untested for other families):

Error in checkForRemoteErrors(val) : 
  2 nodes produced errors; first error: could not find function "bind"
Error: Moment matching failed. Perhaps you did not set 'save_pars = save_pars(all = TRUE)' when fitting your model?

Here are my sources for creating the bind function:
https://discourse.mc-stan.org/t/dirichlet-regresion-using-brms/8591/3
https://github.com/paul-buerkner/brms/issues/1016

As well as a past post regarding issues with `moment_match` and `save_pars` being resolved:
https://discourse.mc-stan.org/t/error-with-loo-moment-match/18914/18 

Here is some reproducible code:
```
library(DirichletReg)
library(brms)

# Generate values from dirichlet distribution
a <- as.data.frame(rdirichlet(100, c(5,5,10,2,1)))

# Create a predictor variable
set.seed(1234)
a$P1 <- sample(1:100, 100, replace = T)

# Create a grouping variable
a$G1 <- 1:100

# Create bind function
bind <- cbind

# Fit model - run time ~ 1 minute
fit <- brm(bind(V1, V2, V3, V4, V5) ~ P1 + (1|G1), data = a, seed = 1234, iter = 1000,
           chains = 4, cores = 4, family = "dirichlet", save_pars = save_pars(all = TRUE))

# Check loo, 6 bad pareto-k values
loo(fit, cores = 4)

# Check loo with moment matching
# Produces error:
# Error in checkForRemoteErrors(val) : 
#  4 nodes produced errors; first error: could not find function "bind"
# Error: Moment matching failed. Perhaps you did not set 'save_pars = save_pars(all = TRUE)' when fitting your model?
loo(fit, moment_match = T, cores = 4)

# Attempt with add_criterion
# Same error
fit2 <- add_criterion(fit, "loo", moment_match = T, cores = 4)
```

Any help would be greatly appreciated.
Thanks

**Comment by paul-buerkner** [comment]
without parallelization is should work that is set cores = 1 in
add_criterion. exporting all the required functions is quite difficult and
I am not sure how to solve this in general.

zfarley ***@***.***> schrieb am Fr., 3. Sept. 2021, 21:14:

**Comment by zfarley** [comment]
Thank you for the help.

I have been able to successfully apply `moment_match = T` to the test dataset by not using parallelization.

Where I am now having trouble is with past models I have run which I have already added `loo` (and `waic`) without `moment_match = T` and saved as `.rds` files via the following code (picking up from the initial post):

```
fit <- add_criterion(fit, c("loo", "waic"), cores = 4)
saveRDS(fit, "fit.rds")
```
I then read the models back in (after having cleared, closed, and restarted R days later):
```
fit <- readRDS("fit.rds")

# without overwrite = T, loo does not change
new_fit <- add_criterion(fit, "loo", overwrite = T, moment_match = T)
```
This produces the following error:
Error in private:public : argument of length 0

Please let me know if providing a model that produces this error would be helpful.

Thank you

**Comment by paul-buerkner** [comment]
I have no idea what this error means. Still happens with cores = 1? If yes, then a reprex (oder small fitted model that reproduces this) could help.

**Comment by zfarley** [comment]
So I uninstalled both R (updated to 4.1.1) and Rstudio and reinstalled.

I am still getting that error for attached model `Test1.rds`
```
Error in private:public : argument of length 0
```
I am also getting this error with a different model (`Test2.rds`, attached):
```
Error in object@.MISC$stan_fit_instance$log_prob(upars, adjust_transform,  : 
  Exception: Exception: dirichlet_lpmf: prior sample sizes[5] is 0, but must be > 0!  (in 'model418081d3bea_45d1ae0d89d3bd9953f51a741c66973d' at line 12)
  (in 'model418081d3bea_45d1ae0d89d3bd9953f51a741c66973d' at line 145)

Error: Moment matching failed. Perhaps you did not set 'save_pars = save_pars(all = TRUE)' when fitting your model?
```
In both models, I fit them, added both `loo` (without `moment_match = T`) and `waic`, then saved them.
I then read them back in and attempted to:
```
fit2 <- brms::add_criterion(fit, "loo", overwrite = T, moment_match = T)
```
This produces the errors above.

In order to assess if there was an issue with either the model being read into R or how it had been fit previously, I re-ran them and tried to add `loo` with `moment_match = T` directly after fitting (`cores` set to default). This produced the same errors.

Here are my model specifications if it helps
```
  Test1 <- brms::brm(bind(Cat1, Cat2, Cat3, Cat4, Cat5) ~  P1 + (1|G1) + (1|G2),
                             data = Data1, seed = 1234, control = list(max_treedepth = 15, adapt_delta = 0.99), iter = 8000,
                             chains = 4, cores = 4, family = "dirichlet", save_pars = save_pars(all = TRUE))

  Test2 <- brms::brm(bind(Cat1, Cat2, Cat3, Cat4, Cat5) ~  P1 + (1|G1),
                             data = Data2, seed = 1234, control = list(max_treedepth = 15, adapt_delta = 0.99), iter = 8000,
                             chains = 4, cores = 4, family = "dirichlet", save_pars = save_pars(all = TRUE))
```

I am trying to attach the models but `.rds` are not supported. I tried putting them in a zip file, no luck. What is the best way to get you the models?

Thank you for your help.

**Comment by zfarley** [comment]
Just as an update, I tried finding more about the second error indicating a prior sample size was 0.

Based on these posts:
https://discourse.mc-stan.org/t/initializing-simplex-dirichlet/6289
https://discourse.mc-stan.org/t/simplex-regression/1560

I double checked I do not have any true zeros in any of my response categories which I do not.

This vignette on the Dirichlet distribution tells me where the dirichlet_lpmf is derived from but unfortunately, I do not know how to access the prior sample sizes or why they would be 0.
https://mc-stan.org/docs/2_27/functions-reference/dirichlet-distribution.html

I tried the following which did not find any values equal to 0:
```
subset(as_draws_df(Test2)[5],  as_draws_df(Test2)[5] == 0)
```
I am unsure whether this is related to sampling or something in my data.

**Comment by zfarley** [comment]
@paul-buerkner is there anything else I can do on my end to try and resolve this?

I very much appreciate your time and help.

**Comment by paul-buerkner** [comment]
I am not sure at this point. Seems like a general problem that I would hope has a general fix but unfortunately I am not aware of one at the moment.

**Comment by zfarley** [comment]
@paul-buerkner 
Would getting you my models help the process at all? Do you have any idea what the error regarding prior sample size being 0 is in relation to?

Do you have any suggestions for alternative brms model validation and comparisons when a large number of pareto-k values are high? If I understand correctly, WAIC will be just as poor of an approximation of cross validation but will not give the warnings such as `loo` does.

Thank you

**Comment by paul-buerkner** [comment]
If the models are not too large and you can provide me with the exact code that fails for each model (reproducible example), it might help. moment matching is a quite fragile procedure still and it is hard to get stable through all the involved computation layers. Of course, you can use `reloo` instead of `moment_match` but this will take some time because the model will be refit several times.

**Comment by paul-buerkner** [comment]
I have now checked with my new mac and I can confirm this error. However, the error happens inside `loo::loo_moment_match.default` so I cannot fix this from the brms side unfortunately. I suggest you open an issue at https://github.com/stan-dev/loo if that error persists for you. I am sorry that I cannot do more for you at this point.
