### ISSUE TITLE
rescor=T in model with measurement errors

### ISSUE THREAD

**Issue by fusaroli** [paul-buerkner/brms#1226]
Potentially v naive question: 

I recoding a correlation model with measurement error (from Bayesian Cognitive Modeling) in brms to compare it w my stan code. However, I can't seem to be able to use rescor when also including measurement error. I thought the issue was due to not estimating sigmas, but when specifying sigma=T the issue was still not solved.

Stan code:: https://github.com/fusaroli/CognitiveModelingRecoded/blob/main/11_PearsonCorrelationMeasurement/11_PearsonCorrelationMeasurement.stan

Brms model 

```
m <- brm(
  bf(x1|se(se1, sigma = TRUE) ~ 1) + 
    bf(x2|se(se2, sigma = TRUE) ~ 1) + 
    set_rescor(rescor = TRUE),
  df,
  family = gaussian,
  ...
)
```

If rescor is FALSE, the models compiles. If rescor is TRUE, I get the following error::

> Compiling Stan program...
> Semantic error in '/var/folders/3m/f039n0x549vfxhdtj55yykzhfjr0d6/T/Rtmpquopxq/model-72a52de9bdbc.stan', line 35, column 59 to column 61:
>    -------------------------------------------------
>     33:      for (n in 1:N) {
>     34:        Mu[n] = transpose([mu_x1[n], mu_x2[n]]);
>     35:        sigma[n] = transpose([sqrt(square(sigma_x1) + se2_x1[nn]), sqrt(square(sigma_x2) + se2_x2[nn])]);
>                                                                     ^
>     36:        LSigma[n] = diag_pre_multiply(sigma[n], Lrescor);
>     37:      }
>    -------------------------------------------------
> 
> Identifier 'nn' not in scope.
> make: *** [/var/folders/3m/f039n0x549vfxhdtj55yykzhfjr0d6/T/Rtmpquopxq/model-72a52de9bdbc.hpp] Error 1
> 
> Error: An error occured during compilation! See the message above for more information.

**Comment by paul-buerkner** [comment]
Nevermind. I think I found and fixed the issue. Can you check with the latest dev version?

**Comment by fusaroli** [comment]
fixed :-) thanks
