### ISSUE TITLE
Interaction Priors

### ISSUE THREAD

**Issue by Benambridge** [paul-buerkner/brms#1227]
Hi

The code below used to successfully generate priors for the interaction of "prior_b_PrimeTypeP:VerbTypeTE".

But coming back to it several months later (following a journal review process) it no longer seems to do so: The line

Interaction.prior = samps[,"prior_b_PrimeTypeP:VerbTypeTE"]

Gives an "out of bounds" error. And indeed, looking at "samps" there no longer seems to be a column with the name "prior_b_PrimeTypeP:VerbTypeTE".

Has something changed in the way that brms saves priors in the object?

Thanks
Ben

=======

library(brms)

Data=read.csv("FINAL_Data.csv", header=T)

priors_mixed = c(
  set_prior('normal(0,3.5431)', class = 'Intercept'),
  set_prior('normal(0,1.4630)', coef = 'PrimeTypeP'),
  set_prior('normal(0,0.1239)', coef = 'VerbTypeTE'),
  set_prior('normal(0,0.7048)', coef = 'PrimeTypeP:VerbTypeTE')
)

Bayes1 <- brm(formula = RecodeStrict ~ PrimeType*VerbType + (1+PrimeType*VerbType|Participant) + (1+PrimeType|Prime_Verb), data=Data, family = bernoulli(), prior=priors_mixed, cores=16, warmup = 10000, iter = 20000, chains = 16, control = list(adapt_delta = 0.95), sample_prior = TRUE, save_all_pars=TRUE) # Priors are from Messenger's adult data

summary(Bayes1, corr=F)
samps = as.matrix(as.mcmc(Bayes1))

save.image(file='Sena_Bayes_Environment3.RData')
load('Sena_Bayes_Environment3.RData')

#Calculate Bayes Factors

library(logspline)
library(mcmcr)

Interaction.posterior=samps[,"b_PrimeTypeP:VerbTypeTE"]
Interaction.prior = samps[,"prior_b_PrimeTypeP:VerbTypeTE"]
Interaction.posterior = Interaction.posterior[which(Interaction.posterior<0)] # <0 because interaction is negative
Interaction.prior = Interaction.prior[which(Interaction.prior<0)] #<0 because interaction is negative
fit.prior     = logspline(Interaction.prior, ubound=0) # upper bound is zero because interaction is negative
fit.posterior = logspline(Interaction.posterior, ubound=0) # upper bound is zero because interaction is negative
posterior     = dlogspline(0, fit.posterior)
prior         = dlogspline(0, fit.prior) # based on the logspline fit
BF01          = posterior/prior
print(posterior)
print(prior)
print(BF01) #Evidence for the null
print(1/BF01) #BF10 Evidence for the hypothesis (Bayes Factor)

## Save the ouput
sink("Sena_Bayes_Output.txt")
summary(Bayes1, corr=F)
print("posterior")
print(posterior)
print("prior")
print(prior)
print("BF01, Evidence for the null")
print(BF01) 
print("BF10 (1/BF01) - Evidence for the hypothesis (Bayes Factor)")
print(1/BF01)
sink()

**Comment by paul-buerkner** [comment]
what is colnames(samps) ?

Benambridge ***@***.***> schrieb am Di., 7. Sept. 2021, 16:06:

**Comment by Benambridge** [comment]
Really sorry to waste your time- I ran it again and it all works fine (and colnames(samps) includes"prior_b_PrimeTypeP:VerbTypeTE") - I must have just made a copying+pasting error when running my code on the cluster the first time around!
