### ISSUE TITLE
add_criterion memory error

### ISSUE THREAD

**Issue by davidfoxcroft** [paul-buerkner/brms#1228]
Hi, using brms::add_criterion with a large (20GB) model object leads to a memory error. Do you have any advice...is this a bug?

![Screenshot-20210907222033-1014x547](https://user-images.githubusercontent.com/5821185/132413291-5bf28eb6-4205-49d2-bb86-fb8602033b8f.png)

**Comment by paul-buerkner** [comment]
I think the model may simply be too large to be handled appropriately in memory. You may want to try using fewer posterior samples or setting pointwise to TRUE (at least for waic and loo).
