### ISSUE TITLE
`extract_model_data()`: ignored arguments

### ISSUE THREAD

**Issue by fweber144** [paul-buerkner/brms#1230]
The `extract_model_data()` function used internally by `get_refmodel.brmsfit()` ignores arguments `wrhs`, `orhs`, and `extract_y`. This is relevant for `projpred:::predict.refmodel`, `projpred::proj_linpred()`, and `projpred::proj_predict()`.

It might be worth discussing this with @AlejandroCatalina, i.e., if we want the behavior of those projpred functions to be the same for `"stanreg"` and `"brmsfit"` fits and, if yes, how that common behavior should look like. But until that is decided, I think it would be good to document this in brms. I can create a PR for this if you want.

**Comment by paul-buerkner** [comment]
yeah documenting this sounds good. thank you!

Frank Weber ***@***.***> schrieb am Mi., 8. Sept. 2021, 13:20:

**Comment by fweber144** [comment]
Ok. But I'll wait until PR #1223 is merged to avoid merge conflicts in the documentation.
