### ISSUE TITLE
k-fold memory leak

### ISSUE THREAD

**Issue by Famondir** [paul-buerkner/brms#1235]
Hi,
I'm doing a k-fold crossvalidation of a 1 parametric item response model with 499  persons and 12 items (yeah the SPM set you used in your tutorial) and am doing grouped (by person) k-fold cv. A simple 10 fold was run easily. Now I'm running a 499 fold cv (each persons responses emitted ata time). The first 150 models ran in 1 hour. When I came back this morning I found 466 models in 16 h and am now at 478/499 after 17.5 h. My memory just was filled up somewhen tonight.

I have 32 GB RAM and running:
R version 4.0.5 (2021-03-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)
brms 2.16.1

It would be great to have the possibility to hold the temporary models on disk and not in memory until they are needed. Is this possible?

Alternatively I could try to get mor memory but what will happen if I try this for multidimensional models which can get way bigger than 35 MB each?

Sincerely, Simon

**Comment by paul-buerkner** [comment]
brms will temporarily store all the models which is why you experience this problem. Storing on disc could be sensible but is not high on my todo lst.

**Comment by Famondir** [comment]
Okay. After 2 days of runtime and no response of our remote server the process now crashed without a result. It'ld be great to have this feature so one can do marginal crossvalidation for mixed models like IRT models. The PSIS loo frequently raises warings about pareto k values in marginal version compared to conditional version and I hoped to overcome this with person wise k-fold.

**Comment by wds15** [comment]
Maybe move this discussion to the Stan forums? Then others can chime in and also benefit.

**Comment by paul-buerkner** [comment]
Incidentally, I stumble upon the same myself today and managed to fix it after several hours of headache.
