### ISSUE TITLE
Problem estimating group-specific shape of gamma distribution

### ISSUE THREAD

**Issue by timbeechey** [paul-buerkner/brms#124]
Hello,

I have attempted to estimate shape for each group within a predictor variable using the following code:

f <- brmsformula(y ~ 1 + (1 | x1) + (1 | x1:x2), shape ~ (1 | x1))

m <- brm(f, data=dat, family=Gamma(link="identity"), prior=prior, chains=3, cores=3, iter=2000, warmup=500)

This results in the following error message:

SYNTAX ERROR, MESSAGE(S) FROM PARSER:

base type mismatch in assignment; variable name = eta, type = real; right-hand side type=vector

ERROR at line 58

 56:        eta[n] = eta[n] + r_1_1[J_1[n]] * Z_1_1[n] + r_2_1[J_2[n]] * Z_2_1[n]; 
 57:        shape[n] = shape[n] + r_3_shape_1[J_3[n]] * Z_3_shape_1[n]; 
 58:        eta[n] = shape / (eta[n]); 
                    ^
 59:        shape[n] = exp(shape[n]); 

PARSER EXPECTED: <expression assignable to left-hand side>
Error in stanc(model_code = paste(program, collapse = "\n"), model_name = model_cppname,  : 
  failed to parse Stan model 'file365633040bd3' due to the above error.

The same model without the group-specific shape prediction works as expected. I have also been able to estimate group-specific sigma using a gaussian distribution with the following:

f <- brmsformula(y ~ 1 + (1 | x1) + (1 | x1:x2), sigma ~ (1 | x1))

m <- brm(f, data=dat, family=gaussian(link="log"), prior=prior, chains=3, cores=3, iter=2000, warmup=500)

Any help you could give me in figuring out what I'm doing wrong would be very appreciated.

Thank you!

**Comment by paul-buerkner** [comment]
This is indeed a bug in the Stan code generation of **brms**. I will fix this asap. Thanks for pointing me to this issue!

**Comment by timbeechey** [comment]
Thanks so much for the quick response and for all your work on brms!

**Comment by paul-buerkner** [comment]
The bug should be fixed now. You can download the dev version of **brms** via `devtools::install_github("paul-buerkner/brms")` and try it out. Feel free to close this issue after making sure it works correctly for you. Thanks again for pointing me to this issue!

P.S. One minor point regarding your model. Very likely, `Gamma(identity)` will not work well and you should use `Gamma(log)` unless you are really want to use the `identity` link for some reason.

**Comment by timbeechey** [comment]
It's working now. Thanks so much!
