### ISSUE TITLE
Random factors and `emmeans` support

### ISSUE THREAD

**Issue by rvlenth** [paul-buerkner/brms#1240]
A user report I received -- https://github.com/rvlenth/emmeans/issues/296 -- regards using `emmeans()` with a model of the form `Lesion ~ Region + Sex + Age + (1 | ID)`. If I understand this correctly, `ID` is a random effect, yet the report suggests that it gets included in the reference grid, which should have only the fixed effects in the model. 

As I mentioned in commenting on the above-linked issue, the fix would have to be in `brms:::recover_data.brmsfit`, because that is where the needed `terms` component is passed.

It could well be that the emmeans code runs just fine with random effects included; however, the problem would be that when we estimate,, say, the `Region` marginal means, the HPD intervals would not fully include the `ID` variations because those variations would be averaged-over.

**Comment by paul-buerkner** [comment]
Thank you for reporting this issue. I have recently generalized brms support for emmeans to work with much more complicated brms models including the option to include random effects in the predictions (optionally). So I do not think this is a bug. Indeed, if `re_formula = NULL` those random effects are included, but only then. The default is to not include them in the prediction (or in the reference grid). I am closing this issue but feel free to reopen if you think my answer is not satisfactory.

**Comment by rvlenth** [comment]
OK, Paul, thanks, I didn't notice or understand the meaning of `re_formula=NULL` in the question I received. So this all makes sense now.
