### ISSUE TITLE
Zero Inflated Beta Binomial for BRMS

### ISSUE THREAD

**Issue by jlabordenavas** [paul-buerkner/brms#1243]
Hi all, 

Any chance the ZIP Beta-Binomial model can be added to the BRMS package?
There seems to be interest on this family
https://discourse.mc-stan.org/t/zero-inflated-beta-binomial-model-under-brms/13170

Thanks.

**Comment by jackobailey** [comment]
You can already do this using the zero-one inflated beta distribution and fixing one of the parameters https://github.com/paul-buerkner/brms/issues/942

**Comment by jlabordenavas** [comment]
Thanks.  I do not see a `zero_one_inflated_beta` listed in the manual (maybe it needs to be updated).  Plus, I am asking about a `zero_inflated_beta_binomial` which is different.

**Comment by jlabordenavas** [comment]
Many thanks! @hdrab127 and @paul-buerkner

**Comment by ssalimi** [comment]
@hdrab127 
I worked on the Zero Inflated Beta Binomial in December to and with some modification added to my manuscript. 
https://discourse.mc-stan.org/t/non-linear-distribution-with-some-zeros-in-data/24915/39?u=ssalimi
It is so cool to see it is now implemented in the "brms". Thanks for that.
