### ISSUE TITLE
Criteria not saved in file on first use of add_criterion

### ISSUE THREAD

**Issue by andymilne** [paul-buerkner/brms#1244]
This bug has been around for ages and apologies for not reporting sooner. When add_criterion is first used on a model that is fitted with the file argument, the criterion specified in add_criterion is added to the model but, crucially, not saved to the file on the disk. It is necessary to rerun the brm() function to reload the model from disk and then run add_criterion again in order to get the criterion saved to disk.

Repro example:

Run:
```
prior1 <- prior(normal(0,10), class = b) +
  prior(cauchy(0,2), class = sd)
fit1 <- brm(count ~ zAge + zBase * Trt + (1|patient),
            data = epilepsy, family = poisson(), prior = prior1,
            file = "fit1")

fit1 <- add_criterion(fit1, "loo")
```
Inspecting the brm object, we can see the criterion has been added to the fit. Now reload the model from disk by running
```
fit1 <- brm(count ~ zAge + zBase * Trt + (1|patient),
            data = epilepsy, family = poisson(), prior = prior1,
            file = "fit1") 
```
Note that fit1 no longer contains the computed criterion (because it wasn't saved to disk). Now run 
```
fit1 <- add_criterion(fit1, "loo")
```
and you will see a message saying the `Automatically saving the model object in 'fit1.rds'`. And indeed the criterion is now saved in the object.

**Comment by paul-buerkner** [comment]
Thanks. Should now be fixed.
