### ISSUE TITLE
Support for Model Profiling with cmdstanr backend

### ISSUE THREAD

**Issue by ajnafa** [paul-buerkner/brms#1252]
Since brms has support for cmdstanr as a backend it may be useful to have support the [profiling feature introduced in cmdstan 2.26.0](https://mc-stan.org/cmdstanr/articles/profiling.html). I'm not sure how much work it would be to add such a feature and its not particularly urgent, but it would be convenient for identifying bottle necks.

**Comment by paul-buerkner** [comment]
I think this suggested features may not make it into brms. When someone needs functionality beyond what stanvars offer, it is easiest to just edit the Stan code directly.
