### ISSUE TITLE
Error using get_refmodel.brmsfit() with Gamma distribution: supplied argument name 'link' does not match 'x'

### ISSUE THREAD

**Issue by kmorndahl** [paul-buerkner/brms#1255]
Hello,

I am getting an error when building a Gamma model with brm() and attempting to get the reference model from that object using the get_refmodel() instance for brmsfit objects. I believe this might be due to a small bug. Other distribution families seem to work fine.

Here's a test case for this issue:

```
library(brms)

# Generate fake data
set.seed(5555)
N <- 100
x <- runif(N, -1, 1)
a <- 0.5
b <- 1.1
y_true <- exp(a + b * x)
shape <- 10
y <- rgamma(N, rate = shape / y_true, shape = shape)
fake_data <- data.frame(x=x,y=y)

# Build brms model with Gamma distribution
# Uses stats family designation with capital 'G'
brm_gamma <- brm(y~x, data=fake_data, family=Gamma(link="log"))

# brm function changes Gamma distribution name to gamma with lowercase 'g'
brm_gamma$family
family <- brm_gamma$family
  
# get_refmodel for brms fit fails with: 
# Error in get(family$family, mode = "function")(link = family$link) : 
#   supplied argument name 'link' does not match 'x'
ref <- get_refmodel(brm_gamma)
ref <- brms::get_refmodel(brm_gamma)

# From get_refmodel.brmsfit source code:
# Gamma family is not polytomous so the following always executes as TRUE:
# if (!(isTRUE(dots$aug_data) && is_polytomous(family)))

# This executes the following line of code, which fails with matching error code
family <- get(family$family, mode = "function")(link = family$link)

# The following excerpt from the code above summons the base R 'gamma' function rather than the stats family 'Gamma' function
get(family$family, mode = "function")

```

I am on Windows 10, RStudio 1.3.1093, R 4.0.2, brms 2.16.1.

Let me know if you need any additional information!

Many thanks for your work with this package.

**Comment by paul-buerkner** [comment]
Thank you! This should now be fixed on github. Can you double check that it now works as expected?

**Comment by kmorndahl** [comment]
Hi Paul,

Thanks very much!

That error code is now gone.

Unfortunately, however, a new error has cropped up: 

```
Error in dis/matrix(mu) : non-conformable arrays
```

Here's that same test case again:

```
# Generate fake data
set.seed(5555)
N <- 100
x <- runif(N, -1, 1)
a <- 0.5
b <- 1.1
y_true <- exp(a + b * x)
shape <- 10
y <- rgamma(N, rate = shape / y_true, shape = shape)
fake_data <- data.frame(x=x,y=y)

# Build brms model with Gamma distribution
brm_gamma <- brm(y~x, data=fake_data, family=Gamma(link="log"))

# get_refmodel for brms fit fails with: 
# Error in dis/matrix(mu) : non-conformable arrays
ref <- get_refmodel(brm_gamma)
```

Perhaps you have insight on what might cause this error? I can of course send more information if necessary

Thanks!

**Comment by hsbadr** [comment]
@paul-buerkner Related to 753addf7415b757f79f93737de7609ee04aa4af0 and this issue, you may also want to map `negbinomial` to one of `negative.binomial` (from `MASS`) or `negbin` / `nb` (from `mgcv`).

**Comment by fweber144** [comment]
@AlejandroCatalina, is it correct that the Gamma family is still experimental in **projpred**? In that case, I think **projpred** should throw a warning about this.

@hsbadr: The negative binomial family is not supported yet by **projpred**, see, for example, the discussions at stan-dev/projpred#67 and stan-dev/projpred#70.

**Comment by AlejandroCatalina** [comment]
Yes, it is not supported as such

Best,
Alex
________________________________

**Comment by fweber144** [comment]
I opened a corresponding issue at stan-dev/projpred#240.
