### ISSUE TITLE
conditioning correlation btw varying effects on another variable

### ISSUE THREAD

**Issue by fusaroli** [paul-buerkner/brms#1256]
This might be a very niche case and best left to directly coding in Stan, but I'm posting it here in case I'm missing an existing functionality.

Imagine I have two models estimating e.g. cognitive ability X in the child and in the parent from some repeated measures task.

```
fC <- bf(scoreC ~ 1 + (1 | p | ID))
fP <- bf(scoreP ~ 1 + (1 | p | ID))

# some prior

m <- brm(
  fC + fP + set_rescor(rescor=FALSE),
  d,
  family = poisson,
...
)

```

Now, let's imagine theory says that the amount of time child and parent spend together should relate to how similar their cognitive ability. e.g the more time spent together the more similar.

Is there a way to condition the correlation set up by "p" on an additional parameter?

And yes, I could extract the random effects estimates by child and parent and run a secondary model. However, when I include the uncertainty of the random effects estimates, the parameter recovery performance is abysmal, so I'd rather try to do it all in one model.

**Comment by paul-buerkner** [comment]
There is currently no option to achieve this in brms and this is quite unlikely to come in the future given that this feature does not easily scale to correlation matrices consistsing of more than 1 unique correlations.

**Comment by fusaroli** [comment]
sounds reasonable! thanks
