### ISSUE TITLE
Add Beta likelihood for meta-analysis

### ISSUE THREAD

**Issue by MilaniC** [paul-buerkner/brms#126]
Beta likelihood is a feature of brms but not for the yi | se(sei) response syntax for meta-analytical approach used in brms. Can the Beta likelihood for meta-analysis by added to brms. This is especially useful for modelling (0,1) response like survival probabilities given informative nonlinear covariates and random effects while weighting the observation by the variance or precision of each estimate.

**Comment by paul-buerkner** [comment]
If you just want to apply weights, you can write `yi | weights(<variable>)`. If you mean something different (I think you do), could you write down how exactly a meta-analytic beta model using `yi | se(sei)` should look like?

**Comment by MilaniC** [comment]
Hi Paul

y_i=estimates of study-specific survival probability, which is (0,1) bound
se_i=precision of the y_i estimate

above “effect sizes” derived from capture-mark-recapture modelling of capture histories  data sourced from 59 studies with these estimates (for my task)

synthesising into an overall meta-analysis (and then meta-regression with informative covariates)

y_i then follow a Beta likelihood (~Beta(mu_i,phi) suitable for (0,1) bounded data with mean mu_i but with known precision (phi) here (the se_i) and hence no residual estimate needed - hence weighting option not suitable in brms I think. Nor would a weighted regression approach in other R packages like betareg that do fit Beta likelihood regression models.

Logit link would be appropriate here.

But the "response | se(sei)" form in brms does seem appropriate assuming Beta likelihood rather than a gaussian likelihood. And then a beta regression with know phi and random effects and potentially nonparametric covariate form is then possible for meta-regression with (0,1) bounded data (which is not possible as far as I understand with any other R package).

I don’t want to estimate phi in y_i~Beta(mu_i,phi) as it is known. So I assume it should be fixed to 1. But no R packages for any form of regression modelling support this feature other than standard meta-analysis packages like metafor. But metafor does not include Beta likelihood although there is some discussion that it might include other options like this and beta-binomial likelihood BUT not in the near future.

Also metafor only supports B splines for nonlinear function covariate form but we find s(…) from mgcv far more flexible. So brms is the way to go.

I could logit transform the original (0,1) bounded data (which are mainly around 0.80-0.95) and assume normality but not good here because (1) models then predict outside the (0,1) bounds (which are impossible values) and (2) model parameters are then difficult to interpret in terms of the original response (the survival probability estimates).

Hope this helps clarify my issue. Useful reference for the standard beta regression model with unknown precision (phi) is for instance  in:

Ferrari, S.L.P. & Pinheiro, E.C. (2012). Improved likelihood inference in beta regression.Journal of Statistical Computation and Simulation 81: 431–44


BTW, the t2() for georeferenced data fix works well but of course with ca. 10k records it takes quite a long time to fit. Thanks for that very rapidly implemented fix.

regards

Milani




____________________________________________________

Dr Milani Chaloupka
Ecological Modelling Services P/L
PO Box 6150, University of Queensland
St Lucia, Queensland, 4067, Australia

Honorary Associate Professor
School of Biological Sciences, University of Queensland
Brisbane, Queensland, 4072, Australia

m.chaloupka@uq.edu.au
m.chaloupka@me.com
phone: + 61 7 38783229
mobile: (local) 0419180554  (international) + 61 419180554
skype: milani2005
____________________________________________________

**Comment by paul-buerkner** [comment]
Ok, one further question / comment. We can to supply precision estimates via the 'addition' syntax but we shouldn't use `se` then because users expect `se` to take standard errors not precisions. From my perspective, we have two options here: Define a new addition fuction named `prec` which takes known precisions, or internally transform input of `se`  to precision via `prec = 1/se^2`. The thing is that, although the parameter is named precision, it is not really the inverse of the variance, but instead we have `Var(y) = (mu (1- mu)) / (1+phi)`. What do you thing makes most sense?

**Comment by MilaniC** [comment]
Hi Paul

That is a tricky question. I think … define new addition function named "prec” should suffice.

And as an aside, I am thinking that setting informative priors is going to be important here for the user.

Milani

**Comment by paul-buerkner** [comment]
Out of curiosity, how do you extract the precision estimates from the primary studies. Are these estimates also a result of the capture-mark-recapture model?

**Comment by MilaniC** [comment]
Yes that is correct. Each study reports the annual survival probability estimate and and estimate of precision (the SEs) of that estimate

**Comment by paul-buerkner** [comment]
Ok, but if we supply the SE to brms, shouldn't we use the `se` addition
term then? Regardless of how we name it, the question remains, how we
should compute the estimate of phi based on SE (and possibly further
information)?

2016-09-28 9:24 GMT+02:00 MilaniC <notifications@github.com>:

> Yes that is correct. Each study reports the annual survival probability
> estimate and and estimate of precision (the SEs) of that estimate
>
> > On 28 Sep. 2016, at 5:07 pm, Paul-Christian Bürkner <

**Comment by MilaniC** [comment]
Ok getting back to this issue.

I think what is required is a varying dispersion Beta regression (yi ∼ B(µi , φi),

**Comment by MilaniC** [comment]
Ok getting back to this issue.

I think what is required is a varying dispersion Beta regression model (yi ∼ B(µi , φi)) that could be fit I think via the bf() constructor with 2 linear predictors as follows:

m1<-brm(bf(yi~1+fixed effects + random effects,
              phi~-1+weights.norm),
              family=Beta()...)

where weights.norm <- 1/(vi/mean(vi))  ## normalised inverse variance weights

Or even as;

m1<-brm(bf(yi~1+fixed effects + random effects,
              phi~-1+s(weights.norm)),
              family=Beta()...)

which in fact fits quickly with good convergence (sample recovery and Rhat)

So the question is now whether this is in fact a mixed effects meta-regression model with Beta likelihood. And also whether the intercept should be included or not on the phi ~ component.

Any advice appreciated.

**Comment by paul-buerkner** [comment]
Ok, so no new functionality required from your side?

> So the question is now whether this is in fact a mixed effects meta-regression model with Beta likelihood. 

Can you explain in more detail what you mean here?

> And also whether the intercept should be included or not on the phi ~ component.

I would definitely recommend adding an intercept. It is way safer. For instance, the `s` term already expects parts of it being soaked up in the intercept.

**Comment by MilaniC** [comment]
I still haven't got my head around this issue completely but I think we can close this issue. But I am going to ponder it more.

**Comment by paul-buerkner** [comment]
Ok. Feel free to reopen it at any time.
