### ISSUE TITLE
Set default `threads` in `options()`

### ISSUE THREAD

**Issue by bwiernik** [paul-buerkner/brms#1262]
I like to set `options(mc.cores = parallel::detectCores(), brms.backend = "cmdstanr")`. I usually want to also set `threads = 2` when fitting, but I have to do this in each model specification. Would it be possible to also have `threads` be configurable with an option?

**Comment by paul-buerkner** [comment]
Should be working now via the `brms.threads` option.

**Comment by bwiernik** [comment]
Thanks!
