### ISSUE TITLE
.warmup meta column for inc_warmup = TRUE

### ISSUE THREAD

**Issue by ASKurz** [paul-buerkner/brms#1263]
When one uses one of the new `as_draws()` functions and sets `inc_warmup = TRUE`, it would be helpful if there was an additional meta column indicating whether draws are warmup versus post warmup. Consider the example, below.

```{r}
library(tidyverse)
library(brms)

dat <- data.frame(x = rnorm(n = 100))

fit <- brm(
  data = dat,
  x ~ 1,
  cores = 4
)

as_draws_df(fit, inc_warmup = TRUE) %>% 
  tibble() %>% 
  glimpse()
```
```
Rows: 8,000
Columns: 6
$ b_Intercept <dbl> -0.3458775868, -0.3458775868, -0.3458775868, -0.2592616922, 0.0…
$ sigma       <dbl> 0.8161222, 0.8161222, 0.8161222, 0.9561957, 0.9206546, 1.057081…
$ lp__        <dbl> -152.2864, -152.2864, -152.2864, -144.1292, -140.6602, -141.353…
$ .chain      <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …
$ .iteration  <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, …
$ .draw       <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, …
```

Maybe there could be a final `.warmup` column for which warmup draws are coded `1` and post-warmup draws are coded `0`.

**Comment by paul-buerkner** [comment]
I like the idea. However, this needs to be implemented in the posterior package first. Would you mind opening an issue on https://github.com/stan-dev/posterior/issues?

**Comment by ASKurz** [comment]
Done.

**Comment by paul-buerkner** [comment]
Thank you!

**Comment by paul-buerkner** [comment]
Closing this issue since it is more a posterior than a brms feature.
