### ISSUE TITLE
brm (potentially) summary failing with categorical response, multilevel model

### ISSUE THREAD

**Issue by dbarneche** [paul-buerkner/brms#1264]
Hi,

Re-flagging a post from the rstan forum:
https://discourse.mc-stan.org/t/brm-summary-failing-with-categorical-response-multilevel-model/24916

I just wanted to double check whether the issue above is expected behaviour, or if in situations where family is categorical and sample_prior="yes" onde should apply alternative coding to a brm call.

Thanks very much for your time and for this amazing package!

**Comment by paul-buerkner** [comment]
This error can should already be resolved in the latest github version of brms. Can you double check?

**Comment by dbarneche** [comment]
Thanks very much @paul-buerkner , I can confirmed that the fix worked on my end as well.
