### ISSUE TITLE
Replacement for cor_bsts to fit autocorrelated count data

### ISSUE THREAD

**Issue by cramjaco** [paul-buerkner/brms#1268]
I'm hunting for a solution to relate some autocorrelated continuous and count data in a time-series.

```
## My actual data are 262 observations
data <- structure(list(catch = c(2, 0, 1, 1, 2, 2, 0, 2, 0, 0, 0, 2, 
3, 2, 1, 0, 0, 2, 1, 1), nutrients = c(1.253666667, 0.944, 1.194333333, 
0.904666667, 1.225, 2.176, 1.183333333, 1.125333333, 1.329, 0.859333333, 
1.341666667, 1.278333333, 1.242, 1.452333333, 1.949333333, 2.882333333, 
1.591333333, 2.194666667, 2.612333333, 1.934666667), date = structure(c(16536, 
16542, 16549, 16556, 16563, 16570, 16577, 16584, 16591, 16598, 
16605, 16612, 16619, 16626, 16633, 16640, 16647, 16654, 16661, 
16668), class = "Date")), row.names = c(NA, -20L), class = c("tbl_df", 
"tbl", "data.frame"))
```

I was initially pretty excited by this post that seemed to suggest that this could be done in brms
https://github.com/paul-buerkner/brms/issues/77
But see that `cor_bsts()` is now discontinued. Is there a new best practice for dealing with these sorts of data? Prediction is not imperative for me, I'm mostly just trying to identify whether there is indeed a relationship between my continuous (nutrients) and descrete (catch) variables.

This post points to the **phophet** package
https://github.com/paul-buerkner/brms/issues/148

But that package says: "It works best with time series that have strong seasonal effects and several seasons of historical data."
In my case, I don't really have strong seasonal effects, just autocorrelation. Am I at a dead end, or just overlooking something at this point. Thanks for any suggestions.

**Comment by paul-buerkner** [comment]
I think this question is better asked on https://discourse.mc-stan.org where more people can read it and benefit from answers from the community.
