### ISSUE TITLE
Log-normal distribution in the errors-in-variables model

### ISSUE THREAD

**Issue by Akaasik** [paul-buerkner/brms#1270]
Apologies in advance if this is more of a **Stan** than **brms** question.

I'm trying to fit an EIV model but with one caveat -- I know the measurement errors but want to work on the log scale. So if the ordinary formula would be
`F_obs | mi(F_sd) ~ me(M_obs, M_sd)`

I would be interested "in sth like"

`log(F_obs | mi(F_sd)) ~ log(me(M_obs, M_sd))`

Would it be possible to fit such model with brms or should one instead treat the data as from a log-normal distribution and use the relation between log-normal distribution and normal distribution to form it as a model without logs.

**Comment by paul-buerkner** [comment]
Please ask brms related questions on https://discourse.mc-stan.org/
