### ISSUE TITLE
How to assign prior distribution for the data in brm() in R

### ISSUE THREAD

**Issue by Yinshao-lzu** [paul-buerkner/brms#1272]
Hello, I first fit a bayesian model by brm() in R. But I found significant difference between observed data and replicated data from the model after using `pp_check(model,type = "dens_overlay")`. Follow the model prompts, I think the difference is maybe caused by insufficient iteration and deficiency of reliable prior distribution. How did I assign prior distribution for the data? 

Here is my data distribution and code:
(data distribution: from -1 to 12)
![数据分布](https://user-images.githubusercontent.com/56902640/145926342-f73992e9-66be-4281-8785-827fab8f1e1b.png)

![fit_brm_wiggle_ppcheck](https://user-images.githubusercontent.com/56902640/145926374-86be08ab-7fd7-4887-883e-18809b5d8aa2.png)

R code
`fit_brm <- brm(Y ~ s(x),
                      data = dt,
                      family = "gaussian",
                      chains = 4,
                      iter = 4000,
                      cores = 4)`

**Comment by wds15** [comment]
This does not look like a problem at all with brms...maybe you post this on the discourse forum?
