### ISSUE TITLE
bayes_factor crashing R

### ISSUE THREAD

**Issue by dontchaknowjo** [paul-buerkner/brms#1273]
Everytime I use bayes_factor, R crashes. I have a machine with an M1 processor, but tried it on another machine and R also crashed when trying to use bayes_factor. I tried going back to an older version of R (3.6) and wasn't able to install brms. bayes_factor is crashing R with new code (fairly small data set, and fairly small brm object), and with old code that was working about 6 months ago.

Thanks in advance!

**Comment by paul-buerkner** [comment]
This is hard to debug as described. I recommend you ask this question on https://discourse.mc-stan.org/ and provide more details so that people have a better chance at helping you.
