### ISSUE TITLE
rename_pars and cmdstanr

### ISSUE THREAD

**Issue by donaldRwilliams** [paul-buerkner/brms#1275]
Hi Paul,

Many are now using `cmdstanr`, and I was wondering if it was possible mimic the behavior of `rename_pars` for a `CmdStanMCMC` object

e.g., so instead of using `rstan` using `cmdstanr`:

```
# fit a model manually via rstan
scode <- make_stancode(count ~ Trt, data = epilepsy)
sdata <- make_standata(count ~ Trt, data = epilepsy)

stanfit <- rstan::stan(model_code = scode, data = sdata)

# feed the Stan model back into brms
fit <- brm(count ~ Trt, data = epilepsy, empty = TRUE)
fit$fit <- stanfit

fit <- rename_pars(fit)
summary(fit)
```

Fit with cmdstanr ?

```
library(brms)
library(rstan)
library(cmdstanr)


scode <- make_stancode(count ~ Trt, data = epilepsy)
sdata <- make_standata(count ~ Trt, data = epilepsy)

stan_code_path <-   write_stan_file(code = scode)

stan_m3 <- cmdstan_model(stan_file = stan_code_path,
                         cpp_options = list(stan_threads = TRUE))


cmdfit <- stan_m3$sample(data = sdata, 
                         threads_per_chain = 1)


fit <- brm(count ~ Trt, data = epilepsy, empty = TRUE)

# perhaps this could work ?
fit$fit <- cmdfit

fit <- rename_pars(fit)
summary(fit)
```

I think this would be quite useful because then we would still have all the additional features of brms, e.g., summary, predict, fitted, etc..

**Comment by rok-cesnovar** [comment]
One way would be using:

```r
fit$fit <- rstan::read_stan_csv(cmdfit$output_files())

fit <- rename_pars(fit)
summary(fit)
```

Its not ideal as it requires rstan installed.

**Comment by donaldRwilliams** [comment]
wow ! 

let me give that a try :-)

**Comment by jsocolar** [comment]
@rok-cesnovar `brms` already imports `rstan` so having `rstan` installed probably isn't a burden in practice.

**Comment by rok-cesnovar** [comment]
Ah yes, forgot about that, thanks! You don't even have to have a "functioning" rstan install, which is typically the problem, as this function is just plain R.

**Comment by paul-buerkner** [comment]
Seems to be resolved so closing this issue.

**Comment by donaldRwilliams** [comment]
Indeed. Thank you!
