### ISSUE TITLE
Extract random-effects model matrix ("Z")

### ISSUE THREAD

**Issue by CYGUBICKO** [paul-buerkner/brms#1276]
I am trying to generate predictions 'manually' via a design matrix and coefficient vector, and so far I am able to re-construct (from the model), the main effect design matrix and able to generate predictions 'manually' which matches the ones generated via `posterior_linpred.brmsfit` and `emmeans`. I also want to do some adjustments to the predictions using the random component of the model, i.e., `Zb`, is there a way (internal or otherwise) to extract or reconstruct `Z` from the `brmsfit` object?

```
library(brms)
library(lme4)
## brms
fit1 <- brm(count ~ zAge + (1|patient), data = epilepsy, family = poisson(), chains=1)
## lme4
fit2 <- glmer(count ~ zAge + (1|patient), data = epilepsy, family = poisson())
getME(fit2, "Z")
```

i.e., the equivalent of `getME(fit2, "Z")`?

**Comment by paul-buerkner** [comment]
Unfortunately not. brms does not generate the full Z matrix at all, not even internally. You can get by-group components of it by running `prepare_predictions` and then inspecting the output to find the right element in the nested list.
