### ISSUE TITLE
multivariate + threading + normalise + set_rescor

### ISSUE THREAD

**Issue by anirban-mukherjee** [paul-buerkner/brms#1277]
When using a multivariate formula, threading, normalise, and passing FALSE to set_rescor, I get an error. I am unable to work out exactly what's going on and what set of options/choices lead to the error (I think this exact set of options/modeling choices is needed for the error to manifest but I am not sure). Seems to be an odd corner case.

Below is a MWE. The "sequential" version without threading runs fine. The "parallel" version bug checks. The parallel version without set_rescor and with normalisation runs fine. The parallel version without normalisation and with set_rescor runs fine.

```
library(brms)
fake_data <-
  data.frame(x = factor(rep(1:2, 100)),
             y1 = rnorm(100),
             y2 = rnorm(100))

bf1 <- bf(y1 ~ 0 + x)
bf2 <- bf(y2 ~ 0 + x)

# runs fine
seqbrm <- brm(
  bf1 + bf2 + set_rescor(FALSE),
  backend = "cmdstanr",
  data = fake_data,
  normalize = FALSE
)

# bug checks
parbrm <- brm(
  bf1 + bf2 + set_rescor(FALSE),
  backend = "cmdstanr",
  data = fake_data,
  normalize = FALSE,
  threads = threading(2)
)
```

Here is the error:
```
Compiling Stan program...
Semantic error in '/var/folders/xh/pyjdt2b12yzbx8nsdmdwxll40000gn/T/Rtmplbjxb3/model-5777a34ca91.stan', line 22, column 15 to column 88:
   -------------------------------------------------
    20:      int N = end - start + 1;
    21:      int N_y1 = end - start + 1;
    22:      ptarget += normal_id_glm_lupdf(Y_y1[start:end] | X_y1[start:end], 0, b_y1, sigma_y1);
                        ^
    23:      return ptarget;
    24:    }
   -------------------------------------------------

Functions with names ending in _lupdf and _lupmf can only be used in the model block or user-defined functions with names ending in _lpdf or _lpmf.

make: *** [/var/folders/xh/pyjdt2b12yzbx8nsdmdwxll40000gn/T/Rtmplbjxb3/model-5777a34ca91.hpp] Error 1

Error: An error occured during compilation! See the message above for more information.
```

**Comment by paul-buerkner** [comment]
which version of brms are you using? I have the feeling I may have fixed
something similar in 2.16.3 (currently on CRAN).

Anirban Mukherjee ***@***.***> schrieb am Mi., 29. Dez. 2021,
02:35:

**Comment by anirban-mukherjee** [comment]
I am on 2.16.3. I updated to the GitHub version but unfortunately that does not change anything.

**Comment by paul-buerkner** [comment]
Okay. let me check what's going wrong.

Anirban Mukherjee ***@***.***> schrieb am Mi., 29. Dez. 2021,
02:49:

**Comment by anirban-mukherjee** [comment]
Poking around in the generated stan code, I think the issue is that the user defined functions are called "partial_log_lik_lpmf_y1" and "partial_log_lik_lpmf_y2", whereas stan expects the user defined functions to end in _lpmf if using _lupdf functions.

With set_rescor(TRUE) this is not an issue because we get a single function that ends in _lpmf. 

With normalisation = TRUE and set_rescor(FALSE) we again get two functions that end in _y1 and _y2 but now the functions use normal_id_glm_lpdf, which is fine, whereas the version with normalisation = FALSE uses normal_id_glm_lupdf, which requires that the user defined function end in _lpmf.

**Comment by anirban-mukherjee** [comment]
I used make_stancode as follows:

```
make_stancode(
  bf1 + bf2 + set_rescor(FALSE),
  backend = "cmdstanr",
  data = fake_data,
  normalize = FALSE,
  threads = threading(2)
)
```

I saved the stan code locally and changed `partial_log_lik_lpmf_y1` to `partial_log_lik_y1_lpmf` and `partial_log_lik_lpmf_y2` to `partial_log_lik_y2_lpmf`. Code compiles as expected.

Hope that helps. Thanks for taking a look!

**Comment by anirban-mukherjee** [comment]
I think in the paste0 in lines 122 and 134 of make_stancode.R, if we replace
`"real partial_log_lik_lpmf", resp,` 
with 
`"real partial_log_lik", resp,"_lpmf"` 
then the generated function will end in _lpmf with resp in the middle of the function name instead of the end, which would then solve this issue.

**Comment by paul-buerkner** [comment]
You are right. Thank you! Just fixed it on github.

**Comment by anirban-mukherjee** [comment]
Super duper, thank you as always for the super quick response and all your work on the package!
