### ISSUE TITLE
Errors related to horseshoe priors

### ISSUE THREAD

**Issue by Yinshao-lzu** [paul-buerkner/brms#1281]
Hello, I'm trying to fit a bayesian hierarchical model for count data. When I select **horseshoe** prior for parameter , there is error: Prior 'horseshoe(1)' is used in an invalid context. See ?set_prior for details on how to use special priors. Is this prior not appropriate for counting data?

`fit_brm <- brm(Y ~ s(x) + (1 + x | group1) + (1 +  x | group2),
                      data = dat,
                      family = poisson(),
                      chains = 4,
                      iter = 4000,
                      cores = 4,
                      control = list(adapt_delta=0.99),
                      prior=set_prior("horseshoe(1)",class = 'b'))`

**Comment by paul-buerkner** [comment]
your model has no parameters (fixed effects) to which the horseshoe prior
applies. in the future please ask brms related questions in the Stan
discourse forums.

Yinshao-lzu ***@***.***> schrieb am Do., 6. Jan. 2022, 15:18:
