### ISSUE TITLE
Compatibility issues with brms and R v3.6.0

### ISSUE THREAD

**Issue by apeterson91** [paul-buerkner/brms#1282]
I have two tests that error when testing brms on R v3.60

1. In tests.make_standata.R 601:3 make_standata handles mi terms with 'subset'
Error: invalid first argument

This is caused by the use of a call to data.frame() in R/formula-sp.R line 418 without specifying the optional argument stringsAsFactors = FALSE.

2. In tests.brmsfit-helpers.R 191:13 insert_refcat() works correctly
Error: dimnames must be a list

This is caused by the following line of code on line 606 of file R/brmsfit-helpers.R
` dimnames(eta)[[ndim]] <- paste0("mu", setdiff(family$cats, family$refcat))`

I'm not sure of the best way to fix this problem. Are you familiar with an established practice that provides backward compatibility?

I'm having difficulty providing a reprex because of the sourcing that needs to be done prior to testing but starting a clean R session with the appropriate version of R in the brms directory followed by executing the following lines of code should reproduce the errors.

`devtools::test_file("tests/testthat/tests.make_standata.R)`
    
`devtools::test_file("tests/testthat/tests.brsmfit-helpers.R)`

**Comment by paul-buerkner** [comment]
Thanks! Fixed the first issue. Can you check if the line `dimnames(eta)[ndim] <- list(paste0("mu", setdiff(family$cats, family$refcat)))` would fix the second? I don't readily have access to this old version on my mac right now.

**Comment by apeterson91** [comment]
Yes I think that should do it, though a similar change would need to be made on line 608 outside the if condition.

**Comment by paul-buerkner** [comment]
Thanks! Should now be fixed as well.
