### ISSUE TITLE
The `lb` and `ub` bounds for class=sigma

### ISSUE THREAD

**Issue by dmi3kno** [paul-buerkner/brms#1285]
Hi,
I am wondering what's the proper way of defining a custom prior for the class=sigma
```r
library(tidyverse)
library(brms)
alpha <- 70
beta <- 0.5
sigma <- 5
n <- 100
d2 <- tibble(
  H=runif(n,130,170),
  mu=alpha+beta*(H-mean(H)),
  W=rnorm(n, mu,sigma)
)
mod <- brms::brm(W~1+H, data=d2, family = gaussian(),
                 prior=c(prior(normal(60,10), class=Intercept),
                         prior(lognormal(0,1), class=b, lb=0)#,
                         #prior(uniform(0,10), class=sigma)
                         ),
                 iter=20000, chains = 4, cores=4, seed=42)
brms::stancode(mod)
bayesplot::mcmc_combo(mod)
```
If I define no prior, the default (half-t) prior is set and everything compiles as expected. However, If I try to define `uniform(0,10)` prior, as Richard does in his latest Statistical Rethinking lecture, I get poor convergence.

```r
mod <- brms::brm(W~1+H, data=d2, family = gaussian(),
                 prior=c(prior(normal(60,10), class=Intercept),
                         prior(lognormal(0,1), class=b, lb=0),
                         prior(uniform(0,10), class=sigma)
                         ),
                 iter=20000, chains = 4, cores=4, seed=42)
brms::stancode(mod)
bayesplot::mcmc_combo(mod)
#> #Warning messages
#> 1: It appears as if you have specified an upper bounded prior on a parameter that has no natural upper bound.
#> If this is really what you want, please specify argument 'ub' of 'set_prior' appropriately.
#> Warning occurred for prior 
#> sigma ~ uniform(0, 10)
```
But of course, class=sigma does not accept, specification lf `lb` and `ub`.
```r
#> Error: Currently boundaries are only allowed for classe(s) 'b'.
```
What is the proper way of specifying uniform prior for the sigma parameter in normal model?

**Comment by paul-buerkner** [comment]
I would recommend not setting uniform priors on parameters that are not bounded. That said, to make this work, brms had to generalize the lb and ub arguments to other classes, but this is not yet implemented. 

In the future, if you have brms related questions, I prefer you ask these questions on https://discourse.mc-stan.org/

**Comment by dmi3kno** [comment]
Thank you. I thought of this primarily as a request regarding implementing `ub` and `lb` for `sigma` class. I also hoped that there's an out of the box solution I overlooked, then the issue would be closed. I am committed to not spamming github issues with usage-related questions. Thank you

**Comment by paul-buerkner** [comment]
I understand! I think this is a very reasonable request more generally and
hope to implement this in some of the upcoming versions :-)

Dmytro Perepolkin ***@***.***> schrieb am Sa., 22. Jan. 2022,
14:03:

**Comment by dmi3kno** [comment]
I don't mean to blow up the scope, but perhaps you could consider adding support for the bounds in other classes, as well? Take `class=Intercept`. I am aware of the solution with `0+intercept` under `class=b`. I also understand you might be considering deprecating `Intercept` class completely. In case `class=Intercept` is here with us to stay, perhaps we could kill two birds with one stone?

**Comment by paul-buerkner** [comment]
Indeed. My intention is to get this to work generally.

Dmytro Perepolkin ***@***.***> schrieb am Sa., 22. Jan. 2022,
14:49:
