### ISSUE TITLE
Error: Family 'exponential' requires response greater than 0.

### ISSUE THREAD

**Issue by JackCaster** [paul-buerkner/brms#1288]
I would like to fit an exponential distribution on a dataset that contains zeros but I get the error
```
Error: Family 'exponential' requires response greater than 0.
```
As far as I know, the support of the exponential distribution includes zero (https://en.wikipedia.org/wiki/Exponential_distribution). Is this behavior intended? I am using brms `2.16.3` and this code snippet reproduce the error:
```
df <- data.frame(x = c(0, rexp(10)))
brm(
   x ~ 1,
   data = df,
   family = exponential()
)
# Error: Family 'exponential' requires response greater than 0.
```

**Comment by paul-buerkner** [comment]
Yes, this is intentional because we cannot compute gradients at the boundaries of the distribution. You can try it out in Stan directly to see it failing there as well.
