### ISSUE TITLE
Warning during compiling (brms version 2.16.5)

### ISSUE THREAD

**Issue by afni-gangc** [paul-buerkner/brms#1291]
brms version: 2.16.5

During model compiling, the following warning keeps showing up:

> Warning in '/tmp/RtmpMBTWKO/model-2b8187b4bf4ae.stan', line 40, column 2: Declaration
>     of arrays by placing brackets after a type is deprecated and will be
>     removed in Stan 2.32.0. Instead use the array keyword before the type.
>     This can be changed automatically using the auto-format flag to stanc

**Comment by rok-cesnovar** [comment]
This warning is issued in the 2.29 release, which is in the RC phase at the moment (announcement out shortly - it is however already available on the CmdStan release page). 

Did you by any chance install the release candidate CmdStan?

**Comment by rok-cesnovar** [comment]
This warning will be issued when using the old array syntax which will no longer be supported in Stan after the 2.32 release (in a year). Essentially all `int a[N]` will have to be replaced by `array[N] int a` at some point.

**Comment by afni-gangc** [comment]
> This warning is issued in the 2.29 release, which is in the RC phase at the moment (announcement out shortly - it is however already available on the CmdStan release page).
> 
> Did you by any chance install the release candidate CmdStan manually?

Yes, I installed CmdStan manually. Is this a benign issue that I don't have to worry about?

**Comment by rok-cesnovar** [comment]
> Is this a benign issue that I don't have to worry about?

You do not have to worry about this warning. It will just be annoying, but nothing is wrong.

You did install a release candidate, meaning that it has not officially been released. It will be in ~2 weeks, barring any critical bugs. It's not likely you will experience any other issues, but if you want to be on the safe side I would install the last release 2.28.2.

**Comment by afni-gangc** [comment]
Thanks @rok-cesnovar ! A naive question - I usually use the following command to grab CmdStan:

> git clone https://github.com/stan-dev/cmdstan.git --recursive

How do I use a similar command line to get the last release?

**Comment by rok-cesnovar** [comment]
@afni-gangc The command you ran will grab the latest development version of CmdStan, which is great if you want to use the latest features and all but can sometimes break as it happens with ongoing development. if there is no specific reason you need the development version, I would suggest installing the latest release by grinning:

```
cmdstanr::install_cmdstan(cores = 4)
# replace 4 with your own value - this just speeds up building cmdstan
```

If you want a specific version, you can specify that by running
```
cmdstanr::install_cmdstan(version = "2.28.2", cores = 4)
```
