### ISSUE TITLE
Error in `brm` function when argument `threads` is used with algorithm `meanfield`

### ISSUE THREAD

**Issue by neringabr** [paul-buerkner/brms#1297]
I tried to use threads for within-chain parallelization via brms interface. Adding `threads` argument to `brm` function where `algorithm = "meanfield"` returned an error:
```
Compiling Stan program...
Start sampling
Error in .fun(data = .x1, seed = .x2, init = .x3, threads_per_chain = .x4,  : 
  unused argument (threads_per_chain = .x4)
```

This problem is also described in [Stan discourse](https://discourse.mc-stan.org/t/reduce-sum-using-variational-inference-algorithm/26158).

brms version: `brms_2.16.3`
cmdstan version: `2.28.2`
cmdstanr version: `cmdstanr_0.4.0.9001`

Full code:
```
library(cmdstanr)
library(rstan)
library(brms)
tryCatch({cmdstanr::set_cmdstan_path('/home/cmdstanr/cmdstan-2.28.2')})
cmdstan_version()

N <- 1000
nchains = 3
ncores = 3
nthreads = 8

data0 <- 
  tibble(
    x = rnorm(N, 0, 1), # x = F1
    x1 = rnorm(N, 1*x, 1),
    x2 = rnorm(N, 0.5*x, 1),
    x3 = rnorm(N, 1*x, 1),
    F1 = as.numeric(NA)
  )

bf0 <- bf(x1 ~ 0 + mi(F1)) +
  bf(x2 ~ 0 + mi(F1)) +
  bf(x3 ~ 0 + mi(F1)) +
  bf(F1 | mi() ~ 1) + 
  set_rescor(rescor = FALSE)

prior0 <- prior(constant(1), class = "b", resp = "x1") +
  prior(constant(1), class = "sigma", resp = "x1") +
  prior(normal(0, 10), class = "b", resp = "x2") +
  prior(constant(1), class = "sigma", resp = "x2") +
  prior(normal(0, 10), class = "b", resp = "x3") +
  prior(constant(1), class = "sigma", resp = "x3") +
  prior(normal(0, 10), class = "Intercept", resp = "F1") +
  prior(cauchy(0, 1), class = "sigma", resp = "F1")

m1_threads <- 
  brm(
    formula = bf0,
    prior = prior0,
    data = data0,
    iter = 1000,
    backend = "cmdstanr",
    algorithm = 'meanfield',
    threads = threading(threads = nthreads, grainsize = NULL,static = FALSE),
    control = list(tol_rel_obj = 0.00000001),
    refresh = 5,
    chains = nchains,
    cores = ncores
  )
```

While debugging it seems that error is returned by command `x$fit <- do_call(fit_model, fit_args)`:
```
Browse[2]> n
debug: x$fit <- do_call(fit_model, fit_args)
Browse[2]> n
Start sampling
Error in .fun(data = .x1, seed = .x2, init = .x3, threads_per_chain = .x4,  : 
  unused argument (threads_per_chain = .x4)
```

Information from `rlang`:
```
> rlang::last_error()
<error/rlang_error>
Error:
! unused argument (threads_per_chain = .x4)
Backtrace:
  1. brms::brm(...)
  2. brms::do_call(fit_model, fit_args)
  3. brms:::eval2(call, envir = args, enclos = envir)
  4. [ base::eval(...) ] with 1 more call
  6. brms .fun(...)
  7. brms .fit_model(model, ...)
  8. brms::do_call(model$variational, args)
  9. brms:::eval2(call, envir = args, enclos = envir)
 10. [ base::eval(...) ] with 1 more call
Run `rlang::last_trace()` to see the full context.

> rlang::last_trace()
<error/rlang_error>
Error:
! unused argument (threads_per_chain = .x4)
Backtrace:
     ▆
  1. └─brms::brm(...)
  2.   └─brms::do_call(fit_model, fit_args)
  3.     └─brms:::eval2(call, envir = args, enclos = envir)
  4.       └─base::eval(expr, envir, ...)
  5.         └─base::eval(expr, envir, ...)
  6.           └─brms .fun(...)
  7.             └─brms .fit_model(model, ...)
  8.               └─brms::do_call(model$variational, args)
  9.                 └─brms:::eval2(call, envir = args, enclos = envir)
 10.                   └─base::eval(expr, envir, ...)
 11.                     └─base::eval(expr, envir, ...)
 ```

**Comment by paul-buerkner** [comment]
is mean field supposed to work with threading at all?

neringabr ***@***.***> schrieb am Sa., 12. Feb. 2022, 12:39:

**Comment by neringabr** [comment]
Hello, Paul. I am new here and I can be wrong, but as I understand, meanfield should work with threading. In my given [link](https://discourse.mc-stan.org/t/reduce-sum-using-variational-inference-algorithm/26158) you can see that I succeeded to call variational inference algorithm with threading, but it took several steps: I made brm object, saved stan code and native stan data structure from brm object, in saved .stan file I changed `reduce_sum` to `reduce_sum_static`, compiled stan code while enabling `reduce_sum` with `cpp_options = list(stan_threads = TRUE)` and did variational inference with `$variational`.

**Comment by rok-cesnovar** [comment]
> is mean field supposed to work with threading at all?

Based on the error (I havent looked at the source code) I would say the issue stems from the fact cmdstanr uses the argument `threds_per_chain` for sampling, but only `threads` for everything else, as there is no concept of chains for optimization/VI in Stan.

**Comment by paul-buerkner** [comment]
Makes sense. I will fix it.

**Comment by paul-buerkner** [comment]
I think I had already fixed this on github some time ago. Thus, should be working correctly with the github version of brms.

**Comment by paul-buerkner** [comment]
It does work for me. I guess you just need to restart your R session.

**Comment by neringabr** [comment]
My bad, works like a charm, thank you! 💯
