### ISSUE TITLE
model stops running after "start sampling" message

### ISSUE THREAD

**Issue by aitorme** [paul-buerkner/brms#1300]
I am trying to run the following model in an Ubuntu 20.04 server:

```brm(
  formula = p
  ~ 1 + g * d * s * v,
  family = bernoulli(link = "logit"),
  data = me,
  prior = me_priors,
  chains = 1,
  iter = 1000,
  cores = 1,
  silent = F,
  seed = 42,
  warmup = 500,
  control = list(adapt_delta = 0.95,max_treedepth = 15),
  save_pars = save_pars(all=TRUE)
  )
```

but after the log file prints `Start sampling`, the model stops running. I check the running threads with `ps` but it's empty.
I'm running `brms_2.16.3` and my R version is `3.6.3`.

**Comment by aitorme** [comment]
I tried it on my local machine and there's an actual error being printed, saying 
`
SAMPLING FOR MODEL '8ccc6557cf697945d7ee1618f2bf78aa' NOW (CHAIN 1).
[1] "Error in sampler$call_sampler(args_list[[i]]) : "            
[2] "  VECTOR_ELT() can only be applied to a 'list', not a 'NULL'"
`

**Comment by paul-buerkner** [comment]
I cannot really tell what is going on but it does not look like a specific brms issue. Would you asking https://discourse.mc-stan.org/ ? It would help a lot if you could provide a minimal reproducible example for your problem.
