### ISSUE TITLE
Changed default parameterization for shifted lognormal family?

### ISSUE THREAD

**Issue by nahorp** [paul-buerkner/brms#1305]
Hello,

I fitted 2 models, 1-2 years apart, using the `shifted_lognormal()` family argument (with default links). The earlier one is as below,

![Screen Shot 2022-02-28 at 9 14 13 am](https://user-images.githubusercontent.com/43395036/155902521-4b670cd3-4055-437c-8aff-16b686d91418.png)

This is congruent with the `?brmsfamily` help documentation (as below),

![Screen Shot 2022-02-28 at 9 25 36 am](https://user-images.githubusercontent.com/43395036/155902537-b2babb25-4fce-42fe-b048-0d13db4a6f33.png)

However, the newer one shows identity link functions (vs. log previously) for sigma and ndt parameters. Am I missing something?

![Screen Shot 2022-02-28 at 9 14 26 am](https://user-images.githubusercontent.com/43395036/155902581-6d76f5f2-04fb-4940-a234-0a510f57561e.png)

Thank you for reading :)

**Comment by paul-buerkner** [comment]
No, this is just a change in how the summary output displays the links. The links of non-mu parameters only apply if those parameters are predicted (via a separate formula), which is now reflected in the summary output.
