### ISSUE TITLE
Request: Support multivariate with missing data a response.

### ISSUE THREAD

**Issue by groceryheist** [paul-buerkner/brms#1306]
#27 added the great feature for imputing missing data on-the-fly when fitting models.  

I think I have uncovered a limitation of `mi` that comes up when I want to fit y ~ x but y has a high missing rate. I can measure w which a reasonably good approximation of y. So I want to impute y using w and also estimate y ~ x.

As I elaborated [on discorse](https://discourse.mc-stan.org/t/modeling-missing-data-on-outcomes-in-brms/26600), a formula like `model <- brm(formula=bf(y.obs | mi() ~ w) + bf(mi(y.obs) ~ x) + set_rescor(FALSE))` leads to an error `invalid type (list) for variable 'mi(y.obs)'`

Can the `mi` function be extended to support multivariate models with missing data in an outcome?

**Comment by paul-buerkner** [comment]
I don't understand what you are trying to achieve unfortunately. You seem to be using the same response variable twice and you use incorrect mi() syntax, as on the left-hand side you need to use y | mi() not mi(y). Missing values in multivariate models is already working I think with the correct syntax.

**Comment by groceryheist** [comment]
Maybe I don't understand how `mi()` works? I'm learning about measurement error models.
If `x` has missing data and `w` is a proxy, I can do `bf(y ~ mi(x)) + bf(x | mi() ~ w)`.
I'm trying to understand how comparable this model is to `y ~ MeasError(x,w)` using the R package `mecore.`    

`MeasErr(y,w) ~ x` is a valid model. Can `brms`  fit a comparable one? 

This comment might help me get an answer to my question on Discorse so I think I may cross post it there.

**Comment by paul-buerkner** [comment]
I think I would prefer to continue this question on discourse.
