### ISSUE TITLE
Strange behavior for predictions from multinomial mixed model

### ISSUE THREAD

**Issue by DominiqueMakowski** [paul-buerkner/brms#1309]
Hi Paul,

I am currently working with the `categorical` family, and trying to compute the derivative of the predictions (i.e., the difference between predictions with a slight increment of `1e-5`). 

For non-mixed models, *or* for mixed models that have a random effect != `NA` in the newdata, things work as expected: the CI of the difference between the predictions are in a "normal range".

``` r
library(brms)

data <- mtcars
data$cyl <- as.character(data$cyl)

model <- brm(cyl ~ mpg * vs + (1 | carb),
             data = data,
             chains = 6,
             iter = 3000,
             algorithm = "meanfield",
             refresh=0,
             family = categorical(link = "logit", refcat = "4"))

# Random effect != NA (carb = 1)
newdata0 <- newdata1 <- data.frame(mpg = 20, vs = 0, carb = 1)
newdata1$mpg <- newdata1$mpg + 1e-5
pred0 <- posterior_epred(model, newdata = newdata0)
pred1 <- posterior_epred(model, newdata = newdata1)
dydx <- (pred1 - pred0) / 1e-5

apply(dydx[, 1, ], 2, quantile, probs = c(.025, .975))
#>                  4            6             8
#> 2.5%  5.374784e-07 -0.000155912 -1.501715e+00
#> 97.5% 2.804111e-02  1.483170736 -4.900558e-05
```

However, as soon as we set the random effect to `NA` to get population-level predictions, the resulting CIs go off the roof.  

``` r
# Carb = NA
newdata0 <- newdata1 <- data.frame(mpg = 20, vs = 0, carb = NA)
newdata1$mpg <- newdata1$mpg + 1e-5
pred0 <- posterior_epred(model, newdata = newdata0)
pred1 <- posterior_epred(model, newdata = newdata1)
dydx <- (pred1 - pred0) / 1e-5

apply(dydx[, 1, ], 2, quantile, probs = c(.025, .975))
#>               4         6         8
#> 2.5%  -763.8764 -90644.62 -94439.20
#> 97.5%  662.4377  94631.06  90715.51
```

<sup>Created on 2022-03-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Could it be a bug with the population-level predictions for multinomial models?
As always, thanks a lot :) 
(see https://github.com/vincentarelbundock/marginaleffects/issues/219 for some more examples)

**Comment by paul-buerkner** [comment]
You need to set `re_formula = NA` to achieve what you want. Grouping variable `= NA` will just be treated as a new level which may cause a whole lot of numerical problems. Strangely so, `carb = NA` should not even work because you did not allow new levels, via `allow_new_levels = TRUE`. So while there seems to be a bug (your code should error), the code would not achieve what you want even if there was no bug.

**Comment by paul-buerkner** [comment]
Hmm, it seems that in the github version of brms, we already see 

```R
red0 <- posterior_epred(model, newdata = newdata0)
 Error: NAs are not allowed in grouping variables.
```

So this should be fixed on github already.

**Comment by DominiqueMakowski** [comment]
It works as expected, thanks a ton :)
