### ISSUE TITLE
Default priors

### ISSUE THREAD

**Issue by mvuorre** [paul-buerkner/brms#131]
This package has tremendous value, especially for people making the transition from `[g]lm[er]()` to bayesian regression models. The transition really is quite seamless, but there's one thing that may cause some confusion among beginners: The default student's _t_ priors on the Standard deviations of group-level (’random’) effects ([brms manual](https://cran.r-project.org/web/packages/brms/brms.pdf) p. 60):

> These parameters are restriced [sic] to be non-negative and, **by default**, have a half student-t prior with 3 degrees of freedom and a scale parameter that depends on the standard deviation of the response after applying the link function. Minimally, the scale parameter is 10.

Also, it seems that this prior is placed on the residual as well (and I don't think this is mentioned in the manual):

```r
> get_prior(y ~ x + (x | id), data = data)
                 prior     class      coef group nlpar bound
1                              b                            
2                              b Intercept                  
3                              b         x                  
4               lkj(1)       cor                            
5                            cor              id            
6                      Intercept                            
7  student_t(3, 0, 10)        sd                            
8                             sd              id            
9                             sd Intercept    id            
10                            sd         x    id            
11 student_t(3, 0, 10)     sigma    
```

Many might agree that this prior distribution is indeed preferred over Uniform(-Inf [or 0], Inf) (Gelman, 2006), but I am not convinced that it should be set as the default, especially when the user really needs to read the entire manual to find out that such a default prior is indeed placed. This is of course a matter up for debate, but I think there are reasons for not placing a default prior:

1. Beginning Bayesians may see the priors as unduly influencing their results (i.e. you may be scaring away potential customers!)
2. To most closely reproduce `[g]lm[er]()` output, users now have to specify flat priors to replace the default. It might be best to, by default, most closely follow those results.
3. From an educational perspective, not having a default _might_ be preferred. I have noticed that students very often are suspicious of any priors. This is not an argument for priors being good or bad, but rather that default priors may be impeding the adoption of Bayesian methods.

In any case, I hope some more thought / discussion would go into choosing this specific default, and that it would be better articulated and clearly mentioned in the manual / `brm()` help page.

Cheers.

**Reference**
Gelman, A. (2006). Prior distributions for variance parameters in hierarchical models (comment on article by Browne and Draper). Bayesian Analysis, 1(3), 515–534.

**Comment by paul-buerkner** [comment]
Hi Matti, 

thanks for your suggestions. Indeed I should mention this more prominently in the manual (I believe it is stated in the packages main vignette / paper `vignette("brms")`, though). Also I should make more clear that this priors are chosen to be only **weakly** informative. Since his paper in 2006, I think Gelman has changed his mind and now argues relatively strongly against uniform priors if I am not mistaken.

The thing is that, at least for hierachical parameters, a proper prior is required for sampling efficiency and convergence so I can't get rid of it even if I wanted. I am not totally sure if this also applies for the residual SD, but I think it's more save to also have a prior there.

From my perspective, it's really a problem that people are scared about priors. Who has told them to be scared of them? In **brms** I try hard to make sure that default priors (I consider improper flat priors also as priors even if they are not proper) are "influencing" the results as little as possible but whenever I am doing an analysis myself I think of ways to make priors more reasonable and tailored to the scale of the data. 

In multilevel models, you will likely not get the same results for the random effects parameters  and [g]lmer even if all priors were improer flat, since the distributions of the parameters are often skewed and thus mode and mean won't conincide. Why should we aim for most closely reproducing glmer? It may be the benchmark that people have in mind but it's not the right benchmark I believe.

I will improve the related documentation tonight.

**Comment by paul-buerkner** [comment]
I have tried to improve the doc of the priors. Any feedback is hightly welcome! :-)

**Comment by mvuorre** [comment]
Thanks for getting on this so quickly. These additions to the manual take care of some of the issues (users who go through the manual won't be able to miss that there are default priors.) However it's still possible that a user may run these models without being aware that there are prior distributions (and I agree that it is likely a good thing and / or required for efficient sampling.)

I wonder if it might be reasonable to have some sort of an indicator in the default output from `summary()` or `print()` that indicates the priors? This way the priors would always be transparent. For example, one section of the output might capture rows of `get_prior(formula, data)` where priors exist.

> Who has told them to be scared of them [priors]?

Based on casual observation, it seems that many people are at least suspicious of anything except the data influencing results. (I'm sure there's a psychology experiment or two to be done to investigate this phenomenon. [This paper](http://pps.sagepub.com/content/6/3/313.long) may be related.) So my point was more about being user-friendly for many people who are transitioning to Bayesian estimation. But it seems that your default priors are the way to go, and I believe that people just need to be aware of them.

> Why should we aim for most closely reproducing glmer?

This is an excellent question. The point I took with this issue was that many users transition from glmer, and therefore might be most comfortable with (most) comparable output.

Thanks!

**Comment by paul-buerkner** [comment]
I think it's totally ok for users to be unaware of these default priors. The reason I set them is that people don't have to worry about them, if they don't like or don't feel comfortable with priors (or don't want to read the doc). After all, I feel that users who are just using **brms** without taking a deeper look won't benefit much from getting the default priors printed. Instead, they would likely rather be scared that these priors were "biasing" their results as you pointed out. Thus, I hesitate putting them into the summary output at this would put too much emphasize on them and possibly also clutter the output for more complex models with explicitely user defined priors.

My questions were a bit of rhetorical and not directed against your argumentation. I agree and often see these reservations against Bayes and priors myself and I am trying my best to explain why this is nothing to worry about (with more or less success). In fact, what people tend to forget is that their likelihood is a model assumption in the same way as is the prior. So it's not just about the data even in frequentist analysis. In fact, people often don't investigate or ignore model violations and just perform ANOVA for whatever data they have, at least in some parts of psychology.

**Comment by mvuorre** [comment]
OK. I think it's sufficient, then, that these are described in the manual, as in the changes you've just made. Thanks for taking the time to think about these points.

**Comment by paul-buerkner** [comment]
Thank you for bringing up this issue! This is certainly an important point and I will see how I can further improve it going forward.
