### ISSUE TITLE
support for the new ppd plots from Bayesplot

### ISSUE THREAD

**Issue by bnicenboim** [paul-buerkner/brms#1313]
`bayesplot` has [prior predictive density plots](https://mc-stan.org/bayesplot/reference/PPD-distributions.html), it's basically the same as a post pred check but without plotting the original data.

It would be nice to have support for this as well.

**Comment by paul-buerkner** [comment]
Good idea. So the point would be to ignore the `y` argument? Or is there something else to it?

**Comment by wds15** [comment]
I think that's it. It's about visualising priors or predictions from the model in absence of data.

**Comment by bnicenboim** [comment]
yes, it ignores "y", and the functions are almost identical to the ppc, I think there are a couple less visualizations.
It would also be good if brms let you do `sample_prior="only"`, with all NAs in the DV. Right now you get this:

```
Error: All observations in the data were removed presumably because of NA values.
In addition: Warning message:
Rows containing NAs were excluded from the model. 
```

**Comment by paul-buerkner** [comment]
Can you open a separate issue for that?

**Comment by bnicenboim** [comment]
should I give it a try coding it? it seems fairly straightforward. Will you use the same `pp_check` functions? Or a new `pp_dens`?

**Comment by paul-buerkner** [comment]
Implemented via `pp_check(..., prefix = "ppd")`
