### ISSUE TITLE
Allow brms to sample only from priors when the DV are all NAs

### ISSUE THREAD

**Issue by bnicenboim** [paul-buerkner/brms#1315]
It would  be good if brms let you do `sample_prior="only"`, with all NAs in the DV. Right now you get this:

```
Error: All observations in the data were removed presumably because of NA values.
In addition: Warning message:
Rows containing NAs were excluded from the model. 
```

_Originally posted by @bnicenboim in https://github.com/paul-buerkner/brms/issues/1313#issuecomment-1064891737_

**Comment by bnicenboim** [comment]
hi, I've checked that to do this, it would be enough to change `validate_data` so it takes an argument `sample_prior` coming from `brm` and modify `validate_data` like this:
```
validate_data <- function(data, bterms, data2 = list(), knots = NULL,
                          na.action = na.omit2, drop.unused.levels = TRUE,
                          attr_terms = NULL, sample_prior = NULL) {
.....
if (!isTRUE(nrow(data) > 0L) && sample_prior != "only") {
    stop2("All observations in the data were removed ",
          "presumably because of NA values.")
  }
```

Or will it bring some unintended consequence?

**Comment by paul-buerkner** [comment]
I don't think it is that easy unfortunately. First, you need to adjust `na.omit2` that handles the actual exclusion of missing values. Then you may need define the behavior of response-scaled default priors when they have no response variable values to use for scaling (the latter may already be handled; would have to check).

**Comment by bnicenboim** [comment]
ok, understood. This new feature would lead to some changes in the prior predictive checks section of our book, I was checking if I could speed it up. ;) 
But no worries (BTW, I still believe you're doing a quite amazing job with all the github issues!)

**Comment by paul-buerkner** [comment]
Closing this issue to reduce load of the issue tracker, as I don't think it is high enough priority.
