### ISSUE TITLE
is the output from residuals correct when y has multiple columns? 

### ISSUE THREAD

**Issue by jgabry** [paul-buerkner/brms#132]
Hey Paul, I was playing around with brms a bit and came across the following: 

```r
bfit <- brm(
  cbind(incidence, size - incidence) ~ size + period + (1 | herd), 
  data = lme4::cbpp, 
  # next 2 lines just for speed for example purposes
  iter = 50, 
  chains = 1
)
r <- residuals(bfit, method = "predict", summary = FALSE)
```

The object `r` has dimensions
```r
> dim(r)
[1]  25 112
```
however the data has only 
```
> nobs(bfit)
[1] 56
```
observations. 

Is it computing residuals for _both_ columns of the outcome matrix?

**Comment by paul-buerkner** [comment]
You just specified a bivariate normal model, which produces residuals for both response variables.
Did you want to specify a binomial model? If so, try

```R
bfit <- brm(
  incidence | trials(size) ~ size + period + (1 | herd), 
  data = lme4::cbpp, 
  # next 2 lines just for speed for example purposes
  iter = 50, 
  chains = 1
)
```

**Comment by jgabry** [comment]
Haha, oops. My bad. Yes, I thought I had specified a binomial model but I forgot to include the `family` argument. `residuals` seems to be working ok if I switch to `family=binomial()`, so I'll close this.  

Follow up question out of curiosity: did you recently disallow using the same syntax as glm and glmer for specifying the outcome in a binomial model or has it always been that way in brms? I don't dislike the syntax the way you have it, just curious.

**Comment by paul-buerkner** [comment]
It has always been this way, since I want to reserve `cbind` purely for multivariate models.
