### ISSUE TITLE
Feature request: Extrapolation for conditional_effects()

### ISSUE THREAD

**Issue by RyokoNod** [paul-buerkner/brms#1325]
Hello Paul,

Could I request a feature that lets you set the conditional effect plot's range outside of the training data's maximum and minimum? I would really like to see how my GAM/GLM models extrapolate outside of the data they're fit with.

I think the current range is defined with variables `min1`, `min2`, `max1`, `max2` in your code. If a user can define the range themselves, it might help them (and me) understand how models behave outside of their comfort zone.

Please let me know if I'm making a logically or theoretically unreasonable request - I'm still a beginner Bayesian so I might have some misunderstanding.

**Comment by paul-buerkner** [comment]
Argument `int_conditions` should allow you to do this, at least in the latest versions of brms.

**Comment by RyokoNod** [comment]
Indeed it is! Thank you, I could have never figured it out from the documentation.

**Comment by paul-buerkner** [comment]
yeah you are right. the documention is not very clear in that regard yet.

Ryoko Noda ***@***.***> schrieb am Mi., 30. März 2022, 05:51:
