### ISSUE TITLE
Feature Request: conditional_effects() for sigmas

### ISSUE THREAD

**Issue by thisisnickb** [paul-buerkner/brms#1328]
Unless I'm missing something (which, well, probably I am), I don't think there's any way to get a conditional_effects() sort of plot or output for the sigma parameters in mixed-effects location-scale models - that function (and the conceptually-related functions in emmeans, if I'm not mistaken) only seem be able to work with betas. Extending the functionality to working with sigmas would be really useful to those of us who are becoming more and more interested in understanding variability.

**Comment by paul-buerkner** [comment]
use argument dpar = "sigma"

thisisnickb ***@***.***> schrieb am Sa., 26. März 2022, 00:26:

**Comment by thisisnickb** [comment]
Brilliant - thanks!
