### ISSUE TITLE
Error launching shinystan (rstan backend)

### ISSUE THREAD

**Issue by fweber144** [paul-buerkner/brms#1329]
With the current `master` version (commit 5acaa4ea929732c98435ccd4feebd63a5f2e4cad), an error is thrown when trying to launch the shinystan app for an rstan-fitted model whereas the issue does not occur for a cmdstanr-fitted model:
```r
library(brms)
options(mc.cores = parallel::detectCores(logical = FALSE))

# rstan backend -----------------------------------------------------------

fit_rstan <- brm(rate ~ conc + state,
                 data = Puromycin,
                 seed = 11403)

library(shinystan)
launch_shinystan(fit_rstan)
## Throws:
# Error in .validate_sampler_params(sampler_params, n_chain = ncol(X), n_iter = nrow(X),  : 
#   Each matrix in 'sampler_params' must have number of rows equal to number of iterations in 'X'. 
## 

# cmdstanr backend --------------------------------------------------------

fit_cmdstanr <- brm(rate ~ conc + state,
                    data = Puromycin,
                    backend = "cmdstanr",
                    seed = 11403)

launch_shinystan(fit_cmdstanr)
## Works.
```
I have tested this with rstan v2.21.3 and v2.26.6 (the latter from <https://mc-stan.org/r-packages/>) and cmdstanr v2.29.2. Tell me if you need more session info.

**Comment by fweber144** [comment]
This is probably related to #1257 which is basically the same issue, just with the cmdstanr backend and `save_warmup = TRUE`. I'm sorry that I didn't realize the relationship earlier.

So perhaps `save_warmup = TRUE` is the underlying problem? If I remember correctly, the rstan backend has `save_warmup = TRUE` by default whereas the cmdstanr backend has `save_warmup = FALSE`.

**Comment by paul-buerkner** [comment]
Both issues should now be fixed.
