### ISSUE TITLE
Speed up `summary` function: problem of latent variables being summarized 

### ISSUE THREAD

**Issue by neringabr** [paul-buerkner/brms#1330]
Hello,

I have a `brms fit` of a latent factor model with 20000 subject ids and 140162 observations. Model looks like this:

```
 Family: MV(gaussian, gaussian, gaussian, gaussian, gaussian, gaussian, gaussian, gaussian, bernoulli) 
  Links: mu = identity; sigma = identity
         mu = identity; sigma = identity
         mu = identity; sigma = identity
         mu = identity; sigma = identity
         mu = identity; sigma = identity
         mu = identity; sigma = identity
         mu = identity; sigma = identity
         mu = identity; sigma = identity
         mu = logit 
Formula: x1 ~ 0 + mi(F1) + (1 | ID) 
         x2 ~ 0 + mi(F1) + (1 | ID) 
         x3 ~ 0 + mi(F1) + (1 | ID) 
         x4 ~ 0 + mi(F2) + (1 | ID) 
         x5 ~ 0 + mi(F2) + (1 | ID) 
         x6 ~ 0 + mi(F2) + (1 | ID) 
         F1 | mi() ~ 0 + arma(time = t, gr = ID, p = 0, q = 4, cov = FALSE) 
         F2 | mi() ~ 0 + arma(time = t, gr = ID, p = 0, q = 4, cov = FALSE) 
         yBinary ~ mi(F1) + mi(F2) + (1 | ID) 
   Data: data0 (Number of observations: 140162) 
  Draws: 1 chains, each with iter = 500; warmup = 0; thin = 1;
         total post-warmup draws = 500
```

From the formulas above you can see that I treat latent variables (`F1`, `F2`) as missing values with `mi()`. Source where I got this idea is here: https://github.com/paul-buerkner/brms/issues/304. These latent variables are needed to describe my variables [`x1`, `x2`, ...,, `x6`]. Latent factor estimates are not interesting to me, I am only interested in [`x1`, `x2`, ...,, `x6`] and `yBinary` estimates.  

However, in `summary.brmsfit()` function an object is created that stores all the information about variables estimates in each iteration, including latent factor values for each observation and iteration. In my case, due to two latent variables treated as missing values I have 2x140162 more parameters:
1. `Ymi_F1[1]` to `Ymi_F1[140162]` for factor `F1` ,
2. `Ymi_F2[1]` to `Ymi_F2[140162]` for factor `F2`.

Storing and handling these ~280k additional parameters really slows down `summary` function: if I drop every variable with missing latent factor inside `summary.brmsfit()` function (they are unnecessary to `summary` function), summary takes only several minutes instead of 9-10 hours. 

So apparently, the latent variables are accidentally summarized for some reason and removing them really speeds up summary function.

**Comment by paul-buerkner** [comment]
Thank you for opening this issue. Does this issue persist in the latest github version of brms?

**Comment by neringabr** [comment]
I will check today and let you know. Thank you!

**Comment by neringabr** [comment]
> Thank you for opening this issue. Does this issue persist in the latest github version of brms?

Hello, yes, issue persists on newest `brms` version (brms_2.16.12). I compared results in two `brms` versions: 
1. `brms@HEAD`  
2. `brms@1138efc`

From `brms@1138efc` I did not find any changes, which could help to solve this issue. If you could clarify what changes have been done to solve this issue (for example: commit number, script name), let me know!

**Comment by paul-buerkner** [comment]
I think I just fixed it on github. Can you double check?
