### ISSUE TITLE
file slot not properly set?

### ISSUE THREAD

**Issue by wds15** [paul-buerkner/brms#1351]
When using the `file` argument of `brm`, the resulting `brmsfit` object has the file slot set to `NULL`. Example:

```r
bmodel10_def <- brm(mf10, data=avitamind_fas, prior=bpriorL3,
                    file="long_model_10",
                    chains=0,
               control=list(adapt_delta=0.95),
               threads=threading(4),
               backend="cmdstanr")

bmodel10_def$file
```

At this stage `bmodel10_def$file` is `NULL`. When running the above code again, then the fit is loaded from the file and the `file` slot is correctly set to the filename `long_model_10.rds`... but shouldn't `file` be set to this value directly after the first call (initial)?

this is brms 2.16.0

**Comment by wds15** [comment]
The issue with not having `files` slot correctly is that the downstream tools like `add_criterium` won't cache things.

**Comment by paul-buerkner** [comment]
I remember to have fixed something like that at some point. Does it still occur in brms 2.17.0+?

**Comment by wds15** [comment]
indeed. The GitHub version does not have this issue. Sorry for the noise. Thanks.
