### ISSUE TITLE
Possible bug in `gr()`

### ISSUE THREAD

**Issue by rpsychologist** [paul-buerkner/brms#1353]
I'm not sure if this is a bug, but combining a global random intercept with separe random slopes using `gr()` will create a dimension mismatch.

Reprex using the epilepsy dataset.
```r
library(brms)
library(lme4)
epilepsy$visit <- as.numeric(epilepsy$visit)
lmer(
    count ~ visit * Trt + 
        (1 | patient) + 
        (0 + dummy(Trt, "0"):visit | patient) + 
        (0 + dummy(Trt, "1"):visit | patient), 
    data = epilepsy)

brm(
    count ~ visit * Trt + 
        (1 | patient) + 
        (0 + visit | gr(patient, by = Trt)),
    data = epilepsy
)
```
Error
```
Compiling Stan program...
Start sampling
Error in mod$fit_ptr() : 
  Exception: mismatch in dimension declared and found in context; processing stage=data initialization; variable name=Jby_2; position=0; dims declared=(59); dims found=(0) 
```

`[1] lme4_1.1-27  Matrix_1.4-1 brms_2.17.0 rstan_2.21.5`

**Comment by paul-buerkner** [comment]
The problem is that you have multiple terms of the same grouping factor with different `by` inputs. This situation was not envisoned in the brms code structure and I need to think of the best way to fix it. For now, changing the order of the two terms might fix it.

**Comment by paul-buerkner** [comment]
The issue should now be fixed.
