### ISSUE TITLE
error in emmeans with regrid/tran arguments

### ISSUE THREAD

**Issue by mattansb** [paul-buerkner/brms#1360]
```R
library(emmeans)
library(brms)

data("mtcars")

mtcars$log_mpg <- log(mtcars$mpg)

m_pre.trans <- brm(log_mpg ~ factor(cyl) * hp, mtcars,
                   family = gaussian(),
                   refresh = 0, backend = "cmdstanr")
m_in.formula <- brm(log(mpg) ~ factor(cyl) * hp, mtcars,
                    family = gaussian(),
                    refresh = 0, backend = "cmdstanr")

emtrends(m_in.formula, ~ cyl, "hp",
         regrid = "response")
#>  cyl  hp.trend lower.HPD upper.HPD
#>    4 -0.004379  -0.00877  0.001094
#>    6 -0.000305  -0.00567  0.005125
#>    8 -0.000877  -0.00269  0.000864
#> 
#> Point estimate displayed: median 
#> HPD interval probability: 0.95
```

Should return the same results as above, but...

```R
emtrends(m_pre.trans, ~ cyl, "hp",
         tran = "log", regrid = "response")
#> Error: Cannot coerce 'transform' to a single logical value.
```

Note that this *is* unique to `brms` - it works with [`stats::glm()`](https://github.com/rvlenth/emmeans/issues/352) and with `rstanarm::stan_glm()`.

I have yet to take a deep dive to see where this happens exactly, so if @rvlenth or @paul-buerkner have any idea where this might be happening, your help would be greatly appreciated!

**Comment by rvlenth** [comment]
Clearly, some function somewhere in the brms codebase is matching tran with a logical argument named transform.

Sent from my iPhone

On May 24, 2022, at 9:27 AM, Mattan S. Ben-Shachar ***@***.***> wrote:

﻿

library(emmeans)
library(brms)

data("mtcars")

mtcars$log_mpg <- log(mtcars$mpg)

m_pre.trans <- brm(log_mpg ~ factor(cyl) * hp, mtcars,
                   family = gaussian(),
                   refresh = 0, backend = "cmdstanr")
m_in.formula <- brm(log(mpg) ~ factor(cyl) * hp, mtcars,
                    family = gaussian(),
                    refresh = 0, backend = "cmdstanr")

emtrends(m_in.formula, ~ cyl, "hp",
         regrid = "response")
#>  cyl  hp.trend lower.HPD upper.HPD
#>    4 -0.004379  -0.00877  0.001094
#>    6 -0.000305  -0.00567  0.005125
#>    8 -0.000877  -0.00269  0.000864
#>
#> Point estimate displayed: median
#> HPD interval probability: 0.95

Should return the same results as above, but...

emtrends(m_pre.trans, ~ cyl, "hp",
         tran = "log", regrid = "response")
#> Error: Cannot coerce 'transform' to a single logical value.

Note that this is unique to brms - it works with stats::glm()<https://github.com/rvlenth/emmeans/issues/352> and with rstanarm::stan_glm().

I have yet to take a deep dive to see where this happens exactly, so if @rvlenth<https://github.com/rvlenth> or @paul-buerkner<https://github.com/paul-buerkner> have any idea where this might be happening, your help would be greatly appreciated!

**Comment by paul-buerkner** [comment]
Yes, indeed. Thank you. Let's see what I can do about that.

**Comment by mattansb** [comment]
Found it - I'll make a PR.
Thanks @rvlenth !

**Comment by mattansb** [comment]
After setting `posterior_linpred(transform = FALSE)` (instead of having this argument controlled by `...`) the examples below no longer fails to run (https://github.com/mattansb/brms/commit/7f91acb13c0333bdd320977d76e23ad376034e6b)

```R
library(emmeans)
library(brms)

data("mtcars")

mtcars$log_mpg <- log(mtcars$mpg)

m_pre.trans <- brm(log_mpg ~ factor(cyl) * hp, mtcars,
                   family = gaussian(),
                   refresh = 0, backend = "cmdstanr")
m_in.formula <- brm(log(mpg) ~ factor(cyl) * hp, mtcars,
                    family = gaussian(),
                    refresh = 0, backend = "cmdstanr")

emtrends(m_in.formula, ~ cyl, "hp",
         regrid = "response")
#>  cyl  hp.trend lower.HPD upper.HPD
#>    4 -0.004379  -0.00877  0.001094
#>    6 -0.000305  -0.00567  0.005125
#>    8 -0.000877  -0.00269  0.000864
#> 
#> Point estimate displayed: median 
#> HPD interval probability: 0.95

emtrends(m_pre.trans, ~ cyl, "hp",
         tran = "log", regrid = "response")
#>  cyl hp.trend lower.HPD upper.HPD
#>    4 -0.08730   -0.1443 -0.000735
#>    6 -0.00575   -0.1090  0.102403
#>    8 -0.01362   -0.0448  0.016138
#> 
#> Point estimate displayed: median 
#> Results are given on the log (not the response) scale. 
#> HPD interval probability: 0.95
```

However, it still does not give the same results that `rstanarm::stan_glm` or `stats::glm` do (both `emtrends` should give the same estimates).
I'm not sure why this happens. The footnote in the output says that "Results are given on the log (not the response) scale."

Without setting `regrid = "response"` it does however give the correct values, but still maintains the footnote?
@rvlenth Does this make sense?

```R
emtrends(m_pre.trans, ~ cyl, "hp",
         tran = "log")
#>  cyl  hp.trend lower.HPD upper.HPD
#>    4 -0.004411  -0.00964  0.000249
#>    6 -0.000292  -0.00565  0.005295
#>    8 -0.000870  -0.00274  0.000923
#> 
#> Point estimate displayed: median 
#> Results are given on the log (not the response) scale. 
#> HPD interval probability: 0.95 
```

**Comment by mattansb** [comment]
Actually, comparing to the `stats::glm` example, it seems that in the `m_in.formula` model that `log(mpg)` transformation isn't captured!

@paul-buerkner, is the original formula passed is such a way the `emmeans` can detect the in-formula transformation?

**Comment by rvlenth** [comment]
Please do:
```
RG <- emmeans::ref_grid(m_in.formula)
RG@model.info$call
```
With some luck, this will show the *first* argument as the model formula. That's what it would take for the transformation to be auto-detected. Note this parallel example:
```
> m = lm(log(mpg) ~ factor(cyl) * hp, mtcars)
> RG = ref_grid(m)
> RG@model.info$call
lm(formula = log(mpg) ~ factor(cyl) * hp, data = mtcars)

> ### Actually, just the show() method is enough to know what came through
> RG
'emmGrid' object with variables:
    cyl = 4, 6, 8
    hp = 146.69
Transformation: “log” 

> ### But here is the check I suggested
> RG@model.info$call
lm(formula = log(mpg) ~ factor(cyl) * hp, data = mtcars)
```
BTW, looking at results of `summary(RG)` are enough to diagnose issues like this. The `emmtrends()` layer just adds unnecessary complexity.

**Comment by rvlenth** [comment]
In spite of what I just said, I do agree that the annotation
> Results are given on the log (not the response) scale.
should not appear in the `emmtrends()` output. That is a bug in **emmeans** (not in **brms**) and I will try to fix it.

**Comment by mattansb** [comment]
```R
RG <- ref_grid(m_in.formula)
RG@model.info$call
#> brms()
```

@paul-buerkner this seems to be some of your code here https://github.com/paul-buerkner/brms/blob/master/R/emmeans.R#L59

@rvlenth Would it be enough for the call to include the formula?
(for `brms` this would be the sub-formula for the `resp` and `dpar`)

**Comment by paul-buerkner** [comment]
I am a bit out of depth with what emmeans expects as info in these cases, so I will likely need some concrete help with what to add as info, where and how.

**Comment by mattansb** [comment]
emmeans uses the `call` to get information about the predictors and outcome(s) for the formula (, and also information about weights, maybe?)

If you don't mind adding `insight` as a "local" dependency (in `Suggests` only), I think I can make these changes myself.

**Comment by rvlenth** [comment]
PS there is already a fairly formidable set...
```
> tools::package_dependencies("brms", recursive = TRUE)
$brms
  [1] "Rcpp"           "methods"        "rstan"          "ggplot2"        "loo"           
  [6] "posterior"      "Matrix"         "mgcv"           "rstantools"     "bayesplot"     
 [11] "shinystan"      "bridgesampling" "glue"           "future"         "matrixStats"   
 [16] "nleqslv"        "nlme"           "coda"           "abind"          "stats"         
 [21] "utils"          "parallel"       "grDevices"      "backports"      "dplyr"         
 [26] "ggridges"       "reshape2"       "rlang"          "tibble"         "tidyselect"    
 [31] "mvtnorm"        "Brobdingnag"    "stringr"        "scales"         "lattice"       
 [36] "digest"         "globals"        "listenv"        "parallelly"     "tools"         
 [41] "grid"           "gtable"         "isoband"        "MASS"           "withr"         
 [46] "checkmate"      "graphics"       "splines"        "vctrs"          "tensorA"       
 [51] "pillar"         "distributional" "StanHeaders"    "stats4"         "inline"        
 [56] "gridExtra"      "RcppParallel"   "pkgbuild"       "RcppEigen"      "BH"            
 [61] "desc"           "shiny"          "colourpicker"   "DT"             "dygraphs"      
 [66] "gtools"         "markdown"       "shinyjs"        "shinythemes"    "threejs"       
 [71] "xtable"         "xts"            "htmltools"      "htmlwidgets"    "jsonlite"      
 [76] "miniUI"         "cli"            "R6"             "rprojroot"      "generics"      
 [81] "ellipsis"       "numDeriv"       "farver"         "lifecycle"      "magrittr"      
 [86] "crosstalk"      "jquerylib"      "promises"       "zoo"            "plyr"          
 [91] "codetools"      "xfun"           "mime"           "crayon"         "fansi"         
 [96] "utf8"           "callr"          "prettyunits"    "labeling"       "munsell"       
[101] "RColorBrewer"   "viridisLite"    "httpuv"         "fontawesome"    "sourcetools"   
[106] "later"          "fastmap"        "commonmark"     "bslib"          "cachem"        
[111] "stringi"        "igraph"         "base64enc"      "pkgconfig"      "purrr"         
[116] "sass"           "processx"       "lazyeval"       "yaml"           "colorspace"    
[121] "ps"             "fs"             "rappdirs"      
```

**Comment by mattansb** [comment]
I will make a PR using `insight`, and hopefully @paul-buerkner you'll be able to convert to internal `brms` functions.

**Comment by rvlenth** [comment]
OK, now I remember that `call` usually comes from the `recover_data` method, which in turn usually uses `recover_data.call`, as it does in this case:
```
> brms:::recover_data.brmsfit
function (object, data, resp = NULL, dpar = NULL, nlpar = NULL, 
    re_formula = NA, epred = FALSE, ...) 
{
    bterms <- .extract_par_terms(object, resp = resp, dpar = dpar, 
        nlpar = nlpar, re_formula = re_formula, epred = epred)
    trms <- attr(model.frame(bterms$allvars, data = object$data), 
        "terms")
    emmeans::recover_data(call("brms"), trms, "na.omit", data = object$data, 
        ...)
}
<bytecode: 0x000001ef10709700>
<environment: namespace:brms>
```
So what it would take is to just get the model formula in there, with something like
```
> call("brms", formula = log(y) ~ x1 + x2)
brms(formula =log( y) ~ x1 + x2)
```
So maybe just replace `call("brms")` in the last line with `call("brms", formula = object$formula$responses[[1]])`?

**Comment by mattansb** [comment]
It seems more complicated than that - I've got it working (https://github.com/mattansb/brms/commit/395bb59e377b14f841f56e06200ca4de68cc01b7) for the example above:

```R
emmeans(m_in.formula2, ~ cyl, resp = "logmpg",
        regrid = "response")
#>  cyl response lower.HPD upper.HPD
#>    4     20.2      14.1      27.2
#>    6     19.5      16.6      23.4
#>    8     15.7      13.7      17.8
#> 
#> Point estimate displayed: median 
#> HPD interval probability: 0.95
```

But now this fails (somewhere in `posterior_linpred()`)...


```R
emmeans(m_in.formula2, ~ 1, resp = "logmpg", dpar = "sigma")
#> Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : 
#> contrasts can be applied only to factors with 2 or more levels
```

**Comment by rvlenth** [comment]
What about `emmeans(m_in.formula2, ~ 1, dpar = "sigma")`? Doesn't seem like you should be specifying the response when looking at the `sigma` part of the model. I likely don't understand...

**Comment by mattansb** [comment]
the model is modelling:

![image](https://user-images.githubusercontent.com/35330040/170420312-1b25318a-58b0-4c4b-93b3-6a01cfcccafb.png)

So sigma a distribution parameter for `log(mpg)` here.

Since `logmpg` is the first response here, I would expect that dropping `resp = "logmpg"` would give the same error, but is gives a different error? @paul-buerkner any idea why?

```R
emmeans(m_in.formula2, ~ 1, resp = "logmpg", dpar = "sigma")
#> Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : 
#> contrasts can be applied only to factors with 2 or more levels

emmeans(m_in.formula2, ~ 1, dpar = "sigma")
#> Error : Distributional parameter 'sigma' is not part of the model.
#> Supported parameters are: 'mu'
```

**Comment by rvlenth** [comment]
Hey, I finally clawed my way into actually installing cmdstanr and cmdStan and fitting the model. So I can look at what's in that object.

It seems to me that the only reason we need the formula at all is to detect a possible response transformation. And we only need it if we're looking at the model for location. And if there is a response transformation, it would be in the very first formula you can get. So I suggest this code in `recover_data.brmsfit`:
```
> recover_data.brmsfit

function (object, data, resp = NULL, dpar = NULL, nlpar = NULL, 
    re_formula = NA, epred = FALSE, ...) 
{
    message("Using worksheet version of recover_data")
    bterms <- .extract_par_terms(object, resp = resp, dpar = dpar, 
        nlpar = nlpar, re_formula = re_formula, epred = epred)
    trms <- attr(model.frame(bterms$allvars, data = object$data), 
        "terms")
    cl <- call("brms")    # just a blank call
    if (is.null(dpar) || dpar == "mu") {
        frm <- object$formula$form
        if (is.list(frm))
            frm<- frm[[1]]$form
        cl$formula <- frm
    }
    emmeans::recover_data(cl, trms, "na.omit", data = object$data, 
        ...)
}
<bytecode: 0x000002a3c34b9b28>
<environment: namespace:brms>
```
So we get:
```
> ref_grid(m_in.formula)
Using worksheet version of recover_data
'emmGrid' object with variables:
    cyl = 4, 6, 8
    hp = 146.69
Transformation: “log” 

> # (works the same specifying dpar = "mu")

ref_grid(m_in.formula2, resp = "logmpg")
Using worksheet version of recover_data
'emmGrid' object with variables:
    cyl = 4, 6, 8
    hp = 146.69
Transformation: “log” 
```

**Comment by paul-buerkner** [comment]
Thank you both! I have pushed an attempt to fix this issue, but I have only activated it for `epred = TRUE` as the `mu` parameter does not generally coincide with the likelihood mean so applying the response transformation on `mu` may not always be sensible. Or am I misunderstanding the purpose of storing this transformation?

**Comment by paul-buerkner** [comment]
I agree. Would you mind preparing such a small example for the doc? Doesn't have to be a PR. Just here on github should suffice and I can then copy and paste it into the doc.

**Comment by mattansb** [comment]
```R
library(brms)
library(emmeans)

mod <- brm(log(mpg) ~ factor(cyl),
           data = mtcars,
           family = gaussian(),
           backend = "cmdstanr")


emmeans(mod, ~ cyl, epred = TRUE) # is on the response scale
#>  cyl emmean lower.HPD upper.HPD
#>    4   3.27      3.17      3.37
#>    6   2.98      2.86      3.10
#>    8   2.70      2.62      2.79
#> 
#> Point estimate displayed: median 
#> HPD interval probability: 0.95


emmeans(mod, ~ cyl, dpar = "mu") # is on the log scale
#>  cyl emmean lower.HPD upper.HPD
#>    4   3.27      3.17      3.37
#>    6   2.98      2.86      3.10
#>    8   2.70      2.62      2.79
#> 
#> Point estimate displayed: median 
#> HPD interval probability: 0.95

# Get mu on the response scale
emmeans(mod, ~ cyl, dpar = "mu",
        tran = "log", 
        regrid = "response")
#>  cyl emmean lower.HPD upper.HPD
#>    4   3.27      3.17      3.37
#>    6   2.98      2.86      3.10
#>    8   2.70      2.62      2.79
#> 
#> Point estimate displayed: median 
#> Results are given on the log (not the response) scale. 
#> HPD interval probability: 0.95
```

@rvlenth, that last one should work, no?
(Same result when using `lm()` as well).

This is the long way to make it work...
```R
emmeans(mod, ~ cyl, dpar = "mu") |> 
  update(tran = "log") |> 
  regrid(transform = "response")
#>  cyl emmean lower.HPD upper.HPD
#>    4   26.3      23.7      29.2
#>    6   19.7      17.5      22.2
#>    8   14.9      13.6      16.2
#> 
#> Point estimate displayed: median 
```

**Comment by rvlenth** [comment]
I tried it, and get:
```
> emmeans(mod, ~ cyl, dpar = "mu",
+         tran = "log", 
+         type = "response")
Using worksheet version of recover_data
 cyl response lower.HPD upper.HPD
   4     26.3      23.8      29.3
   6     19.7      17.2      22.2
   8     14.9      13.6      16.2

Point estimate displayed: median 
Results are back-transformed from the log scale 
HPD interval probability: 0.95 

> emmeans(mod, ~ cyl, dpar = "mu",
+         tran = "log", 
+         regrid = "response")
Using worksheet version of recover_data
 cyl response lower.HPD upper.HPD
   4     26.3      23.8      29.3
   6     19.7      17.2      22.2
   8     14.9      13.6      16.2

Point estimate displayed: median 
Results are given on the log (not the response) scale. 
HPD interval probability: 0.95 
```
Using my modified `recover_data` setup, I do get it on the response scale in both cases. Unfortunately, there is a spurious annotation in the second one about its still being on the log scale -- aargggh. 

However, if I pre-transform the response,
```
> mod_pre <- brm(log_mpg ~ factor(cyl),
+            data = mtcars,
+            family = gaussian(),
+            backend = "cmdstanr")
 ...
> emmeans(mod_pre, ~ cyl, tran = "log", type = "response")
Using worksheet version of recover_data
 cyl response lower.HPD upper.HPD
   4     26.3      23.7      29.0
   6     19.7      17.4      22.4
   8     14.9      13.6      16.2

Point estimate displayed: median 
Results are back-transformed from the log scale 
HPD interval probability: 0.95 

> emmeans(mod_pre, ~ cyl, tran = "log", regrid = "response")
Using worksheet version of recover_data
 cyl emmean lower.HPD upper.HPD
   4   3.27      3.17      3.37
   6   2.98      2.85      3.11
   8   2.70      2.62      2.79

Point estimate displayed: median 
Results are given on the log (not the response) scale. 
HPD interval probability: 0.95 
```
The one with `regrid` doesn't work because of the order in which things are done. With `type = "response"`, we are telling it how to summarize the results, and with `regrid = "response"`, we are telling it to modify the reference grid, and that happens *before* the `tran` argument is processed because that is used to update the argument at the end. In fact, that explains why we got what we did...
```
> emmeans(mod, ~ cyl, regrid = "response")
Using worksheet version of recover_data
 cyl response lower.HPD upper.HPD
   4     26.3      23.8      29.3
   6     19.7      17.2      22.2
   8     14.9      13.6      16.2

Point estimate displayed: median 
HPD interval probability: 0.95 

> emmeans(mod, ~ cyl, regrid = "response", tran = "log", type = "response")
Using worksheet version of recover_data
 cyl response lower.HPD upper.HPD
   4 2.70e+11  1.62e+09  2.95e+12
   6 3.62e+08  3.84e+06  3.28e+09
   8 2.92e+06  5.06e+05  9.08e+06

Point estimate displayed: median 
Results are back-transformed from the log scale 
HPD interval probability: 0.95 
```
With `mod`, it already knew there was a log transformation, so it did it right. But then if we add `tran = "log"`, we are saying we want to add *another* log transformation.

**Comment by rvlenth** [comment]
Note -- I edited my previous comment to remove some "fluff"

**Comment by paul-buerkner** [comment]
Thank you both again! I have now added the following example to the doc, which as I understand it, shows the desired behavior:

```R
# model with transformed response variable
fit2 <- brm(log(mpg) ~ factor(cyl), data = mtcars)

# results will be on the log scale by default
emmeans(fit2, ~ cyl)

 cyl emmean lower.HPD upper.HPD
   4   3.27      3.17      3.37
   6   2.98      2.86      3.11
   8   2.70      2.61      2.79

Point estimate displayed: median 
HPD interval probability: 0.95

# log transform is detected and be adjusted automatically
emmeans(fit2, ~ cyl, epred = TRUE, type = "response")

 cyl response lower.HPD upper.HPD
   4     26.3      23.8      29.0
   6     19.7      17.5      22.4
   8     14.9      13.6      16.2

Point estimate displayed: median 
Results are back-transformed from the log scale 
HPD interval probability: 0.95 
```

What do you think?

**Comment by rvlenth** [comment]
Looks fine. My only comment is that `epred = TRUE` has no effect in the second example. You'll get the same results with `emmeans(fit2, ~ cyl, type = "response")`

**Comment by mattansb** [comment]
That is true in this example. Perhaps the example should be with some family where epred is not just a function of mu?

**Comment by rvlenth** [comment]
But then, if I understand correctly, the response transformation needs to be handled by **brms**, not **emmeans**; and it then should *not* pass the response transformation via `recover_data.brmsfit` because it has already been handled.

**Comment by paul-buerkner** [comment]
As I implemented it yesterday, brms will only let emmeans know of the log
transform when epred is TRUE because only then we know for sure that the
values passed to emmeans are actually the mean of the response variable.

Russell V. Lenth ***@***.***> schrieb am Sa., 28. Mai 2022,
20:28:

**Comment by rvlenth** [comment]
Aha! This seemed puzzling to me until I looked at the example you have with `? "emmeans-brms-helpers"` and realized that the mean of the log-normal distribution (obtained via `epred = TRUE`) depends on both the mean and the variance. I can't imagine fitting that particular model with a response transformation, but the point is made.

**Comment by mattansb** [comment]
Yes, it does unlikely, but perhaps for the demonstration in the examples it's worth it.

**Comment by paul-buerkner** [comment]
Alright, closing this issue now. Thank you both for your insights and help! I really appreciate it and I learned a lot from this discussion.

**Comment by mattansb** [comment]
@paul-buerkner 

Just one last thing - still need to ass `transform = FALSE`  here:

https://github.com/paul-buerkner/brms/blob/master/R/emmeans.R#L105-L109

(Which is where this issue started)

Thanks!

**Comment by paul-buerkner** [comment]
Right, thank you! Fixed now.

Am Di., 31. Mai 2022 um 08:23 Uhr schrieb Mattan S. Ben-Shachar <
***@***.***>:

**Comment by mattansb** [comment]
Thanks!
