### ISSUE TITLE
Improved log factorization of inverse gaussian density

### ISSUE THREAD

**Issue by sims1253** [paul-buerkner/brms#1363]
I found that using
```
lpdf <- 0.5 *(log(shape) - ( log(2) + log(pi) + 3 * log(x))) -
shape * (x - mu)^2/(2 * mu^2 * x)
```
for the inverse gaussian prevents a bug where `log_lik` returns NANs in certain cases and leads to fewer divergent transitions.
Not sure how to vectorize that for the stan code so I'll leave this here before it is forgotten.

**Comment by paul-buerkner** [comment]
Thanks. Changed now. Not sure why it is that way, but since we clearly see it in our simulations I think it makes sense to adjust it.
