### ISSUE TITLE
Warning: Requires (indirectly) orphaned package: `gtools`

### ISSUE THREAD

**Issue by hsbadr** [paul-buerkner/brms#1365]
See https://cran.r-project.org/web/checks/check_results_brms.html.

Related to https://github.com/richarddmorey/BayesFactor/issues/161 & https://github.com/richarddmorey/BayesFactor/pull/162.

**Comment by paul-buerkner** [comment]
Thanks! Do you know through which package(s) this dependency comes in?

**Comment by hsbadr** [comment]
`brms` directly imports `bridgesampling`, which suggests `BayesFactor` that imports `gtools`.

**Comment by paul-buerkner** [comment]
I see, thank you!

**Comment by hsbadr** [comment]
So, if that's the only path, it will get automatically fixed if `BayesFactor` dropped the dependency on `gtools`.

**Comment by paul-buerkner** [comment]
There may be others still, e.g., https://github.com/stan-dev/shinystan/issues/196

**Comment by hsbadr** [comment]
Addressed by the latest CRAN releases of the dependencies.
