### ISSUE TITLE
Seemingly unrelated / Multivariate Probit Regression

### ISSUE THREAD

**Issue by noamross** [paul-buerkner/brms#1366]
I realize that various forms of this have been requested going back to at least https://github.com/paul-buerkner/brms/issues/338  and https://github.com/paul-buerkner/brms/issues/323 ,  but I was wondering if brms could implement the Seemingly Unrelated / Multivariate Probit Regression as described in the Stan Manual here: https://mc-stan.org/docs/2_29/stan-users-guide/multivariate-outcomes.html#multivariate-probit-regression . None of those issues reference that implementation. I find I'm using it more and it would be helpful to have brms's machinery for more complex formulas.

**Comment by andrjohns** [comment]
While not directly related, multivariate probit models will be supported once the Gaussian copula framework from #1317 is finished. It's something that I'll be working on intermittently for the next few weeks (between other Stan projects), so it might not be timely enough if you need it soon.

Is this something you could implement using the `custom_family` framework?

**Comment by noamross** [comment]
Thank you.  I'm not in a rush so look forward to that work, but I will look and see if `custom_family` can accommodate that approach.

**Comment by jeremy-koster** [comment]
> for the next few weeks

Optimistically, @andrjohns, how is that progressing?

**Comment by paul-buerkner** [comment]
I will close this issue for now to clean up the issue tracker a bit since I don't this this has high priority.
