### ISSUE TITLE
Feature request: `prior()` doesn't understand `dpar = "mu"`

### ISSUE THREAD

**Issue by jsocolar** [paul-buerkner/brms#1368]
It would be nice if, in distributional regression, we could pass priors explicitly to the `"mu"` parameter via `dpar = "mu"`.  This is just to help with the legibility of the prior specification when one coefficient shows up on multiple dpars with different priors.

**Comment by paul-buerkner** [comment]
I will internally translate `dpar = "mu"` input to `dpar = ""`, which should fix the interface part. Really storing `dpar = "mu"` in the prior objects would require bigger changes with potential issues for backwards compatibility that I want to avoid for now.

**Comment by paul-buerkner** [comment]
Fixed.
