### ISSUE TITLE
Feature request: zero and one inflated proportional models

### ISSUE THREAD

**Issue by ericward-noaa** [paul-buerkner/brms#1371]
Thanks for all the work on `brms` Paul -- it's an outstanding package.

I know `brms` can handle zero-inflated proportions. Some collaborators and I recently developed a model for responses that includes proportional data, as well as 0s and 1s. The package is built using Stan: [zoid](https://nwfsc-cb.github.io/zoid/index.html) and [source](https://github.com/nwfsc-cb/zoid/)

At a recent conference, a few colleagues wondered about porting it over to `brms` to take advantage of smooths, random effects, etc. If there's enough interest, happy to brainstorm on this more, or work on a PR etc. Thanks!

**Comment by ericward-noaa** [comment]
Apologies, I wasn't clear -- our model is a zero and one inflated Dirichlet. I had looked at the zero_one_inflated_beta in brms, and it looks great for univariate cases.

**Comment by paul-buerkner** [comment]
I see. Yes, adding such a family could be interesting indeed. How shall we proceed with the discussion?

**Comment by paul-buerkner** [comment]
I will close this issue for now to clean up the issue tracker a bit.
