### ISSUE TITLE
Warning: Declaration of arrays by placing brackets after a type is deprecated

### ISSUE THREAD

**Issue by hsbadr** [paul-buerkner/brms#1376]
The current version of `stanc3` generates the following warning:
```
Warning: Declaration of arrays by placing brackets after a type is deprecated
    and will be removed in Stan 2.32.0.
    Instead use the array keyword before the type.
    This can be changed automatically using the auto-format flag to stanc.
```

For example, `int[] y` becomes `array[] int y`.

**Comment by paul-buerkner** [comment]
I have to keep the old format as long as rstan isn't updated on CRAN. Any suggestions as to what to do with it in the meantime?

**Comment by hsbadr** [comment]
I think we've time until Stan v2.32 is released and even more time until we see RStan v2.32 on CRAN. Also, the experimental version of RStan can automatically format the code using `stanc.auto_format` option which makes `rstan::stanc()` format the Stan code before converting it to C++.

I personally add the following to my `~/.Rprofile` (experimental RStan only):
```r
options(
  stanc.allow_optimizations = TRUE,
  stanc.auto_format = TRUE
)
```
> Any suggestions as to what to do with it in the meantime?

If we'd like to address it now, we could conditionally let `brms` generate formatted Stan code based on the version of RStan. I guess that once RStan v2.26 is on CRAN, v2.30 will be under testing and getting more popular.

**Comment by jsocolar** [comment]
Just want to flag that 2.32 release date is tentatively planned for 17 April, so this is becoming somewhat more urgent.

**Comment by paul-buerkner** [comment]
Do I understand it correctly that the old array syntax will no longer work with Stan 2.32+? 

I would really love to avoid having backend dependent code generation, but not sure if there is another way right now...

Does anyone has another idea?

@bgoodri, when can we expect a new version of rstan to get on CRAN? I know this is a difficult task, but we are so far behind in version that maintaining both backends starts to be an issue for brms too.

**Comment by wds15** [comment]
@paul-buerkner is it an option to use the auto formatter from the parser? So whenever the target is cmdstan version >=2.32, then you use the auto-formatter option.

What I have not yet understood is if 2.33 will also support the auto formatter option. That's hopefully the case.

If 2.33 does not support auto format then only ugly solutions come to my mind...like have a formatter option which takes the new array syntax and converts it to the old syntax which would allow brms to be written in the new style and format automatically on the fly to the old format if the target Stan is oldish. Yack.

Getting `rstan` up to date is a huge challenge, but most/maybe all (?) issues are solved as far as I know. Given that R 4.3 is likely in sight to land in April we have possibly now a good window to push out an `rstan` update as I understood @bgoodri?

**Comment by rok-cesnovar** [comment]
brms is already using this before passing the model code to cmdstanr for compilation. This was added to avoid the deprecation warnings spam: https://github.com/search?q=repo%3Apaul-buerkner%2Fbrms%20canonicalize&type=code

**Comment by WardBrian** [comment]
> But I think that will be the last release cycle where that will be the case

Correct. An idea which didn’t occur to me until recently is we could make a small binary which only does the deprecation updates that we could ship in the bin folder of the next few cmdstans. 
Since it would only be designed to be used with pre-2.32 code it wouldn’t need to be updated with new features or anything, so it doesn’t slow down the rest of development, and we could stop shipping it if/when RStan is up past 2.26 or so.

**Comment by paul-buerkner** [comment]
Now implemented.
