### ISSUE TITLE
Questions about estimating a multilevel survival model

### ISSUE THREAD

**Issue by audreyyuwenfei** [paul-buerkner/brms#1377]
Hello all, 

I tried to use brms package in R to estimate a multilevel survival model (shared frailty model). I got the estimated random effect for each cluster, but some of them are negative. I'm not sure whether I can take the exponential to get the shared frailty. I also do not know how to set the distribution for frailties. Can anyone help?

Thank you.

**Comment by wds15** [comment]
This is a question for the Stan discourse forum. Please post there.
