### ISSUE TITLE
Typo in density of `brms::gen_extreme_value()`?

### ISSUE THREAD

**Issue by fweber144** [paul-buerkner/brms#1384]
The density of the generalized extreme value distribution (i.e., the `brms::gen_extreme_value()` family) in the [`brms_families`](https://cran.r-project.org/web/packages/brms/vignettes/brms_families.html) vignette (brms v2.17.0) might have a typo in the exponent of $t(y)$: It reads $-1 -  1/\xi$, but [Wikipedia](https://en.wikipedia.org/wiki/Generalized_extreme_value_distribution) says it should read $1 + \xi$, where $\xi$ seems to be the same $\xi$ as in brms. Of course, this could also be a mistake on Wikipedia; I am not familiar with the generalized extreme value distribution.

There is also #1345, but it doesn't seem to be related.

**Comment by fweber144** [comment]
I haven't checked whether this also affects how the `brms::gen_extreme_value()` family is implemented in brms. If the density is indeed incorrect, the implementation could also be affected.

**Comment by paul-buerkner** [comment]
I fixed the typo. The code itself is fortunately correct.
