### ISSUE TITLE
misleading doc for `transform` in `posterior_linpred`

### ISSUE THREAD

**Issue by jsocolar** [paul-buerkner/brms#1388]
Current doc says 
```
Logical; if FALSE (the default), draws of the linear predictor are returned. If TRUE, draws of transformed linear predictor, that is, after applying the link function are returned.
```

It should instead say "after applying the _inverse_ link function".  As written, one might plausibly think that by default the linear predictor is being returned on the response scale rather than the link scale, and one must set `transform = TRUE` to get the link-scale linear predictor.

**Comment by paul-buerkner** [comment]
I agree. Thank you

**Comment by paul-buerkner** [comment]
fixed now.
