### ISSUE TITLE
subscript out of bounds when calling summary for models with random effects

### ISSUE THREAD

**Issue by rubenarslan** [paul-buerkner/brms#139]
I get the following error when trying to use summary on models fitted using a previous version of brms (the one where you introduced splines). I'm using the most up-to-date version.
The error occurs only for models with random effects as far as I can tell. Most other accessor functions still work. I can send a fit causing the problem via mail if you want.

> Error in fit_summary[c(sd_pars, cor_pars), , drop = FALSE] : 
  subscript out of bounds
In addition: Warning messages:
1: In x$dim : partial match of 'dim' to 'dims'
2: In x$dim : partial match of 'dim' to 'dims'
3: In x$dim : partial match of 'dim' to 'dims'
4: In x$dim : partial match of 'dim' to 'dims'

**Comment by paul-buerkner** [comment]
I know this problem and it has likely one of two reasson.

(a) It may have something to do with rstan's saving of summary outputs. Ones you summarized a model, its summary output it sort of fixed (i.e. saved in a hidden environment; @jgabry can tell you more I guess). When we then summarize it with a new brms version (where the names of some spline parameters are changed), the saved summary output does not match the expected new parameter names anymore. At least I sometimes get this error in this situtation. You could try saving just the model object and summarize it in an empty R session. 

(b) If this doesn't not resolve the problem, it is very likely a bug in brms related to the conversion of parameter names and I would be grateful for seeing the fittede model.

**Comment by rubenarslan** [comment]
I got the error in a fresh session, will send you an email.

**Comment by paul-buerkner** [comment]
It turned out to be indeed a problem of sort (a) although I don't understand all the details. Essentially, the summary output seems to be stored inside the `stanfit` object by **rstan** when first calling summary. 

To avoid the problem of an outdated stored summary, I added a new argument to `summary.brmsfit` called `use_cache`, which you should set to `FALSE`. This way **rstan** will compute the summary output each time it is called and ignore the stored output.

**Comment by jgabry** [comment]
Yeah, this behavior in rstan is just because it doesn't make sense to
recompute everything returned by summary every time summary is called. So,
if left at the default use_cache=TRUE, it will compute and cache everything
the first time it is called and then look for the cached results when
called again. use_cache=FALSE is the right way to disable this.

**Comment by paul-buerkner** [comment]
Thanks Jonah. I wonder if there is a way to override the cached summary with a new one? I know this is a very specific problem and only affects people playing around with Stan internals (like me), but it would be good to avoid the here described error without having to compute the summary output each and every time again.

**Comment by rubenarslan** [comment]
Thanks to you both for the quick fix! 
I couldn't figure out which part of the model internals to delete to get rid of the cached version. Something in attributes(model$fit)$.MISC ?

Quick question though: Is summary called internally often?
If yes, then I would still run into problems when brms or rstan calls summary internally without `use_cache = FALSE`.
If not, then I don't see the point of a cache. Who calls summary twice on a model? Moreover, isn't it a bit unintended if calling a summary method changes the object without any obvious assignment? This might also break things like knitr's caching, which tries to detect assignment.

**Comment by jgabry** [comment]
So would you only need to rename parameters in the summary, as opposed to
recomputing the actual values?

**Comment by paul-buerkner** [comment]
`summary.stanfit` is only called in `summary.brmsfit` so other methods are completely unaffacted. The object is not really changed. It is just the cached summary which is shown without recomputation.

**Comment by paul-buerkner** [comment]
I would only need to rename the parameters in the cached summary.

**Comment by jgabry** [comment]
On Monday, October 31, 2016, Paul-Christian Bürkner <
notifications@github.com> wrote:

> I would only need to rename the parameters in the cached summary.
>
In that case I think you can just edit it in the Misc environment. I
haven't tried that myself but I think it should work.

>

**Comment by rubenarslan** [comment]
@jgabry Hm, well you should know best. In my (often large) models, summary doesn't take that long and I'm accustomed to assigning sth to a variable, if I want to re-use. 
My point was more that I don't know such a behaviour from other packages, so it got me and might confuse others who might not expect it/intend to change an object. I rarely read the documentation for functions like summary. But it's hard to come up with a problem that would result from this except this one (I summarised objects on the cluster before saving them, could have easily switched order, so not a big deal).

After I've thought about it further, the point about knitr cacheing is probably a non-issue, after all the worst-case scenario is that the summary-computations happen again and again, but it wouldn't break anything unless you change package versions mid-knitting.

**Comment by jgabry** [comment]
I totally agree that it's a bit strange, although it's not without
precedent. There are packages that compute and cache things internally,
it's just usually not advertised to users.

What we definitely wouldn't want to do is compute and store anything in the
global environment without an explicit assignment by the user. But storing
the summary info inside an internal environment in the stanfit object (with
option to turn it off) should really only be a benefit to users. That said,
when we implemented it (which precedes my involvement) we certainly weren't
worrying about the affect on packages like brms, which is a much more recent
development.

**Comment by paul-buerkner** [comment]
I do now also rename the parameters in the cached summary so that the error should no longer occur even if `use_cache` is TRUE.

**Comment by rubenarslan** [comment]
Yes, works for me now. Great! :-)
