### ISSUE TITLE
Small bug in divergent transitions warning message

### ISSUE THREAD

**Issue by andieich** [paul-buerkner/brms#1390]
Hi,

I just noticed a small bug in the warning message that is displayed if there are divergent transitions. I get `Warning: There were 40 divergent transitions after warmup. Increasing adapt_delta above  may help. See http://mc-stan.org/misc/warnings.html#divergent-transitions-after-warmup`. The value for `adapt_delta` (I think it was 0.8) is missing.

**Comment by paul-buerkner** [comment]
Fixed.

**Comment by andieich** [comment]
Thanks a lot!
