### ISSUE TITLE
Error in generating stancode for multivariate model with se() and multiple threads

### ISSUE THREAD

**Issue by yanivabir** [paul-buerkner/brms#1395]
I'm trying to fit a model with the following forumla: `bf(a_m | se(a_sd, sigma = TRUE) ~ 1 + me(test_perf, test_perf_sd)) + 
			bf(v_ent_m | se(v_ent_sd, sigma = TRUE) ~ 1 + me(test_perf, test_perf_sd)) + set_rescor(T)`

When running on a single thread, there is no problem. But when using multiple threads, there is a typo in the stancode generated. In the reduce_sum function, I see the following code:

```
// combine univariate parameters
for (n in 1:N) {
      Mu[n] = transpose([mu_am[n], mu_ventm[n]]);
      sigma[n] = transpose([sqrt(square(sigma_am) + se2_am[nn]), sqrt(square(sigma_ventm) + se2_ventm[nn])]);
      LSigma[n] = diag_pre_multiply(sigma[n], Lrescor);
    }
```
(note the nn index)

which generates the following error:

```
Semantic error in '/tmp/RtmpKXbq5l/model-d9084eba3524.stan', line 45, column 59 to column 61:
   -------------------------------------------------
    43:      for (n in 1:N) {
    44:        Mu[n] = transpose([mu_am[n], mu_ventm[n]]);
    45:        sigma[n] = transpose([sqrt(square(sigma_am) + se2_am[nn]), sqrt(square(sigma_ventm) + se2_ventm[nn])]);
                                                                    ^
    46:        LSigma[n] = diag_pre_multiply(sigma[n], Lrescor);
    47:      }
   -------------------------------------------------

Identifier 'nn' not in scope. Did you mean 'n'?
```

Running on a single thread, there is no problem. The correct indexing appears in the model block:
```
// combine univariate parameters
    for (n in 1:N) {
      Mu[n] = transpose([mu_am[n], mu_ventm[n]]);
      sigma[n] = transpose([sqrt(square(sigma_am) + se2_am[n]), sqrt(square(sigma_ventm) + se2_ventm[n])]);
      LSigma[n] = diag_pre_multiply(sigma[n], Lrescor);
    }
```
and the model runs without a problem.

-----
using brms version 2.16.1

**Comment by paul-buerkner** [comment]
After checking the code, it looks like the bug is already fixed in the latest brms version. I will close this issue now, but feel free to reopen it, if it turns out I am wrong.
