### ISSUE TITLE
Using normal_id_glm_lpdf for missing data models / additional responses

### ISSUE THREAD

**Issue by gbiele** [paul-buerkner/brms#1398]
brms s uses Stan's ...glm functions for the main response. Thanks for implementing this!

A look at brms generated code suggests that the same could also be done for additional responses, e.g. when modeling missing data.

Here is an example of current brms-generated Stan code for additional responses:

1a. _Model mu based on observed variables:_
`mu_RESP2 += Intercept_RESP2 + Xc_RESP2 * b_RESP2;` 
2a.  _Add additional terms_
```
for (n in 1 : N_ADHDNPR) {
      mu_RESP2[n] += bsp_RESP2[1] * Yl_RESP3[n] + bsp_RESP2[2] * Yl_RESP4[n];
    }
```
3a. _Update target with normal_lpdf_
`target += normal_lpdf(Yl_RESP2 | mu_RESP2, sigma_RESP2);`

<br>

__The proposal:__ Move `Xc_RESP2 * b_RESP2` out of step 1. and into step 3. as follows: 

1b. _Set mu to the intercept_
`mu_RESP2 = Intercept_RESP2;` 
2b.  _Add additional terms to mu as in 2a._
3b. _Update target with normal_id_glm_lpdf_
`target += normal_id_glm_lpdf(Yl_RESP2 | Xc_RESP2 , mu_RESP2, b_RESP2, sigma_RESP2);`

**Comment by paul-buerkner** [comment]
Good point. Thank you for the suggestion.

**Comment by paul-buerkner** [comment]
Implemented.

**Comment by gbiele** [comment]
I cannot express how impressed I am!
