### ISSUE TITLE
Question regarding nested models

### ISSUE THREAD

**Issue by alireza202** [paul-buerkner/brms#14]
Let's say my data is such that I have 10 cats and within each cat, a variable number of subcats, and in each subcat, a variable number of observations. I've been writing my model like this so far:
```
brm(formula = y ~ x1 + x2 + x3 +
                 (1 | cat:subcat) + (1 | cat),
    data = df,
    family = "gaussian")
```
What if I write it like this?
```
brm(formula = y ~ x1 + x2 + x3 +
                 (1 | subcat) + (1 | cat),
    data = df,
    family = "gaussian")
```
Is this still nested? Do I need to specify cat:subcat at all?

**Comment by paul-buerkner** [comment]
If each subcat is only in one cat, then `(1| cat:subcat)` will lead to the same random effects as `(1|subcat)` anyway. If however, subcats are nested in multiple cats, then `(1| cat:subcat)` would be the way to go for a nested model.

**Comment by alireza202** [comment]
Thanks for clarification!
