### ISSUE TITLE
"Parameter b could not be renamed.  This should not happen."

### ISSUE THREAD

**Issue by wshatpud** [paul-buerkner/brms#140]
Running this model

```
brmfit01a <-  brm(formula = a ~ 1 + (t | l), data = adata, prior = c(set_prior('normal(0,1)', class = 'b'), set_prior('cauchy(0,2)', class = 'sd')))
```

gets two warning messages:

```
Warning messages:
1: There were 2 divergent transitions after warmup. Increasing adapt_delta above 0.8 may help. See
http://mc-stan.org/misc/warnings.html#divergent-transitions-after-warmup 
2: Examine the pairs() plot to diagnose sampling problems
 
3: Parameter b could not be renamed. This should not happen. 
Please inform me so that I can fix this problem. 
```
a is a double that ranges from just above 0 to about 5.  t is a double taking on the values 0 and 1.  l is a double taking on integer values from 1 to 6.  There are about 1500 rows in adata.

**Comment by paul-buerkner** [comment]
Hey, you don't have to worry about the second warning, it is a false positive. This warning has been fixed in the dev version of brms on github.

**Comment by wshatpud** [comment]
Oops: I meant "three warnings" :-).  I was writing about warning 3: "Parameter b could not be renamed."  I'll check out the github version soon.

**Comment by paul-buerkner** [comment]
And I also ment the third warning (the one in the title of the issue). ;-)
