### ISSUE TITLE
Using the Posterior as the next Prior

### ISSUE THREAD

**Issue by aaelony** [paul-buerkner/brms#1405]
Hello this is a feature request for either explaining how to _use the posterior as the next prior_ within brms, or adding such functionality.  The use case is that you have previously fit a model and now there is new data.  Perhaps I am wrong, but it is not clear to me that [brms::update](https://rdrr.io/cran/brms/man/update.brmsfit.html) does this.  I have also not seen this mentioned in workflow related topics.

Thank-you

references:
https://discourse.mc-stan.org/t/using-posteriors-as-new-priors/12745/3
https://discourse.mc-stan.org/t/composing-stan-models-posterior-as-next-prior/8093

**Comment by paul-buerkner** [comment]
There is currently no good principled way this could be done in Stan or any other PPL that uses gradient-based samplers unfortunately. Hence, it can, as of know, not be done with brms and I don't see a way to make it possible at the moment. I am sorry that I don't have better news.

**Comment by aaelony** [comment]
Thanks for your candid answer. At least I am happy I did not misread the documentation of the `update` function ;). 

On the other hand, would some kind of tighter integration with [fitdistrplus](https://rpubs.com/blakeobeans/fitdistrplus) or something similar be possible?  e.g. [vignette](https://cran.r-project.org/web/packages/fitdistrplus/vignettes/paper2JSS.pdf) 

Thank-you
