### ISSUE TITLE
brms issue

### ISSUE THREAD

**Issue by jenniferroters** [paul-buerkner/brms#1406]
Hi all,

I am new to posting in the github community so I am sorry if this the wrong place. I have recently downloaded the newest version of R (4.2.1.) and Rstudio (2022.07.1 Build 554). I was testing out an older previous document that knitted perfectly using the 'papaja' package and now a code chunk will not work (that worked previously) and provides this error message:

Error in compileCode(f, code, language = language, verbose = verbose) : 
  C:\rtools42\x86_64-w64-mingw32.static.posix\bin/ld.exe: file425c5d805023.o:file425c5d805023.cpp:(.text$_ZN3tbb8internal26task_scheduler_observer_v3D0Ev[_ZN3tbb8internal26task_scheduler_observer_v3D0Ev]+0x1d): undefined reference to `tbb::internal::task_scheduler_observer_v3::observe(bool)'C:\rtools42\x86_64-w64-mingw32.static.posix\bin/ld.exe: file425c5d805023.o:file425c5d805023.cpp:(.text$_ZN3tbb10interface623task_scheduler_observerD1Ev[_ZN3tbb10interface623task_scheduler_observerD1Ev]+0x1d): undefined reference to `tbb::internal::task_scheduler_observer_v3::observe(bool)'C:\rtools42\x86_64-w64-mingw32.static.posix\bin/ld.exe: file425c5d805023.o:file425c5d805023.cpp:(.text$_ZN3tbb10interface623task_scheduler_observerD1Ev[_ZN3tbb10interface623task_scheduler_observerD1Ev]+0x3a): undefined reference to `tbb::internal::task_scheduler_observer_v3::observe(bool)'C:\rtools42\x86_64-w64-mingw32.static.posix\bin/ld.exe: file425c5d805023.o:file425c5d805023.cpp:(.text$_ZN3tbb10interface
Error in sink(type = "output") : invalid connection

I have the rtools42 and this worked with my previous version of R and Rstudio so I am not sure how to fix this. Help!

#### Please note:
The brms issue tracker is reserved for bug reports and feature requests. brms-related questions should rather be asked on https://discourse.mc-stan.org/ in order to reach a wider community.

**Comment by paul-buerkner** [comment]
Hey, this is a known problem of Stan with R 4.2. Please use an earlier R version of check out the related threads on https://discourse.mc-stan.org/

**Comment by lenkahas** [comment]
had the same problem I depreciated R t 4.3.1, and reinstalled the appropriate version of Rtools and magrittr and that seemed to do the job.
