### ISSUE TITLE
Error: Error: Family 'binomial' requires numeric responses.

### ISSUE THREAD

**Issue by IagoFerreiroArias** [paul-buerkner/brms#1407]
Dear Paul,

I am new into brms package and Bayesian modelling. I am trying just to run some trials with the package so I was wondering why the following Error message appears when I try to model a binomial response in function of just two categorical fixed effects (Eg. Behaviour  ~ Sex * Day_Period): 

_Error: Family 'binomial' requires numeric responses._

When I 've run the same model in lme4, I didn't get any error message like this one. Is something related just to BRMS package or just another thing that I am taking into account?

All the best,
Iago.

**Comment by paul-buerkner** [comment]
Please ask brms related questions on https://discourse.mc-stan.org
