### ISSUE TITLE
Warnings and errors as part of brmsfit object

### ISSUE THREAD

**Issue by wshatpud** [paul-buerkner/brms#141]
When doing a methods multiverse analysis, one might run a number of models, one right after the other, in a script.  In case there's a warning, it would be nice to have slots for errors and warnings in the brmsfit object to save rerunning models to figure out which complained (and, for example, wanted its adapt_delta increased).  In case there's a warning or an error, it might be nice to know it if one comes back to that model later to graph results.

If that already exists, where do I find it?

**Comment by paul-buerkner** [comment]
These informations are all stored in the `stanfit` object accessibale via `<brmsfit object>$fit`. You can call `stanplot` on the brmsfit object, with `type = 'diag'` to see some diagnostic plots (see `help(stan_diag)` for more details). You may also want to call shinystan via `launch_shiny(<brmsfit object>)` to investigate various diagnostic plots.

**Comment by paul-buerkner** [comment]
Did you find what you were looking for?

**Comment by wshatpud** [comment]
Paul, sorry for not responding earlier, and thanks for the reminder.  Your answer helped (I'm still learning what plots are offered by brms, rstan, bayesplot, and shinystan), but I was looking for something slightly different (and perhaps not as useful as I think).  

In this case, I was fitting four different models to a data set.  I'd get Stan warnings in some cases that I needed to consider increasing adapt_delta.  I might leave work at the end of a day with one of the four still getting such warnings, and I'd like to start working on it the next morning.  I figured there might be an extractor function something like stan_warnings(model) that would repeat any warnings given as part of the sampling process (and that might better be part of rstan than brms, I realize), but I couldn't find it, nor could I find an appropriate component in the brmsfit object.  In this case, my models sample in about 3 minutes each, so getting the warning messages about adapt_delta takes about 10-15 minutes.  With that warning information, I could start working with the diagnostic plots, focusing on the ones that reported warnings.

In writing this, I realize it may be as much my lack of understanding as the lack of a function.  is it safe to say that stanplot(brmfitobject, type = 'diag') gives me the same information as those warnings and I just need to get better at reading the graphs?

**Comment by paul-buerkner** [comment]
@jgabry has written the code for all the plots of **rstan** (including `stan_diag`) so he probably knows more about this then I do. In any case the information about the divergent transitions are stored somewhere in the `stanfit` object (`brmsfit$fit`), but I am not sure whether **rstan** comes with a convenience function to extract those. If not, this would possibly a valuable addition.

**Comment by paul-buerkner** [comment]
In the dev version of **brms** (to be installed via `devtools::install_github("paul-buerkner/brms")`) you can now extract details of diagnostic quantities using various methods. For instance, the number of divergent transitions can be extracted via

```R
np <- nuts_params(<brmsfit object>)
sum(subset(np, Parameter == "divergent__")$Value)
```

For more possibilities see `help("diagnostic-quantities")`.

**Comment by wshatpud** [comment]
Thanks; that was quick, and it looks like I got some plotting upgrades, too!

**Comment by paul-buerkner** [comment]
Yep, `stanplot` now uses the amazing **bayesplot** package at the back-end.
