### ISSUE TITLE
[feature request] more flexible kfold_predict() applicable to external datasets

### ISSUE THREAD

**Issue by fusaroli** [paul-buerkner/brms#1414]
As I teach on predictive approaches, I compare training, cross-validated and test performance of brms models.
It would be pedagogically useful to be able to compare cross-validated performance to those same models predicting an external dataset (to make the case that cross-validated performance can still overfit to the properties of the specific dataset).

However, kfold_predict() cannot be (easily?) run on a novel dataset:

Sequence:

- fit the model: m ← brm(…)
- kfold the model: kf_m ← kfold(m, K = 5, folds = “stratified”, group = “ID”)
- make predictions on the same dataset: kfp ← kfold_predict(kf_m)
- try to predict on a new dataset: kfp_test ← kfold_predict(kf_m, newdata = TestData)

In the last step the code fails: “Error in standata.brmsfit(.x1, resp = .x2, newdata = .x3, newdata = .x4, : formal argument “newdata” matched by multiple actual arguments”.

I can easily build a loop refitting the model on the k sets of training folds, and then applying it to the external dataset, but it'd be nice to have this as part of the standard functions (tho' I realize it might be a nice use case).

I also posted this on the stan forum:
https://discourse.mc-stan.org/t/kfold-predictions-on-an-external-test-set/28989?u=fusaroli

**Comment by paul-buerkner** [comment]
Thanks! I will look into this.

**Comment by paul-buerkner** [comment]
After thinking about this issue a bit more, I decided not to implement it natively. I see the value, but it would fundamentally change the core idea of kfold_predict (predict exactly the left of observation by the corresponding sub-model).
