### ISSUE TITLE
qgen_extreme_value() is missing

### ISSUE THREAD

**Issue by markpayneatwork** [paul-buerkner/brms#1416]
Hi,

I can see that the `qgen_extreme_value()` is missing from brms. The `dgen_extreme_value()`, `rgen_extreme_value()` and `pgen_extreme_value()` variants are available, but qgen is missing. Have I overlooked it, or is it possible to get it added please, so that this is consistent with the other distributions?

Thanks,

Mark

**Comment by paul-buerkner** [comment]
Yes, this should be possible. For example, Wikipedia (https://en.wikipedia.org/wiki/Generalized_extreme_value_distribution) provides some equations for this.

**Comment by paul-buerkner** [comment]
should now be implemented
