### ISSUE TITLE
Zero inflated binomial -- trials -- Presence absence data

### ISSUE THREAD

**Issue by charleygros** [paul-buerkner/brms#1419]
Hi there,

Looking for some advice.

I have a dataset of presence-absence data: species survey, one visit only, is the species detected? yes / no.

Willing to use a `zero_inflated_binomial` distribution.

So something like:
```
m <- brm(presence ~ depth + slope_log + ice_sd + ssh_mean, data = dat, family = zero_inflated_binomial())
```

I get an error saying I need to use `trials`.
Given that we did only one visit to each site to assess the presence of the species... is it correct to use the following?
```
m <- brm(presence | trials(1) ~ depth + slope_log + ice_sd + ssh_mean, data = dat, family = zero_inflated_binomial())
```

**Comment by paul-buerkner** [comment]
Hi, please ask brms related questions on https://discourse.mc-stan.org/
