### ISSUE TITLE
Allow plotting of single smooth terms

### ISSUE THREAD

**Issue by jgellar** [paul-buerkner/brms#142]
I was excited to find out that you have implemented GAMs using mgcv-style terms. However, I have not completely figured out how to use this functionality, and to extract the estimated smooth functions. Do you have an example of how to fit and post-process the brm model results? I have searched online but haven't been able to find anything.

**Comment by paul-buerkner** [comment]
You can basically use smooth terms in the same way as in **mgcv** with the exception that currently only `s` and `t2` splines are implemented (as in **gamm4**). To vizualize the fitted smooth terms, I recommend using the `marginal_effects` method. You can even fit smooth terms on auxiliary parameters  (see `vignette("brms_distreg")` after installing the dev version via `devtools::install_github("paul-buerkner/brms")`).
What kind of post-processing do you have in mind exactly?

**Comment by jgellar** [comment]
Thank you for pointing me towards `marginal_effects`, and the associated `plot` method... that is very helpful.

I would, though, like a little more detail about what `brm()` is doing when it comes across an `s()` term. How is the basis set up? It doesn't look like it is exactly the same basis as what is set up in mgcv. For example, when I fit the following model:
```
fit <- brm(y ~ s(x, bs = "ps", k = 20), data = dat)
```
it results in a fit with 18 coefficients corresponding to the smooth term, whereas in mgcv there would be 19 (k - 1 for the identifiability of the intercept). There Stan fit also has a parameter `b_sx_1`: I imagine this parameter accounts for the difference between the `mgcv` and `brm` models, but what exactly is it? I ask because I have a case where I want to evaluate the estimated smooth term (and standard error) at specific values along the x-axis... to do this I would need something equivalent to `mgcv::PredictMat()`.

Finally, to satisfy my own curiosity: assuming the above code is doing a p-spline fit, how do you solve the problem of the non-invertibility of the penalty (precision) matrix? There are a few ways I have seen to handle this, I was just curious what you chose.

**Comment by paul-buerkner** [comment]
In **brms**, all spline related stuff is handled by **mgcv** on the backend so the functionality is the same. The difference you are observing is that **brms** uses the parameterization of `mgcv::gamm` not of `mgcv::gam`, that is the "random effects" parameterization. 

You can use the `predict` method to obtain estimates (and standard errors) of the response evaluated at certain value of the smooth covariate `x`. During this process `mgcv::PredictMat()` is called by **brms** but there is currently no convenient way to acess the uncertainty in the smooth term itself. Can you provide an example code of how you obtain your desired estimates in `mgcv``? Possibly I could add a function mimicing this.

**Comment by jgellar** [comment]
Just to clarify the use of `marginal_effects` for the purpose of extracting the smooth function:

The idea is that I would call `marginal_effects()` with the `effects` parameter set to the thing that I'm smoothing over, and the `conditions` parameter defined to set all other covariates in the model to zero. Is this correct?

**Comment by paul-buerkner** [comment]
This is correct. By default, `marginal_effects` uses the mean to marginalize over other continuous variables, but you can use other values too (e.g., zero) through the `conditions` argument.

**Comment by jgabry** [comment]
On Tuesday, November 8, 2016, Paul-Christian Bürkner <
notifications@github.com> wrote:

> This is correct. By default, marginal_effects uses the mean to
> marginalize over other continuous variables,
>
Are you actually marginalizing over those variables though? Or just
conditioning on particular possible realizations? I assume the latter,
right?

>

**Comment by paul-buerkner** [comment]
Jonah, you are right it is the latter one. Sometimes I am sloppy with my wording apparently.

**Comment by jgellar** [comment]
I believe by setting `conditions`, I am just conditioning on the possible realizations (in particular conditioning on them being zero, to leave only the smooth term that I'm interested in).

**Comment by jgellar** [comment]
> In brms, all spline related stuff is handled by mgcv on the backend so the functionality is the same. The difference you are observing is that brms uses the parameterization of mgcv::gamm not of mgcv::gam, that is the "random effects" parameterization.

> You can use the predict method to obtain estimates (and standard errors) of the response evaluated at certain value of the smooth covariate x. During this process mgcv::PredictMat() is called by brms but there is currently no convenient way to acess the uncertainty in the smooth term itself. Can you provide an example code of how you obtain your desired estimates in mgcv`? Possibly I could add a function mimicing this.

Thanks for clarifying the parameterization. I'm not as familiar with `gamm` as I am with `gam`, so I'll have to look into how this works. Regarding the predict method: if `brms` is calling `mgcv::PredictMat()`, it means that you have to be storing the smooth object (created by `mgcv::smoothCon()` somewhere in the object that is returned by `brm()`, right? Could you point me towards where that is? That should be all I need.

**Comment by paul-buerkner** [comment]
It is not stored, it is regenerated if necessary.

**Comment by jgellar** [comment]
Thanks again for pointing me towards those functions.

One more question: when using marginal_effects, you are including the overall intercept. When you plot a term from mgcv::gam() or mgcv::gam(), the intercept (by default) is not included. Is there a way to use marginal_effects but not include the intercept?

It's easy enough to subtract the estimate of the intercept from the resulting function, but including the intercept also effects the standard errors.

**Comment by paul-buerkner** [comment]
Currently, there is no convenient way of removing the intercept in `marginal_effects` or related functions. Also, I believe that mgcv::gam() only plots the spline ignoring all other terms / predictors (right?), while  `marginal_effects` conditions on certain values of other terms. If so, I may think of implementing an option to only plot splines.

**Comment by paul-buerkner** [comment]
I just pushed some commits adding the `marginal_smooths` method as an equivalent to the `plot` function of **mgcv**. This method allows you to obtain predictions and plots of smoothing terms. You can try it out with the dev version from github: `devtools::install_github("paul-buerkner/brms")`
