### ISSUE TITLE
Gumbel type in GEV distribution

### ISSUE THREAD

**Issue by JackCaster** [paul-buerkner/brms#1426]
According to https://en.wikipedia.org/wiki/Generalized_extreme_value_distribution, there are three types of GEV: Gumbel, Frechet, and Weibull. By reading the vignette [brms families](https://paul-buerkner.github.io/brms/articles/brms_families.html), it looks like brms parametrizes the GEV by including only when `xi` is different from 0 (i.e., no Gumbel case). According to the Wikipedia article, when `xi = 0` then `t(x) = exp{-(x-mu)/sigma}`.

Would you be able to confirm if GEV in brms includes all 3 types of distributions or only the Frechet / Weibull ones?

**Comment by paul-buerkner** [comment]
Have you tried setting xi=0 and see how it works? In the future, please ask brms related questions on https://discourse.mc-stan.org/

**Comment by JackCaster** [comment]
I apologize I did not use the forum. I set xi = 0 into `dgen_extreme_value` and it yields a result. I take it then that the Gumbel type is implemented, which is great. Thank you for the quick reply.
