### ISSUE TITLE
Issues with within chain threading  and QR Decomp on HPC

### ISSUE THREAD

**Issue by statslover123** [paul-buerkner/brms#1427]
Hello, I am working with a dataset for predicting several agricultural traits from genetic information, several hundred rows representing individuals, the first few columns are the response trait of interest, in this example below it is height,The remaining columns (not response traits like yield, height, protein) are a gene per column and then if an individual has that gene or not per row value (0 or 1). I have used both a lasso prior and horseshoe prior with this dataset using cmdstanr as the backend and the results are reasonable to other methods, however my code fails (I think compile issue?) when I try to include threads=threading(n) . I am doing this work on my uni's HPC as no device I own or have access to is reasonably powerful enough to do this work on. 
Example Code
for_lasso2 <- brm(Height ~ .,data = table2.dfw,iter=10000,chains = 1, backend = "cmdstanr", threads =threading(2), prior = prior(lasso(df=1,scale=1), class = b))

Error 

Semantic error in '/tmp/RtmpFPadg6/model_92d866b321584ef2528037f5fd178ba0.stan', line 21, column 76 to column 77:
   -------------------------------------------------
    19:      real ptarget = 0;
    20:      int N = end - start + 1;
    21:      ptarget += normal_id_glm_lupdf(Y[start:end] | Xc[start:end], Intercept, b, sigma);
                                                                                     ^
    22:      return ptarget;
    23:    }
   -------------------------------------------------

Identifier 'b' not in scope.

Error: Syntax error found! See the message above for more information.
Execution halted

**Comment by statslover123** [comment]
QR Decomp error below

Warning message:
In validityMethod(object) :
  The following variables have undefined values:  b.1,The following variables have undefined values:  b.2,The following variables have undefined values:  b.3,The following variables have undefined values:  b.4,The following variables have undefined values:  b.5,The following variables have undefined values:  b.6,The following variables have undefined values:  b.7,The following variables have undefined values:  b.8,The following variables have undefined values:  b.9,The following variables have undefined values:  b.10,The following variables have undefined values:  b.11,The following variables have undefined values:  b.12,The following variables have undefined values:  b.13,The following variables have undefined values:  b_Intercept. Many subsequent functions will not work correctly.

**Comment by statslover123** [comment]
QR Decomp error, this happens without threads = threading included 

Warning message:
In validityMethod(object) :
  The following variables have undefined values:  b.1,The following variables have undefined values:  b.2,The following variables have undefined values:  b.3,The following variables have undefined values:  b.4,The following variables have undefined values:  b.5,The following variables have undefined values:  b.6,The following variables have undefined values:  b.7,The following variables have undefined values:  b.8,The following variables have undefined values:  b.9,The following variables have undefined values:  b.10,The following variables have undefined values:  b.11,The following variables have undefined values:  b.12,The following variables have undefined values:  b.13,The following variables have undefined values:  b.14,The following variables have undefined values:  b.15,The following variables have undefined values:  b.16,The following variables have undefined values:  b.17,The following variables have undefined values:  b.18,The following variables have undefined values:  b.19,Th [... truncated]

**Comment by paul-buerkner** [comment]
Thanks. Should be fixed now. In the future, please provide a minimal reproducible example that I can just run so that I don't have to create one myself.

**Comment by statslover123** [comment]
Thank you Paul, reinstalling brms and checking now

**Comment by statslover123** [comment]
Looks like it works with horseshoe and lasso prior when trying within chain threading. When you say minimum reproducible, should I provide data to try with? sorry for the hassle

**Comment by paul-buerkner** [comment]
yes but ideally simple fake data so it is just as easy as copy pasting code
and running it.

statslover123 ***@***.***> schrieb am Do., 24. Nov. 2022,
22:00:
