### ISSUE TITLE
Feature request: adding a hurdle cumulative family

### ISSUE THREAD

**Issue by sjwild** [paul-buerkner/brms#1429]
I would like to know if there is any interest in adding a hurdle cumulative-type model. In a lot of survey research, for example, you will have a 5-point Likert scale along with a "Don't know" response option. A hurdle cumulative-type model would allow joint modeling of the "Don't know" responses and the Likert scale.

I have an example using brms and then modifying the resulting Stan code [here](https://github.com/sjwild/hurdle_ordered). (Note I did this using an "identity" link, which I will obviously fix).

I'm happy to initiate a pull request if there is interest.

**Comment by paul-buerkner** [comment]
This could be an interesting family indeed. How much effort is it to first code it up as a brms `custom_family`? That way, it is already easily useable by other people and from there we can see if we want to support it as a built-in family too?

**Comment by paul-buerkner** [comment]
Exciting, thank you! About the nlevels issue, I will think of a nice way to tell brms about the nlevels-2 requirement such that the workaround via an empty brmsfit object and stan code editing is no longer necessary.

**Comment by sjwild** [comment]
That'd be awesome. I _think_ you can do it by modifying the `extract_nthres()` function [here](https://github.com/paul-buerkner/brms/blob/b83c0efaab0e2e9c7ab033635447acd5f3d6fc59/R/data-response.R#L604) to test the `family` argument in `brmsformula`. If `family` is either `hurdle_cumulative` or `ord_beta` (or whatever they are going to be called) then it would generate the correct number of thresholds.

Not sure how that might work if you do something like `y | thres(...) ~ .` Maybe it would be possible to specify an error message or something.

**Comment by paul-buerkner** [comment]
I think, we could add another family `special` that tells how the number of categories relates to the number of thresholds. The default would be `-1` but we could flexibly set it to other values for new families. Once you are done with the custom family except for this point, let me know and I will see how to best implement this new special.

**Comment by sjwild** [comment]
Works for me. I will let you know once I have it finalized.

**Comment by paul-buerkner** [comment]
That looks good! Do you think you can prepare a PR implementing this as a built-in family? Asked differently, what would you need form my side to prepare such a PR?

**Comment by sjwild** [comment]
I'll take a look through a few of the closed PRs to see how it was handled for other families. The one issue that will still need to be addressed is adding another `special` the allows us to modify the number of thresholds vs categories, so that we there are two fewer thresholds than categories.

**Comment by paul-buerkner** [comment]
I have now added the special `"extra_cat"` that will be recognized by the right functions to count `nthres = ncat - 2`.

One question I had is the following: How shall this extra category be identified? We have to differentiate our answer between factor like response variables (factors and characters) and numeric variables, as is done in brms as follows:

```R
extract_nthres <- function(formula, data, diff = 1) {
  diff <- as_one_integer(diff)
  respform <- validate_resp_formula(formula)
  mr <- model.response(model.frame(respform, data))
  if (is_like_factor(mr)) {
    out <- length(levels(factor(mr)))
  } else {
    out <- max(mr)
  }
  out - diff
}
```

**Comment by sjwild** [comment]
I have been thinking about that the last couple days. I think one easy but unsatisfactory solution is to have the hurdle value be one higher than the maximum ordinal value (e.g., the hurdle value is coded as 6 if we are using a 5-point Likert scale). This also works for ordered factors, as the way I have coded it now `vint(hurdle)` needs to use the level number (e.g., level 6 if we are using a 5-point Likert scale + hurdle, regardless of the label used for the hurdle). 

The docs would need to be clear about the requirement that the hurdle be one higher than the maximum value of the ordinal scale.

I don't like this solution though, as I think it is likely going to be confusing for some users. I need to turn my mind to other potential solutions, but unfortunately I have been busy the last couple of days and haven't had a chance to try other ones.

Thoughts?

**Comment by paul-buerkner** [comment]
I think the last category could be sensible, although it would deviate from the usual hurdle notation of 0 ("first value") being the hurdle. So perhaps the first category could also be a sensible choice? I don't know to be honest. Perhaps, we could even extend the `[resp_]thres()` addition argument to a new argument where people can optionally name the hurdle category?

Also note that `vint()` addition term is not available for built-in families, only for custom families.

**Comment by sjwild** [comment]
I thought about zero initially, but encountered 2 issues that led me to specify a value for the hurdle vs use zero:

1) how to calculate the correct the number of thresholds, as for an ordinal factor you would need to remove 2 from the number of levels, while for integers you'd need to remove 1 from the maximum value.
2) for cumulative families, you get an error message saying zero is not valid for cumulative models.

I actually prefer the zero solution if we can get the correct number of thresholds. It is consistent with 0 being the hurdle. Allowing zero to ordinal models (via integer variables) could also solve another of the problems which prevents ordinal beta from being a supported family (I think. I need to look a bit more closely into this one).

If we want to let users specify the hurdle, my preference is to add an additional argument to `[resp]_thres()`.

**Comment by paul-buerkner** [comment]
Both of these issues are easy to solve programatically by checking for the `"extra_cat"` feature in the right places. If the first factor level (or 0) would be the hurdle category, I don't think we needed to add additional control to it via `[resp]_thres()` actually now that I think of it. I will adjust this tomorrow.

**Comment by paul-buerkner** [comment]
All should be prepared now for the first factor level (or 0) being the extra category:

```R
dat <- data.frame(y1 = 0:5, y2 = factor(1:6, ordered = TRUE))
# errors
make_standata(y1~1, dat, family = cumulative())

fam <- cumulative()
fam$specials <- c(fam$specials, "extra_cat")
sdata <- make_standata(y1~1, dat, family = fam)
sdata$Y  # should be 0:5
sdata$nthres  # should be 4

sdata <- make_standata(y2~1, dat, family = fam)
sdata$Y  # should be 0:5
sdata$nthres  # should be 4
```

**Comment by sjwild** [comment]
This is amazing. Thank you.

I will try this out and then see if I can do a pull request.

**Comment by sjwild** [comment]
I have gotten back to this after the holidays, and I want to clarify something before I finish editing the source code. Do you prefer that I, where possible, modify the existing brms functions for ordinal models or introduce new ones? In particular I am thinking of [`stan_ordinal_lpmf`](https://github.com/paul-buerkner/brms/blob/b8f3605d5f053ca1bc2ed8bb62cf49df70a4860f/R/stan-response.R#L494) and [`stan_log_lik_ordinal`](https://github.com/paul-buerkner/brms/blob/master/R/stan-likelihood.R#L796). Otherwise it is easy enough to create new ones (e.g., `stan_log_lik_hurdle_cumulative').

**Comment by paul-buerkner** [comment]
New ones sound good I think.

**Comment by sjwild** [comment]
Closing this as the pull request has been merged.

**Comment by zwelitunyiswa** [comment]
@paul-buerkner @sjwild  Thanks for all your hard work on the package in general and this PR in particular. Quick question, would this work with sequential ordinal models?

**Comment by sjwild** [comment]
Right now `hurdle_cumulative()` only works for cumulative families. I see no reason why it couldn't be extended to sequential or acat families if it's needed (note: I haven't thought about this deeply, so I might be wrong). I'll try spend some time tonight/tomorrow building a custom family to see if it will work. Please feel free to let me know what link function you want for the ordinal portion.

**Comment by zwelitunyiswa** [comment]
Thank you, I appreciate it! In my use case I have some data where patients
go through sequential stages of a disease, with the hurdle being if they
have healed.

I am thinking that the existing sratio(link = "logit", link_disc = "log",
threshold = "flexible") links would work, with the hurdle being logistic of
course.

**Comment by sjwild** [comment]
This [gist](https://gist.github.com/sjwild/d2f4897c98c3ad2588fe7836fa5e294e) contains the code that should work for you as a custom family. There are two files in the gist. The first one is a collection of helper functions needed to run `log_lik_hurdle_sratio()`, `posterior_predict_hurdle_sratio()`, and `posterior_epred_hurdle_sratio()`; they are all taken from the brms source code. The second script contains the main functions and a small example adapted from the Vuorre and Buerkner paper on ordinal models.

Hopefully this works. Please let me know if there are issues.

**Comment by zwelitunyiswa** [comment]
Thank you! This is brilliant.

I will try it on Monday and let you know how it works.
