### ISSUE TITLE
Interpretación of VarCorr outpur

### ISSUE THREAD

**Issue by inti** [paul-buerkner/brms#143]
Hi
The Cov columns in The outpur of VarCorr, what do they mean?
My interpretation is that it is The covariance among the levels of the random effect. Is that correct?
When i have a random effect in the mean and sigma of a gaussian model o Getafe am addotional Cov columns, is this the covariance between the same random effect on both parts of the model? Is this 0 by default or is is being modelled?
Thanks in advance

**Comment by paul-buerkner** [comment]
Your interpretation is correct. Cov is the covariance of different random effects, i.e. cov = sd1 * sd2 * cor. The covariance of a random effect with itself is, by definition, just its variance, i.e. sd^2.

**Comment by inti** [comment]
Great, thanks for the answer.
Is it possible to specify correlation structures for the random effects, for instance like in nlme R package with commands like 

random = ~ +1 | person,
correlation=corCompSymm(form=~day|person)

Here are some examples
http://stackoverflow.com/questions/11819720/converting-repeated-measures-mixed-model-formula-from-sas-to-r

I want to model repeated measures and the original model was coded with SAS.

Look forwards to you suggestions!

**Comment by inti** [comment]
Here is an example, is it possible to code this on `brms`? 

Many thanks in advance! 

```
>library(nlme)
> fm4OatsB <- lme( yield ~ nitro, data = Oats,
+                 random =list(Block = pdSymm(~ Variety - 1)))
> summary( fm4OatsB )
Linear mixed-effects model fit by REML
 Data: Oats 
       AIC      BIC    logLik
  607.2017 627.4381 -294.6008

Random effects:
 Formula: ~Variety - 1 | Block
 Structure: General positive-definite
                   StdDev   Corr         
VarietyGolden Rain 16.23948 VrtyGR VrtyMr
VarietyMarvellous  15.25836 0.594        
VarietyVictory     23.19354 0.936  0.484 
Residual           12.86699              

Fixed effects: yield ~ nitro 
               Value Std.Error DF  t-value p-value
(Intercept) 86.59056  6.267030 65 13.81684       0
nitro       73.66667  6.781501 65 10.86289       0
 Correlation: 
      (Intr)
nitro -0.325

Standardized Within-Group Residuals:
        Min          Q1         Med          Q3         Max 
-1.69439628 -0.73702848 -0.06933371  0.64168250  1.74010016 

Number of Observations: 72
Number of Groups: 6 
```

**Comment by paul-buerkner** [comment]
In **brms** you specify random effects using **lme4** syntax. The above model with structure `pdSymm` looks as follows:

```R
fit <- brm(yield ~ nitro + (Variety - 1 | Block), data = Oats)
```

The `pdCompSymm` structure is currently not implemented.

**Comment by inti** [comment]
Hi,
Thanks for that. In case it is useful to other people. I am pasting the output of brms below. 
The value of the correlation is not equal but obviously `lme` is using ML and `brms` is not. Do you think the prior is the only things that is making the results look different?

Thanks in advance

```
>fit <- brm(yield ~ nitro + (Variety - 1 | Block), data = Oats)
> summary(fit)
 Family: gaussian (identity) 
Formula: yield ~ nitro + (Variety - 1 | Block) 
   Data: Oats (Number of observations: 72) 
Samples: 4 chains, each with iter = 2000; warmup = 1000; thin = 1; 
         total post-warmup samples = 4000
   WAIC: Not computed
 
Group-Level Effects: 
~Block (Number of levels: 6) 
                                         Estimate Est.Error l-95% CI u-95% CI Eff.Sample
sd(VarietyGoldenRain)                       17.52      6.41     8.60    33.16       1708
sd(VarietyMarvellous)                       19.41      7.54     8.76    37.98       1540
sd(VarietyVictory)                          24.25      7.93    12.68    43.26       1599
cor(VarietyGoldenRain,VarietyMarvellous)     0.33      0.34    -0.43     0.86       1259
cor(VarietyGoldenRain,VarietyVictory)        0.60      0.28    -0.11     0.96       1809
cor(VarietyMarvellous,VarietyVictory)        0.20      0.35    -0.52     0.80       2014
                                         Rhat
sd(VarietyGoldenRain)                       1
sd(VarietyMarvellous)                       1
sd(VarietyVictory)                          1
cor(VarietyGoldenRain,VarietyMarvellous)    1
cor(VarietyGoldenRain,VarietyVictory)       1
cor(VarietyMarvellous,VarietyVictory)       1

Population-Level Effects: 
          Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
Intercept    83.95      6.69    71.07    97.65       1214    1
nitro        73.53      6.88    60.23    87.00       4000    1

Family Specific Parameters: 
      Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
sigma     13.3      1.29    11.12     16.1       2528    1

Samples were drawn using sampling(NUTS). For each parameter, Eff.Sample 
is a crude measure of effective sample size, and Rhat is the potential 
scale reduction factor on split chains (at convergence, Rhat = 1).
```

Here is the output of `lme4`

```
>library(lme4)
>summary(lmer(yield ~ nitro + (Variety - 1 | Block), data = Oats))
Linear mixed model fit by REML ['lmerMod']
Formula: yield ~ nitro + (Variety - 1 | Block)
   Data: Oats

REML criterion at convergence: 589.2

Scaled residuals: 
     Min       1Q   Median       3Q      Max 
-1.69440 -0.73701 -0.06934  0.64167  1.74009 

Random effects:
 Groups   Name               Variance Std.Dev. Corr     
 Block    VarietyGolden Rain 263.7    16.24             
          VarietyMarvellous  232.8    15.26    0.59     
          VarietyVictory     537.9    23.19    0.94 0.48
 Residual                    165.6    12.87             
Number of obs: 72, groups:  Block, 6

Fixed effects:
            Estimate Std. Error t value
(Intercept)   86.590      6.267   13.82
nitro         73.667      6.781   10.86

Correlation of Fixed Effects:
      (Intr)
nitro -0.325
```

**Comment by paul-buerkner** [comment]
For this model, the default priors will only have a minimal influence on the estimates. The main reason for the difference is that nlme estimates the mode of the "posterior" via ML, while brms estimates the mean via full bayesian inference. For skewed posterior distributions (e.g., for sds or cors), mode and mean will differ and this is exactly what we see here.

**Comment by inti** [comment]
After looking at the plots of the posterior densities (`plot(fit)`) they do not look outrageously different. I tend to agree with you, that is why one would want to go account for that uncertainty.

Thanks a lot!!!

**Comment by Rolpio** [comment]
I am a little bit confused with hoe I should calibrate and use the "w" matrix within a poisson model in brms. Here is my model below:
I have a two levels model,  "mat" is the matrix generated for the first level (is that correct to do so?). The intention was to control the spatial autocorrolation at that level. The second level is comprised within the dataset and it is named "UPPERGEOG".




model <- brm(Y ~ relevel(SES1, ref= "Q1") + relevel(SES2, ref="Q1") + (1|UPPERGEOG)+ offset(log(EXP)), data = DATASET,family="poisson", control = list(max_treedepth = 35), autocor=cor_car(mat, type= ("escar")), prior=PriorBrFullLasso,warmup = 4000, iter =25000, chains= 6)



My second question is about the einterpretation of the car and sdcar correlation structure. I have no idea how to interpret those:




Group-Level Effects: 
~LGA (Number of levels: 16) 
              Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
sd(Intercept)     0.05      0.02     0.02     0.09       5073 1.00

Correlation Structure: car(mat, ~1, 'escar')
      Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
car       0.98      0.02     0.92     1.00       1555 1.01
sdcar     0.17      0.01     0.15     0.18       7289 1.00

**Comment by paul-buerkner** [comment]
This is definitely offtopic. Please ask such questions on brms-users (
https://groups.google.com/forum/#!forum/brms-users).

2017-11-01 0:01 GMT+01:00 Rolpio <notifications@github.com>:
