### ISSUE TITLE
feature request: Apache arrow for reading/writing arms files.

### ISSUE THREAD

**Issue by go-bayes** [paul-buerkner/brms#1430]
Apache Arrow reads and writes files blazingly fast, and reduces demand on RAM. 

It might be useful to take advantage of arrow when writing and reading brms files, which may be vary large.

Example to identify point of advantage in our workflows.  Obviously won't work. 

Just to consider. 

Grateful, as ever!

```
library("brms")
library("rstan")
library("cmdstanr")
library("arrow")
library("here")


# setup
rstan_options(auto_write = TRUE) 
options(mc.cores = parallel::detectCores ()) # use all course

# data
data(iris)

# ordinary workflow
temp_1 <- brm(
  data = iris,
  Sepal.Length ~ Sepal.Width,
  file = here::here( "temp_1.rds"),
  backend = "cmdstanr"
  )


# desired workflow (obviously won't work)
temp_2 <- brm(
  data = iris,
  Sepal.Length ~ Sepal.Width,
  file = arrow::write_parquet( here::here( "temp_2.rds") ),
  backend = "cmdstanr"
)
```

**Comment by paul-buerkner** [comment]
Thank you for this suggestion! I will look into it.

**Comment by mvuorre** [comment]
fwiw qs might offer a simpler alternative with fewer dependencies https://github.com/traversc/qs

**Comment by paul-buerkner** [comment]
I will close this issue for now to clean up the issue tracker a bit, since I don't think this is a high priority issue.
