### ISSUE TITLE
Typos in `horseshoe()` docs?

### ISSUE THREAD

**Issue by fweber144** [paul-buerkner/brms#1431]
The docs for argument `scale_slab` of `horseshoe()` say:

> Scale of the student-t prior of the regularization parameter.

However, as far as I understand equation (2.9) and section 2.3 of Piironen and Vehtari (2017), the Student-t slab (for the regression coefficients) is achieved by giving the regularization parameter $c^2$ an inverse-gamma distribution. So I guess the above should read something like

> Scale of the Student-t slab.

instead.

The same applies to `df_slab`.

### References

Piironen, J., & Vehtari, A. (2017). Sparsity information and regularization in the horseshoe and other shrinkage priors. *Electronic Journal of Statistics*, 11(2), 5018–5051. https://doi.org/10.1214/17-EJS1337SI

**Comment by paul-buerkner** [comment]
Thank you! @avehtari can you confirm this suggested documentation change would be correct?

**Comment by avehtari** [comment]
Yes

**Comment by paul-buerkner** [comment]
Thank you both. Fixed it.
