### ISSUE TITLE
Feature request: nest `mi` terms in `reduce_sum` call

### ISSUE THREAD

**Issue by saudiwin** [paul-buerkner/brms#1434]
#### Please note:
The brms issue tracker is reserved for bug reports and feature requests. brms-related questions should rather be asked on https://discourse.mc-stan.org/ in order to reach a wider community.

Hi Paul - 

While using the `mi`/`me` syntax with `reduce_sum`, I've noticed that the priors for the missing variables are evaluated in the model section, not in the `reduce_sum` call. However, doing so will reduce the value of the `reduce_sum` call as it increases communication across likelihood evaluations. Would it be doable to add the priors for `mi` terms in the `reduce_sum` calls? Obviously would require code work but might have some serious payoff for improving `reduce_sum` speed in `brms`. Right now when using multiple threads with `mi` terms I'm only seeing about 20-30% core utilization.

I can add code here if you want me to.

**Comment by wds15** [comment]
How much speedup you are getting with mi terms and how much without? I'd suggest profiling the matter first in any case. I can imagine that nesting mi inside of reduce_sum is a good thing as it cuts down the tree of the AD tape quite a bit leading to better memory locality.

**Comment by paul-buerkner** [comment]
I will close this issue to reduce the load on the issue tracker since there hasn't been any relevant update or benchmarks in a while. Feel free to reopen this issue if we get evidence that the different Stan code indeed improves efficiency noticably.
