### ISSUE TITLE
Fails to accept logical predictor values

### ISSUE THREAD

**Issue by epkanol** [paul-buerkner/brms#1442]
I'm new to Bayesian modeling, and in particular brms, so excuse me if I'm out of my mind.
But I think I found an issue with how brms validates (or handles) logical values, related to predictions.
Note - I do not know if this is a problem in brms or in tidybayes (I just realized that `predicted_draws` comes from that package).

I came across this when I used TRUE/FALSE (logical) values in one of my data sets (essentially indicator variables).

My model is a zero-inflated negative binomial, and the formula is a simple:

```
  y ~ 1 + A + B + C,
  zi ~ 1
```

I coded my data like this:

`d <- data.frame(y = y, A=A/sd(A), B=B/sd(B), C=as.factor(ifelse(C == 1, T, F)))`

While the stan program and all checks work well, I could not specify newdata for making predictions.

`newdata <- data.frame(t(c(A=17, B=24, C=T)))`

When I specify my data like this, I get:

```
Error: New factor levels are not allowed.
Levels allowed: 'FALSE', 'TRUE'
Levels found: '1'
```

Attached to this issue, there is a "minimal" zipped Rmd file showing the behaviour.

[brms_logical_factor_levels.zip](https://github.com/paul-buerkner/brms/files/10271809/brms_logical_factor_levels.zip)

If I change to other factor levels (e.g. `C=as.factor(ifelse(C == 1, 2, 1)`), then everything works (provided I use those numbers in the newdata, that is...)

**Comment by paul-buerkner** [comment]
The transpose operator `t()` transforms to numeric values, hence transforms TRUE to 1. This is causing the error. `newdata <- data.frame(A=17, B=24, C=TRUE)` works.

**Comment by epkanol** [comment]
Thanks a lot for the speedy reply and the nice learning experience (I'm not that familiar with the details of R either, as you probably can tell :-)
All the best, and have a nice holiday!
