### ISSUE TITLE
About posterior distribution

### ISSUE THREAD

**Issue by LfeiXie** [paul-buerkner/brms#1444]
I'm new to the bayesian inference, also to the brms package. Therefore, I'm looking for a feature of giving the posterior distribution for a developed model, so that, it can be used directly for model updating with a small but new data in the next time. Namely, I developed a bayesian hierarchical linear model with a lager data and now I want to update the model with a small and new datat, however, the old fitting results (posterior distribution of all parameters) should be referred to as the prior information of the new fitting.
Does the _brms_ package provide the similar functions as the _prior_summary_ function?

**Comment by paul-buerkner** [comment]
Hi, welcome to brms. Please ask brms related questions on discourse.mc-stan.org/ rather than as github issues.
