### ISSUE TITLE
Bayesian Quantile Regression

### ISSUE THREAD

**Issue by Steviey** [paul-buerkner/brms#1445]
**Why this is not working, how can we hint it?...**

`myModel  <- brms::brm(brms::bf(myFormula, quantile=seq(0.1, 0.9, by = 0.1)), data = df_train, family = asym_laplace(),chains=myChains,iter=myIter)
`
Caused by error:
! Expecting a single value when fixing parameter 'quantile'.

**Comment by paul-buerkner** [comment]
Please ask brms reqlated questions on discourse.mc-stan.org/

**Comment by Steviey** [comment]
Thank you.
