### ISSUE TITLE
Error when call to `arma` is very long

### ISSUE THREAD

**Issue by mpdylan** [paul-buerkner/brms#1446]
While working on the feature for issue #1307, I encountered the following bug. If a call to `arma` (or `ar`, etc.) has too many characters, attempting to fit the model using `brm` will raise an error. This can occur if the name of a time variable or grouping factor is very long, and is more likely to occur when flags such as `cov = TRUE` are set.

```
> fit <- brm(y ~ 1 + ar(p = 1, time = t, gr = really_really_long_grouping_factor, cov = TRUE), data = dt)
Error:  Cannot coerce 'label' to a single character value.
> fit <- brm(y ~ 1 + ar(p = 1, time = t, gr = really_long_grouping_factor, cov = TRUE), data = dt)
Compiling Stan program...
```

I think this is caused by the default value of 60 for `width.cutoff` in the `deparse` function used to extract a label for the AC effect, causing long call strings to be split into multiple lines. Using `deparse1`, or, for compatibility with older versions of R, using `paste` to join the result, would probably fix it.

**Comment by paul-buerkner** [comment]
Thanks! brms has a function for that but apparently I didn't use it consistenly. Will fix soon.

**Comment by paul-buerkner** [comment]
Should now be fixed.
