### ISSUE TITLE
Return prior estimates using the `fitted` method

### ISSUE THREAD

**Issue by tomwallis** [paul-buerkner/brms#145]
The `brm` function allows one to sample from the prior distribution as well (by setting `sample_prior = TRUE`). The `prior_samples` method allows one to extract samples for model parameters, as for `posterior_samples`. However, I would like to extract prior samples on the regression line (as in the `fitted(object...)` method). 

My intention here is to compute Savage-Dickey Bayes Factor estimates for a point value of the prediction, under the assumption that priors over nuisance parameters are the same for a null model and my fitted model. That is, I want to compute the density ratio posterior / prior, to quantify the change in belief for a specific point on the regression line after having seen the data.

Is there a timeline for this to be implemented, or a way to do this that I am missing?

**Comment by paul-buerkner** [comment]
Currently, priors samples are only used in the `hypothesis` method, which is also able to compute BFs for point hypotheses. However computing the regression line using this method will presumably be rather difficult (in depends on the model though). There are other aspects which might complicate things. For instance, currently no prior samples are drawn for group-level effects (i.e., `r_*` parameters) as this is more complicated to parse and automatically code in **Stan**. For what kind of model do you need this feature? Maybe I could start implementing it for more simple models.

**Comment by tomwallis** [comment]
The model I'm fitting is a logistic GLMM, with two random effects. 

I can see how it would be complicated to get prior predictions for random effects, but maybe ignoring random effects it should be possible? Aside from the SD Bayes Factor method, it might be useful to be able to visualise prior regression lines (to show visually how much / little information is contained in the prior on the response scale).

Thanks for the pointer to the `hypothesis` method; I hadn't seen it.

**Comment by paul-buerkner** [comment]
Let's say you have a simple logistic regression with predictor `x`. Then, it might be possible to get what you want using the `hypothesis` method. With a small example model, it would look like as follows:

```R
n <- sample(1:10, 100, TRUE)
success <- rbinom(100, size = n, prob = 0.4)
x <- rnorm(100)
dat <- data.frame(x, n, success)
fit4 <- brm(success | trials(n) ~ 0 + intercept + x, 
            data = dat, family = binomial(),
            prior = set_prior("normal(0,5)"),
            sample_prior = TRUE)

(hyp <- hypothesis(fit4, "inv_logit(intercept + x * 1) = 0.5"))
plot(hyp, chars = NULL)
```

In `hypothesis`, replace `1` with the value of your predictor that is of interest for you and `0.5` with the regression value (probability in this case) you are hypothesizing.

I will think of how to get `fitted` and related methods running with prior samples.

**Comment by paul-buerkner** [comment]
After discussing this further via email, the solution is to fit two models. One is just the model of interest and the second is a model using the same priors but with argument `sample_prior = "only"`. The latter model does only sample from priors and can be used in `fitted` etc. to obtain predictions based on just the priors.

@tomwallis Are you ok if I close this issue?

**Comment by tomwallis** [comment]
Great, thanks Paul.
