### ISSUE TITLE
Unnecessary variables required in `newdata` for predictions in projpred

### ISSUE THREAD

**Issue by fweber144** [paul-buerkner/brms#1457]
When performing predictions with new data in projpred, brms reference models require `newdata` to contain the response (and in fact *all* variables from the original dataset), which is not necessary after projecting onto a smaller model:
```r
library(brms)
options(mc.cores = parallel::detectCores())
ref_fit <- brm(
  formula = rate ~ conc + state,
  data = Puromycin,
  backend = "cmdstanr",
  seed = 2052109,
  refresh = 0
)

library(projpred)
soltrms <- "conc"
prj <- project(ref_fit, solution_terms = soltrms, ndraws = 40)
Puromycin_new <- as.data.frame(sapply(Puromycin[soltrms], quantile))
prj_linpred <- proj_linpred(prj, newdata = Puromycin_new)
```
with the last line throwing
```
Error: Response variables must be specified in 'newdata'.
Missing variables: 'rate'
```
(Tested with projpred 2.4.0 and brms's GitHub version, commit https://github.com/paul-buerkner/brms/commit/b31fcee8db3f4d04635f4ad25f0290367277a915.)

This also came up in [The Stan Forums](https://discourse.mc-stan.org/t/projpred-model-with-horseshoe-prior-does-not-converge/29935) and seems to be a long-standing bug, probably related to the `extract_model_data()` function defined in brms and passed to `projpred::init_refmodel()` (the  `extract_model_data` argument was introduced in projpred 2.0.0, so quite some time ago). I will try to fix this and then create a PR.

**Comment by paul-buerkner** [comment]
thank you for checking this out!

Frank Weber ***@***.***> schrieb am Di., 14. Feb. 2023, 13:29:
