### ISSUE TITLE
Exposure for Poisson models

### ISSUE THREAD

**Issue by mrojala** [paul-buerkner/brms#146]
Poisson family doesn't support currently separate exposure/offset but assumes that all points have the same exposure. You can of course add log(exposure) as one of the model parameters but it'd be nice to fix the coefficient to 1. For example, the binomial model supports currently response like success | trials(n). For Poisson models, it could look like rate | exposure(n), and it could correspond to poisson_log(.. + log(n)).

**Comment by paul-buerkner** [comment]
Hey, is this solvable by adding an offset to the linear predictor? For instance,

```R
brm(y ~ ... + offset(log(n)), family = poisson())
```

This would transfor, to `poisson_log(... + log(n))` if I am not mistaken.

**Comment by mrojala** [comment]
Ah, yes, of course! Just tested and that works. Thanks!

**Comment by paul-buerkner** [comment]
Great! :-)

**Comment by ASKurz** [comment]
I’m missing something with how to use offset to account for exposure in a Poisson model. Based on McElreath’s text, pp 321–322, that data are:

num_days <- 30
set.seed(1) 
y <- rpois(num_days, lambda = 1.5)

num_weeks <- 4
set.seed(1)
y_new <- rpois(num_weeks, lambda = 0.5*7)

y_all <- c(y, y_new)
exposure <-  c(rep(1, 30), rep(7, 4))
monastery <- c(rep(0, 30), rep(1, 4)) 
d <- data.frame(y = y_all, 
                days = exposure, 
                monastery = monastery)

Using code from McElreath’s rethinking package:

m10.15 <- map(
    alist(
        y ~ dpois( lambda ),
        log(lambda) <- log_days + a + b*monastery,
        a ~ dnorm(0,100),
        b ~ dnorm(0,1)
), data=d ) 
precis(m10.15)

The results are:

Mean StdDev  5.5% 94.5%
a   0.43   0.15   0.19   0.66
b -0.99   0.28 -1.43 -0.54


My attempt to do this in arms:

b10.15 <- brm(data = d, family = "poisson",
               y ~ 1 + monastery + offset(log(days)),
               prior = c(set_prior("normal(0, 100)", class = "Intercept"), 
                         set_prior("normal(0, 1)", class = "b")),
               chains = 4, iter = 4000, warmup = 1000, cores = 4) 
print(b10.15)

But the results are quite different for the monastery slope:

Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
Intercept     0.45      0.14     0.16     0.73       7796    1
monastery     0.79      0.29     0.20     1.35       7925    1


What am I missing?

**Comment by paul-buerkner** [comment]
There is a problem with the inclusion of offsets for some models in brms 1.5.1. This should already be fixed in the dev version of brms to be installed via

```R
if (!require("devtools")) {
  install.packages("devtools")
}
devtools::install_github("paul-buerkner/brms", dependencies = TRUE)
```

**Comment by ASKurz** [comment]
Success:

Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
Intercept     0.42      0.14     0.13     0.69       8892    1
monastery    -1.01      0.28    -1.57    -0.48       9445    1

Thanks Paul!
