### ISSUE TITLE
GAM with t2() computed on RStudioServer (Linux): output for conditional_effect() incorrect on MacOS

### ISSUE THREAD

**Issue by urskalbitzer** [paul-buerkner/brms#1462]
Hi,
I am fitting a GAM(M) on an R Studio Server (running on Linux). Then, I save the object, download it, and load it in R Studio on my MacBook (running on MacOS). The `summary()` output looks identical in both environments. However, the plots created with `conditional_effect()` look totally different. Below is a reprex, and the real-life example looks even worse. Do you have an idea how this could be fixed? Any help would be highly appreciated as I have to run some of these models on the server.

Thanks!

``` r
library(brms)
#> Loading required package: Rcpp
#> Loading 'brms' package (version 2.18.0). Useful instructions
#> can be found by typing help('brms'). A more detailed introduction
#> to the package is available through vignette('brms_overview').
#> 
#> Attaching package: 'brms'
#> The following object is masked from 'package:stats':
#> 
#>     ar
set.seed(123)
df <- data.frame(x = rep(1:50, each = 10))
df$y_prob <- (sin(df$x) + 1)/seq(from = 2, to = 4, length.out = 500)
df$y_count = rbinom(n = length(df$y_prob), size = 4, prob = df$y_prob)
mod <- brm(y_count | trials(4) ~ t2(x, bs = c("cr"), k = 50),
           family = binomial,
           chain = 1,
           data = df)
#> Compiling Stan program...

# Removed some output here, but sampling went well

saveRDS(mod, file = here::here("model_results/linux_macos_issue_model.rds"))
# summary(mod)
conditional_effects(mod)
```

![](https://i.imgur.com/CwcsPxP.png)

<sup>Created on 2023-02-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

And here's the output on my Mac after reading the file
``` r
library(brms)
#> Loading required package: Rcpp
#> Loading 'brms' package (version 2.18.0). Useful instructions
#> can be found by typing help('brms'). A more detailed introduction
#> to the package is available through vignette('brms_overview').
#> 
#> Attaching package: 'brms'
#> The following object is masked from 'package:stats':
#> 
#>     ar
mod <- readRDS("/Users/username/Downloads/linux_macos_issue_model.rds")
# summary(mod)
conditional_effects(mod)
```

![](https://i.imgur.com/n6Swi5i.png)

<sup>Created on 2023-02-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Session Info on RStudioServer:
``` r
sessionInfo()
#> R version 4.2.2 (2022-10-31)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Ubuntu 22.04.1 LTS
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
#> LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so
#> 
#> locale:
#>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
#>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
#>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] digest_0.6.31   withr_2.5.0     lifecycle_1.0.3 reprex_2.0.2   
#>  [5] evaluate_0.20   rlang_1.0.6     cli_3.6.0       rstudioapi_0.14
#>  [9] fs_1.6.1        rmarkdown_2.20  tools_4.2.2     glue_1.6.2     
#> [13] xfun_0.37       yaml_2.3.7      fastmap_1.1.0   compiler_4.2.2 
#> [17] htmltools_0.5.4 knitr_1.42
```

<sup>Created on 2023-02-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

SessionInfo on MacBook/macOS
``` r
sessionInfo()
#> R version 4.2.2 (2022-10-31)
#> Platform: aarch64-apple-darwin20 (64-bit)
#> Running under: macOS Ventura 13.1
#> 
#> Matrix products: default
#> BLAS:   /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRblas.0.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] withr_2.5.0     digest_0.6.31   lifecycle_1.0.3 magrittr_2.0.3 
#>  [5] reprex_2.0.2    evaluate_0.19   highr_0.10      stringi_1.7.8  
#>  [9] rlang_1.0.6     cli_3.6.0       rstudioapi_0.14 fs_1.5.2       
#> [13] vctrs_0.5.2     rmarkdown_2.19  tools_4.2.2     stringr_1.5.0  
#> [17] glue_1.6.2      xfun_0.36       yaml_2.3.6      fastmap_1.1.0  
#> [21] compiler_4.2.2  htmltools_0.5.4 knitr_1.41
```

<sup>Created on 2023-02-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by paul-buerkner** [comment]
This is a known issue (#1386), which I have not found a solution for yet. If anybody has an idea, I would love to hear.

**Comment by urskalbitzer** [comment]
Thanks for the quick response and apologies for not spotting the other filed issue.

Clearly beyond my technical skills to fix that, but I will try out to use a different version of R to run the models and also look for other solutions.

This is probably one of the weirdest issue I have encountered with R.

**Comment by paul-buerkner** [comment]
Agreed. When I first encountered it myself, I was super puzzled and I still am today.

**Comment by urskalbitzer** [comment]
Just some additions in case that is helpful to anyone looking at this issue:

- I tried `save` and `load` instead of `saveRDS` and `readRDS`, but this didn't make a difference.
- I used `as_draws_df(modefit)` and saved the output with `save()` on the linux server. Then, on my MacBook, I also used `as_draws_df(modelfit)` with the imported model fit that creates an incorrect output for `conditional_effect`. Samples drawn from the model fit on the linux server are identical to samples drawn on the MacBook (probably not surprising)
- I compared the output from `str(modelfit)` from the linux server with the output from `str(modelfit)` with the imported modelfit on my MacBook. Only differences are below (why would this process affect the environment?)

From `str(modelfit)` on linux server
[1] "  .. .. ..- attr(*, \".Environment\")=<environment: 0x557e103d8288> "
[2] "  .. .. .. .. .. ..@ .CXXDSOMISC :<environment: 0x557e113ca908> "    
[3] "  .. ..@ .MISC     :<environment: 0x557e10fbac70> "                  

From `str(modelfit)` on macbook

[1] "  .. .. ..- attr(*, \".Environment\")=<environment: 0x16504cb88> "
[2] "  .. .. .. .. .. ..@ .CXXDSOMISC :<environment: 0x16504fed8> "    
[3] "  .. ..@ .MISC     :<environment: 0x140eccca0> "

**Comment by urskalbitzer** [comment]
Last comment before I look for another solution (I will probably just run the models on my laptop).

In the reprex above I (1) fitted the model on the linux server, (2) saved it as .rds, and then (3) read the saved .rds file on my MacBook. As a result, the predicted values differed between the linux server and my local MacBook.

Now, I also re-fitted the model from the reprex on my MacBook. As a result, I have two model fits for the same model, one fitted on the linux server (`modelfit_server`) and one fitted on my local computer (`modelfit_local`). And I have both model objects on the same computer so that I can directly compare them.

Any (major) difference in predicted values should be linked to difference between these two models fits. There are some minor differences as expected based on the sampling procedure, but they also seem to have some structural differences, specifically in `modelfit$fit`

For example, `modelfit_server$fit@.MISC` has two items (`modelfit_server$fit@.MISC$stan_fit_instance` and `modelfit_server$fit@.MISC$summary`), but `modelfit_local$fit@.MISC` only has the item `$stan_fit_instance` and no `$summary`. Is it expected to have such structural differences between models fit on two different computers?

Also, for the model from the linux server, I get an error for `modelfit_server$fit@.MISC$stan_fit_instance`
>Error in sprintf("C++ object <%s> of class '%s' <%s>", externalptr_address(pointer),  : 
  external pointer is not valid

For the local modelfit I get `modelfit_local$fit@.MISC$stan_fit_instance`
> C++ object <0x11069b7c0> of class 'stan_fit' <0x1106c7c40>

It seems that there are several other differences, and I though it might be helpful to post about it.

Thanks again for your great work on the brms package,
Urs

**Comment by pmhogan** [comment]
@urskalbitzer -- this issue may be due to a mismatch between your BLAS/LAPACK library implementations. From your session info's, it appears that your server is using OpenBLAS but your MacBook the default R-internal version. In issue #1465 I describe a similar problem for spline models which I was able to resolve by ensuring that either the default, R-internal libraries, or the same version of external libraries, are used in both training and prediction environments 👍

**Comment by urskalbitzer** [comment]
Thanks @pmhogan , I saw your post yesterday and was so happy to see that you engaged with the problem and found a solution. Also, thanks for checking my session Info. I will figure out how to use the same libraries on both the server and my local machine (i.e., the two different environments I am using).
