### ISSUE TITLE
Error: Family 'cumulative' requires either positive integers or ordered factors as responses

### ISSUE THREAD

**Issue by herryATcsiro** [paul-buerkner/brms#1468]
Hiya, I get a similar error to previous issue #790:
db=data.frame(Score=factor(rep(c("Low", "Medium","High"),10), 
                           ordered=T, levels=c("Low", "Medium","High")))
is.ordered(db$Score)
m0=brm(f0,data=db, family=cumulative("logit"))

What am I missing?

_Originally posted by @herryATcsiro in https://github.com/paul-buerkner/brms/issues/790#issuecomment-1469463769_

**Comment by paul-buerkner** [comment]
Please ask brms related questions on Stan discourse forums.
