### ISSUE TITLE
non-linear models and missing value modelling

### ISSUE THREAD

**Issue by wds15** [paul-buerkner/brms#1469]
I think I am running into an issue where brms does not let me fit a model, which should just work (I think). Here is a small example:

```
library(brms)
library(dplyr)

set.seed(3465346)
loss2 <- mutate(loss, l=rnorm(n()), miss=rbinom(n(), 1, prob=0.2), lobs=ifelse(miss==1, NA, l))
loss2

fit_loss_2 <- brm(
  bf(cum ~ ult * (1 - exp(-(dev/theta)^omega)),
     ult ~ 1 + (1|AY), omega ~ 1, theta ~ 1 + mi(lobs),
     lobs | mi() ~ 1,
     nl = TRUE),
  data = loss2, family = gaussian(),
  prior = c(
    prior(normal(5000, 1000), nlpar = "ult"),
    prior(normal(1, 2), nlpar = "omega"),
    prior(normal(45, 10), nlpar = "theta"),
    prior(normal(0, 1), nlpar = "lobs")
  ),
  control = list(adapt_delta = 0.9)
)
```

This is aborted with this message:

```
+ Error: The parameter 'lobs' is not a valid distributional or non-linear parameter. Did you forget to set 'nl = TRUE'?
```

But I'd expect this to "just" work, no?

... and here is one more thing which is not possible as it seems: I can't have missing values in parameters of a non-linear formula as it seems (happy to open another issue if that makes sense).

This is brms version 2.18.8.

**Comment by paul-buerkner** [comment]
mi() requires a multivariate model, that is a separate bf() call. mi() terms are not designed to work in non-linear formulas and there is no need to since you can always move the corresponding specification into a linear formula passed to a non-linear parameter.

**Comment by wds15** [comment]
Ahh... I was giving multiple linear formulas within a single `bf` statement and was not aware that this is different from multiple `bf` calls. So this does what I want:

```
model <- bf(cum ~ ult * (1 - exp(-(dev/theta)^omega)),
            ult ~ 1 + (1|AY), omega ~ 1,
            nl = TRUE) +
    lf(theta ~ 1 + mi(lobs)) +
    bf(lobs | mi() ~ 1) + set_rescor(FALSE)

mprior <- prior(normal(5000, 1000), resp=cum, nlpar = ult) +
    prior(normal(1, 2), resp=cum, nlpar = omega) +
    prior(normal(45, 10), resp=cum, nlpar = theta) +
    prior(normal(0, 1), class=Intercept, resp = lobs)

get_prior(model, loss2)

make_stancode(model, loss2, prior=mprior, family=gaussian)

fit_loss_2 <- brm(model,
  data = loss2, family = gaussian(),
  prior = mprior,
  control = list(adapt_delta = 0.9)
)
```

Thanks!
