### ISSUE TITLE
Cannot remove Rtmp folder after brm call

### ISSUE THREAD

**Issue by GMFranceschini** [paul-buerkner/brms#1470]
Good morning,
I am running a `brms` model with parallelization, using the `foreach` R package. 
I fit hundreds of them, and I get the following problem:

```
rm: cannot remove '<...>/tmp/RtmpOWoDlF/.nfs0000000050382f520000528b': Device or resource busy
```
The models are successfully fit and I get the expected results, however, this accumulation of `tmp` files is somehow inconvenient.

Is there a known issue with using `brms` in parallel? Any advice on how to solve this?

**Comment by paul-buerkner** [comment]
I am sorry, I don't think I can help you with this issue. Perhaps ask in the stan forums and provide some more details there?
