### ISSUE TITLE
b_Intercept vs prior_Intercept

### ISSUE THREAD

**Issue by bnicenboim** [paul-buerkner/brms#1472]
Hi,
There is a bit of inconsistency with the treatment of the intercept name for the posterior and for the priors.
The class `Intercept` becomes `b_Intercept` when one looks at the draws of the posterior. But the prior becomes "prior_Intercept". For other parameters, this is more consistent `sigma` -> `prior_sigma`, `b_anypredictor` -> `prior_b_anypredictor`. I think the `b` in `b_Intercept` is there because in the past the intercept was of class `b`, right?

It'll break some of my code, but I think `b_Intercept` should be `Intercept`, right?

**Comment by paul-buerkner** [comment]
b_Intercept is intentional. The reason it is prior_Intercept is because, by default, we specify priors on the intercept that results after centering all predictors, which is only afterwards corrected in generated quantities by computing b_Intercept. Does that answer your question. Or am I misunderstanding something?

**Comment by bnicenboim** [comment]
ooh, I see, the `prior_intercept` isn't necessarily the prior of the intercept of the model, right? Only if the predictors are centered.  Because what I get are the draws of the centered intercept, is that correct? If so, maybe `prior_centered_intercept` would be clearer...
But in any case, why is the `b` intentional? I understand that for the slopes, it makes it clear that they are of class "b", but the intercept is not of that class.

Feel free to close, I completely understand that you might not want to make changes in this, but I know that the centering of the intercept causes a lot of confusion. You could have two possible classes for the prior of the intercept "centered_intercept" or "intercept" making it transparent what the intercept is doing and then you could avoid having `0 + intercept` when someone doesn't want to center the intercept.

**Comment by paul-buerkner** [comment]
I see. FYI, an alternative is to use `bf(y ~ 1 + ..., center = FALSE)` to turn off centering without the `0 + Intercept` notation.
