### ISSUE TITLE
stanvar doesnt work with a vector in x or name

### ISSUE THREAD

**Issue by bnicenboim** [paul-buerkner/brms#1474]
Hi, 
I'm trying now stanvar, and I think I found a couple of bugs:

```r
stanvar(x = c("a" = 3))
# Error: 'c(a = 3)' is not a valid variable name in Stan.
```
But this works:
```r
y <- c("a" = 3)
stanvar(x = y)
```

Also this doesn't work:

```r
stanvar(x = c(3,5), name =c("a", "b"))
```
It only works with one var:
```r
stanvar(x = 3, name ="a")
# Error: Cannot coerce 'name' to a single character value.
```

version: brms_2.19.0

**Comment by bnicenboim** [comment]
oh, it also doesn't do what I was expecting!

```r
y <- c("a" = 3)
stanvar(x = y)
```
the name of the data variable is `y` and not `a`.


The same here:
```r
y <- c("a" = 3, "b"=5, c = "7")
stanvar(x = y)
```
it creates a vector called `y`, I was expecting 3 real types named `a`, `b`, and  `c`.

**Comment by paul-buerkner** [comment]
I understand, but this is not how `stanvar` is supposed to work. It will not pick up the names of a named vector. Instead, it will deparse the name of the object supplied to `x` if argument `name` is not given. We can discuss if this is the best approach, but at least I don't see any bug here.

**Comment by bnicenboim** [comment]
Yes, sorry, I understood that point, when I wrote the second message, but what about  `stanvar(x = c(3,5), name =c("a", "b"))`?

How should I pass something like `c("a" = 3, "b" = 5)` ?

So that it creates in stan:
```stan
transformed data {
real a = 3;
real b = 5;
}
```

for now I'm actually using `glue()` in `prior_string`, something like
```r 
a = 3
b = 5
c(prior_string(glue("Normal({a},2")), class = "b"),
prior_string(glue("Normal({b},2")), class = "Intercept"))
```

(And by the way, you could consider that `prior_string` would automatically use `glue`, but that's just an idea. )

(I'm preparing new teaching material, and trying new stuff  to make it as simple as possible for the students.)

**Comment by paul-buerkner** [comment]
stanvar(...) + stanvar(...) is the way to connect multiple stanvars. I like the glue idea and will think about it some more.

**Comment by bnicenboim** [comment]
oh, ok, I don't think that `stanvar(...) + stanvar(...) ` is in the documentation.
It would be nice to be able to pass `c("a" = 3, "b" = 5)` or maybe even better `list("a" = 3, "b" = 5)` to `stanvar`.

Regarding `glue`, I guess you don't need to limit it to a string, you could allow for `prior(normal({a},2))`, right?

**Comment by paul-buerkner** [comment]
Okay, then it needs to be added to the doc. stanvar is supposed to allow passing quite complicated structures, so vectorizing named vectors won't be sensible to support, because that would clash with a vector being passed to Stan as one argument. Perhaps list arguments could be supported, but again I have to think about it.

**Comment by paul-buerkner** [comment]
Improved the doc as discussed.
