### ISSUE TITLE
`posterior_predict` fails when using softplus link with Fréchet distribution

### ISSUE THREAD

**Issue by flaviomorelli** [paul-buerkner/brms#1475]
Hi Paul, 

I noticed that `posterior_predict` might not work correctly under certain circumstances when using the softplus link. More specifically, I was trying to get posterior predictions from a model with a Fréchet likelihood and a softplus link, but failed. The problem arises because `mu` can be exactly 0 when using a softplus, which doesn't happen with a log link. 

Looking at the `posterior_predict` for the [Fréchet distribution](https://github.com/paul-buerkner/brms/blob/7dc5755c656e3fddf8f5bd334cc0dfaba2dbac4a/R/posterior_predict.R#L612) the scale is:

```R
scale <- get_dpar(prep, "mu", i = i) / gamma(1 - 1 / nu)
```

If `mu` is 0, then `scale = 0`, and `rfrechet` will throw an error. I think this limits the usefulness of the softplus link, as it is very easy to have `mu = 0` when using new data for prediction. 

A quick fix would be to add a small epsilon to the numerator:
```R
eps <- .Machine$double.eps
scale <- (get_dpar(prep, "mu", i = i) + eps) / gamma(1 - 1 / nu)
```

Another option would be to add the epsilon directly to `mu` in the Stan code automatically when the softplus is used. This might make more sense, as for Fréchet the support is `x > 0`, if the minimum is assumed to be 0. 

I think this issue can potentially happen with all the distributions that use the softplus link (e.g., Weibull), but I haven't checked in detail. 

Thanks!

**Comment by paul-buerkner** [comment]
Thanks. Why do you think is the softplus link specifically so susceptible to this? 

We could perhaps directly define the softplus links with a + eps I think, both in Stan and in R.

**Comment by paul-buerkner** [comment]
After further investigation, I don't think I want to make any changes about this. The softplus link and response functions are already implemented in a numerically very stable way and I don't want to interfere with their behavior by adding additional very small numbers.
