### ISSUE TITLE
RDS files saved by brms grow increasingly larger when brm is called from inside a function

### ISSUE THREAD

**Issue by mawilson1234** [paul-buerkner/brms#1476]
I'm fitting some models in R using `brms` (thank you for this library!). The data are from an experiment with per-word reading times, and I want to fit the same kinds of models on data from different words, so I put the code to fit the models into a function that accepts the data to run the models on as an argument. I am saving the models to files so that I don't need to re-fit them for certain evaluations I'll be doing.

However, I've noticed that when I call the function that fits the models, the RDS files that `brm` saves grow larger and larger in size, even when the models should have the same number of parameters. I realize there will be a little variation due to the random nature of MCMC sampling, but what appears to be happening is that all of the data in the function environment at the point when the model is saved is somehow ending up in the RDS with the model object. For instance, the first model has 11 parameters (3 fixed effects, and 1 intercept + 3 fixed effects for each of 2 two random effects). This model takes up ~141 MB on disk. The second model has a different specification, but exactly the same number of parameters, and it takes up ~282 MB (2 x 141 MB) on disk. The third model has, again, the same number of parameters, and it takes up ~423 MB on disk (3 x 141 MB), and so on.

Since these models take a long time to fit, I've made a MWE that shows the same behavior on a smaller dataset with fewer samples drawn (`brms` will complain about the ESS, but the point is that the models finish quickly so that the sizes of the saved files can be inspected).
```r
library(brms)

fit.models <- function() {
	set.seed(0)
	m1 <- brm(
		formula = Sepal.Length ~ Sepal.Width,
		data = iris,
		cores = 4,
		chains = 4,
		iter = 100,
		file = 'm1-function.rds'
	)
	
	set.seed(0)
	m2 <- brm(
		formula = Sepal.Length ~ Petal.Length,
		data = iris,
		cores = 4,
		chains = 4,
		iter = 100,
		file = 'm2-function.rds'
	)
}

fit.models()

set.seed(0)
m1 <- brm(
	formula = Sepal.Length ~ Sepal.Width,
	data = iris,
	cores = 4,
	chains = 4,
	iter = 100,
	file = 'm1-global.rds'
)

set.seed(0)
m2 <- brm(
	formula = Sepal.Length ~ Petal.Length,
	data = iris,
	cores = 4,
	chains = 4,
	iter = 100,
	file = 'm2-global.rds'
)
```

Here's the result of running this on my computer:

- m1-function.rds: 1,064 KB
- m2-function.rds: 1,964 KB
- m1-global.rds: 1,117 KB
- m2-global.rds: 1,143 KB

Note that `m2-function.rds` is roughly twice as large as `m1-function.rds`, while `m1-global.rds` is about the same size as `m2-global.rds`.

I'm not sure if this is unique to `brms`. However, I ran a test using some simple vectors and lists with random numbers, and all the file sizes come out exactly the same, regardless of whether they were called from within the function (5,202 KB).
```r
test <- function() {
	x <- list(runif(1e6))
	saveRDS(x, 'x-function.rds')
	
	y <- list(runif(1e6))
	saveRDS(y, 'y-function.rds')
}

test()

x <- list(runif(1e6))
saveRDS(x, 'x-global.rds')

y <- list(runif(1e6))
saveRDS(x, 'y-global.rds')
```
So this doesn't seem to be default behavior in R for any objects saved to RDS. Whatever it is, something `brms` is doing with regards to how it saves files seems to be responsible. My guess is that it has something to do with how it decides what to include from the calling environment, but I don't know how to control that.

Is it possible for me to change this behavior somehow? Some of my actual models are quite large to begin with, which makes it unfeasible to keep storing what appears to be extra copies of all the previous models in the RDSs.

Edit: Whoops, forgot my session info:
```
R version 4.1.3 (2022-03-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252
[2] LC_CTYPE=English_United States.1252
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C
[5] LC_TIME=English_United States.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] brms_2.19.0 Rcpp_1.0.10

loaded via a namespace (and not attached):
 [1] Brobdingnag_1.2-9    jsonlite_1.8.4       gtools_3.9.4
 [4] StanHeaders_2.26.21  RcppParallel_5.1.7   threejs_0.3.3
 [7] shiny_1.7.4          posterior_1.4.1      distributional_0.3.2
[10] stats4_4.1.3         tensorA_0.36.2       pillar_1.9.0
[13] backports_1.4.1      lattice_0.20-45      glue_1.6.2
[16] digest_0.6.31        promises_1.2.0.1     checkmate_2.1.0
[19] colorspace_2.1-0     htmltools_0.5.5      httpuv_1.6.9
[22] Matrix_1.5-3         plyr_1.8.8           dygraphs_1.1.1.6
[25] pkgconfig_2.0.3      rstan_2.26.21        xtable_1.8-4
[28] mvtnorm_1.1-3        scales_1.2.1         processx_3.8.0
[31] later_1.3.0          emmeans_1.8.5        tibble_3.2.1
[34] bayesplot_1.10.0     generics_0.1.3       farver_2.1.1
[37] ggplot2_3.4.1        ellipsis_0.3.2       DT_0.27
[40] withr_2.5.0          shinyjs_2.1.0        cli_3.6.1
[43] crayon_1.5.2         magrittr_2.0.3       mime_0.12
[46] estimability_1.4.1   ps_1.7.3             fansi_1.0.4
[49] nlme_3.1-162         xts_0.13.0           pkgbuild_1.4.0
[52] colourpicker_1.2.0   prettyunits_1.1.1    tools_4.1.3
[55] loo_2.5.1            lifecycle_1.0.3      matrixStats_0.63.0
[58] stringr_1.5.0        V8_4.2.2             munsell_0.5.0
[61] callr_3.7.3          compiler_4.1.3       rlang_1.1.0
[64] grid_4.1.3           htmlwidgets_1.6.2    crosstalk_1.2.0
[67] igraph_1.4.1         miniUI_0.1.1.1       base64enc_0.1-3
[70] codetools_0.2-19     gtable_0.3.3         curl_5.0.0
[73] inline_0.3.19        abind_1.4-5          markdown_1.5
[76] reshape2_1.4.4       R6_2.5.1             gridExtra_2.3
[79] rstantools_2.3.0     zoo_1.8-11           bridgesampling_1.1-2
[82] dplyr_1.1.1          fastmap_1.1.1        utf8_1.2.3
[85] shinystan_2.6.0      shinythemes_1.2.0    stringi_1.7.12
[88] parallel_4.1.3       vctrs_0.6.1          tidyselect_1.2.0
[91] coda_0.19-4
```

**Comment by paul-buerkner** [comment]
Thank you for opening this issue and providing a reproducible example! I have observed this issue myself previously but was not motivated enough to dig deeper into it. You are right, it has something with how calls (or environments) are stored, but I don't know where brms actually stores this information in a way that R things it needs to hold onto all of the previous models in the environment if called inside a function. I will investigate this and let you know.

**Comment by mawilson1234** [comment]
I don't know if this will help track down the source of the issue, but the `butcher` library's `weigh` function indicates that the blame may lie with the way the formula is stored:
```
> weigh(m1.f.test)

# A tibble: 65 x 2
   object                     size
   <chr>                     <dbl>
 1 formula.formula        2.45
 2 fit                    2.40
 3 formula.family.linkfun 0.0175
 4 formula.family.linkinv 0.0175
 5 family.linkfun         0.0175
 6 family.linkinv         0.0175
 7 model                  0.00176
 8 data.Sepal.Length      0.00125
 9 data.Sepal.Width       0.00125
10 formula.family.ad      0.000504

# i 55 more rows
# i Use `print(n = ...)` to see more rows

> weigh(m2.f.test)

# A tibble: 65 x 2
   object                     size
   <chr>                     <dbl>
 1 formula.formula        4.83
 2 fit                    2.40
 3 formula.family.linkfun 0.0175
 4 formula.family.linkinv 0.0175
 5 family.linkfun         0.0175
 6 family.linkinv         0.0175
 7 model                  0.00176
 8 data.Sepal.Length      0.00125
 9 data.Petal.Length      0.00125
10 formula.family.ad      0.000504

# i 55 more rows
# i Use `print(n = ...)` to see more rows
```
Everything else is identical according to `which(weigh(m1.f.test)$size != weigh(m2.f.test)$size)`.

**Comment by paul-buerkner** [comment]
The problem is that, for some reason, R thinks it will need certain objects in the environment from which brms was called, but only if that enviroment is belonging to a function. So, in some sense, the function is kept apparently and thus all of the objects belonging to its environment need to be kept as well

This problem can be mitigated by stripping the formula off of it's environment and replacing it, say, with the global environment. I have done this in a branch (`issue-1476`), but this is only a temporary solution, since this prevents local functions to be used within the model. It needs to work without altering the formula environment. For example, in my tests, lm() didn't show the same behavior. Can you try out what happens with rstanarm models in the same situation?

**Comment by paul-buerkner** [comment]
Further experiments suggest that this is a general problem that occurs even when calling `lm()` or friends. Here is an example that makes this visible:

```R
fit.models.lm <- function() {
  # make the data bigger to see differences
  dat <- replicate(100, iris, FALSE)
  dat <- Reduce(rbind, dat)

  set.seed(0)
  m1 <- lm(Sepal.Length ~ Sepal.Width, dat)
  saveRDS(m1, 'm1-function.rds')

  set.seed(0)
  m2 <- lm(Sepal.Length ~ Sepal.Width, dat)
  saveRDS(m2, 'm2-function.rds')

  NULL
}

fit.models.lm()

# show that m1 is still stored inside m2
m2 <- readRDS('m2-function.rds')
env <- environment(m2$terms)
ls(env)
get("m1", env)
```

On disk, model `m2` will now be bigger than model `m1` because the former also stores the latter. To avoid, this, remove `m1` after it has been saved to disk but before calling `m2`. For example:

```R
fit.models.lm <- function() {
  # make the data bigger to see differences
  dat <- replicate(100, iris, FALSE)
  dat <- Reduce(rbind, dat)

  set.seed(0)
  m1 <- lm(Sepal.Length ~ Sepal.Width, dat)
  saveRDS(m1, 'm1-function.rds')
  rm(m1)

  set.seed(0)
  m2 <- lm(Sepal.Length ~ Sepal.Width, dat)
  saveRDS(m2, 'm2-function.rds')

  NULL
}

fit.models.lm()

# show that m1 is no longer stored inside m2
m2 <- readRDS('m2-function.rds')
env <- environment(m2$terms)
ls(env)
get("m1", env)
```

yields objects that of the same size on disk. The same works for models fitted with brms. So, in short, `rm()` will do the trick.

**Comment by wds15** [comment]
Reading the vignette from `butcher` on CRAN shows the same oddness from R. That is what the `butcher` package aims to solve. From this page here:

https://butcher.tidymodels.org

it looks as if one needs to make `butcher` aware of brms objects and then their cool stuff works nicely for brms objects as well, maybe?

Or maybe some of the `butcher` tools are already sufficient to deal with the bulk one gains from enclosing environments?

Interesting stuff.

**Comment by paul-buerkner** [comment]
Looks great! Indeed, we had to implement brms methods at least for `axe_env()`, which essentially would need to strip environments from all formulas hiding in `brmsformula` objects as well as in the `terms` attribute of the datset (after applying `model.frame`).

**Comment by mawilson1234** [comment]
I've figured out a workaround for my case that doesn't seem to require directly axing anything. If you loop over a list containing the parameters for the different models and run the models by passing the elements of that list to `brm`, the file sizes look right. Here's a MWE:
```r
library(brms)

fit.models.lapply <- function() {
    formulas <- list(
        Sepal.Length ~ Sepal.Width,
        Sepal.Length ~ Petal.Length
    )
    
    models <- lapply(
        seq_along(formulas),
        \(i) {
            m <- brm(
                formula = formulas[[i]], 
                data = iris,
                file = sprintf('m%d-lapply.rds', i)
            )
            return (m)
        }
    )
    
    return (models)
}

fit.models.serial <- function() {
    m1 <- brm(
        formula = Sepal.Length ~ Sepal.Width, 
        data = iris,
        file = 'm1-serial.rds'
    )
    
    m2 <- brm(
        formula = Sepal.Length ~ Petal.Length,
        data = iris,
        file = 'm2-serial.rds'
    )
    
    return (list(m1, m2))
}

fit.models.lapply()
fit.models.serial()
```
The result is that `m1-lapply.rds` and `m2-lapply.rds` are both about 2.1 MB (2,118 KB and 2,139 KB); in contrast, `m1-serial.rds` is about 2.1 MB (2,160 KB) but `m2-serial.rds` is about 4 MB (4,016 KB). Presumably, if other arguments to `brm` should differ between the models, one could just make a list of lists and run the models using `do.call(brm, args)` inside `lapply`. For this to result in the biggest savings, ideally in the function one should only do what is necessary to fit the models before using `lapply`, since otherwise I think it'll store anything in the local environment before that. But at least even if that happens, it'll be a constant increase in size instead of an exponential one.

**Comment by paul-buerkner** [comment]
can you try out what happens if you pass formulas as strings, "y ~ x"? I
think this may also work for your purpose.

Michael Wilson ***@***.***> schrieb am Mi., 5. Apr. 2023,
00:36:

**Comment by paul-buerkner** [comment]
I don't think so.

Michael Wilson ***@***.***> schrieb am Mi., 5. Apr. 2023,
18:26:
