### ISSUE TITLE
Predicted data not consistent with priors

### ISSUE THREAD

**Issue by tmalsburg** [paul-buerkner/brms#1486]
Sorry, this is a bit long.  Short version: Data generated with `posterior_predict.brmsfit` from just priors does not show the desired pattern.

Background: The man page of `set_prior` mentions that models with default intercept parameterization are reparameterized behind the scenes to have population-level predictors centered around zero (to improve sampling efficiency).  Consequently, the prior for the intercept needs to be set for the grand mean, not for the case where all user-defined predictors are zero.  However, if the predictors are centered, doesn't this mean that the priors for the population-level predictors *also* need to be specified for the reparameterized model?  (If yes, I think that should be made explicit in the man page.)

A case where this matters is a 2x2 design with treatment contrast where the original A:B models the difference between 2 (out of the 4) conditions, but A:B in the reparameterized model captures how the effect of one predictor differs between the levels of the other.  To investigate this, I wrote some code that generates data from just the priors and then examines that data to reverse-engineer how the priors are actually used in brm.  However, the predicted data does not have the properties that I expected and that's what this issue is about:

Simulated scenario: 2x2 design as above with predictors A and B, treatment-coded, and with Gaussian residuals. The Gaussian priors on all b use σ=0.1 except for the prior for A:B which has σ=1.  Predicted data: Without reparameterization, one would expect tightly distributed data in all conditions except in the condition with A=1, B=1 where it should be more spread-out.  However, if the priors are applied to the reparameterized model, the variance of `y.new` should be equal in all 4 conditions.  Results: In my simulation below, the variance *is* the same across all 4 conditions, however, it is also consistently too small and the intercept and condition means are too low (2.5 too low).  The output of the `summary` function also suggest that the b priors were *not* applied to the reparameterized model, I think, contrary to what I would have expected based on the man page of `set_prior`.

Perhaps I'm just making a stupid mistake here, but the `pp_check` plot below looks funky, the simulated condition means are systematically too low, and the by-condition standard deviations in the predicted data seem to be too low as well and inconsistent with the prior specification.  Perhaps `posterior_predict.brmsfit` doesn't take the reparameterization properly into account?

Code:

``` R
library(dplyr)
library(ggplot2)
library(patchwork)
library(brms)

set.seed(1)

n <- 1000
A <- c(rep(0:1, n))
B <- c(rep(0:1, each=n))
e <- rnorm(n, 0, 1)
y <- 300 + 10*A - 20*B + 30*A*B + e

d <- data.frame(y=y, A=A, B=B, e=e)

priors <- c(
  prior(normal(300, 0.1), class=Intercept),
  prior(normal( 10, 0.1), class=b, coef=A),
  prior(normal(-20, 0.1), class=b, coef=B),
  prior(normal( 30, 1.0), class=b, coef=A:B),
  prior(normal(  0, 0.1), class=sigma))

m.brms <- brm(y ~ A * B, d, gaussian(), priors, sample_prior="only")

prior_summary(m.brms)
summary(m.brms)

```

```
 Family: gaussian 
  Links: mu = identity; sigma = identity 
Formula: y ~ A * B 
   Data: d (Number of observations: 2000) 
  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
         total post-warmup draws = 4000

Population-Level Effects: 
          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
Intercept   297.50      0.29   296.93   298.08 1.00     3476     2345
A            10.00      0.10     9.81    10.19 1.00     4020     2784
B           -20.00      0.10   -20.19   -19.81 1.00     3883     2619
A:B          30.00      1.05    27.88    32.11 1.00     3426     2875

Family Specific Parameters: 
      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
sigma     0.08      0.06     0.00     0.22 1.00     2684     1551

Draws were sampled using sampling(NUTS). For each parameter, Bulk_ESS
and Tail_ESS are effective sample size measures, and Rhat is the potential
scale reduction factor on split chains (at convergence, Rhat = 1).
```

``` R
pp_check(m.brms)
```

![W5E97b](https://user-images.githubusercontent.com/3817450/234022975-23c016b4-12bf-4b65-8142-d8e68f95d96f.png)

``` R
d$y.new <- predict(m.brms)[,1]

d |>
  group_by(A, B) |>
  summarize(
    sd = sd(y.new),
    y.new = mean(y.new)) 
```

```
. + `summarise()` has grouped output by 'A'. You can override using the
`.groups` argument.
# A tibble: 4 × 4
# Groups:   A [2]
      A     B      sd y.new
  <int> <int>   <dbl> <dbl>
1     0     0 0.00160  297.
2     0     1 0.00154  277.
3     1     0 0.00161  307.
4     1     1 0.00167  318.
```

**Comment by paul-buerkner** [comment]
the intercept is not the intercept you think it is. see ?set_prior. to use
the original intercept use bf(formula, center = FALSE)

Titus von der Malsburg ***@***.***> schrieb am Mo., 24. Apr.
2023, 16:48:

**Comment by tmalsburg** [comment]
Thanks for the quick response.  I did read the man page of set_prior and I'm aware of the reparameterization.  But I don't think this explains the results I'm getting.

**Comment by paul-buerkner** [comment]
can you still try to see if this fixes things?

Titus von der Malsburg ***@***.***> schrieb am Mo., 24. Apr.
2023, 16:52:

**Comment by tmalsburg** [comment]
I think what you mean is that I try using `0 + Intercept` in the formula to prevent the reparameterization.  The results for that look closer to what I would expect. The only part that I find surprising is the very low within-condition standard deviations, these seems way too tight to me (~0.0016) given the sigma=0.1 of the priors.  Sees as if the uncertainty from the priors was not taken into account.  Another strange thing: `mean(d$y.new)` results in ~302.5, i.e. 2.5 too high (compare to the model *with* reparameterization where the intercept was 2.5 too low).
 
``` R
priors <- c(
  prior(normal(300, 0.1), coef=Intercept),
  prior(normal( 10, 0.1), class=b, coef=A),
  prior(normal(-20, 0.1), class=b, coef=B),
  prior(normal( 30, 1.0), class=b, coef=A:B),
  prior(normal(  0, 0.1), class=sigma))
m.brms <- brm(y ~ 0 + Intercept + A * B, d, gaussian(), priors, sample_prior="only")

summary(m.brms)
```

```
 Family: gaussian 
  Links: mu = identity; sigma = identity 
Formula: y ~ 0 + Intercept + A * B 
   Data: d (Number of observations: 2000) 
  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
         total post-warmup draws = 4000

Population-Level Effects: 
          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
Intercept   300.00      0.10   299.81   300.20 1.00     3612     2786
A            10.00      0.10     9.81    10.19 1.00     4184     3012
B           -20.00      0.10   -20.20   -19.80 1.00     4256     2514
A:B          30.00      1.04    28.06    32.08 1.00     4397     2330

Family Specific Parameters: 
      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
sigma     0.08      0.06     0.00     0.22 1.00     2577     1463

Draws were sampled using sampling(NUTS). For each parameter, Bulk_ESS
and Tail_ESS are effective sample size measures, and Rhat is the potential
scale reduction factor on split chains (at convergence, Rhat = 1).
```

``` R
pp_check(m.brms)
```
![pp2](https://user-images.githubusercontent.com/3817450/234046641-63dbf2b7-048a-4e17-b153-b0c014e6131b.png)


``` R
d |>
  group_by(A, B) |>
  summarize(
    sd = sd(y.new),
    y.new    = mean(y.new)) 
```

```
      A     B      sd y.new
  <int> <int>   <dbl> <dbl>
1     0     0 0.00164  300.
2     0     1 0.00149  280.
3     1     0 0.00169  310.
4     1     1 0.00165  320.
```

**Comment by paul-buerkner** [comment]
can you check the stan code on whether it is correct for your purpose? I
don't think there is a mistake in brms at this point. perhaps asking at the
Stan Forums could help?

Titus von der Malsburg ***@***.***> schrieb am Mo., 24. Apr.
2023, 17:46:

**Comment by tmalsburg** [comment]
Sorry,  but I'm afraid my Stan is not good enough to evaluate the code.  My impression is that the reparameterized model may have a problem on the Stan side because the estimate of the intercept is off by -2.5. The non-centered model-fit seems alright.

However, with both models I see issues in the predicted data (uncertainty is disregarded) and mean is off by 2.5 in the non-centered model. Are the predictions generated in Stan as well?  (I had a quick look at the code but couldn't figure it out.)

**Comment by paul-buerkner** [comment]
it is correct I think. the -2.5 is intended in the way as by default the
intercept and its prior is not the intercept you think it is. with regard
to uncertainty you have to take into account the scale of the data
variables you are evaluating not just priors. to me it looks all good. I
may be wrong of course.

Titus von der Malsburg ***@***.***> schrieb am Mo., 24. Apr.
2023, 18:20:

**Comment by tmalsburg** [comment]
> it is correct I think. the -2.5 is intended in the way as by default the intercept and its prior is not the intercept you think it is.

Okay, I assumed that the reparameterization was supposed to be completely transparent for the user (apart from the prior specification) and that the intercept would be put back to where it might be expected based on the contrast coding, but I see this assumption was wrong.  But what about the first pp_check plot, were we see an offset between predicted data and actual data? I'm pretty sure that's a bug caused by the reparameterization.  You definitely don't want your predicted data to be shifted wrt where it should be.  Ideally the pp_check plot should look the same for both models, no?

> with regard to uncertainty you have to take into account the scale of the data variables you are evaluating not just priors. to me it looks all good. I may be wrong of course.

Not clear to me how the predicted data could be so super tight when there is considerable uncertainty in the priors.  Seems inconsistent to me, but I may miss something important.

For your convenience, I cleaned up my code and put it in this gist, so you can play with it (if you want): https://gist.github.com/tmalsburg/55db4f89cb932cd5b91d51f89c161de8

Thanks for your input so far.

**Comment by paul-buerkner** [comment]
please continue this discussion on Stan discourse.

Titus von der Malsburg ***@***.***> schrieb am Mo., 24. Apr.
2023, 18:41:

**Comment by paul-buerkner** [comment]
All good. Glad you figured it out. :-)
