### ISSUE TITLE
Stratified Cox regression

### ISSUE THREAD

**Issue by wds15** [paul-buerkner/brms#1489]
It would be great to allow for Cox regression models which have a differing baseline hazard function for different strata of the data. Here is an example:

``` r
library(simsurv)
library(survival)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(brms)
#> Loading required package: Rcpp
#> Loading 'brms' package (version 2.19.0). Useful instructions
#> can be found by typing help('brms'). A more detailed introduction
#> to the package is available through vignette('brms_overview').
#> 
#> Attaching package: 'brms'
#> The following object is masked from 'package:survival':
#> 
#>     kidney
#> The following object is masked from 'package:stats':
#> 
#>     ar
# instruct brms to use cmdstanr as backend and cache all Stan binaries
options(brms.backend="cmdstanr", cmdstanr_write_stan_file_dir=here::here("brms-cache"))
# create cache directory if not yet available
dir.create(here::here("brms-cache"), FALSE)

set.seed(456456)

# simulated data from the rstanarm::stan_surv example
covs <- data.frame(id  = 1:200, trt = stats::rbinom(200, 1L, 0.5), l=rnorm(200)) %>%
    mutate(stratum=cut(l, c(-Inf, -0.5, 0.5, Inf)))
d1 <- simsurv(lambdas = 0.1,
              gammas  = 1.5,
              betas   = c(trt = -0.5, l=-0.2),
              x       = covs,
              maxt    = 5)
d1 <- merge(d1, covs)


## now fit the cox model with a different baseline hazard for each
## stratum:
fit_coxph <- coxph(Surv(eventtime, status) ~ trt + strata(stratum), data = d1)
summary(fit_coxph)
#> Call:
#> coxph(formula = Surv(eventtime, status) ~ trt + strata(stratum), 
#>     data = d1)
#> 
#>   n= 200, number of events= 120 
#> 
#>        coef exp(coef) se(coef)      z Pr(>|z|)  
#> trt -0.4335    0.6482   0.1897 -2.285   0.0223 *
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#>     exp(coef) exp(-coef) lower .95 upper .95
#> trt    0.6482      1.543    0.4469    0.9402
#> 
#> Concordance= 0.558  (se = 0.025 )
#> Likelihood ratio test= 5.33  on 1 df,   p=0.02
#> Wald test            = 5.22  on 1 df,   p=0.02
#> Score (logrank) test = 5.3  on 1 df,   p=0.02

## the equivalent in brms would be great to have:
fit_brm <- brm(eventtime | cens(1 - status) ~ 1 + trt,
            data = d1, family = brmsfamily("cox"), refresh=0, cores=4)
#> Start sampling
#> Running MCMC with 4 parallel chains...
#> 
#> Chain 3 finished in 0.4 seconds.
#> Chain 1 finished in 0.5 seconds.
#> Chain 2 finished in 0.5 seconds.
#> Chain 4 finished in 0.5 seconds.
#> 
#> All 4 chains finished successfully.
#> Mean chain execution time: 0.5 seconds.
#> Total execution time: 0.6 seconds.
summary(fit_brm)
#>  Family: cox 
#>   Links: mu = log 
#> Formula: eventtime | cens(1 - status) ~ 1 + trt 
#>    Data: d1 (Number of observations: 200) 
#>   Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
#>          total post-warmup draws = 4000
#> 
#> Population-Level Effects: 
#>           Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
#> Intercept     0.17      0.13    -0.09     0.42 1.00     3920     2592
#> trt          -0.51      0.19    -0.88    -0.14 1.00     3365     2644
#> 
#> Draws were sampled using sample(hmc). For each parameter, Bulk_ESS
#> and Tail_ESS are effective sample size measures, and Rhat is the potential
#> scale reduction factor on split chains (at convergence, Rhat = 1).
```

<sup>Created on 2023-04-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by wds15** [comment]
Maybe this is simpler to implement than it looks at first. Here is a toy example, which hacks the generated brms code such that we fit at the end one baseline hazard M-spline per stratum. This is what I am testing right now here. Things are still hard-coded, but I think it can be generalised easily:

```r
## This script needs brms 2.21.0. The code below runs on DaVinci with R 4.3.1
library(simsurv)
library(survival)
library(dplyr)
library(brms)
options(brms.backend="cmdstanr", cmdstanr_write_stan_file_dir=file.path("~/brms-cache"))
# create cache directory if not yet available
dir.create(file.path("~/brms-cache"), FALSE)

set.seed(456456)

# simulated data from the rstanarm::stan_surv example
covs <- data.frame(id  = 1:200, trt = stats::rbinom(200, 1L, 0.5), l=rnorm(200)) %>%
    mutate(stratum=cut(l, c(-Inf, -0.5, 0.5, Inf)), stratum_index=as.integer(stratum))
d1 <- simsurv(lambdas = 0.1,
              gammas  = 1.5,
              betas   = c(trt = -0.5, l=-0.2),
              x       = covs,
              maxt    = 5)
d1 <- merge(d1, covs)


## now fit the cox model with a different baseline hazards for each
## stratum:
fit_coxph <- coxph(Surv(eventtime, status) ~ trt + strata(stratum), data = d1)
summary(fit_coxph)

## the equivalent in brms would be great to have:
fit_brm <- brm(eventtime | cens(1 - status) ~ 1 + trt,
            data = d1, family = brmsfamily("cox"), refresh=0, cores=4)

summary(fit_brm)


## with a bit of extra magic code this should work ok:

## define more baselines
sv <- stanvar(d1$stratum_index, name="stratum") +
    stanvar(name="baseline_strata_simplex",
            scode="array[3] simplex[Kbhaz] sbhaz_stratum;",
            block="parameters") +
    stanvar(scode="lprior += dirichlet_lpdf(sbhaz_stratum[1] | con_sbhaz);", block="tparameters") +
    stanvar(scode="lprior += dirichlet_lpdf(sbhaz_stratum[2] | con_sbhaz);", block="tparameters") +
    stanvar(scode="lprior += dirichlet_lpdf(sbhaz_stratum[3] | con_sbhaz);", block="tparameters") +
    stanvar(scode="
// make baseline function stratum specific
for(n in 1:N) {
   bhaz[n] = Zbhaz[n] * sbhaz_stratum[stratum[n]];
   cbhaz[n] = Zcbhaz[n] * sbhaz_stratum[stratum[n]];
}
",
block="likelihood")

fit_brm_strata <- brm(eventtime | cens(1 - status) ~ 1 + trt,
                      stanvars=sv,
                      data = d1, family = brmsfamily("cox"), refresh=0, cores=4)

summary(fit_brm_strata)

## here one can check that we did indeed estimate per stratum a
## baseline hazard function on its own:
stancode(fit_brm_strata)
```

The relevant Stan code then becomes:

```stan
...
parameters {
  vector[Kc] b;  // regression coefficients
  real Intercept;  // temporary intercept for centered predictors
  simplex[Kbhaz] sbhaz;  // baseline coefficients
  array[3] simplex[Kbhaz] sbhaz_stratum;
}
transformed parameters {
  real lprior = 0;  // prior contributions to the log posterior
  lprior += dirichlet_lpdf(sbhaz_stratum[1] | con_sbhaz);
  lprior += dirichlet_lpdf(sbhaz_stratum[2] | con_sbhaz);
  lprior += dirichlet_lpdf(sbhaz_stratum[3] | con_sbhaz);
  lprior += student_t_lpdf(Intercept | 3, 1.5, 2.5);
  lprior += dirichlet_lpdf(sbhaz | con_sbhaz);
}
model {
  // likelihood including constants
  if (!prior_only) {
    // compute values of baseline function
    vector[N] bhaz = Zbhaz * sbhaz;
    // compute values of cumulative baseline function
    vector[N] cbhaz = Zcbhaz * sbhaz;
    // initialize linear predictor term
    vector[N] mu = rep_vector(0.0, N);
    
  // make baseline function stratum specific
  for(n in 1:N) {
     bhaz[n] = Zbhaz[n] * sbhaz_stratum[stratum[n]];
     cbhaz[n] = Zcbhaz[n] * sbhaz_stratum[stratum[n]];
  }

    mu += Intercept + Xc * b;
    for (n in 1:N) {
    // special treatment of censored data
      if (cens[n] == 0) {
        target += cox_log_lpdf(Y[n] | mu[n], bhaz[n], cbhaz[n]);
      } else if (cens[n] == 1) {
        target += cox_log_lccdf(Y[n] | mu[n], bhaz[n], cbhaz[n]);
      } else if (cens[n] == -1) {
        target += cox_log_lcdf(Y[n] | mu[n], bhaz[n], cbhaz[n]);
      }
    }
  }
  // priors including constants
  target += lprior;
}
...
```

BTW, the statement `stanvar(d1$stratum_index, name="stratum")` creates a data entry with the old array syntax:

```stan
  int stratum[200];
```

which looks like a bug to me as it should be the new array syntax here.

**Comment by paul-buerkner** [comment]
Just a quick note that we may want to add a new addition term `bhaz` or something for this purpose. This would replace the `bhaz` argument in the `cox()` family.

**Comment by paul-buerkner** [comment]
This feature is now implemented. Here is an example:

```R
fit <- brm(
  time | cens(censored) + bhaz(gr = sex) ~ age * sex + disease + (1|patient),
  data = kidney, 
  family = cox()
)
```

**Comment by JvH13** [comment]
Hi, I can't get the stratified cox regression working. This is my code (my model has more variables, but for the sake of space):

priors <- c(
  prior(normal(0, 5), class = "b")
)

bayesian_cox <- brm(
  formula = INTEGER_TIME | cens(IS_OBSERVED) + bhaz(gr = EVENT) ~
    var1 +
    var2 +
    var3 +
    (1 | sender.id) +                      
    (1 | receiver.tweet.id),                
  data = data,                                         
  family = cox(),                                      
  prior = priors,                                     
  chains = 3,                                          
  iter = 4000,                                         
  warmup = 2000,
  thin = 1,
  threads = threading(2),
  cores = parallel::detectCores() - 1,
  backend = "rstan",
  control = list(adapt_delta = 0.95, max_treedepth = 10)                   
)

I get this error message:
Compiling Stan program...
Error in stanc(file = file, model_code = model_code, model_name = model_name,  : 
  0
Syntax error in 'string', line 94, column 192 to column 197, parsing error:
   -------------------------------------------------
    92:    }
    93:    // compute partial sums of the log-likelihood
    94:    real partial_log_lik_lpmf(array[] int seq, int start, int end, data vector Y, data array[] int cens, data matrix Xc, vector b, real Intercept, data matrix Zbhaz, data matrix Zcbhaz, array[] sbhaz, data array[] int J_1, data vector Z_1_1, vector r_1_1, data array[] int J_2, data vector Z_2_1, vector r_2_1) {
                                                                                                                                                                                                         ^
    95:      real ptarget = 0;
    96:      int N = end - start + 1;
   -------------------------------------------------

Expected non-array type after "array" declaration.

I have tried different things: change the stratifying variable, different dataset, cmdstanr instead of rstan, etc. But this error keeps appearing. 

The grouping variable I am using right now is of type INT. I also tried another grouping variable that is of type NUM, but the same error appears. 

Do you have any idea how I can fix this?

**Comment by paul-buerkner** [comment]
Looks like a brms bug. Can you provide a minimal reproducible example for me?

**Comment by JvH13** [comment]
Dear Paul,

Thank you for your quick response and the great work you do by maintaining this package (forgot to mention that in my previous comment). I am having trouble recreating the problem with synthetic data. When I create a synthetic dataframe that looks like my real dataframe, the model runs fine with the bhaz funciton. Would it be fine to share a part of my dataframe here from which I know that running the model on it causes the error?

Best regards,

**Comment by paul-buerkner** [comment]
If I can easily download and use it, then yes :-)

**Comment by JvH13** [comment]
Please find attached an example dataframe (the first 5000 rows of my dataframe). This is the code I run:

library(foreach)
library(doParallel)
library(brms)
library(cmdstanr)

priors <- c(
  prior(normal(0, 5), class = "b")
)

# Fit the Bayesian Cox model with all fixed effects and random intercepts for sender and receiver
bayesian.cox <- brm(
  formula = INTEGER_TIME | cens(IS_OBSERVED) + bhaz(gr = EVENT) ~
    sender.outdegree +
    receiver.indegree +
    receiver.tweetcount +
    receiver.followerscount +
    #sender.followingcount +
    receiver.followingcount +
    receiver.ffratio +
    (1 | sender.id) +                      
    (1 | receiver.tweet.id),                
    data = data,                                        
    family = cox(),
    prior = priors,                                     
    chains = 3,                                          
    iter = 6000,                                         
    warmup = 2000,
    thin = 1,
    threads = threading(2),
    cores = parallel::detectCores() - 1,
    backend = "cmdstanr",
    control = list(adapt_delta = 0.95, max_treedepth = 10)                   
)

# Print a summary of the model
summary(bayesian.cox)

And this is the error I get:
Compiling Stan program...
Syntax error in 'C:/Users/J08D7~1.VAN/AppData/Local/Temp/Rtmp4I6NRQ/model-b54306e5302.stan', line 101, column 192 to column 197, parsing error:
   -------------------------------------------------
    99:    }
   100:    // compute partial sums of the log-likelihood
   101:    real partial_log_lik_lpmf(array[] int seq, int start, int end, data vector Y, data array[] int cens, data matrix Xc, vector b, real Intercept, data matrix Zbhaz, data matrix Zcbhaz, array[] sbhaz, data array[] int J_1, data vector Z_1_1, vector r_1_1, data array[] int J_2, data vector Z_2_1, vector r_2_1) {
                                                                                                                                                                                                         ^
   102:      real ptarget = 0;
   103:      int N = end - start + 1;
   -------------------------------------------------

Expected non-array type after "array" declaration.

mingw32-make: *** [make/program:66: C:\Users\J08D7~1.VAN\AppData\Local\Temp\Rtmp4I6NRQ\model-b54306e5302.hpp] Error 1

Error: An error occured during compilation! See the message above for more information.

I hope this information is sufficient. 

[example.csv](https://github.com/user-attachments/files/18734310/example.csv)

**Comment by paul-buerkner** [comment]
The issue only occured when using within-chain parallelization. It should now be fixed.

**Comment by JvH13** [comment]
Hi Paul,

Thank you for the quick response and the effort! Without using parallelization the example code + dataset do run the stratified cox regression for me, but when using within-chain parallelization it still gives me errors (but different ones this time):

Model executable is up to date!
Start sampling
Running MCMC with 3 chains, at most 7 in parallel, with 2 thread(s) per chain...

Warning: Chain 1 finished unexpectedly!

Warning: Chain 2 finished unexpectedly!

Warning: Chain 3 finished unexpectedly!

Warning: Use read_cmdstan_csv() to read the results of the failed chains.
Error: Fitting failed. Unable to retrieve the metadata.
In addition: Warning messages:
1: All chains finished unexpectedly! Use the $output(chain_id) method for more information.
 
2: No chains finished successfully. Unable to retrieve the fit. 

When I run this one ' read_cmdstan_csv()'  it gives me an error that argument 'files'  is missing. I am running this with brms version 2.22.9.

I guess this kind of error did not appear when you ran the example? Do you know what I am doing wrong? (Sorry for all the questions....)

**Comment by JvH13** [comment]
This is with cores = 1 (it is exactly the same error as before):

Model executable is up to date!
Start sampling
Running MCMC with 3 sequential chains, with 2 thread(s) per chain...

Warning: Chain 1 finished unexpectedly!

Warning: Chain 2 finished unexpectedly!

Warning: Chain 3 finished unexpectedly!

Warning: Use read_cmdstan_csv() to read the results of the failed chains.
Error: Fitting failed. Unable to retrieve the metadata.
In addition: Warning messages:
1: All chains finished unexpectedly! Use the $output(chain_id) method for more information.
 
2: No chains finished successfully. Unable to retrieve the fit. 

> read_cmdstan_csv()
Error in assert_file_exists(files, access = "r", extension = "csv") : 
  argument "files" is missing, with no default

**Comment by paul-buerkner** [comment]
I have now idea. Can you provide a clean reprex please?
