### ISSUE TITLE
stanplot failing

### ISSUE THREAD

**Issue by wfolta** [paul-buerkner/brms#149]
I'm running under RStudio 1.0.44, R version 3.3.2, on a beta of MacOS Sierra (Mac OS X 10_12_2), on a Touch Bar MacBook Pro, and getting an error when I try to stanplot a model. I have brms version 1.1.0, rstan Version 2.12.1. A `plot` works, but a `stanplot` fails:

```
foo
 Family: gaussian (identity) 
Formula: Petal.Width ~ Sepal.Width + Sepal.Length 
   Data: iris (Number of observations: 150) 
Samples: 4 chains, each with iter = 2000; warmup = 1000; thin = 1; 
         total post-warmup samples = 4000
   WAIC: Not computed
 
Population-Level Effects: 
             Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
Intercept       -1.57      0.33    -2.24    -0.90       2998    1
Sepal.Width     -0.48      0.07    -0.62    -0.33       3016    1
Sepal.Length     0.72      0.04     0.65     0.80       3057    1

Family Specific Parameters: 
      Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
sigma     0.39      0.02     0.35     0.44       2998    1

Samples were drawn using sampling(NUTS). For each parameter, Eff.Sample 
is a crude measure of effective sample size, and Rhat is the potential 
scale reduction factor on split chains (at convergence, Rhat = 1).
> plot (foo)
> stanplot (foo)
ci_level: 0.8 (80% intervals)
outer_level: 0.95 (95% intervals)
Error in if (e1$inherit.blank) return(e2) else return(e1) : 
  argument is of length zero
```

This just started recently, and I encountered a similar error today when using `rstanarm` to follow a webinar introducing `rstanarm`.

**Comment by jgabry** [comment]
This is because of a break in backwards compatibility in the latest ggplot2
release. The plot that's getting called in rstan is compatible with the new
ggplot2 on the develop branch of rstan but we're behind ggplot2 in our
release schedule.

The next rstanarm (actually just released) and brms (coming soon) will be
using the bayesplot package which also avoids this issue.

**Comment by paul-buerkner** [comment]
I actually released the new version of **brms** yesterday, but for some reason I forgot to update the `stanplot` method to use **bayesplot** at the backend... I will fix this today so that you can use the github dev version of **brms**.

**Comment by paul-buerkner** [comment]
The dev version of **brms** from github now uses **bayesplot** as the back-end of `stanplot`. As a side effect, it supports much more plots than before thanks to @jgabry implementing all those features in **bayesplot**.

**Comment by wfolta** [comment]
I loaded the dev version and all is well. It'll take a little getting used to -- and I've changed the default serif font -- but it's nice to have a standard set of plots across packages.

One thing I did notice is that the violin plot doesn't have values on the y axis. Not sure if it's meant to be just a visual comparison or if we might want to know the actual values.

Thanks!

**Comment by paul-buerkner** [comment]
I believe this is intentional since the parameters are not shown on the same scale, which makes values on the y-axis meaningless. You can get them back as follows:

```R
stanplot(fit, type = "violin", facet_args = list(scales = "fixed")) + 
  theme(axis.ticks.y = element_line(), axis.text.y = element_text())
```

**Comment by wfolta** [comment]
Yeah, it does look like adding y-axis values makes the display a lot less useful, since some violins get really crunched in comparison to others, making it hard to compare across chains.
