### ISSUE TITLE
Opaque error message when specifying priors with custom distributional families

### ISSUE THREAD

**Issue by SimonCMills** [paul-buerkner/brms#1490]
Hi Paul, 

I've been working with models that make use of custom distributional families, and found that there is a slightly opaque error message that triggers when you specify a prior for coefficients/classes that don't exist in the "mu" component. In the below code (largely ripped from your [custom families vignette](https://cran.r-project.org/web/packages/brms/vignettes/brms_customfamilies.html)), you can see that you get an error message about priors not corresponding to model parameters when a prior is specified for a coefficient/class that only exists "phi" component of the model. The reverse is however not true, and it will happily run if the coefficient exists in the "mu" component. 

```
library(brms)
data("cbpp", package = "lme4")

beta_binomial2 <- custom_family(
    "beta_binomial2", dpars = c("mu", "phi"),
    links = c("logit", "log"),
    lb = c(0, 0), ub = c(1, NA),
    type = "int", vars = "vint1[n]"
)

stan_funs <- "
  real beta_binomial2_lpmf(int y, real mu, real phi, int T) {
    return beta_binomial_lpmf(y | T, mu * phi, (1 - mu) * phi);
  }
  int beta_binomial2_rng(real mu, real phi, int T) {
    return beta_binomial_rng(T, mu * phi, (1 - mu) * phi);
  }
"

stanvars <- stanvar(scode = stan_funs, block = "functions")

# a model where the "period2" coefficient only exists in the distributional 
# component
prior_spec <- c(set_prior("normal(0,1)", coef = "period2"))
fit <- brm(
    bf(incidence | vint(size) ~ 1, phi ~ 1 + period), 
    data = cbpp,
    family = beta_binomial2, stanvars = stanvars,
    prior = prior_spec, empty=T
)
# error for specifying prior

# but if you move this coefficient to the "mu" component of the model, there is 
# no error
fit2 <- brm(
    bf(incidence | vint(size) ~ 1 + period, phi ~ 1), 
    data = cbpp,
    family = beta_binomial2, stanvars = stanvars,
    prior = prior_spec, empty=T
)
```

Error message (for fit):
```
Error: The following priors do not correspond to any model parameter: 
b_period2 ~ normal(0,1)
Function 'get_prior' might be helpful to you.
```

You can of course avoid the error this by ensuring that you are explicit that the coefficient exists in the "phi" component of the model with `set_prior("normal(0,1)", coef = "period2", dpar = "phi")`, but the error message and the fact that you need to be explicit about dpar is a little confusing until you have learnt about this behaviour. If it was possible to either avoid priors on dpar components triggering an error, or to more informatively error, that would be a great help. If you are happy with one of these options but don't have the time to implement it, I would be happy to have a rummage around in the `validate_priors` function to see if I can implement one of these changes myself.

Thanks, 
Simon

**Comment by paul-buerkner** [comment]
I think this is expected behavior. You need to specify dpar if you do not want the priors to affect the parameters on mu. See also get_prior. Or is there something I am overlooking?

**Comment by SimonCMills** [comment]
Hi Paul, ^ that behaviour is fine, the thing that I find confusing is that you can, for example, specify a class "b" prior (`set_prior("normal(0,1)", class= "b")`) but receive a warning message saying that this prior doesn't correspond to a model parameter, when it does.

e.g.
```
prior_spec <- c(set_prior("normal(0,1)", class = "b"))
fit <- brm(
    bf(incidence | vint(size) ~ 1, phi ~ 1 + period), 
    data = cbpp,
    family = beta_binomial2, stanvars = stanvars,
    prior = prior_spec, empty=T
)
```
with error:
```
Error: The following priors do not correspond to any model parameter: 
b ~ normal(0,1)
Function 'get_prior' might be helpful to you.
```
The error check flags it because the class "b" terms only occur in the dpar compnent of the model. 

I realise that this is a fairly niche issue so no worries if it doesn't warrant changing!
