### ISSUE TITLE
nested design difficulty and get_prior/set_prior mismatch

### ISSUE THREAD

**Issue by drjhw** [paul-buerkner/brms#1493]
I am trying to estimate a complicated unbalanced nested design of 13 treatments that represent 2 overall statuses - 3 control levels and 10 treatments. This unbalanced nested design is itself set in an unbalanced crossed design of experimental blocks (Runs) and people. Each person has only one treatment. Some people appear in several Runs. Each person who appears in any given Run contributes 20-100 observations to that Run. The attached pdf shows the unbalanced nested part of the design.

[unbalanced nested design.pdf](https://github.com/paul-buerkner/brms/files/11411857/unbalanced.nested.design.pdf)

I think the appropriate syntax is y ~ control/treated. This syntax generates the correct design in lme4 - and (despite the complexity and the fact that every element of the design is highly unbalanced) the analysis runs instantly:-

Linear mixed model fit by REML ['lmerMod']
Formula: log(y + 1) ~ status/group12 + age + sex + (1 | Run) + (1 | person)
   Data: adatx

REML criterion at convergence: -671.2

Scaled residuals: 
     Min       1Q   Median       3Q      Max 
-11.5288  -0.4963   0.0699   0.5694   3.9027 

Random effects:
 Groups   Name        Variance Std.Dev.
 person     (Intercept) 0.04141  0.2035  
 Run      (Intercept) 0.31861  0.5645  
 Residual             0.04302  0.2074  
Number of obs: 3230, groups:  patname, 52; Run, 18

Fixed effects:
                           Estimate Std. Error t value
(Intercept)                 6.81851    0.17988  37.907
statusTRTD                  0.01702    0.15370   0.111
age                         0.05423    0.02523   2.149
sexM                       -0.02596    0.07010  -0.370
statusTRTD:group12trtT1   -0.19152    0.15757  -1.215
statusTRTD:group12trtT2   -0.03298    0.23993  -0.137
statusCNTL:group12trtC1   -0.13863    0.18991  -0.730
statusTRTD:group12trtT3    0.12481    0.18310   0.682
statusCNTL:group12trtC2    0.10104    0.14424   0.701
statusCNTL:group12trtC0    0.44541    0.12077   3.688
statusTRTD:group12trtT4    0.28142    0.25350   1.110
statusTRTD:group12trtT5    0.17641    0.18376   0.960
statusTRTD:group12trtT6   -0.05097    0.19278  -0.264
statusTRTD:group12trtT7   -0.31144    0.23797  -1.309
statusTRTD:group12trtT8    0.01337    0.23277   0.057
statusTRTD:group12trtT9   -0.01294    0.15484  -0.084
statusTRTD:group12trtT10   0.29601    0.24831   1.192

Note that, as in the table in the pdf, there are 3 groups with status CNTL and 10 with status TRTD. So, lmer 'understands' what I want to do.

However, when I try to run the same design using brm, I encounter 2 problems.

First, I obtain estimates for non-existent cells (e.g. statusTRTD:groupC0):-

 Family: lognormal 
  Links: mu = identity; sigma = log 
Formula: y ~ status/group12 + age + sex + (1 | Run) + (1 | person)
         sigma ~ status + age + sex + (1 | Run) + (1 | person)
   Data: adatx (Number of observations: 3230) 
  Draws: 1 chains, each with iter = 1000; warmup = 0; thin = 1;
         total post-warmup draws = 1000

Group-Level Effects: 
~person (Number of levels: 52) 
                    Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
sd(Intercept)           0.45      0.00     0.45     0.45 1.00      967      952
sd(sigma_Intercept)     4.15      0.01     4.13     4.17 1.00      954      843

~Run (Number of levels: 18) 
                    Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
sd(Intercept)           0.67      0.00     0.66     0.67 1.00      966      880
sd(sigma_Intercept)     0.32      0.01     0.30     0.34 1.00      986      934

Population-Level Effects: 
                               Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
Intercept                          7.92      0.01     7.91     7.93 1.00      876      944
sigma_Intercept                    5.59      0.03     5.53     5.64 1.00      998      944
statusTRTD                        -0.22      0.00    -0.23    -0.21 1.00      898      935
age                                0.00      0.00    -0.00     0.01 1.00      998      915
sexM                              -0.22      0.00    -0.23    -0.21 1.00      931      983
statusTRTD:group12trtT1           -1.82      0.01    -1.84    -1.81 1.00     1057      908
statusCNTL:group12trtT1           -0.23     10.10   -21.26    19.89 1.00     1041      970
statusTRTD:group12trtT2           -1.76      0.06    -1.88    -1.64 1.00      976      986
statusCNTL:group12trtT2            0.07      9.93   -18.98    18.78 1.00      971      887
statusTRTD:group12trtT3           -1.46      0.03    -1.51    -1.41 1.00      856     1016
statusCNTL:group12trtT3           -0.10     10.57   -20.57    21.71 1.00      906      937
statusTRTD:group12trtT4           -1.28      0.04    -1.34    -1.21 1.00      943     1039
statusCNTL:group12trtT4            0.16      9.66   -19.52    18.27 1.00      910      876
statusTRTD:group12trtC1            0.31      9.94   -18.80    21.06 1.00      790      906
statusCNTL:group12trtC1           -0.94      0.01    -0.97    -0.92 1.00      994      983
statusTRTD:group12trtC0            0.53     10.02   -19.76    19.81 1.00      808      805
statusCNTL:group12trtC0           -0.64      0.01    -0.65    -0.63 1.00     1007     1072
statusTRTD:group12trtT5           -1.30      0.06    -1.42    -1.18 1.00      920      841
statusCNTL:group12trtT5            0.96     10.09   -17.76    22.00 1.00      925      939
statusTRTD:group12trtC2            0.41      9.92   -18.94    19.59 1.00      786      909
statusCNTL:group12trtC2           -1.01      0.01    -1.04    -0.99 1.00      908      907
statusTRTD:group12trtT6           -1.31      0.01    -1.32    -1.29 1.00      998      798
statusCNTL:group12trtT6           -0.11     10.11   -19.51    21.24 1.00     1089      944
statusTRTD:group12trtT7           -1.44      0.02    -1.48    -1.40 1.00      927     1007
statusCNTL:group12trtT7            0.28     10.35   -18.94    20.59 1.00     1044      941
statusTRTD:group12trtT8           -2.42      0.01    -2.44    -2.41 1.00      782      818
statusCNTL:group12trtT8            0.81     10.20   -18.57    20.54 1.00      927      944
statusTRTD:group12trtT9           -1.62      0.01    -1.64    -1.61 1.00      957      729
statusCNTL:group12trtT9           -0.17      9.87   -19.70    20.10 1.00      847      793
statusTRTD:group12trtT10          -1.19      0.01    -1.20    -1.17 1.00     1115      889
statusCNTL:group12trtT10          -0.03     10.40   -21.28    20.35 1.00      976      802
sigma_statusCNTL                  -3.29      0.03    -3.34    -3.24 1.00     1015      908
sigma_age                         -0.78      0.01    -0.80    -0.76 1.00     1031      897
sigma_sexM                         1.97      0.03     1.91     2.01 1.00     1015      713

Draws were sampled using variational(meanfield). 
(I can't get the analysis to run - yet - using algorithm='sampling')

The above output sets global priors for coefficients using set_prior('normal(0,10)', class='b'). If I do not set any priors, then the coefficients for the non-existent cells are enormous (30-40 digit) numbers!

So, I thought one way to eliminate the non-existent parameters could be to set them all to zero using set_prior('constant(0)'). I tried to do that. get_prior() delivers the following output (that tallies with the above result from the variational Bayes analysis):-

 get_prior(amf1, data=adatx)
                       prior     class                     coef   group resp  dpar nlpar lb ub       source
                      (flat)         b                                                              default
                      (flat)         b                       age                                (vectorized)
                      (flat)         b   statusTRTD:group12trtT1                                (vectorized)
                      (flat)         b   statusTRTD:group12trtT2                                (vectorized)
                      (flat)         b   statusTRTD:group12trtT3                                (vectorized)
                      (flat)         b   statusTRTD:group12trtT4                                (vectorized)
                      (flat)         b   statusTRTD:group12trtC1                                (vectorized)
                      (flat)         b   statusTRTD:group12trtC0                                (vectorized)
                      (flat)         b   statusTRTD:group12trtT5                                (vectorized)
                      (flat)         b   statusTRTD:group12trtC2                                (vectorized)
                      (flat)         b   statusTRTD:group12trtT6                                (vectorized)
                      (flat)         b   statusTRTD:group12trtT7                                (vectorized)
                      (flat)         b   statusTRTD:group12trtT8                                (vectorized)
                      (flat)         b   statusTRTD:group12trtT9                                (vectorized)
                      (flat)         b   statusTRTD:group12trtT10                               (vectorized)
                      (flat)         b                statusTRTD                                (vectorized)
                      (flat)         b   statusCNTL:group12trtT1                                (vectorized)
                      (flat)         b   statusCNTL:group12trtT2                                (vectorized)
                      (flat)         b   statusCNTL:group12trtT4                                (vectorized)
                      (flat)         b   statusCNTL:group12trtT3                                (vectorized)
                      (flat)         b   statusCNTL:group12trtC1                                (vectorized)
                      (flat)         b   statusCNTL:group12trtC0                                (vectorized)
                      (flat)         b   statusCNTL:group12trtT5                                (vectorized)
                      (flat)         b   statusCNTL:group12trtC2                                (vectorized)
                      (flat)         b   statusCNTL:group12trtT6                                (vectorized)
                      (flat)         b   statusCNTL:group12trtT7                                (vectorized)
                      (flat)         b   statusCNTL:group12trtT8                                (vectorized)
                      (flat)         b   statusCNTL:group12trtT9                                (vectorized)
                      (flat)         b   statusCNTL:group12trtT10                               (vectorized)
                      (flat)         b                     sexM                                 (vectorized)
 student_t(3, 1021.4, 628.7) Intercept                                                              default
      student_t(3, 0, 628.7)        sd                                                    0         default
      student_t(3, 0, 628.7)        sd                          person                    0    (vectorized)
      student_t(3, 0, 628.7)        sd                Intercept person                    0    (vectorized)
      student_t(3, 0, 628.7)        sd                              Run                   0    (vectorized)
      student_t(3, 0, 628.7)        sd                Intercept     Run                   0    (vectorized)
                      (flat)         b                                       sigma                  default
                      (flat)         b                      age              sigma             (vectorized)
                      (flat)         b                 statusTRTD            sigma             (vectorized)
                      (flat)         b                     sexM              sigma             (vectorized)
        student_t(3, 0, 2.5) Intercept                                       sigma                  default
      student_t(3, 0, 628.7)        sd                                       sigma        0         default
      student_t(3, 0, 628.7)        sd                          person       sigma        0    (vectorized)
      student_t(3, 0, 628.7)        sd                Intercept person       sigma        0    (vectorized)
      student_t(3, 0, 628.7)        sd                              Run      sigma        0    (vectorized)
      student_t(3, 0, 628.7)        sd                Intercept     Run      sigma        0    (vectorized)

So, I constructed constant(0) priors for all the non-existent elements of the design:-
myprior=c(set_prior('constant(0)',class='b',coef='statusCNTL:group12trtT1'),
set_prior('constant(0)',class='b',coef='statusCNTL:group12trtT2'),
set_prior('constant(0)',class='b',coef='statusCNTL:group12trtT3'),
set_prior('constant(0)',class='b',coef='statusCNTL:group12trtT4'),
set_prior('constant(0)',class='b',coef='statusCNTL:group12trtT5'),
set_prior('constant(0)',class='b',coef='statusCNTL:group12trtT6'),
set_prior('constant(0)',class='b',coef='statusCNTL:group12trtT7'),
set_prior('constant(0)',class='b',coef='statusCNTL:group12trtT8'),
set_prior('constant(0)',class='b',coef='statusCNTL:group12trtT9'),
set_prior('constant(0)',class='b',coef='statusCNTL:group12trtT10'),
set_prior('constant(0)',class='b',coef='statusTRTD:group12trtC0'),
set_prior('constant(0)',class='b',coef='statusTRTD:group12trtC1'),
set_prior('constant(0)',class='b',coef='statusTRTD:group12trtC2'),
set_prior('normal(0,10)',class='b'), set_prior('normal(0,10)',class='b',dpar='sigma'),
set_prior('normal(0,10)',class='sd',lb=0), set_prior('normal(0,10)',class='Intercept'))

But, now I encountered the second problem, which is that brm then denies that these parameters exist!

Error: The following priors do not correspond to any model parameter: 
b_statusCNTL:group12trtT1 ~ constant(0)
b_statusCNTL:group12trtT2 ~ constant(0)
b_statusCNTL:group12trtT3 ~ constant(0)
b_statusCNTL:group12trtT4 ~ constant(0)
b_statusCNTL:group12trtT5 ~ constant(0)
b_statusCNTL:group12trtT6 ~ constant(0)
b_statusCNTL:group12trtT7 ~ constant(0)
b_statusCNTL:group12trtT8 ~ constant(0)
b_statusCNTL:group12trtT9 ~ constant(0)
b_statusCNTL:group12trtT10 ~ constant(0)
b_statusTRTD:group12trtC0 ~ constant(0)
b_statusTRTD:group12trtC1 ~ constant(0)
b_statusTRTD:group12trtC2 ~ constant(0)
Function 'get_prior' might be helpful to you.

So, I'm stuck. But, it seems to me that brm is not behaving well. First, lmer can happily estimate the design, in spite of its complexity and unbalanced nature. Second, it seems very odd that brm generates the non-existent cells of the unbalanced nested design *and* get_prior() identifies the non-existent cells, *but* brm denies that those cells exist when I try to eliminate them via set_prior('constant(0)').

I suspect that there is one or more problems in brm's interpretation of the design syntax. So, I am sending this to the brms 'issues'

**Comment by paul-buerkner** [comment]
Hi, I would prefer if you are asking brms-related questions on Stan discourse.
