### ISSUE TITLE
Additional parameter initial value shows up in Wiener model

### ISSUE THREAD

**Issue by DominiqueMakowski** [paul-buerkner/brms#1499]
I'm not 100% sure it is a bug, but I thought I'll mention it nonetheless. 

Assuming this model:

```r
formula <- bf(rt | dec(response) ~ condition,
              bias ~ condition)

family <- wiener(link_bs = "identity",
                 link_ndt = "identity",
                 link_bias = "identity")
```

The posterior names are as follows:

```r
names(as.data.frame(m))
```
```
"b_Intercept"      "b_bias_Intercept" "b_condition"      "b_bias_condition" "bs"               "ndt"              "lprior"          "lp__"
```

In particular, there are 2 parameters for bias: the intercept `b_bias_Intercept` and the effect `b_bias_condition`.

Because the model essentially doesn't run and says that it's ill-conditioned (I tried setting very narrow priors but to no avail), I investigated the inits:

```r
str(m$fit@inits)
```
```
List of 9
 $ b               : num [1(1d)] 0
 $ Intercept       : num 0
 $ bs              : num 1
 $ ndt             : num 0.1
 $ b_bias          : num [1(1d)] 0
 $ Intercept_bias  : num 0.5
 $ lprior          : num -0.382
 $ b_Intercept     : num 0
 $ b_bias_Intercept: num 0.5
```

But here in the inits **bias has 3 parameters**: `b_bias`, `b_bias_Intercept` and `Intercept_bias`... And the two latter seem to be related (when I set the value for one of them it sets the same to the other it seems).

If it's not a bug, then what's the difference between `Intercept_bias` and `b_bias_Intercept`? Thanks a lot

**Comment by paul-buerkner** [comment]
That just has to do with centering of the intercepts. Please see ?set_prior for documentation. You can also check out what happens in the Stan code using make_stancode with a simple linear regression (centering is the same as for the diffusion models).
