### ISSUE TITLE
Not specifying trials in logistic regression with y = 0 has trials set to 0

### ISSUE THREAD

**Issue by lauken13** [paul-buerkner/brms#1501]
Bit of an edge case (and this is depreciated) but if you don't set the trials and have all 0s in your outcome, the trial number is set to 0 and the model returns the prior. 

Probably doesn't require a fix (perhaps a warning), but I thought I should add an issue in case! :)

`
mod2 <- brm(y |trials(1) ~ 1, family = binomial(link = "logit"), data = data.frame(y = rep(0,1000)), backend = "cmdstanr")`

vs 

`
mod2b <- brm(y  ~ 1, family = binomial(link = "logit"), data = data.frame(y = rep(0,1000)), backend = "cmdstanr")`

**Comment by paul-buerkner** [comment]
Thanks! I think it is just about time to disallow not specifying trials() in binomial families altogether. It has been deprecated long enough.

**Comment by paul-buerkner** [comment]
I now no longer allow not specifying trial in binomial models to avoid this and similar issues.
