### ISSUE TITLE
Group K-fold CV for multilevel model fails

### ISSUE THREAD

**Issue by fweber144** [paul-buerkner/brms#1503]
With the current GitHub version of brms (commit 9440d4593885e349e8a8e8b0e4922b08fb008e33), I receive an error in case of a K-fold CV where all observations from one group of a multilevel grouping variable are forced to be in the same fold:
```r
library(brms)
bfit <- brm(count ~ zAge + zBase*Trt + (1 | patient),
            data = epilepsy,
            family = poisson(),
            seed = 2052109,
            chains = 1,
            iter = 500,
            refresh = 0)
set.seed(4523)
folds_vec <- loo::kfold_split_grouped(K = 2, x = epilepsy$patient)
bkfold <- kfold(bfit, folds = folds_vec, seed = 6234)
```
The last line throws:
```
Error in x[, take_levels, drop = FALSE] : subscript out of bounds
```

**Comment by paul-buerkner** [comment]
Thanks. Will work on fixing it.

**Comment by paul-buerkner** [comment]
Should now be fixed. I introduced this problem accidentally when fixing other problems some weeks ago. I am glad you spotted it before release.
