### ISSUE TITLE
'beta' is not a valid parameter class for exgaussian distribution

### ISSUE THREAD

**Issue by timbeechey** [paul-buerkner/brms#151]
When attempting to specify a prior for class="beta" when using the exgaussian family I received the following error message:

> Error: 'beta' is not a valid parameter class.

Below are the brmsformula(), get_prior() and set_prior() calls I have used.

`b2_formula <- brmsformula(b2 ~ 1 + (1|environment) + (1|environment:speaker), sigma ~ (1|environment))`

`get_prior(b2_formula, data=dat, family=exgaussian(link="identity"))`

`b2_prior <- c(set_prior("normal(1,0)", class = "Intercept"),
                   set_prior("exponential(1)", class = "sd"), 
                   set_prior("exponential(1)", class = "beta"), 
                   set_prior("exponential(1)", class="sd", group="environment"),
                   set_prior("exponential(1)", class="sd", nlpar="sigma"))`

Could you please give me any advice on how to correctly specify this prior?

Thank you for your help.

**Comment by paul-buerkner** [comment]
I forgot to allow `beta` as a class in `set_prior`. Thanks for catching that. It should be fixed now.
