### ISSUE TITLE
Minor enhancements in Stan code in case of smoothed effects

### ISSUE THREAD

**Issue by fweber144** [paul-buerkner/brms#1514]
There are a few minor things that could be enhanced in the Stan code when using smoothed effects:

1. There are comments such as `// data for spline s(<variable_name>)` and `// parameters for spline s(<variable_name>)` which cause recompilations when using the same model for a different `<variable_name>` (via `update.brmsfit()`). I haven't tried it out whether the recompilations disappear when omitting these comments, but I think they should.
2. The comment in line `vector[Ks] bs; // spline coefficients` should read something like `// linear effects of splines`, I think.
3. Minor typo in comment `// standarized spline coefficients`: It should read `// standardized spline coefficients`, I think.

**Comment by fweber144** [comment]
Concerning 1.: I said

> I haven't tried it out whether the recompilations disappear when omitting these comments

but it's probably better to replace `spline s(<variable_name>)` with numbered spline terms (i.e., `spline term 1`, `spline term 2`, etc.) instead of omitting these comments.

**Comment by paul-buerkner** [comment]
Thank you! Will fix these issue before next release.
