### ISSUE TITLE
`kfold()` fails with current `master` version

### ISSUE THREAD

**Issue by fweber144** [paul-buerkner/brms#1524]
With the current GitHub version (commit 3091fdfaeebf659bf5a1619b3ee977ada47cff68), I get a failing call to `kfold()` (RDS files for the reprex: [kfold_reprex.zip](https://github.com/paul-buerkner/brms/files/11956954/kfold_reprex.zip)):
```r
# With version from commit 3091fdfaeebf659bf5a1619b3ee977ada47cff68 installed:
library(brms)
bfit <- readRDS("bfit.rds")
folds <- readRDS("folds.rds")
kfold_out <- kfold(bfit, folds = folds, seed = 1234)
```
where the last line throws:
```
Error in validate_data2(newdata2, bterms = bterms, ...) : 
  is.list(dots[[i]]) is not TRUE
```

**Comment by paul-buerkner** [comment]
Thank you. Fixed now.
