### ISSUE TITLE
brms causing r session aborted in r 4.3.1

### ISSUE THREAD

**Issue by chientilee** [paul-buerkner/brms#1528]
When I ran the same model using 4.2.1. It ran properly. Yet, after I updated R and R studio, it wouldn't work anymore. I have consulted to my university IT department to reinstall and make sure I choose the right version. Yet, we couldn't figure out why it won't work anymore.

#### Please note:
The brms issue tracker is reserved for bug reports and feature requests. brms-related questions should rather be asked on https://discourse.mc-stan.org/ in order to reach a wider community.
<img width="1682" alt="Screenshot 2023-07-06 at 3 55 08 PM" src="https://github.com/paul-buerkner/brms/assets/138906208/0a50f27e-6c46-4254-a02c-ed73f623e452">

**Comment by paul-buerkner** [comment]
Please ask brms related questions on Stan discourse. I believe there you will also find existing threads about your issue.
