### ISSUE TITLE
Conflicting prior bounds for beta parameter

### ISSUE THREAD

**Issue by aforren1** [paul-buerkner/brms#153]
It looks like `beta` is used in both the Wiener diffusion and exgaussian models, but they require different bounds (Wiener is constrained to [0, 1], and exgaussian is [0, inf)). How do you want to handle that, e.g. in [priors.R](https://github.com/paul-buerkner/brms/blob/master/R/priors.R#L877)?

**Comment by paul-buerkner** [comment]
The `beta` parameter in the wiener diffusion model is called `bias` to avoid this naming conflict. I am not totally consistent in naming auxilliary paramers. In the wiener model, they are named not as greek letters but as abbreviations of the meaning: `bs` for boundary separation, `ndt` for non-decision time and `bias` for the initial bias.

**Comment by aforren1** [comment]
Sorry for the noise, I experienced several successive thinkos. All good!
