### ISSUE TITLE
How/is it possible to obtain intermediate models using brm function in Bayesian modeling studies

### ISSUE THREAD

**Issue by ZePedroBranco** [paul-buerkner/brms#1530]
I'm doing a research study about bayesian modelling in R.
I'm using the brm function of brms package. Below is a part of my code where I obtain my model (chains=4, iter=2000).
However I have a doubt about the functionalities of the brm function. 
I would like to ask if it is possible to obtain and see the intermediate models of my final model, and if so, how can I obtain them.

```
Example of code is as follow:
.
.
.

prior_intercept <- prior(normal(0, 200), class=Intercept)
prior_x1 <- prior(normal(-10,5), class=b, coef=x1)
prior_x2 <- prior(normal(0,2), class=b, coef=x2)
prior_x3 <- prior(normal(-10,5), class=b, coef=x3)
prior_x4 <- prior(normal(0.8,0.1), class=b, coef=x4)

model <- brm(y ~ x1 + x2 + x3 + x4 ,data = tes1, prior = c(prior_intercept, prior_x1, prior_x2, prior_x3, prior_x4))

.
.
.
```

Thanks.

**Comment by jsocolar** [comment]
Cross-posted here

https://discourse.mc-stan.org/t/how-is-it-possible-to-obtain-intermediate-models-using-brm-function-in-bayesian-modeling-studies/32074
