### ISSUE TITLE
Feature request: rescor for Bernoulli models

### ISSUE THREAD

**Issue by jokroese** [paul-buerkner/brms#1533]
I am running a multivariate Bernoulli model where I would like to model the residual correlation between the dependent variables. From an error, I am aware that "_Currently, estimating 'rescor' is only possible in multivariate gaussian or student models_".

I am wondering: how would I go about extending brms to allow estimating 'rescor' for Bernoulli models?

**Comment by jokroese** [comment]
To motivate this, here is some example data and the model I would like to fit.

```{r}
# Set up simulated data
n <- 100
data <- tibble::tibble(
  x1 = rnorm(n, mean = 0, sd = 1),
  x2 = factor(sample(1:3, n, replace = TRUE))
)
correlation <- 0.7
cov_matrix <- matrix(c(1, correlation, correlation,
                       correlation, 1, correlation,
                       correlation, correlation, 1), nrow = 3, byrow = TRUE)
y <- MASS::mvrnorm(n, mu = c(0, 0, 0), Sigma = cov_matrix)
data <- data |>
  dplyr::mutate(
    y1 = ifelse(y[, 1] > 0, 1, 0),
    y2 = ifelse(y[, 2] > 0, 1, 0),
    y3 = ifelse(y[, 3] > 0, 1, 0)
  )

# Fit model
library(brms)
brm(bf(mvbind(y1, y2, y3) ~ 1 + x1 + (1 | x2)) + set_rescor(TRUE),
    data = data,
    family = bernoulli(link = "logit"))
```

**Comment by jokroese** [comment]
I checked out the generated Stan code of a Gaussian model with `set_rescor(TRUE)` and it looks like the residual correlation approach should work fine for Bernoulli models. Is that right?

If so, I assume calculating it for only Gaussian and Student models is a conscious design decision. Is there a reason to not calculate residual correlations for a Bernoulli model?

**Comment by paul-buerkner** [comment]
I think this is better suited for the Stan discourse forums since residual correlations are already possible for bernoulli models, just via correlated random effects. But their are cavets in identifying such models.
