### ISSUE TITLE
Cholmod error with pp_check with exgaussian

### ISSUE THREAD

**Issue by timbeechey** [paul-buerkner/brms#154]
When calling pp_check() for an exgaussian model I received the following error:

> Error in .local(x, y, ...) : Cholmod error 'X and/or Y have wrong dimensions' at file ../MatrixOps/cholmod_sdmult.c, line 90

The model specification was:

`formula <- brmsformula(b2 ~ 1 + (1|environment) + (1|repetition) + (1|environment:speaker), sigma ~ (1|environment))`

`m <- brm(formula, data=dat, family=exgaussian(link="identity"), prior=b2_prior)`

**Comment by paul-buerkner** [comment]
Thanks for reporting! It should be fixed now.
