### ISSUE TITLE
caching of cmdstan binaries broken with >= 2.20 (for cmdstan >= 2.29)

### ISSUE THREAD

**Issue by wds15** [paul-buerkner/brms#1544]
When using cmdstanr as backend with a configured caching directory for the binaries, then this used to avoid recompilation of the Stan programs. In newer brms version this behaviour is lost and one always recompiles the Stan programs. Here is small example:

```R
library(brms)
suppressPackageStartupMessages(library(here))
# instruct brms to use cmdstanr as backend and cache all Stan binaries
options(brms.backend="cmdstanr", cmdstanr_write_stan_file_dir=here("brms-cache"))
# create cache directory if not yet available
dir.create(here("brms-cache"), FALSE)

prior1 <- prior(normal(0,10), class = b) +
  prior(cauchy(0,2), class = sd)

fit1 <- brm(count ~ zAge + zBase * Trt + (1|patient),
            data = epilepsy, family = poisson(), prior = prior1)

## compiles the model AGAIN!!!
refit1 <- brm(count ~ zAge + zBase * Trt + (1|patient),
              data = epilepsy, family = poisson(), prior = prior1)


stan_model <- stancode(fit1)

stan_data <- standata(fit1)

## but ccmdstanr is not the issue here:
library(cmdstanr)

stan_file_1 <- write_stan_file(stan_model)
model_1 <- cmdstan_model(stan_file_1)

stan_file_2 <- write_stan_file(stan_model)
model_2 <- cmdstan_model(stan_file_2)

## the above does NOT recompile 
```

The issue appears to be here: https://github.com/paul-buerkner/brms/blob/ca12a94a39318c10cdebe96425dc578f9ad926ab/R/backends.R#L27

In the line below the `overwrite_file` flag is set to `TRUE`. This way the file is always overwritten and gets a new time-stamp which is newer than an already existing model binary and hence the recompile is triggered. Not sure why the file needs to be overwritten, but that should be avoided as this does otherwise force recompilation of already compiled models. Just run the above with brms 2.19 and then the recompilation of the model for the `refit` model does not happen.

**Comment by wds15** [comment]
Actually I am not sure about brms 2.19... I used cmdstan 2.28 up until now where this problem does not exist.

**Comment by luwidmer** [comment]
Seems to have been introduced with this commit in 2.17.0: https://github.com/paul-buerkner/brms/commit/70a1d44f84be605679f6cd10ec8536d8b9986939

**Comment by paul-buerkner** [comment]
@rok-cesnovar do you have a suggestion how to best resolve this? Also, do you remember why we put the cmdstan > 2.29 version check in that one place mentioned above?

**Comment by wds15** [comment]
In all honesty, I think that there is a strong rationale to drop this feature from brms to canonicalise the models. I mean, a user can put the respective stanc3 options in the `make/local` file of cmdstan (`STANCFLAGS`). To make it easier for users to enable this permanently a good place to do so is the `cmdstanr` documentation, for example.

The >= 2.29 version check ensures that in this case there does not exist any rstan version with this high version number, I think. This way you ensure that the canonicalisation is only done when it is safe to assume that rstan is not used, which was needed to export Stan functions from models build under cmdstan. However, this hack (convert a cmdstan model to rstan in order to expose the functions) is not needed any more, since we now have in cmdstanr 0.6.1 the functionality to export Stan user functions.

**Comment by paul-buerkner** [comment]
Just to make sure I understand correctly, you are suggesting to never canonicalize the model?

**Comment by wds15** [comment]
Yes, that is the suggestion here.

This would cause that the user gets to see warnings from stanc3 if using newer cmdstan installations, since brms is emitting oldish code which still works with oldish rstan.

Not sure if there are other arguments for canonicalization beyond that one avoids warnings.

The argument is that users can setup cmdstan such that the canonicalization is always done for the user in full automation (and not just when they use brms).

The argument to include this into brms is that this makes brms emit "nicer" Stan code without changing brms itself.

However, maybe brms can anyway be ported now to the new array syntax, which is the main motivation here (I guess)? Now rstan 2.26 is on CRAN such that the new array syntax is supported if I recall right.

**Comment by paul-buerkner** [comment]
Makes sense. brms is already using the new array syntax since recently so that should not be a concern anymore.

**Comment by paul-buerkner** [comment]
okay. I have commented out the relevant code for now. I did a CRAN release only recently so we have some time now to safely try it out on github and see if not canonicalizing causes any trouble.
