### ISSUE TITLE
`silent` behavior change with `cmdstanr` 0.6.1

### ISSUE THREAD

**Issue by grcatlin** [paul-buerkner/brms#1545]
Hi there,

Thanks so much for your work on `brms`, it's an invaluable tool in my toolbox and I really appreciate all of your effort to maintain it!

### reprex

I was messing around with differing versions of `cmstanr` and `brms` today trying to produce a reprex for a separate issue but found some odd behavior that I wasn't expecting when running a simple model. On my system, I no longer see the progress of sampling unless I specify `silent = 0` when I call to `brm()`.

```r
fit <- brms::brm(
    count ~ zAge + zBase * Trt + (1 | patient),
    data = brms::epilepsy,
    family = poisson(),
    backend = "cmdstanr",
    silent = 0
)
```

yields:

```
Compiling Stan program...
Start sampling
Running MCMC with 4 sequential chains...

Chain 1 Iteration:   1 / 1000 [  0%]  (Warmup) 
Chain 1 Iteration: 100 / 1000 [ 10%]  (Warmup) 
Chain 1 Iteration: 200 / 1000 [ 20%]  (Warmup) 
Chain 1 Iteration: 300 / 1000 [ 30%]  (Warmup) 
Chain 1 Iteration: 400 / 1000 [ 40%]  (Warmup) 
Chain 1 Iteration: 500 / 1000 [ 50%]  (Warmup) 
```

and so on whereas:

```r
fit <- brms::brm(
    count ~ zAge + zBase * Trt + (1 | patient),
    data = brms::epilepsy,
    family = poisson(),
    warmup = 500,
    iter = 1000,
    backend = "cmdstanr"
)
```

yields only:

```
Compiling Stan program...
Start sampling
```

However, if I use `rstan`:

```r
fit <- brms::brm(
    count ~ zAge + zBase * Trt + (1 | patient),
    data = brms::epilepsy,
    family = poisson(),
    warmup = 500,
    iter = 1000
)
```

It yields:

```
Compiling Stan program...
Start sampling

SAMPLING FOR MODEL 'anon_model' NOW (CHAIN 1).
Chain 1: 
Chain 1: Gradient evaluation took 8.2e-05 seconds
Chain 1: 1000 transitions using 10 leapfrog steps per transition would take 0.82 seconds.
Chain 1: Adjust your expectations accordingly!
Chain 1: 
Chain 1: 
Chain 1: Iteration:   1 / 1000 [  0%]  (Warmup)
Chain 1: Iteration: 100 / 1000 [ 10%]  (Warmup)
Chain 1: Iteration: 200 / 1000 [ 20%]  (Warmup)
Chain 1: Iteration: 300 / 1000 [ 30%]  (Warmup)
Chain 1: Iteration: 400 / 1000 [ 40%]  (Warmup)
```

and so forth. I'm assuming this has something to do with the latest release of `cmdstanr`? Not a huge deal - if this behavior stays the same can I specify to include `silent = 0` for any call to `brm()` somewhere in `options()`?

### `sessionInfo()` and the like

```r
library(brms)
library(cmdstanr)
cmdstanr::cmdstan_version()
```

```
[1] "2.33.1"
```

```r
sessionInfo()
```

```
R version 4.3.1 (2023-06-16)
Platform: x86_64-apple-darwin20 (64-bit)
Running under: macOS Sonoma 14.0

other attached packages:
[1] cmdstanr_0.6.1 brms_2.20.4    Rcpp_1.0.11
```

**Comment by paul-buerkner** [comment]
We are aware of this issue and working on a solution. The interaction between brms's silent argument and cmdstanr's different arguments to turn info on and off needs to be changed after changes to cmdstanr. We have yet to decide which is the best behavior for silent = 1.

**Comment by AdrianEcology** [comment]
Hi Garrett and Paul,

I recently encountered the same exact same issue and have been able to replicate Garrett's experience on my own machine. Is there an update on this bug? If not, a follow up on this thread would be greatly appreciated. I thought I had messed something up horribly after updating rtools and cmdstanr. Thanks!

Cheers,
Adrian

**Comment by paul-buerkner** [comment]
@jgabry What was our last status on this issue? Will there be changes in brms necessary or will all the changes be (or are already) done from the cmdstanr side?

**Comment by jgabry** [comment]
I think @andrjohns took care of it in https://github.com/paul-buerkner/brms/pull/1548. So I think we just forgot to close the issue, or are we still missing something?

**Comment by paul-buerkner** [comment]
True. Forgot about it. thank you! closing this now.
