### ISSUE TITLE
feature request: force compilation with threading enabled

### ISSUE THREAD

**Issue by jsocolar** [paul-buerkner/brms#1549]
We can shoehorn certain classes of non-factorizable models (e.g. occupancy models) into `brms` by evaluating the likelihood inside an unlooped custom family.  In order to take advantage of multiple threads per chain, one option is to write the stan code for the custom family using `reduce_sum` (this fails to use parallelization for computing the linear predictors, but still can use parallelization for evaluating the conditional likelihood).  However, to use such a custom family, we need a way to force the model to compile with threading enabled.  A hack using `cmdstanr` is to modify `make/local` as necessary at runtime, but if there's a possibility to implement a more streamlined solution that would be great!

**Comment by paul-buerkner** [comment]
Thanks. I will think about how to best approach this and add it in the new release.

**Comment by paul-buerkner** [comment]
This is now possible by using `threading(..., force = TRUE)`
