### ISSUE TITLE
add_criterion(, `loo`) with save_psis=TRUE doesn't do anything if save_psis=FALSE had been used before

### ISSUE THREAD

**Issue by avehtari** [paul-buerkner/brms#1553]
Following works,
```
fit <- brm(...)
fit <- add_criterion(fit, 'loo', save_psis=TRUE)
```
but the following leaves `psis_object` empty
```
fit <- brm(...)
fit <- add_criterion(fit, 'loo', save_psis=FALSE)
fit <- add_criterion(fit, 'loo', save_psis=TRUE)
```

**Comment by paul-buerkner** [comment]
add_criterion cannot check the details of the save loo object and whether new arguments make updating the saved object necessary. There are just too many options to handle here. To make sure the new one is added, use argument `overwrite = TRUE`.

**Comment by avehtari** [comment]
Could you extend the help text for `overwrite` to indicate that it can be useful if changing the options passed to the underlying functions? And mention in the `...` part to use `overwrite` if changing the options to be passed?

**Comment by paul-buerkner** [comment]
Yes. Will do

**Comment by paul-buerkner** [comment]
Done.
