### ISSUE TITLE
Error: Model predictions fail when model includes an interaction between monotonic effect and a scaled continuous variable

### ISSUE THREAD

**Issue by LukianAdams** [paul-buerkner/brms#1557]
I have a `brms` model which includes an interaction term between a monotonic effect and a scaled continuous variable. While the model runs without issue, when I try to compute predictions with `conditional_effects` or `posterior_epred` I get the following error:

`Error in data2draws(out$Csp[[i]], dim = dim) : length(x) %in% c(1, dim[2]) is not TRUE`

This error does not happen if I use a normal factor term, or do not scale the continuous variable. While I could scale the continuous variable before fitting the model, which is what I might do now, I like the convenience of the automatic back transformation that happens when including the scaling explicitly in the model specification.

Here is a reproducible example of the error:

```
set.seed(123)
df <- data.frame(Response = rnorm(100), 
                 OrderedFactor = factor(sample(c("Low", "Medium", "High"), 100, replace = TRUE), levels = c("Low", "Medium", "High"), ordered = TRUE), 
                 ContinuousVariable = runif(100))

#Monotonic effect x scaled continuous variable - Runs fine but produces an error making predictions
fit1 <- brm(Response ~ mo(OrderedFactor)*scale(ContinuousVariable),
            data = df,
            iter = 10, warmup = 5)

conditional_effects(fit1) #Error

#Normal factor x scaled continuous variable - No issues
fit2 <- brm(Response ~ OrderedFactor*scale(ContinuousVariable),
            data = df,
            iter = 10, warmup = 5)

conditional_effects(fit2)

#Monotonic effect x unscaled continuous variable - No issues
fit3 <- brm(Response ~ mo(OrderedFactor)*ContinuousVariable,
            data = df,
            iter = 10, warmup = 5)

conditional_effects(fit3)
```

**Comment by paul-buerkner** [comment]
scale() is a bit of complicated function to handle in predictions, so I recommend to avoid it's use in brms formulas. You can just apply this function in the pre-processing and then enter the scaled variable directly in the model formula. Let me see how difficult it is to fix this issue here at hand.

**Comment by paul-buerkner** [comment]
Interestingly, I cannot reproduce the error. Can you try this out with the latest CRAN or github version of brms?

**Comment by LukianAdams** [comment]
I just updated brms to the development version on github, and I still get the error, odd... As you say though, maybe I should just pre-process the variable, and back-transform after the fact.

Thanks for looking into this, I know it's a minor issue. Wrote it in a bit of a panic ten days out from my thesis due date struggling to get my predictions to work!
