### ISSUE TITLE
updating model from variational Bayes to NUTS sampling

### ISSUE THREAD

**Issue by drjhw** [paul-buerkner/brms#1564]
It would be simple to estimate the variational Bayes model (e.g. myVBfit=brm(mymodel, algorithm='meanfield', data=mydata, tol_rel_obj=1e-5, iter=1e5)) and then "update" it to use NUTS sampling. I need to run the vB analysis with a low value of tol_rel_obj, in order to obtain a sensible result. When I tried to update the vB analysis to use NUTS analysis (myNUTSfit=update(myVBfit, chains=4, cores=4, data=mydata, iter=2e3)), the analysis began sampling, but then threw an error that the tol_rel_obj is an unknown argument:-

Start sampling
Error in checkForRemoteErrors(val) :
4 nodes produced errors; first error: passing unknown argument: tol_rel_obj

Can you amend update(), so that the arguments in brm with variational Bayes do not prevent updating the model via NUTS sampling?

**Comment by paul-buerkner** [comment]
Hmm, I see the problem. Let me check how to best fix it.

**Comment by paul-buerkner** [comment]
fixed.
