### ISSUE TITLE
pkgdown website needs an update?

### ISSUE THREAD

**Issue by hansvancalster** [paul-buerkner/brms#1568]
Hi,

The website https://paul-buerkner.github.io/brms/index.html shows documentation for released version 2.16.2, but the current cran version is 2.20.4. For instance, if you look at the [changelog](https://paul-buerkner.github.io/brms/news/index.html), the latest update is 2021-08-23. Is the pkgdown update cycle broken? Note that you can setup a GitHub action to automate this process with usethis: https://usethis.r-lib.org/reference/use_pkgdown.html.

**Comment by paul-buerkner** [comment]
Hmm this is strange. Did I forgot to update for that long? Will check.

**Comment by paul-buerkner** [comment]
Should be updated now :-)
