### ISSUE TITLE
error in kfold help page regarding future

### ISSUE THREAD

**Issue by yanivabir** [paul-buerkner/brms#1569]
In the kfold.brmsfit help page, the following is given in the example of how to use future:

```
library(future)
plan(multiprocess)
kfold(fit1, chains = 1)
```

The call to `plan` results in an error. I believe it should be:
```
plan("multicore")
```

Note both the string and the different term.

In general, the help page is a little lacking as to how the parallelization works. It took me a lot of trial and error to figure out that `cores` is ignored, and that I should overwrite the `threads` argument from the original model to match the number of available cores per fold.

**Comment by paul-buerkner** [comment]
I hope the documention is now a bit better.
