### ISSUE TITLE
Missing dependencies on install from github source

### ISSUE THREAD

**Issue by tomwallis** [paul-buerkner/brms#157]
I've just been installing `brms` on a Windows 10 machine using 

```
devtools::install_github('paul-buerkner/brms')
```

Just wanted to point out that there were a couple of missing dependencies that weren't automatically flagged for download: `minqa`, `nloptr`. Not sure if there were others that were already installed on my system.

**Comment by paul-buerkner** [comment]
Hmm strange. Those are depenencies of lme4 (I import lme4 only to avoid
function masking possibly I undo this in the next release). I would expect
install_github to figure out itself which packages are required by packages
brms requires. So it is probably a problem of install_github.
Am 27.12.2016 12:15 schrieb "Tom Wallis" <notifications@github.com>:

**Comment by paul-buerkner** [comment]
I think you need to use `dependencies = TRUE` in the call to `install_github`. I now suggest that in the README of brms.
