### ISSUE TITLE
QR decomposition fails for cumulative logit models

### ISSUE THREAD

**Issue by josh-fiechter** [paul-buerkner/brms#1573]
When I try to fit a cumulative model with QR decomposition I get an error saying "Identifier XQ not in scope." It looks like the brms-generated Stan code doesn't actually calculate the requisite matrices. See example below. Thanks!

```
x <- rnorm(100)
y <- sample(c(1:7), 100, replace = TRUE)
dat <- data.frame(cbind(x,y))

bf1 <- bf(y~x, family = cumulative, decomp = "QR")
fit <- brm(bf1, data = dat)
```

Resulting Stan code:
```
transformed data {
  matrix[N, Kc] Xc;  // centered version of X
  vector[Kc] means_X;  // column means of X before centering
  for (i in 1:K) {
    means_X[i] = mean(X[, i]);
    Xc[, i] = X[, i] - means_X[i];
  }
}
```

**Comment by paul-buerkner** [comment]
Thank you! Fixed now :-)

**Comment by StuDonovan** [comment]
Fwiw I'm now running into similar bugs for all my models (intercept-only meta-analysis models with varying effects in levels and variance).

_Formula for model:_
`form <- bf(effect | se(se, sigma = TRUE) ~ 1 + (1 | study),
           sigma ~ 1 + (1 | study), decomp = "QR") + gaussian()`

_Add loo criterion:_
`model <- add_criterion(model, criterion = "loo", overwrite = TRUE, moment_match = TRUE)`

_Returns following error:_
`Compiling Stan program...
Error in stanc(file = file, model_code = model_code, model_name = model_name,  : 
  0
Semantic error in 'string', line 25, column 12 to column 14:
   -------------------------------------------------
    23:    vector<lower=0>[N] se2 = square(se);
    24:    // matrices for QR decomposition
    25:    matrix[N, Kc] XQ;
                     ^
    26:    matrix[Kc, Kc] XR;
    27:    matrix[Kc, Kc] XR_inv;
   -------------------------------------------------

Identifier 'Kc' not in scope. Did you mean 'N'?`

**Comment by paul-buerkner** [comment]
This case was not supposed to work at all. It now throws a more informative error message.
