### ISSUE TITLE
Issue post-processing model with with Cox family type

### ISSUE THREAD

**Issue by colinorourke** [paul-buerkner/brms#1580]
I've been working with a model fitted using the "cox" family type. It works great, but most functions such are predict, log_lik, conditional_effects, etc. don't seem to work with models of this type. I'm not sure, but this seems to be because the `bhaz_basis_matrix` function is checking for objects of class `mSpline`, but the class of an object create by the `mSpline` function from the `splines2` package seems actually to be `MSpline`.

A reprex for this error follows: 

``` r
library(brms)
#> Loading required package: Rcpp
#> Loading 'brms' package (version 2.20.4). Useful instructions
#> can be found by typing help('brms'). A more detailed introduction
#> to the package is available through vignette('brms_overview').
#> 
#> Attaching package: 'brms'
#> The following object is masked from 'package:stats':
#> 
#>     ar

# load data from survival package
dt = survival::bladder1

# fit survival model in brms
surv_mod = brm(
  stop | cens(status == 0) ~ size + number,
  data = dt,
  family = cox(link = "log"))

# try to get pointwise log-likelihoods, which result in error 
log_lik(surv_mod)
#> Error in bhaz_basis_matrix(y, args, basis = bs): inherits(basis, "mSpline") is not TRUE
```

<sup>Created on 2024-01-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by paul-buerkner** [comment]
Strange. Which version of the splines2 package are you using? Perhaps they have changed the object class names?

**Comment by paul-buerkner** [comment]
Okay, I can confirm that problem starts with splines2 version > 0.5.0. In the previous version I had (0.4.7) things were just working. Changing object class names is really not a good thing to do in any package... I will fix it in brms soon.

**Comment by paul-buerkner** [comment]
Should now be fixed.

**Comment by nstucke** [comment]
Hi @paul-buerkner! First, thank you for your work on this!

I have run into an issue similar to what's been described above. I am trying to calculate a Bayes Factor comparing the likelihood of the data under a null vs. alternative hypothesis using 2 Cox (survival) models. Using the bayes_factor() function, I am seeing the same error message described by @colinorourke above:

> Error in bhaz_basis_matrix(y, args, basis = bs) : 
>   inherits(basis, "mSpline") is not TRUE

A similar reprex to the above reproduces this error:
```
# load data from survival package
data <- survival::bladder1

# fit survival model in brms
surv_null_mod <- brm(
  stop | cens(status == 0) ~ size + number,
  data = data,
  family = cox(link = "log"))

surv_alt_mod <- brm(
  stop | cens(status == 0) ~ number,
  data = data,
  family = cox(link = "log"))

# try to calculate bayes factor...error 
bayes_factor(surv_alt_mod, surv_null_mod)
```

All of my packages/software are up to date:
splines2: version 0.5.1
brms: version 2.20.4
R: version 4.3.3 ("Angel Food Cake")

Could this be an object class names issue?

**Comment by paul-buerkner** [comment]
Update to the latest github version of brms

**Comment by paul-buerkner** [comment]
Did you restart R?

**Comment by nstucke** [comment]
Ooooof! That worked! Thank you so much, @paul-buerkner! Appreciate your time!
