### ISSUE TITLE
Setting bounds for imputed values in brms

### ISSUE THREAD

**Issue by gbiele** [paul-buerkner/brms#1581]
This is a feature request, because I think what I am trying to do is not possible in brms.

If one imputes data in brms, there is by default an implicit -Inf to +Inf pior on the imputed values.

It is already helpful that one can use the stanvar function to set a prior on imputed values, it would in many cases be useful to also set bounds on imputed values.

I checked the documentation for setting priors in brms, but as far as I understand it, `set_prior` or related functions cannot be used to set priors bounds on imputed values.

Is it hard or straight forward to add thet feature to specify bounds and priors for imputed values to brms?

**Comment by paul-buerkner** [comment]
Have you tried to add truncation bounds to the response variables with missing values?

**Comment by gbiele** [comment]
_Thanks_, this works.
It is a bit tricky, because one has to set the priors for the imputation model carefully, so that the the likelihood for the imputed values does not become 0, but it works.
To be more specific, if $x$ has missing data bound between 0 and 1 and we use an impuation model $x \sim + \alpha + \beta X$  the priors  for $\alpha$ and $\beta$ must be such that if we calculate `mu_x = a + b %*% X` then `normal_lpdf(x | mu_x, sigma_x)` is unlikely to become zero. In practice, this means that the prior for $\+alpha$ is something like $N(.5,.1)$ and the prior for $\beta$ has to induce a fair amount of regularisation. (how much obviously also depends on the particular data)
