### ISSUE TITLE
split_re_terms can throw a warning on r-devel

### ISSUE THREAD

**Issue by bgoodri** [paul-buerkner/brms#159]
A recent commit on r-devel deprecates `structure(NULL, ...)` and suggests `structure(list(), ...)`. This affects the return statement of `brms:::split_re_terms` and causes some tests that call `expect_silent` to fail. Before the last line of `split_re_terms`, I think you need to check that the first argument is not `NULL`.

**Comment by paul-buerkner** [comment]
Thanks. Indeed today travis failed because of it. I will fix this in the
next few days but will have to wait with a cran release until mid of
january.
Am 27.12.2016 8:56 PM schrieb "bgoodri" <notifications@github.com>:

**Comment by paul-buerkner** [comment]
Should be fixed now.
