### ISSUE TITLE
(potentially) Incorrect output of pvon_mises()

### ISSUE THREAD

**Issue by venpopov** [paul-buerkner/brms#1590]
This seems like a substantial bug with the output of pvon_mises(), i.e., the CDF of the von_mises distribution:

## brms::pvon_mises()

pvon_mises(mu,mu) should be 0, but it's not:

```{r}
i = 1:11
mus <- (2*i- 1-max(i))*pi/max(i)
pvm <- brms::pvon_mises(q=mus,mu=mus,kappa=4)
res <- data.frame(x=mus,mu=mus,p=pvm)
res
```

![image](https://github.com/paul-buerkner/brms/assets/12783882/979b3273-d4c0-4bc9-a74c-309d00737816)

The cdfs also look strange:

```{r}
plot_pvon_mises <- function(mu, kappa) {
  x = seq(-2*pi,2*pi,length.out=1001)
  plot(x,brms::pvon_mises(x,mu,kappa), type='l', ylab=c('von Mises CDF'))
  abline(v=mu,col='red')
  title(paste0("P(x = ",round(mu,2)," | mu=", round(mu,2), ") = ", round(brms::pvon_mises(mu,mu,kappa),4)))
}

par(mfrow=c(3,4))
i = 1:11
mus <- (2*i- 1-max(i))*pi/max(i)
p <- lapply(mus, plot_pvon_mises, kappa=4)
```

![image](https://github.com/paul-buerkner/brms/assets/12783882/49122ae9-1ead-41ec-be80-f4c878193561)

## Expected output

The cdf should be centered on my, and extend from mu-pi to mu+pi, resetting afterwards, but haaving the same shape regardless of  location. Here's  circular::pvonmises() for comparison:

```r
options(digits=3)
mus <- (2*i- 1-max(i))*pi/max(i)
pvm <- sapply(mus, function(mu) circular::pvonmises(q=mu,mu=mu,kappa=4))
res <- data.frame(x=mus,mu=mus,p=pvm)
res
```

![image](https://github.com/paul-buerkner/brms/assets/12783882/efa0e706-77e9-43b4-8c4d-ee5ab3be26d8)

```r
plot_pvon_mises <- function(mu, kappa) {
  x = seq(-2*pi,2*pi,length.out=1001)
  plot(x,circular::pvonmises(x,mu,kappa), type='l', ylab=c('von Mises CDF'))
  abline(v=mu,col='red')
  title(paste0("P(x = ",round(mu,2)," | mu=", round(mu,2), ") = ", round(circular::pvonmises(mu,mu,kappa),4)))
}

par(mfrow=c(3,4))
i = 1:11
mus <- (2*i- 1-max(i))*pi/max(i)
p <- lapply(mus, plot_pvon_mises, kappa=4)
```

![image](https://github.com/paul-buerkner/brms/assets/12783882/1907f6c8-1d3b-48fb-ba64-8cd54cfd8b9c)

**Comment by venpopov** [comment]
Hmm, stan produces the same results as brms. I guess both brms and stan assume that the cdf represents P(0 <= y <= mu). But that doesn't really make sense to me in a circular space 

![image](https://github.com/paul-buerkner/brms/assets/12783882/a58b21ca-8224-4143-b9db-17a644edc608)

**Comment by paul-buerkner** [comment]
I agree. The bounds should be documented properly.

**Comment by paul-buerkner** [comment]
added x bounds to the doc
