### ISSUE TITLE
posterior_predict / loo for cox model doesn't work

### ISSUE THREAD

**Issue by avehtari** [paul-buerkner/brms#1593]
The following errors
```
> data(kidney)
> fit1 <- brm(time | cens(censored) ~ age * sex + disease, family = cox(), data=kidney)
> fit1 <- add_criterion(fit1, criterion="loo")
Error in bhaz_basis_matrix(y, args, basis = bs) : 
  inherits(basis, "mSpline") is not TRUE
```

EDIT: changed the example to use open data

**Comment by paul-buerkner** [comment]
This is due to a recent update in the splines2 package, which I should have fixed in brms already. Can you try to run it again with the brms github version and the latest splines version from CRAN?

**Comment by avehtari** [comment]
I forgot I had installed brms from CRAN to check that a loo PR works with that, too. loo for cox works with github brms
