### ISSUE TITLE
Make shinystan optional

### ISSUE THREAD

**Issue by alyst** [paul-buerkner/brms#1595]
*shinystan* is a quite cumbersome dependency, but its use is isolated to `launch_shinystan.brmsfit()`.
Would be nice to make it optional.

**Comment by paul-buerkner** [comment]
Agreed. will make that change

Alexey Stukalov ***@***.***> schrieb am Mo., 12. Feb. 2024,
18:01:

**Comment by paul-buerkner** [comment]
done
