### ISSUE TITLE
Drop rows with missing values in the by variable.

### ISSUE THREAD

**Issue by rubenarslan** [paul-buerkner/brms#1598]
When I use `(1|gr(patient, by = Trt)`, brms tolerates some missing values. But if one patient has only missing values in `Trt`, we get an error message. The error message is actually pretty helpful (because it refers to a mismatch between dims declared and dims found. But (perhaps because brms says rows with NAs were excluded) it still took us a while to identify the missing values as the problem. 

Probably rows missing values in the `by` variable should just be dropped. This was was brms 2.20.4, but I didn't see a fix in the last commits.

``` r
library(brms)
epilepsy$Trt[which(epilepsy$patient %in% 1:2)] <- NA_real_
epilepsy$count[c(1,11)] <- NA_real_
fit3 <- brm(count ~ 1 + (1|gr(patient, by = Trt)), data = epilepsy)
#> Warning: Rows containing NAs were excluded from the model.
#> Start sampling
#> Error in eval(expr, envir, enclos) : 
#>   Exception: mismatch in dimension declared and found in context; processing stage=data initialization; variable name=Jby_1; position=0; dims declared=(59); dims found=(57) (in 'anon_model', line 12, column 2 to column 32)
#> failed to create the sampler; sampling not done
```

<sup>Created on 2024-02-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

brms also gives a helpful/friendly error if a group has multiple different values in the by variable, but not it if it has a mix of missing values and one non-missing value. Arguably, that scenario should also lead to an error, since the documentation says the group variable has to be nested in the by variable.

**Comment by paul-buerkner** [comment]
I think the problem is that brms keeps all the factor levels in factors intact, because we remove missing data *after* removing unused levels.

**Comment by paul-buerkner** [comment]
fixed.
