### ISSUE TITLE
Summary function with waic = TRUE

### ISSUE THREAD

**Issue by alireza202** [paul-buerkner/brms#16]
In large models, the Summary function takes a very long time (and tons of memory) to run, with "waic = TRUE" option. Why?

**Comment by paul-buerkner** [comment]
To compute the WAIC (or LOO), we have to compute the pointwise log-likelihood, which is a S x N matrix, where S is the number of samples and N is the number of observations. You can imagine that this matrix becomes huge for larger models, with respect to both computation time and memory, although I try to vectorize as much as possible.

That is why I put in the waic argument in summary to suppress waic computation if desired.

**Comment by alireza202** [comment]
Makes sense. Thanks.
