### ISSUE TITLE
loo moment_match fails for brms fits created with combine_models

### ISSUE THREAD

**Issue by avehtari** [paul-buerkner/brms#1603]
The problem and reproducible example provided in Stan discourse https://discourse.mc-stan.org/t/loo-moment-match-crashes-on-brms-fits-after-combine-models/34273

I looked at this, and the reason is that `.update_pars` in `loo_moment_match.R` tries to access `x$fit@sim$fnames_oi_old` which is not available in brms object created by `combine_models()` 

The relevant part in `loo_moment_match.R`
https://github.com/paul-buerkner/brms/blob/b92ed99e627b7ba0894803143aa6552a0d7a1131/R/loo_moment_match.R#L128C3-L128C74
```
new_draws <- named_list(x$fit@sim$fnames_oi_old, list(numeric(ndraws)))
```

EDIT: all the missing slots in `@sim` in brms object created by `combine_models()`
```
  .. .. ..$ pars_oi_old  : chr [1:8] "b" "Intercept" "sd_1" "z_1" ...
  .. .. ..$ dims_oi_old  :List of 8
  .. .. ..$ fnames_oi_old: chr [1:127] "b[1]" "b[2]" "b[3]" "b[4]" ...
```

**Comment by paul-buerkner** [comment]
Thanks! I don't fully understand your edit. Are you saying combine_models() already stores or does not store the relevant info already?

**Comment by avehtari** [comment]
Those slots are missing. See the discourse post for the failing example. moment_match works if you run the following lines to copy the missing info from one one model to the combined model
```
brm_fit$fit@sim$pars_oi_old <- brm_fit_c1$fit@sim$pars_oi_old
brm_fit$fit@sim$dims_oi_old <- brm_fit_c1$fit@sim$dims_oi_old
brm_fit$fit@sim$fnames_oi_old <- brm_fit_c1$fit@sim$fnames_oi_old
```

**Comment by paul-buerkner** [comment]
Thank you! Should be fixed now. :-)
