### ISSUE TITLE
kfold doc errors

### ISSUE THREAD

**Issue by avehtari** [paul-buerkner/brms#1605]
brms::kold doc https://paul-buerkner.github.io/brms/reference/kfold.html has an argument `folds` which can get value `balanced` and doc refers to `loo::kfold_split_balanced` linking to https://www.rdocumentation.org/packages/loo/versions/2.7.0/topics/kfold-helpers which doesn't include  `kfold_split_balanced`. Based on `loo` git commits, 5 years ago, `kfold_split_balanced` was replaced by `kfold_split_stratified` and `kfold_split_stratified` was replaced by `kfold_split_grouped`

**Comment by paul-buerkner** [comment]
Thanks. Will correct that.

**Comment by avehtari** [comment]
I'll add here a related doc issue. `kfold_predict()` doc https://paul-buerkner.github.io/brms/reference/kfold_predict.html says
> method: The method used to make predictions. Either "predict" or "fitted". See [predict.brmsfit](https://paul-buerkner.github.io/brms/reference/predict.brmsfit.html) for details.

but the `predict.brmsfit` doc does not say anything about `fitted`

**Comment by avehtari** [comment]
@paul-buerkner if you don't have time to update the document, can you comment on what these "predict" and "fitted" are supposed to do, or whether they work at all at the moment? I'm just confused how to use `kfold_predict`

**Comment by paul-buerkner** [comment]
predict is an old name for posterior_predict. fitted is an old name for posterior_epred. They change with with of the two methods we do predictions. I will update the names and doc accordingly tomorrow.

**Comment by paul-buerkner** [comment]
Pushed the changes to the method argument.

**Comment by paul-buerkner** [comment]
The "balanced" issue is just that the website needs an update but the current brms doc shows it correctly. Will update the website around the next brms release soonish.
