### ISSUE TITLE
Update readme and messages to take into account latest loo release

### ISSUE THREAD

**Issue by avehtari** [paul-buerkner/brms#1606]
- Update README to show the new loo output with 3 Pareto-k categories
- If the inference is run with less than about 2200 stored draws, k_threshold<0.7. If khats exceed this threshold, the diagnostic message could be modified to recommend in such cases first to run more iterations to get more than 2200 posterior draws. With more than 2200 stored draws the diagnostic message recommending moment_matching or reloo can stay the same

**Comment by avehtari** [comment]
I was going to use the sample specific threshold, and recommend more draws if the sample specific threshold is less than 0.7 and exceeded. The message you wrote is mixing two things (and has a typo)

**Comment by paul-buerkner** [comment]
Ah I see. That makes more sense. Where can I extract the sample specific threshold from?

**Comment by avehtari** [comment]
I can make a PR today

**Comment by paul-buerkner** [comment]
thanks!

Aki Vehtari ***@***.***> schrieb am Mo., 18. März 2024, 10:06:
