### ISSUE TITLE
moment_matching p_loo is wrong

### ISSUE THREAD

**Issue by avehtari** [paul-buerkner/brms#1609]
It is possible that this bug in `loo` but as the example is made with brms I make the issue now here, and after the problem has been located I'll move this if needed.

With `fit_betabinomial2b` from [Nabiximols case study](https://users.aalto.fi/~ave/casestudies/Nabiximols/nabiximols.html)
```
> fit <- add_criterion(fit_betabinomial2b, criterion="loo", save_psis=TRUE, overwrite=TRUE)
> loo(fit)
Computed from 4000 by 257 log-likelihood matrix.

         Estimate   SE
elpd_loo   -528.5 28.1
p_loo        90.4  9.8
...
```

But
```
fit <- add_criterion(fit_betabinomial2b, criterion="loo", save_psis=TRUE, moment_match=TRUE, overwrite=TRUE)
> loo(fit)
Computed from 4000 by 257 log-likelihood matrix.

         Estimate   SE
elpd_loo   -527.2 28.0
p_loo        80.0  9.3
...
```

The difference in `elpd_loo` is 1.3, and thus the difference in `p_loo` should be 1.3, too, but the difference is 10.4. The correct value for `p_loo` is 89.1.

I chose the above example as the discrepancy in `p_loo` is so big, but the error is also visible in the following example
```
> fit1 <- brm(count ~ zAge + zBase * Trt, data = epilepsy, family = poisson());
> fit1 <- add_criterion(fit1, criterion='loo', save_psis=TRUE)
> loo(fit1)
Computed from 4000 by 236 log-likelihood matrix.

         Estimate    SE
elpd_loo   -874.2  89.9
p_loo        22.0   5.4
...
> fit1b <- add_criterion(fit1, criterion='loo', save_psis=TRUE, moment_match=TRUE, overwrite=TRUE)
> loo(fit1b)
Computed from 4000 by 236 log-likelihood matrix.

         Estimate    SE
elpd_loo   -874.1  89.9
p_loo        21.3   4.8
...
```

**Comment by paul-buerkner** [comment]
Thanks! Will look into this! I agree with you that likely p_loo is not properly updated.

**Comment by avehtari** [comment]
I found the error and it's in `loo`, I'll move this there
