### ISSUE TITLE
Passing 'iter' to vb

### ISSUE THREAD

**Issue by alireza202** [paul-buerkner/brms#161]
I'm trying to change the `iter` default for `vb` from 10000 to higher, but when I pass it to `brm`, it doesn't pick it up. Looking at your code, I suspect it's being overlooked for non-sampling methods. Is that right?

**Comment by paul-buerkner** [comment]
It should be fixed in the dev version. Now, `iter` is passed to `rstan::vb` as well (and overwrites the default value).

**Comment by alireza202** [comment]
Thanks for the prompt fix!

**Comment by paul-buerkner** [comment]
Thank you for reporting the bug!
