### ISSUE TITLE
make restructure() also into a generic method?

### ISSUE THREAD

**Issue by venpopov** [paul-buerkner/brms#1611]
follow up on #1604. Would you be willing to also transform restructure() into a generic method? If so, I'd happy to put together a PR

**Comment by paul-buerkner** [comment]
yes that would be okay.

Ven Popov ***@***.***> schrieb am Mi., 6. März 2024, 17:54:

**Comment by venpopov** [comment]
How would you prefer the current method to be named, restructure.default or restructure.brmsfit?

Currently you have a check  `stopifnot(is.brmsfit(x))`. If restructure becomes restructure.default this will stay, but if restructure becomes restructure.brmsfit it will not be necessary.

**Comment by paul-buerkner** [comment]
*.brmsfit. No default method needed at this point I would think
