### ISSUE TITLE
Syntax error when adding a Gaussian Process term with cmdstanr

### ISSUE THREAD

**Issue by FredericBlum** [paul-buerkner/brms#1612]
This is a cross-post of an issue posted in [cmdstanr](https://github.com/stan-dev/cmdstanr/issues/926). According to a post there, the described problem is likely a brms issue:

> I think this might be a brms issue. If I'm not mistaken, with the latest versions of Stan that cmdstanr is using I think instead of `vector[] x` brms should write `array[] vector x`.

**Describe the bug**
When I am adding a gaussian process term within brms, I get a syntax error when I specify that I want to use cmdstanr as a backend. With rstan, the model runs through without problems.

**To Reproduce**
Consider the following brms model:

```
  brm(data=data,
      family=Gamma("log"),
      formula=Duration ~ 1 + utt_initial + word_initial + 
        gp(Longitude, Latitude, by=Macroarea, gr=TRUE),
      prior=c(prior(normal(4.5, 0.1), class=Intercept),
              prior(normal(6, 0.5), class=shape),
              prior(normal(0, 0.3), class=b),
              prior(exponential(12), class=sd),
              prior(lkj(5), class=cor),
              prior(normal(0, 1), class = sdgp)
      ),
      iter=50, warmup=25, chains=4, cores=4,
      control=list(adapt_delta=0.90, max_treedepth=10),
      seed=1,
      silent=0,
      backend='cmdstanr'
```

I receive the following error message:

```
Syntax error in '/var/folders/tp/38bwgqbn0_qgdjzjm2xkbbsm0000gp/T/RtmpaLy5IR/model_bbafd24c38b94b9192507696cc00ee47.stan', line 24, column 23 to column 24, parsing error:
   -------------------------------------------------
    22:     *   a vector to be added to the linear predictor
    23:     */
    24:    vector gp(data vector[] x, real sdgp, vector lscale, vector zgp) {
                                ^
    25:      int Dls = rows(lscale);
    26:      int N = size(x);
   -------------------------------------------------

An identifier is expected as a function argument name.

Error: Syntax error found! See the message above for more information.
```

**Expected behavior**
Model should run without problems.

**Operating system**
MacOS 14.3.1 (23D60)

**CmdStanR version number**
0.7.1

**brms version number**
2.20.4

**Comment by FredericBlum** [comment]
Jein; I get a different error:

```
   -------------------------------------------------
   206:    real Intercept;  // temporary intercept for centered predictors
   207:    vector<lower=0>[Kgp_1] sdgp_1;  // GP standard deviation parameters
   208:    vector<lower=0>[1] lscale_1[Kgp_1];  // GP length-scale parameters
                                      ^
   209:    // latent variables of the GP
   210:    vector[Nsubgp_1[1]] zgp_1_1;
   -------------------------------------------------

";" expected after variable declaration.
```

**Comment by paul-buerkner** [comment]
get you post a minimal reprex for me to try it out myself?

**Comment by FredericBlum** [comment]
Building the minimal example, I got thrown another error that asked me to run `rebuild_cmdstan()`. In the end, it seems like this was all that was necessary... I will stick to this for upcoming errors I guess (: Thanks anyway for your time, I will close the issue.
