### ISSUE TITLE
A better default prior for shape parameter of negative binomial

### ISSUE THREAD

**Issue by avehtari** [paul-buerkner/brms#1614]
The current default prior for `shape` parameter of `negbinomial` is `gamma(0.01, 0.01)` which having a lot of mass for near 0 values, that is, for high overdispersion. A more reasonable prior would be something close to the PC prior shown e.g. in https://dansblog.netlify.app/posts/2022-08-29-priors4/priors4.html#the-dream-pc-priors-in-practice. PC prior has parameter `lambda`, and I don't know yet what would be a good default for that, so I'm not yet suggesting the new default, but creating the issue so that I don't forget this. 

EDIT: removed wrong advice

**Comment by avehtari** [comment]
I looked again at this. Previously, I had missed that Dan used alpha=1/phi. I made [a notebook showing the steps going from Dan's results to PC prior for phi, and an inverse-gamma approximation that is easy to use](https://users.aalto.fi/~ave/casestudies/Priors/negbinomial_shape_prior.html). 

The recommended prior `inv_gamma(0.4, 0.3)` is shown with red dashed line and PC(lambda=1) prior with continuous red line
![image](https://github.com/paul-buerkner/brms/assets/6705400/6cd17840-1fc4-4807-9e3c-390d5bbfe7e7)

@paul-buerkner if you agree with the choice, I can make a PR, too

**Comment by paul-buerkner** [comment]
Looks good! A PR would be great!

**Comment by ASKurz** [comment]
I like this a lot. It has a nice intuitive appeal.

**Comment by paul-buerkner** [comment]
Quick question: I assume you are suggesting to just use `inv_gamma(0.4, 0.3)` as the general default, right? In this case, I can also quickly make the change if you are short on time.

**Comment by paul-buerkner** [comment]
Ah I see. Yes, for the doc it could be more sensible if you would add the info. Do you think you can do it in the next couple of days? I will try to submit the new brms version to CRAN this week.

**Comment by avehtari** [comment]
Hmm... I looked at the code, and I don't know how to make the change for the prior as if I now read it correctly, there are 4 distributions that have parameter `shape` and the default prior is set only based on the name of the parameter, but the family name doesn't matter. If you know how to fix it, then here is a proposal for the updated doc

```
#'   Further, family \code{student} needs the parameter
#'   \code{nu} representing the degrees of freedom of Student-t distribution.
#'   By default, \code{nu} has prior \code{gamma(2, 0.1)}, which is
#'   close to a penalized complexity prior (see Stan prior choice Wiki),
#'   and a fixed lower bound of \code{1}.
#'   Family \code{negbinomial} needs a \code{shape} parameter that has by
#'   default \code{inv_gamma(0.4, 0.3)} prior which is close to a
#'   penalized complexity prior (see Stan prior choice Wiki).
#'   Families \code{gamma}, \code{weibull}, and \code{inverse.gaussian},
#'   need a \code{shape} parameter that has a \code{gamma(0.01, 0.01)}
#'   prior by default.
```

I have updated Stan prior choice Wiki today to include the new advice for negbinomial

**Comment by paul-buerkner** [comment]
good point. let me think about it and see how i can fix it.

Aki Vehtari ***@***.***> schrieb am Mo., 18. März 2024, 18:13:

**Comment by paul-buerkner** [comment]
It's now working. I implemented a small internal feature that allows for family-specific default priors. I think it's actually kind handy more generally and I guess I will expand this to many other families at some point.

**Comment by LucianoDeBenedictis** [comment]
Would it make sense to have this as the default prior for `phi` in Beta regression too? For now, it seems to still be using `gamma(0.01, 0.01)`, which, as mentioned, has a lot of mass below 1.

**Comment by paul-buerkner** [comment]
Not sure. @avehtari do you have any intuition about it?

**Comment by avehtari** [comment]
This prior for the negative binomial is justified starting from the PC prior framework. PC prior framework is especially useful when some parameter value corresponds to a base model. In case of the negative binomial, the base model is Poisson. The PC prior is defined as prior on a divergence from the base model. For beta distribution, I don't see an obvious choice for a base model, and thus a different justification than PC prior would be needed for `phi` of beta distribution. Even if there would be an acceptable base model, then we would need to derive the corresponding PC prior and then find a reasonable approximation.

**Comment by anhsmith** [comment]
I find it more intuitively appealing to put a shrinkage prior on kappa = 1/sqrt(phi), instead of putting a prior directly on phi, as Dan Simpson outlined in his blog post. This way, as kappa -> 0, the model tends to Poisson. As kappa increases, we're getting more overdispersed and negative binomially. 

In brms:

```
formula_negbink <- bf(
  y ~ <mean formula>,
  nlf(shape ~ 1 / kappa^2),
  kappa ~ 1,
  family = negbinomial(link_shape = "identity")
)

priors_negbink <- c(
  prior(exponential(1), nlpar = "kappa", lb = 0)
  # ... plus your usual priors on the mean structure
)

fit_negbink <- brm(
  formula = formula_negbink,
  data    = your_data,
  prior   = priors_negbink
)
```

That `link_shape = "identity"` is important, because brms puts a log link on shape by default even under nlf(), so you need that or you'll silently fit shape=exp(1/kappa^2) instead. You can check this via `stancode()`. 

I checked this reparameterisation against a plain inv_gamma(0.4,0.3) fit on the same data afterward, and the posteriors and loo matched.
