### ISSUE TITLE
abstract function for reading cmdstanr csv output into a fit object for brms and export it

### ISSUE THREAD

**Issue by venpopov** [paul-buerkner/brms#1617]
Currently when the cmdstanr backend is used, after the sampling is done, the following lines of .fit_model_cmdstanr() read in the output files, and do necessary repairs and transformation to make an object to put in the fit slot of the brmsfit object:

```r
.fit_model_cmdstanr(....
  ## .... previous lines
  # not all metadata is not stored by read_csv_as_stanfit
  metadata <- cmdstanr::read_cmdstan_csv(
    out$output_files(), variables = "", sampler_diagnostics = ""
  )
  # ensure that only relevant variables are read from CSV
  variables <- repair_variable_names(metadata$metadata$variables)
  variables <- unique(sub("\\[.+", "", variables))
  variables <- setdiff(variables, exclude)
  # temp fix for cmdstanr not recognizing the variable names it produces  #1473
  variables <- ifelse(variables == "lp_approx__", "log_g__", variables)
  # transform into stanfit object for consistent output structure
  out <- read_csv_as_stanfit(out$output_files(), variables = variables)
  out <- repair_stanfit(out)
  # allow updating the model without recompilation
  attributes(out)$CmdStanModel <- model
  attributes(out)$metadata <- metadata
  out
}
```

Would you be willing to abstract these lines into a separate function and export it so that it can be used externally? It could look something like this (naming is just an example - currently misleading since the output is just the fit slot of a brmsfit object):

```r
#' @export
cdmstan_to_brmsfit <- function(files, exclude = "") {
  # not all metadata is stored by read_csv_as_stanfit
  metadata <- cmdstanr::read_cmdstan_csv(
    files, variables = "", sampler_diagnostics = ""
  )
  # ensure that only relevant variables are read from CSV
  variables <- repair_variable_names(metadata$metadata$variables)
  variables <- unique(sub("\\[.+", "", variables))
  variables <- setdiff(variables, exclude)
  # temp fix for cmdstanr not recognizing the variable names it produces  #1473
  variables <- ifelse(variables == "lp_approx__", "log_g__", variables)
  # transform into stanfit object for consistent output structure
  out <- read_csv_as_stanfit(files, variables = variables)
  out <- repair_stanfit(out)
  # allow updating the model without recompilation
  attributes(out)$CmdStanModel <- model
  attributes(out)$metadata <- metadata
  out
 }
 ```

and then the existing .fit_model_cmdstanr will be

```r
# previous lines here
   out <- do_call(model$sample, args)
  } else if (algorithm %in% c("fullrank", "meanfield")) {
    # vb does not support parallel execution
    c(args) <- nlist(iter, algorithm)
    out <- do_call(model$variational, args)
  } else {
    stop2("Algorithm '", algorithm, "' is not supported.")
  }
  
  out <- cdmstan_to_brmsfit(out$output_files(), exclude)
  
  if (empty_model) {
    # allow correct updating of an 'empty' model
    out@sim <- list()
  }
  out
```

This would be useful for example in [chkptstanr](https://github.com/venpopov/chkptstanr), where we currently use rstan::read_stan_csv to reading a stanfit object from cmdstanrr samples and put it in an empty brmsmodel. But as you know read_stan_csv is not very efficient. But if we use cmdstanr::read_cmdstan_csv, then the object is not in the right format. Having the above function exported would solve that problem

**Comment by venpopov** [comment]
Alternatively, just exporting the current `read_csv_as_stanfit` function would also be enough - the rest of the code is easy to reimplemented

**Comment by paul-buerkner** [comment]
abstracting this into its own function and exporting seems reasonable.
would you have time to make a PR?

Ven Popov ***@***.***> schrieb am Mo., 11. März 2024, 21:32:

**Comment by venpopov** [comment]
yup, can do that! Thanks. Preference on the function name?

**Comment by paul-buerkner** [comment]
just name it somehow right now and I can still edit the PR before merging

Ven Popov ***@***.***> schrieb am Mo., 11. März 2024, 22:24:
