### ISSUE TITLE
marginal_effects using wiener distribution

### ISSUE THREAD

**Issue by awellis** [paul-buerkner/brms#162]
The wiener distribution requires the  addition argument dec(), which in my case is called "response", e.g.

brmsformula(rt  |  dec(response) ~ 1 + condition + (1 + condition | subject), bias ~ 1 + condition)

When attempting to use marginal_effects() I get the following error message:

Error: The following variables are missing in 'data':
response

**Comment by paul-buerkner** [comment]
Thanks for reporting the bug. I will fix it.

**Comment by paul-buerkner** [comment]
It should be fixed now. :-)

**Comment by awellis** [comment]
wow, that was fast. Thanks!

**Comment by paul-buerkner** [comment]
It wasn't a complicated fix. Not sure why it slipped through my test cases.
