### ISSUE TITLE
Syntax Error still not fixed with latest BRMS from GitHub

### ISSUE THREAD

**Issue by rogerzzz123** [paul-buerkner/brms#1621]
#### Please note:
The brms issue tracker is reserved for bug reports and feature requests. brms-related questions should rather be asked on https://discourse.mc-stan.org/ in order to reach a wider community.

Hello there,

I am trying to fit a brms model with cmdstanr as backend so I can use threads for parallelization. I did some online search and realized a new release seems to resolve it but turns out it is still there. Can you please fix it? Also, are there any ways to bypass this error for now?

`Syntax error in var/folders/0d/ct1y3jz13yq8r33b3ppm2bsh0000gq/T/RtmprSUkCS/model_2b33810f077d369797883979939f454a.stan, line 18, column 31 to column 32, parsing error:
   -------------------------------------------------
    16:    }
    17:    // compute partial sums of the log-likelihood
    18:    real partial_log_lik_lpmf(int[] seq, int start, int end, data int[] Y, data matrix Xc, vector b, real Intercept, data int[] J_1, data vector Z_1_1, vector r_1_1) {
                                        ^
    19:      real ptarget = 0;
    20:      int N = end - start + 1;
   -------------------------------------------------

An identifier is expected as a function argument name.

Error: Syntax error found! See the message above for more information.`

**Comment by paul-buerkner** [comment]
Please use the latest github version from brms. I will work there. If not please provide a reprex together with your sessionInfo()
