### ISSUE TITLE
Document equivalence of re_formula = NA and re_formula = ~0 in predict methods

### ISSUE THREAD

**Issue by wpetry** [paul-buerkner/brms#1629]
Users can specify which group-level "random" effects to condition on when making predictions. `brms` is consistent with other mixed modeling packages (`lme4`, `rstanarm`, etc.) in allowing (i) a one-sided formula specifying the effects to condition on, (ii) `NULL` to condition on all effects in the model, or (iii) `NA` to include no group-level effects.

Like the other packages, `brms` accepts `re_formula = ~0` as an equivalent to `re_formula = NA`, but this is not documented for the `predict.brmsfit` method.

**Comment by paul-buerkner** [comment]
Fixed.
