### ISSUE TITLE
Error: Measurement error should be positive - but it is!

### ISSUE THREAD

**Issue by jebyrnes** [paul-buerkner/brms#163]
Hello! I've been working with the EIV code, and run into something curious.  When I run the following model:

```
 mod <- brm(slope | se(slope_se) ~ has_canopy*
                                   me(waves_scale,sdx = se_waves_scale) *
                                   me(temp_scale, sdx = se_temp_scale)*
                                   abs_lat_scale +
                                   (1|Study) + (1|ecoregion), 
                                   data=ksm_data)
```

I get the error

Error: Measurement error should be positive.

But

```
>  which( ksm_data$se_waves_scale <0)
integer(0)
>  which( ksm_data$se_temp_scale <0)
integer(0)
> which( ksm_data$slope_se <0)
integer(0)
```

Curious as to what's going on here.  Trying to come up with a reproducible example, but no dice yet.

**Comment by paul-buerkner** [comment]
Is one of your SDs exactly zero?

**Comment by jebyrnes** [comment]
*sigh* Yes. One was. Now it's just the normal issues of fitting such a wacky model. Ha. Thanks for the kick in the head!

**Comment by paul-buerkner** [comment]
You are welcome. ;-)
