### ISSUE TITLE
default prior for mu in von_mises with tan_half link

### ISSUE THREAD

**Issue by venpopov** [paul-buerkner/brms#1631]
The current default prior for mu in the von_mises distribution is the same as for every other distribution: 

`student_t(3, 0, 2.5)`

By default the von_mises() family uses a tan_half link for mu. This implies that the prior on the constrained space for mu is really weird and quite informative:

```
mu_unconstrained <- rstudent_t(1000000, 3, 0, 2.5)
mu <- 2 * atan(mu_unconstrained)
hist(mu, breaks=60, freq=F)
```

![image](https://github.com/paul-buerkner/brms/assets/12783882/526ac130-f26f-44fe-84cc-226cd283e710)

I woudl expect that the default prior should either be uniform on the constrained space, or ccentered around 0, rather than a highly informative bimodal prior.

If we want to have a uniform prior over -pi to pi on the constrained scale with the tan_half link, this is quite easy: we just need a student_t(1, 0, 1) prior on the unconstrained space. This is because if we assume a uniform prior over -pi to pi, and apply the inv_tan_half transformation, the jacobian adjustment gives us exactly the likelihood of a student T with 1 degree of freedom:

$$ f(x) = \frac{1}{\\pi (1+x^2)}$$

or simulated:

```
mu_unconstrained <- rstudent_t(1000000, 1, 0, 1)
mu <- 2 * atan(mu_unconstrained)
hist(mu, breaks=60, freq=F)
```

![image](https://github.com/paul-buerkner/brms/assets/12783882/8043edf5-e0ba-4cc9-ba9a-ca48885572e9)

Since you mentioned [here](https://github.com/paul-buerkner/brms/issues/1614#issuecomment-2006051851) that now family-specific priors are possible, I think this would be worth changing.

**Comment by paul-buerkner** [comment]
Nice! do you think you can make a PR using the new family specific prior
interface I added for negbinomial? see family-lists.R

Ven Popov ***@***.***> schrieb am Fr., 22. März 2024, 21:45:
