### ISSUE TITLE
"Error: 'p' must contain probabilities in (0,1)" in qstudent_t(1, df = 3), qskew_normal and a few others

### ISSUE THREAD

**Issue by venpopov** [paul-buerkner/brms#1637]
I was trying to visualize some distributions defined in brms, for example the student_t, via `ggdist` and the `distributional` package. For some distributions it works fine:

```r
library(ggplot2)
library(ggdist)
library(distributional)
library(brms)
dist1 <- dist_wrap('shifted_lnorm', package = 'brms')
ggplot() +
  stat_halfeye(aes(xdist = dist1))
```

![image](https://github.com/paul-buerkner/brms/assets/12783882/5935a9a4-9e1b-472d-9983-6f6ea9766572)

but for others such as student_t, skew_normal, there is an error:

``` r
dist1 <- dist_wrap('student_t', package = 'brms', df = 3)
ggplot() +
  stat_halfeye(aes(xdist = dist1))
#> Error in `layer_slabinterval()`:
#> ! Problem while computing aesthetics.
#> ℹ Error occurred in the 1st layer.
#> Caused by error:
#> ! 'p' must contain probabilities in (0,1)
```

<sup>Created on 2024-03-29 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

This is because for some distributions (but not all), the code [here](https://github.com/paul-buerkner/brms/blob/c9146b5c1199b7df6cb4c6512692c44dd0b69da2/R/distributions.R#L2555) gives an error if p=0 or p=1 in a quantile function. Is there a particular reason to reject these values rather than returning +- Inf, as for example stats::qt(p=1) does?

**Comment by paul-buerkner** [comment]
No particular reason, p=0 and p=1 should for allowed. Would it be possible for you to do a PR to fix this?

**Comment by venpopov** [comment]
sure
