### ISSUE TITLE
The centred intercept `Intercept` is exported 

### ISSUE THREAD

**Issue by stefanocoretta** [paul-buerkner/brms#1638]
Hi!

I just noticed on the latest release that the intercept calculated on the centred predictors `Intercept` is now exported together with the non-centred intercept `b_Intercept`.

```r
library(brms)

fit1 <- brm(
  count ~ Trt,
  data = epilepsy, family = poisson(),
  chains = 1
)

variables(fit1)
#> [1] "b_Intercept" "b_Trt1"      "Intercept"   "lprior"      "lp__"       
```

**Comment by paul-buerkner** [comment]
yes indeed. does this cause any problems?

Stefano Coretta ***@***.***> schrieb am Mo., 1. Apr. 2024,
19:05:

**Comment by stefanocoretta** [comment]
Not that I can see, is this intentional? I saw a discussion on the Stan forums from 2020 where you hinted at that being unintentional.

(From a pedagogical perspective, it just makes it a bit more difficult to explain the output of `variables()` without having to go into more details that I find necessary when introducing brms but it doesn't matter at the end of the day since I also skip lprior and lp 😃 )

**Comment by paul-buerkner** [comment]
It is intentional. Moment matching and bridgesampling methods need all the variables in the parameters block to be stored. And a lot of simple models store all such variables except for `Intercept`. So by storing it, I am trying to make these methos much less annoying to use, at least for myself :-D

**Comment by stefanocoretta** [comment]
Right! Yes that makes perfect sense. 😁 I'll just close this
