### ISSUE TITLE
Savage-Dickey density ratios aren't computed with QR decomposition

### ISSUE THREAD

**Issue by josh-fiechter** [paul-buerkner/brms#1640]
I've noticed that the `hypothesis` function returns NA for the `Evid.Ratio` with QR decomposition, even with specified priors. E.g.:
```
x <- rnorm(100)
y <- rnorm(100)
data <- data.frame(cbind(x, y))

bf1 <- bf(y~x, decomp = "QR")
prior1 <- prior(normal(0,1), class = b)
fit <- brm(bf1,
           prior = prior1,
           sample_prior = "yes",
           data = data)
hypothesis(fit, "x = 0")
## `Evid.Ratio` returns NA
```
The issue appears to stem from mismatched naming conventions for prior draws (i.e., `bQ_`) and final transformed parameter estimates (i.e., `b_`). Thanks for your help!

**Comment by paul-buerkner** [comment]
there is nothing really brms can do to fix this. it would be too much
effort to get it to work in this case. I recommend you perform bayes factor
computation via the bayes_factor method instead.

josh-fiechter ***@***.***> schrieb am Sa., 6. Apr. 2024,
23:40:
