### ISSUE TITLE
Add loo_epred

### ISSUE THREAD

**Issue by avehtari** [paul-buerkner/brms#1641]
`brms` has `loo_predict()` and `loo_linpred()`, but not `loo_epred()`. `loo_epred()` would be useful for various calibration plots. I have code for it and can make a PR. This requires adding `loo_epred` to `rstantools`, too.

Question: for multioutput models (at the moment interested in calibration checking for categorical and ordinal models), what should be the shape of the returned array? That is in which order to have the dimensions? Should `length(probs)>1` supported, too?

**Comment by avehtari** [comment]
`loo_epred` is now in `rstantools` (github)

**Comment by paul-buerkner** [comment]
Thank you! When will it be on CRAN? I would like to only merge loo_epred into brms once I can safely release the main branch on CRAN at any time.
