### ISSUE TITLE
Error: Internal renaming led to duplicated names

### ISSUE THREAD

**Issue by bhara033** [paul-buerkner/brms#1648]
#### Please note:
The brms issue tracker is reserved for bug reports and feature requests. brms-related questions should rather be asked on https://discourse.mc-stan.org/ in order to reach a wider community.

Hello Paul,

Hope you are doing well. I am fairly new to using "brms" but wanted to report, what I consider, a bug.
When I tried to run the model below, I got the following error:

_Error: Internal renaming led to duplicated names.
Occured for: 'var21', 'var22', 'var23', 'var24', 'var25', 'var26', 'var27', 'var28', 'var29', 'var21', 'var22', 'var23', 'var24', 'var25', 'var26', 'var27', 'var28', 'var29'_

I checked to make sure that my column names were, in fact, not duplicated. The error seems to be strange because I am able to run several other models using the same dataset without any issues.

I would be grateful if you could help me understand what's going on here.

My model:
```
result <- brm(
  bf(
    mvbind(var9, var10, var15, var16) ~ var2 + var13 + var14 + var19 + var21 + var22 + var23 + var24 + var25 + var26 + var27 + var28 + var29 + var30 + var34 + var48 + var49 + var53 + var54 + var55 + var58 + var61 + var63 + var64 + var89 + var90 + var91 + var92 + var93 + var94,
           zi ~ var2 + var5 + var114,
		   autocor = ~ar(time = var2, gr = var4:var3:var1)
    ),
  data = y,
  family = zero_inflated_negbinomial(),
  iter = 2000, # default 2000
  warmup = 1000, # default iter/2
  chains = 4, # default 4
  cores = 32,
  backend = "rstan",
  open_progress = TRUE,
  save_pars = save_pars(all = TRUE))
  )
```

Another issue I wanted to bring to your attention is that currently I am unable to use the option "**backend = "cmdstanr"**." The reason I wish to use this feature is to leverage parallel computing in "brms" (I am unsure if using the backend = "rstan" also achieves the same thing). Initially, I got an error saying I needed to install this additional R package called "cmdstanr." When I attempted to install it, the installer terminated with the following warning:

_Warning in install.packages :
  package ‘cmdstanr’ is not available for this version of R_

Could you please help me in addressing this issue? Thank you!

Regards,

Suhas

**Comment by paul-buerkner** [comment]
thanks. can you please provide a full minimal reprex for the error
(duplicated names) you encountered?

bhara033 ***@***.***> schrieb am Mi., 17. Apr. 2024, 18:14:

**Comment by paul-buerkner** [comment]
I suspect your questions may actually be better suited for the Stan
discourse forums

Paul Buerkner ***@***.***> schrieb am Mi., 17. Apr. 2024,
18:17:

**Comment by bhara033** [comment]
Sure, Paul! I will share a full reprex for the error with you soon. Thank you!

**Comment by bhara033** [comment]
I have invited you to collaborate on the "test" repository on GitHub. Thank you!

**Comment by paul-buerkner** [comment]
can you perhaps just post a minimal reproducible example here in this issue?

bhara033 ***@***.***> schrieb am Mi., 17. Apr. 2024, 20:51:

**Comment by bhara033** [comment]
The text file containing the R code is attached. Thank you!
[test.txt](https://github.com/paul-buerkner/brms/files/15025000/test.txt)

**Comment by bmfazio** [comment]
Hi, here's a minimal reprex. The error happens because `var2` is a factor, so the coefficient for level `"2"` clashes for the slope on `var22`. Should be solvable from the user side by renaming but a more informative error message may be useful.

```r
library(brms)
y = data.frame(
  var1 = 0,
  var2 = as.factor(1:3),
  var22 = 0
)
get_prior(bf(var1 ~ var2 + var22), data = y)
```

**Comment by bhara033** [comment]
Thank you, @bmfazio! Renaming var2 fixed the issue for me. Sorry for deleting the text file containing R code I posted earlier. I found some issues that I had to fixed. I can repost it if needed. Thank you!

**Comment by paul-buerkner** [comment]
Fixed.
