### ISSUE TITLE
Allow fixing auxiliary parameters to certain values

### ISSUE THREAD

**Issue by paul-buerkner** [paul-buerkner/brms#165]
Right now, auxiliary parameters are automatically estimated, without allowing users to fix them to certain values. This could be relevant, for instance, when fitting complicated drift-diffusion models requiring to fix the bias parameter to 0.5 in order to ensure model convergence.

**Comment by paul-buerkner** [comment]
Closed via f24da74

**Comment by jgabry** [comment]
Did you make it so that this is allowed and easily done for any model, or
just for special cases? I'd be careful about making it enticing for people
to fix auxiliary parameters in cases where it's not necessary. If you offer
it people will use it!

**Comment by paul-buerkner** [comment]
Currently, it is allowed for any auxiliary parameter (e.g., residual sd, shape, degrees of freedom parameters, or various parameters of the Wiener diffusion model). Generally, I try to give people more options, even if some may be only rarely useful, but documenting the concerns is definitely required in such cases. Thanks to your feedback I have amended the related doc stating to be very careful when applying this option (see commit 53b81e8).

**Comment by jgabry** [comment]
Looks good.

**Comment by paul-buerkner** [comment]
Thanks for commenting on this! Sometimes it is not easy to find the right balance between flexibility and safety and I am always grateful for feedback! :-)

**Comment by jgabry** [comment]
Definitely a hard balance to find. Partially because it's hard to know what users will actually do (we don't get to find out most of the time).
