### ISSUE TITLE
R2D2 does not account for scale of the data

### ISSUE THREAD

**Issue by n-kall** [paul-buerkner/brms#1655]
Currently, it seems that the R2D2 prior does not take into account the scale of the covariates. In other words, it seems to assume that the predictors (and outcome?) are standardized. However, I haven't found anywhere in the documentation that this is stated.

I think it could be helpful if this is added to the the documentation on R2D2, and perhaps it should be an option to scale the lambdas as in the R2D2M2 paper (equation 7).

**Comment by paul-buerkner** [comment]
Good point. Same goes for horseshoe actually, I think(?) An autoscaling option for the lambdas would indeed be nice. I assume the same thing could be easily done for horseshoe too. @avehtari what do you think?

**Comment by paul-buerkner** [comment]
I think we already have the autoscale option that currently scales (only) by sigma. I think making autoscale also scale according to the predictors' scales would be great.

**Comment by paul-buerkner** [comment]
I changed the documention to document that we do not automatically scale. I chose this approach because, given the flexibility of the prior, autoscaling of predictors will not always be possible and create awkward situations if we try to partially scale terms and partially not.
