### ISSUE TITLE
brm(..., silent = TRUE) is verbose?

### ISSUE THREAD

**Issue by JannikVindeloev** [paul-buerkner/brms#166]
Dear Paul,

According to the brms documentation:
silent	logical; If TRUE, informational messages of the compiler and sampler are suppressed.

However the following will print Warmup and Sampling information:

group <- rep(c("treat", "placebo"), each = 30)
symptom_post <- c(rnorm(30, mean = 10, sd = 2), rnorm(30, mean = 20, sd = 1))
dat1 <- data.frame(group, symptom_post)

fit <- brm(bf(symptom_post ~ group, sigma ~ group), 
            data = dat1,
            family = gaussian(),
            silent = TRUE)

is this on purpose?

/Jannik

**Comment by paul-buerkner** [comment]
Silent doesn't actuallly mean completely silent (on purpose). I will amend to doc a bit to make this clear.
You can try out what kind of messages is supresses by turning it off.
In order not to print most of the sampling stuff you are referring to, set `refresh = 0`.

**Comment by JannikVindeloev** [comment]
OK thanks
