### ISSUE TITLE
Code for threaded categorical outcome models does not work

### ISSUE THREAD

**Issue by chrishanretty** [paul-buerkner/brms#1664]
There is an error in the code generated for models of categorical outcomes. This error only arises when threading. Here is a MWE:

```
library(brms)
data("mtcars")
mtcars <- mtcars |>
    transform(cyl = factor(cyl))

n_chains <- 4
n_cores <- min(c(4, parallel::detectCores()))

### This runs (but is too short a run for any meaningful inferences)
mod <- brm(cyl ~ wt + disp,
           data = mtcars,
           family = categorical,
           chains = n_chains,
           cores = n_cores,
           iter = 250,
           warmup = 125)

### This does not run
mod <- brm(cyl ~ wt + disp,
           data = mtcars,
           family = categorical,
           chains = n_chains,
           cores = n_cores,
           threads = threading(2),
           iter = 250,
           warmup = 125)
```

The second call gives the error:

```
Error in stanc(file = file, model_code = model_code, model_name = model_name,  : 
  0
Semantic error in 'string', line 22, column 11 to column 17:
   -------------------------------------------------
    20:      int N = end - start + 1;
    21:      // joint regression coefficients over categories
    22:      matrix[Kc_mu6, ncat] b;
                    ^
    23:      // joint intercepts over categories
    24:      vector[ncat] Intercept;
   -------------------------------------------------

Identifier 'Kc_mu6' not in scope. Did you mean 'Xc_mu6'?
```

This is because the `int`s which give information on the number of population-level effects (the various `Kc_mu[category]`) are not passed to the likelihood function using for `reduce_sum`. 

AFAICT either the likelihood function must be rewritten to include the various `Kc_mu[category]` counters, or the function has to be rewritten using the existing matrices `Xc_mu[category]` and some creative use of `dim(...)`.

**Comment by paul-buerkner** [comment]
Thanks for reporting this issue! Does it occur in the latest github version of brms?

**Comment by chrishanretty** [comment]
> Thanks for reporting this issue! Does it occur in the latest github version of brms?

Yes, can confirm it's still a problem in 2.21.5.

**Comment by paul-buerkner** [comment]
Now fixed :-)

**Comment by chrishanretty** [comment]
> Now fixed :-)

Amazing, thanks!
