### ISSUE TITLE
More documentation for loo(reloo_args)

### ISSUE THREAD

**Issue by ASKurz** [paul-buerkner/brms#1665]
It would be helpful if the reference manual had an example of how to use the `reloo_args` argument within the `loo()` function. I find the guidance in the current version of the manual (2.21.0) a little opaque. 

For example, I recently fit a `brm()` model with some of the following settings.

```{r}
my_fit <- brm(
  <blah>,
  <blah>,
  <blah>,
  warmup = 500, iter = 1000, chains = 6, cores = 6,
  init_r = 0.2, seed = 123,
  control = list(adapt_delta = 0.99),
  save_pars = save_pars(all = TRUE)
)
```

After some high Pareto $k$ values and a failed attempt at the `moment_match` approach, `loo()` prompted me to use `reloo = TRUE`. Here was my attempt to retain some of my settings with `reloo_args`.

```{r}
my_loo <- loo(
  my_fit, 
  reloo = TRUE,
  reloo_args = list(
    warmup = 500, 
    iter = 1000, 
    chains = 6,
    cores = 6,
    seed = 123,
    init_r = 0.2,
    control = list(adapt_delta = 0.9))
)
```

After searching around online for a while, I'm not even sure if this approach was correct, and I bet a little more guidance in the reference manual could be of help.

**Comment by paul-buerkner** [comment]
Yes, your use of this argument is sensible. By default, brms will reuse (most of) the sampler arguments used in the original model. I updated the doc a bit.

**Comment by ASKurz** [comment]
Great; thanks!
