### ISSUE TITLE
misleading wording in multivariate model vignette?

### ISSUE THREAD

**Issue by soskuthy** [paul-buerkner/brms#1668]
I've read and re-read the multivariate model vignette a few times:

[https://cran.r-project.org/web/packages/brms/vignettes/brms_multivariate.html](https://cran.r-project.org/web/packages/brms/vignettes/brms_multivariate.html)

I keep getting confused by the following wording (emphasis mine):

> **Within** dams, tarsus length and back color seem to be negatively correlated, while **within** fosternests the opposite is true.

To me, this suggests the following. Take two birds (b1 and b2) from the same dam m1. b1 has a higher value for tarsus, and b2 a lower value for tarsus; we predict that they will have the opposite pattern for back colour (b1 lower for back and b2 higher for back). If we now take two birds (b3 and b4) from another dam, m2, a similar relationship should be seen, with a negative correlation between tarsus and color across b3 and b4. However, under this reading, the correlation does not tell us anything about how m1 and m2 relate to each other.

My understanding of how multivariate models are implemented in brms suggests that this is wrong: in fact, the correlation parameter tells us something about how tarsus and back relate to each other across m1 and m2, but not about b1 vs. b2 or b3 vs. b4 (that's reflected in the rescor parameter). Really, one way to think about the correlation parameter is as if we calculated mean back and tarsus values within each dam, and then looked at how those values are correlated (though, of course, the model does much more than this!).

A simple rewording would fix this problem:

> **Across** dams, tarsus length and back color seem to be negatively correlated, while **across** fosternests the opposite is true.

But it's also entirely possible that I'm misinterpreting this!

**Comment by paul-buerkner** [comment]
I think you are right. Thank you! I will fix it accordingly.
