### ISSUE TITLE
conditional_effects plot for monotonic predictors - lineplot vs catergorial plot

### ISSUE THREAD

**Issue by Famondir** [paul-buerkner/brms#1671]
Hi,
I fitted a model with a model with monotonic predictor:

```
binomial_base_model_fs_mono <- brm(
  data = success_moduls,
  n_Prüfungsstatus | trials(n_Prüfungen) ~ 1 + mo(Semester),
  family=binomial(link='logit'),
  cores = 4,
  sample_prior = TRUE,
  file = "models/binomial_base_model_fs_mono.rds"
)
```

When variable Semester is numeric (integers) the conditional_effects plot shows a linegraph what was not expected:

![image](https://github.com/user-attachments/assets/1a211ea4-bf7b-404d-b0fa-1493256b8914)

Is there a easy way to get a categorial plot with errorbars like this?:

![image](https://github.com/user-attachments/assets/956565cb-eab1-4c7c-965d-737d6e41df4a)

I had to refit the model and change the variable type to ordered to get this.

I tried to use the `categorical`, `ordinal` and `re_formula` options from conditional_effect but had no luck.

**Comment by paul-buerkner** [comment]
Hi, please ask brms related questions on Stan discourse.
