### ISSUE TITLE
Include Pathfinder in brm documentation?

### ISSUE THREAD

**Issue by athowes** [paul-buerkner/brms#1673]
Within the `@param algorithm` roxygen2 for `brms::brm` should it include `algorithm = "pathfinder"`?

https://github.com/paul-buerkner/brms/blob/29caa760b20a1c2969d98cc94c92072971a1c3dd/R/brm.R#L162

(By the way, is there any way to extract out a vector of the supported `algorithm` inputs?)

**Comment by paul-buerkner** [comment]
Thank you! Pathfinder is now added to the docs. You should be able to see the possible algorithms by typing in an invalid one and checking the error message.
