### ISSUE TITLE
Support moment matching LOO for LOO predictions

### ISSUE THREAD

**Issue by avehtari** [paul-buerkner/brms#1674]
Currently, moment matching can be used only to improve pointwise  values.

LOO predictions are useful for examining coverage of LOO predictive intervals and uniformity of LOO-PIT. It would be useful to support moment matching for these, too.

Instead of storing moment matching transformed draws or transformation parameters (which may take lot of memory), I think re-computing moment matching when doing LOO predictions could be fast enough, especially if the moment matching would be done only for those LOO folds that originally had high Pareto-k value.

**Comment by paul-buerkner** [comment]
This should now be working :-)
