### ISSUE TITLE
R2D2 help file request

### ISSUE THREAD

**Issue by jpkrooney** [paul-buerkner/brms#1675]
Hi,
A small request. It is not clear to me whether the R2D2() function uses the R2D2 or the R2D2M2 prior under different model specifications. Can you to helpfile a list of which prior version is used for which models please? Thank you.

**Comment by paul-buerkner** [comment]
Where exactly do you see the difference?

**Comment by jpkrooney** [comment]
Its not that I see a difference, but I was studying the generated code to try to understand the priors better, and I could not tell that the sdgp class was using R2D2M2 until I was told on the Stan forum. I'm reading the paper but it takes me some time to fully understand. So, I thought it would be nice for users to know. Or did I misunderstand things? If you don't think it's necessary, please ignore.

**Comment by paul-buerkner** [comment]
Ah yes, I see. Will update the doc accordingly in the next release.

**Comment by jpkrooney** [comment]
Thanks Paul, very much appreciated!

**Comment by paul-buerkner** [comment]
Fixed.
