### ISSUE TITLE
`lb` and `ub` as either `<NA>` or empty `""`

### ISSUE THREAD

**Issue by athowes** [paul-buerkner/brms#1679]
When you create a prior using e.g.:

```r
brms::prior("normal(2, 0.5)", class = "Intercept")
```

then the `lb` and `ub` entries are `<NA>`.

However, when you extract out the default priors from a `brms` model then rather than `<NA>` if there are no lower and upper bounds an empty is used `""`.

Is this intentional? I would have expected the same thing to be used.

**Comment by paul-buerkner** [comment]
It is intentional. brms can only know the *default* boundaries of a parameter in the context of the model it is applied in. Hence, if bounds are NA, brms will replace it with the appropriate default priors during prior validation.

**Comment by bmfazio** [comment]
I would say `brms::prior` is just a convenience function which, as Paul mentioned, cannot on its own produce a complete prior specification (hence the NAs). If you want to know the full specification a given model will use before actually running it, you probably want to use `get_prior`.
