### ISSUE TITLE
Quantile regression possible?

### ISSUE THREAD

**Issue by wfolta** [paul-buerkner/brms#168]
Not sure if it's possible in brm, not sure if it'd be in the Stan or somehow in post processing the samples -- it might even be possible already -- but something worth thinking about is quantile regression.

**Comment by paul-buerkner** [comment]
Quantile regression is not yet possible in **brms** (at least not to my knowledge). I will take a look at it.

**Comment by wfolta** [comment]
Thanks! I've been using brms in the last couple of weeks to develop a model for returning to work after injuries. It's really shown the power of Bayesian statistics, as I've been able to use censoring, weights, smoothers, random effects, etc, seamlessly, then use marginal_effects, marginal_smooths, and posterior predictive checks to check it out. (I have to say I've had my eyes opened by marginal effects showing how misleading it can be to look at coefficients and their SE's.)

So considering the only-okay results so far, the thought that different quantiles of cases might act differently has intrigued me.

**Comment by paul-buerkner** [comment]
Glad you had a good experience working with brms. Do you have any papers to recommend discussing quantile regression?

**Comment by paul-buerkner** [comment]
Nevermind, I already got it working locally. Just need some tests, doc, and compatibility with all S3 methods.

**Comment by paul-buerkner** [comment]
Quantile regression is now fully implemented using the asymmetric Laplace distribution (family `asym_laplace`). By fixing the auxiliary parameter `quantile` (note the suggestive name), we can perform quantile regression of the chosen quantile. Here is an example:

```R
n <- 200
x <- runif(n = n, min = 0, max = 10)
y <- 1 + 2 * x + rnorm(n = n, mean = 0, sd = 0.6*x)
dat <- data.frame(x, y)
# fit the 20%-quantile
fit <- brm(bf(y ~ x, quantile = 0.2), data = dat, family = asym_laplace())
summary(fit)
```

Of course, we can combine this with all other modeling options of **brms**, such as multilevel structures or smoothing terms.

**Comment by wfolta** [comment]
Looks like it works fine!

**Comment by wfolta** [comment]
Ooo, you're going to kill me, but is it possible that we could specify `quantile=c(0.1, 0.5, 0.9)` and collect the regression data in one shot? As I understand it, the most common two use cases for quantile regression would be: a) median regression, or b) choose a range of quantiles and observe how they act relative to each other. In the latter case, a vector of quantiles would be great and if they could be calculated in a single Stan run, it might be more efficient. (I'm just guessing on this one.)

I realize that this could throw a monkey wrench into things, since `brm` doesn't return multiple results like this, but perhaps it could establish how Issue #3 (multivariate regression) might return its values.

If there is no efficiency to be gained and it's too painful to implement multiple return values, it would be nice -- though perhaps inconsistent -- if `quantile` could be changed without requiring a recompile of the model. (Which perhaps it can already, I haven't tried.)

Thanks! My current model is slow enough that I don't think I'll be able to fully use quantile regression unless there is an efficiency to be had in doing multiple quantiles at once. Probably a poor model and noisy data, and I'm only thinking of quantile regression as something to help me probe where the model's doing poorly. (I'm also doing a lot of pp_checking, though I'm still learning about designing my own statistics to probe what's working well and not.)

**Comment by paul-buerkner** [comment]
It won't be possible to pass multiple quantiles since it would completely break the structure of **brms** as you say. However, I will make sure that quantile can be updated without recompiling the model (there is no efficiency gain anyway).

It is likely possible to optimize the Stan code of quantile regression to make it run faster, but I don't know when I have time digging deeper into it.

**Comment by wfolta** [comment]
Thanks, that'll be great! I don't think quantile regression runs slowly, my non-quantile regression currently runs slowly and I was just hoping that there might be some efficiency for multiple quantiles in one run rather than multiple runs -- not counting model compilation. So no need to optimize quantile regression unless someone else becomes a heavy user of it and can document actual slowness.

As far as multiple returns, I'd suggest that it might be possible once full multivariate regression is possible. At least I assume that multivariate regression will return multiple things and the quantile regression results might fit into that structure as if they were actually multiple target variables. (Just wishful thinking here.)

(My current model has probably noisy data, four categorical fixed effects, three continuous fixed effects, and four random intercepts, plus weighting. I'm not even sure if four random effects is a crazy thing to try or not, but these random effects make sense to me.)

**Comment by paul-buerkner** [comment]
I guess it won't be more efficient to run it within one Stan model, since we estimate different parameters for each quantile regression. It could possibly be implemented in a general multivariate framework, but I wouldn't improve things. Multivariate models will not actually return multiple things (brms already allows for multivariate normal models) in the sense that the structure of the returned object is nearly the same as for univariate output.

**Comment by realkrantz** [comment]
@paul-buerkner. I propose the addition of the capability to do `binomial quantile regression` in `brms`, as discussed [here](https://discourse.mc-stan.org/t/is-binomial-quantile-regression-possible-in-brms/6644/4).

**Comment by paul-buerkner** [comment]
I am not aware of any model in the literature allowing this kind of regression. Can you point me to one?

**Comment by realkrantz** [comment]
Thanks, @paul-buerkner. This is implemented in this [package](https://cran.r-project.org/web/packages/bayesQR/bayesQR.pdf), which unfortunately does not have the many good things that `brms` offers.

**Comment by realkrantz** [comment]
Thanks a lot for that @paul-buerkner. Just updated the links. This is a very useful approach which combined with `brms` and everything else, it would yield very informative results.

**Comment by MaximilianNaglUR** [comment]
Hello, 
first of all thank you a lot for your implementations in the “brms” package.
As the quantile regression using the asymmetric Laplace Distribution is already implemented, I was wondering if it would be possible to extend the functionality to random intercept models. A frequentist approach is already implemented in the “lqmm” or “qrLMM” package, but it`s unfortunately not that stable... In these models a random intercept is modelled for each quantile. This is especially common in medical studies and would enlarge the possible applications of the “brms” package. 
Interesting literature would be https://www.jstatsoft.org/article/view/v057i13 or https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5667718/

**Comment by paul-buerkner** [comment]
Would you mind opening a new issue for it, describing the basic idea and model in some more detail?
