### ISSUE TITLE
Support for future with cmdstanr?

### ISSUE THREAD

**Issue by wds15** [paul-buerkner/brms#1684]
Right now the future functionality is only supported by the RStan backend, but not the cmdstanr backend. As I am heavily relying on cmdstanr I would love to use the future facility for cmdstanr based runs.

What are the issues here / what was the rationale to not allow this?

**Comment by paul-buerkner** [comment]
No reason other than not thinking about it. Do you have time to provide a PR perhaps?

**Comment by wds15** [comment]
I don't have time... but will carve some out and send you one.

The background is that there is now future.mirai available on CRAN. This links future stuff to mirai which is an extremely powerful backend working locally and scaling to clusters with minimal overhead. As mirai is also used as backend in targets this would then make things fit really nice...

**Comment by paul-buerkner** [comment]
How can we efficiently combine multiple cmdstanr models? If we have a good way to do that, implementing futures for the cmdstanr backend should be easy and I am happy to implement it myself then.

**Comment by paul-buerkner** [comment]
Nevermind. Figured it out :-)
