### ISSUE TITLE
fun_von_mises.stan missing

### ISSUE THREAD

**Issue by ps2-2** [paul-buerkner/brms#1690]
I just updated brms, first to 2.22.0 (from CRAN), and then 2.22.1 (from github), and in both cases subsequently received an error regarding a missing file when trying to fit a von Mises model:

`In file(con, "r") :
  cannot open file '/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/brms/chunks/fun_von_mises.stan': No such file or directory`

Following [my post on the Stan forums](https://discourse.mc-stan.org/t/missing-von-mises-distribution-in-brms-2-22-0/36714), it looks like this is probably related to the other issues [here](https://github.com/paul-buerkner/brms/issues/1633) and [here](https://github.com/paul-buerkner/brms/pull/1678).

**Comment by paul-buerkner** [comment]
did you restart R after installing brms again?

ps2-2 ***@***.***> schrieb am Di., 24. Sept. 2024, 21:49:

**Comment by ps2-2** [comment]
Yep.

**Comment by paul-buerkner** [comment]
I take it that the following code errors for you?

```R
library(brms)
dat <- data.frame(y = rnorm(10, 0, 0.1))
fit <- brm(y~1, data = dat, family = von_mises())
```

It does work for me and I cannot find any traces of fun_von_mises.stan in the brms code base. Perhaps you are having some old brms models loaded in your environment that cause this?

I suggest to uninstall brms in a fresh R session (without any objects loaded). Then restart R and install brms in a fresh R session again. After another restart there should really be nothing that would keep R from clinging to some old code.

**Comment by paul-buerkner** [comment]
cool! :-)
