### ISSUE TITLE
Feature request: Change default `brm(iter = 2000)` to `brm(iter = getOption("brms.iter", 2000)`

### ISSUE THREAD

**Issue by mvuorre** [paul-buerkner/brms#1705]
A small quality of life improvement request:

I frequently run a bunch of models and don't initially want to wait for 2000 iterations. It would be faster if I could set a global option (e.g.) `options(brms.iter = 200)` and have `brm()` use that option. If the default for that option was 2000, it would default to current behavior. Does this make sense? If so I am happy to submit a PR.

**Comment by paul-buerkner** [comment]
sounds good!

Matti Vuorre ***@***.***> schrieb am Fr., 15. Nov. 2024,
08:48:

**Comment by mvuorre** [comment]
Implemented in https://github.com/paul-buerkner/brms/commit/cbd7a2612930d2e85130984d276b95ffa8ecb292, closing.
