### ISSUE TITLE
[Feature Request] Allow Passing `save_dso = FALSE` with `rstan` backend

### ISSUE THREAD

**Issue by emstruong** [paul-buerkner/brms#1709]
I'm running a Monte Carlo Simulation with brms in `SimDesign`. What seems to happen is that when I repeatedly fit `brms` objects that cannot re-use the previous compiled model, a lot of temporary compiled files seem to be stored in the `/tmp` folder. This eventually brings the system to a halt as there is no more disk storage to compile models.

Would it be possible to allow passing the `save_dso = FALSE` argument via `brm` to try to solve this problem? It seems like there is some checker that disallows passing unknown arguments.

**Comment by paul-buerkner** [comment]
Can you show a reprex? I think passing save_dso should be possible.

**Comment by emstruong** [comment]
Just to link the [discussion](https://discourse.mc-stan.org/t/deleting-temporary-files-created-by-brms/37311)

```r
library(brms)
tmp2<-brms::brm(
    count ~ zBase * Trt + (1|patient),
    data = epilepsy, family = poisson(),
    prior = prior(normal(0, 10), class = b) +
        prior(cauchy(0, 2), class = sd), backend = "rstan", stan_model_args = list(save_dso = FALSE)
)
tmp2[["fit"]]@stanmodel@dso@dso_filename
```
The function makes it seem as if this should not `save_dso`, as far as I can tell, it still saves `dso`. `tmp2[["fit"]]@stanmodel@dso@dso_filename` is not empty and I can see the file in my terminal

**Comment by paul-buerkner** [comment]
I just checked and `save_dso` is correctly passed to rstan::stan_model. So the issue is not on the brms side.

**Comment by emstruong** [comment]
Even with re-compilation, it seems like using `cmdstanr` is nearly twice as or 5 times faster than `rstan`? I'll investigate further, but assuming I didn't mess anything up, that's pretty incredible.

**Comment by wds15** [comment]
Checkout the setup here:

http://opensource.nibr.com/bamdd/src/01b_basic_workflow.html#r-session-setup

This avoids recompilation with cmdstan.

**Comment by emstruong** [comment]
Thanks, that's helpful. It's just that in my simulation, I'm doing the forbidden default priors everywhere--which means that using `update` is 'dangerous' because `brms` has data-based default priors and IME `update` will silently refit the model seemingly without updating data-based default prior. 

Just putting it here since it also might be helpful for future web-searchers wondering what the best way to do this is
