### ISSUE TITLE
loo_R2: add seed argument 

### ISSUE THREAD

**Issue by avehtari** [paul-buerkner/brms#1713]
loo_R2 used Bayesian bootstrap for quantifying the uncertainty. To be able to quantify the corresponding uncertainty when comparing two models, the same random seed should be used in Bayesian bootstrap

With seed argument and the following code
```
loo_r2_diff <- loo_R2(fit1, re_formula=NA, summary=FALSE, seed=1) - loo_R2(fit2, re_formula=NA, summary=FALSE, seed=1)
```
`loo_r2_diff` would contain Bayesian bootstrap draws describing the uncertainty in model comparison (without common seed the result would be not useful).

The relevant part in `.loo_R2()´ would be to wrap the call `rexp()` with a local seed that has been passed as one of the arguments
```
  withr::with_seed(SEED, {
    exp_draws <- matrix(rexp(S * N, rate = 1), nrow = S, ncol = N)
  })         
```
I used `withr::with_seed()` as an easy illustration, but there are ways to do the same without adding new dependency.

**Comment by paul-buerkner** [comment]
Thanks! I will put it on my todo list for the next release.
