### ISSUE TITLE
Hierarchical Quantile Regression - Convergence Issues

### ISSUE THREAD

**Issue by marcos060482** [paul-buerkner/brms#1718]
Hi,
I am currently working on a hierarchical quantile regression model with three levels (student, class, and school). At this stage, I am testing a null model with random effects at the class and school levels. However, I am facing convergence issues, as the Rhat values are consistently above 1.05, with many exceeding 2 or even 3.

Below is the R code I used:

m03 <- brm(
  formula = Proficiencia ~ 1 + (1 | ID_escola/ID_classe/ID_aluno),
  family = asym_laplace(),
  data = dados,
  chains = 4,
  cores = 4,
  iter = 2000,
  seed = 123
)

Additionally, I attempted to include control = list(adapt_delta = 0.99, max_treedepth = 15) to improve model adaptation. However, the execution time became excessively long, and I still have not achieved the desired results.
I would greatly appreciate any suggestions that might help resolve this issue.

Thanks,
Marcos Machado

**Comment by lunafazio** [comment]
Hi, this issue tracker is meant for discussing bugs or features with the brms package. For modeling questions, you should post on the [Stan forums](https://discourse.mc-stan.org) instead.

When you do so, I would also suggest that you include the full summary output and, if possible, the actual data so people have an easier time assisting you.
