### ISSUE TITLE
Allow both truncation and censoring at the same time

### ISSUE THREAD

**Issue by Atan1988** [paul-buerkner/brms#172]
Hi Paul,

     Thank you again for brms. It has been great. 
      I notice that it doesn't currently support truncation and censoring at the same time. Although it is easy to add - FUN_lccdf(trunc(i), ...) into the stan code generated from make_stancode, I think it might be helpful to allow truncation in the main brms formula. 

      Is there anything I can do to help implement this?

Thanks!
Allen

**Comment by paul-buerkner** [comment]
I am happy to implement it. How would the stan code lool like combining
truncation and censoring (I can figure it out myself but you might be
faster).

Am 24.01.2017 18:26 schrieb "Atan1988" <notifications@github.com>:

**Comment by Atan1988** [comment]
below is some example modified stan code from make_stancode：
I only needed left truncation but i think right truncation would be just to substract fun_lccdf of the right truncation point.

thanks！ let me know if  can help in any other way. 

// This Stan code was generated with the R package 'brms'. 
// We recommend generating the data with the 'make_standata' function. 
functions { 
} 
data { 
  int<lower=1> N;  // total number of observations 
  vector[N] Y;  // response variable 
  vector[N] trunc;  // response variable 
  int<lower=1> K;  // number of population-level effects 
  matrix[N, K] X;  // population-level design matrix 
  int<lower=-1,upper=2> cens[N];  // indicates censoring 
  int prior_only;  // should the likelihood be ignored? 
} 
transformed data { 
  int Kc; 
  matrix[N, K - 1] Xc;  // centered version of X 
  vector[K - 1] means_X;  // column means of X before centering 
  Kc = K - 1;  // the intercept is removed from the design matrix 
  for (i in 2:K) { 
    means_X[i - 1] = mean(X[, i]); 
    Xc[, i - 1] = X[, i] - means_X[i - 1]; 
  } 
} 
parameters { 
  vector[Kc] b;  // population-level effects 
  real temp_Intercept;  // temporary Intercept 
  real<lower=0> sigma;  // residual SD 
} 
transformed parameters { 
} 
model { 
  vector[N] eta; 
  eta = Xc * b + temp_Intercept; 
  // prior specifications 
  b ~ normal(0, 2.5); 
  temp_Intercept ~ normal(0, 10); 
  sigma ~ student_t(3, 0, 16); 
  // likelihood contribution 
  if (!prior_only) { 
    for (n in 1:N) { 
      // special treatment of censored data 
      if (cens[n] == 0) 
        target += lognormal_lpdf(Y[n] | eta[n], sigma) - lognormal_lccdf(trunc[n] | eta[n], sigma); 
      else if (cens[n] == 1) 
        target += lognormal_lccdf(Y[n] | eta[n], sigma) - lognormal_lccdf(trunc[n] | eta[n], sigma); 
      else if (cens[n] == -1)  
        target += lognormal_lcdf(Y[n] | eta[n], sigma)- lognormal_lccdf(trunc[n] | eta[n], sigma); 
    } 
  } 
} 
generated quantities { 
  real b_Intercept;  // population-level intercept 
  b_Intercept = temp_Intercept - dot_product(means_X, b); 
}

**Comment by paul-buerkner** [comment]
Thanks! That makes totally sense! :-)

**Comment by paul-buerkner** [comment]
It should be working now. Would you mind double-checking the created Stan code when combining censoring with (upper / lower / both) truncation?

**Comment by Atan1988** [comment]
I have tested the lower truncation case, and it's working as intended. I will also test upper and both truncation tomorrow.

Thank you for implementing this so quickly!

Allen

**Comment by Atan1988** [comment]
I made an attempt to construct some testing cases for both gamma and lognormal using the  R code below.
The lognormal case works well, but the code won't start on the gamma case （lines related to gamma are commented out).  I think I will need to give stan a good starting point for gamma fit, but I am not sure how to do it properly.  

library(brms)

set.seed(100999)
n <- 2500
dat <- data.frame(x1 = rnorm(n)) 
dat$Intercept <- 10
sdlog <- 1.28
dat$meanlog <- with(dat, Intercept + 0.05*x1)

dat$y <- unlist(lapply(dat$meanlog, function(x) rlnorm(1, meanlog = x, sdlog = 1.28)))
#dat$y <- unlist(lapply(exp(dat$meanlog), function(x) rgamma(1, scale = x, shape = 1.28)))

dat$lb <- sample(c(0, 2500, 5000, 5e4, 1e5, 2.5e5), size = n, replace = T)
dat$ub <- sample(c(5e5, 1e6, 2.5e6, 5e6), size = n, replace = T)
dat$limit <- sample(c(1e5, 2.5e5, 5e5, 1e6), size = n, replace = T)

dat1 <- dat[!(dat$y > dat$ub | dat$y < dat$lb), ]
dat1$y1 <- with(dat1, ifelse(y >= limit + lb, limit + lb, y))
dat1$censored <- with(dat1, ifelse(y >= limit + lb, 1, 0))

fit1 <- brm(formula = y1|cens(censored) + trunc(lb = lb, ub = ub) ~ x1
            , family = lognormal(link = "identity")
            #, family = Gamma(link = "log")
            , data = dat1
            , chains = 4
            , iter = 2500
            , prior = c( set_prior("normal(0, 1)", class = "b")
                           , set_prior("normal(0, 5)", class = "b", coef = "Intercept")
                      )
            )

fit1

**Comment by paul-buerkner** [comment]
Try using the `init_r` argument and set it to values smaller than `2` (default).

**Comment by Atan1988** [comment]
Is there any way to set the initial value of the intercept term higher (closer to 10).
I am suspecting that because gamma has a lighter tail than lognormal, and because all the numbers I used are large in the hundreds of thousands and millions(as in insurance claims dollar amount), some of the likelihoods are practically evaluated to be zero by stan, which causes a log(0) error message. 

Thanks! I think the solution implemented in the dev version itself generates appropriate stan code to solve the problem with both censoring and truncation at the same time.

**Comment by paul-buerkner** [comment]
You might want to rescale your variables, to make things easier. With such large scales I am not surprised that you are running into problems finding good initial values. Let's move this to the brms-users list, if there is further need for discussion (https://groups.google.com/forum/#!forum/brms-users).
