### ISSUE TITLE
Index Out of Range Error with com_poisson family

### ISSUE THREAD

**Issue by MichaelSchatz** [paul-buerkner/brms#1721]
I realize it is still in development, but was hoping to use the com_poisson family for a project and have not been able to successfully run it. I keep getting the following error: 

Chain 1 Exception: Exception: Exception: vector[min_max] max indexing: accessing element out of range. index 52 out of range; expecting index to be between 1 and 51

reprex is below:

`  model_test <- brm(count ~ 1 + zAge + zBase + Trt,
              data = epilepsy, family = brmsfamily("com_poisson")
             )`

**Comment by paul-buerkner** [comment]
Looks like a bug. I will investigate.

**Comment by paul-buerkner** [comment]
It does work for me. I assume you use an old version of brms? If you keep getting this error for the latest brms and Stan versions, please let me know.
