### ISSUE TITLE
Allow multiple monotonic predictors

### ISSUE THREAD

**Issue by bschneidr** [paul-buerkner/brms#174]
I'm running a cumulative logit model with the following kind of specification:

    my_model <- brm(data = my_data, 
                    formula = ls ~ monotonic(Income) + monotonic(Age), 
                    family = cumulative(link = "logit"))

where `Income` and `Age` are ordered factors.  

However, the model is fit as if I had only specified the formula `ls ~ monotonic(Age)`: in the resulting `brmsfit` object, there is no reference to parameters for `monotonic(Income)` (or even just `Income`, for that matter) anywhere except for in `my_model$formula`, which correctly displays the formula written in the call to `brm()`.  If I swap the order of `monotonic(Income)` and `monotonic(Age)` in the formula, then the fit object acts as if I had only specified the formula `ls ~ monotonic(Income)`.
  
I'm not sure, but I think that brms is only allowing for one monotonic effect in the Stan code which it compiles.

Below is example data that can be used to recreate this issue:

     library(purrr)
     library(dplyr)
         
     my_data <- data_frame(ls = rdunif(n = 1500, b = 5, a = 1) %>%
                                                   as.ordered(),
                           Age = rdunif(n = 1500, b = 5, a = 1) %>%
                                        as.ordered(),
                           Income = rdunif(n = 1500, b = 5, a = 1) %>%
                                            as.ordered())

**Comment by paul-buerkner** [comment]
This is weired, I will check that.

**Comment by paul-buerkner** [comment]
I can confirm this is a bug and I will fix it asap.

**Comment by paul-buerkner** [comment]
It should be working correctly now. You can try it yourself using the dev version of brms:

```R
if (!require("devtools")) {
  install.packages("devtools")
}
devtools::install_github("paul-buerkner/brms", dependencies = TRUE)
```

Thanks for reporting this problem!

**Comment by bschneidr** [comment]
Thanks for addressing this so quickly!

The `monotonic()` functions are now incorporated into the model correctly. Your fix seems to have done the trick.
