### ISSUE TITLE
use_cache Argument in Brmsfit objects does not work.

### ISSUE THREAD

**Issue by stuntman723** [paul-buerkner/brms#176]
When attempting to get a summary of a brmsfit object by using `summary(object, use_cache=FALSE)` there is an error saying that use_cache=FALSE is an unused argument. I'm not entirely sure why this is happening and think it may be an issue.

![issue](https://cloud.githubusercontent.com/assets/8878563/22334921/8b4892dc-e3aa-11e6-8228-e0f52197e3e9.PNG)

**Comment by paul-buerkner** [comment]
Hmm, it works fine for my models. Also, I don't see a point in my code, where `use_cache` could produce the error above. Do you have a reproducible example for me?

**Comment by stuntman723** [comment]
Here's the example which is failing for me:
``fdafas

**Comment by paul-buerkner** [comment]
Your example does not seem to be complete. Also, which version of brms are you using?

**Comment by stuntman723** [comment]
I updated the example, and I am using 0.10.0

If you have any suggestions for where to upload a .dat file to a website, that would be great.

**Comment by paul-buerkner** [comment]
Please update your brms version. We are already at 1.3.1.

brms 0.10.0 doesn't even have the use_cache argument if I am not mistaken.

Best,
Paul

**Comment by stuntman723** [comment]
Ah sorry about that, thank you for responding so quickly.
