### ISSUE TITLE
Scaling with the noise std in the horseshoe's scale_global

### ISSUE THREAD

**Issue by jpiironen** [paul-buerkner/brms#177]
There seems to be a possibility of adjusting the prior scale `scale_global` for the global shrinkage parameter `tau` in the horsehoe prior which is great. However, I was unsure whether this scale will be multiplied later by the unknown noise standard deviation `sigma` (in regression) as we recommend (https://arxiv.org/abs/1610.05559), or should the user try to guess the value for `sigma` beforehand and incorporate this value into `scale_global`? Taking the noise level into account is quite important and is now implemented in rstanarm, so if it is missing from brms, it would be great to have it if possible!

**Comment by paul-buerkner** [comment]
I will add this asap. Thanks for pointing me to it!

**Comment by paul-buerkner** [comment]
The relevant Stan code for `horseshoe(df = 1, scale_global = 2)` now looks as follows in linear models.

```
hs_local ~ student_t(1, 0, 1); 
hs_global ~ cauchy(0, 2 * sigma); 
b ~ normal(0, hs_local * hs_global); 
```

It this what you had in mind?

**Comment by jpiironen** [comment]
Yes, this is exactly what I meant, thanks for the quick response! Also, now that you are at it, it would not hurt to have a possibility of changing the degrees of freedom for `hs_global` instead of always using half-Cauchy. So you could have something like `horseshoe(df=1, df_global=4, scale_global=0.1)` which translates to 
```
hs_local ~ student_t(df, 0, 1);
hs_global ~ student_t(df_global, 0, scale_global*sigma);
b ~ normal(0, hs_local * hs_global); 
```
Would this be possible to add?

**Comment by paul-buerkner** [comment]
Done ;-)

Would you mind trying it out with the dev version of brms?

**Comment by jpiironen** [comment]
I tried it briefly, seems to work OK, but I realized that with `brms` I get considerably more divergent transitions than with `rstanarm` even when both use the same `adapt_delta=0.99`. Here's the code I used: http://pastebin.com/eFXasnVH. It is possible that I mispecified the model somehow as I'm not too familiar with `brms` yet. But the reason may also be that `rstanarm` is using a parametrization that is more robust for sampling. This topic has been discussed also earlier (https://groups.google.com/forum/#!msg/stan-dev/pt1NNytNVUI/4PHO9ekefBYJ). We also used a reparametrization in our work (see the appendix in our paper). You might be interested in checking this out.

**Comment by paul-buerkner** [comment]
Thanks for looking into this. It is indeed a problem of the parameterization for small degrees of freedom. I will work on improving numerical stability.

**Comment by paul-buerkner** [comment]
I am now using the parameterization favored by rstanarm. Indeed, this drastically improves efficiency and stability. Would you mind reviewing the code?

**Comment by jgabry** [comment]
I gave it a quick glance and from what I can tell it looks like you're using the rstanarm parameterization correctly. So looks good to me!

**Comment by paul-buerkner** [comment]
Thanks @jgabry! 

@jpiironen Any more suggestions (always welcome)?

**Comment by jpiironen** [comment]
Seems correct to me also, and it performs much better now. I don't have anything else at this point, thanks for implementing these!

**Comment by paul-buerkner** [comment]
Great! Thanks for opening this issue and for all the suggestions!
