### ISSUE TITLE
How to see stan version number from a `brms` fit object?

### ISSUE THREAD

**Issue by tomwallis** [paul-buerkner/brms#181]
Given the recent major bug in the stan sampler, I wanted to check the stan version that was used to run a model fit. However, looking at `fit$version` returns the `brms` version only. Is there a way to return the version of Stan that was used to collect the samples?

**Comment by paul-buerkner** [comment]
Try out `fit$fit@stanmodel@model_cpp$model_cppcode`

**Comment by tomwallis** [comment]
Thanks Paul, that returned it. I wonder if it's much trouble to add this to the `fit$version` result? It would be useful to have more easily accessible.

**Comment by paul-buerkner** [comment]
That's certainly possible. Do you think adding the `rstan` version would suffice?

**Comment by tomwallis** [comment]
I guess? Does the `rstan` version always correspond to the Stan version? It's mainly so I can ask "do I need to re-fit this model?" for older versions of Stan, should bug reports happen.

**Comment by jgabry** [comment]
Coincidentally I actually just added this to rstanarm earlier today. I used
the rstan version, which I think should be sufficient. We try very hard to
keep the rstan version number lined up with the Stan version.
