### ISSUE TITLE
grouped bayesplot only allow group-level effects, not "fixed effects"

### ISSUE THREAD

**Issue by silberzwiebel** [paul-buerkner/brms#183]
Hey,

I'd like to plot a posterior predictive check grouped by the experimental condition. 
Suppose I have the following brms formula:

```
rating ~ RO + (1 | subject)
```

Now, using bayesplots pp_check directly gives me what I want (plot the response dependent on the value of RO):

```
pp_check(relDist_model_RO$data$Rating, 
         yrep = posterior_predict(relDist_model_RO, nsamples = 10), 
         fun = "violin_grouped", group = relDist_model_RO$data$subject)
```

but using the wrapper function provided by brms

```
pp_check(relDist_model_RO, type = "violin_grouped", nsamples = 10, group = "RO")
```

results in
```
Fehler: Group 'RO' is not a valid grouping factor. Valid groups are: 
subject
```

I think, the term "group" has a different meaning in brms than it has in bayesplot?

(this issue corresponds to https://groups.google.com/forum/#!category-topic/stan-users/general/5FtaMivN5YA )

**Comment by paul-buerkner** [comment]
Thanks! I will change this.

**Comment by paul-buerkner** [comment]
It should be working correctly now. Thanks again for pointing me to this issue!

**Comment by andymilne** [comment]
Hi Paul, I think this bug may still be here -- at least when using bars_grouped. The following generates an error:

```
pp_check(mdlred2, nsamples=1000, type = "bars_grouped", group = Data$ScPb)
Error: Cannot coerce group to a single character value.
```

On the other hand, this works as expected:

`pp_check(mdlred2$data$Ratings, yrep = posterior_predict(mdlred2, nsamples = 1000), fun = "bars_grouped", group = Data$ScPb)`

**Comment by paul-buerkner** [comment]
the error tells you exactly what is the problem: group expects you to pass
the name of the variable not the variable itself.

Andrew Milne <notifications@github.com> schrieb am Di., 5. Juni 2018, 02:41:

**Comment by andymilne** [comment]
OK - I couldn’t glean the meaning of that error message - it’s pretty inscrutable :-)

I cannot - as far as I know - call the grouping variable by name because it’s not directly included in the model but is just a column in data. But maybe I am misunderstanding.

**Comment by paul-buerkner** [comment]
Yeah, you are right. In this case the error message is not that clear (but the help page is `?pp_check.brmsfit`).

To include a variable outside of your data frame, I think you have to call the default method of `pp_check` directly as you already did above.
