### ISSUE TITLE
hurdle_gamma with marginal_effects

### ISSUE THREAD

**Issue by troutjef** [paul-buerkner/brms#184]
Love the brms package. Usually, I use marginal_effects to visually check outputs. However, does marginal_effects account for the "hurdle" probabilities in the plots when using family = hurdle_gamma (i.e. multiply the probability by the mean)?

**Comment by paul-buerkner** [comment]
It does. Here is the relevant function (from R/fitted.R):

```R
fitted_hurdle_gamma <- function(draws) {
  draws$hu <- get_theta(draws, par = "hu")
  draws$mu <- adjust_old_forked(draws$mu, draws$hu)
  draws$mu <- ilink(draws$mu, draws$f$link)
  with(draws, mu * (1 - hu))
}
```

**Comment by troutjef** [comment]
Thank you. I was having trouble recreating it on my own. I was almost certain the fault was mine, but thought I'd ask anyway. Thanks again.

**Comment by pboesu** [comment]
Related question: Is there a trick to conveniently get fitted values for the counts component alone, i.e. conditional on the hurdle having been crossed already.

(I know how to manually get those from the estimated parameters, but was wondering if there's something similarly convenient as `fitted (fit, dpar = "hu")` for the hurdle probabilities. )

**Comment by paul-buerkner** [comment]
Try `fitted (fit, dpar = "mu")` in the latest dev version of brms from github.

**Comment by pboesu** [comment]
Nice one, thank you!

It works to get the fit on the linear predictor scale this way, but `scale = response` appears to be ignored silently, returning the same values as for `scale = linear`. 

I can put together a reproducible example and file a separate issue if that helps.

**Comment by paul-buerkner** [comment]
You are right. I will fix this.

2017-11-14 16:54 GMT+01:00 Philipp Boersch-Supan <notifications@github.com>:

**Comment by paul-buerkner** [comment]
Please try it again with the latest dev version.

**Comment by pboesu** [comment]
Works a treat. Dankeschön!
