### ISSUE TITLE
summary(brmsfit) misses new line

### ISSUE THREAD

**Issue by silberzwiebel** [paul-buerkner/brms#188]
A minor point I discovered the other day:
Printing a summary of a brmsfit object in RStudio adds a new line after the output, which is fine.
However, printing a summary in R only (i.e., on the command line with no GUI), does not add a new line.
The output looks like this:
```
scale reduction factor on split chains (at convergence, Rhat = 1).>
```

where the "greater than symbol" is R's command line input.
This feels a bit weird and is different from, e.g., the last line of a summary from a lm():

```
F-statistic: 3.015e+04 on 1 and 11333 DF,  p-value: < 2.2e-16

>
```

**Comment by paul-buerkner** [comment]
Good catch, thanks! It should be fixed now in the dev version on github.
