### ISSUE TITLE
feature request: marginal_effects plot for ordinal regression

### ISSUE THREAD

**Issue by silberzwiebel** [paul-buerkner/brms#190]
Hi,

I'm not sure whether I fully understand the marginal_effects plot yet that I discovered yesterday.
I'm working with ordinal regression and `marginal_effect()`already prints a warning that it's treating the predicted variable as continuous which is likely an invalid assumption for ordinal regressions.

Do you have any plans to treat the predicted variable in a proper manner for marginal effects plot?
Maybe this is possible by using something similar to the new ppc_bars from bayesplot (see https://github.com/stan-dev/bayesplot/issues/73 )?
Since I did not grasp fully what marginal_effects is actually computing, my feature request might be not doable out of theoretic reasons, though.

Alternatively, and maybe easier to implement as a work-around I suggest to add horizontal violin plots and/or jitter the data points in vertical direction if one plots the points inside the marginal effects plot like this:

![marginalordinal](https://cloud.githubusercontent.com/assets/4533862/23501982/0478624c-ff2e-11e6-84ff-258365911b9d.png)

Doing so gives at least a quick suggestion where the bulk of the ordinal data lies for the value of the predictors.

**Comment by paul-buerkner** [comment]
To get a sense of what `marginal_effects` is doing for ordinal models, just run `predict(., summary = FALSE)` on your fitted model. For each data point (rows) you get nsamples predictions (columns). The task now is to somehow summarize the predictions for each data point to get a single value (blue line) + CIs (grey area) to be plotted in `marginal_effects`. I am not sure whether `ppc_bars` falls into this category (Suggestions welcome).

I totally agree that adding a jitter or similar would help making use of the points in the plot. Let's see what makes the most sense.

**Comment by silberzwiebel** [comment]
> For each data point (rows) you get nsamples predictions (columns).

I think you flipped rows and columns here. I get as many rows as samples and as many columns as I have data points.

Just had a  quick look in Kruschke DBDA book. He is using something similar as ppc_bars for something I reckon could be compared to the marginal effects plot. Here are his two example plots copied from the figures pdf he has made available (just to be sure to violating any copyright. elsevier is evil, that's what I heard ...):

![bildschirmfoto 2017-03-02 um 11 55 36](https://cloud.githubusercontent.com/assets/4533862/23504385/1b353088-ff37-11e6-8825-60814b030571.png)
![bildschirmfoto 2017-03-02 um 11 55 13](https://cloud.githubusercontent.com/assets/4533862/23504386/1b3bb638-ff37-11e6-9565-52b87c2831d4.png)

So, as I understand it, it's not possible to add a single value to plot the blue line, instead one could plot full histograms at some given discrete x values (and include the blue line anyway with the disclaimer of treating ordinal data as continuous).

**Comment by paul-buerkner** [comment]
You are right, I flipped rows and columns. Thanks for sharing those figures. At first glance, I am not sure whether I like these plots. How did he come up with these regression lines?

**Comment by silberzwiebel** [comment]
citing from Kruschke (2015, p. 689):
> Figure 23.7 displays aspects of the posterior predictive distribution superimposed on the data. A smattering of credible regression lines is displayed. It must be remembered, however, that the regression lines refer to the underlying metric predicted variable, not to the ordinal predicted variable. Thus, the regression lines are merely suggestive and should be used to get a visual impression of the uncertainty in the slope and intercept. More directly pertinent are the posterior predicted probabilities of each outcome at selected x values marked by vertical lines. At the selected x values, the posterior predicted probabilities of the outcomes are plotted as horizontal bars “rising” leftward away from the vertical baseline. 

He explains his model using this picture:
![bildschirmfoto 2017-03-02 um 12 17 56](https://cloud.githubusercontent.com/assets/4533862/23505044/eff9103a-ff39-11e6-89ce-0c1dceaf510a.png)

Trying to translate this to `brms` syntax, I guess he would have run the following:
```
brm(Y ~ X, family = cumulative(link=probit))
```
Then he would draw from the posterior distribution of the regression coefficient for X to get credible slopes for his regression lines. The intercepts of these regression lines come from an (extra?) intercept parameter he specified in his JAGS model (beta0 in the model picture).

**Comment by jgabry** [comment]
I'm a bit confused by how Kruschke is using certain terminology. I need to
take a closer look at that section of his book, but I think the regression
lines that he seems to imply come from the posterior predictive
distribution are actually just constructed from the posterior (not
predictive) distribution of the coefficients.  Since the underlying latent
variable is presumably Gaussian, the posterior predictive distribution
could be draws from a Gaussian (but not a regression line, which doesn't
include sigma, even if sigma is fixed to 1, as it often is in these models
since the scale of the latent variable isn't identified).

Then there's the posterior predictive distribution of the actual ordinal
outcome, and that certainly doesn't give you a regression line, just draws
of an ordinal variable.

**Comment by paul-buerkner** [comment]
The other problem I see is that this "latent variable" interpretation is only meaningful for family `cumulative` but not for the other families `sratio`, `cratio` (both sequential models) and `acat` (adjacent category). A special `marginal_effects` implementation for ordinal models would need to work with all ordinal families.

**Comment by jgabry** [comment]
Yeah that's true. This particular interpretation definitely does not apply
to all models fit to ordinal data.

**Comment by silberzwiebel** [comment]
@jgabry 
> I think the regression lines that he seems to imply come from the posterior predictive distribution are actually just constructed from the posterior (not predictive) distribution of the coefficients.

This is how I also read the text and the plots. When Kruschke writes
> Figure 23.7 displays aspects of the posterior predictive distribution superimposed on the data. 
I think he just means the tilted barplots.

He goes on with

> A smattering of credible regression lines is displayed. It must be remembered, however, that the regression lines refer to the underlying metric predicted variable, not to the ordinal predicted variable. 

which fits with your remarks, Jonah.

Given this difficulties of interpreting such plots and the other problem mentioned by 
@paul-buerkner, I would suggest to not plot any regression line but only something like a barplot.
In my head the marginal_effects plot is then doing something similar to `ppc_bars_grouped` where the groups aka exp. conditions are plotted on the x-axis, and depending on this x axis, a different, tilted ppc_bars is plotted. Quite possibly however, this (i.e., plotting posterior predictive checks depending on different predictor values) is not what `marginal_effects`is meant for.

If it is, however, one kind of gets in trouble with metric predictors.
Here, one would have to set a discrete number of tilted ppc_bars to plot. Also, the magnitude of the tilted bars going into horizontal directions have nothing to do with the scale of the x-axis as one might think.

The following idea popped up in my mind, not sure if it makes sense. I tried to create an example plot with Kruschke's fictitious data but couldn't do it. So I'll try to explain in words.
Instead of plotting tilted bars that visualize the probability of ratings by their height, I imagined colored tiles. On the y-axis, we would have as many tiles as we have ordinal outcomes, on the x-axis we would have as many tiles as the user wishes. The darker a tile, the lower the probability of the outcome Y. Something comparable to this interaction plot from `marginal_effects`, but with the x axis being one predictor (and possibly having a higher resolution), the y-axis denoting the ordinal outcome (fixed to 9 if there are 9 outcomes) and the color scale denoting probability:

![marginalordinalidea](https://cloud.githubusercontent.com/assets/4533862/23547605/b181a494-fffb-11e6-9210-03ec1416b5b5.png)

Not sure how to add uncertainty of the probabilities. Maybe with a label inside each tile?
I do not have any idea how this could work then with a two-way interaction plot, though.

**Comment by paul-buerkner** [comment]
This sounds like a good idea. We could possibly add an argument to `marginal_effects` that only takes effect for models predicting probabilities (i.e. ordinal, categorical, binomial models) that allows for plotting such a "probability surface". I am not sure though, how the best implementation for this would look like.

**Comment by jgabry** [comment]
On Fri, Mar 3, 2017 at 5:29 AM silberzwiebel <notifications@github.com>
wrote:

> @jgabry <https://github.com/jgabry>
>
> I think the regression lines that he seems to imply come from the
> posterior predictive distribution are actually just constructed from the
> posterior (not predictive) distribution of the coefficients.
>
> This is how I also read the text and the plots. When Kruschke writes
>
> Figure 23.7 displays aspects of the posterior predictive distribution
> superimposed on the data.
>
> I think he just means the tilted barplots.
>
> He goes on with
>
> A smattering of credible regression lines is displayed. It must be
> remembered, however, that the regression lines refer to the underlying
> metric predicted variable, not to the ordinal predicted variable.
>
> which fits with your remarks, Jonah.
>

Ok yeah, you're right, I think he's clearer about the distinction than it
seemed to at first glance. Thanks for clearing that up!

**Comment by silberzwiebel** [comment]
It just occurred to me while trying out to plot points with the new feature in #208 that a very quick (I assume) workaround for this issue is to actually plot geom_violin or geom_jitter instead of geom_point for ordinal regression models. 
This gives a quick view, where the magnitude of the data points are -- opposed to geom_point, where you have to judge from the thickness of the outer lines of the points because data points cluster a lot due to the low amount of possible y-values.
geom_violin however would still add to the impression that the outcome is treated metric (which is what the lines suggest anyway, though [and there is the warning message]), so maybe geom_jitter (horizontal jitter only) is the better choice.

**Comment by paul-buerkner** [comment]
I have added argument `jitter_width` to the `plot` method of `marginal_effects` to allow for horizontal jittering of data points.

**Comment by paul-buerkner** [comment]
I finally added this feature in the dev version. You can now run ` marginal_effects()` with `ordinal = TRUE` to get a tile-style plot just as suggested by @silberzwiebel above. For instance

```R
fit2 <- brm(rating ~ period + carry + treat, 
            data = inhaler, family = cumulative())
marginal_effects(fit2, "treat", ordinal = TRUE)
``` 

generates the attached plot.
[me_plot.pdf](https://github.com/paul-buerkner/brms/files/1629181/me_plot.pdf)
