### ISSUE TITLE
marginal_effects plot: scale_color_x is not fully applied

### ISSUE THREAD

**Issue by silberzwiebel** [paul-buerkner/brms#193]
The interaction plots of `marginal_effects` use red, green, and blue as default colors; the credible intervals are plotted in a shaded manner.
If one wants to change these colors (e.g., to be colorblind friendly) by adding a ggplot2 color scale such as `scale_color_grey()`, only the color of the lines is changed but not the shaded areas.

**Comment by paul-buerkner** [comment]
Also adding `scale_fill_grey()` should do it.

**Comment by silberzwiebel** [comment]
True. Sorry for the noise.

**Comment by paul-buerkner** [comment]
All good. I stumbled upon this once (or twice?) myself ;-)

I will amend the doc of `marginal_effects` to explain how to appropriately change colors.
