### ISSUE TITLE
Predicting with category-specific random intercepts

### ISSUE THREAD

**Issue by waynefoltaERI** [paul-buerkner/brms#195]
I'm not sure that what I'm doing makes statistical sense, but I believe it should work:

`> formula (foo3)
adjud ~ X1 + X2 + X3 + X4 + X5 + X6 + X7 + X8 + s(X9, k = 3) + (cs(1) || RE1) + (cs(1) || RE2) + (cs(1) || RE3) + (cs(1) || RE4) + (cs(1) || RE4) 

> foo3 <- brm (form, data=rtwm_train,
             algorithm="meanfield", 
             prior=c(set_prior ("student_t (10, 0, 5)", class="b"),
                     set_prior ("student_t (10, 0, 7)", class="Intercept"),
                     set_prior ("student_t (10, 0, 5)", class="sd"),
                     set_prior ("student_t ( 5, 0, 7)", class="sds")))

> predict (foo3)
Error in seq_len(sdata$ncat - 1) : 
  argument must be coercible to non-negative integer
In addition: Warning message:
In seq_len(sdata$ncat - 1) : first element used of 'length.out' argument`

It has no problems when I use the same formula except using straight-up intercepts (`1`) rather than category-specific intercepts (`cs(1)`). I've tried with `||` and `|` in the random effects. Should this work or have I messed up?

**Comment by paul-buerkner** [comment]
This should work. I will find out what is going wrong.

**Comment by paul-buerkner** [comment]
Which family did you use?

**Comment by waynefoltaERI** [comment]
I used `categorical`.

Thanks! I'm not sure that my model makes sense, but to the degree that it does, I think category-specific intercepts are what I want.

It runs, of course, if I don't use `cs`, but I can't really figure out what the resulting random effects would mean. Not that I totally understand a multinomial logistic -- it hurts my head compared to a straight-up logistic regression -- but having a single valued random effect feels more ordinal than categorical and so it feels like it might be nonsensical.

(It also runs extremely slowly, and in the back of my mind I seem to remember that categorical regressions run slowly unless ______. I can't remember what. But maybe I'm imagining things.)

**Comment by paul-buerkner** [comment]
Uhm, categoric specific effects are only implemented for ordinal models. That is they should not work with the `categorical` family at all... If you add a category specific population-level effect (e.g. ` + cs(X1)`), it should fail with an error. Apparaently, I missed a check, when only category specific group-level effects are used. I will fix that.

**Comment by paul-buerkner** [comment]
Edit: the categorical family fits category specific group-level effects anyway. No need to use `cs`.

**Comment by waynefoltaERI** [comment]
Ah, makes sense. So when I do simply `(1 | RE1)`, it's doing what I want? When I do `ranef`, I get only a single value, not one per category, and I was thinking this couldn't make sense. Am I just misunderstanding or is `ranef` not showing what I think it's showing?

**Comment by paul-buerkner** [comment]
Which version of brms are you using? With the latest release version (1.5.1), you should get multiple effects. For instance, whn I run

```R
fit<- brm(rating ~ period + carry + treat + (1|subject),
            data = inhaler, family = categorical, iter = 500,
            prior = set_prior("normal(0,5)"),
            chains = 2, cores = 2)
ranef(fit)
```

I get multiple effects.

**Comment by waynefoltaERI** [comment]
Ah, my bad. In my simplified formula, I had 5 RE's, each with hundreds of levels, and the way `ranef` displays it is to repeat these five RE's three times (for four levels in my target variable), with an attribute to identify which is which. I was looking for something like `$RE1:level2`, `$RE1:level3` or a two-dimensional table such as when there are random slopes. I didn't notice the attribute and didn't scroll far enough back. Thanks!

So this Issue all boils down to adding a warning/error when `cs` is used in a non-ordinal regression's group-level effect. I'll close it.

**Comment by paul-buerkner** [comment]
Thanks, I will think of ways to improve the output of `ranef` and I will leave this issue open until I added the error message for group-level effects of `cs`.
