### ISSUE TITLE
zero length column in hypotheses

### ISSUE THREAD

**Issue by puterleat** [paul-buerkner/brms#196]
This is a tiny bug, but when trying to use the df produced by hypotheses
```
tests <- hypothesis(m, h)
name(tests$hypothesis))
```

this produces:

```
[1] "Estimate"   "Est.Error"  "l-95% CI"   "u-95% CI"   "Evid.Ratio" ""      
```
Note the zero length last column, which leads to some problems with dplyr etc when trying to manipulate columns.

Could this last column be renamed `sig` or `star`?

**Comment by paul-buerkner** [comment]
Good point. I will fix that.

**Comment by paul-buerkner** [comment]
The column is now named `Star` (I want to avoid any reference to "significance")
