### ISSUE TITLE
Allow hypothesis testing for non-brmsfit objects

### ISSUE THREAD

**Issue by puterleat** [paul-buerkner/brms#198]
Sometimes it's quicker to run stan_glm than brm, but it's a shame to miss out on nice features of brms like hypothesis test. I realise you might not consider this core functionality, but would it be possible to pass posterior samples from other stanfit objects (using their as.data.frame method) and still use the hypothesis function?

**Comment by paul-buerkner** [comment]
That sounds like a good idea! We could make an `hypothesis.data.frame` or an `hypothesis.stanfit` method (or both). Not sure if we will end up with the exact same functionality as for `brmsfit` objects (in particular all the stuff using prior samples will likely not work), but all the basic stuff should work without problems.

**Comment by jgabry** [comment]
You can try, but there's a hidden self-destruct mechanism that will be triggered if you try to do a hypothesis test using an rstanarm object ;)

**Comment by paul-buerkner** [comment]
That is why I won't use `stanreg` objects, but possible `data.frame` or `stanfit` ;-)

**Comment by paul-buerkner** [comment]
You can now call `hypothesis` for all objects, which are coercible to a `data.frame` (including `stanreg` objects) ;-)
