### ISSUE TITLE
Print divergent transitions warnings with `summary(fit)`

### ISSUE THREAD

**Issue by tomwallis** [paul-buerkner/brms#199]
Hi Paul

I think it would be useful to be able to see if there were divergent transitions for a model fit with a call to `summary(fit)`. I often fit models on a remote workstation, and if I fit a few in the same tmux session then the warnings can be lost. Would it be difficult to add the Stan warning message to the bottom of the summary (maybe underneath "Samples were drawn ...")?

**Comment by paul-buerkner** [comment]
Hi Tom,

I like the idea. Should we rather add this as a warning (similar to the warning returned when rhats are > 1.1) or as part of the printed output?

**Comment by tomwallis** [comment]
Maybe as a warning is a good idea. It's also useful to print the link to the docs:
http://mc-stan.org/misc/warnings.html#divergent-transitions-after-warmup

**Comment by paul-buerkner** [comment]
Basically, I will mirror the warning returned by rstan after model fitting, I guess.

**Comment by paul-buerkner** [comment]
Should be implemented now. :-)

**Comment by tomwallis** [comment]
Great, thanks Paul!
