### ISSUE TITLE
Expand the coef method to return more than just point estimates

### ISSUE THREAD

**Issue by paul-buerkner** [paul-buerkner/brms#200]
See https://groups.google.com/forum/#!topic/brms-users/z3lg3GsQbxE for a discussion.

**Comment by tomwallis** [comment]
Thanks Paul. I'm proud to be involved in `brms`'s 200th issue!

**Comment by paul-buerkner** [comment]
I reworked the `fixef`, `ranef`, `coef`, and `VarCorr` methods to be more flexible and consistent with other post-processing functions. If `summary = TRUE`, point and uncertainty estimates of the coefficients are returned. If `summary = FALSE`, the posterior samples of the coefficients are returned, directly.

The now deprecated implementations are available via argument `old`.

@tomwallis Would you mind testing this feature?

**Comment by tomwallis** [comment]
Hi Paul, thanks for implementing this feature. I've implemented a simple test for the `coef` method (see below). Works as expected, with the exception that the `estimate = "median"` argument silently uses the mean rather than the old behaviour. Then I saw in the docs that this method is now depreciated, but I think it would be good to have a warning if the user specifies `estimate = "median"` where `old = FALSE`.


``` r

library(brms)
data(cbpp, package = "lme4")

fit <- brm(incidence | trials(size) ~ period + (1 | herd),
           family = binomial(),
           data = cbpp)

summary(fit)


# Extract herd-level estimates manually (adapted from https://groups.google.com/forum/#!topic/brms-users/z3lg3GsQbxE) -------
fix <- as.vector(as.matrix(fit, pars = "^b_Intercept"))
ran_offsets <- as.matrix(fit, pars = "^r_")
herd_samples <- ran_offsets + fix
# colMeans(comb)  # matches results of coef
# round(coef(fit_learning)$im_name[, 2], 5) == round(colMeans(comb), 5)
herd_CIs <- apply(herd_samples, 2, quantile, probs = c(0.025, 0.5, 0.975))


# Extract herd-level estimates with new brms functionality -----------
herd_CIs_2 <- coef(fit, probs = c(0.025, 0.5, 0.975))

# compare (some nasty indexing); should be TRUE:
all(herd_CIs == t(herd_CIs_2$herd[, , 1][, 3:5]))
TRUE
# YES

# Check means / meds ---------------
herd_CIs_mean <- coef(fit)
herd_CIs_med <- coef(fit, estimate = "median")

# should be false:
all(herd_CIs_mean$herd[, , "Intercept"] == herd_CIs_med$herd[, , "Intercept"])
TRUE
## Oh oh !

# Check using robust argument --------------
herd_CIs_mean <- coef(fit)
herd_CIs_med <- coef(fit, robust = TRUE)

# should be false:
all(herd_CIs_mean$herd[, , "Intercept"] == herd_CIs_med$herd[, , "Intercept"])
FALSE
# Yes!

```

I haven't tested the other functions yet, but I assume they work off the same generative code?

**Comment by paul-buerkner** [comment]
Thanks for testing! I will add a warning when `estimate = "median"` and `old = FALSE`.

`VarCorr` is a bit different than the other three, but I think there is no need for further external testing.
