### ISSUE TITLE
Improve efficiency for IRT models

### ISSUE THREAD

**Issue by paul-buerkner** [paul-buerkner/brms#203]
Many IRT models are support by brms through it's non-linear syntax. For instance, 1, 2 and 3PL models with items as fixed effects and persons as random effects can be specified as follows:

```R
# 1PL (Rasch) model with discrimination fixed to 1
fit1PL <- brm(y ~ 0 + item + (1|person), <data>, family = bernoulli())

# 2PL model
fit2PL <- brm(
  bf(y ~ exp(disc) * eta,
     disc ~ 0 + item,
     eta ~ 0 + item + (1|person),
     nl = TRUE),
  <data>, 
  family = bernoulli(),
  prior = <some priors>
)

# 3PL
fit3PL <- brm(
  bf(y ~ inv_logit(guess) + (1 - inv_logit(guess)) * inv_logit(exp(disc) * eta),
     guess + disc ~ 0 + item,
     eta ~ 0 + item + (1|person),
     nl = TRUE),
  <data>, 
  family = bernoulli("identity"),
  prior = <some priors>
)
```

With regard to efficiency, the main problem with this implementation is the use of design matrices for the item effects. As every observation depends only on a single item, the design matrix is super sparse with only a single 1 in each row and 0 otherwise. 

The obvious solution it to use the sparse matrix multiplication implemented in Stan. This will reduce RAM requirements but does not really lead to a speed increase. Unless the data is super sparse (above 95% or so), efficiency will even be decreased. 

Thus, I favor a different solution: We could add a special function (let's call it `fun` for the moment) that could be used in the model formulae around item (i.e. `0 + fun(item)` instead of `0 + item`). This should then be parsed to Stan code looking as follows:

```
eta[n] = eta[n] + item[item_index[n]]
```

**Comment by charlesmalpas** [comment]
Hi Paul,

This is very exciting. I was wondering if it is possible to extend the IRT model to the graded response model? I can see how to do this for a single item (as per the BRMS overview), but can't quite work out how to do this for multiple items (if that is even possible!).

Kind regards,
Charles

**Comment by paul-buerkner** [comment]
Can you be more specific on how the model looks like that you have in mind?

Am 23.09.2017 03:09 schrieb "Charles Malpas" <notifications@github.com>:

**Comment by charlesmalpas** [comment]
Hi Paul,

Sorry for the delay. The model structure would be essentially that same as your 2PL model above, except that he response variable (y) would be ordinal. The discrim, difficulty, thresholds, and theta parameters are then estimated. The specific model most often used is Samejima's graded response model (GRM):

Samejima, F. (1997). Graded response model. In Handbook of modern item response theory (pp. 85-100). Springer New York. (https://link.springer.com/chapter/10.1007/978-1-4757-2691-6_5).

This model is also implemented in the [mirt package](https://cran.r-project.org/web/packages/mirt/) by passing itemtype="mirt" to mirt(). 
 
Please let me know if I can provide any more information.

Kind regards,

Charles

**Comment by paul-buerkner** [comment]
Hi Charles,

unfortunately, the nonlinear syntax of brms is not supported in ordinal models, but I have implemented a special parameter call `disc` (for discrimination) in these models to compensate for that (not that discriminations are modeled on the log-scale by default). You could try for instance

```R
brm(bf(y ~ ... + (1|item), disc ~ ... + (1|item)), ..., family = cumulative())
```

Not sure how close this comes to the original formulation of the graded response model.

**Comment by charlesmalpas** [comment]
Thanks Paul! I will give it a try.

**Comment by paul-buerkner** [comment]
After some more thought, I think this is actually a non-issue, since we should usually treat items as group-level effects, as well. In this case, the described indexing is done anyway, in addition to stabalizing the items' estimates via partial pooling.
