### ISSUE TITLE
[feature request] allow manipulation of levels for two-way interactions in marginal_effects()

### ISSUE THREAD

**Issue by silberzwiebel** [paul-buerkner/brms#205]
Hi,

currently, the `marginal_effects()` visualizations for a two-way interaction of continuous predictors show one predictor at the x-axis and three levels of the second one (mean and mean ± SD) as colored lines.
I wondered whether it is possible to manually specify these three levels to something different than mean and mean ±  SD. 

For instance, I would be interested to plot four levels that correspond to four different experimental conditions which would make it easier to interpret the plots (e.g., the blue line shows the mean of predictor X for exp. condition Y, the yellow line shows the mean of predictor X for exp. condition Z, ...)

I did not find such option and would be grateful if you could implement this.
Thanks a lot!

**Comment by paul-buerkner** [comment]
You are right, currently there is no such option implemented. Do you have a suggestion, how a convenient interface for this feature could look like?

**Comment by silberzwiebel** [comment]
Since in my mind this is closely connected to the conditions feature,
I'd suggest an option called `interaction_conditions`.
The default would then be something like

```
marginal_effects( ..., interaction_conditions = c(mean-sd, mean,
mean+sd), ...)
```

and one could specify different, possibly precomputed values in this
argument like

```
marginal_effects( ..., interaction_conditions = c(0.2, 0.6, 0.4, 0.8), ...)
```

It would be cool, if also function calls would be allowed, so one could
specify a function and does not need to precompute the values, so instead of

```
marginal_effects( ...., interaction_conditions = c(mean(data[expCond ==
"A",]$predictor), mean(data[expCond == "B"]$predictor)), ...)
```

somethink like this

```
marginal_effects( ...., interaction_conditions = c(expCond, "A", "B")), ...)
```

where the default is then to take the mean of the data subset where the
column expCond equals the following arguments ("A" or "B"). Not sure
whether a brmsfit object has these columns, though, if they were not in
the formula.

**Comment by paul-buerkner** [comment]
The feature is now implemented in the dev version of brms on github. I named the argument `Iconditions` as `interaction_conditions` appeared to be too long (this is subject to debate of course). Passing functions is possible, although the special situation you mentioned is likely not covered by it.

I would by grateful if you tested this feature and provided feedback both on the feature itself as well as on its documentation.

**Comment by silberzwiebel** [comment]
Thanks, that was quick!

> The feature is now implemented in the dev version of brms on github. I named the 
> argument |Iconditions| as |interaction_conditions| appeared to be too long (this 

what about |interact_cond| as a compromise between brevity and
informativeness?

> is subject to debate of course). Passing functions is possible, although the 
> special situation you mentioned is likely not covered by it.
> 
> I would by grateful if you tested this feature and provided feedback both on the 
> feature itself as well as on its documentation.

Everything I tested, worked like I would expect. (Did not test function
passing, though).
Documentation looks good, too.

I do have one more request, though: Although I like that the default
labels for the different colored lines are numbers now (I do not have
factorial predictors at hand here) because it gives a better feeling
about their actual value, I would like to label the "interaction
conditions" with meaningful labels in the context of the data/experiment.
Either like the "normal" conditions using the row-names (so, the |list|
should then probably be a |data.frame|), or in another way.
Having the possibility to add labels would then also provide an option
to manually restore the mean +/- SD labels if one wishes to do so.

**Comment by paul-buerkner** [comment]
Hmm `interact_cond` is fine as well, but for consistency I would like to keep the `conditions` at the end. What about `int_conditions` or does that invoke a different association?

The problem with data.frames is that we might have different interaction plots each with a different number of interaction conditions, and so need input of varying length. I think the easiest way is to use named vectors. For instance 

```R
Iconditions = list(x = setNames(c(1:3), c("a", "b", "c")))
```

Note that you may always take the `ggplot` object created by the `plot` method and amend it manually. See `?marginal_effects` for an example.

**Comment by paul-buerkner** [comment]
Using named vectors to label interaction conditions is now possible. Moreover, I have renamed `Iconditions` to `int_conditions`, which I think is more consistent with how I name arguments in brms.

Is there anything more to consider or can we close this issue?

**Comment by silberzwiebel** [comment]
Thanks, it works.
Didn't heard of named vectors before.
Could you add one more sentence to the documentation where it says that
the names of the named vectors are used as labels?

And there is a potential confusion: In the documentation you wrote

> An optional named list [...] The names of int_conditions have to match
the variable names exactly.

The first "named" corresponds to setNames(), correct? The second
"names", however, corresponds to the names of the variables, right?

Apart from that, the issue is resolved for me, thanks again.

**Comment by paul-buerkner** [comment]
Thanks for reviewing the functionality! Actually, both "names" refer to the names of the variables. I will clarify that.
