### ISSUE TITLE
poster_predict for drift diffusion model incomplete

### ISSUE THREAD

**Issue by gbiele** [paul-buerkner/brms#206]
Hello,
first thanks for the great package!!

It seemt to me that the posterior_predict function produces incomplete results for the  wiener family.
The function returns only RTs, but for wiener first passage time distribution it should return both the RT and at which boundary the processes ended*.

Or am I missing something?

Best - Guido

*if the posterior_predict function is set up to generally return one matrix, one could simply give the lower boundary responses a negative RT.

**Comment by paul-buerkner** [comment]
Hi Guido,

you are right. I am not yet sure how to solve this, but I will give it some thoughts today.

**Comment by gbiele** [comment]
I think the solution is actually not so hard:
1) generate responses and response times from model and data
2) multiply RTs for lower boundart responses with -1
3) return matrix with RTs

having negative RTs for lower boundary responses is anyhow standard in most packages that fit the DDM. so you could use this coding als for the input data (instead of the dec() ... flag)

Viele Gruesse - Guido

**Comment by paul-buerkner** [comment]
For posterior_predict, you are right, but this is not the only function that matters (+ backwards compatibility). So it is not a matter of doing it but more of doing it in a way that everything is still consistent (and noboday runs into problems when changing default behavior without notice). 
I expect to have a good implementation in a few hours.

**Comment by paul-buerkner** [comment]
In the dev version of brms on github, you may now use the `negative_rt` argument to get what we have discussed. You can install the dev version via

```R
if (!require("devtools")) {
  install.packages("devtools")
}
devtools::install_github("paul-buerkner/brms", dependencies = TRUE)
```

**Comment by gbiele** [comment]
Just to clarify: You mean to use negative_rt only when calling
posterior_predict, correct?
Or can it now also be used when calling brm (this would be convenient, but
is not necessary).

**Comment by paul-buerkner** [comment]
It is just for `predict` and `posterior_predict`. With regard to model specification, I will stick to `dec()` for now.

**Comment by gbiele** [comment]
OK,
thanks a lot for the very quick fix!

**Comment by paul-buerkner** [comment]
Thanks for reporting this issue!
