### ISSUE TITLE
marginal_effects: all points are plotted despite conditioning

### ISSUE THREAD

**Issue by silberzwiebel** [paul-buerkner/brms#208]
I had this with my data and then checked with the example given in the documentation:
Although it is stated that if `points = TRUE` and conditions are given only those points that actually match the conditions are plotted, the three subplots of the example in the documentation (and for my data) show all data points.

I'm not sure, if the `rug` argument should behave the same (it is not explicitly stated), I think it should also only show rugs for data points that match the conditions (at the moment it also plots rugs for all data points).

Possibly, this issue is just a documentation issue because I could imagine that for metric predictors most data points won't match the conditions exactly and therefore the feature of the points argument is only implemented for categorical predictors.
If so, I'd rather like to see an implementation also for metric predictors (possibly by specifying ranges for the metric predictors for which to show data points / rugs) than an update of the documentation ;)

**Comment by paul-buerkner** [comment]
Yep, it is a documentation issue. `points` is only affected by factors in `conditions` for the reason you mentioned. I will add a feature for metric predictors, but don't know if it will go into the next release.

**Comment by paul-buerkner** [comment]
Argument `select_points` should now allow selecting points of metric predictors in conditions. Feel free to close this issue if you are happy with the implementation :-)

**Comment by silberzwiebel** [comment]
Thanks, that was quick again ;)
I've tried the argument and it works fine. However, I'm not sure if this is the most user-convenient way to implement this (it might be the most developer-convenient way, though ;)).
When testing this, I had trouble to map the "scaled to unit interval" to my actual data values. I would find it more easy, if it would be possible to define as many ranges as there are conditions.
Something like:
```
marginal_effects(..., 
conditions = data.frame(predX = c(-0.3, 0.7),  
select_points = c(predX > -0.5 & predX < 0.0, predX > 0.2 & predX < 1.0) 
))
```

This would enable users to reason in terms of their actual values and also allow to exclude/include differing ranges of points for different conditions.
Not sure, how much work it is to implement it like this ...

**Comment by paul-buerkner** [comment]
I agree that for your particular case, this is more appropriate, but from a general implementation perspective, the argument structure you are proposing does not seem feasible for me as it is too specific.

Anyway, I think the unit interval is relatively straight forward and also used in other packages. Just normalize you variable to [0, 1] via `(x - min(x)) / max(x) - min(x))`. For now, I will leave `select_points` as it is, I am happy to add further options in the future.

**Comment by silberzwiebel** [comment]
Alright, I'll agree that my use case might be too specific. I'm closing this issue now, as the implementation works as expected.
