### ISSUE TITLE
Beta distribution domain

### ISSUE THREAD

**Issue by guillaumechaumet** [paul-buerkner/brms#209]
According to some authors see [wiki](https://en.wikipedia.org/wiki/Beta_distribution) or [wolfram](http://mathworld.wolfram.com/BetaDistribution.html), there is a debate on whether or not domain is limited to (0,1) or [0,1]. In your implementation of Beta, you chose (0,1). I have seen that you have implemented a zero inflated beta distribution that works with zero and one. 
Did you add a [0,1] beta distribution that I have not seen ?
By the way, very nice package
Cheers

**Comment by paul-buerkner** [comment]
I use (0,1) because the implementation of the beta distribution in Stan has support only on (0, 1) as otherwise we run into problems with log p = - Inf.

There is currently no "zero_one_inflated_beta" family, but I can certainly add one.
