### ISSUE TITLE
How to proceed to non-centered reparametrization with "brm" ?

### ISSUE THREAD

**Issue by atrolle** [paul-buerkner/brms#211]
Hello,

I fit a model with the "brm" function as follows :

fit1 <- brm(formula = MOYENNE | cens(Censored) ~ BAC_DOMINANTE + (1|Etablissement) ,
                                        data = data, family = lognormal(),
                                        warmup = 10000, iter = 20000, chains = 4, cores = 8,
                                        control = list(adapt_delta = 0.9999))

But I got a warning message :
1: There were 56 divergent transitions after warmup. Increasing adapt_delta above 0.9999 may help. See
http://mc-stan.org/misc/warnings.html#divergent-transitions-after-warmup 
2: Examine the pairs() plot to diagnose sampling problems

I read with much attention the help section entitled "Divergent transitions after warmup" at this URL.
I could remark that divergent transitions occur below the diagonal of the pairs() plot.
As the "adapt_delta" parameter value is already very high, the only solution I see to avoid these divergent transitions is to use (non-centered) reparametrization. 

How should I proceed to reparametrization while using the "brm" function?
I found a closed issue (#74) entitled "Is reparametrization necessary/possible in brms?", but the thing is that I do really have to worry about reparametrization.

Thank you in advance for your help.

Best regards,
Arnaud.

**Comment by paul-buerkner** [comment]
brms already uses the non-centered parameterization so that is not the the reason for your divergent transistions.

Instead of the `lognormal` family, you could try `weibull` and see if this family works better. 

As a side question: Do you really need 10k warmup and 20k iterations? The default values of 1k and 2k (or somewhat higher in some cases) should usually be fine.

**Comment by atrolle** [comment]
Thank you Paul. Using weibull familiy works better!! 

Moreover, you're right; I do no need so many iterations.

Best regards,

**Comment by paul-buerkner** [comment]
Great! :-)
