### ISSUE TITLE
Add shifted lognormal distribution

### ISSUE THREAD

**Issue by awellis** [paul-buerkner/brms#218]
Hi Paul, 

would you be willing to add the shifted lognormal distribution for modelling response time data? This is discussed [here.](https://groups.google.com/forum/#!msg/stan-users/xv-Yjpb7faw/o7SHlrAH7sUJ)

**Comment by paul-buerkner** [comment]
Thanks, I will take a look! :-)

**Comment by paul-buerkner** [comment]
As a follow-up on this: @awellis Do you think the shifted lognormal distribution is superior to the exponentially modified gaussian distribution (family `exgaussian`), which is already implemented in brms?

**Comment by paul-buerkner** [comment]
In the github version, you can now fit shifted lognormal models via family `shifted_lognormal`. The shift parameter is called `ndt` (non-decision time), borrowing name and code from the wiener diffusion model.
