### ISSUE TITLE
multi_normal priors and hierchical priors

### ISSUE THREAD

**Issue by ljstrnadiii** [paul-buerkner/brms#219]
Hi, 

I am working on a final project in my Bayesian course. Brms has been a really nice package! I am super impressed. 

My professor wants me to implement a g-prior regression, but I am not sure if there is a multivariate prior sampler. In addition to a multivariate normal sampler, is there a way to build "hierarchical priors"? 

I basically want:

set_prior("multi_normal(0, sigma^2*csq*V)")
where sigma ~ InvGamma(a,b)
csq = number of obs
V = solve(crossprod(X))

is there a way to do this with brms?

**Comment by paul-buerkner** [comment]
Can you be a bit more specific about the model (and the corresponding prior) you want to implement?

**Comment by ljstrnadiii** [comment]
I can try.

The data I have are all continuous. The model is a normal family and the stan model that implements exactly what I want is 
```
stanmod="
data {
    int<lower=1> n; // number of observations 
    vector[n] y; // data
    matrix[n, 11] X; //covariates
    vector[11] mu0; //prior mean for beta
    cov_matrix[11] V; //V part of Zellner's g-prior
    cov_matrix[n] I; //nxn identity matrix
    real<lower=0> csq; //constant for Zellner's g-prior
    real<lower=0> v; //sample variance
}
parameters {
    real<lower=0> prec;
    vector[11] beta;


}
transformed parameters{
    real<lower=0> sigmasq;
    vector[n] mu;
    sigmasq = 1/prec;
    mu = X*beta;

}
model {
    //specify priors
    beta ~ multi_normal(mu0, sigmasq*csq*V);
    prec ~ gamma(0.01, 0.01); 
    // we have independet data  
    //y~multi_normal(X*beta,sigmasq*I);
    for(i in 1:n) y[i] ~ normal(mu[i],sqrt(sigmasq));
}
generated quantities {
    real Rbsq;
    Rbsq = 1-sigmasq/v;
}"
```
where the stan data is specified as 
```
# make list stan data
stan_dat <- list(n = nrow(train), y = train$imdb_score,
                X = X, mu0 = mu, V = solve(crossprod(X)), 
                I = diag(nrow(train)), csq = nrow(train), v = var(train$imdb_score))
```
and the stan fit call is 
```
fit3 <- stan(model_code = stanmod, data = stan_dat, 
            iter = 10000, chains = 4)
```

What I have not been capable of figuring out in brms is how to set a multi_normal prior and implement a 2-stage sampler--use sampled values of sigma in the dispersion of the multi_normal prior on betas.

**Comment by paul-buerkner** [comment]
Ok I see, thanks! Unfortunately, brms does not support multivariate priors on the regression coefficients or special data in the priors. So I think, this model is not yet possible with brms (but might be possible in the future).

As a side note, I would not put a gamma prior on the precisions, but a half-student (or half normal) on the standard deviation sigma directly. In Stan, we don't care about conjugate priors anymore. Furthermore, you may want to vectorize the likelihood statement and use

```
y ~ normal(mu, sqrt(sigmasq));
```

**Comment by ljstrnadiii** [comment]
Good catch! Thanks for the feedback. 

I wonder what it would take to make this possible. Do you have an idea of what it would take in order to implement this? 

I have yet to make any github contribution and it could be a cool side project. It would actually be nice to just specify a prior as g_prior like the lasso for simplicity. Maybe I'll fork the repo and play with it a little.

**Comment by paul-buerkner** [comment]
It is actually not too difficult to implement. We can already right, for example:

```
make_stancode(count ~ Trt_c * log_Base4_c, epilepsy,
              prior = prior(multi_normal(mu0, sigma^2*csq*V)))
```

and the only thing that keeps the stancode from compiling is that `mu0`, `csq` and `V` are not defined in the data block. So what we need is an interface that takes the data as well as the stan code for the data and puts it into the right places.

**Comment by ljstrnadiii** [comment]
I would have to take some time to get familiar with your code. I am not even sure where your code accepts the string generated by make_stancode to even make a brms object. Can you show me an example of how we can use make_stancode to actually fit a brm model?

**Comment by paul-buerkner** [comment]
No worries, I didn't expect you to implement this feature, yourself :-)

I already have an idea how to the code should look like and will implement is as soon as I have time.

For your benefit: `make_stancode` generates the stancode, `make_standata` generates the data passed to Stan and `brm` calls both to fit the model.

**Comment by ljstrnadiii** [comment]
Thanks!

Last question: assume I have the standata and Stanmod defined above is there a way to pass those to the brm object to keep my models consistent? I just prefer to have the same diagnostics and plots across all my models. I see how you break apart the data and then sample with 
'rstan::sampling' etc. 

I have two brms models and then this one Stan object defined above.

**Comment by superdayv** [comment]
Just following up on this, am I correct that it is still currently not possible to set priors on fixed effects when there are multiple outcome variables (i.e., when using cbind() )?

Thanks!

**Comment by paul-buerkner** [comment]
You can set priors on fixed effects of course also in multivariate models. See `?set_prior` and `?get_prior`.

With regard to the topic of this issue, we cannot pass additional data yet, which is required in the priors, but maybe this will be part of 2.0 once I get a good idea about an appropriate interface.

**Comment by paul-buerkner** [comment]
I am pretty sure it's to late to apply it to the final project in your Bayesian course, but the feature you proposed is finally implemented in the latest github version if brms.

Using your example, you can now go for 

```R
<define csq and V in R>
prior <- set_prior("multi_normal(0, sigma^2 * csq * V)")
stanvars <- stan_var(csq) + stan_var(V)
fit <- brm(y ~ x, data, prior = prior, stan_vars = stanvars)
```

See `?stan_var` for more details.

**Comment by ljstrnadiii** [comment]
Great! Thanks Paul!
