### ISSUE TITLE
Gaussian processes

### ISSUE THREAD

**Issue by paul-buerkner** [paul-buerkner/brms#221]
Gaussian processes provide approach to modelling non-linear relationships. All the basic stuff is already available in the dev version of **brms** on github, but some of the more advanced features are still missing.

- [x] Univariate Gaussian processes
- [x] Multivariate Gaussian processes
- [x] Add argument `by` as in `mgcv::s`
- [x] Compatibility with S3 methods
- [x] More documentation
- [x] More unit tests

**Comment by jebyrnes** [comment]
This is amazing. Browsing through the code/helpfile examples, I noticed that the 'location' is set by a single argument, which is ideal for timeseries. However, does this miss space (which is what you might mean by MV GP, but I'm not sure), for which you'd only need a coordinate system? So excited you're doing this.

FYI, I've found http://www.jameskeirstead.ca/blog/gaussian-process-regression-with-r/ invaluable for new predictions using posterior estimates of the covariance function - easy to turn the heart of this code into a function for use in prediction.

**Comment by paul-buerkner** [comment]
I assume with 'location' you mean 'covariates' / 'predictors'? Indeed for spatial GPs we need two covariates and this is what I call MV GP. It should be working within the next few days.

Predictions from GPs are already fully implemented in **brms**. See function `gp_predictor` in https://github.com/paul-buerkner/brms/blob/master/R/linear_predictor.R

**Comment by jebyrnes** [comment]
Yup! You are amazing as ever.

On May 2, 2017, at 4:44 AM, Paul-Christian Bürkner <notifications@github.com<mailto:notifications@github.com>> wrote:


I assume with 'location' you mean 'covariates' / 'predictors'? Indeed for spatial GPs we need two covariates and this is what I call MV GP. It should be working within the next few days.

Predictions from GPs are already fully implemented in brms. See function gp_predictor in https://github.com/paul-buerkner/brms/blob/master/R/linear_predictor.R

**Comment by paul-buerkner** [comment]
Multivariate Gaussian processes are now fully implemented. :-)

**Comment by jebyrnes** [comment]
Q: does ~ x1 + x2 | group work here, or is that what the by argument is for?

**Comment by paul-buerkner** [comment]
The by argument will allow one to fit separate gaussian processes for different groups.

**Comment by paul-buerkner** [comment]
The `by` argument is now fully implemented. You can fit separate Gaussian processes for different groups via
```
gp(x, by = group)
```
when `group` is non-numeric variable,
