### ISSUE TITLE
Switch exgaussian to Stan's exp_mod_normal?

### ISSUE THREAD

**Issue by aforren1** [paul-buerkner/brms#222]
What do you think about using `exp_mod_normal` from Stan in place of `exgaussian`, which seems to lead to faster sampling? I don't think it would affect anything else in the API. The diff between master and a test branch is [here](https://github.com/paul-buerkner/brms/compare/master...aforren1:exgauss).

Toy example below (I'm also not entirely sure what the "right" way to benchmark these things is, and also not sure if this is sufficient to demonstrate an improvement):
```r
library(brms)

set.seed(1)
n <- 10000
dat <- data.frame(y = rnorm(n, 300, 50) + rexp(n, 1/80),
                  x = rnorm(n))

m_b <- brm(y ~ x, data = dat,
           family = exgaussian(),
           prior = c(prior('normal(300, 20)', class = 'Intercept'),
                     prior('normal(50, 10)', class = 'sigma'),
                     prior('normal(80, 10)', class = 'beta')),
           seed = 1, chains = 1)
```
Single chain timings:

| Branch | Elapsed Time (s) | Sampling Time (s) | Total Time (s) | 
| -------- | -------- | -------- | -------- |
| master | 130.777 | 63.997 | 194.774 |
| exgauss | 80.939 | 50.095 | 131.034 |

Population-level parameters from master branch:
<table>
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:right;"> Estimate </th>
   <th style="text-align:right;"> Est.Error </th>
   <th style="text-align:right;"> l-95% CI </th>
   <th style="text-align:right;"> u-95% CI </th>
   <th style="text-align:right;"> Eff.Sample </th>
   <th style="text-align:right;"> Rhat </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Intercept </td>
   <td style="text-align:right;"> 300.712143 </td>
   <td style="text-align:right;"> 1.2485814 </td>
   <td style="text-align:right;"> 298.278479 </td>
   <td style="text-align:right;"> 303.039085 </td>
   <td style="text-align:right;"> 453.1835 </td>
   <td style="text-align:right;"> 1.0020754 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> x </td>
   <td style="text-align:right;"> -0.442004 </td>
   <td style="text-align:right;"> 0.7609208 </td>
   <td style="text-align:right;"> -1.896372 </td>
   <td style="text-align:right;"> 1.068618 </td>
   <td style="text-align:right;"> 766.9210 </td>
   <td style="text-align:right;"> 0.9992422 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> sigma </td>
   <td style="text-align:right;"> 51.330000 </td>
   <td style="text-align:right;"> 0.9231845 </td>
   <td style="text-align:right;"> 49.510706 </td>
   <td style="text-align:right;"> 53.183079 </td>
   <td style="text-align:right;"> 513.6079 </td>
   <td style="text-align:right;"> 1.0008046 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> beta </td>
   <td style="text-align:right;"> 79.062949 </td>
   <td style="text-align:right;"> 1.3608895 </td>
   <td style="text-align:right;"> 76.336169 </td>
   <td style="text-align:right;"> 81.631918 </td>
   <td style="text-align:right;"> 405.2558 </td>
   <td style="text-align:right;"> 1.0017766 </td>
  </tr>
</tbody>
</table>

Population-level parameters from exgauss branch:
<table>
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:right;"> Estimate </th>
   <th style="text-align:right;"> Est.Error </th>
   <th style="text-align:right;"> l-95% CI </th>
   <th style="text-align:right;"> u-95% CI </th>
   <th style="text-align:right;"> Eff.Sample </th>
   <th style="text-align:right;"> Rhat </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Intercept </td>
   <td style="text-align:right;"> 300.792858 </td>
   <td style="text-align:right;"> 1.2113787 </td>
   <td style="text-align:right;"> 298.276924 </td>
   <td style="text-align:right;"> 303.162023 </td>
   <td style="text-align:right;"> 489.3372 </td>
   <td style="text-align:right;"> 0.9995608 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> x </td>
   <td style="text-align:right;"> -0.422833 </td>
   <td style="text-align:right;"> 0.7605313 </td>
   <td style="text-align:right;"> -1.907526 </td>
   <td style="text-align:right;"> 1.073586 </td>
   <td style="text-align:right;"> 801.7829 </td>
   <td style="text-align:right;"> 0.9992946 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> sigma </td>
   <td style="text-align:right;"> 51.366906 </td>
   <td style="text-align:right;"> 0.8654715 </td>
   <td style="text-align:right;"> 49.709587 </td>
   <td style="text-align:right;"> 52.938834 </td>
   <td style="text-align:right;"> 622.6410 </td>
   <td style="text-align:right;"> 0.9990455 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> beta </td>
   <td style="text-align:right;"> 78.972200 </td>
   <td style="text-align:right;"> 1.3551520 </td>
   <td style="text-align:right;"> 76.420599 </td>
   <td style="text-align:right;"> 81.668746 </td>
   <td style="text-align:right;"> 538.5716 </td>
   <td style="text-align:right;"> 0.9990721 </td>
  </tr>
</tbody>
</table>

No big differences, and generally more effective samples using `exp_mod_normal`.

**Comment by paul-buerkner** [comment]
To my shame, I must admist that I didn't realize Stan has a built in exgaussian distribution... Thanks for pointing me to it.

**Comment by paul-buerkner** [comment]
closed via 6f1c18a

**Comment by aforren1** [comment]
No shame! It's a big manual, and there are at least three different ways to refer to this distribution. Also, what do you think about removing the `beta > 0.05 * sigma` conditionals for the `p/dexgaussian` functions in "distributions.R" (it looks like Stan doesn't use that approximation, which might lead to slightly different answers)? Though it would need an extra tweak to prevent underflow, e.g.:

```r
dexgaussian <- function (x, mu, sigma, beta, log = FALSE) 
{
    if (any(sigma <= 0)) {
        stop2("sigma must be greater than 0.")
    }
    if (any(beta <= 0)) {
        stop2("beta must be greater than 0.")
    }
    args <- nlist(x, mu, sigma, beta)
    args <- do.call(expand, args)
    args$z <- with(args, x - mu - sigma^2/beta)
    # switch log(pnorm(z/sigma)) for pnorm(z/sigma, log.p = TRUE) to prevent underflow
    out <- with(args, -log(beta) - (z + sigma^2/(2 * beta))/beta + pnorm(z/sigma, log.p = TRUE))
    if (!log) {
        out <- exp(out)
    }
    out
}
```

It only *slightly* changes the result at small betas.

**Comment by paul-buerkner** [comment]
Agreed. I changed that accordingly.

**Comment by aforren1** [comment]
Thanks for the changes!

**Comment by paul-buerkner** [comment]
Thank you for your help! :-)
