### ISSUE TITLE
LOO function for brmsfit

### ISSUE THREAD

**Issue by christinamaiello** [paul-buerkner/brms#225]
I noticed in the rstanarm implementation of loo, they have a nice feature where: "If k_threshold is not NULL and there are J observations with k estimates above k_threshold then when loo is called it will refit the original model J times, each time leaving out one of the J problematic observations. The pointwise contributions of these observations to the total ELPD are then computed directly and substituted for the previous estimates from these J observations that are stored in the object created by loo"

Based on the brms documentation it doesn't seem like the LOO function takes this approach when used on brmsfit objects. Is this a feature that can be added? 

Many thanks,

Christina

**Comment by paul-buerkner** [comment]
Pointwise substitution of ELPD components is now possible using the `reloo` method. K-fold cross-validation is now possible via method `kfold`.
