### ISSUE TITLE
Offset in add_ic

### ISSUE THREAD

**Issue by lian0060** [paul-buerkner/brms#227]
Hi,
Is offset supported in add_ic? I tried to fit a model with formula

z~bathy_011992+crw+ (bathy_011992+crw|tid) + offset(log(tau+0.001))

Let r denote the fitted object, then the following error messages appear. 
> r1 <- add_ic(r,ic="waic")
Error in offset(log(tau + 0.001)) : object 'tau' not found
> r1 <- add_ic(r,ic="loo")
Error in offset(log(tau + 0.001)) : object 'tau' not found

Thanks
dong

**Comment by paul-buerkner** [comment]
This should be working and I am trying to fix it right now. Thanks for reporting this issue!

**Comment by paul-buerkner** [comment]
Hmm, the following example works for me with brms 1.7.0 (current release version):

```R
test = data.frame(z = rnorm(100), bathy_011992 = rnorm(100),
                  crw = rnorm(100), tau = abs(rnorm(100)),
                  tid = rep(1:10, each = 10))

library(brms)
fit <- brm(z~bathy_011992+crw+ (bathy_011992+crw|tid) + offset(log(tau+0.001)),
           data = test)

add_ic(fit)
```

Could you check whether it works for you as well? If yes, could you provide a reproducible example with which the error occurs?

**Comment by lian0060** [comment]
I did the following that caused this error message.
> fit$formula <- z ~ bathy_011992 + crw + (bathy_011992 + crw | tid) + offset(log(tau1 + 0.001))
> add_ic(fit)
Error in offset(log(tau1 + 0.001)) : object 'tau1' not found

Thanks for your quick response. 
Dong

**Comment by paul-buerkner** [comment]
For what reasons are you changing the formula after fitting the model? Even if it worked it would be super dangerous as the model was fitted with another formula. 

With regard to your problem: `add_ic` cannot find `tau` if it was not originally part of the model, as only variables part of the model are being stored.

**Comment by lian0060** [comment]
I do not want to bore you with my reasons.
Should I close this issue? This is not a bug of the package.

Dong

**Comment by paul-buerkner** [comment]
I would be interested in the reason, since it might be a reasonable application of the package I haven't thought of yet.

The issue can be closed though I think.

**Comment by lian0060** [comment]
I have been using INLA for fitting GLMMs. The INLA interface does not support lme4 formula. So the lme4 formula was first converted into INLA syntax. But the converted formula is not as readable. So I appended the original lme4 formula in the end for reporting.

r$formula  <-   z ~ bathy_011992 + crw + (bathy_011992 + crw | tid) + offset(log(tau1 + 0.001)).

I do not think other users will have the same problem. And thanks for making this package. I will explore it further and let you know if I have questions.
