### ISSUE TITLE
pp_check interval plot fails when x variable has attribute

### ISSUE THREAD

**Issue by ecologics** [paul-buerkner/brms#229]
This issue has been identified in `rstanarm::pp_check()` and fixed as follows: https://github.com/stan-dev/rstanarm/issues/168.

`brms::pp_check(fit, type="intervals", x='variableName')` fails when `variableName` has an attribute.  It can be fixed using `as.numeric()`, and made to work in the interim as follows:

`fit$data$variableName <-  as.numeric(fit$data$variableName)`.

`brms` v.1.7.0.9000

**Comment by paul-buerkner** [comment]
Fixed via 9dc09b5. Thanks for reporting!
