### ISSUE TITLE
Error using . in formula

### ISSUE THREAD

**Issue by waynefoltaERI** [paul-buerkner/brms#23]
When I try to use '.' in a formula, I get the following error:

```R
> system.time (bb2 <- brm (Species ~ ., data=ir2,
+                          family="bernoulli", n.chains=3, n.iter=3000, n.warmup=600,
+                          prior=c(set_prior ("normal (0, 5)"))))
Error in terms.formula(formula) : '.' in formula and no 'data' argument
```

I can spell out all of the columns individually, but the '.' notation is quite useful. I believe brm is using a Formula call under the hood that doesn't supply the 'data' argument.

**Comment by paul-buerkner** [comment]
Thanks for reporting the error. I will try to fix this. :-)

**Comment by paul-buerkner** [comment]
It should be fixed now in the dev version on github. Would you mind retesting it?

**Comment by waynefoltaERI** [comment]
That seems to have done the trick!
