### ISSUE TITLE
Estimate and plot survival functions

### ISSUE THREAD

**Issue by paul-buerkner** [paul-buerkner/brms#232]
I realized that in survival regression it is pretty common to compute and plot the survival functions for different conditions. Using the internal structure of `marginal_effects` this should be relatively straightforward to implement.

**Comment by shannonajw** [comment]
In addition to this, would you be able to advise on estimating shared parameter models (joint models with one or more longitudinal and a survival outcome) in the brms framework? For instance, this site shows how to implement it in JMbayes: http://www.drizopoulos.com/vignettes/multivariate%20joint%20models

**Comment by paul-buerkner** [comment]
for joint models I recommend the stan_jm function of the rstanarm package.

shannonajw <notifications@github.com> schrieb am Fr., 20. Apr. 2018, 18:37:

**Comment by shannonajw** [comment]
Thanks Paul, looks like the stan_jm function is quite good for this, my only gripe is that it doesn't allow smoothing functions (splines) like brms does!

**Comment by paul-buerkner** [comment]
I see. I think there is much discussion about survival models in Stan at the moment. Maybe we will have a good solution for this at some point, but I am not sure what it will be exactly.

**Comment by seonghobae** [comment]
Is this still valid plan who want to do graphing with the brms library?

**Comment by paul-buerkner** [comment]
Yes, but I currently cannot invest so much time into new brms features. Expect a lot more to come in 2020.

**Comment by paul-buerkner** [comment]
This is implemented in bayesplot via https://github.com/stan-dev/bayesplot/issues/233
