### ISSUE TITLE
Add more Gaussian process kernels

### ISSUE THREAD

**Issue by paul-buerkner** [paul-buerkner/brms#234]
Right now, only the exponentiated-quadratic kernel is supported as it has a native implementation in Stan. However, there seem to be quite a few other kernels worth considering. This issue is ment to provide a list of kernels with results concerning their feasibility in Stan.

**Comment by jae0** [comment]
Something like the following would cover the main forms discussed in : 

https://en.wikipedia.org/wiki/Mat%C3%A9rn_covariance_function

`     functions {
            matrix matern_covariance( int N, matrix dist, real phi, real sigma_sq, int COVFN) {
              matrix[N,N] S;
              real dist_phi; 
              real sqrt3;
              real sqrt5;
              sqrt3=sqrt(3.0);
              sqrt5=sqrt(5.0);

              if (COVFN==1) { // exponential == Matern nu=1/2 , (p=0; nu=p+1/2)
                for(i in 1:(N-1)){
                  for(j in (i+1):N){
                    dist_phi = fabs(dist[i,j])/phi;
                    S[i,j] = sigma_sq * exp(- dist_phi ); 
                }}

              
              } else if (COVFN==2) { // Matern nu= 3/2 covariance
                for(i in 1:(N-1)){
                  for(j in (i+1):N){
                   dist_phi = fabs(dist[i,j])/phi;
                   S[i,j] = sigma_sq * (1 + sqrt3 * dist_phi) * exp(-sqrt3 * dist_phi);
                }}
              

              } else if (COVFN==3) { // Matern nu=5/2 covariance
                for(i in 1:(N-1)){
                  for(j in (i+1):N){
                    dist_phi = fabs(dist[i,j])/phi;
                    S[i,j] = sigma_sq * (1 + sqrt5 *dist_phi + 5* pow(dist_phi,2)/3) * exp(-sqrt5 *dist_phi);
                }}
            
              } else if (COVFN==4) { // Matern as nu->Inf become Gaussian (aka squared exponential cov)
                for(i in 1:(N-1)){
                  for(j in (i+1):N){
                    dist_phi = fabs(dist[i,j])/phi;
                    S[i,j] = sigma_sq * exp( -pow(dist_phi,2)/2 ) ;
                }}
              } 

                 
              for(i in 1:(N-1)){
              for(j in (i+1):N){
                S[j,i] = S[i,j];  // fill upper triangle
              }}

              // create diagonal: nugget(nonspatial) + spatial variance +  eps ensures positive definiteness
              for(i in 1:N) S[i,i] = sigma_sq ;            
              return(S)   ;
            }

      }
`

**Comment by paul-buerkner** [comment]
Thanks, this is very helpful!

**Comment by gabriuma** [comment]
To use the Mattern covfun in approximate GP, we just to change the spectral density function (function 'spd' in the Stan code):

       #Spectral density for Mattern nu=3/2
	real spd(real alpha, real rho, real w) {
		real S;
		S = 4*alpha^2 * (sqrt(3)/rho)^3 * 1/((sqrt(3)/rho)^2 + w^2)^2;
		return S;
	}

        #Spectral density for Mattern nu=1/2
	real spd(real alpha, real rho, real w) {
		real S;
		S = 2*alpha^2 * (1/rho) * 1/((1/rho)^2 + w^2);
		return S;
	}

        #Spectral density for Mattern nu=5/2
	real spd(real alpha, real rho, real w) {
		real S;
		S = 16/3*alpha^2 * (sqrt(5)/rho)^5 * 1/((sqrt(5)/rho)^2 + w^2)^3;
		return S;
	}

All the rest Stan code remains the same.

**Comment by benearnthof** [comment]
Has there been an update on this? I'm new to this package and would like to use a Matern kernel in a model, but I'm not sure where to put the Stan code snippets.

**Comment by paul-buerkner** [comment]
I think(?) that matern kernels are not supported in Stan itself so supporting them in brms should not be a major issue. Perhaps I find the time in the upcoming weeks.

**Comment by benearnthof** [comment]
For future reference: It seems like the Matern covariance functions are available in [The Stan Math library](https://github.com/stan-dev/math/blob/develop/stan/math/prim/fun/gp_matern52_cov.hpp)

**Comment by jgradym** [comment]
Just wanted to voice support for adding a Ornstein–Uhlenbeck option for running a brm() function with a phylogeny. This seems to be the new standard evolutionary covariance structure when dealing with phylogenies, as its more realistic than others (ie, consistent with stabilizing selection). An option of model = "OU", "Brownian" etc would be super helpful. As is, I can't use brms for most phylo analyses. Most recent evol packages (using MLE instead of Bayesian) have about 5 standard options (eg see ?phylopars in Rphylopars). But the most important, by far is the OU one. Would be fantastic to get it into brms!

**Comment by potash** [comment]
Hello, I would like to see the Matern covariance functions (specifically `gp_exponential_cov`) in brms. Can I help make this happen? I have been browsing the source code and it seems fairly straightforward. Some questions I have:

0) Do you have any documentation to help new contributors? I have never developed an R package. How do I install it from local source? Do I need to recompile/reinstall every time I modify the source?

1) will the brms `gp(x, sdgp, lscale, zgp)` function in stan take `cov` as a parameter? Does stan have string parameters or will there be a set of constants `int GP_EXP_QUAD_COV=1; int GP_EXPONENTIAL_COV=2;` etc.?

2) How can `.predictor_gp()` get passed the `cov` parameter?

3) Is it necessary to implement the approximate gp for these covariances as well? I feel this should be done eventually but as I and many others do not necessarily need it, it would be OK and faster to start with only exact versions of these kernels and throw an error for approximate.

Thanks!

**Comment by potash** [comment]
Edit: I know see @gabriuma's comment about approximate Matern covariances and see that it should be quite easy so perhaps my third question is moot.

**Comment by paul-buerkner** [comment]
I will add this issue to the list of issues for the next release to make sure I will at least implement the Matern kernels. I will have to think about the best way to implement different kernels in the Stan code so it is a bit hard for me to suggest concrete steps that you could already take to implement this.

**Comment by paul-buerkner** [comment]
This has been implemented in #1688. I added matern and exponential kernels including HSGP versions of the matern kernels. If people need other kernels at some point, I suggest to open new issues for these specific kernels.

**Comment by paul-buerkner** [comment]
Perfect! Thank you!

**Comment by avehtari** [comment]
> @avehtari was there a reason we didn't discuss the Matern 1/2 kernel in our paper?

Trying to get the paper out in finite time?

**Comment by paul-buerkner** [comment]
Fair point. :-D Thanks!

**Comment by gabriuma** [comment]
>Trying to get the paper out in finite time?
basically:-)

We empirically calculated the relationship between HSGP factors (section
4.3) for Matern \inf, 3/2, 5/2, which requires quite a bit of work. In my
experience, these may be the most useful kernels for common applications.
Matern 1/2 is too rough (wiggly) I think.

Gabriel
FISABIO, Environment and Health

**Comment by potash** [comment]
@gabriuma Matern 1/2 is fairly common in soils and agriculture, maybe it's just a historical accident that should be corrected... or maybe it makes sense because these variables can be very rough with a lot of variation (not measurement error) on very short length scales. Maybe they would be better represented as a sum of two smoother kernels but matern 1/2 could be a decent choice for simplicity.

**Comment by paul-buerkner** [comment]
HSGPs for the exponential kernel are now supported.

**Comment by avehtari** [comment]
How about HSGP with periodic kernel? I was going to test the Birthdays case study with brms + Pathfinder, but would need periodic HSGP

**Comment by paul-buerkner** [comment]
yeah should be doable. periodic kernel needs a bit more work because it has
an additional parameter I think. would you mind opening a new issue for it?

Aki Vehtari ***@***.***> schrieb am Sa., 28. Sept. 2024,
20:37:

**Comment by gabriuma** [comment]
Hi,

We implemented an approximate linear representation of a periodic squared
exponential kernel in our paper. Please read section 3.3, then appendix B,
then section 4.4, and finally case study 5.2.

Gabriel
FISABIO, Environment and Health
