### ISSUE TITLE
Three-way interaction plot with marginal_effects?

### ISSUE THREAD

**Issue by atrolle** [paul-buerkner/brms#235]
Hi,

I used brm to fit a two-level linear regression model to my longitudinal data.
In this model, I have a significant three-way interaction between the time trend and two other categorical predictors.  Can I get a three-way interaction plot by using marginal_effects?

Best regards,
Arnaud.

**Comment by paul-buerkner** [comment]
You can use the `conditions` argument of `marginal_effects`. There is an example in `help("marginal_effects")` for this.

**Comment by atrolle** [comment]
Thank  you Paul.
Sorry, I had not seen the last example in the help.
It works fine.

Best,
Arnaud.

**Comment by paul-buerkner** [comment]
Great! :-)
