### ISSUE TITLE
Error in variable models

### ISSUE THREAD

**Issue by inti** [paul-buerkner/brms#237]
Hi, is there a way to fit error-in-variable models? That is models where the predictor has an associated measurement error.
Looking forward !

**Comment by paul-buerkner** [comment]
For measurement error in predictor variables, use function 'me' in the
model formula (see help('me')).

For measurement error in the response use (if, say, y is your response and
sdy is the measurement error on the SD scale):

y | se(sdy, sigma = TRUE) ~ ...

Best
Paul

2017-07-17 4:19 GMT+02:00 Inti Pedroso <notifications@github.com>:
