### ISSUE TITLE
Upgrade to regularized horseshoe

### ISSUE THREAD

**Issue by paul-buerkner** [paul-buerkner/brms#238]
See https://arxiv.org/abs/1707.01694

**Comment by paul-buerkner** [comment]
The regularized horseshoe prior is now working. @jpiironen would you mind double checking my implementation?

Also, I added the argument `par_ratio` as an alternative to specifying `scale_global` directly. If `par_ratio` is given, `scale_global` is computed as `par_ratio / sqrt(nrow(data))`.

**Comment by jpiironen** [comment]
Seems correct to me!

**Comment by paul-buerkner** [comment]
Many thanks for taking a look!!

Am 24.07.2017 16:54 schrieb "Juho Piironen" <notifications@github.com>:
