### ISSUE TITLE
`fitted` method seems to require vectorised `stan_funs`?

### ISSUE THREAD

**Issue by tomwallis** [paul-buerkner/brms#242]
I'm trying to fit a non-linear model using stan, that relies on some (rather ugly) user-specified functions. Specifically, my user-defined function contains an `if` statement of the form:

```r

real res

if (x <= alpha){
    res <- 0.0;
    return res;
}

else if (x > alpha){
    return beta * tanh(gamma * (x - alpha));
}

```
where `x` is data, and `alpha` `beta` and `gamma` are nonlinear parameters.

I can fit the above model with `brm` no problem, and the fitted parameter estimates look reasonable on my simulated data set. However, when I try to generate model predictions using the `fitted` method, I get the following error: 

```r
the condition has length > 1 and only the first element will be used
```

I'm not exactly sure why this is happening, but my guess is that the `fitted` method is passing a vector of data values `x` to the function above, and the `if` statement can only deal with a scalar input (`if` can only evaluate logical of length 1). If I wrap `fitted` in a `for` loop over the rows of the data frame then I get back reasonable-looking values for each row (albeit still a warning on every iteration of the loop, and it's really slow).

I've tried refactoring my stan function to avoid the `if` statement by using a `max` instead:

```r
  real res;
  
  # full function:
  res <- beta * tanh(gamma * (x - alpha));
  
  # cutoff (no negative):
  res <- fmax(0.0, res)
  return res;
```

However, this function gives me an unspecified error when I call `make_stancode` or `brm` (see [this issue](https://github.com/paul-buerkner/brms/issues/241)). Perhaps I'm doing something wrong there.

In any case, am I correct that the `fitted` method might be passing a vector of `x` levels to my custom stan function? Or is the `condition length > 1` error happening somewhere else?

**Comment by paul-buerkner** [comment]
Did you load the Stan functions into to global env beforehand? If you don't load them (so that the relevant function is missing), **brms** should give you the informative error message like:

```
... Most likely this is because you used a Stan function in the non-linear model formula 
that is not defined in R. Currently, you have to write this function yourself 
making sure that it is vectorized. I apologize for the inconvenience.
```

effectively telling you to write a vectorized version of the function in R yourself.

**Comment by tomwallis** [comment]
Ah. I had also written the functions in R (and they were loaded into the global env), so I got the `condition length > 1` error (due to using the `if` statement in the R function) rather than the informative brms error message.

Is there a vignette featuring the custom `stan_funs` argument? I hadn't explicitly realised that one would need to additionally define the functions in the R global environment (I had defined them to generate test data), but of course it makes sense in hindsight (how else could R access a function in a compiled Stan program?).

Perhaps it would be worth adding to the `stan_funs` argument description in `brm` and `make_stancode` to mention this explicitly? e.g. 

> An optional character string containing self-defined Stan functions, which will be included in the functions block of the generated Stan code.
> Note that the self-defined functions must additionally be defined as R functions in the global workspace for the `fitted` [etc] methods to work on the returned `brmsfit` object.

**Comment by paul-buerkner** [comment]
I will improve the doc of `stan_funs` accordingly.

Generally, you can expose Stan functions in R using `expose_functions` on you brmsfit object, but this does won't help in `fitted` etc. in most cases, since the Stan functions are usually not vectorized

**Comment by paul-buerkner** [comment]
Fixed. Thanks for opening this issue!
