### ISSUE TITLE
Change of variables vs transformations; interpreting log parameters

### ISSUE THREAD

**Issue by tomwallis** [paul-buerkner/brms#243]
Apologies in advance if this is more of a **Stan** than **brms** question.

I would like to fit data using a custom stan function, whose parameters are constrained to be positive. Because I want to include group-level effects on these parameters, I need the *sum* of the linear system (i.e. the formula specified for each nonlinear parameter) to be positive. Therefore it makes sense to me to define the **brms** formulae on the *log* parameter scale rather than the linear scale, then exponentiate the result for use in my custom function.

Here's a toy example. It has a few problems but should be enough to illustrate:

```r
library(brms)
set.seed(2231)
dat <- expand.grid(x = seq(1, 100, length.out = 30),
                   group = c("A", "B"))
dat$alpha <- 0.2
dat$alpha[dat$group == "B"] <- 0.3
dat$beta <- 1.2
dat$beta[dat$group == "B"] <- 1.7
dat$y <- dat$alpha * dat$x^(dat$beta) + rnorm(nrow(dat))

myfun <- function(x, logalpha, logbeta){
  alpha <- exp(logalpha)
  beta <- exp(logbeta)
  return(alpha * x^beta)
}

stan_funs <- "
real myfun(real x, real logalpha, real logbeta){
# exp the log values:
real alpha = exp(logalpha);
real beta = exp(logbeta);
real res;

return alpha * pow(x, beta);
}
"

model_formula <- brmsformula(y ~ myfun(x, logalpha, logbeta),
                             logalpha ~ 1 + (1 | group),
                             logbeta ~ 1 + (1 | group),
                             nl = TRUE)

priors <- c(set_prior("normal(-1.6, 0.2)", coef = "Intercept", nlpar = "logalpha"),
            set_prior("cauchy(0, 0.2)", class = "sd", nlpar = "logalpha"),
            set_prior("normal(0, 0.5)", coef = "Intercept", nlpar = "logbeta"),
            set_prior("cauchy(0, 0.2)", class = "sd", nlpar = "logbeta"))
```
Note my intercept priors are centered on $exp(-1.6) = 0.2$ for alpha and $exp(0) = 1$ for beta. I've also placed cauchy priors with modes of 0 on the (log) sd of the group-level variability.

```r
get_prior(formula = model_formula,
          data = dat)

make_stancode(formula = model_formula,
              data = dat,
              prior = priors,
              stan_funs = stan_funs)

```

This produces the following Stan code (here, just parameters, transformed parameters and model block are shown):

```r
parameters { 
  vector[K_logalpha] b_logalpha;  // population-level effects 
  vector[K_logbeta] b_logbeta;  // population-level effects 
  real<lower=0> sigma;  // residual SD 
  vector<lower=0>[M_1] sd_1;  // group-level standard deviations 
  vector[N_1] z_1[M_1];  // unscaled group-level effects 
  vector<lower=0>[M_2] sd_2;  // group-level standard deviations 
  vector[N_2] z_2[M_2];  // unscaled group-level effects 
} 
transformed parameters { 
  // group-level effects 
  vector[N_1] r_1_logalpha_1; 
  // group-level effects 
  vector[N_2] r_2_logbeta_1; 
  r_1_logalpha_1 = sd_1[1] * (z_1[1]); 
  r_2_logbeta_1 = sd_2[1] * (z_2[1]); 
} 
model { 
  vector[N] mu_logalpha; 
  vector[N] mu_logbeta; 
  vector[N] mu; 
  mu_logalpha = X_logalpha * b_logalpha; 
  mu_logbeta = X_logbeta * b_logbeta; 
  for (n in 1:N) { 
    mu_logalpha[n] = mu_logalpha[n] + (r_1_logalpha_1[J_1[n]]) * Z_1_logalpha_1[n]; 
    mu_logbeta[n] = mu_logbeta[n] + (r_2_logbeta_1[J_2[n]]) * Z_2_logbeta_1[n]; 
    // compute non-linear predictor 
    mu[n] = myfun(C_1[n] , mu_logalpha[n] , mu_logbeta[n]); 
  } 
  // prior specifications 
  b_logalpha ~ normal(-1.6, 0.2); 
  b_logbeta ~ normal(0, 0.5); 
  sigma ~ student_t(3, 0, 212); 
  sd_1 ~ cauchy(0, 0.2); 
  z_1[1] ~ normal(0, 1); 
  sd_2 ~ cauchy(0, 0.2); 
  z_2[1] ~ normal(0, 1); 
  // likelihood contribution 
  if (!prior_only) { 
    Y ~ normal(mu, sigma); 
  } 
} 
```

Continuing to fit the model in **brms**:

```r
fit <- brm(model_formula,
           data = dat,
           prior = priors,
           iter = 4000,
           chains = 3,
           cores = 3,
           save_model = "myfun.Stan",
           stan_funs = stan_funs)

```

This model fails to converge etc, but here is the summary anyway:

```r
summary(fit)

Group-Level Effects: 
~group (Number of levels: 2) 
                       Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
sd(logalpha_Intercept)     0.47      0.49     0.12     2.13         12 1.17
sd(logbeta_Intercept)      0.32      0.27     0.11     1.30          8 1.45

Population-Level Effects: 
                   Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
logalpha_Intercept    -1.58      0.18    -1.94    -1.25          3 1.36
logbeta_Intercept      0.23      0.19    -0.09     0.63          4 2.14

Family Specific Parameters: 
      Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
sigma     1.02       0.1     0.87     1.24         29 1.12
```

My questions:

1. Does this type of implementation require incrementing the log posterior manually (Jacobian correction)? 

I think the answer is "no". I think my case is the same as [the third model discussed here](http://discourse.mc-stan.org/t/basic-newbie-question-about-transforming-a-parameter-and-jacobians/1314). Priors are being placed on variables defined in the `parameters` block. Taking Ben Goodrich's answer there:

> Essentially the rule is that if you put priors only on the things declared in the parameters block, then no Jacobian corrections are required

2. If Jacobian corrections *are* required, how could this be implemented in **brms**?

3. I ultimately want to discuss the results of the model fitting on the linear (not log) parameter scale. Is it fine to simply `exp()` the estimates (samples) when computing credible intervals etc? Obviously means would be stretched, but quantiles should be invariant.

Thanks for your help.

**Comment by paul-buerkner** [comment]
Hi Tom,

(1) No Jacobian adjustments required for parameters defined in the parameters block.

(3) Yes, this is exactly, how it should be done :-)

Best,
Paul

**Comment by tomwallis** [comment]
Super, thanks Paul.
