### ISSUE TITLE
Bayesian R-squared method

### ISSUE THREAD

**Issue by paul-buerkner** [paul-buerkner/brms#244]
The implementation of `bayes_R2` by @jgabry in rstanarm reminded me of several questions I got regarding R-squared estimates and I am opening this issue in order not to forget about it again...

**Comment by jgabry** [comment]
Here's very rough draft of a short little paper explaining the `bayes_R2` function I put in that rstanarm pull request: 

https://github.com/jgabry/bayes_R2/blob/master/bayes_R2.pdf

**Comment by paul-buerkner** [comment]
Amazing thank you!

**Comment by paul-buerkner** [comment]
`bayes_R2` is now fully functional. @jgabry would you mind telling me when the new version of **rstantools** is on CRAN so that I can switch to using its generic?

**Comment by jgabry** [comment]
Yeah No problem

**Comment by ASKurz** [comment]
Using the `bayes_R2()` method, can one compute an R2 difference score? 

Say I have fits from two competing models of the same data, `fit1` and `fit2`. Both objects contain the same number of iterations. I then use `bayes_R2()` with `summary = F` in order to get two objects `fit1_R2` and `fit2_R2`. Would it be legit to compute a difference score by subtracting `fit2_R2` from `fit1_R2`?

**Comment by paul-buerkner** [comment]
Yes that would indeed be reasonable.

Am 24.09.2017 18:38 schrieb "ASKurz" <notifications@github.com>:

**Comment by jmgirard** [comment]
Gelman et al. (2019) state the following:

> A new issue then arises, though, when fitting a set of models to a single dataset. Now that the denominator of R² is no longer fixed, we can no longer interpret an increase in R² as an improved fit to a fixed target.

Does this mean that the approach of @ASKurz above would be an approximation at best, or does extracting the $R^2$ per posterior sample get around this?



Gelman, A., Goodrich, B., Gabry, J., & Vehtari, A. (2019). R-squared for Bayesian regression models. The American Statistician, 73(3), 307–309. https://doi.org/10/gf2hnb
