### ISSUE TITLE
launch_shiny does not provide pp_check

### ISSUE THREAD

**Issue by silberzwiebel** [paul-buerkner/brms#248]
Running `pp_check(fit)` gives a nice plot without the need to provide any further information. Launching shiny via `launch_shiny(fit)` and then navigating to Diagnose > PPcheck, however, wants me to select `y` and `yrep` manually. 

Could you make this as automagically as in manually running `pp_check(fit)`?

Thanks!

**Comment by paul-buerkner** [comment]
@jgabry Can I make this possible form the brms side or does it require changes in shinystan?

**Comment by jgabry** [comment]
I think I need to make some tweaks to shinystan but definitely possible.
Can you open an issue at the shinystan repo?

(Btw, I just submitted to CRAN a version with an S3 generic
launch_shinystan so you should be able to define a method for brmsfits.)

**Comment by paul-buerkner** [comment]
I am closing this issue as the solution mainly requires tweaks to shinystan (for which a separate issue exists in the shinystan repo) and only minimal changes to brms once that's done
