### ISSUE TITLE
marginal_effects() does not preserve "sum contrasts" factor coding

### ISSUE THREAD

**Issue by mabarbour** [paul-buerkner/brms#250]
Hi Paul,
I've noticed a potential issue in the marginal_effects() function. If a factor is modeled with "sum contrasts", then it is currently not possible to plot effects at the imaginary reference level of zero. I've included a small, reproducible example to illustrate the problem:

`library(brms)

## generate data
df <- data.frame(y = rnorm(100),
                 x = rnorm(100),
                 treatment.contrasts = factor(rep(c("A","B","C","D"), each = 25)))
df$sum.contrasts <- C(df$treatment.contrasts, sum)

## view contrasts
contrasts(df$treatment.contrasts)
contrasts(df$sum.contrasts)

## run models
fit.treatment <- brm(y ~ x + treatment.contrasts, data = df)
fit.sum <- brm(y ~ x + sum.contrasts, data = df)

## get data for plotting
marginal_effects.treatment <- marginal_effects(fit.treatment, effects = "x")
marginal_effects.sum <- marginal_effects(fit.sum, effects = "x")

## note that the reference level for both "treatment.contrasts" and "sum.contrasts" are the same. However, the reference level for sum.contrasts should be at an imaginary factor = 0. 
print(marginal_effects.treatment$x)
print(marginal_effects.sum$x)`

I guess one work around is to model "sum.contrasts" as a group-level effect, but for my purposes, I'm interested in modeling it as a population-level effect.

**Comment by paul-buerkner** [comment]
This is already possible. Just use NA for the factor variable when
specifying the conditions argument. See also the details section of
?marginal_effects

Am 10.08.2017 15:42 schrieb "Matt Barbour" <notifications@github.com>:

**Comment by mabarbour** [comment]
Wow, I thought I had scoured the ?marginal_effects section but I missed this. Thanks for a great package!
