### ISSUE TITLE
Multivariate Non Linear Models 

### ISSUE THREAD

**Issue by tushar-mbww** [paul-buerkner/brms#253]
Hi @paul-buerkner ,

I'm able to run univariate non linear models . However , when I replace a single variable with multiple dependent (syntax taken from linear models , since I couldn't find any reference for this in vignette("brms_nonlinear") ) - I get an error:
Error: is.btl(bt) is not TRUE

Could you please help me with this?

fit1 <- brm(
            bf(
               cbind(Awareness_LN , PI_LN) ~ 
                 alpha + 
                 (exp(betadirectbuy * (direct_buy/1)^powerdirectbuy) - 1) / (1 -adsdirectbuy) + 
                 (exp(betafb * (fb/1)^powerfb) - 1) / (1 -adsfb) +
                 (exp(betagdn * (gdn/1)^powergdn) - 1) / (1 -adsgdn) + 
                 (exp(betalkdin * (lkdin/1)^powerlkdin) - 1) / (1 -adslkdin) + 
                 (exp(betamob * (mob/1)^powermob) - 1) / (1 -adsmob) +
                 (exp(betabing * (bing/1)^powerbing) - 1) / (1 -adsbing) +
                 (exp(betabrok * (brok/1)^powerbrok) - 1) / (1 -adsbrok) +
                 (exp(betagoogle * (google/1)^powergoogle) - 1) / (1 -adsgoogle) +
                 (exp(betasearch * (search/1)^powersearch) - 1) / (1 -adssearch) +
                 (exp(betadisp * (disp/1)^powerdisp) - 1) / (1 -adsdisp) +
                 (exp(betaolv * (olv/1)^powerolv) - 1) / (1 -adsolv) +
                 (exp(betatw * (tw/1)^powertw) - 1) / (1 -adstw), 
               alpha + 
                 betadirectbuy + powerdirectbuy + adsdirectbuy + 
                 betafb + powerfb + adsfb + 
                 betagdn + powergdn + adsgdn + 
                 betalkdin + powerlkdin + adslkdin +
                 betamob + powermob + adsmob +
                 betabing + powerbing + adsbing +
                 betabrok + powerbrok + adsbrok +
                 betagoogle + powergoogle + adsgoogle +
                 betasearch + powersearch + adssearch +
                 betadisp + powerdisp + adsdisp +
                 betaolv + powerolv + adsolv +
                 betatw + powertw + adstw ~ 1 , 
               nl = TRUE
               ),
            data = Modelfile_final, 
            prior = list_of_priors,
            control = list(adapt_delta = 0.95),
            chains = 5,
            warmup = 1000,
            iter = 3000
            )

**Comment by paul-buerkner** [comment]
No need to cross post on github and brms users. Unfortunately multivariate
non-linear models are not yet implemented. I am sorry that the error
message is uninformative. I will fix that.

Am 15.08.2017 23:49 schrieb "tushar-mbww" <notifications@github.com>:

**Comment by paul-buerkner** [comment]
I just added an informative error message. Thanks for pointing me to this issue. Multivariate non-linear models will be implemented in brms 2.0.0, which will be released before end of this year, hopefully.

**Comment by tushar-mbww** [comment]
Thank you @paul-buerkner . That would be very helpful.
Let me know if I can be of assistance.
