### ISSUE TITLE
marginal_effects: allow to set transparency of points

### ISSUE THREAD

**Issue by silberzwiebel** [paul-buerkner/brms#255]
Having several points close to each other in the `marginal_effects` plot makes it hard to see where the actual bulk of the data are. See this example (which actually deals with the number of bikes riding in Münster ;), see https://github.com/codeformuenster/predictCyclists)
![marginal_no_alpha](https://user-images.githubusercontent.com/4533862/29581606-25e28848-877a-11e7-95d2-eae82bdb011b.png)

If I could easily set the transparency of the points (say `alpha = 0.1`), in marginal_effects then more points would lead to a more dense impression.

**Comment by paul-buerkner** [comment]
I will add an options for this :-)

**Comment by paul-buerkner** [comment]
Done. The `plot` method for `marginal_effects` now has a `points_alpha` argument allowing to set the transparency of the data points.

**Comment by paul-buerkner** [comment]
Just a quick note that I decided to remove `points_alpha` again, because it was too specific. Instead, I implemented a more general approach to adjust arguments to several geoms used in `marginal_effects`.

To adjust the transparency of the points, you can use

```R
plot(marginal_effects(fit), points = TRUE, point_args = list(alpha = 0.1))
```

**Comment by silberzwiebel** [comment]
Many thanks, works fine!

There is now a doubling in the parameters for the jitter_width. I
suggest to remove the jitter_width parameter in favor for point_args =
c(width = 0.2).

**Comment by paul-buerkner** [comment]
Thanks for pointing this out. I will add a warning when using `jitter_width` and point to user `point_args`.
