### ISSUE TITLE
Avoid setting `theme_default` on attach?

### ISSUE THREAD

**Issue by tomwallis** [paul-buerkner/brms#256]
Setting `bayesplot::theme_default()` on attaching `brms` (new in version 1.9.0) resets the default for all plots, not just for plots output by `brms`. Annoyingly, it also removes default values like `panel.grid` attributes - so for example, if I apply `theme_minimal()` to my plots I lose all gridlines and need to manually re-activate them using `theme(panel.grid = element_line())`. 

Is there a way to avoid this behaviour when attaching `brms`?

**Comment by paul-buerkner** [comment]
I agree this is annoying. I hadn't thought of it from this perspective. There is no way for the user to stop this from happening when attaching brms. The only way is to remove it from the `.onAttach` function completely, which is possibly not a bad idea. I will think about this a bit more.

**Comment by tomwallis** [comment]
Nice, thanks Paul.
