### ISSUE TITLE
Single-level models supported?

### ISSUE THREAD

**Issue by tmalsburg** [paul-buerkner/brms#258]
The documentation suggests that only multi-level models are supported, but when I tried a single-level models it seems to work just fine.  Hence my question: are single-level models supported?  If yes, this should be reflected in the documentation and the description on GitHub. 

Thanks for this software by the way.  I have just started to use it and I'm amazed by how well it's working.  Huge time-saver compared to hand-coding Stan models and compared to fiddling with random effects structures in lme4.

**Comment by paul-buerkner** [comment]
They are of course supported :-)

You are right though, that this should be explicitely stated in the doc, since some other multilevel packages don't support single level models.

**Comment by tmalsburg** [comment]
Awesome, thanks for the clarification.
