### ISSUE TITLE
Allow using to specify confidence levels other than 95% for summaries.

### ISSUE THREAD

**Issue by tmalsburg** [paul-buerkner/brms#259]
I assume 95% is what most people want but sometimes it would be convenient if it was possible to change that default to something else.

Feature request:

1. Allow users to set the default globally.(?)
2. Allow users to set the confidence level via an argument to `summary.brmsfit` (and related functions that return CIs).  Perhaps allow users to specify a probs parameter which accepts arbitrarily many values, e.g. `probs = c(0.05, 0.5, 0.95)` for 90% CI plus median. 

Thanks for this package, btw, it's a pleasure to work with it.

**Comment by paul-buerkner** [comment]
This is a good idea. In most methods such as predict, there is already a `probs` argument to set both boundaries of the credible intervals. I am adding a `prob` argument to `summary.brmsfit` right now, to set the width of the CIs with a single value. In what other methods do you think such an option is missing?

**Comment by tmalsburg** [comment]
I was thinking `fixef.brmsfit` but just saw that it already has `probs`.

**Comment by tmalsburg** [comment]
Would it make sense to call this parameter something else than `prob`?  Perhaps `conf.level`?  I'm afraid that it could lead to confusion when there is `prob` on some functions and `probs` on others with different semantics.

**Comment by paul-buerkner** [comment]
I know the naming is a bit unfortunate. The reason I want to use `prob` is that it is consistent with some **bayesplot** and **rstantools** methods, and I prefer not to refer to confidence intervals in the argument names.

**Comment by paul-buerkner** [comment]
In the dev version of **brms** on github `summary.brmsfit` now has a `prob` argument. Also, I have added the method `posterior_interval` to directly compute CIs of parameters.

**Comment by tmalsburg** [comment]
Cool, thanks! :+1:
