### ISSUE TITLE
Add Phylogenetic Correlation Structures 

### ISSUE THREAD

**Issue by jmaspons** [paul-buerkner/brms#26]
I would like to do comparative analysis with brms but it needs phylogenetic correlation structures.

Some examples at ?ape::corClasses

**Comment by paul-buerkner** [comment]
Thanks for the suggestions! I will take a look at it.

**Comment by paul-buerkner** [comment]
Which of the correlation structures described in ?ape::corClasses are relevant to you? Because it will certainly take some time implementing them all. ;-)

**Comment by jmaspons** [comment]
corPagel and corBrownian (corPagel with lambda=1) are more common (for me). With some guidance I can help with code.

MCMCglmm implements models for phylogenetic comparative analysis. Maybe it can be useful to take a look how is implemented in a Bayesian framework. Also https://stat.ethz.ch/pipermail/r-sig-phylo/attachments/20140724/efd95222/attachment.pl

**Comment by paul-buerkner** [comment]
Thanks for the link. What you already can do in brms is defining correlations between levels of the same grouping factor using the `cov.ranef` argument. This is very similar to the `ginverse` argument of `MCMCglmm`, which generalizes the `pedigree` argument I believe. Maybe this is helpful to you. 

Anyway, I will take a closer look at those correlation structures and see how the can be incorporated into brms.

**Comment by paul-buerkner** [comment]
Hmm, the link for the MCMCglmm analysis above doesn't work for me. Can you provide a new link?

**Comment by paul-buerkner** [comment]
I just learned a bit about comparative analysis with phylogenetic correlation structures from http://www.mpcm-evolution.org/practice/online-practical-material-chapter-11

With expection of the missing data augmentation decribed in part (5), all models described their can already be fitted with brms. If you want to fit models having similar structure, I can explain how to do it.

**Comment by jmaspons** [comment]
Thanks. I tried to compare different methods using the example from MCMCglmm. Could you confirm that the models are equivalent?

`
library(brms)
library(MCMCglmm)
library(caper)

## Example
data(bird.families)

# simulate phylogenetic and residual effects with unit variance
phylo.effect<-rbv(bird.families, 1, nodes="TIPS")
phenotype<-phylo.effect+rnorm(dim(phylo.effect)[1], 0, 1)

test.data<- data.frame(phenotype=phenotype, taxon=row.names(phenotype))

# inverse matrix of shared phyloegnetic history
Ainv<-inverseA(bird.families)$Ainv


## MCMCglmm
prior<-list(R=list(V=1, nu=0.002), G=list(G1=list(V=1, nu=0.002)))
mMCMC<-MCMCglmm(phenotype~1, random=~taxon, ginverse=list(taxon=Ainv),
                 data=test.data, prior=prior, verbose=FALSE)

summary(mMCMC)

## BRMS
mNUTS<- brm(phenotype ~ 1 + (1 | taxon), data=test.data, cov.ranef=list(species=Ainv))

summary(mNUTS)

## PGLS
compData<- comparative.data(bird.families, test.data, names.col=taxon)
mPGLS<- pgls(phenotype ~ 1, data=compData, lambda="ML")

summary(mPGLS)
`

**Comment by paul-buerkner** [comment]
You need to use the covariance matrix instead of its inverse `Ainv` and specifiy `nodes = "TIPS"` to that `A` has appropriate dimension. Also, shouldn't it be `taxon` instead of `species` in cov.ranef? I would try the following:

```R
Ainv<-inverseA(bird.families, nodes = "TIPS")$Ainv
A <- solve(Ainv)
rownames(A) <- rownames(Ainv)

mNUTS <- brm(phenotype ~ 1 + (1 | taxon), data=test.data, cov.ranef=list(taxon=A),
            prior = c(set_prior("normal(0,5)", coef = "Intercept"),
                      set_prior("student_t(10,0,5)", class = "sd"),
                      set_prior("student_t(10,0,5)", class = "sigma")),
            control = list(adapt_delta = 0.99))
summary(mNUTS)
plot(mNUTS)
# estimate lambda
hypothesis(mNUTS, "sd_taxon_Intercept^2 / (sd_taxon_Intercept^2 + sigma_phenotype^2) = 0",
           class = NULL)
```

The priors are not really required here, but they make sampling a bit easier for this particular model. I increased `adapt_delta` to `0.99` because there were some divergent transitions. To get enough effective sample size you may want to increase `iter` as well.

I wrote a little R-Script taking examples from www.mpcm-evolution.org/author/mpcmevolution, which can be found here:  [mpcm_chapter11_brms.zip](https://github.com/paul-buerkner/brms/files/112034/mpcm_chapter11_brms.zip). In fact, I think about making a little vignette for those types of models, to explain how comparative analysis can be done in brms.

**Comment by jmaspons** [comment]
Great! You are right about my mistakes.

A vignette explaining how to do comparative analysis could help to spread the usage of brms in evolutive ecology. I will spread the word among my colleagues.

**Comment by paul-buerkner** [comment]
Thanks. :-)

One more question: Are the correlation structures you mentioned when opening this issue included in what brms can already fit? Asked differently, does it make sense (from your perspective) to also implement them?
