### ISSUE TITLE
brms should not touch ggplot theme on load

### ISSUE THREAD

**Issue by tmalsburg** [paul-buerkner/brms#260]
Perhaps a matter of taste but I think brms should leave the default plotting theme untouched.  Basically what's happening is that I load brms somewhere in my Knitr document and then all plots after that position look differently than the plots before.  Of course, I can reset the default theme after loading brms that's not an ideal solution, because that theme is actually useful for the diagnostic plots produced by brms.

I suggest that brms plotting functions use `bayesplot::theme_default()` as the default value for the theme argument in its plotting functions. This way we get an appropriate theme for diagnostic plots and brms doesn't mess up my own plots.  Alternatively, it may make sense to have a brms-specific theme setting such that people can set the theme used by brms once if they prefer something else without having to specify the theme every time they call a brms plotting function.

**Comment by paul-buerkner** [comment]
I agree with you. @tomwallis already complained about it in #256 and in the dev version of brms on github, the default ggplot theme is no longer changed on attach. I don't want to "fix" the theme for certain plots via a `theme` argument to allow the global theme options to change appearance of the plots.

**Comment by tmalsburg** [comment]
Oh, sorry for the noise. I had searched the issues for "theme" but apparently the default is to search only in open issues.  Thanks for the fix.
