### ISSUE TITLE
Feature request: Distinguish between -0.00 and 0.00 in summary output

### ISSUE THREAD

**Issue by tmalsburg** [paul-buerkner/brms#263]
where -0.00 is displayed if the value being rounded is < 0 and 0.00 other wise.  My parameter estimates are often small and I'm seeing a lot of 0.00 which is not terribly informative.

**Comment by paul-buerkner** [comment]
Try print(summary(fit), digits = 4) to see more digits.

Am 06.09.2017 12:47 nachm. schrieb "Titus von der Malsburg" <
notifications@github.com>:

**Comment by tmalsburg** [comment]
Yes, I know, but sometimes I just want to know whether 0 is included in the CrI and then it would be convenient to have -0.00 notation.  Not important of course, but I think a lot of people might find this convenient and the -0 notation is to my knowledge accepted.  See [signed zero](https://en.wikipedia.org/wiki/Signed_zero).

**Comment by tmalsburg** [comment]
Yes, I know, but sometimes I just want to know whether 0 is included in the CrI and then it would be convenient to have -0.00 notation.  Not important of course, but I think a lot of people might find this convenient and the -0 notation is to my knowledge accepted.  See [signed zero](https://en.wikipedia.org/wiki/Signed_zero).

**Comment by paul-buerkner** [comment]
Hmm makes sense. Are you aware any convenient way to code this or of any
other model fitting package implementing this?

2017-09-06 15:12 GMT+02:00 Titus von der Malsburg <notifications@github.com>
:

**Comment by tmalsburg** [comment]
This [posting on stackoverflow](https://stackoverflow.com/questions/6925358/sprintf-adds-minus-sign-to-zero-after-rounding) might be useful.  Apparently, R already has signed zeros internally and you just have to make sure you print them accordingly (with sprintf).  Hope that helps.

**Comment by paul-buerkner** [comment]
It should be implemented in the dev version on github now. :-)

**Comment by tmalsburg** [comment]
Super cool, thank you so much!

**Comment by jgabry** [comment]
This seems like nice feature but I actually worry that it unintentionally
encourages poor practices when it comes to how variables are scaled before
fitting a model. If it really matters whether something so close to zero is
almost zero but negative vs almost zero but positive then it's clear that
the variables haven't been scaled appropriately.

**Comment by tmalsburg** [comment]
@jgabry, are you saying any model producing estimates < 0.005 is incorrectly parameterized? If yes, why?  Numerical precision should not be a big issue in this range if I'm not mistaken.  I can easily scale my predictors but the betas would then rarely have natural interpretations.  It would be great if you could point me to relevant literature.

**Comment by jgabry** [comment]
I didn't mean to say that the model would be wrong, but there are several
reasons we recommend that the data typically be scaled so that parameters
are roughly on unit scale.

- It makes the parameter space more amenable to sampling (this may not be
an issue for brms depending on what rescaling it does internally), but it's
definitely good practice (and a good habit to develop) for Stan and MCMC in
general. In the case of HMC/NUTS it makes it easier to estimate the mass
matrix during warmup. But again Paul may do some rescaling or
reparameterizing internally to help with this for brms. I'm not sure.

- It can sometimes be appropriate to report estimates like 0.00027 when you
ultimately write up your results (if for example the unit of measurement
typically used in your field means estimates are that small) but you can
always rescale initially and then after fitting and model checking and
whatnot then go back to the original scale. Everything from model fitting
to model comparison, visualization, etc., is typically easier to do and
understand when all parameters have similar scales. There are of course
exceptions! So for your particular case what I'm saying may not be as
useful. It's definitely intended as more of a general recommendation.

**Comment by jgabry** [comment]
There are probably other reasons I'm forgetting too. There's too much to
remember ;)

**Comment by tmalsburg** [comment]
That bit about scaling the data is new to me.  Interesting.  It's a bit unfortunate that we have to adopt scales that make the sampler happy instead of scales that make sense given the research question, but okay.
Although, I do wonder how this rescaling of the data should be done for some specific types of variables.  For instance, what to do if the DV is categorical?  No need to answer this questions, but if there is material available where the issue of rescaling the DV is discussed (I think I didn't see this in Stan manual), it would be great if you could point me to it.

Regarding negative zero, I think I see why it might be a bad thing when the posterior mean and the end points of the credible intervals are all close zero.  But when I made this feature request I was thinking about cases where the posterior mean and the upper end of the credible interval are reasonably large but the lower end of the CrI close to zero.  If I understand you correctly, there is no need to rescale the predictors or the data in that situation, however it may still be useful to know whether the end point of the CrI is above or below zero.  (Unfortunately, binary decisions, a.k.a. "significance", are a thing in many research areas.)

**Comment by jgabry** [comment]
@tmalsburg These are good points/questions. I think our recommendations about rescaling are scattered around case studies, blog posts, etc. It's mentioned in a few places in the Stan manual, but of course the manual is 600 pages long so it's hard to read everything! (Eventually we'll get a version of the manual that's in html and it will be easier to search than the current pdf.) 

Here's a paragraph from section 27.4 of the Stan manual (version 2.16):

> **Unit Scales without Correlation**
>
> Ideally, all parameters should be programmed so that they have unit scale and so that posterior correlation is reduced; together, these properties mean that there is no rotation or scaling required for optimal performance of Stan’s algorithms. For Hamiltonian Monte Carlo, this implies a unit mass matrix, which requires no adaptation as it is where the algorithm initializes.

One way to get the parameters close to unit scale, as recommended in that paragraph, is to rescale the data. Multiplying/dividing continuous variables by constants is the most natural example. 

I don't think you'd want to try to do anything to a categorical outcome variable, so if that's what your model is for then maybe none of this applies in your case. Although if there are predictors in the model amenable to rescaling then you can certainly do that even if the outcome is categorical.

**Comment by tmalsburg** [comment]
Thanks a lot, @jgabry.  And, Paul, sorry for this off-topic discussion in your issue tracker.

**Comment by paul-buerkner** [comment]
All good. It was interesting for me as well :-)
