### ISSUE TITLE
GJRM

### ISSUE THREAD

**Issue by stacyJohannes** [paul-buerkner/brms#264]
I am would like to join my three model by using a SemiParTRIV, however I am failing. Below is my model and the error. Can someone please help me.
My Region are 14
> f.4<- list(Water~ as.factor(Residence)+as.factor(Sex)+as.factor(Wealth)+as.factor(Radio)+as.factor(TV)+as.factor(Internet)+as.factor(Edu)+
+ as.factor(Marital)+s(Members)+s(Age)+s(Region, bs="mrf",xt=xt, k=7),
+ Sanitation~ as.factor(Residence)+as.factor(Sex)+as.factor(Wealth)+as.factor(Radio)+as.factor(TV)+as.factor(Internet)+as.factor(Edu)+
+ as.factor(Marital)+s(Members)+s(Age)+s(Region, bs="mrf",xt=xt, k=7),
+ Hygiene~ as.factor(Residence)+as.factor(Sex)+as.factor(Wealth)+as.factor(Radio)+as.factor(TV)+as.factor(Internet)+as.factor(Edu)+
+ as.factor(Marital)+s(Members)+s(Age)+s(Region, bs="mrf",xt=xt, k=7))
> wash3<- SemiParTRIV(f.4, data =anna,Chol=TRUE)

Warning messages:
1: In smooth.construct.mrf.smooth.spec(object, dk$data, dk$knots) :
  argument of mrf should be a factor variable
2: In smooth.construct.mrf.smooth.spec(object, dk$data, dk$knots) :
  argument of mrf should be a factor variable
3: In smooth.construct.mrf.smooth.spec(object, dk$data, dk$knots) :
  argument of mrf should be a factor variable

**Comment by paul-buerkner** [comment]
I am confused. Is this questions related to **brms**?

**Comment by stacyJohannes** [comment]
Nope. It's GJRM.  I just thought you might have an idea since the error is
mrf also.

**Comment by paul-buerkner** [comment]
But then you shouldn't open a **brms** issue ;-)

I cannot tell exactely what is happening, but looking at the warnings it seeps as if the mrf argument should be a factor variable. 

Please ask the maintainer of GJRM for more help.
