### ISSUE TITLE
add_ic stores model name in hidden property

### ISSUE THREAD

**Issue by rubenarslan** [paul-buerkner/brms#265]
I'd prefer if `add_ic` did not store the model name in `model$loo$model_name`. 

When I run a lot of models on the cluster to compare them, I often don't bother with the model variable name (or give it something fairly generic that isn't well suited to my later goal of comparison), because I save it to a file with an identifying name anyway.

This can then lead to LOO output where ten different `m1` are compared. 

Is it possible to do away with this?

**Comment by paul-buerkner** [comment]
It seems as if it is not the storing that bothers you, but the output when comparing models, right?

I could possibly add an argument to LOO and related functions that ignore the `model_name` and instead just print the output with standard names defined by the ordering (i.e. `model1` etc.).

**Comment by rubenarslan** [comment]
Well, on some abstract level the storing bothers me because it seems redundant and puzzled me for a while, because I didn't know where the model names where coming from.

But yeah, in the comparison I'd prefer something other.
Ideally, that the model variable names that are passed in are used, not generic ordered names. You could also use allow named arguments I suppose?
i.e. `LOO(baseline = m1, main_effs = m2, interaction = m3)`.

While we're on the subject, I thought it would make sense to give an option to order the iclist by decreasing LOO?

**Comment by paul-buerkner** [comment]
Naming via argument names is not possible in general since `LOO` is generic and its first argument is named `x`. Given this, how would you prefered option look like?

**Comment by rubenarslan** [comment]
I suppose my preferred solution would be if you overwrote the stored model name with the ones you got from the LOO call after [this line](https://github.com/paul-buerkner/brms/blob/b6b813ea64bc8a308e810f187f6c9f0ec1334623/R/loo-helpers.R#L32)
i.e. `out[[i]]$model_name = model_names[i]`.

Same for line 48.

Sorry, would try it out myself, but I'm home and my local is broken.

**Comment by paul-buerkner** [comment]
Ahh so use the current model names rather than the model names when computing LOO. That makes sense. I can change that.
