### ISSUE TITLE
How to specify a cumulative logit model with non proportional odds for ordinal data ?

### ISSUE THREAD

**Issue by atrolle** [paul-buerkner/brms#269]
Hi,

For ordinal data, I could see that cs() cannot be used in the formula when using the "cumulative()" family ; thus, category-specific estimates cannot be obtained.
So, I guess that, when using this family, one runs a cumulative logit model with proportional odds, by default.
If possible, how should I proceed to get a cumulative logit model with NON proportional odds ?

Thank you in advance,
Best,
Arnaud.

**Comment by paul-buerkner** [comment]
Good question. The reason, why cs() (i.e. non proportional oddes) cannot be used in cumulative models is that it can (and more often than not will) imply negative probabilities causing bayesian models to fail. So basically, there is no way of fitting the non-proportional odds model in brms (in frequentist packages, getting it to fit is pure luck by the way).

So if you want to use category specific effects, you should aim at using other ordinal families like sratio() or acat()

**Comment by atrolle** [comment]
Hi Paul,
Thank you very much for this information.

Best,
