### ISSUE TITLE
Syntax for "fixed" effect covariate in non-linear model

### ISSUE THREAD

**Issue by padpadpadpad** [paul-buerkner/brms#271]
Hello again

I am so impressed by the progress you can make into fitting brms models in a short space of time.

I am now wondering if you have a non-linear model to fit, say the example of the loss data frame, and within that you add a factor upon which you expect the parameters to differ on.

Say the data is from two different countries.

```r
loss$country <- sample(c('USA', 'UK', nrow(loss), replace = TRUE)
```
How would you then specify the model to give you separate parameter estimates for the effect of country on ult for example? ult of the USA and ult estimate of the UK?

I found one [gist](https://gist.github.com/ramhiser/ab8a5f3dec4b14ad6afdc6ff39e49b0b) doing something that looked similar but it did not quite do what I expected with categorical variables.

I tried something like:

```r
nlform3 <- bf(cum ~ ult * (1 - exp(-(dev/theta)^omega)),
              ult ~ 1 + country + (1 | AY),
              omega ~ 1 + (1 | AY),
              theta ~ 1 + (1 | AY),
              nl = TRUE)
```

The other way in actual Stan code would be to make a dummy variable, something like

```r
nlform3 <- bf(cum ~ (ult + (ult_country*country))  * (1 - exp(-(dev/theta)^omega)),
              ult ~ 1 + (1 | AY),
              omega ~ 1 + (1 | AY),
              theta ~ 1 + (1 | AY),
              nl = TRUE)
```

But I have not tried that as of yet as would be much clunkier if there was a specific syntax to specify extra relationships we expect from the model.

Cheers
Dan

**Comment by paul-buerkner** [comment]
The first seems good to me, but you are using dummy coding, so the intercept of ult will be ult of USA, say, and the country coefficient will be the difference of UK and USA. If you want separate coefficients for both countries go for `ult ~ 0 + country + (1 | AY)`, which implies a cell mean coding of country (this is basic R formula syntax so not special stuff of brms).

**Comment by padpadpadpad** [comment]
Thanks a lot. This package (in about 2 days) has got me closer to fitting a complex non-linear mixed model than nlme and nlmer got me in bout 2.5 years of a PhD.

**Comment by paul-buerkner** [comment]
I am glad to hear that! :-)

Am 06.10.2017 11:38 vorm. schrieb "Daniel Padfield" <
notifications@github.com>:
