### ISSUE TITLE
Cannot change link functions for wiener() family

### ISSUE THREAD

**Issue by singmann** [paul-buerkner/brms#276]
It appears as if it is not possible to change the link functions for the parameters of the Wiener family. This would be awesome, because it is in principle possible to use the identity link function for all wiener parameters and only constrains them via priors and rejection instead of the hard constrains via link functions. This makes interpretation of the posterior often a lot easier.

However, this does not appear to be possible in brms:
```
require(brms)
d <- rwiener(100, 1, 0.2, 0.5, 2)
make_stancode(bf(q | dec(resp) ~ 1, bs ~ 1, ndt ~ 1, bias ~ 1), 
              family = wiener(link_bs = "identity", 
                              link_ndt = "identity",
                              link_bias = "identity"), 
              data = d)
```
gives:
```
[...]
  for (n in 1:N) { 
    bs[n] = exp(bs[n]); 
    ndt[n] = exp(ndt[n]); 
    bias[n] = inv_logit(bias[n]); 
[...]
```

**Comment by paul-buerkner** [comment]
This is indeed a bug, which I have just fixed in the dev version of **brms**. Thanks for pointing me to it!
