### ISSUE TITLE
Implement mixture models

### ISSUE THREAD

**Issue by paul-buerkner** [paul-buerkner/brms#28]
Stan allows to fit mixture models in a flexible way as described in Section 10 of the Stan 2.9.0 Reference Manual. Regarding their implementation in brms, one has to think about (1) what kind of mixture models to allow and (2) how to specify them within the `brm` function. Regarding (2) it might be a good idea to implement a new addition argument `mixture` for the LHS of `formula`, in which the type of mixture could be specified.

**Comment by waynefoltaERI** [comment]
For extra magical points, have an option to use a Dirichlet Process to determine the number of components in the mixture. (I still can't get my head around how this works.)

**Comment by paul-buerkner** [comment]
I started thinking about mixture models a bit more and came up with an inital idea for a syntax (suggestions more than welcome):

(1) New function `mix(...)`, where `...` can be some (calls to) family functions. For instance

```R
family = mix(gaussian(), exponential())
```

(2) Extention of function `bf` (short for `brmsformula`) to support new auxiliary parameter `mu` as an alternative to specifying predictors in the `formula` argument. For instance

```R
bf(y ~ 1, mu ~ x + (1+x|g))
```
should be equivalent to
```R
bf(y ~ x + (1+x|g))
```

(3) Extending names of auxiliary parameters by a number suffix in mixture models to refer the position of the family within the call to `mix`. For instance

```R
bf(y ~ 1, mu1 ~ x, mu2 ~ z, sigma1 ~ x, shape2 ~ z)
family = mix(gaussian(), Gamma())
``` 

(4) New function `mix_cstr` (and corresponding argument `cstr` in `mix`) allowing to specify equality constraints of the auxiliary parameters. For instance

```R
family = mix(gaussian(), gaussian(), cstr = mix_cstr(sigma1 = sigma2))
```

**Comment by wfolta** [comment]
I like it. The only part that I worry about is the auto-numbering of the aux parameters. My fear is that it would make it easier to change something in the `mix` without changing the `mu*`'s

Could `family` become something like an aux variable in a `bf`, then for a mixture you have a vector of `bf`'s?

```
m1 <- bf (y ~ x, sigma=x, family=gaussuan ())
m2 <- bf (y ~ z, shape=z, family=Gamma ())

mod <- brm (c(m1, m2), ..., data=myData, ...)

```
It keeps things together for each mixture component. On the other hand, you might be able to end up modifying m1 and m2 in such a way that they they are working at cross-purposes, and you might have to repeat things in each.

It would also be less like previous ways of doing things. On the other hand, I've started using separate `bf` statements lately and it feels like there should maybe be a distinction between the model (formula, family, aux variables) and the sampling (iterations, options, method). Does that make sense?

For example, if I want to have a separate `bf` for a straight-up regression, then want to switch to a quantile regression, I have to change things in two places: 1) in my `bf`, and one in the `brm`. In my mind, I can have a model that I run sometimes quickly (200 iterations, or an meanfield), and sometimes overnight (2000 iterations, HMC).

So maybe it's possible to allow things to be entered in the `bf` or directly in the `brm`, basically keeping compatibility with what we have, but once you want to get fancy it's through `bf`'s?

**Comment by paul-buerkner** [comment]
Thanks @wfolta for your comments! Internally, `family` is already part of the `brmsformula` object for reasons of having everything in one place, just as you say. So we might really want to add a `family` argument to `bf`... I guess I will just do it tonight. It is a matter of 15 minutes or so. The `family` argument of `brm` will remain of course or this is going to annoy a whole lot of people ;-)

However, with respect to mixture models I am sceptical whether I want to use multiple calls to `bf`: 

(a) Possible redundance as you point out, but I guess that would not be too much of a problem (still way easier than writing it yourself in Stan).

(b) It is not clear, where to specify the response variable. Should this go in every `bf`? Should we possibly even *define* mixtures through having a common response variable? Were can we put addition arguments, if we ever want to have them for mixture models? And how do we handle the constraints then? I think we will need the option for constraints or otherwise the number of auxiliary parameters will explode leaving us with too complicated response distributions.

(c) How can we make this distinct to general multivariate models (also on my to-do list), which should be compatible with mixture distributions (mulivariate models of mixtures... sounds complicated). Defining mixture components via a shared response variable as discussed in (b) would be an option, but this is rather verbose and will likely lead to some problems with the internal workflow.

Given that I will add a `family` argument to `bf`, do you still think having multiple `bf`s is better than using a `mix` function (being passed to the single `bf` if desired)?

I am very grateful for having someone to discuss this, as it is a far from trivial question with many implications both for me and for the users.

**Comment by jgabry** [comment]
Interesting ideas! My two cents would be that although this will be a nice
addition to brms, you should be in no rush to officially add mixtures and
multivariate models until you are absolutely committed to how they will be
implemented long term. So maybe these things could be implemented but go in
a separate branch and stay there (even for many months) so that you can
have as many people as possible try it out and comment on the new syntax,
new output, whatever, before releasing it. People like @wolta who want to
start using it will be able to buy buy you won't commit yourself without
giving yourself a chance to come up with something better. I can't even
list the number of times I've released something and then come up with a
very different but better way not long after. So with big decisions I now
always try to force myself to go much slower. Even if that means postponing
releasing something I like just to give future me the chance to be smarter.
Anyway, just some thoughts.

P.S. Ben and I mentioned brms several times at StanCon yesterday,
especially to recommend a way for people new to the Stan language to find
readable Stan code for models they're currently fitting with some other R
package. Keep up the great work!

**Comment by jgabry** [comment]
"buy buy" should just be "but". Not sur how that happened!

**Comment by paul-buerkner** [comment]
I agree with you Jonah! I made a couple of design mistakes in the early releases of brms and as a result had to maintain bad code for several months. This way annoying. Fortunately, I got rid of it in version 1.0.0 and since then I am doing exactly as you say when it comes to new feature that require code refactoring: I slow down until I feel confident. That is why I posted all this syntax stuff here so I have my ideas documented and free for anyone to comment. After all, mixture and multivariate models will be be the most important features I am planning to implement this year.

P.S. Thanks for recommending brms to people at StanCon! I hope to be able to come to New York for the next StanCon :-)

**Comment by jgabry** [comment]
Cool. If you're able to make it to the next StanCon you should submit a
talk!

**Comment by paul-buerkner** [comment]
On the new branch `mixture-models` on github, the most basic features of mixture models are now implemented. For instance, you can fit a gaussian mixture model like this:

```R
dat <- data.frame(y = c(rnorm(50), rnorm(50, 4)), x = rnorm(100))
fit <- brm(bf(y ~ 1, mu1 + mu2 ~ x), 
           data = dat, 
           family = mixture(gaussian(), gaussian()),
           prior = c(prior(normal(0, 10), nlpar = mu1),
                     prior(normal(0, 10), nlpar = mu2)),
           chains = 1
)
summary(fit)
``` 

Most post-processing methods are not yet working with mixture models and I will add a list of stuff that needs to be done in the next couple of days.

**Comment by paul-buerkner** [comment]
Here is was needs to be done (or has already been done) to achieve full support for mixture models:

- [x] Compatibility of `family` related functions with mixture families
- [x] Formula parsing for mixture models
- [x] basic Stan code 
- [ ] Option to identify mixture components (see http://mc-stan.org/documentation/case-studies/identifying_mixture_models.html)
- [ ] Allow to restrict auxiliary parameters to the same value
- [ ] Priors for the mixture probabilities
- [ ] compatibility with `predict`
- [ ] compatibility with `fitted`
- [ ] compatibility with `log_lik`
- [ ] documentation
- [ ] unit testing

**Comment by paul-buerkner** [comment]
closed via #202

**Comment by paul-buerkner** [comment]
Mixture models will be included in the next release. I am sure there will be more features related to mixture models in the future, but those will not affect the now implemented syntax.

**Comment by paul-buerkner** [comment]
Predicting mixing proportions is now possible as well. To get this working, I had to make some minor changes to the syntax so that mixture models fitted with the dev version of brms in the last couple of days might not be working anymore. As soon as version 1.6.0 is released (which will happen within the next few days), there will be no adhoc changes to the mixture model syntax anymore.

**Comment by stephensrmmartin** [comment]
Paul: Is there currently any way of constraining non-auxilliary params to be equal? Say I want to fit a mixture model where one is y ~ x1 and the other y ~ x1 + x2. I want to constraint mu1_Intercept = mu2_Intercept, and the x1 coefficients to be equal. Is this at all possible in brms, and I'm just not seeing it?

**Comment by paul-buerkner** [comment]
This is currently not possible. We need a far more advanced syntax for it, I think. Please feel free to offer suggestions on how such a syntax could look like.

**Comment by stephensrmmartin** [comment]
Seems like the non-linear syntax would ideally be appropriated for this.

Something like:
mod <- bf(y ~ 1, family=mixture(gaussian,gaussian), mu1 = b1 + b2*x1, mu2 = b1 + b2*x1 + b3*x2, b1 + b2 + b3 ~ 1)

**Comment by mschubert** [comment]
As a new user, I found this issue when looking for how to fit constrained mixtures.


> (4) New function mix_cstr (and corresponding argument cstr in mix) allowing to specify equality constraints of the auxiliary parameters. For instance
>
> ```r
> family = mix(gaussian(), gaussian(), cstr = mix_cstr(sigma1 = sigma2))
> ```

Were the contraints (`mix_cstr`) ever implemented?

**Comment by paul-buerkner** [comment]
in the formula: `bf(..., sigma2 = "sigma1")`

**Comment by jalavery** [comment]
> Paul: Is there currently any way of constraining non-auxilliary params to be equal? Say I want to fit a mixture model where one is y ~ x1 and the other y ~ x1 + x2. I want to constraint mu1_Intercept = mu2_Intercept, and the x1 coefficients to be equal. Is this at all possible in brms, and I'm just not seeing it?

I saw the above post and your reply from 2017 and was wondering if this has been implemented since then? I have read through the documentation but was unable to find information about setting the non-auxillary parameters to be equal. I appreciate any information you can provide, and thanks for providing such a wonderful package!

**Comment by paul-buerkner** [comment]
This is possible but only with a bit of hacking so far. See https://github.com/paul-buerkner/brms/issues/888
