### ISSUE TITLE
A way to calculate MC standard error

### ISSUE THREAD

**Issue by superdayv** [paul-buerkner/brms#280]
I believe that Stan can do this, but I'm not sure if brms allows the user to calculate MC standard error? If not, this would be a nice feature to add going forward.

**Comment by paul-buerkner** [comment]
If `mod` is your brms model, you can see the summary output of rstan via `mod$fit`. I did not display the MC error in the summary output of a brms model in order to keep the summary easier to read, but I may add an option to show the MC error as well.

**Comment by superdayv** [comment]
Ah okay, wonderful! Thanks for getting back to me!

**Comment by paul-buerkner** [comment]
You can now use argument `mc_se` in `summary.brmsfit` to get what the MC error as well.
