### ISSUE TITLE
Comparison marginal_effects() and posterior_linpred()

### ISSUE THREAD

**Issue by strengejacke** [paul-buerkner/brms#282]
This issue was discussed via email first, so I give some background on it for other people who are interested in it:

I have a model fitted with **brms** and want to compute marginal effects (predicted values of the outcome). Terms in question are `ArrivalTime` and `SexParent`, while other terms are held constant (continuous variables at their mean, factors at their reference level).

I used both `posterior_linpred()` and `marginal_effects()`. which _should_ produce the same results. As seen, the plots are almost identical, however, the y-offset (see y-axis values) in the plots differ.

My question is, where is the difference between `posterior_linpred()` and `marginal_effects()` that results in this difference? Or am I making a mistake when computing the `newdata` for the function call to `posterior_linpred()`?

``` r
library(ggplot2)
library(brms)
library(glmmTMB)
library(rstantools)
library(dplyr)
library(purrr)

data(Owls)

# fit model

m1 <- brm(
  SiblingNegotiation ~ FoodTreatment + ArrivalTime + SexParent + (1 | Nest),
  data = Owls,
  family = zero_inflated_poisson(link = "log", link_zi = "logit")
)


# this is how I prepare my data frame - terms of interest
# (ArrivalTime + SexParent) keep all their unique values, cont. variable
# are set to mean, factors to their reference

newdat <- data.frame(expand.grid(
  FoodTreatment = levels(Owls$FoodTreatment)[1],
  ArrivalTime = unique(Owls$ArrivalTime),
  SexParent = unique(Owls$SexParent),
  Nest = levels(Owls$Nest)[1]
))


# predictions based on post. linpred

prdat <- posterior_linpred(
  m1,
  newdata = newdat,
  re.form = NA,
  transform = TRUE
)


# here I take the mean value from each sample column from
# the predictions, so I have same amount of "predicted values" as
# I have rows in my "newdat" data frame

pr <- prdat %>%
  as.data.frame() %>%
  purrr::map_dbl(mean) %>%
  as.data.frame() %>%
  dplyr::bind_cols(newdat)

# fix column name of predicted values

colnames(pr)[1] <- "predicted"


# plot posterior_linpred

ggplot(pr, aes(x = ArrivalTime, y = predicted, colour = SexParent)) + geom_line()
```

![](https://i.imgur.com/U1j9hJy.png)

``` r


# now predictions from brms::marginal_effects()

mf <- marginal_effects(m1, effects = "ArrivalTime:SexParent", re_formula = NA)


# same plot - almost identical, however, y-offset differs

ggplot(mf[[1]], aes(x = ArrivalTime, y = estimate__, colour = SexParent)) + geom_line()
```

![](https://i.imgur.com/Q6WyKjB.png)

**Comment by strengejacke** [comment]
Although the documentation of `posterior_linpred()` says that the argument name is `re.form` (http://mc-stan.org/rstanarm/reference/posterior_linpred.stanreg.html), it is actually `re_formula`.

So, using

``` r
prdat <- posterior_linpred(
  m1,
  newdata = newdat,
  re_formula = NA,
  transform = TRUE
)
```

gives the same results!

**Comment by paul-buerkner** [comment]
You looked at the doc of rstanarm. This doesn't tell you the argument names
for brmsfit objects. Please see ?posterior_linpred.brmsfit.

Am 27.10.2017 12:57 schrieb "Daniel" <notifications@github.com>:
