### ISSUE TITLE
Add "standard" arguments to S3-functions (like posterior_linpred())

### ISSUE THREAD

**Issue by strengejacke** [paul-buerkner/brms#283]
As a follow-up of [this issue](https://github.com/paul-buerkner/brms/issues/282), would you consider also adding the standard parameter like `re.form` to `posterior_linpred.brmsfit()`? This helps avoiding unexpected results and reading _different_ help-pages for the same function? 

Supporting both `re_formula` and `re.form` would probably satisfy "classical" brms-user and "rstantools"-user...

**Comment by paul-buerkner** [comment]
Thanks, I will consider this. I want to point out, though, that this is not a question of whether you use brms or rstantools, but rather whether you use brms or rstanarm. 

rstantools just provides the generic (without the `re.form` argument), which both brms and rstanarm rely on in their S3 methods to avoid function masking. In this sense, the different help files refer to different functions, but I agree that it is suboptimal having different names for the same argument. The reason, I initially avoided `re.form` is because I don't like dots in function or argument names (except for S3 methods where the have a special meaning).

**Comment by strengejacke** [comment]
I thought rstantools is the "base" package where all other packages derive their S3-methods - but in this case, it doesn't matter.

Actually, my issue become more urgent for `posterior_predict()`. While `posterior_linpred()` seems to accept both argument `re.form` and `re_formula` simultaneously, `posterior_predict()` throws an error.

> The reason, I initially avoided re.form is because I don't like dots in function or argument names 

I personally dislike underscore-separation in _arguments_, but use them in function names. This makes it faster recognizable whether you refer to an argument or a function - but that's personal matter of taste, I guess. That's why I strictly use dot-separators for arguments, and underscores for function names in my pkgs.

**Comment by paul-buerkner** [comment]
`posterior_linpred` does not *accept* `re.form` it just ignores it (as usual in functions with an unused `...` argument).  Is it much effort to add some lines to your code, either using `re.form` or `re_formula` depending on the passed object?

I agree that it is a matter of style, but in brms I choose the *tidyverse* style of using underscores.

**Comment by strengejacke** [comment]
Ok, by _accept_ I meant that this argument does not result in an error. But you're right, perhaps this issue is better addressed at `rstantools::posterior_predict()`, which should accept (and ignore) `re_formula`. And it's not much effort to add this exception to my code - perhaps this issue can be closed.

I'm not sure how other packages handle this when they inherit from generic S3-methods (like predict, print, plot...) - do they all use the _same_ argument names if someone was "first", and accept this as convention? Perhaps this is a design choice packages should not break...

> I agree that it is a matter of style, but in brms I choose the tidyverse style of using underscores.

Actually, tidyverse uses underscores for function names, but very rarely in arguments. Typical tidyverse-style for arguments is one (non-separated) word or a prefixed dot. :-)

**Comment by paul-buerkner** [comment]
Hmm, I cannot reproduce the error you get in `posterior_predict` when passing `re.form`. 

Anyway, this is nothing to be solved in `rstantools::posterior_predict`, which just has `posterior_predict(object, ...)` as its function signature. So rstantools doesn't tell us how the arguments should be named. 

When I named the argument `re_formula` in the `predict` and `fitted` methods (of which `posterior_predict` and `posterior_linpred` are aliases), there were no `posterior_predict` or `posterior_linpred`) generics / methods around. 

I am not sure how other packages are handling it, but to come back to the main point, I agree it is desirble to use the same argument names.

**Comment by strengejacke** [comment]
Sorry, I can't reproduce this error anymore - maybe there was something wrong with my last setup when I ran into this issue.

I'm using this function call in my package:

```
    prdat2 <- prdat <- rstantools::posterior_predict(
      model,
      newdata = fitfram,
      re.form = ref,
      re_formula = ref,
      ...
    )
```

and got an error when passing a `brmsfit`-object, however, the error did not occur when I used the same argument with `posterior_linpred()`. So I though that `rstantools::posterior_predict()` did not accept and ignore the `re_formula`-argument to pass it down to `brms::posterior_predict.brmsfit()`. However, now that I wanted to create a reproducible example, I don't get the error message anymore... Maybe something went wrong when I compiled my package.

So currently, it's not such a big matter when you use different argument-names, as you don't run into errors, as I first expected.

**Comment by strengejacke** [comment]
Ok, I get the error when I pass a `stanreg`-model, fitted with rstanarm, to `posterior_predict()`, but not when I use `posterior_linpred()`.

So, this works:

```
    prdat <- rstantools::posterior_linpred(
      <rstanarmmodel>,
      newdata = fitfram,
      transform = TRUE,
      re.form = ref,
      re_formula = ref,
      ...
    )
```

while this does not work:

```
    prdat2 <- prdat <- rstantools::posterior_predict(
      <rstanarmmodel>,
      newdata = fitfram,
      re.form = ref,
      re_formula = ref,
      ...
    )
```

Sorry for all these confusing posts and mails from me. ;-)

**Comment by strengejacke** [comment]
``` r
library(lme4)
library(rstanarm)
library(rstantools)

data(sleepstudy)
m <- stan_lmer(Reaction ~ Days + (1 + Days | Subject), sleepstudy)

rstantools::posterior_linpred(m, re.form = NULL, re_formula = NULL)
#>           
#> iterations        1        2        3        4        5        6        7
#>       [1,] 249.1308 269.0950 289.0592 309.0233 328.9875 348.9517 368.9158
#>       [2,] 256.9490 275.3359 293.7227 312.1096 330.4964 348.8832 367.2701
#>       ... 

rstantools::posterior_predict(m, re.form = NULL, re_formula = NULL)
#> Error in .pp_data_mer_z(object, newdata, re.form, ...): unbenutztes Argument (re_formula = NULL)
```

**Comment by strengejacke** [comment]
So, you may close this issue (unless you want to harmonize arguments), I would rather open an issue over at rstanarm's GitHub page and ask if `posterior_predict()` could ignore unused arguments, as in `posterior_linpred()`.

**Comment by paul-buerkner** [comment]
Ah ok it is an error in posterior_linpred.stanreg.

Actually I kind of like the behavior of methods throwing an error instead
of silently ignoring the argument since it avoids the problem you had
previously where re.form was silently ignored.

I will leave this issue open for the time being.

Am 31.10.2017 20:07 schrieb "Daniel" <notifications@github.com>:

**Comment by paul-buerkner** [comment]
In the new dev version, `posterior_linpred.brmsfit`, `posterior_predict.brmsfit`, and `predictive_error.brmsfit` now all support `re.form` as an alias of `re_formula`.
