### ISSUE TITLE
Documentation: Wiki or Vignette on "Extending" in-formula constructors such as ?cor_car()

### ISSUE THREAD

**Issue by mikejacktzen** [paul-buerkner/brms#284]
I'd like to request a Vignette or Wiki that walks through the process on how to 'extend' a formula component that is used in  brms() 

Say, a correlation term -> constructor -> stan code generation.

Using the ?cor_car constructor as an example

1. brm(data, y~x , autocor = cor_car(W) ) 
2. cor_car(W)  will output a portion of stan code that has W passed to Stan in the data block 
3. Full stan code is assembled
4. sampling done stan-side

The addition of `?cor_car` is great. I think these 'classic' CAR and ICAR approaches cover most of the 'common use cases'. They only use the spatial adjacency matrix, as in:

```
cor_car(W)
cor_icar(W)
```
There are some newer variants of these CAR approaches that make some small adjustments to the adjacency matrix W with some other matrix Q; say,

```
cor_car_variant(W,Q)
```

I tried to look into how to extend `cor_car(W)` to `cor_car_variant(W,Q)` as in Step 1 and 2 above, but I definitely do not understand the internals of brms well enough. 

In the other direction, I'd be happy to contribute the pure stan-side code (going backwards from the last step of 3) that implements the `cor_car_variant(W,Q)` that I had in mind.

I think working out the cor_car_variant() as an example would be a useful vignette to jumpstart users if they wish to 'extend' other aspects of brms()

**Comment by paul-buerkner** [comment]
Adding such a formula component to brms is quite complicated. You do not only have to add some Stan code and data passed to Stan, but also priors and compatibility with post-processig methods such as `predict` and `log_lik`. Furthermore, you have to make sure that as many other modeling options as possibly are compatible with the new feature. 

I think it is usually best, if you explain the extentions you want to make in detail and provide the necessary stan code, leaving implementations of the internals to me (at least until I come up with an internal structure, that is easier to extend for others).

**Comment by paul-buerkner** [comment]
Do you have any references to those adjustments or can explain them yourself (incl. Stan code)? I am happy to implement them. Maybe I have some time over the holidays.

**Comment by mikejacktzen** [comment]
Just saw this comment,

In a few days, i'll followup with the stan code. it was developed stan 1.0, want to see if it still runs on the new stan version before sharing.

However, here's the data block, which pinpoints the difference from the classic car priors.

On the r-side, users should pre-compute then pass to stan the quantities so that on the stan side, the data block accepts

```
data {
int<lower=0> N; # number of areas
int<lower=0> p; # number of covariates
int<lower=0> q; # number of eigenvalues in dim red
matrix[q,q] Q_s;  # q by q matrix for sparse precision random effect
matrix[N,q] M; # matrix of q<<n eigenvectors
vector[N] E; # expected cases
matrix[N,p] X; # covariate matrix

int<lower=0> Z[N]; # observed cases
}
```

You'll notice the only real difference from the classic car models are the quantitites

```
int<lower=0> q; # number of eigenvalues in dim red
matrix[q,q] Q_s;  # q by q matrix for sparse precision random effect
matrix[N,q] M; # matrix of q<<n eigenvectors
```

**Comment by mikejacktzen** [comment]
@paul-buerkner 

the r script using rstan 
https://github.com/mikejacktzen/car_moran/blob/master/scripts/03_call_stan.R

that passes the data
https://github.com/mikejacktzen/car_moran/blob/master/data/proc/stan_dat_moran_tract_la.RData

to the stan file
https://github.com/mikejacktzen/car_moran/blob/master/scripts/bym_moran_op.stan


Focusing on the stan file, you'll see that the most important line is the regression spec in line 113, involving the matrix multiplication `M*gamma` 

``` 
log_mu = log(E) + 
M*gamma +
beta0 + 
X*Beta
```

Really, this is the only **stan-side** difference on the formula specification.

M was the data matrix (precomputed in R) that is declared in line 6 of the stan data block

the gamma parameter could be specified stan-side thru alternative equivalent parametrizations.
The one I used (in lines 13-29 and 39-67) may not be exactly the same as the stan spec generated by `brms::car_cov()`

I'm pretty sure any equivalent specification of `gamma` is fine, as long as the matrix multiplication in the single line 113 is present, `M*gamma`

What do you think?
Will definitely keep revisiting this to help see this thru, would be a great contribution for 'dimension reduced spatial' random effects to analyze spatial big data

**Comment by paul-buerkner** [comment]
@mikejacktzen Thanks for all the details! I have two questions.

1. What does Q add to the existing CAR models? When do we need it?

2. I wonder how this plays with the current parameterization of CAR models in brms, using exact sparse representations (see https://github.com/mbjoseph/CARstan). Asked differently, how should we extent the existing Stan code for CAR models in brms to incorporate Q?

**Comment by mikejacktzen** [comment]
for 1) basically dimension reduction leading to faster mcmc computations
the pre computed Q ideally is a much smaller matrix than those used by the vanilla CAR models
so, in each mcmc iteration, there is cheaper computation for the matrix algebra stuff

for 2) i'll have to think about that. All my use cases with these car models in stan were before the better 'sparse' implementations you linked to were developed.

**Comment by paul-buerkner** [comment]
1) Perhaps you are overestimating my knowledge here. I understand the idea behind dimension reduction, but where does this Q come from? How does the user know what to pass as Q?

2) Thanks!

**Comment by mikejacktzen** [comment]
I left out the details in 1, but yes, there is an exact recipe. Here

https://github.com/mikejacktzen/datzen/blob/master/R/moran_op.R

In short, the Q matrix is the result of multiplying a subset of eigen values/vectors to covariate features and spatial adjacencies.

The dimension reduction happens when the user chooses a small set of eigen vals / vecs to use.

An added benefit of this is that the resulting spatial random effects are 'orthogonal' to the covariate features. A problem that some people have pointed out with the vanilla car is that the resulting vanilla spatial random effects are 'confounded' (not orthogonal) with covariate features.

**Comment by paul-buerkner** [comment]
I am currently going through old brms issues to clean up the brms issue tracker. I had some time to look into the details of reparameterizations of CAR models today so that I can finally say something about the approach you are proposing. The main 2 features are (1) dimension reduction and (2) orthogonalization with respect to other predictors ("fixed effects"). For reasons explained at the end of #600, feature (2) is not going to be implemented in brms.

This leaves us with a possible dimension reduction of the spatial random effects, which seems a potentially relevant feature for brms. However, the proposed interface `cor_car_variant(W, Q)` is not a good user interface for this purpose since we cannot expect users to come up with Q themselves. Further, to my understanding, your Q depends on W and so we are basically passing some information twice, which we should avoid. I potentially better interface (given that we only aim for a dimension reduction) is `cor_car(W, k = <smaller than or equal N>)` where `k` gives the dimension of the (reduced) spatial random effects vector. If `k = N`, we would simply use the full dimensionality. Based on what I have read, this seems possible and sensible, but I don't have the time to figure out the details myself.

Accordingly, if you or someone else comes up with a good implementation of a dimensionality reduced CAR model, please open a new issue and I am happy to add thise feature to the CAR capabilities of brms. To keep the issue tracker and the issues themselves clean I will close this issue as the here proposed version will not be implemented in brms.
