### ISSUE TITLE
Increasing number of decimal places in summary()

### ISSUE THREAD

**Issue by superdayv** [paul-buerkner/brms#287]
I may be unaware of another way to do this, but when I try to increase the number of decimal places in the output through:

    options(digits=10)

the summary() function seems to be stuck providing two decimal places.

Is there a way around this?

**Comment by paul-buerkner** [comment]
Go for `print(summary(<your model>), digits = 10)` or as a short form `print(<your model>, digits = 10)`

**Comment by superdayv** [comment]
Oh perfect! Sorry to post such a mundane question. Thanks for the help!

**Comment by paul-buerkner** [comment]
All good. You are welcome :-)
