### ISSUE TITLE
problem loading brms

### ISSUE THREAD

**Issue by pviton** [paul-buerkner/brms#289]
I'm trying to load brms using

R version 3.2.4 (2016-03-10) -- "Very Secure Dishes"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

under MS Win 7. Running library(brms) returns:

Loading required package: Rcpp
Loading required package: ggplot2
Error in inDL(x, as.logical(local), as.logical(now), ...) : 
  unable to load shared object 'C:/ProgramFiles/R/R-3.2.4/library/rlang/libs/x64/rlang.dll':
  LoadLibrary failure:  The specified procedure could not be found.

As far as I can see, this dll exists in the specified location. Also, I get a message

The procedure entry point R_ExternalPtrAddrFn could not be found in [R.dll]

I know that my R version is a bit old, but the CRAN entry for brms says that the required R version is > 3.2.0, so I qualify. Can anyone see what's going wrong? Rstan is installed and is working correctly.

Thanks for any advice!

**Comment by paul-buerkner** [comment]
I am pretty sure this is not a brms issue, but one of the package "rlang",
of which brms depends on indirectly. Try updating R to the latest version
if possible.

2017-11-12 18:57 GMT+01:00 pviton <notifications@github.com>:

**Comment by pviton** [comment]
Thanks for your very fast reply! You're right : it was rlang; rather than update my entire R system I just installed rlang 0.1.2 and that was enough to get brms to load correctly. Thanks again!
