### ISSUE TITLE
Setting seed in vignettes

### ISSUE THREAD

**Issue by jsta** [paul-buerkner/brms#291]
I would like to reproduce the analyses in the vignettes. Would a PR adding seeds be welcome?

**Comment by paul-buerkner** [comment]
brms automatically sets a seed, but in Stan results are only fully
reproducible on the same machine anyway.

Accordingly, you will get other results than I do anyway.

2017-11-14 17:51 GMT+01:00 Joseph Stachelek <notifications@github.com>:

**Comment by jsta** [comment]
Interesting! Thanks for the info.
