### ISSUE TITLE
posterior_samples returning more parameters than requested

### ISSUE THREAD

**Issue by ferberkl** [paul-buerkner/brms#292]
Hi Paul,

First, thanks for developing an excellent package that has made my transition to Bayesian models much easier.

When I input a character vector of parameters for which I want posterior samples, it is returning those parameters plus others I did not ask for (specifically other interaction terms). Please see below.

Thanks,
Kyle

![image](https://user-images.githubusercontent.com/7082452/32918580-d2dbc9a6-caf0-11e7-9e94-c4bbe2f26928.png)

**Comment by paul-buerkner** [comment]
By default, pars is evaluated as a regular expression. To turn off this
behavior, set exact_match to TRUE.

Am 16.11.2017 23:10 schrieb "ferberkl" <notifications@github.com>:

**Comment by ferberkl** [comment]
Got it. Thanks!
