### ISSUE TITLE
Distributional regression with a Random effects matrix 

### ISSUE THREAD

**Issue by MichelNivard** [paul-buerkner/brms#297]
Is the following model identified in brms:

fit_phylo_random <- brm(bf(y ~ (1|phylo), sigma ~ (1|phylo)),
                   data = data, family = gaussian(),
                   cov_ranef = list(phylo = A),
                   chains = 2, control = list(adapt_delta = 0.95))

and does this model add a random inercept defined by design matrix A to the model of sigma, or will this fail?

**Comment by paul-buerkner** [comment]
This should work, but it will model sigma on the log-scale by default to
ensure that sigma itself is postive.

2017-12-04 11:52 GMT+01:00 MichelNivard <notifications@github.com>:

**Comment by MichelNivard** [comment]
That seems reasonable, and is probably modifiable behavior right ? (as long as I pick a strictly positive scale for sigma?)'

**Comment by paul-buerkner** [comment]
If you want to model sigma on the linear ("identity") scale in a gaussian
model, go for

family = brmsfamily("gaussian", link_sigma = "identity")

In your case, this may work out nicely as well.

2017-12-04 14:51 GMT+01:00 MichelNivard <notifications@github.com>:

**Comment by MichelNivard** [comment]
one more Q on this. I cant seem to get brms to run with more than 1 ranef covariance matrix present. My code:

Model_phylo3 <- brm(pheno ~(1|phylo) + (1|err),data=dataset,cov_ranef = list(phylo=K,err=C),chains = 4)

Tere is no error, likely a failure to compile?

**Comment by paul-buerkner** [comment]
Could you provide a reproducible example (with fake data) so that I can try
it out?

2017-12-04 15:41 GMT+01:00 MichelNivard <notifications@github.com>:

**Comment by MichelNivard** [comment]
`
sib_K <- function (N, fam_size = 5) 
{
  if (N != abs(round(N))) 
    stop("N must be a positive integer")
  if (fam_size != abs(round(fam_size))) 
    stop("fam_size must be a positive integer")
  num_fams <- N/fam_size
  if (num_fams != round(num_fams)) 
    stop("fam_size must divide N")
  K <- matrix(0, N, N)
  for (family in 1:num_fams) {
    fam_inds <- (family - 1) * fam_size + 1:fam_size
    K[fam_inds, fam_inds] <- 0.5
  }
  diag(K) <- 1
  K
}

rpheno <-function (N, P, K, h2 = rep(0.5, P), B, E) 
{
  if (!all(dim(K) == N)) 
    stop("K must be a NxN matrix")
  if (missing(B)) {
    B <- rWishart(1, P, 1/P * diag(P))[, , 1]
  }
  else {
    if (!all(dim(B) == P)) 
      stop("B must be a PxP matrix")
  }
  if (missing(E)) {
    E <- rWishart(1, P, 1/P * diag(P))[, , 1]
  }
  else {
    if (!all(dim(E) == P)) 
      stop("E must be a PxP matrix")
  }
  B <- diag(sqrt(h2)) %*% cov2cor(B) %*% diag(sqrt(h2))
  E <- diag(sqrt(1 - h2)) %*% cov2cor(E) %*% diag(sqrt(1 - 
                                                         h2))
  Y <- mat.sqrt(K) %*% matrix(rnorm(N * P), N, P) %*% mat.sqrt(B) + 
    matrix(rnorm(N * P), N, P) %*% mat.sqrt(E)
  Y
}




N       <- 500
P       <- 2
K      <- sib_K(N,fam_size=2)
Y      <- rpheno(N,P,K,h2=c(.5,.5))
phylo <- 1:N
err <- 1:N

dataset<- cbind.data.frame(Y[,1],phylo,err)
colnames(dataset) <- c("pheno","phylo","err")
rownames(dataset) <- 1:N

colnames(K) <- 1:N
rownames(K) <- 1:N
C <- matrix(as.numeric( K != 0),500,500)

colnames(C) <- 1:N
rownames(C) <- 1:N
Model_phylo3 <- brm(pheno ~(1|phylo) + (1|err),data=dataset,cov_ranef = list(phylo=K,err=C),chains = 4)


`

**Comment by paul-buerkner** [comment]
Thanks! Not sure where the function `mat.sqrt` comes from, but with a dummy function for it, I get the error `Error: Covariance matrix of grouping factor 'err' is not positive definite.`
If you don't see any error message, as you say, restart R and try it again. Sometimes Rstudio eats error messages after running a Stan model on multiple cores.

**Comment by MichelNivard** [comment]
Ah,  yeah it isn't. In contemporary maximum likelihood solutions to the problem I am working on it doesn't need to be (only the total random effects co-variance matrix needs to be). I'll try to add a very small value to the diagonal and take it from there thanks.

**Comment by paul-buerkner** [comment]
In brms, each of these matrices is cholesky transformed (and used in the Stan code), separately, and hence all of them must be positive definite on their own (otherwise the cholesky tranform is not defined).
