### ISSUE TITLE
Including all remaining variables via "." operator gives error

### ISSUE THREAD

**Issue by tomwallis** [paul-buerkner/brms#298]
I get the following error if I use the "." operator to include all remaining variables:

```r
Error in terms.formula(as.formula(x)) : 
  '.' in formula and no 'data' argument
```

Reproducible example:

```r
library(brms)
library(dplyr)

dat <- brms::epilepsy
dat <- dat %>% select(count, log_Age_c, log_Base4_c, Trt_c)

fit1 <- brm(count ~ ., data = dat, family = poisson())
```

I'm on version 1.10.2. I'm pretty sure this worked in older versions?

**Comment by paul-buerkner** [comment]
Yes, it used to work. Can you try it with the latest dev version from github?

**Comment by tomwallis** [comment]
Ha. That works. So not sure what caused it. Thanks Paul!
