### ISSUE TITLE
brms cheat sheet

### ISSUE THREAD

**Issue by paul-buerkner** [paul-buerkner/brms#305]
On twitter, Andrew McDonald suggested writing a cheat sheet for brms similar to how it is done for many other packages and I agree (e.g., see the cheat sheets of RStudio: https://github.com/rstudio/cheatsheets). This issue is simply a reminder that I don't forget about it

**Comment by jgabry** [comment]
We'd love to have these for all of the Stan dev team's R packages (which now include brms!). This seems like something that could be contributed from the community rather than something that needs to take away time from development. I'll post over on Discourse and see if we get any volunteers to help with cheatsheets.

**Comment by jgabry** [comment]
http://discourse.mc-stan.org/t/contribute-cheatsheets-for-the-stan-ecosystem-in-r/4011

**Comment by jebyrnes** [comment]
Love this. Question - would a brms cheat sheet highlight all of the different ways one can use brms, or just a straight through analysis of a linear model as an example?

**Comment by paul-buerkner** [comment]
I don't know yet. There is so much to put on a cheat sheet for brms that we will likely end up with multiple sheets.

**Comment by hsbadr** [comment]
@paul-buerkner Just a reminder :)

**Comment by paul-buerkner** [comment]
I continue to like the idea of cheat sheets. But for several years now, nobody was motivated to work on it. I personally won't have time for it either for the forseeable future. Accordingly, I will close this issue now. 

If somebody is motivated to work on brms cheat sheets, please write here and I am happy to reopen this issue.
