### ISSUE TITLE
Predictions for ordinal models not working

### ISSUE THREAD

**Issue by David-Hervas** [paul-buerkner/brms#306]
Hello, updated today to version 2.0.1 and predictions from ordinal models are not working, they throw the following error:

```
Error: New factor levels are not allowed.
Levels allowed: '1', '2', '3', '4', '5', '6'
Levels found: 'NaN'
```

Here is a reproducible example
```
#Ordinal model
test.data <- data.frame(y  = ordered(sample(1:6, 50, replace = TRUE)), 
                        x1 = rnorm(50), 
                        x2 = rnorm(50))
mod1 <- brm(y ~ x1 + x2, family = "cumulative", data = test.data)
predict(mod1, newdata = data.frame(x1 = 1, x2 = 2))  #Error

#Linear model
test.data$y2 <- as.numeric(test.data$y)
mod2 <- brm(y2 ~ x1 + x2, family = "gaussian", data = test.data)
predict(mod2, newdata = data.frame(x1 = 1, x2 = 2))  #Works as expected
```

**Comment by paul-buerkner** [comment]
Thanks! I can confirm this is a bug in version 2.0.1.

I just fixed it in the github version of brms to be installed via

if (!require("devtools")) {
  install.packages("devtools")
}devtools::install_github("paul-buerkner/brms", dependencies = TRUE)


2017-12-28 23:40 GMT+01:00 David Hervas <notifications@github.com>:
