### ISSUE TITLE
Predictions from ordinal models still not working

### ISSUE THREAD

**Issue by David-Hervas** [paul-buerkner/brms#307]
Hello, I just updated with the github version and predictions from ordinal models are still not working correctly. I get the following error:

```
test.data <- data.frame(y  = ordered(sample(1:6, 50, replace = TRUE)), 
                        x1 = rnorm(50), 
                        x2 = rnorm(50))
mod1 <- brm(y ~ x1 + x2, family = "cumulative", data = test.data)
predict(mod1, newdata = data.frame(x1 = 1, x2 = 2))
```
```
Error: eta must be a numeric vector or matrix.
```

Further testing reveals that the issue only occurs when the 'newdata' `data.frame` has just one row. It works fine otherwise:

`predict(mod1, newdata = data.frame(x1 = c(1,2), x2 = c(2,1)))`

```
     P(Y = 1) P(Y = 2) P(Y = 3) P(Y = 4) P(Y = 5) P(Y = 6)
[1,]  0.08100  0.14975  0.14975  0.16200  0.11875  0.33875
[2,]  0.09475  0.16175  0.14125  0.17025  0.12050  0.31150
```

**Comment by paul-buerkner** [comment]
Thanks and apologies for not fixing it completely in the first place. This is a typical problem of R dropping dimensions somewhere when not explicitely told otherwise... Would you mind trying it again with the updated dev version of brms?

**Comment by David-Hervas** [comment]
Now it's working as expected. Thanks for the quick fix!

**Comment by paul-buerkner** [comment]
I am glad to hear that!
