### ISSUE TITLE
Implementation of Johnson-Neyman Technique

### ISSUE THREAD

**Issue by seonghobae** [paul-buerkner/brms#309]
Hi,

I'm wanna to implement the Johnson-Neyman Technique where calibrated brms object but I do not know how to make work that.

Any Ideas?

Best,
Seongho

**Comment by paul-buerkner** [comment]
I did previously not know anything of the Johnson-Neyman Technique, but following the paper D'Alonso et al. (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3203541/pdf/nihms329467.pdf), it seems entirely frequentist (non-Bayesian) at least in the formulations I have seen so far. For instance, in its computation, we repeatedly use F-values, which is typical for classical ANOVA like methods but usually irrelevant in Bayesian statistics. Accordingly, I don't think it is reasonble to perform in brms unless you can point me to a Bayesian version of it.

**Comment by paul-buerkner** [comment]
I very much like what you have written about a Bayesian approach to the Johnson-Neyman technique in 7.4!

**Comment by ASKurz** [comment]
That's great to read; thanks!
