### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by bachlaw** [paul-buerkner/brms#31]
Great software, but the latest version does not upgrade or install for me, even clean.  The error seems to arise in this section:

1112: #include <rstan/rstaninc.hpp>
1113: /**
1114:  * Define Rcpp Module to expose stan_fit's functions to R.
1115:  */
1116: RCPP_MODULE(stan_fit4model19b4ffa5ef5_gaussian_identity__brms_model_mod){
1117:   Rcpp::class_<rstan::stan_fit<model19b4ffa5ef5_gaussian_identity__brms_model_namespace::model19b4ffa5ef5_gaussian_identity__brms_model,
1118:                boost::random::ecuyer1988> >("stan_fit4model19b4ffa5ef5_gaussian_identity__brms_model")
1119:     // .constructor<Rcpp::List>()
1120:     .constructor<SEXP, SEXP>()
1121:     // .constructor<SEXP, SEXP>()
1122:     .method("call_sampler",
1123:             &rstan::stan_fit<model19b4ffa5ef5_gaussian_identity__brms_model_namespace::model19b4ffa5ef5_gaussian_identity__brms_model, boost::random::ecuyer1988>::call_sampler)
1124:     .method("param_names",
1125:             &rstan::stan_fit<model19b4ffa5ef5_gaussian_identity__brms_model_namespace::model19b4ffa5ef5_gaussian_identity__brms_model, boost::random::ecuyer1988>::param_names)
1126:     .method("param_names_oi",
1127:             &rstan::stan_fit<model19b4ffa5ef5_gaussian_identity__brms_model_namespace::model19b4ffa5ef5_gaussian_identity__brms_model, boost::random::ecuyer1988>::param_names_oi)
1128:     .method("param_fnames_oi",
1129:             &rstan::stan_fit<model19b4ffa5ef5_gaussian_identity__brms_model_namespace::model19b4ffa5ef5_gaussian_identity__brms_model, boost::random::ecuyer1988>::param_fnames_oi)
1130:     .method("param_dims",
1131:             &rstan::stan_fit<model19b4ffa5ef5_gaussian_identity__brms_model_namespace::model19b4ffa5ef5_gaussian_identity__brms_model, boost::random::ecuyer1988>::param_dims)
1132:     .method("param_dims_oi",
1133:             &rstan::stan_fit<model19b4ffa5ef5_gaussian_identity__brms_model_namespace::model19b4ffa5ef5_gaussian_identity__brms_model, boost::random::ecuyer1988>::param_dims_oi)
1134:     .method("update_param_oi",
1135:             &rstan::stan_fit<model19b4ffa5ef5_gaussian_identity__brms_model_namespace::model19b4ffa5ef5_gaussian_identity__brms_model, boost::random::ecuyer1988>::update_param_oi)
1136:     .method("param_oi_tidx",
1137:             &rstan::stan_fit<model19b4ffa5ef5_gaussian_identity__brms_model_namespace::model19b4ffa5ef5_gaussian_identity__brms_model, boost::random::ecuyer1988>::param_oi_tidx)
1138:     .method("grad_log_prob",
1139:             &rstan::stan_fit<model19b4ffa5ef5_gaussian_identity__brms_model_namespace::model19b4ffa5ef5_gaussian_identity__brms_model, boost::random::ecuyer1988>::grad_log_prob)
1140:     .method("log_prob",
1141:             &rstan::stan_fit<model19b4ffa5ef5_gaussian_identity__brms_model_namespace::model19b4ffa5ef5_gaussian_identity__brms_model, boost::random::ecuyer1988>::log_prob)
1142:     .method("unconstrain_pars",
1143:             &rstan::stan_fit<model19b4ffa5ef5_gaussian_identity__brms_model_namespace::model19b4ffa5ef5_gaussian_identity__brms_model, boost::random::ecuyer1988>::unconstrain_pars)
1144:     .method("constrain_pars",
1145:             &rstan::stan_fit<model19b4ffa5ef5_gaussian_identity__brms_model_namespace::model19b4ffa5ef5_gaussian_identity__brms_model, boost::random::ecuyer1988>::constrain_pars)
1146:     .method("num_pars_unconstrained",
1147:             &rstan::stan_fit<model19b4ffa5ef5_gaussian_identity__brms_model_namespace::model19b4ffa5ef5_gaussian_identity__brms_model, boost::random::ecuyer1988>::num_pars_unconstrained)
1148:     .method("unconstrained_param_names",
1149:             &rstan::stan_fit<model19b4ffa5ef5_gaussian_identity__brms_model_namespace::model19b4ffa5ef5_gaussian_identity__brms_model, boost::random::ecuyer1988>::unconstrained_param_names)
1150:     .method("constrained_param_names",
1151:             &rstan::stan_fit<model19b4ffa5ef5_gaussian_identity__brms_model_namespace::model19b4ffa5ef5_gaussian_identity__brms_model, boost::random::ecuyer1988>::constrained_param_names)
1152:     ;
1153: }
1154: 
1155: // declarations
1156: extern "C" {
1157: SEXP file19b42a4479df( ) ;
1158: }
1159: 
1160: // definition
1161: 
1162: SEXP file19b42a4479df(  ){
1163:  return Rcpp::wrap("gaussian(identity) brms-model");
1164: }
1165: 
1166: 
Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! Warning message:
running command 'make -f "C:/PROGRA~1/R/R-32~1.3/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-32~1.3/share/make/winshlib.mk" -f "C:/Users/Alien/Documents/.R/Makevars" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="file19b42a4479df.dll" WIN=64 TCLBIN=64 OBJECTS="file19b42a4479df.o"' had status 127 
Error : unable to load R code in package 'brms'
ERROR: lazy loading failed for package 'brms'

**Comment by paul-buerkner** [comment]
I see that you are using Windows. Did you try to install the latest version from CRAN? 

As brms 0.7.0 is only 2 days old, the windows binaries are not available on CRAN yet. Thus, you have to install from source which requires compilation and you thus need a C++ compiler. For Windows you should install Rtools (https://cran.r-project.org/bin/windows/Rtools/) and make sure you check the box, when you are asked to change the system path. Then restart R and try again. 

Apart from the installation process, you will need a C++ compiler anyway when fitting models with brms. This is because brms is based on Stan requiring compilation of its models.

**Comment by bachlaw** [comment]
This fixed it. Thanks much.

Sent from my iPhone

On Jan 20, 2016, at 1:37 AM, Paul-Christian B?rkner <notifications@github.com<mailto:notifications@github.com>> wrote:


I see that you are using Windows. Did you try to install the latest version from CRAN?

As brms 0.7.0 is only 2 days old, the windows binaries are not available on CRAN yet. Thus, you have to install from source which requires compilation and you thus need a C++ compiler. For Windows you should install Rtools (https://cran.r-project.org/bin/windows/Rtools/) and make sure you check the box, when you are asked to change the system path. Then restart R and try again.

Apart from the installation process, you will need a C++ compiler anyway when fitting models with brms. This is because brms is based on Stan requiring compilation of its models.

-
