### ISSUE TITLE
fit and predict MV ordinal

### ISSUE THREAD

**Issue by DavWest** [paul-buerkner/brms#314]
Dear Paul,

Thanks a lot for your fantastic package!

Fitting of multivariate ordinal models might be a problem as well as prediction based on these models. Please find a reproducible example below.

`
#data
d1 <- data.frame(y1 = ordered(sample(LETTERS[1:4], 100, replace=TRUE, prob=c(0.03, 0.29, 0.27, 0.41))),
y2 = ordered(sample(LETTERS[1:4], 100, replace=TRUE, prob=c(0.10, 0.33, 0.46, 0.11))),
y3 = ordered(sample(LETTERS[1:4], 100, replace=TRUE, prob=c(0.36, 0.02, 0.49, 0.13))),
x1 = rnorm(100))

#fit
fit_probit <- brm(cbind(y1, y2, y3) ~ x1, data = d1, family = cumulative(link = "probit", threshold = "flexible")) #working
fit_logit <- brm(cbind(y1, y2, y3) ~ x1, data = d1, family = cumulative(link = "logit", threshold = "flexible")) #Error in stanc(model_code = paste(program, collapse = "\n"), model_name = model_cppname,  : c++ exception (unknown reason)

#predict
predict_probit1 <- predict(fit_probit) #working
predict_probit2 <- predict(fit_probit, newdata = data.frame(x1 = 0.5)) #Error in array(eta, dim = c(dim(eta), ncat - 1)) : negative length vectors are not allowed
`

Best,
David

**Comment by paul-buerkner** [comment]
Thanks! Both problems should be fixed now in the dev version of brms from github.

**Comment by DavWest** [comment]
Everything works fine now. Thanks a lot!
