### ISSUE TITLE
Hierarchical Gaussian Processes

### ISSUE THREAD

**Issue by tbsmithca** [paul-buerkner/brms#316]
Is it possible to estimate hierarchical Gaussian processes with BRMS? I know that we can fit separate Gaussian processes according to factor levels, but I would like to be able to share information between the factor levels.

**Comment by paul-buerkner** [comment]
Can you point me to a reference, how exactly the model should look like that you have in mind?

**Comment by tbsmithca** [comment]
After looking around more deeply, it seems that the best way to do what I am looking for is to simply add two GPs, one that models the overall trend and the other that models the individual group trend.
