### ISSUE TITLE
What is the correct way to get a list of valid parameters for the dpar argument?

### ISSUE THREAD

**Issue by mjskay** [paul-buerkner/brms#318]
I am working on a package that extracts and tidies up samples from various Bayesian models, including brms. For that, it would be nice to be able to automatically get a list of parameters that can be passed to the `dpar` argument of `fitted.brmsfit` (see mjskay/tidybayes#99) so that estimates of all dpars could be extracted and tidied automatically.

My (hackish) approach that works on everything I have tried so far is this:

```r
# assuming `model` is a brms model, this (might) give a vector of values that
# can be passed to the `dpar` argument of `fitted.brmsfit`
names(parse_bf(model$formula)$dpar) %>%
  .[. != "mu"]
```

However, this looks very brittle to me. I was not able to find a solution to this in the documentation, but I may have missed it. If there is one, I would love to know what it is. If there is not, could something like this be added?

Thanks!

**Comment by paul-buerkner** [comment]
I can write a helper functions doing the same as `names(parse_bf(model$formula)$dpar)`, but that doesn't really add much value I think, since you already know this solution. One question: Why do you want to exclude `mu`? In most cases, `mu` is equivalent to the mean, but this may not always be the case, so `dpar = NULL` and `dpar = "mu"` may imply something different.

**Comment by mjskay** [comment]
> One question: Why do you want to exclude `mu`? In most cases, `mu` is equivalent to the mean, but this may not always be the case, so `dpar = NULL` and `dpar = "mu"` may imply something different.

Ah, I think I had thought there were situations where passing `dpar = "mu"` would fail even though `"mu"` was returned by `names(parse_bf(model$formula)$dpar)`, but I can't now find an example of that. I suspect that was only true of an old approach I had taken to trying to get the list of dpars.

However, this raises another question: it might be helpful to be able to determine if `dpar = NULL` and `dpar = "mu"` are equivalent for a given model, or if some other value of `dpar` is equivalent to `dpar = NULL`. Is there a way to do that?

**Comment by paul-buerkner** [comment]
In earlier version of brms `mu` was indeed not supported by argument `dpar` but this has changed.

Usually `mean(Y) = inv_link(mu)` so usually `dpar = NULL` and `dpar = mu` are the same. However, for some families, this is not correct. For instance for family `lognormal`, we have `mean(Y) = exp(mu + sigma^2 / 2)`.
In general, it is either `mu` itself of `mu` in combination with other parameters that determines the mean, which is returned by fitted.

**Comment by mjskay** [comment]
Ah, okay. Also that is good to know that `scale = "response"` is set up to produce the mean, I had assumed (for example) that in the lognormal case it would produce the geometric mean (`exp(mu)`).

Thanks, this has been very helpful.

**Comment by paul-buerkner** [comment]
Great! Feel free to close this issue if all of your questions have been
answered.

Am 15.01.2018 17:55 schrieb "Matthew Kay" <notifications@github.com>:
