### ISSUE TITLE
 Average posterior predictive distributions

### ISSUE THREAD

**Issue by MadsJensen** [paul-buerkner/brms#319]
Is there function to make an  average posterior predictive distribution, i.e. where the posterior predictions are a weighted average based on two or more models. Like what McElreath (Statistical Rethinking) describe p. 203.

**Comment by paul-buerkner** [comment]
There was none, but now there is. :-) 

Check out the new method `pp_average` in the dev version of brms to be installed via 

```R
if (!require("devtools")) {
  install.packages("devtools")
}
devtools::install_github("paul-buerkner/brms", dependencies = TRUE)
```

**Comment by MadsJensen** [comment]
Great  thanks! And very fast implementation, I'll you know if I encounter any problems etc.
