### ISSUE TITLE
posterior_samples: rename chains -> chain

### ISSUE THREAD

**Issue by schmettow** [paul-buerkner/brms#32]
posterior_samples(brmsfit, add.chains = T) returns a data.frame with additional columns "chain*s*" and "iter". As "chains" is an identifier variable, it would be more memorable to call the column "chain" (singular).

**Comment by paul-buerkner** [comment]
I agree. What I am a bit worried about is backwards compatibility, since `chains` is not a prefix of `chain` and thus `$` won't find the `chain` column if `$chains` is used. The easiest solution would be to have both columns for now, but maybe you have another idea.

**Comment by schmettow** [comment]
maybe, you could handle this by introducing a redundant parameter `add.chain` for `posterior_samples` which would then name the column "chain". You could mark `add.chains` as deprecated (like you did with other function parameters before). In any case: not a big deal and applause for this great package!

**Comment by paul-buerkner** [comment]
This sounds like a good idea :-)
