### ISSUE TITLE
control parameters revert to default when updating model

### ISSUE THREAD

**Issue by ferberkl** [paul-buerkner/brms#326]
The control parameters revert to default when using the update() function. For example:

fit1 <- brm(outcome ~ (1 | group), data=data1,
                   control = list(adapt_delta = 0.95))

fit2 <- update(fit1, newdata=data2)

control_params(fit2) shows adapt_delta = 0.8

Is this the intended behavior? I think it would be nice if the same control parameters were used in the updated model fit.

**Comment by paul-buerkner** [comment]
It was intentional when I initially coded it, but now I am no longer sure. I will think about this and whether there are potential drawbacks in keeping the control arguments of the initial model.

**Comment by paul-buerkner** [comment]
In the github version of brms, `update` now keeps the original control arguments if they are not overwritten by the user. Thanks making me aware of this issue!

**Comment by ferberkl** [comment]
Thanks, Paul!
