### ISSUE TITLE
Truly silent option

### ISSUE THREAD

**Issue by lindeloev** [paul-buerkner/brms#329]
I am creating a notebook including `brms` examples. `brm` breaks up code blocks even when `silent = TRUE, refresh=0` and the code block suppresses everything (`{r, cache=TRUE, results='hide', messages=FALSE, warnings=FALSE, errors=FALSE}`). Screenshot:

![image](https://user-images.githubusercontent.com/1439417/35200720-096cd5f4-ff13-11e7-8540-bb7bef3c9747.png)

While a relatively minor problem, this makes it a bit harder to read and copy-paste code. This issue was raised in #166, but maybe the notebook case is more clear? It was also discussed in stan and Rstan, but from what I can read, they fixed it: https://github.com/stan-dev/rstan/issues/49.

**Comment by paul-buerkner** [comment]
The output you see is send through the message stream so anything the suppresses messages, will suppress this as well. I think you mispelled the arguments of the code block header. It should be `message=FALSE` and `warning=FALSE` (no plural).

**Comment by lindeloev** [comment]
You are right, I misread the knitr documentation. Thank you!

**Comment by DanyangDai** [comment]
Hi Paul

I was using `brm` for zero inflated beta in my rmd. With `message = FALSE` and `warning = FALSE`, it was still printing a long list of chain fittings. I found the solution from [Suppress all output from brms in Markdown files](https://discourse.mc-stan.org/t/suppress-all-output-from-brms-in-markdown-files/30117).

Using `output <- capture.output(fit <- brm(...))` works well for pdf outputs. Thanks to Yizhang.
