### ISSUE TITLE
newdata prediction with forked/hurdle families fails

### ISSUE THREAD

**Issue by rubenarslan** [paul-buerkner/brms#33]
I tested it only with hurdle models, but I think it's something general to forked families in brms:::melt_data.
You add a missing value dummy column for the response, but then you use model.frame without `na.action = na.pass` and end up with an empty column.
But if I "fix" this while debugging, I run into the next error from brms:::fitted_hurdle, which complains that data$N_trait is not set. I think you probably wanted to set it in brms:::amend_newdata at the end?

I'll send you the fit below via email.

```r
m1hg = brm(value ~ 0 + (0 + trait | target) + (0 + trait | rater) + trait * situation * gFaktor, gesamt_st, family = hurdle_gamma, warmup = 260, iter = 400, chains = 2)
summary(m1hg)
newd = unique(gesamt_unknown[, c("situation","gFaktor")])
predicted = fitted(m1hg, newdata = newd, re_formula = NA, summary = T)
```

```r
Error in `$<-.data.frame`(`*tmp*`, "response", value = logical(0)) : 
  replacement has 0 rows, data has 880
> traceback()
8: stop(sprintf(ngettext(N, "replacement has %d row, data has %d", 
       "replacement has %d rows, data has %d"), N, nrows), domain = NA)
7: `$<-.data.frame`(`*tmp*`, "response", value = logical(0))
6: `$<-`(`*tmp*`, "response", value = logical(0))
5: melt_data(data, family = family, effects = effects)
4: update_data(newdata, family = fit$family, effects = ee, et$group, 
       na.action = na.pass, drop.unused.levels = FALSE)
3: amend_newdata(newdata, fit = object, re_formula = re_formula, 
       allow_new_levels = allow_new_levels)
2: fitted.brmsfit(m1hnb, newdata = newd, re_formula = NA, summary = T)
1: fitted(m1hnb, newdata = newd, re_formula = NA, summary = T)
```

**Comment by paul-buerkner** [comment]
Thank you very much for finding and investigating the problem! I will try to fix this asap.

**Comment by paul-buerkner** [comment]
I hope to have it fixed now. 

As you already found out, there were actually 2 problems. The first could be resolved by passing the na.action argument of `update_data` (with  `na.action = na.pass` for new data) to `melt_data`. The second one was that `N_trait` was not available, because it was generated within the part of `make_stancode` where the response is checked. As we do not require the response to be defined in `newdata` (with a few exceptions), this part is omitted when predicting with new data. Now  `N_trait` is defined elsewhere in `make_stancode` and prediction works at least on my machine and with the model you sent me via email. 

I would be greatful, if you could retest this on your machine.

**Comment by rubenarslan** [comment]
Yes, it works for me too! The predictions look a bit odd tho:

![plot_zoom_png-2](https://cloud.githubusercontent.com/assets/831109/12488451/efd6da1e-c06b-11e5-969b-9fc2bfb7c0ac.png)

**Comment by paul-buerkner** [comment]
Can you explain, why it looks odd to you? Because they all look very similar or because of the CIs varying with `gFaktor`?

**Comment by rubenarslan** [comment]
Sorry, my bad. I expected one smooth line for the estimate, but I put in too few values in the new data object and ggplot didn't smooth it over. With more values it looks like I expected.
Thank you so much for the quick fix!

![plot_zoom_png-3](https://cloud.githubusercontent.com/assets/831109/12488874/f5b25ca4-c06d-11e5-9aa4-6e2558e242ca.png)

**Comment by paul-buerkner** [comment]
And thank you so much for catching this issue and helping me with the fix! :-)

**Comment by paul-buerkner** [comment]
Can you open a new issue and provide a minimal reproducible example?
