### ISSUE TITLE
k_fold: parameter problem with ...

### ISSUE THREAD

**Issue by dmenne** [paul-buerkner/brms#334]
Example in kfold.brmsfit

```
(kfold1 <- kfold(fit1, chains = 2, cores = 2))
# Fehler: Object '2' is not of class 'brmsfit'.
```
This is a base-R problem named parameters after ...

**Comment by paul-buerkner** [comment]
The `...` argument is reserved for brmsfit objects. Instead, go for

```R
(kfold1 <- kfold(fit1, update_args = list(chains = 2, cores = 2)))
```

**Comment by dmenne** [comment]
Correct, the code is from your not-run  examples

**Comment by paul-buerkner** [comment]
Oh... Sorry ;-)

**Comment by dmenne** [comment]
I promise, no more petty details. Just finished working through the full documenation.

**Comment by paul-buerkner** [comment]
Fixed! Thank you so much for looking at the documentation so thoroughly!!
