### ISSUE TITLE
posterior_predict with categorical response variable

### ISSUE THREAD

**Issue by lakras** [paul-buerkner/brms#336]
Hi! I think I might have found a bug—

I modeled a categorical response variable with 11 different values (district names), then tried to impute missing data using that model with posterior_predict. I get this error after running the posterior_predict function:

> Error: At least 3 response categories are required for family 'categorical'.
> Please use family 'bernoulli' instead.

(I tried using family bernoulli when I build my model, just to see what would happen, and it of course fails because my response variable has 11 different values.)

Thank you so much!

**Comment by paul-buerkner** [comment]
indeed, it looks like a bug. Could you please send me a reproducible
example (possibly with fake data)?

Lydia Andreyevna Krasilnikova <notifications@github.com> schrieb am Mi.,
31. Jan. 2018, 01:07:

**Comment by lakras** [comment]
Hi! Sorry for the delay! I am using version 2.1.0. Here's a reproducible example:

```
# TESTING BRM WITH PRETEND DATA
country         <- c("countryA", "countryB", "countryC", "countryD", "countryA", "countryC", "countryD", NA, NA)
interesting_num <- c(1, 2, 3, 4, 5, 6, 7, 7, 7)
boolean_value   <- c(TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE)

test_data <- data.frame(country, interesting_num, boolean_value)
test_data$country <- as.factor(test_data$country)

# fits model using presence/absence of other taxa
test_model = brm(country ~ boolean_value + interesting_num,
  family = categorical(link = "logit"), data=test_data, cores=4)

# selects predictor variable(s)
predictors = subset(test_data, select = c("boolean_value", "interesting_num"))

# imputes missing values
impute <- function(value, imputed_value)
{
  ifelse(is.na(value), imputed_value, value)
}
variable_index <- which(names(test_data) == "country")
variable_values <- test_data[, variable_index]
simulated_values <- posterior_predict(test_model, newdata = predictors, family=categorical(link="logit"))[1,]
imputed_values <- impute(variable_values, simulated_values)
```

Thank you so much!!!!

**Comment by paul-buerkner** [comment]
Thanks! It turned out being a typo in one of the validation functions, which only affected categorical models when applied to new data. Please try it again with the new github version of brms.

**Comment by jasonigriff** [comment]
Another bug seems to have emerged when applying the posterior_predict function to a model of a categorical response variable. 
When running the same example code provided above by lakras (posted on Feb 6th 2018) , I get the following error message when running the posterior_predict function on the model: 
"Error in dimnames(zeros_arr) <- `*vtmp*` : 'dimnames' must be a list"

I see the same error when using the predict and posterior_predict functions on models of other datasets that have categorical response variables and so I think this is a general issue for the class of models.

I am using : brms version 2.16.3

I look forward to discussing this further and love your package.

**Comment by paul-buerkner** [comment]
Which version of R are you using?

**Comment by jasonigriff** [comment]
I ran this using R version 3.6.1. I have since checked the current dev version of brms on github and this does indeed seem to have a fix for this issue. Thanks for a very fast response and for creating such a useful tool for such a diversity of analyses.
