### ISSUE TITLE
Specify fixed distributional parameters in brms?

### ISSUE THREAD

**Issue by bachlaw** [paul-buerkner/brms#339]
I apologize if this should be obvious, but I have reviewed the documentation for _brmsfamily_ and not found an answer for this:

Is there a way in `brms` to "force" a specified outcome variable distribution to coalesce around certain distributional parameters, e.g., to use a student_t distribution with 5 degrees of freedom rather than 1, or a particular shape parameter of the generalized extreme value (only reverse Weibull), instead of just allowing the model to estimate those parameters and/or use defaults for them when sampling?

**Comment by paul-buerkner** [comment]
See `?brmsformula`. For your example:

```R
formula <- bf(..., nu = 5)
```

**Comment by bachlaw** [comment]
Perfect, thank you.

Sent from my iPhone

On Feb 3, 2018, at 2:28 PM, Paul-Christian Bürkner <notifications@github.com<mailto:notifications@github.com>> wrote:


See ?brmsformula. For your example:

formula <- bf(..., nu = 5)
