### ISSUE TITLE
Parameters not listed in launch_shinystan

### ISSUE THREAD

**Issue by ecologics** [paul-buerkner/brms#340]
Not sure if this is a bug, or a feature that is waiting to happen, or alternatively impossible to do, but I'm guessing it stems from the vectorization of the regression and the absence of parameter definition in the `generated quantities` block.

Models built with brms and examined using `launch_shinystan()` are missing most of their `b_` parameters under plots in the "DIAGNOSE" and "EXPLORE" tabs, but these will appear in the "ESTIMATES" tab.

Use of `save_all_pars=TRUE` makes no difference in this regard.

Using brms 2.1.2 and shinystan 2.4.0.

Sample code (from `brm()` help page). However, this occurs with any model.

```
data_het <- data.frame(y = c(rnorm(50), rnorm(50, 1, 2)),
                       x = factor(rep(c("a", "b"), each = 50)))
fit6 <- brm(bf(y ~ x, sigma ~ 0 + x), data = data_het, save_all_pars=TRUE)

launch_shinystan(fit6)
```
It would be great to have a `b_x` for example in the above model for examination in `shinystan`.

**Comment by paul-buerkner** [comment]
It should show all parameters, but maybe something that happens during internal renaming of parameters causes problems with shinystan. @jgabry Any ideas?

**Comment by paul-buerkner** [comment]
I realized I brought this up myself some time ago on the shinystan issue tracker (https://github.com/stan-dev/shinystan/issues/155), but it hasn't been touched for half a year now, although I would expect the fix to be relatively straightforward (without looking at the actual code I must admit). Since this isn't really a brms issue, I will close this issue and try to move the shinystan issue forward.

**Comment by iron0012** [comment]
I am also experiencing this. Is there a workaround? For example, is there a certain way that I could name my input variables in order for them to be recognized by shinystan?

**Comment by paul-buerkner** [comment]
No solution that I am aware of, unfortunately.

**Comment by ecologics** [comment]
I'commented on the shinystan issue tracker.
