### ISSUE TITLE
brm function causing R fatal errror

### ISSUE THREAD

**Issue by ballengerj** [paul-buerkner/brms#342]
Began using the brms package a few days ago, and seems to work perfectly on one Windows 7 PC, and not at all on another high-performance Windows 7 PC with the exact same code. Every time I run the function "brm" (whether using a single core or multiple cores) on PC 2 it crashes R after compiling the C++ model after starting sampling. Please find attached a screenshot of completed model on System 1 along with an associated diagnostic file for System 1 at that point. Also find attached a screenshot of fatal error for same model on System 2 along with an associated diagnostic file for System 2. I also tested the example provided in the "brms_overview" vignette, and it fails as well.

![system 1 -code works fine](https://user-images.githubusercontent.com/8918206/35932509-c86a8240-0c05-11e8-920b-2b2189a39bac.PNG)
[System 1 Diagnostic File.txt](https://github.com/paul-buerkner/brms/files/1704151/System.1.Diagnostic.File.txt)

![system 2 - fatal error to child processes](https://user-images.githubusercontent.com/8918206/35930818-ec1c2d38-0c00-11e8-922c-78878caa4ab1.PNG)
[System 2 Diagnostic File.txt](https://github.com/paul-buerkner/brms/files/1704077/System.2.Diagnostic.File.txt)

**Comment by paul-buerkner** [comment]
This is definitely not happening inside brms, but somewhere deeper, where I have no control over. What is the error message if you use only 1 core?

**Comment by ballengerj** [comment]
Unfortunately it doesn't give a true error message. It just causes the R session to terminate with a fatal error.

**Comment by paul-buerkner** [comment]
@bgoodri have you ever seen something like that before happening with rstan?

**Comment by bgoodri** [comment]
I have not seen this before. Can you try going to Tools -> Shell and then type `R` to start R at the command line. Then do
```
example(sampling, package = "rstan", run.dontrun = TRUE)
```
to see what the error message says.

**Comment by ballengerj** [comment]
Ok, I get the following message:

`Error in find.package(package, lib.loc, verbose = verbose): there is no package called 'rstan'`

That said, I do have `rstan` installed on the computer

**Comment by paul-buerkner** [comment]
I suggest uninstalling brms and rstan and install it again. If this doesn't solve your problem, I would ask the administrator of the high-performance Windows 7 PC (or any IT guy at your institute familiar with R), if he can help you installing rstan on it (as well as Rtools to get a C++ compiler if you haven't done that yet).

**Comment by ballengerj** [comment]
Prior to contact, I had already uninstalled and re-installed R, the packages `rstan` and `brms` and have verified that RTools is correctly installed and the c++ compiler is working appropriately. I just went through these steps once again now, and the error still occurs.

**Comment by bgoodri** [comment]
After doing

remove.packages("rstan")

check that

system.file("libs", "rstan.so", package = "rstan")

is an empty string. If not, you may have to manually delete that directory
using Windows Explorer or something.

Then reinstall rstan again. I am still not sure why this would cause a
crash in RStudio rather than just an error.

**Comment by ballengerj** [comment]
Followed those steps and got an empty string. In the meantime, I also checked and deleted some older versions of rstan (actually all packages) I found in older libraries for other R versions. I now keep all of my packages in a single repository for that very reason.

I then re-ran the code and it still did not work. I hadn't mentioned before, but sometimes when it fails I get the following message:

![system 2 - rscript application error](https://user-images.githubusercontent.com/8918206/35977348-e5015c16-0cb0-11e8-9e08-3ad9783d3c70.PNG)

I do not get this message every time it fails, but only some times. Because I got it initially, I had IT do a thorough hardware check to search for bad sectors on the hard disk. 

I appreciate any additional suggestions you guys can think of!

**Comment by ballengerj** [comment]
To be clear, this is the first time I got this message since reaching out to you guys for help, or I would have sent it sooner.

**Comment by paul-buerkner** [comment]
The only thing I can imagine is that in some situations, R searches for packages in a different folder than where you actually stored them. Ideally, we should use the default folder path for R packages, which I think on Windows is `C:\Users\<username>\Documents\R\win-library\<R.version>` (Windows 10 so not sure if the same on Windows 7), but I have really no idea if this is related to your problem.

**Comment by ballengerj** [comment]
Yeah, I don't really think that is it, as it is setup in exactly the same manner on the computer that the script does work on. I have a `.RProfile` file setup that sets the default package directory on both computers to the same directory.

**Comment by paul-buerkner** [comment]
Have you tried running the model in a simple Rscript not within Rmarkdown? Possibly, for some reason, not all R processes execute `.RProfile` at the start, or maybe the `.RProfile` isn't executed at all on your machine 2 (which is easy to test by adding a print statement in  `.RProfile`)? Again unlikely, but since we have seem to ruled out simple answers...

**Comment by ballengerj** [comment]
Yes, I have tried to run it directly from the R console. Same result. As for the `.RProfile` it does have a couple of print statements in it so I know it is running correctly. Also, I have had success running `rstan` programs on computer 2 in the past. I'm going to try to run a couple of examples from it on the computer now to see if they still work.

**Comment by ballengerj** [comment]
Just ran an example from `rstan` and it seemed to work without a problem.

**Comment by paul-buerkner** [comment]
Nice, so I would expect it to work with brms as well, since brms interally calls rstan anyway and has nothing to do with the deeper details. Otherwise, can you generate stan code and data using `brms::make_stancode` and `brms::make_standata`, then pass this to `rstan::stan` and see if it still works?

**Comment by ballengerj** [comment]
Tried that with no luck. I get the same error. 

For this I used both my model and your model from `fit1` from the `brm` help page.  Both gives the same result, though I do get a little more information on where in the process it stops working.

![system 2 - running directly using stan](https://user-images.githubusercontent.com/8918206/35986796-08e0a35a-0cc8-11e8-99a8-a0fa0e0d6741.PNG)

**Comment by ballengerj** [comment]
Ran the following example from `stan` and it runs fine. Do you think it could be something with how `make_stancode` is parsing the stan model code and something is different between the two machines?

`scode <- "
parameters {
  real y[2]; 
} 
model {
  y[1] ~ normal(0, 1);
  y[2] ~ double_exponential(0, 2);
} 
"
fit1 <- stan(model_code = scode, iter = 10, verbose = FALSE) 
print(fit1)`

**Comment by paul-buerkner** [comment]
No, I don't think so. Rather it could be the complexity / size of the model and / or the data and some memory problem. I have found a similar error message on the Steam help forums (https://support.steampowered.com/kb_article.php?ref=1274-uohk-5653). Maybe this helps. Anyway, this is with very high certainty no problem of brms, Stan or R but points to underlying problems of your system, which I am not able to solve.

**Comment by paul-buerkner** [comment]
Just a quick follow-up: Were you able to solve this problem?

Since it is not an issue I can fix from the brms side, I would like to close it to keep the issue tracker clean.

**Comment by ballengerj** [comment]
Unfortunately we have yet to solve the issue. I'm still working on it though. If you have any additional ideas, please let me know.

**Comment by paul-buerkner** [comment]
I will do so.

2018-02-12 19:43 GMT+01:00 Joseph C. Ballenger <notifications@github.com>:

**Comment by adblackwell** [comment]
I have the same issue. The issue also occurs with the rethinking package, so I think it is a bug in rstan or rtools rather than brms. I can run brms models with no random effects, but as soon as I add random effects the models crash. The same models don't crash on other computers. I am reasonably certain it has to do with the processor. The computer that crashes has an i7-6700 processor. This might be related to the Skylake bug, however disabling hyperthreading in the bios doesn't make any difference. Anyway, I don't think changes in brms will fix this.

**Comment by adblackwell** [comment]
Actually the processor might have bee a red herring. I went into my MAKEVARS file and found that it said "CXXFLAGS=-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function". I changed it to "CXXFLAGS=-O3 -Wno-unused-variable -Wno-unused-function", per the rstan documentation and it seems to have fixed the issue.

**Comment by paul-buerkner** [comment]
That's very nice to hear! Thanks for sharing.
