### ISSUE TITLE
Noob question about beta-binomial estimation in brms

### ISSUE THREAD

**Issue by alexhallam** [paul-buerkner/brms#344]
I am interested in producing shrinkage estimates. I have done this previously with David Robinsons `ebbr` [package](https://github.com/dgrtwo/ebbr). 

The idea is that rows (batters, in this example) with fewer observations are shrunk to the overall mean more than rows with more observations. 

In his examples he uses Empirical Bayes, but I am aware that Hierarchical Bayes can also produce shrinkage estimates. 

Is it possible to produce similar shrunken estimates in `brms`?

As an example say I have the following data:

```
   name                  H    AB average
   <chr>             <int> <int>   <dbl>
 1 Hank Aaron         3771 12364  0.305 
 2 Tommie Aaron        216   944  0.229 
 3 Andy Abad             2    21  0.0952
 4 John Abadie          11    49  0.224 
 5 Ed Abbaticchio      772  3044  0.254 
 6 Fred Abbott         107   513  0.209 
 7 Jeff Abbott         157   596  0.263 
 8 Kurt Abbott         523  2044  0.256 
 9 Ody Abbott           13    70  0.186 
10 Frank Abercrombie     0     4  0   
```

For copy and paste ease, here is the dput

```
structure(list(name = c("Hank Aaron", "Tommie Aaron", "Andy Abad", 
"John Abadie", "Ed Abbaticchio", "Fred Abbott", "Jeff Abbott", 
"Kurt Abbott", "Ody Abbott", "Frank Abercrombie"), H = c(3771L, 
216L, 2L, 11L, 772L, 107L, 157L, 523L, 13L, 0L), AB = c(12364L, 
944L, 21L, 49L, 3044L, 513L, 596L, 2044L, 70L, 4L), average = c(0.304998382400518, 
0.228813559322034, 0.0952380952380952, 0.224489795918367, 0.253613666228647, 
0.208576998050682, 0.263422818791946, 0.25587084148728, 0.185714285714286, 
0)), .Names = c("name", "H", "AB", "average"), row.names = c(NA, 
-10L), class = c("tbl_df", "tbl", "data.frame"))
```

**Comment by paul-buerkner** [comment]
Beta binomial models are not yet implemented (see #231), but normal binomial models will produce similar results and shrinkage. For your data, go for

```R
fit <- brm(H | trials(AB) ~ 1 + (1 | Name), <your data>, family = binomial())
```

**Comment by alexhallam** [comment]
Thanks for the great reply!

I ended up using a larger sample in what follows (500 rows). The full data set was around 9000 rows and that was taking too long.

The code you provided worked great:
`fit <- brm(H | trials(AB) ~ 1 + (1 | name), data = example, family = binomial())`


Also, from a quick visual inspection is seems that the shrinkage is working as I would expect

```
ex_df <- example %>% modelr::add_predictions(fit) %>% 
  rowwise() %>% mutate(hbayes_esimate = pred/AB)
ex_df  %>%
  ggplot()+
  geom_point(aes(y=average,x=AB,group=name),shape=21)+
  geom_point(aes(y=hbayes_esimate,x=AB,color=log(AB),group=name))+
  geom_hline(aes(yintercept=avg),data=avg_line)+
  geom_segment(aes(x = AB,y=average,xend=AB,yend=hbayes_esimate,group=name))+
  scale_x_log10()+
  coord_cartesian(xlim = c(100, 10000))  # this is just to decluter the plot for instructive purposes
```
![shrink](https://user-images.githubusercontent.com/9298693/36066834-4af6bd52-0e7f-11e8-9163-916a41513875.jpg)

One question I do have, is how to interpret the output of 

```
> summary(fit)
Group-Level Effects: 
~name (Number of levels: 492) 
              Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
sd(Intercept)     0.13      0.01     0.12     0.15        634 1.01

Population-Level Effects: 
          Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
Intercept    -1.11      0.01    -1.13    -1.10        651 1.00
```

I know that when doing logistic regression the coefficients are exponentiated to get odds ratios. If this is the case then is `exp(-1.11) = 0.33` the estimated overall odds?

**Comment by paul-buerkner** [comment]
This interpretation seems correct to me.
