### ISSUE TITLE
`predict` throws error on categorical regression

### ISSUE THREAD

**Issue by tvladeck** [paul-buerkner/brms#345]
I am using version of `2.1.3`, installed using `devtools`, but I had the same problem with the CRAN version (`2.1.0`) as well (which is what led me to install the version on github).

The issue is that `predict.brmsfit` does not seem to work with models with the `categorical` family. I get the following error: 

```R
Error in Summary.factor(c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L,  : 
  ‘max’ not meaningful for factors
```

Here is a minimal reprex: 

```R
> data("iris")
> iris_example_reg <- brm(
  Species ~ Sepal.Length, 
  data = iris,
  family = categorical,
  chains = 1, iter = 300
)
> newdata <- data.frame(Sepal.Length = 5.0)
> predict(iris_example_reg, newdata)
Error in Summary.factor(c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L,  : 
  ‘max’ not meaningful for factors
> posterior_predict(iris_example_reg, newdata)
Error in Summary.factor(c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L,  : 
  ‘max’ not meaningful for factors
```

**Comment by tvladeck** [comment]
It appears it that the error is thrown [here](https://github.com/paul-buerkner/brms/blob/56392b088135c1e562e9bf64638d9bed9e562046/R/data-predictor.R#L709) in `data_response.brmsterms`, which is called by `extract_old_standata`, which is called by `validate_newdata`, which is called by `predict

```R
out$ncat <- max(out$Y)
```

**Comment by paul-buerkner** [comment]
Thanks! I have been playing around with this a bit in 2.1.x, but I apparently didn't fix everything. Could you try it again with the latest github version?

**Comment by tvladeck** [comment]
This worked well for the reprex and for the more complicated model I was actually building. I think you can consider this closed.
