### ISSUE TITLE
too many correlations "overflow"

### ISSUE THREAD

**Issue by marcomarconi** [paul-buerkner/brms#350]
I have noticed that when the number of parameters grows quite big I encounter this error:

```
SYNTAX ERROR, MESSAGE(S) FROM PARSER:

ERROR:  Container index must be integer; found type=real
  error in 'model18c14975e4ea_file18c134bd7097' at line 101575, column 9
  -------------------------------------------------
101573:   cor_1[99998] = Cor_1[317,448]; 
101574:   cor_1[99999] = Cor_1[318,448]; 
101575:   cor_1[1e+05] = Cor_1[319,448]; 
                ^
101576:   cor_1[100001] = Cor_1[320,448]; 
  -------------------------------------------------

PARSER EXPECTED: <one or more container indexes followed by ']'>
Error in stanc(model_code = paste(program, collapse = "\n"), model_name = model_cppname,  : 
  failed to parse Stan model 'file18c134bd7097' due to the above error.

```

It looks like that 100000 gets to be translated to scientific notation before being used as an index.

**Comment by paul-buerkner** [comment]
Ouch, you have a model with quite a few correlation! ;-) 

Let me fix this bug.

**Comment by paul-buerkner** [comment]
Can you try it again with the latest github version of brms?

**Comment by paul-buerkner** [comment]
I am very curious what kind of model needs so many correlations. Can you show me the model you are trying to fit?

**Comment by marcomarconi** [comment]
Thanks, well, in fact I just executed a model with the wrong definition and I ran into this error. I thought it was worth reporting it anyways :)

**Comment by paul-buerkner** [comment]
So, you defined your grouping variable in front of the `|` in a grouping term? ;-)

Thanks for reporting it anyway!
