### ISSUE TITLE
Duplicated group-level effects are not allowed.

### ISSUE THREAD

**Issue by Aorus42** [paul-buerkner/brms#351]
Hello,

I get the error "Duplicated group-level effects are not allowed." when trying to run a model with the same group-level effect specified for multiple predictors. In the lme4 package it looks like it's possible to do something like this:
lmer(y ~ TREATMENT + TIME + (TREATMENT| SUBJECT) + (TIME | SUBJECT)

What would be the equivalent in brms? Many thanks!

**Comment by paul-buerkner** [comment]
Both of your group-level terms `(TREATMENT| SUBJECT)`  and `(TIME | SUBJECT)` contain an intercept, which is thus duplicated.

Why not `(TREATMENT + TIME | SUBJECT)` or, if you don't want the effects to be modeled as correlated, `(TREATMENT + TIME || SUBJECT)`?

**Comment by Aorus42** [comment]
Ahh, that works. Thank you for the very quick reply! I need to brush up on the brms syntax :).
