### ISSUE TITLE
Having a predictor only impact one of the dependents | Question

### ISSUE THREAD

**Issue by tushar-mbww** [paul-buerkner/brms#352]
Hi -
I'm fairly new to BRMS. Trying to figure out understand how I can modify the code (sample below) so that one of the predictors only impacts a specific dependent variable?

My apologies if this has already been answered before.

Thanks for the help.

fit <- brm(
           cbind(Aw , PI , Co)  ~ 
             0 + intercept +
              direct_buy + fb + gdn + lkdin + mob + bing + mob + brok + google + search + disp + `ol,`  
           family = "gaussian",
           data = Modelfile_final,
           prior = list_of_priors,
           init_r = 0.0001,
           control = list(adapt_delta = 0.95),
           chains = 5,
           warmup = 1000,
           iter = 3000
          )

**Comment by paul-buerkner** [comment]
See `vignette("brms_multivariate")`. And going forward, please ask your questions on brms-users (https://groups.google.com/forum/#!forum/brms-users) not on github.
