### ISSUE TITLE
Using s() or other smoothers in nonlinear formula?

### ISSUE THREAD

**Issue by natalieklein** [paul-buerkner/brms#354]
Hi, I just found `brms` after using `nlme` and `lme4` and am excited to try it. I could not find any examples about this particular use case and am not sure whether it's possible.

I want a nonlinear hierarchical model but with a smoothing term as part of the nonlinear formula.
For instance, I tried
```r
brmsfit = brm(bf(y~exp(a1)*s(time+a2),a1~(1|trial),a2~(1|trial),nl=TRUE),
              data=dfsub,family=gaussian(),
              prior=c(prior(normal(0,0.5),nlpar="a1"),prior(normal(0,10),nlpar="a2")))
```
which gives error 
```
SYNTAX ERROR, MESSAGE(S) FROM PARSER:

No matches for: 

  s(real)

Function s not found.
  error in 'model1e606ee6cbfd_file1e6058bd38f6' at line 50, column 49
  -------------------------------------------------
    48:     mu_a2[n] = mu_a2[n] + (r_2_a2_1[J_2[n]]) * Z_2_a2_1[n]; 
    49:     // compute non-linear predictor 
    50:     mu[n] = exp(mu_a1[n]) * s(C_1[n] + mu_a2[n]); 
                                                        ^
    51:   } 
  -------------------------------------------------

Error in stanc(model_code = paste(program, collapse = "\n"), model_name = model_cppname,  : 
  failed to parse Stan model 'file1e6058bd38f6' due to the above error.
```
So despite my lack of experience with Stan, it appears that `s()` is not getting passed through for the nonlinear formula (though I checked that something simpler like `brmsfit = brm(y~s(time),data=dfsub)` does work without an error). 

For more context about what I am trying to do: I have been able to do the following in `nlme` and `lme4`, where the nonlinear part was encapsulated in a user-defined formula `myfunc`:
```r
nlmefit = nlme(y~myfunc(time,a1,a2),fixed=a1+a2~1,random=list(trial=pdDiag(list(a1+a2~1))),
                         start=list(fixed=fe,random=reg[,2:3]),data=subdf)
```
In particular, `myfunc` returns a nonlinear function of fitted values from a smoothing function, where `a1` is an amplitude parameter and `a2` is a time shift parameter, so the random effects allow each `trial` to have a different amplitude and time shift parameter, but share a common shape from the `gam` fit. In particular, here is one way that I was doing this:
```r
g = bam(y~s(time,bs="ad",k=k,m=m,sp=sp),data=dfsub)
myfunc <- function(x,a1,a2){
         tvec = x+a2
        pr = predict(g,data.frame(list(time=tvec)),newdata.guaranteed=TRUE,block.size=200000)
        mv = max(abs(pr))
        value = pr/mv # Rescale so max value is 1
        return(exp(a1)*value)
}
```

It seems it might be possible to do this even better with `brms` but I'm not sure if it's supported or how I need to write the user-defined function to make it work. Thanks very much for any pointers!

**Comment by paul-buerkner** [comment]
If you can write myfunc in Stan language, you can write your model as

```R
brm(bf(y~exp(a1)*myfunc(time+a2),a1~(1|trial),a2~(1|trial),nl=TRUE),
    ..., stan_funs = <myfunc stancode>)
```

The `s()` function is desigend to be evaluated in the **mgcv** package, but when it appears inside a nonlinear formula, it is taken literally and passed directly to Stan, which as you saw doesn't work. 

You could do something like

```R
bf(y~exp(a1)*a2, a1~ (1|trial), a2~ s(time) + (1|trial), nl=TRUE)
```

but I think this is not what you have in mind.

**Comment by natalieklein** [comment]
Great, thanks for your help! I will look into that.
