### ISSUE TITLE
zero-adjusted Gamma likelihood model query

### ISSUE THREAD

**Issue by MilaniC** [paul-buerkner/brms#355]
This works in gamlss:

require(gamlss)
require(cplm)        ## for the data

## get some data ...
data(AutoClaim, package = "cplm")
df1 <- na.omit(AutoClaim)

## the nu parameter to separate zeros (hu in brms)

zaga <- gamlss(CLM_AMT ~ BLUEBOOK + NPOLICY, nu.formula = ~(CLM_FREQ5 + MVR_PTS + INCOME), data = df1, family = "ZAGA")

summary(zaga)

But does not work in brms for the equivalent hurdle_gamma() likelihood using default priors (but note that hurdle_lognormal() does work):

control=list(adapt_delta=0.95,max_treedepth=12)
m1<-brm(bf(CLM_AMT ~ BLUEBOOK + NPOLICY, hu ~ CLM_FREQ5 + MVR_PTS + INCOME), data = df1, family = hurdle_gamma(), control=control)
summary(m1)

Model fails to run and produces these sorts of errors that suggest that the hurdle_gamma parameterisation might not be separating the zeros from the > 0 data:

#############

Rejecting initial value:
  Error evaluating the log probability at the initial value.
Exception: Exception: gamma_lpdf: Inverse scale parameter is 0, but must be > 0!  (in 'model37446beea6a_file3747c1ad985' at line 35)
  (in 'model37446beea6a_file3747c1ad985' at line 87)

Rejecting initial value:
  Error evaluating the log probability at the initial value.
Exception: Exception: gamma_lpdf: Inverse scale parameter is inf, but must be finite!  (in 'model37446beea6a_file3747c1ad985' at line 35)
  (in 'model37446beea6a_file3747c1ad985' at line 87)

Initialization between (-2, 2) failed after 100 attempts. 

#############

Appreciate advice on this apparent issue with fitting a logit-gamma hurdle type model using brms.

**Comment by paul-buerkner** [comment]
The (hurdle) gamma mode sometimes has problems with initialization. For other families I recommend setting `inits = 0` but I believe this fails for gamma models. Still worth a try though. You could also restrict the initialization area to a more narrow interval, for instance via `init_r = 0.3` (see `?rstan::stan`).

It could also be the problem with the scale of the covariates being too large. Maybe scale your covariates so that they are roughly of order 1.

**Comment by paul-buerkner** [comment]
Going forward, please ask brms related questions on brms-users (https://groups.google.com/forum/#!forum/brms-users), because it is easier for other users to find them there than in closed github issues. Bugs / feature requests should of course be posted on github.

**Comment by paul-buerkner** [comment]
Did it work and if yes, can I close this issue?

**Comment by MilaniC** [comment]
No it did not work using reset of init-r.

Centre and scaling of a problematic covariate did not help either although that covariate was the problem.

Using s(Income) was the solution in this case.

So yes this issue is closed.

Many thanks

**Comment by paul-buerkner** [comment]
Great, thank you! :-)
