### ISSUE TITLE
Extracting transformed parameter estimates

### ISSUE THREAD

**Issue by marivascruz** [paul-buerkner/brms#356]
Hi Paul, 

Thanks for brms. It may be a silly question, but it was unclear to me how to extract transformed parameter estimates. 

I'm particularly interested in extracting theta parameters from brms using "Eight Schools" example here: 
https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started

Manuel

**Comment by paul-buerkner** [comment]
Please ask such questions on brms-users (https://groups.google.com/forum/#!forum/brms-users) and please be more specific with your question.
