### ISSUE TITLE
Variable Prior parameters

### ISSUE THREAD

**Issue by dmenne** [paul-buerkner/brms#357]
I am trying to make some progress in using brms with precompiled models - see https://github.com/dmenne/brmspack for a first stab.

Prior parameters currently are fixed values in the model, so a recompile is when priors are changed. I tried

```
prior_m_intercept = 5500
prior(normal(prior_m_intercept, 1000), nlpar = "m", coef = "Intercept")

```
but this gives:

`variable "prior_m_intercept" does not exist.`

Any ideas how to parameterize these without recompiling?

**Comment by paul-buerkner** [comment]
`normal(prior_m_intercept, 1000)` is evaluated literally using non-standard evaluation within `prior()`. You have to write `normal(5500, 1000)`.

**Comment by dmenne** [comment]
I know, that's what I am using anyway. Just some musing to get around this without the infinite compile times. It's not a problem for me, but for pre-packed tools compiling is no option.

**Comment by paul-buerkner** [comment]
Ahh I see what you mean. This relates to issue #219. I have already an idea how to get this working. Maybe I can get it done soon.

**Comment by dmenne** [comment]
I had seen that thread, but not read it to the end.

**Comment by paul-buerkner** [comment]
Try out function `stan_var` in the latest github version of brms, which should be able to achieve what you have in mind.

**Comment by dmenne** [comment]
Faster than neutrinos....
Your example in the docs works, but my version fails.  

User error or problem with no-linear models?

```
library(brms)

data("usz_13c_d", package = "breathtestcore") # on CRAN
data = usz_13c_d[usz_13c_d$patient_id < "sub_18",]

form =
  bf(pdr ~ m*beta/tempt*(1-exp(-minute / tempt))^(beta-1)*exp(-minute/tempt),
     m + tempt + beta  ~ group + (1|ID1|patient_id), nl = TRUE)

# Note: the model requires more priors to run successfully,
# but here we are only focussing on compilation, so these are 
# omitted.
prior = c(
  prior(normal(prior_m_intercept, 1000), nlpar = "m", coef = "Intercept")
)

stanvars = stan_var(5500.0, name = "prior_m_intercept")
code = make_stancode(form, prior = prior, data = data, family = gaussian(),
                     stanvars = stanvars)

## variable "prior_m_intercept" does not exist.
# Cross-check: the example in stan_var(brms) works ok
```

**Comment by paul-buerkner** [comment]
The argument is called `stan_vars` not `stanvars` to be consistent with the naming conventions of `brms`.

**Comment by dmenne** [comment]
Sorry..

**Comment by paul-buerkner** [comment]
All good. Please keep me updated on how handling precompiled brms models works out. :-)

**Comment by dmenne** [comment]
Trying to recompile an model that previously worked and failed with the CRAN version, I noted that contrary to what you said above it is again stanvars, not stan_vars. Typo or the way to go?

**Comment by paul-buerkner** [comment]
Sorry for the confusion. I realized I was even confusing myself with the names and so I decided to name everything `stanvars` including the argument in `brm`.

**Comment by dmenne** [comment]
Happy confusing...
