### ISSUE TITLE
Dynamic prior names for precompiled models

### ISSUE THREAD

**Issue by dmenne** [paul-buerkner/brms#358]
Assume I have three treatment groups, PL, NU and OS, with contrast priors required as in the model below. Normally, it is a nice feature that I can pass priors by group name (groupNU etc), because it is safer than passing by index.
However, assume a user has two groups PL and Anti only, model otherwise the same. While I can determine the coef names for the priors dynamically, the model will be recompiled anyway. With ragged indexing I use in handmade Stan, the groups can be arbitrary assuming that non-intercept priors are within the same range -- they usually are.

```
form =
  bf(pdr ~ m*beta/tempt*(1-exp(-minute / tempt))^(beta-1)*exp(-minute/tempt),
     m + tempt + beta  ~ group + (1|ID1|patient_id), nl = TRUE)


prior = c(
  prior(normal(prior_m_intercept, 1000), nlpar = "m", coef = "Intercept"),
  prior(normal(0, 300), nlpar = "m", coef = "groupNU"),
  prior(normal(0, 300), nlpar = "m", coef = "groupOS"),
  

```

**Comment by paul-buerkner** [comment]
Can you give me an example of how your desired Stan code would look like and how you imagine a possible interface for that?

**Comment by dmenne** [comment]
An example is here:

https://github.com/dmenne/breathteststan/blob/master/exec/breath_test_group_1.stan

This model fits the data badly because it is too simple, maybe it is even incorrect, but technically it works. Here is the calling function.

https://github.com/dmenne/breathteststan/blob/master/R/stan_group_fit.R

which works for any grouping by one treatment. I left it in an incomplete state because I wanted to replace it by something more sophisticated from brms as shown above, but got stuck.  See also 

https://apps.menne-biomed.de/breathtestshiny/ 

for an app that is used in clinical context.

**Comment by paul-buerkner** [comment]
Thanks! It may be obvious, but I am still unsure what you need from the brms interface to support and how the generated Stan code should look like as compared to how it currently looks. 

For instance, it would be nice if you showed me some Stan code generated by brms, which just differes in the way you want indices to be handled.

**Comment by paul-buerkner** [comment]
Ahh now I get what you ment. Indeed you can do this, because the length and names of the fixed effects vector `b` are not hard coded in Stan and if you supply the same prior to all coefficients, it does not matter if there are more or other predictors.
