### ISSUE TITLE
Certain variable names in brms formulas throw errors with s() terms

### ISSUE THREAD

**Issue by ecologics** [paul-buerkner/brms#359]
I have come across two words that when used as part of a variable name in a `brms` formula throw confusing errors. These words I have hit up against are: `time` and `treatment`.

```
df <- data.frame(
  timeDayOfYear = 1:365,
  time_doy = 1:365,
  julianTime = 1:365,
  julianDay = 1:365,
  treatment = 1:365,
  tmt = 1:365)
df$y <- sin(timeDayOfYear)

fails <- brm(y ~ s(timeDayOfYear), data=df)
fails <- brm(y ~ s(time_doy), data=df)
fails <- brm(y ~ s(julianTime), data=df)
fails <- brm(y ~ s(treatment), data=df)

works <- brm(y ~ s(julianDay), data=df)
works <- brm(y ~ s(tmt), data=df)
```

There error that is thrown is:
```
Error: Cannot use multiple special terms within one term.
Occured for: 's(timeDayOfYear)'
```

One way forward might be to improve the error message here and advise users to adopt safer variable names.

**Comment by paul-buerkner** [comment]
This is a bug in brms 2.1 which has already been fixed on github.

**Comment by ecologics** [comment]
Oops running brms 2.1.2.  Must stay up to date.  Please close.

**Comment by paul-buerkner** [comment]
All good. You couldn't know that. You can also close issues yourself if you like ;-)

**Comment by ecologics** [comment]
Never closed one before. Now I know :)
