### ISSUE TITLE
Wide CI for prediction of zero-inflated beta family

### ISSUE THREAD

**Issue by alireza202** [paul-buerkner/brms#36]
Here's my brm call:

    brm(formula = d ~ p + (1 || item), 
        data = training,
        family = "zero_inflated_beta",
        chains = 2,
        cluster = 2,
        iter = 1000, 
        warmup = 300) -> zib_fit

The model runs with no problems, and it seems like it is converged (Rhat = 1, the two chains mix well, and posterior distribution of parameters look similar and normal-like). Here's the summary of zib_fit:

    Family: zero_inflated_beta (logit) 
    Formula: d ~ p + (1 || item) 
       Data: training (Number of observations: 8971) 
    Samples: 2 chains, each with iter = 1000; warmup = 300; thin = 1; 
             total post-warmup samples = 1400
       WAIC: Not computed

    Random Effects: 
    ~item (Number of levels: 1330) 
                  Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
    sd(Intercept)     1.43      0.07     1.29     1.58        195    1

    Fixed Effects: 
              Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
    Intercept    -1.11      0.11    -1.32    -0.89        419 1.01
    p             5.54      0.22     5.12     5.96        315 1.00

    Family Specific Parameters: 
        Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
    phi     1.64      0.07     1.51      1.8        848    1

    Samples were drawn using sampling(NUTS). For each parameter, Eff.Sample 
    is a crude measure of effective sample size, and Rhat is the potential 
    scale reduction factor on split chains (at convergence, Rhat = 1).

However, when I use the model to predict for new data:

    testing_pred = predict(object = zib_fit, newdata = testing, probs = c(0.05, 0.95))

the predictions look like this

	Estimate	Est.Error	5%ile	95%ile
	1	0.03223522	0.17344704	0.00000000	0.00000000
	2	0.2166267	0.3436864	0.0000000	0.9736827
	3	0.09275476	0.27608277	0.00000000	0.98260804
	4	0.08670104	0.26223131	0.00000000	0.91945058
	5	0.09281734	0.27890228	0.00000000	0.98422182
	6	0.2148495	0.3208814	0.0000000	0.9330208

Prediction interval is most of the times as large as the range of response (and sometimes zero)! 
By the way, what is Est.Error?

Two more questions: 

1. What would be appropriate priors for zero-inflated beta model?
2. Where can I find the estimate of the probability of zero in this model?

**Comment by paul-buerkner** [comment]
Keep in mind that zero-inflated families have two processes which are both modeled in the same formula. If you specify a formula as for an ordinary family, you use the same parameters across both processes, which will lead to pointless results.

I suggest that you write `d ~ 0 + trait * p + (0 + trait || item)` instead (or `d ~ 0 + trait * p + (0 + trait | item)` if you want to estimate the random effects correlation). Variable `trait` is an internally generated factor with 2 levels, one for the beta part of the model and for the zero part. For more details take a look at the Details section of help(brm), specifically the formula syntax part.

Est.Error is the standard deviation.

I am not an expert in zero-inflated beta models and suitable priors obviously depend on your data, research question, prior knowledge, etc. Accordingly, I am hesitating to give any particular advice here. If you don't want to use improper flat priors on fixed effects, you may go for something like `set_prior("normal(0,10)", class = "b")`, which will likely be relatively weakly informative for fixed effects of beta models when using the logit link.

From the summary output, you won't see the predicted number of zeros. To get to it, you should use
```r
testing_pred = predict(object = zib_fit, newdata = testing, summary = FALSE)
```
This will be a S x N matrix, where S is the number of samples (i.e. predictions made for every observation; 1400 in your case) and N is the number of observations. Accordingly, you can get the number of zeros by counting them for each row of `testing_pred`.

**Comment by alireza202** [comment]
Many thanks! It solved my problem. :)

**Comment by paul-buerkner** [comment]
Great! :-)

**Comment by alireza202** [comment]
I'm trying to understand the 'trait' variable better. When I use `d ~ 0 + trait * p + (0 + trait || item)`, it generates 4 fixed-effect variables:

`traitd, traithu_d, p, traithu_d:p`

My understanding is that `traitd` and `traithu_d` are fixed-effect intercepts related to the beta and zero-inflated parts of the model, respectively. I assume that `p` and `traithu_d:p` follow the same logic, though I'm not sure why it's not `traitd:p` instead of `p`.

Is my understanding correct, or it's totally off? :)

**Comment by paul-buerkner** [comment]
Your understanding with regard to the intercepts is correct. Intuitively (also for me) we should have the same logic for `p`, but this is not excactly what happens. In your case the fixed effect of `p` is the effect of `p` on the main part of the model, whereas `traithu_d:p` is the *difference* between the effect of `p` on the main part and the effect of `p` on the zero-inflated part. This is the way the `model.matrix` function of the `stats` package works and I am not sure whether I can change this default behavior without causing trouble for some models.

What you can do, however, is using the variables `main` and `spec` instead of `trait`, to achieve what you want. `main` is the 'intercept' of the main part and `spec` is the 'intercept' of the zero-inflated part and we can use those variables also in interactions. For your model, we could write `d ~ 0 + main + spec + (main + spec) * p` for the fixed effects part.  Some more details are given in the Details section of help(brm).
