### ISSUE TITLE
brms for multi-level model with more than 2 levels 

### ISSUE THREAD

**Issue by Lawrence-Liu** [paul-buerkner/brms#361]
Hey, 

I am wondering if brms supports multi-level model with more than 2 levels. I didn't see an example with than 2 levels in any tutorials and documentation. 

An example would be investigating the relationship between GPA (y variable) and attendance rate (x variable). Three levels are involved in this example: student, class, and school.  Can we get the group effects of class and school?

**Comment by paul-buerkner** [comment]
Any number of levels are supported. In the future, please ask such questions on brms-users (https://groups.google.com/forum/#!forum/brms-users).

**Comment by Lawrence-Liu** [comment]
Thanks and will do!
