### ISSUE TITLE
Improvements for hypothesis()

### ISSUE THREAD

**Issue by mvuorre** [paul-buerkner/brms#362]
Two minor suggestions for the `hypothesis()` method:

## 1. Allow named hypotheses

I think it would make it easier to work with brmshypothesis objects if we could input named hypotheses. That, is perhaps we could input named vectors such as

```
hs <- c("slope" = "b_condition = 0", "constant" = "Intercept = 0")
```

to `hh <- hypothesis(fit, hypothesis = hs)`. The rownames* of `hh$hypothesis` would then be `slope` and `constant`, instead `b_condition` and `Intercept`.

Currently, when "testing" a whole bunch of hypotheses simultaneously, it's difficult to read the results when the hypotheses are complex transforms of parameters. This suggestion would make the results much more readable in such cases.

\* Perhaps the rownames could be explicitly named, i.e. as column `Hypothesis`.

## 2. Identify groups for group-level hypotheses in output

This one is related to #327. When "testing" hypotheses for multiple groups of a multilevel model, it would be neat if the output of `hypothesis(..., group = "id", scope = "coef")` had an extra column that identified each `id`.

**Comment by paul-buerkner** [comment]
Both ideas sound very reasonable to me. Let me try to get them implemented in the next release.

**Comment by mvuorre** [comment]
I actually did not even bother checking whether (1.) works with current brms version (dumb!) It turns out that you can already use named hypotheses if testing a hypothesis at the population level. Example:

```
> hyps <- c(
+     "Name" = "-((Intercept) / (isi)) = 0",
+     "-((Intercept) / (isi)) = 0"
+ )
> hypothesis(fit, hyps)
Hypothesis Tests for class b:
                         Estimate Est.Error l-95% CI u-95% CI Evid.Ratio Star
Name                         1.88      0.25     1.41     2.38         NA    *
(-((Intercept)/(i... = 0     1.88      0.25     1.41     2.38         NA    *
---
'*': The expected value under the hypothesis lies outside the 95% CI.
```

So that was dumb on my part--sorry. However, named hypotheses don't work if testing group-specific hypotheses:

```
> hyps <- c(
+     "Name" = "-((Intercept) / (isi)) = 0",
+     "-((Intercept) / (isi)) = 0"
+ )
> hypothesis(fit, hyps, group = "subject", scope = "coef")
Hypothesis Tests for class :
                         Estimate Est.Error l-95% CI u-95% CI Evid.Ratio Star
(-((Intercept)/(i...001]     2.93      0.20     2.55     3.34         NA    *
[Omit bunch of rows of output]
(-((Intercept)/(i...01]1     2.93      0.20     2.55     3.34         NA    *
```

**Comment by paul-buerkner** [comment]
Interesting, I didn't even know that naming already worked this way... ;-)

I agree with your suggestions. Basically, I will move the rownames to its own column, allow naming of hypothesis and add a subject column if applicable.

**Comment by paul-buerkner** [comment]
Could you try it out in the new dev version of brms?

**Comment by mvuorre** [comment]
Thank you so much, it works as expected:

```
> hyp <- c("Ha" = "Intercept = 0",
+          "Hb" = "-((Intercept) / (isi)) = 0")
> hypothesis(fit, hyp)
Hypothesis Tests for class b:
  Hypothesis Estimate Est.Error l-95% CI u-95% CI Evid.Ratio star
1         Ha     1.27      0.21     0.87     1.67         NA    *
2         Hb     1.88      0.25     1.41     2.38         NA    *
---
'*': The expected value under the hypothesis lies outside the 95% CI.
> hypothesis(fit, hyp, group = "subject", scope = "coef")
Hypothesis Tests for class :
   Group Hypothesis Estimate Est.Error l-95% CI u-95% CI Evid.Ratio star
1   0001         Ha     2.67      0.30     2.10     3.30         NA    *
2   0002         Ha     2.86      0.32     2.25     3.51         NA    *
[...]
```

**Comment by paul-buerkner** [comment]
Nice! I assume you are ok with me closing this issue now.
