### ISSUE TITLE
Enable future in brm_multiple

### ISSUE THREAD

**Issue by rubenarslan** [paul-buerkner/brms#364]
Would be cool to run the chains for all imputations (except the first) in parallel. I can try my hand at a PR if you want.

**Comment by paul-buerkner** [comment]
I agree and it would be awesome if you could submit a PR for this if that's possible! :-)

**Comment by gbiele** [comment]
Just seeing this by chance, here a quick comment:
In my experience, chains from different imputed data sets can easily fail to converge. This is not necessarily surprising, especially if the uncertainty for some of the imputed variables is high.
I have dealt with this by (I) running 3 chains per imputed data set and to (II) check convergence for each imputed data set before (III) concatenating all chains over all imputed data sets to obtain the posterior over multiple imputed data sets.

**Comment by paul-buerkner** [comment]
You are right, although I wouldn't call it "fail to converge", but rather "Stan (incorrectly) indicates convergence failues" in this case.  What you describe is exactly what happens in brms, already. See `?brm_multiple`

**Comment by gbiele** [comment]
Aah, sorry for redundant comment! I had overlooked that this issue was about parallelization.

**Comment by rubenarslan** [comment]
One quick question: is there any provision in brms or rstan for writing chain progress (iteration) to files, so that you can see progress for models where you don't use `cores` (PSOCK?) parallelisation, but future? `diagnostic_file` is a different output (but works), setting `open_progress` to TRUE doesn't seem to work (in my temp folder, no progress file appears to be created).

**Comment by paul-buerkner** [comment]
rstan allows to print the progress in Rstudio's Viewer pane so I assume it allows to write progress somehow, but I don't know if the same solution works with future.

**Comment by rubenarslan** [comment]
Ok, when I don't use future, it errors out with:
>  you cannot specify 'open_progress = TRUE' when using RStudio

If I use `cores > 1` `rstan::stan` creates a file called something like `file4f1e44506bfa_StanProgress.txt`, but it contains only
> Click the Refresh button to see progress of the chains

when using brms, and the file doesn't change thereafter.

I thought I might be able to use `open_progress` on the cluster with future, I think it's file-based, but I can't seem to create a file with `open_progress`. Maybe the way you call stan makes all parallel chains try to open the same file handle or something?

**Comment by paul-buerkner** [comment]
Not entirely sure to be honest. @bgoodri has implemented this part in **rstan** I think. Maybe he knows if / how this can be achieved?

**Comment by lukeholman** [comment]
Hey, just adding a note to say that I logged on to this repo to post the exact same suggestion! Thanks again to everyone working on this lovely package, it's transforming my research.

**Comment by paul-buerkner** [comment]
Fitting imputed models in parallel using **future** is now possible in the dev version of brms.
