### ISSUE TITLE
Is there a way to get predicted classes instead of probabilities per class for the categorical models?

### ISSUE THREAD

**Issue by robustbayesian** [paul-buerkner/brms#366]
For a binary logistic model I get the predicted classes simply by rounding, ie:

```
predicted_data <- as.data.frame(predict(logit.brm, scale="response"))
round(predicted_data$Estimate)
```
I can even feed it to the confusionMatrix from the caret package like so `confusionMatrix(round(predicted_data$Estimate), predicted_data$Estimate)`

For multinomial / categorical models in brms this doesn't work, since for 3+ response levels the probability of any individual response may not be above .5.

What I'd really like is something comparable to nnet's predict for its multinom function. For this, all I have to do is type predict(multinom.fit, dataframe). For instance, let's say I am using the iris dataset. After fitting the model, predict(iris.fit , iris) returns a vector of the classifications:

> [1] setosa     setosa     setosa     setosa     setosa     setosa     setosa     setosa     setosa     setosa    
 [21] setosa     setosa     setosa     setosa     setosa     setosa     setosa     setosa     setosa     setosa    
 [51] virginica  virginica  virginica  versicolor virginica  versicolor virginica  versicolor virginica  versicolor
 [61] versicolor versicolor versicolor versicolor versicolor virginica  versicolor versicolor versicolor 

Is there a way to get brms to do this? I've been searching around the net and playing around with the predict and fitted functions but I can't seem to get this kind of output.

**Comment by paul-buerkner** [comment]
I have stopped answering questions on github, as in my experience people rarely search in closed issues for solutions to their problems. Thus, plase ask this question again on brms-users (https://groups.google.com/forum/#!forum/brms-users)
