### ISSUE TITLE
Install error one one of 3 machines

### ISSUE THREAD

**Issue by harrelfe** [paul-buerkner/brms#367]
I successfully installed brms 2.1.0 on two of my machines today.  On the third machine, which differs only slightly in which other R packages are installed), I get the error below.  Any help appreciated.

```
trying URL 'http://cran.rstudio.com/src/contrib/brms_2.1.0.tar.gz'
Content type 'application/x-gzip' length 4582854 bytes (4.4 MB)
==================================================
downloaded 4.4 MB

* installing *source* package ‘brms’ ...
** package ‘brms’ successfully unpacked and MD5 sums checked
** R
Warning: namespace ‘brms’ is not available and has been replaced
by .GlobalEnv when processing object ‘brmsfit_example1’
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘threejs’
ERROR: lazy loading failed for package ‘brms’

```

**Comment by paul-buerkner** [comment]
Very strange. Haven't seen this error before. Try uninstall brms (and possibly also rstan) completey, restart R and install them again.

**Comment by harrelfe** [comment]
Uninstalled rstan, reinstalled it, then tried to install brms and got same error as before.  I do have the following objects in my global environment but I don't think these overlap with anything: `bdNew bdSet clean_figures installGithubPac installPac latexRef latexSec spar stanSet updatePac`.  I do not run any of those on startup.

**Comment by paul-buerkner** [comment]
Upon a closer look at the error above, R seems to complain about `threejs`. Could this be the cause of the problem?

**Comment by harrelfe** [comment]
Since `brms` imports `shinystan` (whether I want to use `shiny` or not) and `shinystan` imports `threejs` what should I do about it?  I tried uninstalling `shinystan` and `threejs` and when trying to re-install `shinystan` I got this:

**Comment by paul-buerkner** [comment]
I have literally no idea what the latest error means, but from what I see, the problem with installing brms seems to be ultimately caused by a problem in threejs or even deeper. Maybe ask the package maintainer of threejs about it?

**Comment by harrelfe** [comment]
Before I do that (which is logical as a next step) I'll wipe my user-install libraries clean and reinstall all the packages I think I need and see if the error persists.

**Comment by paul-buerkner** [comment]
Agreed. That makes sense.

**Comment by harrelfe** [comment]
That did the trick.  The problem might have been a stringent `Makevars` file in `~/.R` that prevented one of the needed packages from updating from CRAN for linux.  Thanks you all your responses.

**Comment by DanChaltiel** [comment]
I have the same error, and have no clue how to deal with it : 

```
> install.packages("emmeans")
Installing package into ‘C:/Users/d.chaltiel/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
also installing the dependency ‘brms’


  There is a binary version available but the source version is later:
     binary source needs_compilation
brms  2.2.0  2.3.0             FALSE

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/emmeans_1.2.zip'
Content type 'application/zip' length 1007856 bytes (984 KB)
downloaded 984 KB

package ‘emmeans’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\d.chaltiel\AppData\Local\Temp\RtmpmuCs9w\downloaded_packages
installing the source package ‘brms’

trying URL 'https://cran.rstudio.com/src/contrib/brms_2.3.0.tar.gz'
Content type 'application/x-gzip' length 5015129 bytes (4.8 MB)
downloaded 4.8 MB

* installing *source* package 'brms' ...
** package 'brms' correctement décompressé et sommes MD5 vérifiées
** R
Warning: namespace 'brms' is not available and has been replaced
by .GlobalEnv when processing object 'brmsfit_example1'
Warning: namespace 'rstan' is not available and has been replaced
by .GlobalEnv when processing object 'brmsfit_example1'
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Warning: package 'Rcpp' was built under R version 3.4.4
Warning: package 'ggplot2' was built under R version 3.4.4
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'StanHeaders'
ERROR: lazy loading failed for package 'brms'
* removing 'C:/Users/d.chaltiel/Documents/R/win-library/3.4/brms'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-34~1.2/bin/x64/R" CMD INSTALL -l "C:\Users\d.chaltiel\Documents\R\win-library\3.4" C:\Users\D4FAA~1.CHA\AppData\Local\Temp\RtmpmuCs9w/downloaded_packages/brms_2.3.0.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘brms’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\d.chaltiel\AppData\Local\Temp\RtmpmuCs9w\downloaded_packages’
```

I tried to wipe my use-install library (using [this gist](https://gist.github.com/Mikuana/51ed2e5f1ab04783884e6af94ecb7262)), but it had no effect.

What do you think I should do ?

**Comment by paul-buerkner** [comment]
It seems that the package `stanHeaders` is missing on your system for some reason. Installing it might resolve the problem.

**Comment by cblaix** [comment]
Dear Paul,

I have come across a similar error when trying to install brms from github.

 ```
devtools::install_github("paul-buerkner/brms")
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/purrr_0.3.0.zip'
Content type 'application/zip' length 414141 bytes (404 KB)
downloaded 404 KB

package ‘purrr’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Utilisateur\AppData\Local\Temp\RtmpoJJwMC\downloaded_packages
√  checking for file 'C:\Users\Utilisateur\AppData\Local\Temp\RtmpoJJwMC\remotesb848ca20f4\paul-buerkner-brms-966947e/DESCRIPTION' (446ms)
-  preparing 'brms': (4.4s)
√  checking DESCRIPTION meta-information ...
-  checking for LF line-endings in source and make files and shell scripts (1.1s)
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'brms_2.7.2.tar.gz'
   
* installing *source* package 'brms' ...
** R
Error : (converted from warning) namespace 'brms' is not available and has been replaced
by .GlobalEnv when processing object 'brmsfit_example1'
ERROR: unable to build sysdata DB for package 'brms'
* removing 'C:/Users/Utilisateur/Documents/R/win-library/3.5/brms'
In R CMD INSTALL
```
Any ideas on what might be causing the problem?

**Comment by paul-buerkner** [comment]
Honestly, I have no idea and would suspect this problem to actually be unrelated to brms.

**Comment by cblaix** [comment]
Installation worked fine from CRAN. Unfortunately, I am interested in using a Dirichlet distribution. Do you know when the CRAN version will be updated?

**Comment by paul-buerkner** [comment]
I am waiting for loo and rstanarm to be released at the same time. Hopefully, this will have soon.

**Comment by brianhuey** [comment]
I just wanted to document my solution to the error @harrelfe was experiencing. I think he's correct in that it results from a restriction on dependencies being installed. Attempted to upgrade to brms 2.12.0:
```
> install_github('paul-buerkner/brms', ref='f7ae06b36eb547d47f6094192774ba37b04bc3b5')
Downloading GitHub repo paul-buerkner/brms@f7ae06b36eb547d47f6094192774ba37b04bc3b5
✔  checking for file ‘/tmp/RtmpaYDEAn/remotes1137387487e/paul-buerkner-brms-f7ae06b/DESCRIPTION’ ...
─  preparing ‘brms’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘brms_2.12.0.tar.gz’
   
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
* installing *source* package ‘brms’ ...
** using staged installation
** R
Error : (converted from warning) namespace ‘brms’ is not available and has been replaced
by .GlobalEnv when processing object ‘brmsfit_example1’
ERROR: unable to build sysdata DB for package ‘brms’
* removing ‘/usr/local/lib/R/site-library/brms’
Error: Failed to install 'brms' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmpaYDEAn/file11369a42b03/brms_2.12.0.tar.gz’ had non-zero exit status`
```

Installing the latest `rstan` and `loo` via `install_github()` first did the trick.

**Comment by paul-buerkner** [comment]
Thank you for this information. Good to know!

**Comment by gbiele** [comment]
I just had the same problem when installing Rstan from github and following solution worked form me:

1) Open the list of dependencies here: https://github.com/paul-buerkner/brms/blob/master/DESCRIPTION
2) **In R load each packages with a minimum version number in the dependencies list and check if the installed version is sufficiently recent, if not install the correct version.**

In my case, rstantools was the problem. The current github version of brsm required rstantools 2.1.0, CRAN has only 2.0.0, and installing rstantools 2.1.0 from github solved the issue for me.

**Comment by Steviey** [comment]
+1
