### ISSUE TITLE
Sequencing of inits

### ISSUE THREAD

**Issue by bachlaw** [paul-buerkner/brms#369]
Paul,

For generalized hierarchical models, I've found that while population parameters can span the gamut of the  link function, the group parameters are often close to zero, thanks to shrinkage.  In other models, the population parameters are also close to zero, particularly when scaled, with only the population intercepts spanning the link function.  This suggests that some speed gains may be achievable by specifying one range of inits (perhaps even previously derived values) for population parameters and/or intercepts and then a series of zeroes or near-zeroes for the remaining populiation and/or group parameters. 

Is there a heuristic one can use to approximate when the population parameters stop in the init string and the group parameters begin, e.g., take the number of the population parameters from `get_prior` until you get to the group parameters and just go with zeroes thereafter? I recognize the answer for brms in this respect may be the same as Stan itself, but did not want to assume. Thanks.

**Comment by paul-buerkner** [comment]
Indeed, the answer is the same as for Stan, just that you have to check brms' Stan code for the correct parameters names, which are not the ones that come up in the output, because brms renames the parameters after model fitting.

**Comment by paul-buerkner** [comment]
Since there is nothing to be done from the brms side, I am closing this issue now.
