### ISSUE TITLE
Add support for non-linear mixed models

### ISSUE THREAD

**Issue by paul-buerkner** [paul-buerkner/brms#37]
As brms generates Stan code on the fly, it should be possible to translate non-linear model formulae into Stan code, given that Stan knows the occuring functions (such as `exp` or `log`; possibly under another name) or that I have defined these functions in the 'functions' block of the Stan code. Definitely more of a long term goal, though.

**Comment by paul-buerkner** [comment]
Non-linear mixed models are more or less working now. Still, there are quite a few things to do:
- [ ] document new functionality
- [ ] add more unit tests
- [ ] possibly improve efficiency of the Stan code
- [ ] improve comments in the Stan code

Also, I am almost sure I will find some more bugs in the process.

**Comment by EmmanuelCharpentier** [comment]
Thank you for this very interesting and very handy package. The "nonlinear" option is a very big selling point !

A vignette, including several examples and at least one detailed example, is indeed urgently needed : the current documentation makes it hard for a newcomer to figure out what should go in the "nonlinear" part of the model, and how to specify a model with both linear and nonlinear parts.

**Comment by paul-buerkner** [comment]
I agree. The vignette should be ready within the next few weeks.

**Comment by aforren1** [comment]
If it helps in the meanwhile, I've worked a few simple examples using the `Orange` dataset at http://rpubs.com/aforren1/orange-nonlinear.

**Comment by paul-buerkner** [comment]
@aforren1 This is great, thanks! :-)

**Comment by paul-buerkner** [comment]
All of the main features of non-linear models have been implemented in `brms` version 0.8 and 0.9. The remaining stuff has been moved to other issues (see #91 and #90). Accordingly, I think this issue can be closed now.
