### ISSUE TITLE
Cholmod error with WAIC()

### ISSUE THREAD

**Issue by ivyjansen** [paul-buerkner/brms#374]
When calling WAIC() for a gaussian model I received the same error as in issue #154 :

> Error in .local(x, y, ...) : Cholmod error 'X and/or Y have wrong dimensions' at file ../MatrixOps/cholmod_sdmult.c, line 90

The model specification was (data on [Gdrive](https://drive.google.com/open?id=1Ml9kSnEYfgaOu7uByuwWg9C7_6vZQ4i-)):

```
m0 <- brm(Y ~ 1 + (0 + x1 || id) + (0 + x2 || id) + (1 | z1) + (1 | z2),
          data = data, algorithm = "meanfield", cores = 4)
```

`summary(m0)` gave reasonable results
`summary(m0, waic = TRUE)`, `WAIC(m0)`,... all give the above error

Fitting the model with the sampling algorithm instead of "meanfield" does not solve the problem.

Any idea what might be the reason?

**Comment by paul-buerkner** [comment]
have you tried it with the latest GitHub version of brms?

ivyjansen <notifications@github.com> schrieb am Fr., 9. März 2018, 14:45:

**Comment by ivyjansen** [comment]
Apparently I'm still working with an older version (‘brms’ version 2.0.1).
I'll try to update first.

**Comment by ivyjansen** [comment]
Updating to the latest version on Github (brms 2.1.8) does not solve the problem.

**Comment by paul-buerkner** [comment]
Could you try it again with the latest github version?

**Comment by ivyjansen** [comment]
No error message anymore, now it works.
Sorry for the late reply and thanks for the quick solution !
