### ISSUE TITLE
Multivariate w/weibull - syntax error

### ISSUE THREAD

**Issue by philj1s** [paul-buerkner/brms#375]
Firstly this is just amazing work.  Really having fun exploring models I've never even attempted before.

I'm trying to develop a joint model of a right-censored survival time and a dichotomous outcome.  First stab:

fit <- brm(bf(y1|cens(censored) ~ x, family=weibull) +
             bf(y2 ~ x, family=bernoulli),
           data=mydata)

yields the following:

SYNTAX ERROR, MESSAGE(S) FROM PARSER:
variable "shape" does not exist.
  error in 'model19b07b431f3d_file19b02c7b168d' at line 44, column 46
  -------------------------------------------------
    42:   vector[N] mu_y2 = Xc_y2 * b_y2 + temp_y2_Intercept; 
    43:   for (n in 1:N) { 
    44:     mu_y1[n] = exp((mu_y1[n]) / shape); 
                                                     ^
    45:   } 
  -------------------------------------------------

Is this expected?  The code runs without a hitch if I pick a survival distribution without a shape parameter (e.g. lognormal).

Thanks!

**Comment by paul-buerkner** [comment]
Thanks! It should be fixed in the github version now. :-)
