### ISSUE TITLE
Marginal_effects and ask = FALSE (minor, workaround easy)

### ISSUE THREAD

**Issue by dmenne** [paul-buerkner/brms#376]
I have a case where implicit plotting with

`marginal_effects(fit1, conditions = conds, re_formula = NULL, ask = FALSE)`

results in "Hit <return>" to see next plot (once, for 2*3 pages of output). Looks like `ask` is not always propagated. Easy workaround:

`plot(marginal_effects(fit1, conditions = conds, re_formula = NULL), ask = FALSE)`

In case an example fit showing the effect is needed, I can sent one by PM or upload to server.

**Comment by paul-buerkner** [comment]
`ask` is not an argument of `marginal_effects` itself but of the associated `plot` method. Accordingly, your solution is not a workaround, but the only intended way of doing it.

**Comment by dmenne** [comment]
Ok, I see, ... is only passed to predict and fitted
