### ISSUE TITLE
Beta binomial error model/family (not beta distribution as hierarchical prior)

### ISSUE THREAD

**Issue by gbiele** [paul-buerkner/brms#377]
I am proposing to add the beta-binomial distribution as a “family” to brms.

I am aware of the [closed issue](https://github.com/paul-buerkner/brms/issues/344) on the beta binomial regression. Here I am addressing a related but not identical model.

“Beta binomial regression” can refer (a) to hierarchical regressions in which the hierarchical prior is a beta distribution or (b) a general linear model where the beta-binomial distribution is the error model (or family in R-speak).

This issue is about (b).
The beta-binomial distribution is attractive as an error model/family for research where the response variable is bound between zero and some maximum number, which would be relevant for lots of research in psychology and psychiatry that uses questionnaire or rating scale sum-scores as response variable. Such data can also be modelled with the a binomial model, but the over-dispersion parameter of the beta binomial makes it more flexible which leads to better fit (If one is concerned about overfitting the data, one can use loo to compare the models).

To clarify what I am thinking of, here is the Stan code for a simple beta binomial regression model:
```
data { 
  int<lower=1> N;  // number of observations 
  int<lower=0> Y[N];        // response variable 
  int<lower=1> K;  // number of poredictors 
  matrix[N, K] X;  // design matrix 
}

transformed data {
  int maxY = max(Y);
}

parameters { 
  vector[K] b;                     // regression weights
  real<lower=0, upper = 1> theta;  // overdispersion  
}

transformed parameters {
  real<lower=0> phi = (1-theta)/theta;
}

model { 
  vector[N] p = inv_logit(X * b);
  b ~ normal(0,2);
  target += beta_binomial_lpmf(Y | maxY, p * phi, (1-p) * phi);
} 
```
Using the inverse logit as link function for the mean of the beta binomial is intuitive. There has also been [some discussion on the Stan mailing list](https://groups.google.com/forum/#!topic/stan-users/4iUO6TGopbs ) about parameterizing the over-dispersion parameter.

I think it would also be straight forward to put a (normal) hierarchical prior on the regression weights to implement a hierarchical.

**Comment by paul-buerkner** [comment]
(a) and (b) are mathematically equivalent. In (b) you just integrate (marginalize) over the beta-distributed random effects.

**Comment by gbiele** [comment]
I am aware that (a) and (b) are mathematically equivalent, just tried to be as clear as possible that the idea was not to use the beta distribution as a prior for variation between subjects in a hierarchical model. And yes, the motivation of the proposal was to have a distribution for e.g. sum-score data that is more flexible than the binomial distribution.

**Comment by paul-buerkner** [comment]
When using the `custom-family` branch, you can now define this family yourself. See #381 for details and example code, which happens to be for the beta-binomial model ;-)

**Comment by gbiele** [comment]
great, thanks!

**Comment by paul-buerkner** [comment]
In light of the (now merged) `custom_family` feature and the fact that the beta-binomial model is used as a case study in `vignette("brms_customfamilies")` I think this issue can be closed. Of course it is still reasonable to implement native (as opposed to custom families) in general, but the beta-binomial is not one of my priorities in this regard.
