### ISSUE TITLE
Ressurrecting phylogenetic correlation structures?

### ISSUE THREAD

**Issue by renatomoraisaraujo** [paul-buerkner/brms#378]
Dear Paul,

I found a closed issue related to implementing phylogenetic correlation structures in brms. Back then it appeared that the problem was solved with the method that features in the phylogenetic vignette now. You even questioned the person whether it would still be useful to implement correlation structures, but didn't get an answer.

Well, it happens that for the model I want to implement it doesn't make much sense to include "Species" as a group-level effect. I only want to account for the correlation between observations that happen to be in a phylogenetic context. I have been fitting a pGLS with a Brownian correlation structure but, besides the many limitations, I would really like to jump to Bayesian inference.

Would you still be keen on implementing a phylogenetic correlation structure? If so, I think the simplest one, the Brownian motion model correlation structure (please see https://rdrr.io/cran/ape/man/corClasses.html) would be ideal for a start. I really appreciate your feedback, thank you!

**Comment by paul-buerkner** [comment]
I think that's already possible. You can pass your pyhlogenetic covariance matrix (i.e. gamma * ta from the brownian model) by hand to the `cor_fixed` correlation structure of brms.

**Comment by renatomoraisaraujo** [comment]
Thank you very much for your answer. It seems very straightforward to do as you said. With the risk of sounding too obvious here, are these correlation structures not feasible to be used in a non-Gaussian model?

Error: Fixed residual covariance matrices are not implemented for family 'gamma'.

**Comment by paul-buerkner** [comment]
You need a distribution that can take a covariance matrix of residuals, and since we only have that for normal and student-t distributions in Stan, it is only possible for these families for now.

**Comment by renatomoraisaraujo** [comment]
Ok, it works in the gaussian model anyway. Thank you very much once again and thanks for the wonderful job with brms. It's quickly becoming my favourite analytical package in R!

**Comment by paul-buerkner** [comment]
Glad to hear that! :-)
