### ISSUE TITLE
Estimate prediction larger than 90% quantile

### ISSUE THREAD

**Issue by alireza202** [paul-buerkner/brms#38]
I'm getting predictions for my Zerio-Inflated Beta model, and for some predictions I see:

         Estimate  Est.Error 10%ile 25%ile 75%ile 90%ile
            (dbl)      (dbl)  (dbl)  (dbl)  (dbl)  (dbl)
    1 0.009530440 0.03391364      0      0      0      0
    2 0.010388541 0.03790067      0      0      0      0
    3 0.007963558 0.03169906      0      0      0      0
    4 0.008344872 0.03136680      0      0      0      0
    5 0.008264070 0.03016002      0      0      0      0
    6 0.008028368 0.03091140      0      0      0      0

My guess is that the Estimate is the mean of the posterior, right? Wouldn't it make more sense to use median of the posterior as an estimate for ZIB model?

My `predict` line is:

    testing_pred = predict(object = zib_fit, newdata = testing, probs = c(0.1, 0.25, 0.75, 0.9))

**Comment by paul-buerkner** [comment]
The Estimate is the mean, yes. You can easily get the median by using `0.5` in the probs argument as the 50% quantile is the median. It may make more sense for your particular model, but I don't know want to generally change the default behavior at the moment or use varying defaults depending on the family (the latter would be confusing for users I guess).

**Comment by alireza202** [comment]
Thanks. Just wanted to make sure. You're right, there is no need to change.

**Comment by paul-buerkner** [comment]
Great, I hope ZIB models are doing fine for your data! :-)

**Comment by alireza202** [comment]
ZIB is exactly what I wanted. Thanks for the great addition!
