### ISSUE TITLE
mi() + trunc()

### ISSUE THREAD

**Issue by maltelau** [paul-buerkner/brms#380]
Hi Paul

Like everyone else, I thank you for the amazing work you're doing with brms.

I'm getting an error when I'm trying to combine the new imputation feature with truncation.
I'm on the latest commit (02dab041352174fb74fa728b4b2b41d6ba902de0), reporting version brms_2.1.8

```
data(mtcars)
mtcars$cyl[1:10] <- NA

# runs fine, but might impute a negative number of cylinders
model <- brm(bf(mpg ~ mi(cyl)) +  bf(cyl | mi() ~ 1),
             data = mtcars)

# error
model <- brm(bf(mpg ~ mi(cyl)) + bf(cyl | mi() + trunc(lb = 0) ~ 1),
             data = mtcars)
```
The second with both mi() and trunc() fails with the error
```
Error in if (check_response && any(inv_bounds)) { : 
  missing value where TRUE/FALSE needed
```

`make_standata(..., check_response = FALSE)` seems to produce the right output in this case at a cursory glance, so an easy workaround could be to allow us to somehow pass in check_response to brm() which then passes it on to make_standata.

But perhaps a better solution would be to only check that the non-missing data is within bounds.
For example, change line 800 in data-predictor.R to something like:
```
Y_notmissing <- out$Y[!is.na(out$Y)]
inv_bounds <- Y_notmissing < out$lb | Y_notmissing > out$ub
```

**Comment by paul-buerkner** [comment]
Thanks! It should be fixed now in the latest github version.
