### ISSUE TITLE
brm warning question

### ISSUE THREAD

**Issue by katmaro** [paul-buerkner/brms#383]
I am new to Bayesian multilevel modelling and I'm trying to run some very simple models but I always run into the same warning message:

The model looks as followed:

model1 <- brm(y ~  x1+ x2 + x3 +
                      (1 | id),
                    data = data)

summary(model1)

Warning messages:
1: Rows containing NAs were excluded from the model 
2: In if (nchar(CXX) > 0) return(TRUE) :
  the condition has length > 1 and only the first element will be used

What does the second warning message mean? And do I have to be concerned about it? 

I very much appreciate your help.

**Comment by paul-buerkner** [comment]
This is not a warning issued by brms, but somewhat deeper. I suggest you update all of your packages in a fresh R session and try again. In the future, please ask such questions on the brms-users google group.
