### ISSUE TITLE
Feature request: Full and Subset Model Coefficient Averaging 

### ISSUE THREAD

**Issue by mikejagermeister** [paul-buerkner/brms#386]
Having recently made the conversion to Bayes, I was wondering if there's any way to get model averaged coefficients, similar to what the model.avg function does in the ‘MuMIn’ package. I see that the pp_average allows calculating weighted values for predicting but I can't seem to find a way to recover the weighted coefficients it uses to make these weighted predictions.

**Comment by paul-buerkner** [comment]
Try out function `posterior_average` on the `new-loo` brms branch on github.

**Comment by shannonajw** [comment]
How would you suggest trying it out? I tried installing brms from the new-loo branch but seem to get this error: "Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘loo’ 1.1.0 is being loaded, but >= 2.0.0 is required".

**Comment by paul-buerkner** [comment]
Run `devtools::install_github("stan-dev/loo", ref = "new-psis")`

**Comment by shannonajw** [comment]
Thanks! It works great, but is it also possible to obtain coefficients for parameters that are not constant across all models (I would imagine that they would be zero for the models where they are not included)? This would provide, for instance, the probability that a coefficient != 0 (like in Peter Hoff's (2009) textbook).

**Comment by paul-buerkner** [comment]
I have made some changes on github and added argument `missing`, which can be used to handle parameters that are missing in some of the models. If you just want to obtain model weights, use method ` model_weights`.

**Comment by shannonajw** [comment]
I'm trying this new feature out, but I'm still not getting any output for the missing parameters. It does however, come up with a new variable `temp_Intercept`. Here is the line that I'm using to run the averaging: 

```
posterior_average(fit_full, fit_m1, fit_m2, fit_m3, fit_m4, 
                      fit_m5, fit_m6, fit_m7, weights = "loo2", missing = 0) 
```

Additionally, using the option "marglik" for weights produces this error: "Error in vapply(which(modb), function(x) deparse(mc[[x + 2]]), "") : values must be length 1, but FUN(X[[1]]) result is length 5010" 

The `model_weights` method works great!

**Comment by paul-buerkner** [comment]
Thanks for testing! `posterior_average` should now show all parameters by default when `missing` is specified. Before, you had to specifiy `pars` manually in that case.

The other should now be fixed as well.

**Comment by shannonajw** [comment]
My pleasure! It works like a charm now. One small question: How would you obtain reproducible results for these methods (if at all possible)? I tried setting a seed through the `control` option but it doesn't seem to work. 

P.S. Thanks for creating this great package by the way, I'm a social scientist and this makes a whole slew of methods much easier to apply in my own research without needing to worry about excessive coding.

**Comment by paul-buerkner** [comment]
I have just added a `seed` argument for this purpose. This said, you can always set the seed yourself via `set.seed`.

**Comment by mikejagermeister** [comment]
Wow, thanks for making this! It works wonderfully. One question though: 

How do I get the subset-only inferences? 

For example, suppose I set up the following models in regular old glm:

`library(MuMIn)`
```
m1 = glm(len ~ supp, data=ToothGrowth)
m2 = glm(len ~ dose, data=ToothGrowth)
m3 = glm(len ~ dose + supp, data=ToothGrowth)
m4 = glm(len ~ dose * supp, data=ToothGrowth)
```
`model.avg(m1, m2, m3, m4)`

I then get the following output:

> Call:
model.avg(object = m1, m2, m3, m4)

Component models: 
‘123’ ‘12’  ‘1’   ‘2’  

Coefficients: 
       (Intercept)     dose1     dose2    supp1 dose1:supp1 dose2:supp1
full      18.81298 -8.203261 0.9187098 1.848306   0.6574348   0.9456473
subset    18.81298 -8.203261 0.9187098 1.849436   0.7748692   1.1145636

The missing argument as zero in brms gives me results that match the full coefficients. The subset ones only take into account the weights of models that include a parameter, so the subset coefficients for the interaction would match the ones in model 4, since model 4 is the only one that includes. If that's not an enabled feature, no worries. Just trying to figure out if there's a way to do this in the function as-is.

Thanks again for creating this. It's going to be quite useful!

**Comment by paul-buerkner** [comment]
I don't see this subset feature making much sense in `posterior_average`, since its output is a data.frame with rows being posterior samples and columns being parameters. If you want to average a coefficient that only exists in a subset of models, can't you just pass this subset? Alternatively, you may set `missing = NA` (need to reinstall from github for this), but be aware that if the subset of models has small weights, the number of non-NA posterior samples will be small as well.
