### ISSUE TITLE
copy variable-attributes from data to model.frame attribute of brmsfit object

### ISSUE THREAD

**Issue by strengejacke** [paul-buerkner/brms#393]
When you have [labelled data](https://cran.r-project.org/web/packages/sjlabelled/vignettes/intro_sjlabelled.html), most regression functions in the different packages just copy attributes from vectors/variables into the data frame that you can access with `model.frame()`:

```
library(sjPlot)
data(efc)
m <- lm(neg_c_7 ~ e42dep + c172code, data = efc)

> str(model.frame(m))
'data.frame':	834 obs. of  3 variables:
 $ neg_c_7 : atomic  12 20 11 10 12 19 15 11 10 28 ...
  ..- attr(*, "label")= chr "Negative impact with 7 items"
 $ e42dep  : atomic  3 3 3 4 4 4 4 4 4 4 ...
  ..- attr(*, "label")= chr "elder's dependency"
  ..- attr(*, "labels")= Named num  1 2 3 4
  .. ..- attr(*, "names")= chr  "independent" "slightly dependent" "moderately dependent" "severely dependent"
 $ c172code: atomic  2 2 1 2 2 2 2 2 2 2 ...
  ..- attr(*, "label")= chr "carer's level of education"
  ..- attr(*, "labels")= Named num  1 2 3
  .. ..- attr(*, "names")= chr  "low level of education" "intermediate level of education" "high level of education"

<truncated...>
```

It would be great if `brms` also behaves in this way. Currently, I get:

```
m <- brm(neg_c_7 ~ e42dep + c172code, data = efc)

> str(model.frame(m))
'data.frame':	834 obs. of  3 variables:
 $ neg_c_7 : num  12 20 11 10 12 19 15 11 10 28 ...
 $ e42dep  : num  3 3 3 4 4 4 4 4 4 4 ...
 $ c172code: num  2 2 1 2 2 2 2 2 2 2 ...
 - attr(*, "terms")=Classes 'terms', 'formula'  language neg_c_7 ~ neg_c_7 + e42dep + c172code
  .. ..- attr(*, "variables")= language list(neg_c_7, e42dep, c172code)
  .. ..- attr(*, "factors")= int [1:3, 1:3] 1 0 0 0 1 0 0 0 1
  .. .. ..- attr(*, "dimnames")=List of 2

<truncated...>
```

Preserving the label(s)-attributes would make it easier to automatically label plots or tables (see for instance [here](https://strengejacke.wordpress.com/2017/10/23/one-function-to-rule-them-all-visualization-of-regression-models-in-rstats-w-sjplot/)).

**Comment by paul-buerkner** [comment]
It's because brms calls `na.omit` even if no missing values are present, which leads to indexing of variables and thus to the removal of attributes. Let me check if there is a nice workaround.

**Comment by paul-buerkner** [comment]
It should now be fixed on github.

**Comment by strengejacke** [comment]
Thanks, it works! Happy Easter, so don't care about issues too much this weekend! :-)
