### ISSUE TITLE
marginal_effects without errotbars

### ISSUE THREAD

**Issue by xieguagua** [paul-buerkner/brms#395]
Dear Paul,

Can we plot marginal effects without error bars.
like this (ci=FALSE)
library("ggeffects")
fit_zinb1 <- brm(count ~ persons + child + camper, data = zinb,
                 family = zero_inflated_poisson("log"))

dat1 <- ggpredict(fit_zinb1, terms = c( "child"))
plot(dat1)
plot(dat1,ci = FALSE)

Thanks.

**Comment by paul-buerkner** [comment]
Specify `probs = c(0.5, 0.5)` in `marginal_effects`. In the future please ask such questions on brms-users (https://groups.google.com/forum/#!forum/brms-users) so that my answer is better visible for other users.

**Comment by xieguagua** [comment]
Paul,

Thanks for your kind answer.
It works!
p<-marginal_effects(fit_zinb2,probs = c(0.5, 0.5))
plot(p, errorbar_args = list(width=0))

Unfortunately, I can not access Google group  freely.

Best Regards.


 
From: Paul-Christian Bürkner
Date: 2018-04-06 14:41
To: paul-buerkner/brms
CC: xieguagua; Author
Subject: Re: [paul-buerkner/brms] marginal_effects without errotbars (#395)
Specify probs = c(0.5, 0.5) in marginal_effects. In the future please ask such questions on brms-users (https://groups.google.com/forum/#!forum/brms-users) so that my answer is better visible for other users.

**Comment by paul-buerkner** [comment]
Ah I see, in this case, please feel free to continue asking questions on github.
