### ISSUE TITLE
Additional response distributions for models with multiple outcomes

### ISSUE THREAD

**Issue by jamesrrae** [paul-buerkner/brms#396]
One appreciated feature about brms is the ability to fit multivariate models that model the residual between response variables, such as the one below:

`brm(cbind(y1,y1) ~ x1, data=data)`

However, the brms manual indicates that modeling the residual correlation between measures is only possible for Gaussian and student response distributions.  Would it be possible to add this feature for other response distributions, such as the beta distribution?

**Comment by paul-buerkner** [comment]
If you can write down a multivariate beta model for me which includes a residual correlation, it is possible.

**Comment by jamesrrae** [comment]
That's beyond my statistical knowledge. I guess I'll try and fit the model I want on the "x-side" of the model or maybe transform my outcome variables so I can use a student or normal response distribution.

**Comment by paul-buerkner** [comment]
You can always bring correlations between response variables into the model via correlations of random effects. Assume both of your responses are poisson distributed and that `obs` indicates the observation number (i.e. `data$obs <- 1:nrow(data)`). Then the following models residual standard deviations and correlations:

```R
brm(cbind(y1,y2) ~ x1 + (1|p|obs), data=data, family = poisson())
```

For beta-models, the problem with this approach is that the random effects interfere with the `phi` parameters of the beta-distribution as both model overdispersion.

**Comment by jamesrrae** [comment]
Great to know - this will be helpful when I'm using other response distributions! I'll try to figure out another work around for the beta distribution problem.

**Comment by jamesrrae** [comment]
I'm not sure about the correlated residuals, but as an update to this request I did come across this paper that fit a multivariate beta regression and hierarchical beta regression (and I think the authors have some other papers on this topic too):

http://www.dme.im.ufrj.br/arquivos/publicacoes/arquivo245.pdf

The model is described starting on page 4. Could this be an option for brms? Not sure how I could assist with moving this forward, but I'm happy to any way I can.

**Comment by paul-buerkner** [comment]
I agree that copulas are a powerful way to create multivariate distributions. Since the here proposed appraoch is based on copulas and since we already have a copula issue (#444) I am closing this issue to avoid duplication.
