### ISSUE TITLE
LOOIC value of brm model

### ISSUE THREAD

**Issue by tibo1** [paul-buerkner/brms#402]
I am using the brm function with three different family specifications to estimate which model fits my data best. I have zero inflated count data and I am using the families beta (b), zero inflated beta (zib) and beta binomial2 (bb2) (for b and zib I have transformed the outcome variable to range between 0 and 1). When using the LOO function on the three different models I get negative LOOIC values for the b and zib models, and a positive LOOIC value for the bb2 model. I am a novice concerning the use of LOOIC so what I am wondering is if the LOOIC value can be both positive and negative (I have only seen positive values specified in the literature I have read)? If it can only be positive, do you have any suggestions for what I might have done wrong when specifying the b and zib model? Thanks so much in advance for your reply. Best regards, Tiril

**Comment by paul-buerkner** [comment]
Please ask this question on the brms users google group.
