### ISSUE TITLE
Time taken for a brms model

### ISSUE THREAD

**Issue by rubenarslan** [paul-buerkner/brms#406]
I'm often interested in the sampling performance of one model relative to another. But I often don't know that until I run the second (or third or x) model. Would it be possible and maybe generally useful for brms to store the time taken from model compilation to finishing?

**Comment by paul-buerkner** [comment]
@jgabry is this information already stored somewhere in the stanfit object?

**Comment by jgabry** [comment]
Yeah, you can call get_elapsed_time on a stanfit object. I don’t think it
includes compilation time, but will tell you sampling and warmup times. But
I think compilation time (even if annoying) should be dwarfed by fitting
time for any model slow enough to care about how long it takes.

Standard disclaimer: time itself is relevant in practice, but irrelevant by
itself for assessing efficiency. Need n_eff/time for that!

**Comment by rubenarslan** [comment]
Sorry that I didn't find this myself. Great!

@jgabry Sure. Sorry, I spoke vaguely. Usually, it goes something like this: I thought the last time a very similar model finished in 24 hours, why is this still running after 48, did I misspecify something or do I misremember? And maybe one day in the distant future, I'll be able to accurately guesstimate the walltime for the cluster from all my previous brms fitting experience, instead of going by the heuristic of expectation * 10. And yes, I've never cared about compilation time with these models..

**Comment by jgabry** [comment]
On Wed, Apr 18, 2018 at 3:10 PM Ruben C. Arslan <notifications@github.com>
wrote:

> Sorry that I didn't find this myself. Great!
>

No problem.

@jgabry <https://github.com/jgabry> Sure. Sorry, I spoke vaguely. Usually,
> it goes something like this: I thought the last time a very similar model
> finished in 24 hours, why is this still running after 48, did I misspecify
> something or do I misremember? And maybe one day in the distant future,
> I'll be able to accurately guesstimate the walltime for the cluster from
> all my previous brms fitting experience, instead of going by the heuristic
> of expectation * 10. And yes, I've never cared about compilation time with
> these models..
>


Got it. That makes sense. If a small change to a model makes it take a lot
 longer to run it’s probably a sign that either there was a mistake in the
code making that small change, or that the small change is actually not so
small in its affect on the posterior geometry.
