### ISSUE TITLE
What families have ARMA effect implemented?

### ISSUE THREAD

**Issue by alireza202** [paul-buerkner/brms#41]
When I try Poission or Negative Binomial families, it seems like ARMA effect is not yet implemented for them. I was wondering, what families have ARMA effects implemented?

> Error: ARMA effects for family negbinomial are not yet implemented

**Comment by paul-buerkner** [comment]
They are implemented for the 'linear' model families gaussian, student and cauchy. It is somewhat difficult to implement them also for other families.
