### ISSUE TITLE
posterior_linpred() with transform = TRUE fails for custom families

### ISSUE THREAD

**Issue by strengejacke** [paul-buerkner/brms#413]
Example:

```r
data("cbpp", package = "lme4")
library(brms)

beta_binomial2 <- custom_family(
  "beta_binomial2",
  dpars = c("mu", "phi"),
  links = c("logit", "log"),
  lb = c(NA, 0),
  type = "int",
  vars = "trials[n]"
)

stan_funs <- "
real beta_binomial2_lpmf(int y, real mu, real phi, int T) {
  return beta_binomial_lpmf(y | T, mu * phi, (1 - mu) * phi);
}
int beta_binomial2_rng(real mu, real phi, int T) {
  return beta_binomial_rng(T, mu * phi, (1 - mu) * phi);
}
"
stanvars <- stanvar(as.integer(cbpp$size), name = "trials")

fit_brm <- brm(
  incidence ~ period + (1 | herd),
  data = cbpp,
  family = beta_binomial2,
  stan_funs = stan_funs,
  stanvars = stanvars
)

# I'm using the generic here...
rstantools::posterior_linpred(fit_brm, transform = TRUE)
```

Result:

> Error in get(fitted_fun, draws$f$env) :
>   object 'fitted_beta_binomial2' not found

The custom family does not store the link-inverse function, I _think_ this might be the reason. I stumbled upon this issue due to a user-feedack (https://github.com/strengejacke/sjPlot/issues/347).

My solution was to check whether a `brmsfit`-object has a custom family, and if so, create a link-function with `make-link()` and get the link-inverse from that function:

```r
if (!is.null(fam$family) && (is.character(fam$family) && fam$family == "custom")) {
  il <- stats::make.link(fam$link)$linkinv
}
```

I'm not sure if this "workaround" is sufficient as implementation in `posterior_linpred()` in this case?

**Comment by paul-buerkner** [comment]
I think the problem is simply that you need to specify the `fitted_*` function for you custom family as indicated by the error message. See https://cran.r-project.org/web/packages/brms/vignettes/brms_customfamilies.html for details

**Comment by strengejacke** [comment]
Correct, that works! Thanks!
