### ISSUE TITLE
pointwise Warning on summary

### ISSUE THREAD

**Issue by rubenarslan** [paul-buerkner/brms#416]
I've added LOOs to a few models using `add_ic` with the argument `pointwise = FALSE`. When I later `summary`se them, they throw the warning 

> Switching to pointwise evaluation to reduce RAM requirements. This will likely increase computation time. You may overwrite the default behavior with the 'pointwise' argument.

each time. But this is not actually happening (would take way longer).

**Comment by paul-buerkner** [comment]
Hmm strange. I don't see a problem in the code right now. Do you have a reprex for me? 

Also, I was thinking lately of removing the auto-setting of `pointwise` and instead go for `pointwise = FALSE` by default in any case (the user could still turn it on of course). Any opinions on this?

**Comment by paul-buerkner** [comment]
Ah I get now what's happening. Let me fix this.

**Comment by paul-buerkner** [comment]
Should be fixed now. Can you try it again?
