### ISSUE TITLE
Instructions for contributing family to brms?

### ISSUE THREAD

**Issue by gbiele** [paul-buerkner/brms#421]
Hi,

I remember having read in an issues that you (Paul) wrote that you would welcome help for adding new families to brms and maybe even pointed to a tutorial about how one can do this. Now I can't find this and wonder if I am just imagining this.

Anyhow: Would you (Paul) welcome support for adding new families and if so, do you have a documentation that could guide one through the process (where does one add things, which tests are required)?

Best, Guido

**Comment by paul-buerkner** [comment]
Hi Guido,

I think the guide is the following: https://cran.r-project.org/web/packages/brms/vignettes/brms_customfamilies.html

It is about custom families in brms. Was that the one you had in mind?

**Comment by gbiele** [comment]
I was not thinking about using a custom family as you describe in the vignette (which works!), but about contributing a family to brms such that one can use it without using the custom family approach.

I understand that this might take some time. on the other hand, after looking at the pull request for custom families, it seems to me that this might be a doable job.

**Comment by paul-buerkner** [comment]
I see. I should write a vignette about this, but for now, here are the steps that come to my mind:

* In families.R, let `.brmsfamily` know about your new family and define your own family function, which is just a wrapper around `.brmsfamily`.
* Still in families.R, add your family name to either `real_families` or `int_families`. 
* If possible try to use already existing names of distributional parameters otherwise the task will be a lot more complicated (explanation on request). You may need to amend some of the `has_*` functions in families.R
* In stan-likelihood.R define a `stan_llh` function for your family.
* In data-predictor.R, allow checking of the response variables for your family in `data_response`.
* Define `fitted_`, `predict_` and `log_lik_` functions for your family (just as for the custom families) in the corresponding R files.
* If required, define distribution functions in distributions.R.

As I am writing that I realize this whole process is actually less complicated than I thought (when not adding new distributional parameters). The only parts I don't like are some of those in families.R. When I find the time, I will do a little bit of refactoring there.

**Comment by gbiele** [comment]
Thanks, I'll give it a try in the next weeks when I have some free time.

**Comment by jgabry** [comment]
@gbiele Which “family” do you plan to contribute? Given the new ability to use custom families it seems less necessary to have many more built-in families unless they are generally useful outside of very specific modeling needs. That is, depending on how generally useful the family is it may or may not make sense for that code to be maintained long-term in brms. It will depend on what Paul thinks obviously, but maybe worth laying out the details here before putting in all the work!

**Comment by paul-buerkner** [comment]
@jgabry This is a good point, which I think requires further discussion. custom families are definitely more advanced and what we need for them is a sort of "repository" where users can post their custom families so they can be used by others. 

The advantages of native families are of course less work for users (in particular writing the corresponding `log_lik`, `predict` etc. methods), and better input checking.

That said, I have an idea in mind to make implementing (most) native families way easier by having all required information stored in one place per family. For the gaussian and poisson families, this could for instance look as follows:

```R
.family_gaussian <- function() {
  list(
    links = c("identity", "log", "inverse"),
    dpars = c("mu", "sigma"),
    type = "real", ybounds = c(NA, NA), closed = FALSE,
    links_dpars = list(sigma = c("log", "identity")),
    ad = c("weights", "se", "cens", "trunc", "mi")
  )
}

.family_poisson <- function() {
  list(
    links = c("log", "identity", "sqrt"),
    dpars = c("mu"),
    type = "int", ybounds = c(0, NA), closed = TRUE,
    links_dpars = list(),
    ad = c("weights", "cens", "trunc", "mi")
  )
}
```

**Comment by paul-buerkner** [comment]
I have done some refactoring today, which greatly simplifies adding a native family (see PR #422). Suppose your family is called `foo`, the required steps are:

* Open an issue on Github to discuss if the family should be implemented as a native family. A working implementation in the form of a custom family may be helpful. 
* In `family-lists.R`, add function `.family_foo` which should contain basic information about your family (you will find lots of examples for other families there).
* In `families.R`, add family function `foo` which should be a simple wrapper around `.brmsfamily`.
* In `stan-likelihood.R`, add function `stan_llh_foo` which provides the likelihood of the family in Stan language.
* If necessary, add self-defined Stan functions in separate files under `inst/chunks`.
* Add functions `predict_foo`, `fitted_foo` and `log_lik_foo` to `predict.R`, `fitted.R` and `log_lik.R`, respectively.
* If necessary, add distribution functions to `distributions.R`.

I have also added this information to the `brms_customfamilies` vignette.

**Comment by gbiele** [comment]
Sorry for the late reply.

I was planning on working at the beta-binomial family. I agree that the custom family functionality makes it already very easy to use the beta binomial distribution. 
Still, I am trying to convince colleagues who are used to SPSS or Stata to use brms, and in this context it makes sense to make it as easy as possible to use it. I need especially the beta binomial family because our research often has sum scores as dependent variable.

@paul-buerkner : Thanks for making it easier to contribute families!

**Comment by paul-buerkner** [comment]
I see. If you like, we can follow my newly specified guidelines on adding native families and open a new issue in which we discuss the beta-binomial family?

Then we can treat this issue here as closed since we now have documentation and easy workflow to implement native families.

**Comment by paul-buerkner** [comment]
Closing this one now. As said above, please feel free to open a new issue to discuss implementation of the beta-binomial family.
