### ISSUE TITLE
gfortran issue [solved]

### ISSUE THREAD

**Issue by eiskrzypczakhennig** [paul-buerkner/brms#426]
Dear Paul and `brms` users, 
just a non-statistical comment and solution to a problem I came across recently after upgrading the `gcc` compiler from 7.3.1 to version 8.1.0. Installing then `brms` version 2.2.0 ended in error messages about missing shared objects:

<pre><code>
`Error in dyn.load(file, DLLpath = DLLpath, ...):   
unable to load shared object '.../3.5/igraph/libs/igraph.so':  
libgfortran.so.4: cannot open shared object file: No such file or directory  
ERROR: lazy loading failed for package 'brms'`
</code></pre>

Reinstalling package `igraph` first and then `brms` solved this issue. I thought this post may be helpful to some people or/and can be included in the FAQ for minor issues. Otherwise, just remove it.

**Comment by paul-buerkner** [comment]
Thanks! Good to know you were able to solve it.
