### ISSUE TITLE
CAR model with multivariate response

### ISSUE THREAD

**Issue by qdread** [paul-buerkner/brms#427]
First, thank you very much for your excellent package which really makes my life a lot easier since it frees up time for me to actually think about science instead of parsing Stan code. 

I am interested in whether it is possible for brms to support multivariate responses in conditional autoregressive models. Currently, if I specify a model with multivariate response and specify autocorrelation with `cor_car(W)` the message returned is: `Error: CAR models are not implemented when 'rescor' is estimated.` Is this something that is possible to implement in the future or does the structure of CAR models not allow rescor to be estimated? Thanks again for all your work.

**Comment by qdread** [comment]
Yes, it does work in the dev version! Thanks very much and I apologize for not checking that version first.

**Comment by paul-buerkner** [comment]
No need to apologize. I just fixed it because of your post ;-)
