### ISSUE TITLE
Error with marginal_effects

### ISSUE THREAD

**Issue by jswesner** [paul-buerkner/brms#428]
I've been getting the error below with marginal effects. I've used it successfully for years.  Any clue what this would be?

marginal_effects(m1)
Error: `expr` must quote a symbol, scalar, or call

**Comment by paul-buerkner** [comment]
Without a minimal reproducible example there is little I can tell you.

**Comment by paul-buerkner** [comment]
Could it be that you are using the dev version of ggplot2?

**Comment by jswesner** [comment]
Yep. That was it. I installed the non-dev version of ggplot2 and all works. Didn't realize I had the dev version.
