### ISSUE TITLE
logitnormal regression

### ISSUE THREAD

**Issue by schmettow** [paul-buerkner/brms#429]
Hi Paul,

thanks again, for truly maximizing our choice of models so far. 

Logitnormal distribution is an alternative to beta distribution and applies for response types with lower and upper bounds, such as rating scales. In regression models, the advantage over beta distribution is that logit-normals location and scale parameters, right away. This is more intuitive and makes it easier to specify priors, distributional models and heteroscedasticity.

Research background: I am currently looking at rating scale responses in a variety of experiments. I realize that individual response patterns vary not just in location, but also massively in range. While beta regression works well for rating scale responses, in general, I can't see how to model participant-level variance. With logitnormal regression, I could just specify a varying scale parameter on participant level. The second case is my research on the Uncanny Valley phenomenon, where both location and range of responses are non-linear.

Implementation: Probably less straight-forward. The distribution is not implemented in Stan. In addition, mean and variance don't have analytical solutions.

**Comment by paul-buerkner** [comment]
If you can provide me with a working implementation of this distribution in the form of a custom family (see https://cran.r-project.org/web/packages/brms/vignettes/brms_customfamilies.html), I am happy to implement it as a native family.

That said, you can model the variation with a beta family as well by predicting the `phi` parameter even if that's only approximately equal to the precision (inverse of the variance).

**Comment by schmettow** [comment]
I took a look at it. Really cool framework! I'll see how far I can get on my own.
Distributional beta regression worked like a charm.

**Comment by schmettow** [comment]
This is something for the long summer break ;)
