### ISSUE TITLE
censored hurdle model

### ISSUE THREAD

**Issue by hansvancalster** [paul-buerkner/brms#430]
Hi Paul,

I would like to fit a *right-censored hurdle gamma* model. When I try this with `brm()` this gives an error saying that censoring is not yet implemented for `hurdle_gamma` (or mixtures models in general I expect). 

I already looked at the `make_stancode` of a `hurdle_gamma` model without censoring, on the one hand, and a `gamma` model with censoring, on the other, and I think both can be combined to achieve what I need. But before going that way I just wanted to ask your opinion about this and whether you have plans to implement this?

Hans

**Comment by paul-buerkner** [comment]
What we need are the `*_lcdf` and `*_lccdf` functions of these families. Let me see if I can implement them.

**Comment by paul-buerkner** [comment]
In the dev version, censoring (and truncation) should now be working for zero-inflated and hurdle models.

**Comment by hansvancalster** [comment]
Amazing work! 

I convinced myself that it works correctly with this example:

```
set.seed(1234)
n <- 60
alpha <- 0.6 # 0+1 inflation
gamma <- 0.4 # conditional one inflation
U <- 50
data <- data.frame(y = ifelse(rbinom(n, 1, alpha) == 1,
               rbinom(n, 1, gamma),
               rbeta(n, 1, 2)
               )) %>%
  mutate(r = y * U,
         censored = ifelse(r == U, "right", "none"))
  
```

```
m_zoib <- brm(y ~ 1, family = zero_one_inflated_beta(), data = data)
m_hgc <- brm(r | cens(censored) ~ 1, family = hurdle_gamma(), data = data)
```



```
qs_zoib <- seq(0, 4, 0.01)
ps_zoib <- posterior_samples(m_zoib) %>%
  mutate(mu = plogis(b_Intercept),
         ps_number = row_number()) %>%
  group_by(ps_number) %>%
  do(data.frame(qs = qs_zoib, 
                cdf_values = ifelse(qs_zoib < 1,
                                    .$zoi * (1 - .$coi) + 
       (1 - .$zoi) *  pbeta(q = qs_zoib,
                          shape1 = .$mu * .$phi,
                          shape2 = (1 - .$mu) * .$phi),
       .$zoi * (1 - .$coi) + 
       (1 - .$zoi) *  pbeta(q = qs_zoib,
                          shape1 = .$mu * .$phi,
                          shape2 = (1 - .$mu) * .$phi) + 
         .$zoi * .$coi))) %>%
  group_by(qs) %>%
  summarise(p50_cdf = quantile(cdf_values, 0.5),
            lwr_cdf = quantile(cdf_values, 0.025),
            upr_cdf = quantile(cdf_values, 0.975)) %>%
  mutate(model = "zero-one-inflated beta",
         qs = qs * U)
```


```
qs_hgc <- seq(0, 4*U, 0.5)
ps_hgc <- posterior_samples(m_hgc) %>%
  mutate(mu = exp(b_Intercept),
         ps_number = row_number()) %>%
  group_by(ps_number) %>%
  do(data.frame(qs = qs_hgc, 
                cdf_values = ifelse(qs_hgc > 0,
                                    .$hu + (1 - .$hu) * pgamma(q = qs_hgc,
                                                               shape = .$shape,
                                                               scale = .$mu/.$shape),
                                    .$hu))) %>%
  group_by(qs) %>%
  summarise(p50_cdf = quantile(cdf_values, 0.5),
            lwr_cdf = quantile(cdf_values, 0.025),
            upr_cdf = quantile(cdf_values, 0.975)) %>%
  mutate(model = "right-censored hurdle gamma")
```


```{r}
ps <- bind_rows(ps_zoib, ps_hgc)
```


```
ps %>%
  ggplot() + 
  geom_ribbon(aes(x = qs, ymin = lwr_cdf, ymax = upr_cdf, fill = model), 
              alpha = 0.2) + 
  geom_line(aes(x = qs, y = p50_cdf, colour = model)) +
  stat_ecdf(data = data, aes(x = r), alpha = 0.4) +
  theme(legend.position = "top")
```
![image](https://user-images.githubusercontent.com/18713718/40237418-b0d5a3a4-5ab0-11e8-9967-cc1d029c8ad8.png)

**Comment by paul-buerkner** [comment]
Nice! Glad that it works. I am closing this issue now.

**Comment by franzsf** [comment]
hi Paul, 

Thanks again for all your work on this package.

I saw this thread and wanted to confirm if lower-bound truncation can work on hurdle models? 

I'm currently having trouble getting brms to accept a hurdle_gamma model with lower-bound truncation -- I specifically suspect all the zero values (i.e., which shouldn't meet the hurdle) in violating the "Some responses are outside of truncation bounds" error I'm getting.

For context, the outcome variable reflects member-month medical costs, which can be zero (no claims in the month) or some amount over $150:

`> summary(model_dataset[MH > 0,MH])
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  150.1   177.1   304.3   813.0   705.8 45645.8 `

The toy formulation that triggers the error:

`cost.model.0 <- brm(bf(MH | trunc(lb = 150) ~ 1,
                       hu ~ 1),
                    family = hurdle_gamma(link="log", link_hu = "logit"),
                    data = model_dataset,
                    iter = 2000,
                    warmup = 1000,
                    chains = 4,
                    cores = 4)`

Appreciate any insight into anything I'm doing wrong here (or potential enhancement if what I'm seeing is accurate). Thanks again for all your work!

**Comment by paul-buerkner** [comment]
Please ask brms related questions on https://discourse.mc-stan.org/ rather than in (closed) github issues.
