### ISSUE TITLE
max_treedepth in brmsfit not reported to shinystan

### ISSUE THREAD

**Issue by ecologics** [paul-buerkner/brms#431]
Actual instances of exceeding the maximum tree depth (i.e. Stan's `max_treedepth` parameter) are not correctly reported in `shinystan` on `brmsfit` objects. I do not know if this is a problem generally with `shinystan` or with `brms`. But am reporting it here.

Here is an example.

First create some data where the default `max_treedepth=10` is insufficient, and then examine reports at the console and in `shinystan`.

```
set.seed(235)  
## Create a second order relationship with some error
x <- seq(-1, 1, by=0.1)
y <- 10*x^2 + rnorm(length(x), sd=0.03)
df <- data.frame(x,y)

## Run brms with a spline term
## and a prior on the spline
## adapt_delta adjusted to avoid divergent transitions
## max_treedepth set at the minimum required to avoid console warnings
m <- brm(y ~ s(x), 
         data=df, 
         iter=500, 
         prior=prior_string("cauchy(0, 6)", class="sds", coef="s(x)"), 
         control=list(adapt_delta=0.99, 
                      max_treedepth=13))
## Runs with no warnings of exceeded maximum treedepth

## Now examine in shinystan
launch_shinystan(m)
```

Here is a screen shot of the shinystan interface indicating the shinystan may be calculating instances of exceeded treedepth based on the default `max_treedepth=10` and not on the value provided to `brm(..., control=list(max_treedepth=)`.

![image](https://user-images.githubusercontent.com/17838640/40135512-c411d820-5902-11e8-8925-c485b6224fb8.png)

**Comment by jgabry** [comment]
@paul-buerkner I think you just need to use the `max_treedepth` argument to `as.shinystan` internally, now that you’re no longer using the method for stanfit objects. Unfortunately it can’t infer max_treedepth from the sampler parameter values on their own. If you’re already specifying that argument then maybe this is a shinystan issue.

**Comment by paul-buerkner** [comment]
Hmm weird, I thought your shinystan PR already contained the treedepth information. See https://github.com/paul-buerkner/brms/blob/master/R/brmsfit-methods.R line 972 ff.

**Comment by jgabry** [comment]
Hmm indeed it looks like I added that in my PR.

**Comment by jgabry** [comment]
@ecologics Does `m$fit@stan_args[[1]] ` contain `max_treedepth`?

**Comment by ecologics** [comment]
Yes, although it is nested under `$control`.

```
> m$fit@stan_args[[1]]
$chain_id
[1] 1

$iter
[1] 500

$thin
[1] 1

$seed
[1] 1106738029

$warmup
[1] 250

$init
[1] "random"

$algorithm
[1] "NUTS"

$method
[1] "sampling"

$control
$control$adapt_delta
[1] 0.99

$control$max_treedepth
[1] 13
```

**Comment by paul-buerkner** [comment]
Thanks! It should now be fixed in the dev version.

**Comment by jgabry** [comment]
Thanks!
