### ISSUE TITLE
weights in brm

### ISSUE THREAD

**Issue by eiskrzypczakhennig** [paul-buerkner/brms#436]
Dear Paul, 
I am using the weight option in the `brm` function to account for different variances in groups in a negative binomial generalized linear mixed effect model. Using weights this way is to my understanding approximating the idea of the weighting function `varIdent()`  from the R package `nlme`. After considering the Stan code and your `brm` code, I am still trying to make up my mind, how weights are used for the posteriors. On the one hand, the Stan code shows clearly that the posteriors are simply multiplied with weights:

<pre><code>
vector<lower=0>[N] weights; \\ model weights
target += weights[n] * neg_binommial_2_log_lpmf(Y[n] | mu[n], shape);
</code></pre>

On the other hand, other packages seem to implement weights sometimes differently. For example, the `gls()` function from the `nlme` package sems to use internally multiplicative inverse of weights, while showing in the summary output "raw" weights. Again, the function `lm()` [differs](http://www.imachordata.com/a-quick-note-in-weighting-with-nlme/) in the implementation of weights when compared to `gls()`.  So, the way of implemeting weights in models can differ from R package to R package. 

Can you tell how `brm()`uses weights? Does it uses internally the multiplicative inverse, which would imply that the user needs to use the "raw" form of weights? Or does it take the weights as they are given by the user, which would imply that the multiplicative inverse needs to be taken by the user a priori coding the model? Many thanks!

**Comment by paul-buerkner** [comment]
Hi, such questions are better asked at http://discourse.mc-stan.org/ (with the brms tag). Would you mind asking this question again there?

**Comment by eiskrzypczakhennig** [comment]
Dear Paul, 
thanks a lot for your quick response. I have opened the topic at the suggested [list](http://discourse.mc-stan.org/t/weights-in-brm/4278).
