### ISSUE TITLE
Error in zero_inflated_beta model, when there is a non-relevant column with type 'logical'

### ISSUE THREAD

**Issue by alireza202** [paul-buerkner/brms#44]
This is a strange error I was getting, and it took me some time to figure it out. My dataframe had a column with type logic (say x3, with all NA values). When I ran ZIB model with `trait` in the formula, I would get:

> Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]): contrasts can be applied only to factors with 2 or more levels

And I was not using that column in my formula! If I removed `trait` from the equation it would run though.

I figured out when I remove the offending column, it runs.

Here is my brm call:

```
brm(formula = d ~ 0 + trait * (x1 + x2) + (0 + trait | item), 
    data = df,
    family = 'zero_inflated_beta',
    chains = 2,
    cluster = 2,
    iter = 1000, 
    warmup = 300) -> fitted_model
```

**Comment by paul-buerkner** [comment]
Thanks for investigating and reporting this issue! As far as I can tell, this should already be fixed in the latest CRAN release (0.8.0). Would you mind testing it again within this version and tell me if it works?

**Comment by alireza202** [comment]
I'm working on a project these days using a dev version. When I'm done with it, I'll update, and test it.

**Comment by paul-buerkner** [comment]
@alireza202 Just a quick follow up to ask if you were able to test it with the new version?

**Comment by alireza202** [comment]
Not really. That project is put aside for now, and I can't go back to it. If I ran into the problem again, I'll report here.

**Comment by paul-buerkner** [comment]
Thanks for the reply @alireza202. All of my own tests are suggesting that it is fixed. Also, I have added unit tests to make sure I won't accidently bring it in again. Accordingly, I think that this issue can be closed  now. In case you somehow run into the same problem again, please feel free to reopen it.
