### ISSUE TITLE
Specifying single k-fold subset 

### ISSUE THREAD

**Issue by qdread** [paul-buerkner/brms#441]
Hello again,
I have a very large dataset that I am using to fit a multivariate model and do k-fold cross validation. I have manually specified subsets for k-fold cross-validation so that I can do stratified subsetting for the folds. I need to run each fold in parallel because of the time it takes to fit each fold. Currently the `Ksub` argument of the `kfold` function is specified as follows:

>  If Ksub is a single integer, Ksub subsets (out of all K) subsets will be randomly chosen. If Ksub consists of multiple integers, the corresponding subsets will be used. This argument is primarily useful, if evaluation of all subsets is infeasible for some reason.

I would like to be able to specify a *single* subset to be fit so that I can fit all subsets in parallel simultaneously. Would it be possible to get an option to specify a single integer (or factor level) so that only that single subset is fit? Thanks again for your help.

**Comment by paul-buerkner** [comment]
I see the problem. It's the same as with `sample` when only a single integer is passed. Let me think of a solution.

**Comment by paul-buerkner** [comment]
Done. If you want, say, to fit only the second subset, go for `Ksub = as.array(2)`. brms will recognize if you pass an array in which case it will always use these subsets instead of randomly choose subsets when `length(Ksub) == 1`.

**Comment by qdread** [comment]
Thanks! You're a lifesaver. Works perfectly.

**Comment by paul-buerkner** [comment]
Great! Good luck with your analysis.
