### ISSUE TITLE
Pattern for changing variable names with `posterior_linpred()`?

### ISSUE THREAD

**Issue by strengejacke** [paul-buerkner/brms#442]
When I have a model with multiple responses, use `posterior_linpred()` and convert the result into a data frame, then response variables with underscores are "renamed".

For instance, formulas are:

> Formula:
> neg_c_7 ~ e42dep + c12hour + c172code + (1 | ID | e15relat) 
> c12hour ~ c172code + (1 | ID | e15relat) 

Then the variable (column) names from `posterior_linpred()` are:
`1.negc7`, `2.negc7`, `3.negc7` and so on.

I was just wondering which pattern is applied to do the renaming? I need this for one of my packages (ggeffects), which computes marginal effects for variuous models, and for multiple response models I'm looking for the name of the dependent variable in the column names of the predictions, which of course no longer match when underscores are removed. Are there any other chars that are removed?

**Comment by paul-buerkner** [comment]
It is `base::make.names` function, but also note that `posterior_linpred` returns a 3D-array of posterior draws for multivariate models.

**Comment by strengejacke** [comment]
Yes, but I mean the data frame returned when you coerce the results to a data frame.

But I'm still confused. Here's the structure of the returned array from `posterior_linpred()`:

```r
str(p) 
#> num [1:4000, 1:834, 1:2] 11.4 12 11.5 12 11.7 ...
#>  - attr(*, "dimnames")=List of 3
#>   ..$ : NULL
#>   ..$ : NULL
#>   ..$ : chr [1:2] "negc7" "c12hour"
```

As you see, the dimension name is _negc7_.

The column names after coercing to data frame, are ofcouse:

```r
colnames(as.data.frame(p)) %>% head()
#> [1] "1.negc7" "2.negc7" "3.negc7" "4.negc7" "5.negc7" "6.negc7"
```

When I use `make.names` on the name of the response variables (the model object is _b14_), the underscores are preserved:

```r
sjstats::resp_var(b14)
#>     negc7   c12hour 
#> "neg_c_7" "c12hour" 

make.names(sjstats::resp_var(b14))
#> [1] "neg_c_7" "c12hour"
```

My problem is that I `grep()` the different response variables via their name, but of course "grepping" for `neg_c_7` as pattern in the column names won't work. That's the background of my question. I now did a workaround by removing underscores from the response variable name if the model is a multivariate response model - but I wonder if this already catches all exceptions?

**Comment by paul-buerkner** [comment]
Yes, underscores as well as dots in response variables names are removed by brms in order to not cause any problems in the internal handling as well as within Stan. Everything else is preserved.

**Comment by strengejacke** [comment]
Thanks!
