### ISSUE TITLE
`terms()` method for brmsfit-objects?

### ISSUE THREAD

**Issue by strengejacke** [paul-buerkner/brms#443]
As far as I can see, there's no `terms()` generic in _brms_ for _brmsfit_ objects. Is it possible / would it make sense to implement such a function, or are there good reasons why it's not available?

**Comment by paul-buerkner** [comment]
What should be the output of such a method?

**Comment by strengejacke** [comment]
Do you refer to my personal preferences, or in general? :-)
The most complete output would be as described here: `?terms.object`

I personally would like to get information about the attributes `term.labels`, `predvars`, `dataClasses`, `variables`. Maybe `response`.

Here's an example from `lme4`, but it's the same for R-base-models:

```r
fm1 <- lmer(Reaction ~ Days + (Days | Subject), sleepstudy)
terms(fm1)
#> Reaction ~ Days
#> attr(,"variables")
#> list(Reaction, Days)
#> attr(,"factors")
#>          Days
#> Reaction    0
#> Days        1
#> attr(,"term.labels")
#> [1] "Days"
#> attr(,"order")
#> [1] 1
#> attr(,"intercept")
#> [1] 1
#> attr(,"response")
#> [1] 1
#> attr(,".Environment")
#> <environment: R_GlobalEnv>
#> attr(,"predvars")
#> list(Reaction, Days)
```

**Comment by paul-buerkner** [comment]
To whatever you opinion is. brms cannot just return a single terms object because its formula object is not a single formula but (basically) a list of formulas (a `brmsformula` object). See `str(<brmsfit>$formula)` for details about the internal structure. I am hesitant to add a `terms` method as users will expect a single terms object to be returned but as described above that doesn't make sense for many models.

**Comment by strengejacke** [comment]
Yes, I thought that it would be difficult to implement a `terms()` method for brmsfit-objects that cover many, many different models. I think my basic intention was to get reliable variable names that match column names in the model frame, if users use expressions like `poly(term)` or `log(term)` in the model formula. I once had an issue with this with "normal" (lm/glm) models, that's why I needed `terms()`, which returns the clean variable names.

I haven't run into such issue with brms-models yet, but wanted to be sure to catch all possible exceptions. Maybe, if this ever occurs, I'll just write a quick workaround.
