### ISSUE TITLE
compare_ic with list-column of models returns "error in split_dots.."

### ISSUE THREAD

**Issue by keesterbrugge** [paul-buerkner/brms#445]
Hi Paul,

Thanks for this great package. 

I'm trying to use some of the ideas from hadley's book – r4ds – on how to work with large numbers of models, see [here](http://r4ds.had.co.nz/many-models.html). Basically, models are stored in dataframe columns. 

When I want to compare the models in the list-column using WAIC I get an error. I prefer not to input the models I want to compare as argument to `compare_ic`  one by one. 

As a reproducible code example I've used code from "statistical rethinking" exercise 6H1.

```r
library(rethinking)
library(tidyverse)
library(brms)


data(Howell1)
d <- Howell1
d$age <- (d$age - mean(d$age))/sd(d$age)
i <- sample(1:nrow(d),size=nrow(d)/2)
d1 <- d[ i , ]


formulas <- list(
  m1 = height ~ 1 + age,
  m2 = height ~ 1 + age + I(age^2))

df <- tibble( 
  name = names(formulas),
  formulas = formulas
  ) %>% 
  mutate(model = formulas %>% purrr::map( 
      .f = brm, 
      data = d1, 
      family = gaussian,
      prior = c(set_prior("normal(0, 100)", class = "Intercept"),
                set_prior("normal(0, 10)", class = "b"),
                set_prior("cauchy(0, 1)", class = "sigma")),
      chains = 2, iter = 2000, warmup = 1000, cores = 2)
    )

invoke(brms::waic, .x = df$model) # preferred method, but does not work. 
# returns error: Error in split_dots(x, ..., model_names = model_names) : argument "x" is missing, with no default

brms::waic(df$model[[1]], df$model[[2]]) # works as expected, but tedious

invoke(brms::waic, .x = list(df$model[[1]], df$model[[2]])) # tedious, correct values, but names are wrong. 

invoke(brms::waic, .x = list(m1 = df$model[[1]], m2 = df$model[[2]])) # tedious and does not work 
# returns error: Error in split_dots(x, ..., model_names = model_names) : argument "x" is missing, with no default


``` 
Am I doing something wrong?
If not, is there a workaround? 

Thanks again

**Comment by paul-buerkner** [comment]
You should use the `model_names` argument of `waic` whenever you are not passing the models to `waic` directly, since in this case, `brms` is not able to infer the model names correctly based on `base::substitute`.

**Comment by paul-buerkner** [comment]
With regard to the `x` is missing argument. This is because `waic` is generic with first argument `x`. You can write your own workaround as follows.

```
waic_wrapper <- function(...) {
  dots <- list(...)
  if (!"x" %in% names(dots)) {
    names(dots)[1] <- "x"
  }
  do.call(waic, dots)
}

**Comment by keesterbrugge** [comment]
thanks so much for your quick answer.

So for posterity, this is the code that makes it work as expected:

```r
waic_wrapper <- function(...) {
  dots <- list(...)
  if (!"x" %in% names(dots)) {
    names(dots)[1] <- "x"
  }
  do.call(brms::waic, dots)
}

invoke(waic_wrapper, .x = df$model, model_names = df$name)
```
