### ISSUE TITLE
AR(1) State Evolution

### ISSUE THREAD

**Issue by tbsmithca** [paul-buerkner/brms#446]
I am looking to implement a model like the one introduced in Section 3.3 of [http://www-stat.wharton.upenn.edu/~stjensen/papers/shanejensen.safetime2012.pdf](url). Essentially, I would like to fit a hierarchical model where the per group level coefficients evolve by an AR(1) process from year to year. How would I go about specifying this model with brms?

**Comment by paul-buerkner** [comment]
This is not yet possible, but see #403 for the issue discussion these features.
