### ISSUE TITLE
For zero-inflated / hurdle models, what does the output of fitted produce?

### ISSUE THREAD

**Issue by jwdink** [paul-buerkner/brms#447]
Are the values generated assuming we've "jumped" the hurdle? Or is the hurdle probability multiplied first? I couldn't find anything in the documentation on this -- apologies if I missed it.

**Comment by paul-buerkner** [comment]
Would you mind asking such questions on http://discourse.mc-stan.org/ using the brms tag? This will reach a much wider audience than a github issue.

**Comment by jwdink** [comment]
Sure thing, sorry about that.
