### ISSUE TITLE
custom link function

### ISSUE THREAD

**Issue by adder** [paul-buerkner/brms#449]
It's possible to define custom families, which is great!

I was wondering if it's possible to also define custom link functions?
I couldn't find an example of this.

In my case I want to use the `binomial()` family, but instead of the `logit` link function, I want to use a 'logit(log(logit())` link function.
Is this somehow possible?

Thanks!

**Comment by paul-buerkner** [comment]
You can use brms' non-linear syntax:

```
bform <- bf(y ~ log(logit(eta)), eta ~ ..., nl = TRUE)
brm(bform, family = binomial("logit"), ...)
```

Or, if your "outer" link was not an existing link function:

```
bform <- bf(y ~ logit(log(logit(eta))), eta ~ ..., nl = TRUE)
brm(bform, family = binomial("identity"), ...)
```

In the future, I recommend that all questions which are not bug reports or feature requests should go to the stan forums (http://discourse.mc-stan.org/) for greater visibility.

**Comment by adder** [comment]
Thanks for answering this!
I just want to say that you need the inverse link functions in the non-linear syntax.
in the example above this is `exp(1/(1 + exp(- eta))`

**Comment by paul-buerkner** [comment]
you are right of course. I just copied and pasted your code mindlessly ;-)

adder <notifications@github.com> schrieb am Do., 14. Juni 2018, 08:41:
