### ISSUE TITLE
Print updates during sampling

### ISSUE THREAD

**Issue by zachwarner** [paul-buerkner/brms#45]
Not an issue but a feature that would be nice: the ability to view sampling progress (as with the "refresh" option in a stan() call). Apologies if this is already implemented and I've just missed it.

**Comment by paul-buerkner** [comment]
I assume, you are talking about parallel sampling. If so, you can just use argument `cores` instead of `cluster` to use the rstan build in procedure including the refresh option. :-)

**Comment by zachwarner** [comment]
Indeed, I meant in parallel sampling. Thanks for the solution; that did the trick.

Is there anything in the documentation on this or any other distinctions between cores/cluster?

**Comment by paul-buerkner** [comment]
It is more or less an historical thing. When I implemented parallel sampling, rstan didn't have it as a build in functionality, just as code around calls to `stan`. The only reason, I still keep the `cluster` argument is that it allows to set the `cluster_type` (see `help(parallel::makeCluster)`), while rstan only allows `PSOCK`. Maybe, I will add functionality for other cluster types such as MPI in the future, but I am not sure yet.

**Comment by zachwarner** [comment]
That makes sense. Thanks again.
