### ISSUE TITLE
documentation about trials()

### ISSUE THREAD

**Issue by tjmahr** [paul-buerkner/brms#450]
I was copy-pasting some `stan_glmer()` code to run in brms to try it out, but noticed that the formula didn't look right. 

```
bf(cbind(Target, Distractor) ~ Condition, family = binomial)
#> Target ~ Condition 
#> Distractor ~ Condition 
```
I've used brms for multivariate models, so I recognized this as two outcomes modeled separately.

I checked the documentation (`?brmsformula`) and read:

> For families `binomial` and `zero_inflated_binomial`, [the formula]
> addition[ally] should contain a variable indicating the number of
> trials underlying each observation. In lme4 syntax, we may write for
> instance `cbind(success, n - success)`, which is equivalent to
> `success | trials(n)` in brms syntax. If the number of trials is
> constant across all observations, say `10`, we may also write `success
> | trials(10)`.

I check the journal article for an example, but the only reference is in footnote 3:

> In functions such as `glm` or `glmer`, the binomial response is
> typically passed as `cbind(success, failure)`. In brms, the equivalent
> syntax is `success | trials(success + failure)`.

I naively assumed that the normal way of doing binomials with `cbind()` would work in brms. I also interpreted the phrase "brms equivalent" to mean something like "alternative option" or "syntactic sugar". I probably won't be the only one who will fall into this trap. 

The documentation should add a line, **in bold**, saying that the `cbind()` idiom for binomial models does not work in brms because `cbind()` is reserved for multivariate models and that when translating binomial models with `cbind()`, the `trials()` form is required.

**Comment by paul-buerkner** [comment]
I agree and changed the doc accordingly :-)
