### ISSUE TITLE
Using brms to estimate variance components for ordinal measured response (not an issue)

### ISSUE THREAD

**Issue by bernard-liew** [paul-buerkner/brms#451]
Dear Paul,

I am doing a reliability study, using the methods of https://www.ncbi.nlm.nih.gov/pubmed/28505546. I have a question on using brms to estimate use of the variance components.

Background: I have 20 subjects, 2 fixed raters, 2 testing sessions, and 10 trials per sessions. my dependent variable is a continuous, interval, variable (scale 0-10) [ subjective pain rating]. So participants are asked to provide a whole number between 0-10, repeatedly. Sessions are nested within each subject-assessor combination, and trials nested within each session. I want to estimate the variance components, in itself, but also to calculate an ICC to produce a relative measure of inter-rater and inter-session reliability .

My model is:

brms_mod = brm (vas ~ RATER + 
                  (1|SUBJ) +
                  (1|SUBJ:SESSION) ,
                  data = df %>% filter (SIDE == "R"),
                family = cumulative("logit"),
                threshold = "equidistant")

My question is: in lmer, the inter-trial variance (level 1) is found in the residual. But in brms, no residual variance is produced. Am I right? Must I specify trials in the random effects (1|SUBJ:SESSION:TRIAL)? 

Also I know ICC can be derived from the variance components when the response is on a metric scale. Given my ordinal scale, can an ICC be derived from the variance components?

Thank you for all the help.

Kind regards,
Bernard

**Comment by paul-buerkner** [comment]
Hi Bernard, questions which are not realated to new features of bug reports should be asked on the Stan forums (http://discourse.mc-stan.org/) not on github.
