### ISSUE TITLE
waic in summary not working

### ISSUE THREAD

**Issue by cumuluss** [paul-buerkner/brms#454]
Hi Paul,
i was using the option waic=TRUE in the summary function, but after the update to brms version 2.3.1 it is not working (on R 3.5)
Thank you for any comments!
Best

**Comment by paul-buerkner** [comment]
In brms 2.3, I removed the ICs and similar stuff from the summary output, because I feel they are for themselves of limited practical use. I recommend using the `waic()` method directly to extract all the information related to the WAIC

**Comment by cumuluss** [comment]
Ok! Thank you!!!!
