### ISSUE TITLE
Possible bug for hurdle models that combine gr() and correlated random effects 

### ISSUE THREAD

**Issue by rpsychologist** [paul-buerkner/brms#457]
I think there is a bug in renaming the posterior samples when a hurdle model is fit with correlated random effects combined with gr(). At least, when there's more than 2 grouping levels.  

Here's a dummy model that reproduces the bug.
```
library(brms)
data(sleepstudy, package = "lme4")

# create 3 groups
sleepstudy$group <- rep(sample(0:2, 18, replace = TRUE), each = 10)

fit <- brm(bf(Reaction ~ 1 + (1 | 2 | gr(Subject, by = group)), 
              hu ~ 1 + (1 | 2 | gr(Subject, by = group))),
           data = sleepstudy, 
           family = "hurdle_lognormal",
           iter = 1)
```
Gives warning: 

> 4: In x$fit@sim$fnames_oi[change$pos] <- change$fnames :
>   number of items to replace is not a multiple of replacement length

If we extract the samples group2 will have no cor parameter.
```
ps <- posterior_samples(fit, pars = "cor_Subject")
names(ps)
```

> [1] "cor_Subject__Intercept:group0__hu_Intercept:group0" "cor_Subject__Intercept:group1__hu_Intercept:group1"

And the print method shows group0 twice instead.
```
Group-Level Effects: 
~Subject (Number of levels: 18) 
                                          Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
cor(Intercept:group0,hu_Intercept:group0)    -0.15      0.57    -0.97     0.87         38 1.11
cor(Intercept:group1,hu_Intercept:group1)     0.58      0.46    -0.78     0.99         36 1.13
cor(Intercept:group0,hu_Intercept:group0)    -0.15      0.57    -0.97     0.87         38 1.11
```

**Comment by paul-buerkner** [comment]
Thanks for reporting this issue! It should now be fixed on github.
