### ISSUE TITLE
Add support for MI with the R package mi

### ISSUE THREAD

**Issue by bharris-fs** [paul-buerkner/brms#462]
It's really nice that brms now works with mice.  would it be possible to add the ability to work with the mi package?  I could imagine either a native feature or an mi2mids and an mids2mi pair of functions to let the user convert the output of mi::mi() into a mids object and back, as needed.

**Comment by paul-buerkner** [comment]
I am hesitant to support too many packages internally, as this increases the number of packages I need to put under "Suggests". The necessary steps from the user side to get **mi** working with `brm_multiple` are really minor. Suppose `imp` is the output of `mi::mi()`. Then running the following will do:

```R
brm_multiple(data = mi::complete(imp), ...)
```

**Comment by paul-buerkner** [comment]
I agree and will add more explanation in the missing values vignette on how to handle the output of other packages.
