### ISSUE TITLE
Correlated posteriors in a multilevel binomial regression

### ISSUE THREAD

**Issue by MarinaGolivets** [paul-buerkner/brms#465]
Hello,

I am trying to analyze a dataset with predictors collected at two hierarchical levels. The higher level is determined by a plot geographical location and the lower level is determined by environmental heterogeneity within a plot so that the response variable is measured for each unique environmental condition within a plot. In most cases, plots were homogeneous and thus are represented by a single data point, whereas about 30% of plots contained 2-4 conditions and thus are represented by 2-4 data points.

I've been trying to fit a binomial regression with these data but I run into a problem that posterior distributions of several predictors are highly correlated. I suspect that the problem might be a small number of observations per group (i.e. number conditions per plot), though I am not completely sure. I get the same problem with simulated data and I can't recover the parameters:

`a <- rnorm(1000, 1, 3)`
`b <- rnorm(1000, 7, 5)`
`c <- rnorm( 1000, 0, 2)`
`d <- rnorm( 1300, 0, 1)`

`group <- sample(1:1000, 1300, replace = TRUE)`
`data <- data.frame(a = a, b = b, c = c, group = 1:1000) %>% right_join(data.frame(d = d, group = group))`
`x1 <- 7`
`x2 <- -2`
`data$y <- 5 + x1*data$a + x2*data$b + data$c + data$d`
`data$pr <- 1 / (1 + exp(-data$y))`
`data$y <- rbinom(1300, 1, data$pr`

`data$obs <- 1:1300`

`data[, c("a", "b")] <- data[, c("a", "b")] %>% mutate_all(funs(as.numeric(scale(.)))) `

`m.sim <- brm(y ~  a + b + (1|group) +(1|obs),
          data = data,
          family = bernoulli(),
          prior = c(prior("normal()", class = "b"),
            prior("student_t(3, 0, 10)", class = "sd")),
          chains = 1, cores = 1, thin = 2,  iter = 1000, warmup = 50,
          control = list(adapt_delta = .9, max_treedepth = 12))`

`pairs(m.sim)`
[pairs.pdf](https://github.com/paul-buerkner/brms/files/2156856/pairs.pdf)

I'd really appreciate any advice on how to proceed with this problem.

Marina

**Comment by paul-buerkner** [comment]
Github issues are resevered for bug reports and feature requests. Questions should be asked on http://discourse.mc-stan.org/.
