### ISSUE TITLE
Allow redeclaration of some variables in the Stan program

### ISSUE THREAD

**Issue by jpiironen** [paul-buerkner/brms#466]
This feature request stems from the epilogue of issue #459. So I would like to be able to explicitly specify how certain variables are declared in the Stan program. In particular I would like to be able to move ```b``` from parameters to transformed parameters using command like ```stanvar(scode = 'vector[K] b = b_raw*tau;', block='tparameters')```, in which case brms could ignore the default declaration and prior for this parameter. The purpose is to allow user to try out different parametrizations, some of which can be easier for NUTS.

**Comment by jpiironen** [comment]
By the way, are there any updates on this, have you had time to look at whether this is a light operation or something that would take a longer time? I don't want to push you at all, I'm simply curious about the rough time span, because I need to run some experiments in a near future and I was thinking whether I should wait this or write the relevant Stan-codes by hand. Thanks!

**Comment by paul-buerkner** [comment]
I have thought about. I think the only really application is redefinition of the regression parameters `b`. I already have an idea in mind how to make that possible internally without causing too much trouble. Let me try that out later on today.

**Comment by jpiironen** [comment]
Great, thanks for the update!

**Comment by jpiironen** [comment]
Seems to work as intended, thanks a lot! 

By the way, I was curious about a small detail in the generated Stan-code: the matrix ```X``` appears to be ```N-by-K```, whereas the centered matrix ```Xc``` is ```N-by-Kc``` where ```Kc = K-1```. What is reason for this, does ```X``` contain some extra column? I ran into this when I was trying to specify the ```b_raw``` to have length ```K``` and it did not work (your example was correct).

**Comment by paul-buerkner** [comment]
Within the Stan code, the intercept is removed from X and added separately to the linear predictor. Together with centering the columns of X around zero, this improves sampling efficiency for many models. The related Stan code can be found in the transformed parameters block.

**Comment by jpiironen** [comment]
Yeah, I was presuming it has something to do with the intercept but I still did not understand why ```X``` has the intercept column if it is never used? I'm probably missing something obvious here..

**Comment by paul-buerkner** [comment]
R creates X with an intercept column. Of course I could remove the intercept column beforehand but than the Stan code created by brms would be less self-contained.

**Comment by jpiironen** [comment]
Got it, thanks. :)

**Comment by jgellar** [comment]
@paul-buerkner , the code above doesn't seem to be working for me on the latest version of `brms`. I'm getting the following error:

```
SYNTAX ERROR, MESSAGE(S) FROM PARSER:
Duplicate declaration of variable, name=b; attempt to redeclare as vector in transformed parameter; previously declared as vector in parameter
 error in 'model6554bc41f7_file65542753337c' at line 28, column 23
  -------------------------------------------------
    26: }
    27: transformed parameters {
    28: vector[Kc] b = zb * tau;
                              ^
    29: }
  -------------------------------------------------
```

Could you look into this?

**Comment by paul-buerkner** [comment]
I probably removed this feature as it wasn't officially announced and I didn't like it, because it was too much special case coding. Sorry. :-(

**Comment by jgellar** [comment]
I understand. Perhaps there is another way for me to do what I'm trying to do?

I am fitting a multilevel model (`y ~ (1|age) + (1|education) + (1|region) + ...`), and I would like to set up a hyperprior across the variance components, saying that the standard errors of each of those random effects come from another (half-normal) distribution. I have figured out how to do that, but there were some sampling problems (a few divergent transitions) and I'd like to use a "Matt trick" on the hyperprior. This would require moving `sd_age`, `sd_education`, etc. from the parameters block to the transformed parameters block, which I don't think is currently possible without the solution you implemented above.

Do you have any other suggestions?

**Comment by paul-buerkner** [comment]
Brms will eventually support such priors natively. Until then you need to
adjust the stan code yourself. If you only change the prior you can feed
the stanfit object back into brms afterwards using the "empty" feature of
brm. You will need to install the github version of brms though for this
feature.

jgellar <notifications@github.com> schrieb am Fr., 24. Apr. 2020, 18:19:

**Comment by jgellar** [comment]
Thanks for the tip, I'll try it out.
