### ISSUE TITLE
Setting the prior of mue to uniform with boundaries results in error message

### ISSUE THREAD

**Issue by TehillaO** [paul-buerkner/brms#474]
Thank you for a great explanation on your package. I am currently trying to ‘go Bayesian’ with my meta-analysis but I am struggling with defining my prior distribution for the effect of mue. Simply, I have correlation coefficients as my effect sizes and I would like to set the prior for them (for the oveall effect of mue) as uniform with boundaries (-1, 1). This is how far I got:  

brm <- brm(yi | se(sei) ~ 1 + (1|Study_ID), prior = set_prior("uniform(-1,1)", lb = -1, ub = 1), data = df, iter = 5000, warmup = 2000, cores = 4).

I received the following warning message:
Error: The following priors do not correspond to any model parameter: 
<lower=-1,upper=1> b ~ uniform (-1,1)
 Function 'get_prior' might be helpful to you. 

Could you help me to figure out how to get it to work?

Thank you in advance for all your efforts!

**Comment by paul-buerkner** [comment]
Github issues are resevered for bug reports and feature requests. Questions should be asked on http://discourse.mc-stan.org/.
