### ISSUE TITLE
Predictions for bernoulli model

### ISSUE THREAD

**Issue by tmalsburg** [paul-buerkner/brms#479]
I fit a straight-forward two-level bernoulli model:

``` R
m <- brm(z ~ 1 + x + (x|group), d, family=bernoulli(), prior) 
```

When I calculate the predictions, I get this:

``` R
> head(predict(m))
     Estimate Est.Error Q2.5 Q97.5
[1,]  0.97525 0.1553817    1     1
[2,]  0.96125 0.1930227    0     1
[3,]  0.94375 0.2304327    0     1
[4,]  0.91525 0.2785441    0     1
[5,]  0.88475 0.3193633    0     1
[6,]  0.84575 0.3612334    0     1
```

The estimate is apparently the inverse logit of the linear predictor but the boundaries of the CrIs are zeros and ones and the estimate is sometimes outside the CrI.  Wouldn't it be better to have the estimate and the CrI on the same scale?

For comparison, this is what I get for `fitted(m)`:

``` R
      Estimate  Est.Error      Q2.5     Q97.5
[1,] 0.9735499 0.01896133 0.9245797 0.9944931
[2,] 0.9604719 0.02471656 0.8981335 0.9901808
[3,] 0.9421562 0.03136789 0.8650232 0.9829013
[4,] 0.9172673 0.03861247 0.8247004 0.9712271
[5,] 0.8845759 0.04592109 0.7777843 0.9536570
[6,] 0.8432393 0.05256839 0.7234426 0.9272927
```

**Comment by paul-buerkner** [comment]
Estimate and CI are on the same scale but, by default, estimate is the mean, which may well be smaller than the 2.5% quantile or greater than the 97.5% quantile in extreme situations. If you want to obtain the median rather the mean, go for `predict(m, robust = TRUE)`.

**Comment by paul-buerkner** [comment]
predict predicts new data (0 or 1s in your case) while fitted returns the probability of getting a one. To see this, try out `fitted(m, summary = FALSE)` and `predict(m, summary = FALSE)`

**Comment by tmalsburg** [comment]
No, `predict(m)` doesn't give me new data.  The data is 0s and 1s but the new data is probabilities (see first example at the top).  With `predict(m, robust=TRUE)` I do get 0s and 1s but their relative frequencies are wrong.  When the estimated probability is 0.5001, I should get close to 50% 0s and 50% 1s but that's not what I see. Instead I get 1s all the way.  I think there is something off here.  Either in there is a bug in the code or in the documentation.  The link for bernoulli is: P(y_i = 1) = logit^-1 (X_i β_i) but what `predict` is giving me is y_i = 1 when logit^-1 (X_i β_i) >= 0.5.

**Comment by paul-buerkner** [comment]
I am not sure. Have you tried calling predict with `summary = FALSE` as I suggested? you will see that most are 1s but not all depending on the probability. Remember that the probabilities are quite high on average as seen in the output of fitted.

**Comment by paul-buerkner** [comment]
If you still think it's a bug, can you send me a reproducible example?

**Comment by tmalsburg** [comment]
Example:
``` R
d <- tibble(z=rbinom(100, 1, 0.6))
m <- brm(z ~ 1, d, family=bernoulli())
summary(m)
predict(m, robust=TRUE)
```
results in

``` R
       Estimate Est.Error Q2.5 Q97.5
  [1,]        1         0    0     1
  [2,]        1         0    0     1
  [3,]        1         0    0     1
  [4,]        1         0    0     1
  [5,]        1         0    0     1
  [6,]        1         0    0     1
  [7,]        1         0    0     1
  [8,]        1         0    0     1
...
```

**Comment by tmalsburg** [comment]
Okay, I misunderstood the defaults.  With `summary = FALSE`, I do get what I expected (and comparing to `glm` my expectations were wrong.  Sorry for the noise.

**Comment by paul-buerkner** [comment]
That's correct behavior. Remember that when robust = TRUE, Estimate is the median, which will be either 0 or 1 in this case depending on whether we have more 0s or more 1s. If you look at

```
head(predict(m, summary=FALSE))
```

or

```
head(predict(m))
```

you see that predictions work correctly.

**Comment by paul-buerkner** [comment]
Ok glad we could sort this out! :-)
