### ISSUE TITLE
Ability to specify (Stan)  types and priors for nonlinear parameters

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [paul-buerkner/brms#48]
As far as I understand, the nonlinear parameters are supposed to be real scalars (or positve scalars for the RE standard deviations).

I recently stumbled upon a case where I would have loved to specify a custom type and size : I wanted to model the effect of some variable T as monotonous (i. e either constantly increasing or constantly decreasing). The conventional solution is to use the "ordinal factor" type of R and an orthogonal polynomial basis ; this is valid for "equally spaced" levels of the ordinal variable and gives difficut-to-interpret results.

An obvious solution is to factor the effect as the product of a "shape" parameter and a size parameter. This is trivially done in ```Stan``` by declaring the shape as a simplex and the size as a real. ```Stan``` runs on my example gave me reasonable (and enlightening !) answers.

As far as I understand, this cannot be done in ```brms```, for lack of ability : 

- to declare the shape as a simplex,

- to pass the size of the simplex as a parameter

- and to give it a"reasonable prior.

I feel that this could be a reasonable and useful addition to ```brms``` capabilities.

**Comment by paul-buerkner** [comment]
That sounds interesting! Would you mind giving a small Stan code example?

**Comment by EmmanuelCharpentier** [comment]
I'll send you something later today, maybe tonight...where do you want it sent ?
-'Emmanuel Charpentier


-------- Message d'origine --------
De : Paul-Christian Bürkner <notifications@github.com> 
Date : 29/02/2016  09:01  (GMT+01:00) 
À : paul-buerkner/brms <brms@noreply.github.com> 
Cc : EmmanuelCharpentier <emm.charpentier@free.fr> 
Objet : Re: [brms] Ability to specify (Stan)  types and priors for nonlinear
  parameters (#48) 

That sounds interesting! Would you mind giving a small Stan code example?

**Comment by paul-buerkner** [comment]
Thanks! Posting it here or sending it to my email-adress (see my [github profile](https://github.com/paul-buerkner)) would be great! :-)

**Comment by paul-buerkner** [comment]
A prototype version of 'monotonous' effects is now implemented and usable by writing `monotonous(<predictor>)` on the RHS of formula. The following things still need to be done:

- [ ] allow monotonous effects in random terms
- [ ] allow monotonous effects in non-linear models
- [ ] write unit tests
- [ ] document
