### ISSUE TITLE
Add argument to brm() for updating saved brmsfit objects

### ISSUE THREAD

**Issue by adder** [paul-buerkner/brms#480]
I frequently have to fit the same mode to different datasets.
To avoid having to compile the model each time I want to fit a new dataset.
I fit the model to a dataset and save it to disk. When I want to fit a new dataset, I load the previous model from disk and use `update` to fit the model on the new data.

 In issue #472 it was argued that is would be useful to have a `fit` argument in `brm` that automatically checks if there there is already a fitted model saved on disk and uses that instead of fitting the model again.

Inspired by #472, I would argue that it would also be useful to have an `update` argument (default FALSE). 
If `fit` is defined and `update = TRUE` it checks if there is already a models saved on disk, loads it and redo the fit (skipping the compilation step). This would probably just means that `update()` is called internally (with all arguments from the `brm()` call).
If the model is not saved on disk, compile the model, fit it and save it to disk.

If there is any other way to skip recompiling the same model over and over, this would offcourse also be fine :). 

cheerz

**Comment by paul-buerkner** [comment]
I think this would complicate things too much, as update already calls brm internally. Suppose, model `fit` is already saved on disc in file `fit.Rds`, then try out

```
fit <- brm(file = "fit.Rds")
fit_new <- update(fit, newdata  = <data>, recompile = FALSE, file = "fit_new.Rds")
```

**Comment by adder** [comment]
fair enough :)
A too complicated codebase only gives troubles in the future.
I'll do as suggested.
Thanks and I'm closing this.
