### ISSUE TITLE
Beginners question re multinomial model estimation

### ISSUE THREAD

**Issue by saptarshiguha** [paul-buerkner/brms#483]
Hello,
Suppose I have the following matrix y

```
      [,1] [,2] [,3] [,4] [,5] [,6] [,7]
 [1,]   86    5    4    3    6   21    7
 [2,]    10    0    3    1    0    0    0
 [3,]    1    2    0    3    3    2    1
 [4,]    1    2    1    0    0    0    1
 [5,]  400   15    2    8    6   10    4
...
```
the rows correspond to indivnidual users and the columns are observartions in each bucket (1 ... 7).  Note every user has a different number of 'trials'. The number of rows would be ~100K or so.

Consider the following model,

alpha ~ Exponential(1)
beta ~ Dirichlet(1)
thetai ~ Dirichlet(alpha*beta)
y'ith row  ~ Multinomial(thetai).

Is this possible using brms? I read somewhere that brms doesn't support multinomial models?

thanks much
Saptarshi

**Comment by paul-buerkner** [comment]
See https://github.com/paul-buerkner/brms/issues/338 for some discussion about multinomial models in brms.
