### ISSUE TITLE
Conditioned hypothesis

### ISSUE THREAD

**Issue by andymilne** [paul-buerkner/brms#484]
I don't think this currently possible in `brms` (I haven't found a way to do this). It would be useful to test a hypothesis conditioned on one or more values of one or more covariates. For example, in a model `Y ~ X1*X2`, it would be convenient to be able to test, for example, `"X1 > 0"` or `"X1 = 0"` when `X2 = a, b, c, ...`. Maybe using syntax similar to that in `marginal_effects()`; for example, `hypothesis(fit, "X1 > 0", condition = list(X2 = c(-1, -0.5, 0, 0.5, 1)))`?

**Comment by paul-buerkner** [comment]
If no interactions are modeled, the conditional probability is the same as the unconditional probability and so there is nothing to do. If interactions are modeled, then you have the corresponding interaction coefficients as well in your model and, if you know the coding of your interaction, can combine those to form the estimates you are interested in. Suppose X1 is continuous and X2 is a dummy (0, 1) and you are interested in the effect of X1 if X2 = 1. Then go for

```R
hypothesis(fit, "X1 + X1:X2 > 0")
```
