### ISSUE TITLE
zero/one formula by zero (one) inflated beta distribution, speed from C++ compiler, R²

### ISSUE THREAD

**Issue by Hallo951** [paul-buerkner/brms#486]
Hi,

I was looking for a r-package with which I can calculate a zero / one inflated beta regression including random effect. In my search, I found 3 package (gamlss, zoib, brms) that can do that, but only the brms package offers the full functionality (gamlss: currently no prediction function with random terms, zoib: very slow, no R², broken predictive function at zero / one inflated models (I could fix that, but I do not trust that), strange results). brms can as far as I understood it all I need, but I still have a few questions, because I do not know the Bayesian statistics well:

Question 1:
Is there a way to consider an individual formula in the calculation when using the zero_one_inflated_beta or zero_inflated_beta distribution? Currently the same formula is used for the zero / one inflated part as for the beta distribution part, or is that not true? I ask because I think that by not being able to consider separate zero / one formulas in the calculation, one does not get the "best" result.

Question 2:
Is there a way to speed up the C ++ compiler in the calculation? The calculation does not take so long but the compiler is very slow. Here is an example of a simple calculation with the zero inflated beta distribution (4 chains, 4 cores, Intel i7, 16 GB RAM, the rest is standard): compiling: 46s, computation: 21s.

Question 3:
What is the difference between the "bayes_R2" and the "loo_R2" and is that comparable to the normal R² from the simple linear models?

Question 4:
The WAIC is comparable to the AIC, true? What are the advantages of this LOO (which takes longer to calculate) compared to the WAIC (AIC) and there is something similar for brms like the AICc?

Question 5:
Can you tell me a few good settings, which in the Bayesia statistic provides a good compromise between accuracy and speed? I mean, how many chains, warmups (whatever they're good for) and iter, etc. should be taken.

Thank you...

**Comment by paul-buerkner** [comment]
As indicated in the brms readme, please ask questions on http://discourse.mc-stan.org/
