### ISSUE TITLE
i cant seem to set priors for my multivariate multilevel model.

### ISSUE THREAD

**Issue by KevinAckermans** [paul-buerkner/brms#487]
I have been trying to get these priors to work for a few hours now, so i figured i would ask.
When i try:

prior_viewbrics = c(set_prior("normal(16,11)",class = "b",coef= "ConditieText", resp = "sam”),
  set_prior(“normal(14,10)",class = "b",coef= "ConditieText", resp = "pres"),
  set_prior("normal(10,10)",class = "b",coef= "ConditieText", resp = "inf"), 
  set_prior("normal(19,17)",class = "b",coef= "ConditieVideo", resp = "sam”),
  set_prior(“normal(33,20)",class = "b",coef= "ConditieVideo", resp = "inf"),
  set_prior("normal(16,17)",class = "b",coef= "ConditieVideo", resp = "pres"))

i get this error:
Error in set_prior("normal(16,11)", class = "b", coef = "ConditieText",  : 
  formal argument "class" matched by multiple actual arguments

when i then omit all of the class arguments (which i would rather not, but he.. as long as it works)
The formal argument just moves to the next specifyer.

Error in set_prior("normal(16,11)", coef = "ConditieText", resp = "sam\342\200\235),\n  set_prior(\342\200\234normal(14,10)",  : 
  formal argument "coef" matched by multiple actual arguments

I have checked with get_prior and all of the "b" classes are without prior so i am kind of stuck at this moment.

                  prior     class          coef    group resp dpar nlpar bound
1                       Intercept                                             
2                               b                                             
3                lkj(1)    rescor                                             
4  student_t(3, 12, 15) Intercept                         inf                 
5                               b                         inf                 
6                               b  ConditieText           inf                 
7                               b ConditieVideo           inf                 
8                               b SchoolSchool1           inf                 
9   student_t(3, 0, 15)        sd                         inf                 
10                             sd               Conditie  inf                 
11                             sd     Intercept Conditie  inf                 
12  student_t(3, 0, 15)     sigma                         inf                 
13 student_t(3, 20, 15) Intercept                        pres                 
14                              b                        pres                 
15                              b  ConditieText          pres                 
16                              b ConditieVideo          pres                 
17                              b SchoolSchool1          pres                 
18  student_t(3, 0, 15)        sd                        pres                 
19                             sd               Conditie pres                 
20                             sd     Intercept Conditie pres                 
21  student_t(3, 0, 15)     sigma                        pres                 
22 student_t(3, 14, 10) Intercept                         sam                 
23                              b                         sam                 
24                              b  ConditieText           sam                 
25                              b ConditieVideo           sam                 
26                              b SchoolSchool1           sam                 
27  student_t(3, 0, 10)        sd                         sam                 
28                             sd               Conditie  sam                 
29                             sd     Intercept Conditie  sam                 
30  student_t(3, 0, 10)     sigma                         sam  

I do have a working model going, so that works fine ;)

  test_inf <- bf(inf~1 + Conditie + School + (1|p|Conditie))
  test_sam <- bf(sam~1 + Conditie + School + (1|q|Conditie))
  test_pres <- bf(pres~1 + Conditie + School + (1|r|Conditie))
  test_random <- brm(test_inf + test_sam + test_pres, data = MM_M2M3, warmup = 1500, iter = 2500, chains = 2, cores = 4, prior=prior_viewbrics, control = list(adapt_delta = 0.99, max_treedepth = 15))

**Comment by paul-buerkner** [comment]
As indicated in the brms readme, please ask questions on http://discourse.mc-stan.org/
