### ISSUE TITLE
resp argument when there is only one response

### ISSUE THREAD

**Issue by rubenarslan** [paul-buerkner/brms#488]
I'm fitting a few models where I want to call `loo_R2` on just one response. So, I was programmatically always limiting the `loo_R2` call to that response. However, some of the models don't have multiple responses (I added missing value imputation with brms as a step in model building).
So, if I fit a model with just one response, and call loo on it with a specified resp argument, I get a NA result because the function indiscriminately underscores the resp names and looks for it in sdata. I guess it'd be useful to add a check whether the specified resp is the only one, and if so, set resp to ''.

**Comment by paul-buerkner** [comment]
I think `resp` should just be ignored in univariate models. This shouldn't be too difficult to achieve.

**Comment by rubenarslan** [comment]
I'm now running some tests where I want to compare models with the same response parts, but some are univariate and some are multivariate. I haven't gotten far enough to say with certainty whether my problems are caused by the `resp` thing, but I think so.

**Comment by rubenarslan** [comment]
With `loo` I only get an inappropriate warning "response values of at least two models do not match. ", but with `loo_R2` I get `NA`. So, I think it's not possible to do model comparison of a univariate and a multivariate model with `loo_R2`. That's maybe a bigger difficulty?

**Comment by paul-buerkner** [comment]
Try out the new dev version of brms in which `resp` is now ignored throughout for univariate models.

**Comment by rubenarslan** [comment]
Thanks for the quick fix, it works. And nevermind the point about model comparison, I thought I could pass multiple models to `loo_R2` like I can with `loo`, but it's just further arguments that are passed down.
