### ISSUE TITLE
`update` and `add_ic` dont't commute. They should...

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [paul-buerkner/brms#490]
``` r
knitr::opts_chunk$set(cache=TRUE, echo=TRUE, results="markup")
library(brms)
```

The problem
===========

Apparently, :

-   `update` keeps the values computed for information indices (`waic`,
    `looic`, `marglik`) attached to a fit by `add_ic` ;
-   `add_ic` won’t overwrite exsting values for these information
    indices.

This can lead to ptentially caastrophic confusions if one tries to
compute these informational indices “once and for all” :

An example
==========

Let :

``` r
Data <- local({
    set.seed(1515) # Reproducibility
    G <- expand.grid(F1=c("A","B"),F2=c("X","Y"))
    S <- sample(nrow(G),20,replace=TRUE)
    R <- G[S,]
    row.names(R) <- 1:nrow(R)
    R <- within(R,
                Y <- (F1=="A") + (F2=="X")*0.5 + ((F1=="A")&(F2=="X"))*0.2 +
                    rnorm(nrow(R),-1,0.2))
    R
})
```

Compare :

Bad solution
------------

``` r
A1 <- brm(Y ~ F1*F2, data=Data,
          prior=prior(student_t(3,0,10), class="b"),
          save_all_pars = TRUE, sample_prior="yes",
          seed=1546, silent=TRUE, refresh=0)
A1 <- add_ic(A1, ic=c("waic", "loo", "marglik"), reloo=TRUE)
A2 <- update(A1, .~.-F1:F2, seed=4321)
A2 <- add_ic(A2, ic=c("waic", "loo", "marglik"), reloo=TRUE)
A3 <- update(A2, .~.-F2, seed=1234)
A3 <- add_ic(A3, ic=c("waic", "loo", "marglik"), reloo=TRUE)
A4 <- update(A2, .~.-F1, seed=5678)
A4 <- add_ic(A4, ic=c("waic", "loo", "marglik"), reloo=TRUE)
```

``` r
waic(A1,A2,A3,A4)
```

    ##          WAIC  SE
    ## A1      12.28 4.2
    ## A2      12.28 4.2
    ## A3      12.28 4.2
    ## A4      12.28 4.2
    ## A1 - A2  0.00 0.0
    ## A1 - A3  0.00 0.0
    ## A1 - A4  0.00 0.0
    ## A2 - A3  0.00 0.0
    ## A2 - A4  0.00 0.0
    ## A3 - A4  0.00 0.0

``` r
loo(A1,A2,A3,A4)
```

    ##         LOOIC   SE
    ## A1      12.75 4.33
    ## A2      12.75 4.33
    ## A3      12.75 4.33
    ## A4      12.75 4.33
    ## A1 - A2  0.00 0.00
    ## A1 - A3  0.00 0.00
    ## A1 - A4  0.00 0.00
    ## A2 - A3  0.00 0.00
    ## A2 - A4  0.00 0.00
    ## A3 - A4  0.00 0.00

``` r
bayes_factor(A1,A2)
```

    ## The estimated Bayes factor in favor of x1 over x2 is equal to: 1

``` r
bayes_factor(A2,A3)
```

    ## The estimated Bayes factor in favor of x1 over x2 is equal to: 1

``` r
bayes_factor(A2,A4)
```

    ## The estimated Bayes factor in favor of x1 over x2 is equal to: 1

which I don’t believe even for a femtosecond, and :

Better solution
---------------

``` r
B1 <- brm(Y ~ F1*F2, data=Data,
          prior=prior(student_t(3,0,10), class="b"),
          save_all_pars = TRUE, sample_prior="yes",
          seed=1546, silent=TRUE, refresh=0)
B2 <- update(B1, .~.-F1:F2, seed=4321)
B3 <- update(B2, .~.-F2, seed=1234)
B4 <- update(B2, .~.-F1, seed=5678)
B1 <- add_ic(B1, ic=c("waic", "loo", "marglik"), reloo=TRUE)
B2 <- add_ic(B2, ic=c("waic", "loo", "marglik"), reloo=TRUE)
B3 <- add_ic(B3, ic=c("waic", "loo", "marglik"), reloo=TRUE)
B4 <- add_ic(B4, ic=c("waic", "loo", "marglik"), reloo=TRUE)
```

``` r
waic(B1,B2,B3,B4)
```

    ##           WAIC   SE
    ## B1       12.28 4.20
    ## B2        9.83 4.13
    ## B3       24.04 5.11
    ## B4       42.74 3.57
    ## B1 - B2   2.45 1.05
    ## B1 - B3 -11.76 5.36
    ## B1 - B4 -30.45 4.49
    ## B2 - B3 -14.21 4.81
    ## B2 - B4 -32.90 4.63
    ## B3 - B4 -18.69 6.80

``` r
loo(B1,B2,B3,B4)
```

    ##          LOOIC   SE
    ## B1       12.75 4.33
    ## B2       10.04 4.19
    ## B3       24.18 5.16
    ## B4       42.82 3.59
    ## B1 - B2   2.70 1.09
    ## B1 - B3 -11.43 5.47
    ## B1 - B4 -30.08 4.57
    ## B2 - B3 -14.13 4.86
    ## B2 - B4 -32.78 4.68
    ## B3 - B4 -18.65 6.87

``` r
bayes_factor(B1,B2)
```

    ## The estimated Bayes factor in favor of x1 over x2 is equal to: 0.02677

``` r
bayes_factor(B2,B3)
```

    ## The estimated Bayes factor in favor of x1 over x2 is equal to: 11.26601

``` r
bayes_factor(B2,B4)
```

    ## The estimated Bayes factor in favor of x1 over x2 is equal to: 37064.24

wich I *can* believe until further examination…

For reference : Frequentists model comparisons.
-----------------------------------------------

``` r
drop1(lm(Y~F1*F2, data=Data), test="Chisq")
```

    ## Single term deletions
    ## 
    ## Model:
    ## Y ~ F1 * F2
    ##        Df Sum of Sq    RSS     AIC Pr(>Chi)
    ## <none>              1.2651 -47.211         
    ## F1:F2   1  0.016456 1.2816 -48.952   0.6112

``` r
drop1(lm(Y~F1+F2, data=Data), test="Chisq")
```

    ## Single term deletions
    ## 
    ## Model:
    ## Y ~ F1 + F2
    ##        Df Sum of Sq    RSS     AIC  Pr(>Chi)    
    ## <none>              1.2816 -48.952              
    ## F1      1    6.1444 7.4260 -15.815 3.072e-09 ***
    ## F2      1    1.5835 2.8651 -34.863 6.042e-05 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Possible solutions
==================

The most obvious workaround is that `update` *should* either update or
remove the computed values of information indices if they exist.

-   remove is easy, and has no bad side-effects. It forces the user to
    recompute thes evalues.

-   update is harder, and needs info not necessarily stored with the
    model (values of the optional arguments, for example).

Another helper would be to be able to *force* `add_ic` to recompute
values, event if the indices have already be computed.

**Comment by paul-buerkner** [comment]
Thanks! In the latest dev version of brms, fit indices will now be removed when updating a model. Updating those I think shouldn't be done automatically because it may require too much computation time on larger models.

Forcing `add_ic` to overwrite values is an important idea I think. I think we can implement this as part of #478 .
