### ISSUE TITLE
Issue with `add_ic(<model>, ic="loo", reloo=TRUE)` : fails if `reloo` effective.

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [paul-buerkner/brms#494]
``` r
knitr::opts_chunk$set(cache=TRUE, echo=TRUE)
```

Data (those are real, sparse and ill-distributed…).

``` r
foo <- structure(list(preop = c(84, 86, 86, 82.9, 86.4, 85, 93.8, 87.6, 95.1,
                                87.6, 90.7, 93.1, 90.7, 93.6, 91.9, 87.6,
                                85.8, 84.3, 84.4, 85.2, 88, 86.7, 82.4, 88.6,
                                86.5, 90.9, 87.4, 85.8, 87.9, 89.9),
                      simul = c(87.7, 90.6, 88.6, 87.3, 89.6, 89.7, 93.5,
                                91.1, 92.1, 94, 93, 91.2, 95.7, 96.9, 96.6,
                                89.9, 87.8, 90.1, 91.1, 89.2, 96.6, 92.5,
                                87.8, 94.4, 91.3, 96.4, 93.7, 90.5, 88.6,
                                93.5),
                      postop = c(86.5, 92.9, 90.1, 88.2, 91.9, 87.5, 91.6,
                                 94.3, 97.6, 89, 91.5, 93.1, 94.9, 96.3, 94,
                                 91.1, 86.6, 89.8, 91.1, 89.1, 92.3, 92.7,
                                 87.7, 96.5, 91.3, 97.4, 91.5, 92.6, 94.6,
                                 96.2),
                      Cis = structure(c(1L, 2L, 2L, 2L, 1L, 2L, 1L, 1L, 1L,
                                        1L, 1L, 1L, 1L, 1L, 1L, 1L, 2L, 2L,
                                        2L, 2L, 1L, 2L, 2L, 1L, 2L, 1L, 2L,
                                        1L, 1L, 1L),
                                      .Label = c("FALSE", "TRUE"),
                                      class = "factor")),
                 class = "data.frame", row.names = c(NA, -30L))
library(brms)
options(mc.cores = parallel::detectCores())
rstan::rstan_options(auto_write = TRUE)
theme_set(theme_classic())
```

This GAM model isn’t especially reasonable, given the sparsity of the
data, but my point isn’t here
:

``` r
M1 <- brm(bf(postop~t2(preop,simul, by=Cis), family=gaussian, sigma~Cis),
               data=foo,
          prior=c(prior(student_t(3,0,10), class="b"),
                  prior(student_t(3,0,10), class="sds")),
          control=list(adapt_delta=1-1e-3),
          save_all_pars=TRUE, sample_prior=TRUE,
          seed=1812, silent=TRUE, refresh=0)
```

    ## Compiling the C++ model

    ## Start sampling

The problem arises when I want to compute the information criteria :

``` r
## Unproblematic :
M1 <- add_ic(M1, ic=c("waic","R2","marglik"))
```

    ## Iteration: 1
    ## Iteration: 2
    ## Iteration: 3
    ## Iteration: 4
    ## Iteration: 5
    ## Iteration: 6
    ## Iteration: 7
    ## Iteration: 8

``` r
## Fails :
M1 <- add_ic(M1, ic="loo", reloo=TRUE)
```

    ## 4 problematic observation(s) found.
    ## The model will be refit 4 times.

    ## 
    ## Fitting model 1 out of 4 (leaving out observation 1)

    ## Start sampling

    ## Error in rep(TRUE, ncol(object$X)): argument 'times' incorrect

Therefore, no “correct” loo, hence warnings when used later.

I’m stuck…

**Comment by paul-buerkner** [comment]
Let me see what is going wrong.

**Comment by paul-buerkner** [comment]
It should be fixed now. The problem was that `mgcv::PredictMat` is not type stable when passing data containing only a single data point.

**Comment by EmmanuelCharpentier** [comment]
> It should be fixed now. 

Should I install the development version ? Or should I clone your Git and work on a specialized branch ?

> The problem was that mgcv::PredictMat is not type stable when passing data containing only a single data point.

ISTR to have had to use the `drop=FALSE` argument of the `]` (indexing) operator a couple times to avoid this kind of problem. A vector and a  single-row or sngle-column matrix often behave quite differently, and the indexing operator *drops* the "unused dimensions" *by **default***...

**Comment by paul-buerkner** [comment]
Just install the dev version.

Yeah that automatic dropping of dimensions is one of the few things that annoy be about R. About 30%+ of the bugs in brms are due do some automatic dropping of dimensions either in brms itself or in packages brms depends on.

**Comment by EmmanuelCharpentier** [comment]
Ahem... Probably unrelated (hence another (minor) issue) but... !

To my example, I add : 
```

M2 <- brm(bf(postop~s(preop, by=Cis), family=gaussian, sigma~Cis),
               data=foo,
          prior=c(prior(student_t(3,0,10), class="b"),
                  prior(student_t(3,0,10), class="sds")),
          control=list(adapt_delta=1-1e-3),
          save_all_pars=TRUE, sample_prior=TRUE,
          seed=1812, silent=TRUE, refresh=0)
M2 <- add_ic(M2, ic=c("waic","R2","marglik"))
M2 <- add_ic(M2, ic="loo", reloo=TRUE)
```

Then I try : 

```
> model_weights(M1, M2, weights="loo")
       M1        M2 
0.1841742 0.8158258 
```

OK

```
> model_weights(M1, M2, weights="loo2")
      M1       M2 
0.269501 0.730499 
Warning messages:
1: Some Pareto k diagnostic values are too high. See help('pareto-k-diagnostic') for details.
 
2: Some Pareto k diagnostic values are too high. See help('pareto-k-diagnostic') for details.
```

Why ?

**Comment by paul-buerkner** [comment]
`loo2` does stacking of posterior predictive distributions, which is something different than `loo`. Hence it doesn't use the stored `loo` object.

**Comment by paul-buerkner** [comment]
I am not aware of `loo_model_weights()` (the underlying function) being able to take a reloo argument.

**Comment by EmmanuelCharpentier** [comment]
from the doc of the underlying function in `lii` : 

> Currently the ‘loo_model_weights’ function is not implemented to be used with results from K-fold CV, 
but you can still obtain weights using K-fold CV results by calling the ‘stacking_weights’ function directly.

Wouldn't that mean we would have o implement something like this ? Or that we should bug `loo`'s authors to this end ?

**Comment by paul-buerkner** [comment]
Maybe ask a question about this on http://discourse.mc-stan.org/
