### ISSUE TITLE
pp_check for multi-factorial designs

### ISSUE THREAD

**Issue by Anna-LenaSchubert** [paul-buerkner/brms#495]
I want to use the pp_check function to compare posterior predictives to original data, but I can only do so for a single factor if I select "bars_grouped". I have a 2 x 2 x 2 design and would love to check model fit separately for each of these eight conditions, e.g. group_by = c("A", "B", "C"). 

Is there some way to achieve that in the current version in brms? If not, I'd love to see it in a future version.

**Comment by paul-buerkner** [comment]
`pp_check` has a `newdata` argument which you can use to pass data of a single condition.

If you are unsure whether your issue is a questions or feature request (or bug report), please post it first on http://discourse.mc-stan.org/ for greater visibility.
