### ISSUE TITLE
Feature request: Error Earlier when Models Aren't Comparable

### ISSUE THREAD

**Issue by billdenney** [paul-buerkner/brms#498]
Moved from stan-dev/loo#89

I just tried to compare two `brms` models which accidentally had different numbers of observations due to a predictor being `NA`.

When using `loo` on the models, it computed everything for both models then gave the error "Models don't have the same number of data points".  It would be helpful if this error were tested for before doing the calculations so that the errors came immediately rather than after multiple, potentially long, calculations.

**Comment by paul-buerkner** [comment]
Let me see whether we can check that earlier.

**Comment by paul-buerkner** [comment]
Should be fixed now in the dev version of brms from github.

**Comment by billdenney** [comment]
Thank you!
