### ISSUE TITLE
Crash when doing serial updates

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [paul-buerkner/brms#499]
FYI : I've got a nice crash of the R process when updating a set of models (same structure, ten different independent variables on the same set of the same independent variables), GAM model, data sparse and ill-distributed. Head of the error message : 
```
OpenBLAS : Program will terminate because you tried to start too many threads.

 *** caught segfault ***
address 0x101, cause 'memory not mapped'
OpenBLAS : Program will terminate because you tried to start too many threads.
OpenBLAS : Program will terminate because you tried to start too many threads.

Traceback:
 1: smooth.construct.tp.smooth.spec(object, dk$data, dk$knots)
 2: smooth.construct(object, dk$data, dk$knots)
 3: smooth.construct3(object, data, knots)
 4: mgcv::smoothCon(eval2(smterms[i]), data = data, knots = knots,     absorb.cons = TRUE)
 5: data_fe(bterms, data)
 6: is.data.frame(x)
 7: colnames(data_fe(bterms, data)$X)
 8: change_fe(x, data, pars, scode = scode)
 9: change_effects.btl(x$dpars[[dp]], ...)
10: change_effects(x$dpars[[dp]], ...)
11: change_effects.brmsterms(bterms, data = data, pars = pars, scode = stancode(x))
12: change_effects(bterms, data = data, pars = pars, scode = stancode(x))
13: rename_pars(x)
```
Then a dump of the data, which comprised the former model with its 8000 samples and totally clogged ESS. I had to kill the R process...

What do you need to diagnose the problem ?

**Comment by paul-buerkner** [comment]
Not sure if I can debug that at all, but a minimally reproducible example would increase the chances.

**Comment by EmmanuelCharpentier** [comment]
Private answer set (contains real data...).

**Comment by paul-buerkner** [comment]
Thanks for sending a reproducible example. Unfortunately, it works just fine on my machine. Based on the error message above it seems your problem has somthing to do with the BLAS you are using on your machine (what kind of system are you using btw?). It is very unlikely to be an issue related to brms.

**Comment by EmmanuelCharpentier** [comment]
Indeed, it seems that you are right : using Sage's R (still at 3.4.4, but we're working on this...), the whole things ends up in about 8 minutes...

Blas/lapack : According to `sessionInfo()` : 

System's R:
```
Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.3.2.so
```
On my Debian system, which has History (yes, capital H...), this would come from `libblas3`, `libatlas3-base` and `libopenblas`. All three are installed... (History, I tell you : I'm fiddling with Linux since 1992 and Debian since 2002, IIRC (ISTR that Debian was "potato" at the time...). My systems have had ample opportunity to accumulate cruft...).

Do you have advice ?

Using Sage's R (3.4.4) (which installs its own libraries (long story again...)) : 
```
Matrix products: default
BLAS/LAPACK:
/usr/local/sage-8/local/lib/libopenblas_haswell-r0.2.20.so
```

**Comment by paul-buerkner** [comment]
I have absolutely no idea...

Maybe you should ask this question on a more technical R forum.

**Comment by paul-buerkner** [comment]
Closing this as it is not related to brms.
