### ISSUE TITLE
using me() yields different results than I expected

### ISSUE THREAD

**Issue by HenrikEckermann** [paul-buerkner/brms#504]
Hi Paul,

I guess there is no issue but it might be. Also, in case others run into a similar question I decided to open an issue here.

I want to fit the model that corresponds to _Statistical Rethinking_ chapter 14, problem H1. This is a "toy" issue where there is a count response (_MATINGS_) and _AGE_ as predictor. One should first fit a model using the given predictor and outcome. After that one should assume that AGE has a constant measurement error (se = 5) and refit the same model with that information.  Richard McElreath fits the following model in the book:

```{r}
library(rethinking)
data(elephants)
df <- elephants

m14H1_2 <- map2stan(
    alist(
        MATINGS ~ dpois(lambda),
        log(lambda) <- a + bA*AGE_est[i],
        AGE ~ dnorm(AGE_est , 5),
        a ~ dnorm(0, 10),
        bA ~ dnorm(0, 1)
    ),
    start=list(AGE_est=df$AGE),
    data=df , chains=4 , WAIC=FALSE )
precis(m14H1_2)
```

Using `brm()` (version brms 2.4), I tried the regular intercept formula `MATINGS ~ 1 + me(AGE, 5)`, which did not yield the same results compared to the above model output. I noticed [issue #114 ](https://github.com/paul-buerkner/brms/issues/114) where you wrote one could use "0 + intercept..." as well. I tried both ways and thought that the following model should yield the same results as Richards model but it does not:

```{r}
detach(package:rethinking, unload = TRUE)
library(brms)

fit.se <- 
    brm(
      family = poisson(),
      MATINGS ~ 0 + intercept + me(AGE, 5),
      prior = c(
        set_prior("normal(0, 10)", class = "b", coef = "intercept"),
        set_prior("normal(0, 1)", class = "b", coef = "meAGE5")
      ),data = df, save_mevars = T
)
fixef(fit.se)
```

I want to understand why the results differ. Could you give me a hint what I am missing here and possibly how to specify the equivalent model using `brm()` ?

Thanks!

**Comment by paul-buerkner** [comment]
The rethinking model misses the hierarchical prior on the latent variable `Age_est`. In other words, it does account for the fact the we have measurement error in the sense that it increases uncertainty in the regression coefficient of Age, but it doesn't try to "correct" for measurement error. The letter is what the brms model does as well, by setting a `Age_est ~ normal(mean_Age, sd_Age)` prior with the parameters being estimated from the data.

**Comment by HenrikEckermann** [comment]
Thanks for the quick clarification!

**Comment by paul-buerkner** [comment]
You are welcome. Going forward, please ask questions on http://discourse.mc-stan.org/ instead of in the form of github issues if you are unsure whether it is a bug report or more of a question.
