### ISSUE TITLE
Feature request: BRMS formula to LaTeX convenience function

### ISSUE THREAD

**Issue by jackobailey** [paul-buerkner/brms#505]
Although I recognise that this might not be a priority, it would be useful to have a function that takes a brms formula and outputs the equivalent specification as latex code ready for publications.

**Comment by paul-buerkner** [comment]
Is it really much more effort for users than just copy and pasting the output of `print.brmsformula` and replacing `~` by `\sim`?

**Comment by jackobailey** [comment]
Looks like I've jumped the gun! Probably not.

**Comment by paul-buerkner** [comment]
I think this can be closed as there is really not much to do to make a latex equation out of a formula.
