### ISSUE TITLE
Regression coefficients for survival families

### ISSUE THREAD

**Issue by richardbeare** [paul-buerkner/brms#506]
Hi,
I suspect this is a silly question, and I've missed something in the documentation. I'm exploring some models which predict a time based on a mix of continuous and categorical variables. If the model is fitted with default Gaussian families the coefficients can be directly interpreted as mean time increments. With different distribution families the interpretation requires transform of the coefficient. Are there helper functions hidden away to assist?

**Comment by paul-buerkner** [comment]
General questions should rather be asked http://discourse.mc-stan.org/ instead of in github issues. The latter is reserved for feature issues or (potential) bug reports
