### ISSUE TITLE
handle 0% encounter 

### ISSUE THREAD

**Issue by mcfran** [paul-buerkner/brms#507]
Hi,
I am trying to develop glmm hurdle and zeroinflated models to predict fish catch. In my datasets, some years have no encounters as no fish were detected which create some convergence issues, high estimate, est.Error... I was able to run some models using brms but I still have high estimate values for the years with no catch. I  saw that brms can handle missing data but did brms can handle 0% encounter and then predict the catch for each year? if yes, what is the best way to write the code?
Thank you,
MC

**Comment by paul-buerkner** [comment]
Questions should rather be asked on https://discourse.mc-stan.org/ while github issues are reserved for bug reports and feature requests.
