### ISSUE TITLE
Minor issue : `silent=TRUE` should entail `open_progress=FALSE`

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [paul-buerkner/brms#508]
Use case : a set of identical models applied to various datasets, and updates of the models (implied by `add_ic(..., reloo=TRUE)`.

When ran by `knitr` under `AUCTeX`, every fit (`brm(...)`) or `update` of a model entailed the opening of a new browser windows displaying (the start of) the "progress messages" that Stan insists to put out. I *think* that this depends on te setting of `interactive()` which is not the same when run under `AUCTeX`.

[ Curiosity : what happens when ran under RStudio ? ]

This minor point has been an excruciating pain in my ... posterior (yes...) until I dived into `rstan`'s documentation went to `stan-package`, then to `sampling` and got enlightened.

If it is too much of a bother to add logic to this effect to the code, could the existence of `open_progress` be mentioned (explained) in the docs for `brm` and`update` ?

**Comment by paul-buerkner** [comment]
Isn't this rather an issue of `rstan`?

**Comment by EmmanuelCharpentier** [comment]
I see your point. Min is that `silent` is not an `rstan` option, and that using it entails setting `show_messages=FALSE`, i.e. `silent` acts as a replacement for `rstan` options. And the name you choose for it conveys the same main idea (i.e. "Stan, shut the f*ck up ! Or else...")...

But my reading of the docs may be naive... In any case, pointing the the relevant `rstan` options in the doc may be useful.

**Comment by paul-buerkner** [comment]
Fair enough. It's document now :-)
