### ISSUE TITLE
kfold stratified

### ISSUE THREAD

**Issue by rubenarslan** [paul-buerkner/brms#510]
As discussed per mail, it would be great, if `kfold` in brms allowed something similar to the `folds` argument in rstanarm, which allows us to ensure that dependent data points end up in the same fold (when that is desired).

A simple way to implement this with the present arguments would be to allow the simultaneous specification of both `K` and `group`. When a group variable is given, `K` stratified folds would be formed based on that group.  Currently, `K` is ignored, when specifying `group`.

For other, more complex ways of defining folds (e.g., for timeseries), it might be useful to allow for a more general user-defined `folds` argument as in rstanarm that simply allows us to assign rows to a fold.

**Comment by paul-buerkner** [comment]
Thanks for opening this issue! That makes sense to me.

**Comment by paul-buerkner** [comment]
In the latest github version, you should now have all the K-fold options you have ever dreamed of ;-)

**Comment by rubenarslan** [comment]
This just to confirm that I could use stratified kfold now, and it works exactly as expected. Thank you!
