### ISSUE TITLE
Weird warnings when no RE/ME/AC variables

### ISSUE THREAD

**Issue by burchill** [paul-buerkner/brms#511]
I was running an exgaussian with the formula `RT ~ SimulatedCondition` as a simple model in `brm`, and I kept getting the following warnings:

```
Warning messages:
1: In is.na(x) : is.na() applied to non-(list or vector) of type 'NULL'
2: In is.na(x) : is.na() applied to non-(list or vector) of type 'NULL'
3: In is.na(x) : is.na() applied to non-(list or vector) of type 'NULL'
4: In is.na(x) : is.na() applied to non-(list or vector) of type 'NULL'
5: In is.na(x) : is.na() applied to non-(list or vector) of type 'NULL'
```

After some snooping through the code, I realized that the problem originates in `.get_group_vars`, specifically the line: `sort(unique(out))`.  In my case, this was because a few lines above it, (`out <- c(get_re_groups(x), get_me_groups(x), get_ac_groups(x))`) returned a `NULL` value for `out` (as each of the `get_...` functions returned `NULL`. And trying to do `sort(unique(out))` returns the aforementioned warning.

Can this be avoided / turned into an informative warning if it needs to stay in? Also, is this (and `get_group_vars` returning a `NULL` value in `update_data`) a problem?  Or does the code work fine regardless?

Here's reproducible code:

```r
n = 1000
df <- data.frame(x = runif(n,1,10))
df$y <- df$x*5 + rnorm(n) + 30
m <- brm(y ~ x,
         data = df,
         family = gaussian(link = "identity"))
```

I'm using `brms_2.4.0` on R `3.3.1`.

**Comment by paul-buerkner** [comment]
That's because you are using an outdated version of R. I suggest updating R to the latest version.

**Comment by burchill** [comment]
Yep, you're right--I get the same warnings on `3.4.4` but not `3.5.0`.
