### ISSUE TITLE
i used brms doing bayes multinomial logistic regression, but have some issues.

### ISSUE THREAD

**Issue by psychowzx** [paul-buerkner/brms#516]
I am a new R user and a new brms user. I want to use it for doing  bayes multinomial logistic regression.
This is my code:
    library(brms)
    setwd("E:\\li\\gamblers-ofc\\revision_wzx_3rd")
    LR=read.csv("L-R.csv")
    fit1=brm(formula=Right~Left + age,family="categorical",data=LR,prior=c(set_prior("normal(0,10)")))

and then, it always report errors:
Warning messages:
1: In is.na(x) : is.na() applied to non-(list or vector) of type 'NULL'
2: In is.na(x) : is.na() applied to non-(list or vector) of type 'NULL'
3: In is.na(x) : is.na() applied to non-(list or vector) of type 'NULL'
4: In is.na(x) : is.na() applied to non-(list or vector) of type 'NULL'
5: In is.na(x) : is.na() applied to non-(list or vector) of type 'NULL'

maybe this is a very sample question, i guess this was caused by the wrong data structure.
my data is .sav file, such as
ID            TypeL     TypeR
1                first           one
2              second     two
typeR is dependent variables, and TypeL is predictor. this arrangement is wrong?

**Comment by paul-buerkner** [comment]
You don't need to worry about the warnings, but if you want to get rid of them, you have 2 options. 

1) Update R to the latest release version (3.5.1)
2) Install the dev version of brms for github via 

```R
if (!requireNamespace("devtools")) {
  install.packages("devtools")
}
devtools::install_github("paul-buerkner/brms")
```

**Comment by paul-buerkner** [comment]
I am sorry, I am not sure what you mean. This rather seems like a question than a bug report to me and so I would recommend asking the question on https://discourse.mc-stan.org/. Please don't forget to include code and describe exactly where your problem is.
