### ISSUE TITLE
pars option for fixef, ranef, and coef?

### ISSUE THREAD

**Issue by peterphalen** [paul-buerkner/brms#520]
Hello! 

I'm trying to run calculations on the posterior samples of the random effects of a large varying-slope / varying-intercept model. For bureaucratic reasons I'm currently forced to use `brms` on a government computer that has limited RAM and freezes up when it has to manipulate matrices that are too large. So, calling `coef(summary=FALSE)` on the full model is not practical, but I think the machine could handle `coef(summary=FALSE, pars="smaller_set_of_coefficients").`

Would it be possible/easy to add a `pars `option to the `fixef()`, `ranef()`, and `coef()` functions? 

Thank you so much!
Peter

**Comment by paul-buerkner** [comment]
I like this idea. In the new github version of brms, you can now select coefficients via `pars`.
