### ISSUE TITLE
applying model_weights and posterior_average to a list of models/list-column of models

### ISSUE THREAD

**Issue by tmerkling** [paul-buerkner/brms#521]
Hi Paul,

Thanks for this very neat package!

I'm trying to do model selection on a set of binomial GLMMs. I would like to compare the model weights using the `model_weights` function, select a subset of the best fitting models and then apply the `posterior_average` and `posterior_summary` functions to calculate averaged parameters across the best models (similar to the model averaging approach implemented in `MuMIn`).
Because I have quite a few models it would be useful if those functions could be applied to lists of models instead of having to write them down one by one. However, I have not found a way to do that, is there one?
Maybe this could be implemented in a similar way as for `waic` in  #445 ?

Thanks for your help,
Thomas

**Comment by paul-buerkner** [comment]
Try out 

```R
args <- c(model_list, weights = "waic")
do.call(model_weights, args)
```

Similar to what I described in #445.
