### ISSUE TITLE
get_prior() and modeling sigma

### ISSUE THREAD

**Issue by ASKurz** [paul-buerkner/brms#523]
Consider the following distributional model:

```
library(tidyverse)
library(brms)

set.seed(100)
d <-
  tibble(x = rep(0:1, each = 100)) %>% 
  mutate(y = rnorm(n = n(), mean = 100, sd = 10 + x * 10))

fit <-
  brm(data = d, 
      family = gaussian,
      bf(y ~ 1, sigma ~ 1 + x))
```

If I check what the default priors are with `get_prior(data = d, formula = bf(y ~ 1, sigma ~ 1 + x))`, there’s no mention of the prior used for `b_sigma_x`. Though there is a row in the returned data frame, the corresponding slot in the `prior` column is blank. Shouldn't there be a distribution, there?

**Comment by paul-buerkner** [comment]
That's because there is no proper prior by default. If you want one, you need to specify it.

**Comment by ASKurz** [comment]
Is the default prior just uniform, then? If so, what bounds are used?

**Comment by paul-buerkner** [comment]
It is uniform on the log-scale, but since we are using the log-link, the boundary on the predicted values of sigma is [0, \infty).

**Comment by ASKurz** [comment]
Thanks for the clarification, Paul.
