### ISSUE TITLE
Allow for different priors on different intercepts for ordinal regression in brms 

### ISSUE THREAD

**Issue by zacharyhorne** [paul-buerkner/brms#524]
Allow brms to set different priors on the different intercepts of an ordinal model. For instance, I’m trying to tell brms that the most likely response is the 5th and 6th likert scale point but I only seem to be able to increase the probability of the first or last likert scale point.

**Comment by paul-buerkner** [comment]
Specifying separate priors on thresholds in ordinal models should now be possible. See the output of `get_prior` for details

**Comment by paul-buerkner** [comment]
Closing this issue.

**Comment by signekb** [comment]
Is this feature (specifying separate priors on thresholds) still only available in the GitHub version of brms?

**Comment by paul-buerkner** [comment]
This should be available on CRAN
