### ISSUE TITLE
Passing 'includes' and 'allow_undefined' to stan_model()

### ISSUE THREAD

**Issue by plogacev** [paul-buerkner/brms#525]
Is it possible to make make_stancode() forward the parameters 'includes' and 'allow_undefined' to stan_model()? This would allow including C++ code in non-linear models.

**Comment by paul-buerkner** [comment]
It's not, but I will make this possible

**Comment by plogacev** [comment]
That would be great! Thanks in advance!

**Comment by paul-buerkner** [comment]
You can now pass `stan_model_args` as a list to `brm` in the github version of brms. 
Please note that `brm` and not `make_stancode` actually calls `rstan::stan_model`.
