### ISSUE TITLE
A good one : brm can't fit an intercept-only model...

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [paul-buerkner/brms#529]
These intercept-only models aren't interesting by themselves (there are usually more streamlined ways to estimate a mean...), but are an interesting apex of an hypercube of models of the same data.

Contemplate : 
```
quux <- brm(Douleur_1an ~ 1, family=bernoulli,
           data=Data,
           save_all_pars=TRUE, sample_prior="yes",
           seed=1954, silent=TRUE, refresh=-1, open_progress=FALSE)
```
which gives
```
> quux <- brm(Douleur_1an ~ 1, family=bernoulli,
+            data=Data,
+            save_all_pars=TRUE, sample_prior="yes",
+            seed=1954, silent=TRUE, refresh=-1, open_progress=FALSE)
Error in `$<-.data.frame`(`*tmp*`, "bounds", value = "") : 
  replacement has 1 row, data has 0
```
BTW, this : 
```
foo <- brm(Douleur_1an ~ LOE_Init + Technique, family=bernoulli,
           data=Data,
           prior=prior(student_t(3,0,10), class="b"),
           save_all_pars=TRUE, sample_prior="yes",
           seed=1954, silent=TRUE, refresh=-1, open_progress=FALSE)
```
fits perfectly.

I think that this yet again an instance of the `[...,drop=FALSE]` curse...

Data not being mine, I can't join them (I can send them to a private address if necessary...).

**Comment by paul-buerkner** [comment]
Indeed that's a good one. It appeared only if one set `sample_prior = "yes"` but there were actually
no priors to sample from (the prior of the temporary intercept is ignored even if `sample_prior = "yes"`).
It should be fixed now.
