### ISSUE TITLE
Improve efficiency of Stan code for models specified with multivariate formula syntax

### ISSUE THREAD

**Issue by paul-buerkner** [paul-buerkner/brms#53]
Currently, multivariate linear, zero-inflated and hurdle as well as categorical models are specified via multivariate formula syntax similar to how `MCMCglmm` does it. This basically leads to larger design matrices containing many zeros. At first I thought that is doesn't do too much harm (except for requiring more RAM), but recently I realized that it may decrease sampling speed noticeably as it causes many unnecessary gradient computations.  The obvious solution of doing sparse matrix multiplication doesn't really improve things (at least in the current Stan implementation), so that the Stan code itself needs to be changed.

**Comment by rubenarslan** [comment]
+1

**Comment by paul-buerkner** [comment]
This will likely be solved as a by-product of #91.

**Comment by paul-buerkner** [comment]
Closed via PR #109.
