### ISSUE TITLE
Evidence ratio/hypothesis based on posterior predictions

### ISSUE THREAD

**Issue by benwhalley** [paul-buerkner/brms#530]
When we have a model with multiple predictors the quantity of interest is sometimes easiest to see via `brms::posterior_linpred` or `tidybayes::add_fitted_samples`. i.e. create a new data frame with predictors at combinations of interest, and then inspect the posterior predictions for these.

It's also possible calculate posterior predicted differences, and use it with brms::hypothesis() to get the evidence ratio e.g. for  grpA-grpB < 0. However it's not possible to get the BF for a point hypothesis this way. For example:

```{r}
sillyexample <- brm(mpg~wt*cyl, data=mtcars)
D <- tidybayes::add_fitted_samples(tibble(wt=1, cyl=c(4,6)), sillyexample) %>% 
  data.table::dcast(.iteration~cyl, value.var="estimate") %>% 
  mutate(d = `4`-`6`)
D %>% 
  brms::hypothesis(c("d > 0", "d = 0"))
```

This would be really useful, for example when trying to make a specific prediction from a larger model (perhaps including many interactions) and where the difference of interest becomes a long combination of many parameters. I guess what this would require is some way to pass both prior_predictions and posterior_predictions to hypothesis, so that the Savage-Dickey method can be applied? 

Relatedly, for visualisation it would be neat if there was a prior equivalent to `posterior_linpred` etc.

**Comment by paul-buerkner** [comment]
I am not sure if I can implement this natively but I have a suggestion: Fit the model twice (1) just as usual and (2) with `sample_prior = "only"`. Then compute the quantity of interest for both models and compare their densities at the relevant point to obtain a Savage Dickey Ratio.

**Comment by paul-buerkner** [comment]
You may now use the new `density_ratio` function to conveniently compare the densities of a quantity of interested obtained from posterior and prior samples using the approach I suggested in my previous post.

**Comment by benwhalley** [comment]
Crikey - you're productive! Had spent some time hacking this together but not as nicely, so thank you very much.
