### ISSUE TITLE
reloo -- Error in checkForRemoteErrors(val)

### ISSUE THREAD

**Issue by andymilne** [paul-buerkner/brms#531]
I have a problem with the following command:

`Liking7in24Mdl5 <- add_loo(Liking7in24Mdl5, nsamples = 1000, reloo = TRUE)`

I get the following output

```
1 problematic observation(s) found.
The model will be refit 1 times.

Fitting model 1 out of 1 (leaving out observation 732)
Start sampling
starting worker pid=20778 on localhost:11907 at 15:30:29.584
starting worker pid=20788 on localhost:11907 at 15:30:29.784
starting worker pid=20798 on localhost:11907 at 15:30:29.976
starting worker pid=20808 on localhost:11907 at 15:30:30.173
Error in checkForRemoteErrors(val) : 
  4 nodes produced errors; first error: passing unknown arguments: subset1, subset2, subset3, subset4, 
```
and so on.

Maybe this is a problem with my setup. Maybe it's a problem with using `nsamples` and `reloo` at the same time? The original model has `total post-warmup samples = 10000`

**Comment by paul-buerkner** [comment]
Indeed it's a problem with using `nsamples` and `reloo` at the same time. Still, this should not happen and is now fixed in the GitHub version of brms.

**Comment by andymilne** [comment]
Quick work. Thank you!
