### ISSUE TITLE
inits = 0 not respected by reloo

### ISSUE THREAD

**Issue by andymilne** [paul-buerkner/brms#532]
I am running 

`SayOld7in24Mdl3 <- add_ic(SayOld7in24Mdl3, nsamples = 800, reloo = TRUE)`

on a previously fitted model that had the `inits = 0` argument. It seems that when the `reloo` is performed, the `inits` argument is not respected because I get a stream of 

```
Rejecting initial value:
  Log probability evaluates to log(0), i.e. negative infinity.
  Stan can't start sampling from this initial value.
```
errors during the refit.

**Comment by paul-buerkner** [comment]
You mean not automatically set? This is intentional. You need to specify `reloo_args = list(inits = 0)` in the latest github version of brms to pass inits to `reloo`.

**Comment by andymilne** [comment]
Thanks, I didn't know about that argument.

**Comment by andymilne** [comment]
Are there other arguments that needs to be passed in this way, I couldn't see anything in help (in the obvious places, at least)?

**Comment by paul-buerkner** [comment]
Anything that you want to pass specifically to `reloo` needs to go into this argument.

**Comment by andymilne** [comment]
Even things like `family`, `warmup`, `iter`, `data`, `prior`. Surely not everything in the original `brm()` call?

**Comment by paul-buerkner** [comment]
You don't need to pass those of course. Basically, everything that is stored in the brmsfit object does **not** need to be passed again.

**Comment by paul-buerkner** [comment]
This is more about the interaction between brmsfit objects and `update.brmsfit`, while `add_ic` and related functions are only distantly related to that. 

I think we can close this issue now.
