### ISSUE TITLE
Unstable hypothesis results with heavy-tailed prior distributions.

### ISSUE THREAD

**Issue by EoinTravers** [paul-buerkner/brms#534]
It seems that when testing a point hypothesis (e.g. `hypothesis(my.model, "effect = 0")`), the estimated density at that point can be strongly affected by the maximum and minimum values of the parameter in the prior samples. This means that even with a very large number of prior samples, the Bayes Factor remains unstable. 

Below is an illustration, using the modified function from `brms:::evidence_ratio`.

```r
eval_dens <- function(x, lim=F) {
  cut = 0
  if(lim){
    from <- -lim
    to <- lim
  } else {
    from <- min(x)
    to <- max(x)
  }
  dens <- do.call(density, c(loo::nlist(x, from, to)))
  spline(dens$x, dens$y, xout = cut)$y
}

x = rcauchy(4000, 1, 1)
plot(x)
```
![image](https://user-images.githubusercontent.com/3819320/46751606-f4511680-ccb2-11e8-88af-291ae0943853.png)

```r
plot(x[abs(x) < 50])
```

![image](https://user-images.githubusercontent.com/3819320/46751615-f915ca80-ccb2-11e8-93b8-25fcbc3a138b.png)

```r
c(min(x), max(x))
# [1] -7350.073 12711.163

eval_dens(x, lim=F) # The current behaviour
# [1] 1.112969
eval_dens(x, lim=max(abs(x)))
# [1] 0.9270298
eval_dens(x[abs(x) < 500], lim=F)
# [1] 0.4348631
eval_dens(x, lim=10)
# [1] 0.17411
eval_dens(x, lim=5)
# [1] 0.1741139
```

A rough solution would be to only consider posterior samples within some inner quantile, for instance 

```r
from = quantile(x, .025)
to = quantile(x, .975)
```

but I don't know if this is a principled solution here.

**Comment by paul-buerkner** [comment]
For distributions with non-existent first and second moments, the approach in `hypothesis` is **not** recommended. Instead, please use method `bayes_factor`, which relies on bridgesampling. See also https://rpubs.com/lindeloev/bayes_factors
