### ISSUE TITLE
Issue with expose_functions()

### ISSUE THREAD

**Issue by shigesong** [paul-buerkner/brms#536]
The new rstan 2.18 seems to break the expose_functions(). I discovered this while playing with Statistical_Rethinking_with_brms_ggplot2_and_the_tidyverse, chapter 11. I got: 

Error in (function (classes, fdef, mtable) :
unable to find an inherited method for function ‘get_stancode’ for signature ‘"stanmodel"’

**Comment by paul-buerkner** [comment]
It seems as if the `get_stancode` method for `stanmodel` objects got lost somewhere. At least, I can't access it no matter what I try. @bgoodri any ideas how to fix this?

**Comment by bgoodri** [comment]
Working on it

**Comment by paul-buerkner** [comment]
Since this is an rstan issue and Ben is working on it, I am closing this issue.

**Comment by shigesong** [comment]
Just did, thanks.
