### ISSUE TITLE
Can't sample when using offset with a single data point

### ISSUE THREAD

**Issue by szego** [paul-buerkner/brms#545]
I'm trying to fit a Poisson model with a single data point, but I'm getting the following error when sampling starts:

> Exception: mismatch in number dimensions declared and found in context; processing stage=data initialization; variable name=offset; dims declared=(1); dims found=()

Here's the model:

```
brm(
    y ~ 1 + offset(log(x)),
    family = poisson("log"),
    data = list(y = 3, x = 2)
)
```

I don't get the error if I try to fit the same model with two data points:

```
brm(
    y ~ 1 + offset(log(x)),
    family = poisson("log"),
    data = list(y = c(3,4), x = c(2,3))
)
```

I'm using brms 2.6.0 and rstan 2.18.1.

**Comment by paul-buerkner** [comment]
Thanks for reporting this issue. Offsets were not defined as 1D arrays thus confusing Stan when vectors of length 1 were provided, which are treated as scalars not as vectors. This should now be fixed in the dev version of brms from github.

**Comment by szego** [comment]
I think I blinked while you were fixing this, so I missed it completely!

Thanks for the awesome package.
