### ISSUE TITLE
3-level factor in a non-linear formula

### ISSUE THREAD

**Issue by cumuluss** [paul-buerkner/brms#547]
Hi Paul 
im currently trying to fit a nonlinear model. Here "https://github.com/paul-buerkner/brms/issues/46"
you said "Currently, a 3-level factor will not be allowed in a non-linear formula (you will recieve an error message before the model is compiled), but it's allowed to put it in nonlinear. "
This was more than to years ago is this nowadays implemented?
Thank you!
C

**Comment by cumuluss** [comment]
thank you for your answer. Im not sure about what im doing. As I have a similar case, i was following your Advanced Item-Response Models example in your vignette about non-linear models. There you have the term eta. In this case it is just one continuous variable. What else could that be? Could it also be a set of predictors? In my case i have two continuous and a factor with 4 levels.

**Comment by paul-buerkner** [comment]
yes, eta could be any predictor term possible in brms including categorical
predictors of course.

Am Do., 8. Nov. 2018, 14:47 hat cumuluss <notifications@github.com>
geschrieben:

**Comment by cumuluss** [comment]
Thank you! That sounds good!

**Comment by paul-buerkner** [comment]
Great. In the future, please ask brms related questions on https://discourse.mc-stan.org/
