### ISSUE TITLE
Marginal effects, Ordinal logistic regression, Specific effects

### ISSUE THREAD

**Issue by DianaAlvarezB** [paul-buerkner/brms#548]
Hi, 
I am running an ordinal model with specific effects and I am trying to modify the marginal_effects function. 

`fit_sc1 <- brm(formula = GPA ~  cs(Gender) + cs(Family_Income) + cs(Cognitive_Reflection)+ cs(Alcohol) + 
                 cs(Tobacco) + cs(Grit) + cs(Perseverance_of_Effort) + cs(Consistency_of_Interests),
               data=datos1, family = acat())`

The results for gender show an impact on GPA, just why endorsing category 4 of the dependent variable, as the following graph shows.
![gender](https://user-images.githubusercontent.com/36611830/48307233-0fab7d80-e50e-11e8-87f2-2ca6cf93c73b.png)

Is there an option to plot just the category 4, deleting the other reponse options on the graph?

Thank you

**Comment by paul-buerkner** [comment]
For greater visibility, I would like to ask you to open a thread on https://discourse.mc-stan.org/ for brms related questions. The issue tracker is reserved to feature requests and bug reports.
