### ISSUE TITLE
Is there a way to save generated Stan code? 

### ISSUE THREAD

**Issue by terrytangyuan** [paul-buerkner/brms#55]
In other words, if we specify a formula in brm, could we save the Stan code based on the formula? 

Thanks.

**Comment by terrytangyuan** [comment]
Oops, I missed `model` object in the fitted model. That's exactly what I want. Great work!

**Comment by paul-buerkner** [comment]
You could also just call the `make_stancode` function to get the Stan code directly, without the need to compile the model first.
