### ISSUE TITLE
Issue when interacting monotonic terms

### ISSUE THREAD

**Issue by benwhalley** [paul-buerkner/brms#550]
This may be an issue with my data (because a simpler example using mtcars does work) but the following code produces an error for me:

```{r}
df <- read_csv('https://gist.githubusercontent.com/benwhalley/bcbebceec883720952d2b5b4eb5e3581/raw/3b3394c7e7895bee93f9b3963378afc76c479a6b/exampledata.csv')
model1 <- brm(iscase|trials(1) ~ mo(GAD7)*mo(PHQ9), 
                                data=df, 
                                family=binomial(link="logit"))

marginal_effects(model1, "GAD7:PHQ9")

```

Error:

```
Error: Invalid values in variable 'PHQ9': '-1', '-1', '-1', '-1', '-1', '-1', '-1', '-1', '-1', '-1', '-1', '-1', '-1', '-1', '-1', '-1', '-1', '-1', '-1', '-1', '-1', '-1'
```

Is it a problem that each variable has so many levels relative to N?

**Comment by paul-buerkner** [comment]
The problem is that `PHQ9` numeric in which case brms treats them as is and doesn't allow for negative counts. If you want brms to automatically scale your monotonic predictor, you have to make it an ordered factor.

**Comment by paul-buerkner** [comment]
Perhaps you need to update brms to the latest CRAN version (2.6.0)

**Comment by benwhalley** [comment]
Ah - thank you... applying both suggestions has fixed the issue.  I thought I had the latest brms, but had set repos to a dated MRAN snapshot.
