### ISSUE TITLE
Problem with newdata in fitted

### ISSUE THREAD

**Issue by jerlich** [paul-buerkner/brms#551]
```
> new_fit2$version
$brms
[1] ‘2.1.0’

$rstan
[1] ‘2.17.3’

> newdata <- tibble(treat = 'L',
+                   delay = 10,
+                   rewmag = 10,
+                   subjid = subjids,smag = 4
+ )
> fitted(new_fit2, newdata = newdata, nsamples = 10)
Error in model.matrix.default(terms, data) : 
  model frame and formula mismatch in model.matrix()

> new_fit2$formula
choice ~ inv_logit((rewmag/(1 + exp(logk) * delay) - smag)/noise) 
noise ~ 0 + treat + (1 | subjid)
logk ~ 0 + treat + (treat | subjid)
```

It seems to be related to the `0 + ...` fixed effects, since a similar model without that doesn't give the error.

**Comment by paul-buerkner** [comment]
You are using an outdated version of brms. Does the problem still occur in the current release version of brms (2.6.0)?

**Comment by jerlich** [comment]
The error is still present when using the 2.6.0 version of brms to draw fits from the 2.1.0 model. It's a large model, so it will take me some time to refit with 2.6.0 and then retest.

**Comment by paul-buerkner** [comment]
Ok. Can provide a minimal reproducible example for me to test this myself?

**Comment by jerlich** [comment]
seems that when fitting a model with 2.6.0 and then using `fitted` on that model, the error does not appear. It's a little annoying to refit, but not the end of the world.
