### ISSUE TITLE
Error with CAR model when data are disconnected

### ISSUE THREAD

**Issue by edwardabraham** [paul-buerkner/brms#554]
I love BRMS, thanks very much for making life so much easier! I have run into a problem fitting a CAR model to my data using `cor_car`. The model
is failing to initialise, with the error `Error: All locations should have at least one neighbor.`. Checking shows that the neighbour matrix `W` is well-formed. It turns out that the problem is not with my
matrix, but with the distribution of the data. 

The implementation of the CAR model is able to handle areas without any
measurements, but fails if there are disconnected data points. A simple example is below. The grid has three cells in a line `a`, `b`, and `c`. If there is data in `a` and `c`, but not in `b`, then the model
fails to compile.  I think that this issue effects the efficient sparse implementation, but would not effect the `multi_normal_prec` implementation  (http://mc-stan.org/users/documentation/case-studies/mbjoseph-CARStan.html). 

In any case, it would be good to have a different error message for this problem, as the issue is not with the neighbour matrix, but with the distribution of the data. 

```
library(brms)                                                
# Run using BRMS 2.6.1                                       
                                                             
# W defines three cell grid, with `a` and `c` disconnected:  
# +---+---+---+                                              
# | a | b | c |                                              
# +---+---+---+                                              
                                                             
W <- as.matrix(data.frame(a=c(0, 1, 0),                      
    b=c(1, 0, 1),                                            
    c=c(0, 1, 0)))                                           
rownames(W) <- c("a", "b", "c")                              
                                                             
data <- data.frame(value = rnorm(6, 0, 1))                   
                                                             
# These two data configurations work                         
#data$group = rep(c("a", "b", "c"), 2)                       
#data$group = rep(c("a", "b"), 3)                            
                                                             
# With data in disconnected cells, the model fails with:     
#Error: All locations should have at least one neighbor.     
data$group = rep(c("a", "c"), 3)                             
                                                             
model <- brm(value ~ 1,                                      
    family='normal',                                         
    data=data,                                               
    autocor = cor_car(W, formula = ~ 1 | group))          
```

**Comment by paul-buerkner** [comment]
What would you think of the following error? 

```
Error: For exact sparse CAR, all locations should have at least one neighbor
within the provided data set. Consider using type = 'icar' instead. 
```

**Comment by edwardabraham** [comment]
Cheers Paul, unfortunately, the same problem occurs with all three of the current CAR types (`esicar`, `icar`, and `escar`) (checked using the test case above). The immediate fix would be to make the error message something like `Error: for current implementations of the CAR model, the data must be in a connected region of the domain`

It would be possible to introduce a less efficient exact CAR type, e.g., `ecar`,  based on the first example by Max Joseph (his model is below), which I don't think has this problem. Happy to check this out further. There is probably also a way to fix the sparse method to handle disconnected data, but I'm not sure how to do that! 

```
data {
  int<lower = 1> n;
  int<lower = 1> p;
  matrix[n, p] X;
  int<lower = 0> y[n];
  vector[n] log_offset;
  matrix<lower = 0, upper = 1>[n, n] W;
}
transformed data{
  vector[n] zeros;
  matrix<lower = 0>[n, n] D;
  {
    vector[n] W_rowsums;
    for (i in 1:n) {
      W_rowsums[i] = sum(W[i, ]);
    }
    D = diag_matrix(W_rowsums);
  }
  zeros = rep_vector(0, n);
}
parameters {
  vector[p] beta;
  vector[n] phi;
  real<lower = 0> tau;
  real<lower = 0, upper = 1> alpha;
}
model {
  phi ~ multi_normal_prec(zeros, tau * (D - alpha * W));
  beta ~ normal(0, 1);
  tau ~ gamma(2, 2);
  y ~ poisson_log(X * beta + phi + log_offset);
}
```

**Comment by edwardabraham** [comment]
Yep! That works  .. now I  just need to figure out if `icar` is what I want to use for my model.

**Comment by paul-buerkner** [comment]
Are you ok if I close this issue or is there anything left to be done?

**Comment by edwardabraham** [comment]
Yep, happy for this to be closed. In the longer term there would be value in either the `multi_normal_prec` implementation, or in figuring out how to get the efficient implementation to work when the data are disconnected. If I come back to this problem, I could raise a pull request with a solution. In the mean-time, however,  the updated error message is all that is needed.

**Comment by paul-buerkner** [comment]
Sounds like a good plan. Closing this issue.
