### ISSUE TITLE
Evidence ratios of Inf

### ISSUE THREAD

**Issue by andymilne** [paul-buerkner/brms#555]
When no samples go against a hypothesis test in `hypothesis`, would it be better if its evidence ratio is reported as `> N`, where N is the number of samples minus one, rather than as `Inf`?

**Comment by paul-buerkner** [comment]
I can't change the output data.frame for reasons of backwards compatibility. I am hesitant to change just the output of the print method as it won't coincide with the actual data.frame then. I can add a not to the documentation though.

**Comment by paul-buerkner** [comment]
I have improved the doc accordingly and will close this issue now.
