### ISSUE TITLE
For ordinal models, predict with scale = linear returns values on response scale

### ISSUE THREAD

**Issue by andymilne** [paul-buerkner/brms#557]
Note that the title above is wrong -- accurate description is below...

Given an ordinal model -- e.g., `family = cumulative("probit_approx")` -- `fitted(mdl, scale = "linear", summary = FALSE)` gives the same output as `predict(mdl, scale = "linear", summary = TRUE)`

**Comment by paul-buerkner** [comment]
predict has no `scale` argument because it does not make sense to "predict" values on the linear scale. Predicted values are, by definition, response values.

**Comment by andymilne** [comment]
I mistyped. I mean `fitted`, not `predict`. Putting `summary = TRUE` results in the following warning 
```
Error in dimnames(out) <- `*vtmp*` : 
  length of 'dimnames' [1] not equal to array extent
```

**Comment by andymilne** [comment]
Yes, same error with the dev version.

**Comment by paul-buerkner** [comment]
Ok, I found the problem. It should now be working correctly again with brms from github. 

Thank for reporting this issue!
