### ISSUE TITLE
odd rstan/brms interaction

### ISSUE THREAD

**Issue by bbolker** [paul-buerkner/brms#558]
I get an odd problem when I load `rstan`, fit a model, manipulate that model in a particular way (in order to reduce the object size when I store it on disk), and then try to compile a `brms` model. This is admittedly a weird scenario, and I can work around it, but thought I would post it in case anyone has an explanation and/or it recurs in some other context ...

> Error in (function (file, model_name = "anon_model", model_code = "",  : 
  trying to get slot "model_code" from an object (class "stanmodel") that is not an S4 object 
Calls: brm ... eval -> eval -> eval -> eval -> do.call -> <Anonymous>
Execution halted

```
hack_size <- function(x, ...) {
    UseMethod("hack_size")
}

hack_size.stanfit <- function(x) {
    x@stanmodel <- structure(numeric(0), class="stanmodel")
    x@.MISC <- new.env()
    return(x)
}

hack_size.brmsfit <- function(x) {
    x$fit <- hack_size(x$fit)
    return(x)
}

library(rstan)
rstan_options(auto_write = TRUE)
model_file <- system.file("extdata", "8schools.stan", package = "broom.mixed")
schools_dat <- list(
    J = 8,
    y = c(28, 8, -3, 7, -1, 1, 18, 12),
    sigma = c(15, 10, 16, 11, 9, 11, 10, 18)
)
set.seed(2015)
rstan_example <- stan(
    file = model_file, data = schools_dat,
    iter = 1000, chains = 2, save_dso = FALSE
)

rstan_example <- hack_size(rstan_example)

library(brms)
## ggeffects::efc, "Sample dataset from the EUROFAMCARE project"
efc <- readRDS(system.file("extdata","efc.rds",package="broom.mixed"))
print(sessionInfo())    
brms_crossedRE <- brm(mpg ~ wt + (1 | cyl) + (1 + wt | gear),
                      data = mtcars,
                      iter = 100, chains = 2,
                      family=gaussian
                      )
```

**Comment by paul-buerkner** [comment]
I have literally no idea, but if anyone understands this, then certainly @bgoodri.

**Comment by paul-buerkner** [comment]
I briefly talked with Ben about this issue and he said that this is probably a **rstan** issue. Perhaps you can open an issue on https://github.com/stan-dev/rstan?

To be at least, it doesn't seem like I can change anything on the brms side to make that work, because it happens completely inside `rstan::stan_model` and brms is just passing the stan code.

**Comment by paul-buerkner** [comment]
Closing this. If it turns out to be related to brms, please reopen this issue.
