### ISSUE TITLE
Prior argument for length-scale parameter of Gaussian processes seem to not be updating stancode with brms 2.6.0

### ISSUE THREAD

**Issue by raphtael** [paul-buerkner/brms#559]
Hi Paul,

thanks for brms, it has proven a useful tool for my day-to-day analyses.

However, I recently updated my R version (3.5.1) as well as the brms package (2.6.0). On this recent brms version, it seems that the 'prior' argument to the 'gp' function is not be passed to stancode (the prior argument for the intercept or other parameters seem to be working fine). Hence, it makes it difficult to change the gp priors in brms 2.6.0. I can work around the issue by running the stancode function, manually changing the Stan script, and sampling with rstan, but it is less convenient than directly fitting with brms. It might also be worth checking why this happens. For your information, I did not have this issue with brms 1.10.0.

```
# Simulate data
set.seed(101)
dat <- mgcv::gamSim(1, n = 30, scale = 2)
# fit a simple gaussian process model
fit1 <- brm(y ~ gp(x2), dat, chains = 2)
stancode(fit1) # prior on lenght-scale is inv_gamma_lpdf(0.524508, 0.000122)
# Change the prior length-scale of the GP
priors <- c(prior("normal(0, 2)", class = "Intercept")
              , prior("inv_gamma(1,  1)", class = 'lscale'))  
fit2 <- brm(y ~ gp(x2), dat, chains = 2, prior = priors)
stancode(fit2) # prior on lenght-scale is still inv_gamma(0.524508, 0.000122). It should be inv_gamma(1, 1). However, prior on intercept has been updated to normal(0, 2).
```

Cheers,
Raphael

**Comment by paul-buerkner** [comment]
At some point, I added default priors to the lscale parameters separately, which means that the 'class' prior will only take effect when the computation of the specific prior fails. See `get_prior(y ~ gp(x2), dat)` for details about how to change the individual priors.
