### ISSUE TITLE
Specifying priors on multiple random effects for nonlinear models

### ISSUE THREAD

**Issue by tomwallis** [paul-buerkner/brms#56]
I've been playing around with `brms` to fit bounded binomial regression models (where the inverse link function is bounded to some subset of [0, 1]). For example:

``` r 
fit <- brm(y ~ 0.5 + 0.45 * inv_logit(eta), data = dat,
           family = bernoulli("identity"),
           nonlinear = list(eta ~ x),
           prior = set_prior("normal(0,5)", nlpar = "eta"))

```

fits a model where the bernoulli expected value is a sigmoid bounded between 0.5 and 0.95, and the prior on the linear coefficient of `x` is Normal with mean 0 and sd 5. Now imagine I wish to include a random effect intercept into the nonlinear model of `eta`:

```r
priors <- c(set_prior("student_t(3,0,5)", nlpar = "eta", class = "b"), 
            set_prior("student_t(3,0,2)", nlpar = "eta", class = "sd", group = "subj"))

# verify that the prior made its way into the stan code:
make_stancode(correct ~ 0.333 + 0.667 * inv_logit(eta), data = dat,
            family = bernoulli("identity"),
            nonlinear = list(eta ~ 1 + (1 | subj)),
            prior = priors)
```

This works as expected: the relevant part of the Stan model output by `make_stancode` is

``` r
  // prior specifications 
  b_eta ~ student_t(3,0,5); 
  sd_eta_1 ~ student_t(3,0,2); 
```

Now I try to add a second (crossed) random effect:

``` r
priors <- c(set_prior("student_t(3,0,5)", nlpar = "eta", class = "b"), 
            set_prior("student_t(3,0,2)", nlpar = "eta", class = "sd"))

make_stancode(correct ~ 0.333 + 0.667 * inv_logit(eta), data = dat,
           family = bernoulli("identity"),
           nonlinear = list(eta ~ 1 + (1 | subj) + (1 | im_code)),
           prior = priors)
```

Results in the following Stan code:

```r
  // prior specifications 
  b_eta ~ student_t(3,0,5); 
  sd_eta_1 ~ student_t(3, 0, 10); 
  z_eta_1 ~ normal(0, 1); 
  sd_eta_2 ~ student_t(3, 0, 10); 
  z_eta_2 ~ normal(0, 1); 
```

So the priors on the random effect sds are not being correctly passed to Stan. I've tried a few variations based on the output of `get_prior` with no success:

``` r
get_prior(correct ~ 0.333 + 0.667 * inv_logit(eta), data = dat,
+            family = bernoulli("identity"),
+            nonlinear = list(eta ~ 1 + (1 | subj) + (1 | im_code)))
                prior class      coef   group nlpar bound
1                         b                     eta      
2                         b Intercept           eta      
3 student_t(3, 0, 10)    sd                              
4                        sd           im_code eta.2      
5                        sd Intercept im_code eta.2      
6                        sd              subj eta.1      
7                        sd Intercept    subj eta.1      
```

Where am I going wrong here? I'm not sure how to read the output of `get_prior` correctly. I've tried, for example, specifying `nlpar` as "eta.2" for "im_code", but this also has no effect on the Stan code. Suggestions?

**Comment by paul-buerkner** [comment]
2 days ago, I mad some changes to the dev version and parsing of priors. It looks like I made a mistake there. I will check this and correct it asap.

**Comment by paul-buerkner** [comment]
It looks like I have already fixed it. Would you mind installing the latest dev version and try again?

**Comment by tomwallis** [comment]
Right you are: updating to the dev version did the trick. Thanks!

**Comment by paul-buerkner** [comment]
I am glad to hear that! :-)
