### ISSUE TITLE
Feature: temporarily save parallel chains to disk upon completion

### ISSUE THREAD

**Issue by lindeloev** [paul-buerkner/brms#561]
I am currently debugging a complex model with convergence issues. I run multiple chains in parallel and often one chain completes several hours before the last chain. It would be great to be able to inspect the results from the "quick" chain immeditately so that I can shut down the other chains if the first chain is bad.

Here's one idea how the API could accommodate this: 

* If the `file` argument is specified, completed chains will be saved as `filename_chain1.rds`. If `file` is not specified, there is no change in behavior.
* If you want to, you can load that in a separate R session and explore it.
* When all chains have completed, the "chain-files" are deleted, and the full `filename.rds` file is saved.

**Comment by paul-buerkner** [comment]
I agree this would be a nice feature, but it is one that needed to be implemented in rstan (https://github.com/stan-dev/rstan) natively for all Stan models, not in the form of a workaround in brms. I would thus suggest you propose this issue on the rstan page.

**Comment by lindeloev** [comment]
Good idea. I raised an issue [here](https://github.com/stan-dev/rstan/issues/591). Closing.

**Comment by lindeloev** [comment]
Update: I solved this and posted the solution in [the stan issue](https://github.com/stan-dev/rstan/issues/591#issuecomment-442865357). The great thing is that you can draw traceplots even while sampling is ongoing, i.e., when no chains have completed.
