### ISSUE TITLE
Plotting MCMC in GLMM

### ISSUE THREAD

**Issue by JacopoCerri** [paul-buerkner/brms#563]
Dear colleagues,

I fit a GLMM for an ordered outcome. When I started fitting some simple model, to get familiar with brms, the function plot(brmsfit) functioned in a correct way, plotting the convergence of the MCMC. However, it does not work anymore and it prints the following error:
 'Error in FUN(X[[i]], ...) : object 'Value' not found'

As the model is similar to a GLMM with a gaussian error term (the response variable is made out of ordered categories, whose distribution nevertheless approaches a Gaussian one), I also fitted a GLMM with a Gaussian error. Usually, this model is less demanding in terms of parameter estimation (a lower number of intercepts), however the problem persists.

Do you have any idea why it is happening? I tried to update, remove, and re-install brms but the situation did not improve.

Best,

Jacopo Cerri

**Comment by JacopoCerri** [comment]
Right, I am sorry for having missed that point. Find attached an anonymized dataset in the RData format. Once you load it in your environment, you might run the following code, fitting a GLMM:

`
mod <- brm(Outcome ~ A + B + C + A*B +
                  (A + B|ID), family="cumulative", data=foo, chains=4,
                iter=5000, cores = 6)

plot(mod)

`
Best,

Jacopo Cerri
[Dataset_GitHub.RData.zip](https://github.com/paul-buerkner/brms/files/2632755/Dataset_GitHub.RData.zip)

**Comment by paul-buerkner** [comment]
I didn't want to wait so long and so I just ran the following subset of your model

```
mod <- brm(Outcome ~ A + B + C + A*B +
             (A + B|ID), family="cumulative", data=foo[1:300,], 
           chains=2,iter=1000, cores = 2)

plot(mod)
```

This works for me.

If it fails for you, perhaps it's an issue with another R package. If the problem persists, I would recommend uninstalling R, removing all installed packaged from your machine, installing R again and installing brms (and all of its dependencies) again.

**Comment by paul-buerkner** [comment]
I haven't heard back from you for a few days. Where you able to solve the problem?

**Comment by paul-buerkner** [comment]
Closing this as it is unlikely an actual brms issue.
