### ISSUE TITLE
Enable 'map_rect'

### ISSUE THREAD

**Issue by paul-buerkner** [paul-buerkner/brms#564]
It would be nice to add a switch to `brm` enabling within-chain parallelization of the likelihood via `map_rect'. For more complex models this is going to be a real pain, but perhaps we can get it working for some simpler model classes as a start.

**Comment by paul-buerkner** [comment]
As Sebastian Weber is working on a more general and less clunky interface for within chain parallelization in Stan, I don't think `map_rect` is worth implementing at all in brms. Once the new interface is released, I will open a new issue to implement that one in brms.

**Comment by torkar** [comment]
Please open a new issue, Paul! ;)

**Comment by groceryheist** [comment]
`Reduce_sum` is out, and works great, but what if I have a really big dataset and a big cluster of cpus? MPI sounds nice, but seems only to work in `map_rect`. Any plans to support MPI someday?

**Comment by paul-buerkner** [comment]
The interfact of map_rect is not flexible enough to be viable for brms. So it is highly unlikely to ever make it into brms.
