### ISSUE TITLE
Evid.Ratio and Post.Prob values are NA

### ISSUE THREAD

**Issue by jrosen48** [paul-buerkner/brms#566]
When using the `hypothesis()` function, the `Evid.Ratio` and `Post.Prob` values are reported as `NA`:

```
> brms::hypothesis(m1, "exp(c_male) = 0", alpha = .01)
Hypothesis Tests for class b:
         Hypothesis Estimate Est.Error CI.Lower CI.Upper Evid.Ratio Post.Prob Star
1 (exp(c_male)) = 0     0.72      0.03     0.65      0.8         NA        NA    *
---
'*': The expected value under the hypothesis lies outside the 99%-CI.
Posterior probabilities of point hypotheses assume equal prior probabilities.
```

Based on the rest of the output from the function and what I can tell about the estimates from the `summary()` method, there doesn't seem to be any issues (or anything missing!) for this parameter estimate. Is there a reason why these are `NA`?

**Comment by paul-buerkner** [comment]
I would think that you didn't sample from priors, which is necessary for Evid.Ratio and Post.Prob to be computed for a non-directional hypothesis. See `?hypothesis`
