### ISSUE TITLE
Programmatically check diagnostics

### ISSUE THREAD

**Issue by vkehayas** [paul-buerkner/brms#568]
I would like to programmatically check all diagnostics for models fit with `brms` in unit tests. Unless I missed it, I found nothing relevant inside the `brmsfit` object or an existing function in the manual that does this. Of course, [`rstan` has all the necessary functions to do that](http://mc-stan.org/rstan/reference/check_hmc_diagnostics.html), but it would be more convenient if `brms` had a handy little function that checks all of them on behalf of the user on demand. I have in mind something as simple as this:
https://github.com/betanalpha/knitr_case_studies/blob/master/rstan_workflow/stan_utility.R
I could submit a PR if you are interested unless you want to do it better and faster yourself.

**Comment by paul-buerkner** [comment]
I agree this would make a useful feature and it's worth a more general discussion. What divergence diagnostics shell we show and how should we show it? Bringing @avehtari, @bgoodri and @jgabry into the discussion.

**Comment by avehtari** [comment]
I think this should be common to brms, rstan, rstanarm, etc. so maybe it should be in rstantools?
stan_utility has
```
check_all_diagnostics <- function(fit) {
  check_n_eff(fit)
  check_rhat(fit)
  check_div(fit)
  check_treedepth(fit)
  check_energy(fit)
}
```
These are all useful. It would be useful to consider the soon coming update in rhat and effective sample size. It would be very important to discuss the warning limits and acknowledge that they may change when we learn more. For example, E-BFMI warning limit is not well studied.

**Comment by paul-buerkner** [comment]
Totally agree. Perhaps we should indeed wait for our final decision on the Rhat / ESS output before we decide how to include that in `check_all_diagnostics` or however we end up naming it. 

@vkehayas Would you mind opening an issue on https://github.com/stan-dev/rstantools as this feature likely not requires major changes to brms, but just a small wrapper function, once the corresponding `stanfit` method is done.

**Comment by vkehayas** [comment]
@bgoodri Would you like me then to open an issue on rstan instead of rstantools?

**Comment by bgoodri** [comment]
OK

**Comment by DJFernandes** [comment]
In case anyone stumbles onto this thread looking to check diagnostics on their brms model, here are easy commands that works with brms 2.13.3



```
library(brms)
brm_mod = brm(...)

# to check divergences, saturated tree depth, E-BFMI
rstan::check_hmc_diagnostics(brm_mod$fit)

# to get rhat
rhat_vals = rhat(brm_mod)

# to get neff
neff_vals = neff_ratio(brm_mod)
```

**Comment by paul-buerkner** [comment]
Diagnostics have been or will be moved to our new posterior package (https://github.com/stan-dev/posterior) so I am closing this issue.
