### ISSUE TITLE
predict coming up with a different number of observations

### ISSUE THREAD

**Issue by wacunn** [paul-buerkner/brms#569]
Hello, I am running a categorical model in brms
ta <- brm(switchtype ~ trialcode * value + (1 + trialcode * value|subject), family="categorical", data=threechoice, cores=4)

The dataset threechoice has 5722 observations

when I run this command to get the predicted values
pr <- predict(ta, summary = FALSE)
pt <- posterior_table(pr)

pr and pt both only have 4655 values. I assume that there should be 5722, no?
Any advice would be appreciated. Thanks!

Best
wil

**Comment by vkehayas** [comment]
Forgive me if this was obvious to you but did you check that there are no missing values in the `switchtype` variable?

**Comment by wacunn** [comment]
Yes! That solved it. I have no idea why those would exist, so there may be a problem with the raw data.

**Comment by paul-buerkner** [comment]
Glad you could solve it!
