### ISSUE TITLE
Error: Parameter cor_eta1 could not be renamed.

### ISSUE THREAD

**Issue by tomwallis** [paul-buerkner/brms#57]
I've been fitting some nonlinear mixed effects models with varying intercepts and slopes. I just ran a model fit which returned an error (apparently occurring at the end of the fitting). I'm afraid I can't share the underlying data here. I could try to come up with a minimal example if required. 

``` r
fit <- brm(correct ~ 0.333 + 0.667 * inv_logit(eta), data = dat,
+            family = bernoulli("identity"),
+            nonlinear = list(eta ~ x1 * x2 + (x1 *x2 | subj)),
+            prior = priors, 
+            cluster=4)
Compiling the C++ model
Start sampling
Error: Parameter cor_eta1 could not be renamed. Please report a bug.
```

Any idea what caused this?

**Comment by paul-buerkner** [comment]
My apologies for these issues. That's the bad part of having to use a dev version. Again, this is something I changed during the last days. I will reprocduce it with my own data and see what's going on.

**Comment by paul-buerkner** [comment]
It should be fixed now.

**Comment by tomwallis** [comment]
Yep, that's working now. Thanks for the prompt fix!
