### ISSUE TITLE
Marginal_effects not working for the estimation with ME predictors

### ISSUE THREAD

**Issue by hlluik** [paul-buerkner/brms#571]
Hello!

I am trying to get the marginal effects out of brm model that contains predictors with ME (y~ x1 + me(x2, sd) + me(x3,sd) +...., data=data, family=bernoulli(link="logit")), but it does not work as the attribute is not the same length as the vector. Is there any workaround how to still get the marginal effects as using the fitted command does not solve the problem either?

Best,
H

**Comment by paul-buerkner** [comment]
Which version of brms are you using? Does it still fail with the latest CRAN version of brms (2.6.0)?

If yes, please provide a self-contained minimal reproducible example for the problem you see.

**Comment by paul-buerkner** [comment]
Ok, I found the problem and fixed it in the dev version to be installed via 

```R
if (!requireNamespace("devtools")) {
  install.packages("devtools")
}
devtools::install_github("paul-buerkner/brms")
```

Thanks for reporting this bug!
