### ISSUE TITLE
brms 2.7.0 doesn't install from CRAN

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [paul-buerkner/brms#573]
On Linux Debian testing (fresh update), running as root (in order to maintain systemwide installation of the Debian-packaged R 3.5.1, `brms` fails to update (via `update.packages(ask=FALSE, checkBuilt=TRUE)`).
Other attempts to install also fail :
```
> remove.packages("brms")
Elimination du package de ‘/usr/local/lib/R/site-library’
(car ‘lib’ n'est pas spécifié)
> install.packages("brms")
Installation du package dans ‘/usr/local/lib/R/site-library’
(car ‘lib’ n'est pas spécifié)
essai de l'URL 'https://cloud.r-project.org/src/contrib/brms_2.7.0.tar.gz'
Content type 'application/x-gzip' length 3818402 bytes (3.6 MB)
==================================================
downloaded 3.6 MB

* installing *source* package ‘brms’ ...
** package ‘brms’ correctement décompressé et sommes MD5 vérifiées
** R
terminate called after throwing an instance of 'std::runtime_error'
  what():  Mutex creation failed
Aborted

Les packages source téléchargés sont dans
	‘/tmp/Rtmpu1AN7B/downloaded_packages’
Warning message:
In install.packages("brms") :
  l'installation du package ‘brms’ a eu un statut de sortie non nul
```

More problematic : trying to reinstall an older version of `brms` (via `devtools::install_url()` using the CRAN archive) **also fails**. Sounds like an R or system problem.

I've [found](https://github.com/r-lib/later/issues/63) [some](https://github.com/RcppCore/RcppParallel/issues/77) [references](https://bugs.archlinux.org/task/59581) to similar problems, not specific to `brms`.

I'll investigate further.

**Comment by paul-buerkner** [comment]
Thanks for reporting this issue. I don't think this is related to brms itself as it passes CRAN checks on all platforms and doesn't even have compiled code in it. I am curious to hear what the solution to this was once you found it.

**Comment by EmmanuelCharpentier** [comment]
A couple points : 

1. This has been reported as [Debian bug #916773](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=916773) against r-base ; however the real culprit is almost certainly somethong else.
2. A brute-force workaround is to reinstall all packages. A better workaround would be to reinstall (recursive) dependencies, but this is not as trivial as it seems...
3. Dirk Eddelbuettel (Debian's R maintainer) suggests to keep the present issue until the real problem is diagnosed.

HTH,

**Comment by eddelbuettel** [comment]
As I tagged me, what did you mean by "present issue" ?  You filed the same issue twice, once as Debian bug report and once here, but have not really provided anything truly reproducible.   Kurt told us that his solution was a reinstallation of the C++ packages; in my experience this is sometimes needed.  Could be as simple as somewhat making an innocent change in an interface, could be an issue between the OS/compiler (ie `g++` on Debian may have changed for which Debian would rebuild its packages) and you installing another package---Paul's `brms` and its dependencies---outside of Debian.  

I really do not see too much that is operational here :-/

**Comment by paul-buerkner** [comment]
Thanks for this suggestion @silberzwiebel! I guess I will now close this issue for being unrelated to brms.
