### ISSUE TITLE
Special characters in factors in smooths

### ISSUE THREAD

**Issue by boschwartz** [paul-buerkner/brms#574]
I ran in to an issue where using a s(Y, by = Z) term produced this error
_"Error in tcrossprod(b, X) : non-conformable arguments"_
afterwards when trying to run marginal_effects()

I solved it by removing the special characters (here "+" and "-") from the factors in Z.

It seems like the spline does not treat special characters like if I had just included e.g. a Y:Z term where the "+" becomes a "P". The output with the spline included contains variables  with "+" and "-" in the name and that I think confuses marginal_effects().

**Comment by paul-buerkner** [comment]
Thanks! It should now be fixed in the github version of brms.
