### ISSUE TITLE
Validate "cores" before compiling

### ISSUE THREAD

**Issue by rpsychologist** [paul-buerkner/brms#576]
This issue is just a minor thing, but changing it would improve the user experience. Currently, the argument "cores" is not validated, hence if it is invalid the model will first compile but then fail and throw an error. This behavior can be annoying if you are stupid like me and, e.g., pass an object that does not exist as an argument, thinking that the model will sample while I go and grab a cup of coffee. ;)

```
brm(count ~ log_Age_c + log_Base4_c * Trt + (1|patient),
    data = epilepsy, 
    family = poisson(), 
    cores = cores)
## Compiling the C++ model
## Start sampling
## Error in nlist(chains, cores) : object 'cores' not found
```

**Comment by paul-buerkner** [comment]
Good point. While I was at it, I also added early validity checks for a bunch of other arguments which were otherwise only evaluated after compiling a model. The next coffee break will hopefully be more effective ;-)
