### ISSUE TITLE
wrong order in for negative-integer responses for family=cumulative()

### ISSUE THREAD

**Issue by lindeloev** [paul-buerkner/brms#580]
Just noticed this small bug. The title describes it in full, I think :-) Here is a response variable from -3 to 3 and the plot of marginal effects:

```
library(brms)

# Some data
D = data.frame(
  response = ordered(sample(-3:3, 50, replace=T)),
  group = rep(c('A', 'B'), each=25))

# Fit and plot
fit = brm(response ~ group, D, family=cumulative(), chains = 1)
marginal_effects(fit, 'group', categorical=T)
```

![image](https://user-images.githubusercontent.com/1439417/50633583-22f62a80-0f4c-11e9-9c87-c39b1e5c2f36.png)

**Comment by lindeloev** [comment]
Oh, this seem to be happening during modeling, i.e., much earlier than `marginal_effects` which seems to be innocent.

    get_prior(response ~ group, D, family=cumulative())

shows the wrong order:
```

                prior     class   coef group resp dpar nlpar bound
1                             b                                   
2                             b groupB                            
3 student_t(3, 0, 10) Intercept                                   
4                     Intercept     -1                            
5                     Intercept     -2                            
6                     Intercept     -3                            
7                     Intercept      0                            
8                     Intercept      1                            
9                     Intercept      2                            
```

**Comment by paul-buerkner** [comment]
Thanks for reporting this issue. I will try to resolve it later on today.

**Comment by paul-buerkner** [comment]
The issue in `marginal_effects` should now be resolved in the github version. The reason is that 

```
sort(as.character(-3:3))
[1] "-1" "-2" "-3" "0"  "1"  "2"  "3" 
```

which changed the factor ordering. 

For the same reason, the ordering is changed in `get_prior` but there, the alphabetical ordering of all priors is intentional and won't be changed (and doesn't really matter as the order of the user specified priors is arbitary).
