### ISSUE TITLE
Hurdle Model Syntax

### ISSUE THREAD

**Issue by piscis-bailey** [paul-buerkner/brms#586]
Hi Paul,

I am trying to code a hurdle model with family=hurdle_negbinomial. When I run the following:

get_prior(bf(no_eggs ~ legg_add + rank_all + (1|site) + offset(log(mass)),
             hu ~ legg_add + rank_all + (1|site),
             data = p_shp,
             family = hurdle_negbinomial()))

I get "Error: Expecting a single value when fixing parameters." I have also tried running just the model itself and I get the same error. I have scoured the internet but the only hurdle model examples I can find for brms are for zero-inflated distributions. In my case, I want to be able to specify different parameters for the logistic and negative binomial components of the hurdle model. I have successfully run separate logistic and negative binomial models, but for the purposes of prediction, I would like to predict from a hurdle model so that the covariance between the error in each sub-model is accounted for when drawing the 95% credible intervals.

Thanks for writing such an amazing package.

Cheers,

Colin

**Comment by paul-buerkner** [comment]
Could it be that you set a bracket incorrectly? That is, does the following work?

```
get_prior(bf(no_eggs ~ legg_add + rank_all + (1|site) + offset(log(mass)),
             hu ~ legg_add + rank_all + (1|site)),
          data = p_shp,
          family = hurdle_negbinomial())
```

In your version, `data` was passed to `bf` which does not make sense.

**Comment by piscis-bailey** [comment]
That's it! Thanks again for writing brms.
