### ISSUE TITLE
Access ggplot objects underlying `marginal_effects`

### ISSUE THREAD

**Issue by tomwallis** [paul-buerkner/brms#59]
I would like to be able to access the ggplot objects underlying the `marginal_effects` function (to e.g. change axis labels). The help doc for this function states the return value is "A list of ggplot objects one for each effect." When I run

``` r
plt <- marginal_effects(fit4, effects = "comparison_type:im_type")
```

the `plt` variable is a list, containing one item of class `brmsMarginalEffects`. This appears to contain a data frame. I suppose I could customise the ggplot by simply passing this dataframe to a new ggplot object, but is there any way to have the ggplot itself returned?

**Comment by tomwallis** [comment]
Actually, I think this is not necessary. It's easy, and more flexible, to just create a new ggplot object using the saved data frame:

```r
plt_dat <- marginal_effects(fit4, effects = "comparison_type:im_type")
plt_dat <- plt_dat$`comparison_type:im_type`

subj_marginals <- dat %>% 
  group_by(subj, comparison_type, im_type) %>% 
  summarise(pc = mean(correct, na.rm=TRUE),
            n = n())

ggplot(aes(x = comparison_type, y = Estimate, colour = im_type), data = plt_dat) +
  geom_point(aes(y = pc), data = subj_marginals, 
             position = position_dodge(width=0.2),
             alpha = 0.4) + 
  geom_pointrange(aes(ymax = upperCI, ymin = lowerCI), 
                  position = position_dodge(width=0.2)) + 
  xlab("Comparison Type") +
  scale_y_continuous(name = "p(c)", limits = c(0, 1))
```

**Comment by tomwallis** [comment]
Perhaps it would be useful to update the "value" doc for the `marginal_effects` function.

**Comment by paul-buerkner** [comment]
The trick is to save the output of the plot method:
```R
plots <- plot(marginal_effects(.))
# to avoid plotting:
plots <- plot(marginal_effects(.), do_plot = FALSE)
```
Previously, marginal_effects directly returned (at list of) ggplot objects, but users also wanted to extract the underlying data.frames and so I separated the plot from marginal_effects. I will amend the doc accordingly. The reason why 

```R
marginal_effects(.)
```
directly produces plots is that the `print` method implicitly calls `plot`.

**Comment by tomwallis** [comment]
Ah I see, thanks.
