### ISSUE TITLE
when I updated my OSX to Mojave, the brm() could not work

### ISSUE THREAD

**Issue by xm0557** [paul-buerkner/brms#590]

**Comment by xm0557** [comment]
"Error in if (nchar(CXX) == 0) { :" is always shown. And another warning: In system2(file.path(R.home(component = "bin"), "R"), args = paste("CMD config",  :
  运行命令''/Library/Frameworks/R.framework/Resources/bin/R' CMD config CXX14 2>/dev/null'的状态是72

**Comment by paul-buerkner** [comment]
This is unrelated to brms, but to the C++ toolchain of mojave. On https://discourse.mc-stan.org/ you should find existing threads discussing this issue.

**Comment by xm0557** [comment]
Yes，I am downloading new Xcode for mojave，old version doesnot work。Thank you and your fantastic brms！！！

Meng from China
发自我的 iPhone
