### ISSUE TITLE
error when using re_formula argument in bayes_R2()

### ISSUE THREAD

**Issue by emieldl** [paul-buerkner/brms#592]
Hi,

First of all, thank you for you amazing package!
I am trying to calculate an R² value using the bayes_R2 function without the random effect.

model <- brm(mpg ~ disp + (1|cyl), data = mtcars)

with_re <- bayes_R2(model)
without_re <- bayes_R2(model, re_formula = NA)

But when setting the re_formula = NA, I get the following error-message:

Error in standata.brmsfit(x, resp = resp, re_formula = NA, check_response = TRUE,  : 
  formal argument "re_formula" matched by multiple actual arguments

Is this an error or am I doing this wrong?

Thanks,
Best regards,
Emiel

**Comment by paul-buerkner** [comment]
Thanks for reporting this issue! It should now be fixed in the github version of brms to be installed via

```R
if (!requireNamespace("devtools")) {
  install.packages("devtools")
}
devtools::install_github("paul-buerkner/brms")
```
