### ISSUE TITLE
Running folds in parallel on windows using kfold?

### ISSUE THREAD

**Issue by gcolitti** [paul-buerkner/brms#593]
I'm a new brms user and new to Bayesian analysis in general. I have a couple of questions regarding `brms::kfold `. My understanding is that `kfold `will use the number of iterations and chains specified as arguments in the original fit model object per fold. Is this correct? When I use `kfold `it doesn't seem like the `chains = 3, cores = 3` arguments specified in the original fit object are used (based on my processor utilization during `kfold`). Also, I was wondering if the folds could be run in parallel in addition to the chains. But I'm hoping I can get at least one or the other to run in parallel to speed things up. Thanks!

**Comment by paul-buerkner** [comment]
Indeed, `cores` won't be re-used as the number of cores is (to my knowledge) not stored in the stanfit object. Instead, you should pass `cores` to `kfold` again. 

With respect to parallelization of the folds, this indeed a good idea and I will see if I can make this happen in the future.

**Comment by paul-buerkner** [comment]
Just added the option to run folds in parallel on the `loo-compare` branch of github using the **future** package. Here is an example:

```R
library(brms)
library(future)

fit <- brm(count ~ log_Base4_c * Trt + (1|patient),
           data = epilepsy, family = poisson())

plan(multiprocess)
(kf <- kfold(fit, chains = 1, K = 10))
```
