### ISSUE TITLE
"fixef and summary give different estimates when using a horseshoe prior 

### ISSUE THREAD

**Issue by rezagoljani** [paul-buerkner/brms#594]
Hello,
I used a horseshoe prior for my model.  the "summary" function gives me the desired results (many zeros under population level section). However, when I print population effects using "fixef" I get totally different results. I wonder if anybody had the same issue or have an answer for that!

Thanks!

**Comment by paul-buerkner** [comment]
This is just because `summary` by default rounds to 2 digits, while `fixef` does not. The horseshoe prior does not shrink values to **exactly** zero, but closer to zero. Hence, you should not expect exactly zero estimates.
