### ISSUE TITLE
Implement calculation of robustness regions

### ISSUE THREAD

**Issue by Zirys1** [paul-buerkner/brms#597]
Would it be possible to implement the possibility that robustness regions are calculated?

A robustness region specifies the range of expected effect sizes used when specifying the alternative model that support the same conclusion (e.g. evidence for H1, evidence for H0, or inconclusive outcomes).
Robustness regions give the lower and upper effect size for the alternative model that leads to the same conclusion given a certain Bayes factor threshold.

**Comment by paul-buerkner** [comment]
Bayes factors are not central to brms, but rather some nice addon. From this perspective, I don't think it makes sense (nor is it generally possible given the flexibility of the brms framework) to implement these kinds of robustness checks.
