### ISSUE TITLE
marginal_effects error

### ISSUE THREAD

**Issue by jamesrrae** [paul-buerkner/brms#598]
I'm running a monotonic model using the following call:

```
brm_multiple(cbind(Y1, Y2, Y3, Y4, Y5) ~ x1*mo(x2),
                   data=data,
                   family=Beta(),
                   prior = priors1,
                   seed=1234,
                   chains=2)
```
I then try calling `marginal effects` and get the following error message:

```
Error in seq_len(sdata$Jmo[i]) : 
  argument must be coercible to non-negative integer
In addition: Warning message:
In seq_len(sdata$Jmo[i]) :
 Show Traceback
 
 Rerun with Debug
 Error in seq_len(sdata$Jmo[i]) : 
  argument must be coercible to non-negative integer 
```

I thought this issue might be related to issue #570, so I tried to fix it by installing the dev version. This didn't fix the problem.

**Comment by paul-buerkner** [comment]
Do you have a minimal reproducible example for me?

**Comment by jamesrrae** [comment]
The exact example I encountered it with was a huge model that took hours and hours to run. However, I can try and make you a quick and reproducible example.

**Comment by paul-buerkner** [comment]
That would be awesome! And thanks for opening this issue by the way. 

I will also see if I can reproduce this on my own, but it's generally easier for me if I have just some code I can copy over the produces the error.

**Comment by paul-buerkner** [comment]
I just found an example that produces the error so no need for you to provide one this time:

```R
df <- data.frame(
  y = rnorm(10),
  y2 = rnorm(10),
  x = rnorm(10),
  z = sample(1:3, 10, TRUE)
)
df_list <- replicate(5, df, simplify = FALSE)

library(brms)
fit <- brm_multiple(mvbind(y, y2) ~ x*mo(z), data = df_list)
marginal_effects(fit)
```

**Comment by jamesrrae** [comment]
Ah! I just finished mine. Oh well,  thanks for making such a clean example to generate the error. I was trying to subset my data so that I kept all of the possible features that could be responsible for the error.

**Comment by paul-buerkner** [comment]
Just fixed the error in the github version of brms. :-)
