### ISSUE TITLE
Predict error when new factor levels found in the new_data

### ISSUE THREAD

**Issue by Amin-Tajgardoon** [paul-buerkner/brms#599]
Hi,
predict function seems to not support new factor levels in the predictor variables:

```
dat <- data.frame(y = rnorm(90), x = factor(rep(c("a", "b", "c"), each = 30)),
                  z = factor(rep(1:3, 30))) # x is a factor with levels = ["a", "b", "c"]

train = dat[ dat$x != "c",  ] # train data where x values are "a" or "b", no data from level "c"
test = dat[ dat$x == "c",  ] # test data where x values are only "c"

fit = brm(y ~ x + z, data = train)

posterior_predict(fit, newdata = test, allow_new_levels = T) #Error
```
The predict funtion throws an error:

```
Error: New factor levels are not allowed.
Levels allowed: 'a', 'b'
Levels found: 'a', 'b', 'c'
```
Is there a fix for this (beside creating dummy variables in train and test)?

Thank you

**Comment by paul-buerkner** [comment]
This is correct. There is no predictive model for levels of a population-level predictor. Accordingly, new levels can't be supported. Instead, `allow_new_levels` only applies to group-level effects.
