### ISSUE TITLE
Bayes factor for intercept only mixed logistic regression model vs. null model

### ISSUE THREAD

**Issue by kekecsz** [paul-buerkner/brms#601]
I would like to compute a Bayes factor for an intercept only mixed logistic regression model vs. null model.

This is for a study where each participant undergoes multiple trials with a success or fail outcome, and we would like to assess whether it is more likely that the data came from a world where M0 is true (chance for success is p = 0.5 in each trial), vs. a world where M1 is true (people have a different success rate than p = 0.5, and there may be some personal differences in success rate, i.e. random intercept).

According to these guides the following code should be used to compute the Bayes factor:
https://rpubs.com/lindeloev/bayes_factors
https://mvuorre.github.io/post/2017/03/21/bayes-factors-with-brms/

When I use the hypothesis() approach, the Evid.Ratio is NA

dat_1 = read.csv("https://raw.githubusercontent.com/kekecsz/Bayes-factor-different-distributions/master/data_all_%200.51_14000.csv")

fit2 <- brm(data_all_H1_pre2 ~ 0 + intercept + (0 + intercept|participant_ID), data = dat_1,
            family = bernoulli,
            control = list(adapt_delta = 0.90))

hypothesis(fit2, hypothesis = 'intercept = 0')

When I want to use the bayes_factor() function instead, the null model does not run, returning the error message:
SAMPLING FOR MODEL '7fd1e8370afde87f07b7e1f715ec714c' NOW (CHAIN 1).
[1] "Error in sampler$call_sampler(args_list[[i]]) : "                      
[2] "  Must use algorithm=\"Fixed_param\" for model that has no parameters."
[1] "error occurred during calling the sampler; sampling not done"

fit2_null <- brm(data_all_H1_pre2 ~ 0, data = dat_1,
            family = bernoulli,
            control = list(adapt_delta = 0.90))

bayes_factor(fit2, fit2_null) # can't run this, because the code above (fit2_null) returns an error.

How can one calculate the Bayes factor for this kind of model using brms?

**Comment by paul-buerkner** [comment]
Please ask brms related questions on https://discourse.mc-stan.org/ (using the "Interfaces - brms" tag) so that more users benefit from my (and others') answers.
