### ISSUE TITLE
n.samples in posterior_linpred

### ISSUE THREAD

**Issue by bachlaw** [paul-buerkner/brms#603]
Using brms 2.7 on both Linux and Windows, R 3.5.1, the `n.samples` option for `posterior_linpred` does not seem to actually limit the number of samples drawn.  Instead, it returns the entire number of original samples, regardless of what is specified.  Reprex:

```require(doParallel)
require(brms)

y <- sample(size = 1e5, c(0,1), replace=TRUE)
x1 <- rpois(1e5, 1)
x2 <- rnorm(1e5, 0,1)

df <- data.frame(y,x1, x2)

fit.1 <- brm(y ~ x1 + x2,
             family=bernoulli(),
             data=df,
             prior = set_prior("normal(0,2)", class="b"),
             cores=4, chains=4, iter=2000)

post.samples <- 100

post.1 <- posterior_linpred(fit.1, newdata=df, n.samples=post.samples)
post.2 <- (posterior_linpred(fit.1, newdata=df, n.samples=post.samples))[1:100,]

all.equal(nrow(post.1), nrow(post.2))
```
`post.1` returns 4000 samples, rather than the specified (and less memory-intensive) 100.

**Comment by paul-buerkner** [comment]
The argument is called `nsamples` in brms.

**Comment by bachlaw** [comment]
Thanks. Curse of the prefix. Carry on!

Sent from my iPhone

On Feb 13, 2019, at 1:49 AM, Paul-Christian Bürkner <notifications@github.com<mailto:notifications@github.com>> wrote:


The argument is called nsamples in brms.
