### ISSUE TITLE
can't run brm

### ISSUE THREAD

**Issue by chagag** [paul-buerkner/brms#604]
Hi - I am new to brm. I am trying to go through this implementation of statistical rethinking in brm - https://bookdown.org/connect/#/apps/1850/access

When I run this code below (which seems to work for other people) : 

b7.1 <-
  brm(data = d.A1, family = gaussian,
      log_gdp ~ 1 + rugged,
      prior = c(prior(normal(8, 100), class = Intercept),
                prior(normal(0, 1), class = b),
                prior(uniform(0, 10), class = sigma)),
      iter = 2000, warmup = 1000, chains = 4, cores = 4)

I get this error : 

Error in isFALSE(attr(x, "cmc", exact = TRUE)) : 
  could not find function "isFALSE"

I suspect that some other package is causing this but was wondering if you know by any chance. 

Thanks!

**Comment by paul-buerkner** [comment]
You R version is outdated. Please install the latest version from https://cran.r-project.org/
