### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by chagag** [paul-buerkner/brms#605]
Hi, sorry to bother you again but updated R as suggested and still can't get brms to work. 

There seems to be a file missing -when I run code I get this error:

Compiling the C++ model
restarting interrupted promise evaluationError in FUN(X[[i]], ...) : 
  cannot open file '~/R/win-library/3.5/stringr/data/Rdata.rdb': No such file or directory

Any suggestions on how to solve this? Thanks so much!
Amit

**Comment by paul-buerkner** [comment]
As you see from the error message, there seems to be a problem installing with the **stringr** package, which I don't think has something to do with brms.
