### ISSUE TITLE
Rejecting initial value

### ISSUE THREAD

**Issue by HenrikEckermann** [paul-buerkner/brms#609]
Hi Paul,

I try to fit the following model with brms:

```
brm(
    data = data,
    family = skew_normal(),
    formula = bf(y ~ 1+ factor1*factor2 + covariate1 + covariate2 + 
                                (1 + factor1*factor2 + covariate1 + covariate2), 
                          sigma ~ 1+ factor1*factor2 + covariate1 + covariate2),
    control = list(adapt_delta = 0.95, max_treedepth = 15)
)
```

In the output I get for some models  the info:

```
Chain 4: Rejecting initial value:
Chain 4:   Log probability evaluates to log(0), i.e. negative infinity.
Chain 4:   Stan can't start sampling from this initial value.
```

It seems that Stan just tries  different values by itself and so the model can be fitted and I get estimates. Are these estimates now reliable or do I have to change something about the model specification?

**Comment by paul-buerkner** [comment]
Please ask brms related questions on https://discourse.mc-stan.org/ rather than (directly) opening GitHub issues.
