### ISSUE TITLE
Error specifying a nested random effect (as in lme4)

### ISSUE THREAD

**Issue by tomwallis** [paul-buerkner/brms#61]
Can `brms` currently handle nested random effects?

I am trying to fit the following model, which fits fine using `lme4`:

```r
> glmer(correct ~ 1 + (1 | image_type / image_code), data = dat, family = binomial())
```

Running a (similar) model in `brms`:

```r
> get_prior(correct ~ 0.333 + 0.667 * inv_logit(eta), data = dat,
+            family = bernoulli("identity"),
+            nonlinear = list(eta ~ 1 + (1 | image_type / image_code)))
Error: Illegal grouping term: image_type/image_code 
 may contain only variable names combined by the symbol ':'
```

Ok, so try writing with the explicit interaction symbol:

```r
> get_prior(correct ~ 0.333 + 0.667 * inv_logit(eta), data = dat,
+            family = bernoulli("identity"),
+            nonlinear = list(eta ~ 1 + (1 | image_type) + (1 | image_type:image_code)))
Error in get(random$group[[i]], data) : 
  object 'image_type:image_code' not found
```

Am I specifying this incorrectly?

Thanks

**Comment by paul-buerkner** [comment]
You are specifying this correctly. I will take a look at whats happening (probably again because of my code refactoring a few days ago).

**Comment by paul-buerkner** [comment]
The explicit version should be working now (it just didn't work for non-linear models until now). I will open another issue to add support for the `/` symbol in random effects terms.

**Comment by tomwallis** [comment]
Great, thanks Paul. That's fixed.
