### ISSUE TITLE
Bug in bayes_R2 with re_formula argument?

### ISSUE THREAD

**Issue by strengejacke** [paul-buerkner/brms#610]
Hi Paul,
is `bayes_R2()` intended to accept the `re.form` or `re_formula`-argument? The docs say that arguments in `...` are passed down to `fitted()`. `re.form` does not change anything in the output for mixed models, `re_formula` throws an error. For _stanreg_ objects, you can get two different versions of R2, conditioned on random effects or on fixed effects only. See example below.

``` r
library(rstanarm)
library(brms)
library(lme4)
library(rstanarm)
data(sleepstudy)

m1 <- stan_lmer(Reaction ~ Days + (1 | Subject), data = sleepstudy, iter = 500, chains = 1)
m2 <- brm(Reaction ~ Days + (1 | Subject), data = sleepstudy, iter = 500, chains = 1)

# bayes R2 for stanreg
mean(as.vector(rstanarm::bayes_R2(m1, summary = FALSE, re.form = NULL)))
#> [1] 0.6969091
mean(as.vector(rstanarm::bayes_R2(m1, summary = FALSE, re.form = NA)))
#> [1] 0.2841374

# bayes R2 for brmsfit, re.form = NULL or NA, no difference
mean(as.vector(rstanarm::bayes_R2(m2, summary = FALSE, re.form = NULL)))
#> [1] 0.6989208
mean(as.vector(rstanarm::bayes_R2(m2, summary = FALSE, re.form = NA)))
#> [1] 0.6989208

mean(as.vector(rstanarm::bayes_R2(m2, summary = FALSE, re_formula = NULL)))
#> Error in standata.brmsfit(x, resp = resp, re_formula = NA, check_response = TRUE, : formal argument "re_formula" matched by multiple actual arguments
mean(as.vector(rstanarm::bayes_R2(m2, summary = FALSE, re_formula = NA)))
#> Error in standata.brmsfit(x, resp = resp, re_formula = NA, check_response = TRUE, : formal argument "re_formula" matched by multiple actual arguments
```

<sup>Created on 2019-02-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by paul-buerkner** [comment]
Thanks for opening this issue. `re.form` is not supposed to work in most brms post-processing methods. At some point, we will definitely have to align the argument names of brms, rstanarm, etc., though.

`re_formula` should work and already fixed this issue in the GitHub version of brms. See also #592

**Comment by strengejacke** [comment]
> `re.form` is not supposed to work in most brms post-processing methods

Yes, I knew that. Was just wondering if there's some kind of exception here, because `re_formula` did not work (though `re.form` is not documented in `fitted()`, so it was no surprise it had no effect).

Thanks for clarification!
