### ISSUE TITLE
brm_multiple bug

### ISSUE THREAD

**Issue by manuelreif** [paul-buerkner/brms#613]
Hi!
Thank you so much for brms - best package ever!

I am using `brms` in combination with `mice` (multilevel logistic regression). So I am doing multiple imputation first, and then I use `brm_multiple()` to go through the datasets. Unfortunately `brm_multiple()` produces an error:

```r  
Error in if (any(rhats > 1.1)) { : missing value where TRUE/FALSE needed
Calls: <Anonymous>
Execution halted
```
I debugged into this function and the error occures exactly here:
```r
  if (any(rhats > 1.1)) {
    warning2("Imputed model 1 did not converge.")
  }
 ```

because some of the Rhats are `NaN.`
I think this happens because some values of the L matrix have zero variance.

```r
Browse[1]> apply(DRAW_problem, 2, function(x) var(x))
  L_2[1,1]   L_2[2,1]   L_2[3,1]   L_2[1,2]   L_2[2,2]   L_2[3,2]   L_2[1,3]   L_2[2,3]   L_2[3,3] 
0.00000000 0.10208954 0.14876893 0.00000000 0.02481528 0.09752205 0.00000000 0.00000000 0.06967453 
```

I think this is not a problem since these components are supposed to be constant.
  https://discourse.mc-stan.org/t/convergence-failure-maybe-in-brms/4148/8

So I think the change below would fix it? Or could this cause any other problems? Or could the error occur on other positions in the code?
 
```r
if (any(na.omit(rhats) > 1.1)) {
  warning2("Imputed model 1 did not converge.")
}
```

Thank you!
  Manuel

**Comment by paul-buerkner** [comment]
Thanks for reporting this issue. The problem should be fixed now in the GitHub version of brms.
