### ISSUE TITLE
Add brm_multiple support for update

### ISSUE THREAD

**Issue by gcolitti** [paul-buerkner/brms#615]
It would be nice if `update ` supported models fit to a mice (multiple imputed) data set using `brm_multiple`. Ideally, support would include passing another mice data set to `update` in the following way:

data_mice1 <- mice(data1, m = 5, print = FALSE)
data_mice2 <- mice(data2, m = 5, print = FALSE)

model <- brm_multiple(data_mice1, formula)

updated_model <- update(model, newdata = data_mice2)

**Comment by paul-buerkner** [comment]
Good idea! Should now be working on GitHub.
