### ISSUE TITLE
VarCorr does not work for meta-analytic models

### ISSUE THREAD

**Issue by mscharkow** [paul-buerkner/brms#616]
VarCorr fails for models with an additional `se` term, yielding `Error in `colnames<-`(`*tmp*`, value = y$rnames) :   attempt to set 'colnames' on an object with less than two dimensions`.
This also breaks the `icc` function from the sjstats package. For now, reverting to brms 1.x helps.

Minimal example:
```{r}
library(brms)
library(metafor)
dat <- escalc(measure="ZCOR", ri=ri, ni=ni, data=dat.molloy2014)
dat$sei <- sqrt(dat$vi)
m0 <- brm(yi | se(sei) ~ 1 + (1 | authors), data = dat)
VarCorr(m0)
```

**Comment by paul-buerkner** [comment]
Thanks! should now be fixed on GitHub.
