### ISSUE TITLE
custom family for neg_binomial_2

### ISSUE THREAD

**Issue by jnmaloof** [paul-buerkner/brms#620]
Hi

I am trying to create a custom family for the alternative negative binomial distribution available in stan (https://mc-stan.org/docs/2_18/functions-reference/nbalt.html), where the distribution is defined in terms of the mean, mu, and the overdispersion parameter, phi.

I am interested in this because I want to fit a distributional model where the value of phi depends on model predictors.

I have been trying to follow the "custom families" vignette.  Because all of the functions for this alternative parameterization already exist in Stan, this should be easier than the vignette, yet I am stuck.

I have

```
neg_binomial_2 <- custom_family("neg_binomial_2",
                                dpars = c("mu", "phi"),
                                links =c("log", "log"),
                                lb = c(0, 0),
                                type = "int")
```

And that works fine.

I shouldn't need to define any stanfuns since they already exist.  But I am stuck at trying to define the log likelihood and predict functions.

```
log_lik_neg_binomial_2 <- function(i, draws) {
  mu <- draws$dpars$mu[, i]
  phi <- draws$dpars$phi[, i]
  y <- draws$data$Y[i]
  neg_binomial_2_lpmf(y, mu, phi)
}
```

This doesn't work because R doesn't know about the stan function  `neg_binomial_2_lpmf(y, mu, phi)`.  How can I use this function (or what should i be doing instead)?

I imagine the answer is super-simple; apologies I am quite new to doing anything custom with brms or stan...

Thanks,

Julin

**Comment by paul-buerkner** [comment]
You don't need a custom family for this, just use `family = negbinomial()`. In the future, please ask brms related questions on https://discourse.mc-stan.org/
