### ISSUE TITLE
Allow 'identity' link function for nonlinear ordinal models

### ISSUE THREAD

**Issue by mvuorre** [paul-buerkner/brms#624]
As nonlinear models were just implemented for ordinal models (#623, brilliant!), would it also be possible to allow the identity link for them? This would be useful when the link function is already in the formula as in the examples here: <https://cran.rstudio.com/web/packages/brms/vignettes/brms_nonlinear.html>

Cheers

**Comment by paul-buerkner** [comment]
The short answer is "No". The long answer is that if someone has a proposal on how to handle the thresholds in this case, maybe we can make it possible.

**Comment by mvuorre** [comment]
OK, I'll have to think about it some more. Thanks!

**Comment by paul-buerkner** [comment]
After thinking of this a little more I really don't see a way of implementing this in a reasonable manner. If a custom ordinal family is required, the `custom_family` would be a better solution anyway I guess.
