### ISSUE TITLE
Mistake in help for hypothesis

### ISSUE THREAD

**Issue by dannagifford** [paul-buerkner/brms#627]
Hello, the help for hypothesis() states that brm() option 'sample_prior' must be set to TRUE for Bayes factor to be calculated. However, the help for brm() states that sample_prior takes values in  c("no", "yes", "only"). Is sample_prior meant to be specified as a boolean or a character?

The text in ?hypothesis:
"...argument ‘sample_prior’ of function ‘brm’ must be set to ‘TRUE’."

Edit: also in the Examples:
     ## fit a linear mixed effects models
     fit <- brm(time ~ age + sex + disease + (1 + age|patient),
                data = kidney, family = lognormal(),
                prior = prior, sample_prior = TRUE,   # <----- HERE
                control = list(adapt_delta = 0.95))

**Comment by paul-buerkner** [comment]
Both works, where `TRUE` means `"yes"` and `FALSE` means `"no"`, but I fully agree I need to change the documentation to avoid confusion (in fact I just changed it). Thank you for the suggestion!
