### ISSUE TITLE
Vastly different Bayes Factors based on scale of outcome variabe

### ISSUE THREAD

**Issue by JAQuent** [paul-buerkner/brms#628]
I have the problem that I want to state the evidence that my predictor x is related to y so I want to compare the model includig x with the model that just includes the intercept. Now, I noticed that the BF varies massively depending the scale of my outcome variable, while the t-value (beta/sd) of x is more or less the same. This is illustrated in the example below where I just multiple y with 100. 

Generating data:
```
set.seed(10)
n     <- 20
beta0 <- 4.7
beta1 <- 0.5
x     <- rnorm(n, mean = 10, sd = 20)
e     <- rnorm(n, mean = 0, sd = 10)
y     <- beta0 + beta1*x + e
df    <- data.frame(x = x,
                 x_scale = scale(x),
                 y = y,
                 y100 = y * 100)
```

Fitting models:
```
effM_xscale_y  <- brm(y ~ x_scale,
             data = df,
             save_all_pars = TRUE,
             control = list(adapt_delta = 0.95))

effM_xscale_y100  <- brm(y100 ~ x_scale,
                   data = df,
                   save_all_pars = TRUE,
                   control = list(adapt_delta = 0.95))
nullM_y <- brm(y ~ 1,
             data = df,
             save_all_pars = TRUE,
             control = list(adapt_delta = 0.95))

nullM_y100 <- brm(y100 ~ 1,
             data = df,
             save_all_pars = TRUE,
             control = list(adapt_delta = 0.95))
```

Calculating BFs:
```
BF1 <- bayes_factor(effM_xscale_y, nullM_y)
BF2 <- bayes_factor(effM_xscale_y100, nullM_y100)
```

To my understanding the BFs should be more or less the same but BF1 is 725.93713, while BF2 is 76790.32216. Am I missing something? The fixed effect show that the t-values (beta/sd) are comparable: 3.23818 vs. 3.216721. In my real data set the difference in BF is 0.5 to 59.

**Comment by paul-buerkner** [comment]
You did not specify any prior on the regression coefficients. Thus, the Bayes factor won't make much sense at all.

**Comment by JAQuent** [comment]
Ah, thank you for your really quick response. What is then the minimum of information that I need to provide that I can make a meaningful inference from the BF or is this an issue special to intercept-only models. 
I now do get the same BF values if I use "normal(0,1000)" vs "normal(0,100)" as priors. 

In my real data set x is scaled but y goes from 0 to 1. Is it enough to provide normal(0.5, 0.15) as a priors for both the intercept and the slope? Sorry, for raising the issue in the first place as I am clearly lacking informtion. Is there source you'd recommend to read up on?

**Comment by paul-buerkner** [comment]
There is no general answer to that. Setting reasonable priors for use with Bayes factors is hard. You may want to look open a thread on https://discourse.mc-stan.org/ and see if someone has suggestions for your specific case.
