### ISSUE TITLE
Contribution of Each Term in Additive Model

### ISSUE THREAD

**Issue by BayesBro** [paul-buerkner/brms#629]
Suppose I have a model like `brm(y ~ s(x1) + s(x2) + x3)`. For each observation, I would like to see the contribution of each of the additive components to the overall predicted value. In other words, I would like to be able to decompose a prediction into the contribution from each of the terms in the model. Is this possible to do with brms?

**Comment by paul-buerkner** [comment]
brms related questions are better asked at https://discourse.mc-stan.org for greater visibility.
