### ISSUE TITLE
Formula problem in brms (fitting Gaussian shape curve)

### ISSUE THREAD

**Issue by tankwin08** [paul-buerkner/brms#63]
Hey Paul,
I saw the #46 and my code also gave the same error, but it seems not the same problem. I used the brms to fit the Gaussian shape (non-linear model). it works well when just had one peak, formula is 
y ~ A1 * exp(-(x - u1)^2/(2 * sigma1^2)) 
The two peaks formula I generated is:
y ~ A1 * exp(-(x - u1)^2/(2 * sigma1^2)) + A2 * exp(-(x - u2)^2/(2 * 
    sigma2^2))
<environment: 0x0000000005c6bfc8>
### # when I try to fit two peaks, it gave me the following error:
SYNTAX ERROR, MESSAGE(S) FROM PARSER:
ERROR at line 50

 48:      for (n in 1:N) { 
 49:        // compute non-linear predictor 
 50:     #    eta[n] <- (eta_A1[n] * exp( - (C[n, 1] - eta_u1[n]) ^ 2 / (2 * eta_sigma1[n] ^ 2)) + eta_A2[n] * exp( - (C[n, 1] - eta_u2[n]) ^ 2 / (2 *); 
                                                                                                                                                    ^
 51:      } 

PARSER EXPECTED: <expression>
Error in stanc(model_code = paste(program, collapse = "\n"), model_name = model_cppname,  : 
  failed to parse Stan model 'file1c201d0d57a3' due to the above error.
From the error, it looks like beacuse my formula jump to the second line, and when computing the non-linear predictor, it just used the formula in the first row. I am still trying ways to figure out.  I wonder if too many parameters may be a problem for the nolinear model.
This is a awesome package, I also had data has three peaks, four peaks. Do you have any suggestion? Thanks so much for your attention!

**Comment by paul-buerkner** [comment]
Thanks for reporting this issue! I assume that this was already fixed in #46. However, this fix is not part of the latest CRAN version yet. Does it work if you run the model with the latest dev version of brms from github? You can install it via `devtools::install_github("paul-buerkner/brms")`.

**Comment by tankwin08** [comment]
Awesome, I think I figure out. Thanks very much for your suggestions, Paul.

**Comment by paul-buerkner** [comment]
You are welcome. :-)
