### ISSUE TITLE
marginal_effects() seems to ignore ask=FALSE

### ISSUE THREAD

**Issue by jmgirard** [paul-buerkner/brms#633]
I am trying to include `marginal_effects()` plots in my RNotebook and would like to prevent the function from asking me to Hit <Return> to see the next plot. From the documentation, it seems that setting `ask = FALSE` should accomplish this. However, it doesn't seem to.
```r
marginal_effects(fit, plot = TRUE, ask = FALSE)
#> Hit <Return> to see next plot: 
#> Hit <Return> to see next plot: 
#> Hit <Return> to see next plot: 
#> Hit <Return> to see next plot: 
```

**Comment by paul-buerkner** [comment]
`plot` and `ask` are arguments of the corresponding plot method not of `marginal_effects` itself:

```R
plot(marginal_effects(fit), plot = TRUE, ask = FALSE)
```
