### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by LailaKF** [paul-buerkner/brms#634]
Hi Paul,

For some reason I can't install the brms package.

#######################################################################
if (!requireNamespace("devtools")) {
  install.packages("devtools")
}
devtools::install_github("paul-buerkner/brms")
Downloading GitHub repo paul-buerkner/brms@master
from URL https://api.github.com/repos/paul-buerkner/brms/zipball/master
Installing brms
"C:/PROGRA~1/R/R-34~1.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/Laila_KF/AppData/Local/Temp/Rtmp4CJYC7/devtools81c5529e21/paul-buerkner-brms-ebaf754"  \
  --library="C:/Users/Laila_KF/Documents/R/win-library/3.4" --install-tests 
ERROR: dependencies 'bridgesampling', 'nleqslv', 'future' are not available for package 'brms'
>removing 'C:/Users/Laila_KF/Documents/R/win-library/3.4/brms'
>Installation failed: Command failed (1)
#######################################################################

Tried to install the packages 'bridgesampling', 'nleqslv', 'future'  separately, but that also didn't solve the problem...do you happen to have any ideas what might be wrong?

Thanks a lot in advance!
Best,
Laila

**Comment by LailaKF** [comment]
Ok, just solved it by changing the CRAN mirror from Uni Muenster to some other mirror...

**Comment by paul-buerkner** [comment]
Glad you could solve it.
