### ISSUE TITLE
measurement error me() models not functioning?

### ISSUE THREAD

**Issue by jonnations** [paul-buerkner/brms#635]
Hi,

Working in Rstudio 1.1.456 and brms 2.8.0

I am working with several models that include sd values. They have all run properly in the past, and I was able to plot marginal effects, etc. Now they are throwing an error:
`Error in me(x1, sdx) : 
  Sorry, meausrement error type classical not yet implemented`

If I restart RStudio I can get the first model to run, then if I try to plot the marginal_effects() I receive this same error. 

As an example I am using the scripts from the me() function in the documentation.
`# sample some data
N <- 100`
`dat <- data.frame(
  y = rnorm(N), x1 = rnorm(N), 
  x2 = rnorm(N), sdx = abs(rnorm(N, 1))
 )`

`fit1 <- brm(y ~ me(x1, sdx) + me(x2, sdx), data = dat, save_mevars = TRUE)`
Runs properly. 
`plot(marginal_effects(fit1))`
`Error in me(x1, sdx) : 
  Sorry, meausrement error type classical not yet implemented`

Then re-running the same model:
`fit1 <- brm(y ~ me(x1, sdx) + me(x2, sdx), data = dat, save_mevars = TRUE)`
`Error in me(x1, sdx) : 
  Sorry, meausrement error type classical not yet implemented`

Any thoughts on why this is happening?

**Comment by paul-buerkner** [comment]
this error is not from brms. I guess you have loaded another package after
loading brms that also have an me() function an this masked the brms
function. what does running me (without brackets our arguments) return?

Jonathan A. Nations <notifications@github.com> schrieb am Mo., 8. Apr.
2019, 19:12:

**Comment by jonnations** [comment]
It returns the same error.
`Error in me() : 
  Sorry, meausrement error type classical not yet implemented`

**Comment by jonnations** [comment]
Ok, it seems to be coming from somewhere in MCMCglmm. Everything works fine until this is loaded. I was using a few functions from this package for phylogenetic applications, but I will now just use MCMCglmm::inverseA() instead of loading the whole thing. Thank you!
