### ISSUE TITLE
marginal_effects plots and measurement error

### ISSUE THREAD

**Issue by jonnations** [paul-buerkner/brms#636]
Hi Paul,

Similar to this issue #163 , I am having a problem with measurement error and positive values. This time the model runs, but I get an error when plotting the marginal_effects. The actual data from my model are included below. The sd values are small, but they are all positive. As you can see the measurements themselves are quite small. 

I have other measurements in my dataset that run and plot without any problems. Many of these other measurements have a few small sdx values, but this `x` measurement has the most. I artificially switched all values <0.1 to 0.1, and this didn't fix the problem.

Thank you for looking at this! 

`fit1 <- brm(y~me(x, xsd), data = d)`
`plot(marginal_effects(fit1)`
Error: Measurement error should be positive.

Actual data for minimally reproducible example:

xsd = c(0.011697664, 0.012078188, 0.014930732, 0.016025176, 0.025747496, 0.027845842, 0.032291029, 0.036123345, 0.036167316, 0.045783621, 0.048654259, 0.05609418, 0.059134114, 0.066223495, 0.07924126, 0.09430966, 0.142904636, 0.149845176, 0.155512013, 0.178069322, 0.200994772, 0.201257528, 0.201513698, 0.202378701, 0.204367528, 0.205357025, 0.225664824, 0.278167693, 0.939051798, 1.207835279, 1.677092523)
x = c(0.096899633, 0.0534159, 0.052806035, 0.304772773, 0.080968143, 0.108036803, 0.65928368, 0.087181223, 0.520392172, 0.111019565, 0.505119224, 0.068984984, 0.057373505, 0.335897863, 0.193871517, 0.11008836, 0.531210549, 0.907356441, 0.215181804, 0.855841543, 0.441491876, 0.999549197, 0.39775861, 0.38505464, 0.462391789, 0.338213922, 0.478186445, 0.597656537, 1.800666199, 3.398143882, 3.418043948)
y = c(2.708050, 3.555348, 3.912023, 3.401197, 3.688879, 2.484907, 3.555348, 3.555348, 4.905275, 4.174387, 2.995732, 4.828314, 3.555348, 4.605170, 3.806662, 2.708050, 2.995732, 4.553877, 2.484907, 3.020425, 3.555348, 4.248495, 3.401197, 4.007333, 2.708050, 2.890372, 2.140066, 4.248495, 4.094345, 4.174387, 4.787492)

d <- data.frame(y, x, xsd)

**Comment by paul-buerkner** [comment]
Thanks for reporting this issue and for providing a reproducible example! 
It actually took me a refactor to fix it, but this refactor was long overdue anyway. 
In the github version of brms, it should now work as expected.

**Comment by jonnations** [comment]
Thanks Paul! The model works and marginal_effects plots without error. However, the plots are different than they were before, as they only include the mean ab_line and CI ribbon and not the three colors for the me() values. This is fine for my needs, but I just wanted to let you know.
See pics below. Top is the new plot, bottom is the old one.

![me()_new](https://user-images.githubusercontent.com/16668795/55831055-e05a6600-5ad7-11e9-9c47-1882c45eccd9.png)
![me()_old](https://user-images.githubusercontent.com/16668795/55831057-e05a6600-5ad7-11e9-8a80-8414b9786c5f.png)

**Comment by paul-buerkner** [comment]
Thanks! Yes, this change is intentional.
