### ISSUE TITLE
Bayes_R2 feature requests

### ISSUE THREAD

**Issue by andymilne** [paul-buerkner/brms#639]
Regarding the bayes_R2 and loo_R2. I would be interested in two new features, if they are possible.

Firstly, that they work for ordinal models. It is very likely I am making conceptual errors here (not really understanding how these things work under the hood), but would it be possible to calculate an ordinal R2 by treating each ordinal level as a binary response -- so for N observations of an ordinal variable with K levels, the R2 would be calculated like in a binary regression with KN observations?

Secondly, allowing for covariate grouping in binary and ordinal models (as discussed in Hosmer and Lemeshow's Applied Logistic Regression book). For example, with a binary response, one may be interested in getting the R2 for how well the model captures differences between covariate groups (e.g., grouping together observations whose predictors, or some of whose predictors, have the same values). So the comparison is between averaged predictions and observations -- averages taken within each covariate group.

**Comment by paul-buerkner** [comment]
Hey. I am not a fan of the first proposal as ordinal categories are not necessarily equidistant and I think it's better to reflect this by not allowing bayes_R2 for ordinal models altogether (regardless of how it's computed exactly). Also, this would require a lot of special case coding is not justified by the provided feature.

I don't have access to this book currently and without looking at the method in detail, I can't say much about whether that could be sensible (likely it's too specific for brms though).

**Comment by andymilne** [comment]
I had thought my initial suggestion was a way of calculating R2 whilst avoiding the non-equidistant nature of ordinal categories, but I am probably missing something.

**Comment by paul-buerkner** [comment]
Hmm, then you need to explain to me how you would create the binary responses exactly.

**Comment by andymilne** [comment]
Well, say you have 3 levels, then every response is coded as 1 0 0 (for level 1), or 0 1 0 (for level 2), or 0 0 1 (for level 3). The fitted model should be a corresponding posterior distribution of probabilities for each of the three levels. And these form the basis of the comparison between predicted and observed.

**Comment by paul-buerkner** [comment]
I see. This would then also generalize to categorical models, I guess, if we decide to work on the predicted probabilities. If this is a reasonable approach, I cannot tell right now.

For instance, it is sufficient to know the probabilities of K - 1 category since the last probability is just `1 - sum(<all other>)`. We could either ignore this and predict all categories, but that would then also imply to predict both 0 and 1 in binary models, which seems different from what I have seen so far in the literature. Or, we could choose K - 1 categories which are to be predicted. This raises the immediate question if the computed R2 is the same regardless of which category is excluded. 

Perhaps someone has already thought about theses questions. Otherwise someone has to do it before we implement anything without understanding its implications.

**Comment by andymilne** [comment]
Yes, I had the same concern myself but do not have sufficient knowledge to answer those questions. It seems an obvious (possible) solution for ordinal/categorical models, so I suspect it must have been considered somewhere before.

**Comment by paul-buerkner** [comment]
An option for the ordinal models would be to handle it the same way as in `marginal_effects`, that is to
compute results as if the categories were equidistant but issuing a warning that doing so is probably not
a good idea.

**Comment by andymilne** [comment]
So long as there is a warning, that sounds pretty reasonable.

**Comment by paul-buerkner** [comment]
Ordinal models are now allowed in `bayes_R2` (with a warning). The idea of Hosmer and Lemeshow appears to specific to me given the general purpose of brms. Accordingly, I don't think it will be worth implementing.

**Comment by andymilne** [comment]
Thank you Paul. It works as expected. Is loo_R2 feasible in this context too?

**Comment by paul-buerkner** [comment]
Good point. Just change that as well.

**Comment by andymilne** [comment]
There is another option for ordinal models that does not require making the ordinal levels equidistant. The method is closely related to those Gelman, et al.'s Bayes_R2 paper http://www.stat.columbia.edu/~gelman/research/unpublished/bayes_R2_v3.pdf. This method is equally applicable to linear, bernoulli, and ordinal, and is a Bayesian version of McKelvey and Zavoina's R2.

Ignoring sampling from the posterior for simplicity, the Bayes_R2 is defined in Gelman et al. as var(mdl) / (var(mdl) + var(errors)). The var(errors) can be simply the model's estimate of sigma, or obtained from the actual residuals (Aki Vehtari's simulations https://avehtari.github.io/bayes_R2/bayes_R2.html show these to be very comparable). 

In Gelman, et al., they suggest that when doing logistic regression, the variances should be calculated on the response scale; that is, the observations {0, 1}, the predictions are [0, 1] (no reason is given in the paper as to why this suggestion is made). However, what if the variances are calculated on the linear scale? This is the method suggested way back by McKelvey and Zavoina (for a summary, see https://stats.idre.ucla.edu/other/mult-pkg/faq/general/faq-what-are-pseudo-r-squareds/). This "R2mz" is the R2 on the latent scale underlying the actual responses. In much psychological/perceptual research, the underlying latent scale is actually the key item of interest. In simulations, http://www.klausfzimmermann.de/files/19982016/pdf/31_PseudoR2s_intheOrdinal_Journalofmathematical_sociology_1992.pdf and https://link.springer.com/article/10.1007/BF01102759, it is shown that the R2mz very closely approximates the underlying latent-scale R2.

Using this method in bernoulli or ordinal models with probit links is simply given by var(mdl) / (var(mdl) + 1); for logit link by var(mdl) / (var(mdl) + pi^2 / 3). The following function (if of interest to any one, and apologies for clunky coding) calculates a Bayesian version of R2mz and works with linear, bernoulli, and ordinal models:

```
bayes_R2_mz <- function(fit, ...) {
  y_pred <- fitted(fit, scale = "linear", summary = FALSE, ...)
  var_fit <- apply(y_pred, 1, var)
  if (fit$formula$family$family == "cumulative" ||
      fit$formula$family$family == "bernoulli") {
    if (fit$formula$family$link == "probit" || 
        fit$formula$family$link == "probit_approx") {
      var_res <- 1
    }
    else if (fit$formula$family$link == "logit") {
      var_res <- pi^2 / 3 
    }
  } 
  else {
    sum_fit <- summary(fit)
    sig_res <- sum_fit$spec_pars["sigma","Estimate"]
    var_res <- sig_res^2
  } 
  R2_mz <- var_fit / (var_fit + var_res)
  print(
    data.frame(
      Estimate = mean(R2_mz), 
      Est.Error = sd(R2_mz), 
      Q2.5 = quantile(R2_mz, 0.025),
      Q97.5 = quantile(R2_mz, 0.975),
      row.names = "R2_mz"
    )
  )
  return(R2_mz)
}

# Demonstration
mtcars <- mtcars %>%
  mutate(cyl = ordered(cyl))
m_cyl <- brm(cyl ~ mpg, data = mtcars, family = cumulative(link = "logit"))

rsq_bayes <- 
  bayes_R2_mz(m_cyl)
hist(rsq_bayes, xlim=c(0,1))
```

**Comment by jlevy44** [comment]
I am a fan of the above implementation. Is there potential to add this as a standard package feature for ordinal models?
