### ISSUE TITLE
Error in sampling large random effects structure; suggestions?

### ISSUE THREAD

**Issue by tomwallis** [paul-buerkner/brms#64]
Apologies if this is better suited to the Stan users mailing list.

I'm trying to fit a model with 26 fixed-effects coefficients with the "maximal" random effects covariance structure (that is, each of the 26 coefficients can be level-dependent, and I also model the correlations). When I try to sample this model I get the following error from Stan:

```r 
SAMPLING FOR MODEL 'bernoulli(identity) brms-model' NOW (CHAIN 1).
  [1] "Error : Rejecting initial value:"                                                                     
  [2] "  Log probability evaluates to log(0), i.e. negative infinity."                                       
  [3] "  Stan can't start sampling from this initial value."                                
``` 
This error is reported by `brm` as simply `error occurred during calling the sampler; sampling not done` -- to find the underlying Stan error I used `cluster = 1` and `verbose = TRUE`.

The error occurs for all samples, which then obviously fails. If I only include a random global intercept the model is estimated fine, but including more than one or two of the non-intercept fixed effects into the random factor seems to cause the sampling issue. I'm obviously mispecifying something but I'm not sure what. Any help appreciated.

**Comment by paul-buerkner** [comment]
You could try the following: In `brm` set `inits = 0` or, alternatively, `init_r` to a very small value to try to initialize the model at (or very close to) zero. If this fails, you could try rescaling (standardizing) predictors. Even if we get the model to initialize, modeling a 26 x 26 random effects correlation matrix will likely be difficult for Stan.

**Comment by tomwallis** [comment]
Setting `inits = 0` seems to avoid the problem. Model is sampling away.

I suppose here I need to be very careful interpreting the Rhat estimates?

**Comment by paul-buerkner** [comment]
I don't expect particularily good convergence just because the correlation matrix is so huge, but one never knows. In any case, you should take a closer look at the Rhats and the effective sample size. Setting `inits = 0`, however, shouldn't really change anything related to the Rhats.

**Comment by tomwallis** [comment]
In my understanding, the Rhat statistics depend on the chains being initialised randomly – otherwise it's less surprising than they converge, no?

From Gelman & Rubin (1992):

> Our recommended strategy is to use several independent sequences, with starting points sampled from an overdispersed distribution.

In any case, I am being conservative with the number of samples I'm running to try to ensure that the Rhats are converged. I may end up going with a smaller model in any case (or just not modelling the RE covariance structure).

**Comment by paul-buerkner** [comment]
I don't know excactly how Stan introduces randomness when `inits = 0`, but I don't think that the chains necessarly converge better when starting from the same point. After all, they may be starting from very different points after warmup has been completed. I might be wrong here, so that it would possibly be a good questions for the Stan users list. 

By the way, did you manage to fit your model with so many correlated random effects?

**Comment by tomwallis** [comment]
Good idea. I will ask the list.

The model fits (20k samples per chain) and most of the parameters have Rhat = 1, but there are still a couple that aren't converged. Will run for longer.
