### ISSUE TITLE
Left side of the model formula with measurement error

### ISSUE THREAD

**Issue by wzel** [paul-buerkner/brms#643]
From `me()` documentation:

> Specify predictors with measurement error.
> [...]
> `fit1 <- brm(y ~ me(x1, sdx) + me(x2, sdx), data = dat, save_mevars = TRUE)`

How about extending `me()` beyond predictors, so that something like

> `fit1 <- brm(me(y, sdx) ~ x1 + x2, data = dat, save_mevars = TRUE)`

were legal? I am currently tackling it using an offset:

> `fit1 <- brm(y ~ x1 + x2 + offset(me(0, sdx)), data = dat, save_mevars = TRUE)`,

but this may be incorrect, especially if you consider a log-normal model:

> `fit <- brm(y ~ x1 + x2 + offset(exp(me(0, sdx))), data = dat, save_memvars = TRUE, family = brmsfamily("lognormal"))` (?).

Plus, this hack cannot be used for multivariate models, where the dependent variables are associated with different measurement errors.

Thank you for having a look and for the great package!

**Comment by paul-buerkner** [comment]
It's already possible via `mi` terms (although perhaps not super easy to find in the documentation.

```
brm(y | mi(sdx) ~ x1 + x2, data = dat, save_mevars = TRUE)
```

**Comment by wzel** [comment]
Thank you very much!
