### ISSUE TITLE
Rename the 'fitted' method

### ISSUE THREAD

**Issue by paul-buerkner** [paul-buerkner/brms#644]
I know that multiple people including @jgabry and @bgoodri dislike the name `fitted` used in brms to compute expected values of the posterior predictive distribution, and I agree. However, we still need a good new name to take the place of `fitted`. How does, for instance, `posterior_expect` sound to you? I am open to suggestions.

**Comment by bgoodri** [comment]
Do we want to put a S3 generic into rstantools?

**Comment by paul-buerkner** [comment]
That would be ideal, yes.

**Comment by bgoodri** [comment]
I guess my main concern is that if it is called `posterior_expect` then it
should actually be an expectation as opposed to evaluating the predictions
at the expectation of the coefficients (in nonlinear or generalized linear
models).

**Comment by paul-buerkner** [comment]
What do you mean by "expectation of the coefficients"? It's not that `fitted.brmsfit` took the means of the coeffiecients and transformed them somehow, but I guess this is not what you ment.

**Comment by bgoodri** [comment]
Right, what rstanarm is doing with fitted is using the posterior medians to
get a prediction, which doesn't make a lot of sense in the Bayesian context
but we needed something if people had code that was calling fitted or
predict after glm(). So, if we put posterior_expect into rstantools and
wrote methods for it, it should be an actual expectation. But I don't know
if posterior_expectation really conveys that it is the expectation of the
posterior predictive distribution or different say than what
get_posterior_mean does in rstan.

**Comment by paul-buerkner** [comment]
What about `pp_expect` or `pp_expectation`. We are using `pp` as abbreviation for posterior predictions in other places anyway.

**Comment by bgoodri** [comment]
That could work

**Comment by paul-buerkner** [comment]
Great! Of those two, I would prefer `pp_expect`, I think. @jgabry what is your opinion on this?

**Comment by jgabry** [comment]
Is this just colMeans(posterior_predict(fit))? If so I’m not sure it needs a method itself, but I’m not opposed to it and I’m fine with that name.

**Comment by paul-buerkner** [comment]
It's like `posterior_linpred(..., transform = TRUE)` so it should be easy to make a method in rstanarm as well.

**Comment by jgabry** [comment]
Oh I see. Yeah I’m fine with that. Can you open an rstantools issue? Or feel free to just add it to rstantools if if you want.

**Comment by paul-buerkner** [comment]
Sure. I guess I just make a PR for the generic.

**Comment by statwonk** [comment]
I think the `lognormal` might be an example of what @bgoodri means. `mu` is the median not the expected value.

**Comment by paul-buerkner** [comment]
yes but fitted is designed to always return the mean (see the corresponding
code on GitHub in fitted.R).

Christopher Peters <notifications@github.com> schrieb am So., 28. Apr.
2019, 23:04:

**Comment by elliottmorris** [comment]
Hi @paul-buerkner. 

Sorry, but after these changes I cannot figure out how to recreate the old output from `posterior_linpred` using ``ppc_expect``. 

Specifically, I used to run:

```
draws <- posterior_linpred(model,
    newdata=df,
    draws=1000,
    allow_new_levels=T,
    transform=T)
```

But the following is not yielding the same results:
```
draws <- brms::pp_expect(model,
    newdata=df,
    nsamples=1000,
    allow_new_levels =T,
    scale='linear')
```
I'd be grateful for any help you can provide.

E

**Comment by paul-buerkner** [comment]
You could still use posterior_linpred or not?

G. Elliott Morris <notifications@github.com> schrieb am Fr., 24. Jan. 2020,
19:36:

**Comment by elliottmorris** [comment]
You're saying I shouldn't make the switch over? Warnings say it's deprecated right?

Either way, shouldn't I be able to recreate posterior predictions for the linear predictor with the new function?

**Comment by paul-buerkner** [comment]
Oh posterior_linpred shouldn't be deprecated. I will check it out later on.
Do you have a reprex for the non equal behavior?

G. Elliott Morris <notifications@github.com> schrieb am Fr., 24. Jan. 2020,
19:43:

**Comment by elliottmorris** [comment]
I will put one together if by next week I still can't replicate across models. Thanks Paul

**Comment by elliottmorris** [comment]
Yes it seems that the `posterior_linpred` function has changed pretty dramatically over the past few months. 

It used to return a draw of the linear predictor for every specified run. Now it looks to be returning a draw from the distribution _of the average_ of the linear predictor. That's pretty different functionality. 

What am I missing? Are these changes documented somewhere?

**Comment by paul-buerkner** [comment]
If that is the case that this is unintended. It should have stayed the
same. Once I am home tonight I will take look.

G. Elliott Morris <notifications@github.com> schrieb am Fr., 24. Jan. 2020,
20:44:

**Comment by elliottmorris** [comment]
Excellent. Thanks again.

**Comment by elliottmorris** [comment]
Sorry just an FYI again. It seems like the behavior changed between 2.9 and 2.10, not 2.11.

**Comment by paul-buerkner** [comment]
`pp_expect(..., scale = "linear")` does not work because pp_expect is supposed to always return the expected value of the posterior predictive distribution and thus has no (user facing) `scale` argument. Existing functions contiue to work in the same way. For instance,

```R
posterior_linpred(model)
fitted(model, scale = "linear", summary = FALSE)
```

yield the same results.

**Comment by elliottmorris** [comment]
Okay, that’s useful context.  Thanks.

The functionality of `posterior_linpred()` still seems to have changed significantly between brms 2.9 and 2.10-11. I’ll put together a reprex, unless you know why off the top of your head?

(Again, the difference I’m seeing looks to be a much smaller range of predictions for each observation in newdata, or something to that effect.)

**Comment by paul-buerkner** [comment]
I am not entirely sure what you mean by the change of functionality
unfortunately. It may have changed for ordinal and categorical models where
is wasnt correct in some instances before. But for other models it should
have stayed same. I dont want to speculate so please provide a minimal
reproducible example

G. Elliott Morris <notifications@github.com> schrieb am Sa., 25. Jan. 2020,
19:33:

> Okay, that’s useful context.  Thanks.
>
> The functionality of `posterior_linpred()` still seems to have changed
> significantly between brms 2.9 and 2.10-11. I’ll put together a reprex,
> unless you know why off the top of your head?
>
> (Again, the difference I’m seeing looks to be a much smaller range of
> predictions for each observation in newdata, or something to that effect.)
> On Jan 25, 2020, 06:31 -0500, Paul-Christian Bürkner <

**Comment by elliottmorris** [comment]
Yes, the issue I'm having is with categorical models. 

I'm pasting some code below and attaching a zip for the example. (The typical `reprex::reprex()` approach was having issues loading different brms versions).

You can see that the outcome has changed. I just can't figure out how to recreate the old predictions for the linear predictor. These new ones are wrong.

Thanks again for all the help and dev!

```
Restarting R session...

> library(tidyverse)
── Attaching packages ────────────────────── tidyverse 1.3.0 ──
✓ ggplot2 3.2.1     ✓ purrr   0.3.3
✓ tibble  2.1.3     ✓ dplyr   0.8.3
✓ tidyr   1.0.0     ✓ stringr 1.4.0
✓ readr   1.3.1     ✓ forcats 0.4.0
── Conflicts ───────────────────────── tidyverse_conflicts() ──
x dplyr::filter() masks stats::filter()
x dplyr::lag()    masks stats::lag()
> library(brms)
Loading required package: Rcpp
Loading 'brms' package (version 2.10.0). Useful instructions
can be found by typing help('brms'). A more detailed introduction
to the package is available through vignette('brms_overview').

> # read in generated data files 
> targets <- read_rds('targets.rds')
> cces <- read_rds('sample_cces.rds')
> # just read it in if already run
> vote_model <- read_rds("vote_model.rds")

> # draws
> pred <- posterior_linpred(object=vote_model,
+                           newdata=targets,
+                           allow_new_levels=TRUE,
+                           nsamples=500,
+                           transform = TRUE)

> # look at range of preds for clinton
> # they go from roughly 0 to 1 in brms 2.10.0 but much smaller range in brms 2.11.0
> summary(colMeans(pred[,,1]))
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
0.03755 0.33496 0.57316 0.56024 0.80095 0.99251 


> # now compare colmeans to 2.11 -----
> detach("package:brms", unload=TRUE)
> remove.packages('brms')
Removing package from ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library’
(as ‘lib’ is unspecified)
> devtools::install_version("brms", version = "2.11.0", repos = "http://cran.us.r-project.org")
Downloading package from url: http://cran.us.r-project.org/src/contrib/Archive/brms/brms_2.11.0.tar.gz
* installing *source* package ‘brms’ ...
* DONE (brms)
> library(brms)
Loading required package: Rcpp
Loading 'brms' package (version 2.11.0). Useful instructions
can be found by typing help('brms'). A more detailed introduction
to the package is available through vignette('brms_overview').

> # draws
> pred <- posterior_linpred(object=vote_model,
+                           newdata=targets,
+                           allow_new_levels=TRUE,
+                           nsamples=500,
+                           transform = TRUE)
Warning message:
posterior_linpred(transform = TRUE) is deprecated.Please use pp_expect() instead. 

[paul_reprex.zip](https://github.com/paul-buerkner/brms/files/4112929/paul_reprex.zip)
> # look at range of preds for clinton
> # they go from roughly 0 to 1 in brms 2.10.0 but much smaller range in brms 2.11.0
> summary(colMeans(pred[,,1]))
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.2838  0.4708  0.5115  0.4965  0.5371  0.5515 
```

**Comment by paul-buerkner** [comment]
Thank you for providing a reproducible example. I don't know what caused the issue but it seems to be working correctly again in the latest github version of brms (2.11.4).

**Comment by elliottmorris** [comment]
How interesting. Well, thanks!
