### ISSUE TITLE
Credible intervals for hypothesis and posterior_interval/summary do not match

### ISSUE THREAD

**Issue by ianhussey** [paul-buerkner/brms#647]
Perhaps I have misunderstood the use cases for hypothesis() vs posterior_interval()/summary(), but the upper and lower bound intervals do not seem to agree between these methods. ie:

- posterior_interval == summary
- posterior_interval != hypothesis
- posterior_interval != summary

Is this deliberate/have I misunderstood?

[minimal reproducible example.zip](https://github.com/paul-buerkner/brms/files/3098063/minimal.reproducible.example.zip)

Best,
Ian

**Comment by mvuorre** [comment]
In your example, you calculate one sided hypotheses so it shouldn't match the intervals of the other two methods ("`'CI': 90%-CI for one-sided and 95%-CI for two-sided hypotheses.`"). If you use a two sided hypothesis (iv = 0), all the methods match.

**Comment by paul-buerkner** [comment]
Yes, this is exactly the reason (i.e., different default of 90% or 95% intervals).
