### ISSUE TITLE
Running kfold on model constructed from imputed data throws error

### ISSUE THREAD

**Issue by alissab** [paul-buerkner/brms#652]
Hi there - thanks so much for this fabulous package. 

I've been running multi-level models on a remote server successfully until I started trying to use the kfold function on a model that was constructed from imputed data (did data imputation before model fitting using the mice package). [Before I was using imputed data, the kfold function worked fine.] Here is the error:

> <etc.>
> Fitting model 8 out of 10
> Fitting model 9 out of 10
> Fitting model 10 out of 10
> Error: 'newdata' must be a list of data.frames.

Here are the R/package versions the remote server is using: 
R 3.5.0
brms 2.8.0
mice 3.4.0

I'll attach example data: 
[data.xlsx](https://github.com/paul-buerkner/brms/files/3104604/data.xlsx)

...and this is the R code I used: 

```
require(dplyr)
require(brms)
require(future)
require(mice)

dat <- read.csv("data.csv", stringsAsFactors = FALSE, na.strings = c("", "NA"))

# scale numeric data
scaled_vars <- c("tmax", "mean_prec", "twi", "pc1", "pc2", "plot_tree_BA")
dat[, scaled_vars] <- scale(dat[, scaled_vars])

# impute missing values using mice package
dat_imp <- mice(dat_imp, m = 5, print = FALSE)

# weakly informative priors
prior <- c(set_prior("normal(0, 1)", class = "b", coef= "tmax"),
           set_prior("normal(0, 1)", class = "b", coef= "mean_prec"),
           set_prior("normal(0, 1)", class = "b", coef= "twi"),
           set_prior("normal(0, 1)", class = "b", coef= "pc1"),
           set_prior("normal(0, 1)", class = "b", coef= "pc2"),
           set_prior("normal(0, 1)", class = "b", coef= "plot_tree_BA"),
           set_prior("student_t(3, 1, 10)", class = "Intercept"),  # default
           set_prior("gamma(0.01, 0.01)", class = "shape"),  # default
           set_prior("student_t(3, 0, 10)", class = "sd"),  # default
           set_prior("normal(1, 5)", class = "sd", group = "species"),
           set_prior("normal(3, 10)", class = "sd", coef = "Intercept", group = "species"), 
           set_prior("normal(5, 5)", class = "sd", coef = "plot_tree_BA", group = "species")
)

# prep for parallel computing on remote server
plan(cluster)

mod1 <- brm_multiple( sap_plot_count ~
              tmax + mean_prec + twi + pc1 + pc2 +
              plot_tree_BA +
              (1 + plot_tree_BA | species),
            family = negbinomial(link = "log", link_shape = "log"),  
            future = TRUE,  
            save_all_pars = TRUE,  
            control = list(adapt_delta = 0.9, stepsize = 0.01, max_treedepth = 15),
            prior = prior,
            init_r = 0.1,
            data = dat_imp
)

loo1 <- kfold(mod1, K = 10)
```

**Comment by paul-buerkner** [comment]
Can you please provide a **minimial** reproducible example that I can run on my laptop? Your model will run too long before I can see the problem.

**Comment by paul-buerkner** [comment]
Ok, nevermind, I was able to run it with very small `iter`. I don't see the error you are reporting. Can you try it with the latest github version of brms to be installed via

```R
if (!requireNamespace("devtools")) {
  install.packages("devtools")
}
devtools::install_github("paul-buerkner/brms")
```

**Comment by paul-buerkner** [comment]
It should be working now, although the results have to be interpreted with caution as
`kfold` and similar methods are not fully compatible with models fitted on multiple imputed data
sets (hence I added a warning as well).

Thanks for reporting this issue!
