### ISSUE TITLE
`hypothesis` cannot find intercept on non-brmsfit objects

### ISSUE THREAD

**Issue by mattansb** [paul-buerkner/brms#654]
`hypothesis` seems to have a problem with finding the intercept on non-brmsfit objects. See example on a `stanreg` object:

````
library(brms)
library(rstanarm)

data(attitude)
set.seed(444)

m_brm <- brm(rating ~ complaints,attitude,
           sample_prior = TRUE)

m_stan <- stan_glm(rating ~ complaints,attitude,
                   family = gaussian())

hypothesis(m_brm,"complaints=1")   # works
hypothesis(m_brm,"(Intercept)=1")  # works

hypothesis(m_stan,"complaints=1")  # works
hypothesis(m_stan,"(Intercept)=1") # :(
#> Error: Some parameters cannot be found in the model: 
#> 'Intercept'
````

**Comment by paul-buerkner** [comment]
This is because `(Intercept)` is not a proper variable name that `hypothesis` has no chance finding anywhere.

**Comment by paul-buerkner** [comment]
You need to extract the samples vis `as.matrix(m_stan)`, and then change the column names to something that `hypothesis` can understand.

**Comment by mattansb** [comment]
okay - I thought it would work like with `brmsfit` objects. Thanks for the clarification!
