### ISSUE TITLE
More direct code to obtain A in the phylogenetic comparative analysis vignette

### ISSUE THREAD

**Issue by devillemereuil** [paul-buerkner/brms#655]
This is a somewhat pedantic issue, but I guess it's also very easy to fix. The code from the "Estimating Phylogenetic Multilevel Models with brms" vignette to obtain the variance-covariance matrix is somewhat inefficient and a more concise code could be advised to users.

Right now, the code reads:
```R
inv.phylo <- MCMCglmm::inverseA(phylo, nodes = "TIPS", scale = TRUE)
A <- solve(inv.phylo$Ainv)
rownames(A) <- rownames(inv.phylo$Ainv)
```

but the exact same result can be obtained directly (and more quickly!) using `ape`'s `vcv.phylo()` function:
```R
A <- ape::vcv.phylo(phylo)
```

I just thought this would be easy to fix and point users in the right direction.

**Comment by paul-buerkner** [comment]
Thanks! That's perfect. I wasn't aware of this but have now updated it accordingly.
