### ISSUE TITLE
Store model summary in model object

### ISSUE THREAD

**Issue by jackobailey** [paul-buerkner/brms#658]
As far as I can tell, `brms` computes model summaries every time one uses the `summary()` function. This is fine for many models. But where models have many parameters -- for example, longitudinal models using panel data where each participant has their own varying intercept and varying slopes -- models can be very large (in the order of GBs) and calling `summary()` can take a long time.

Would it be possible to either 1. include the model summary in the model object by default after estimation is complete and have `summary()` simply return it, or 2. store the model summary in the model object when it is first called by the user so that subsequent calls retrieve it from the object?

I accept that this isn't an urgent problem, but it would make working with some models a lot faster.

**Comment by paul-buerkner** [comment]
brms uses the summary returned by rstan which is automatically cached. As such I think what you are proposing is already implemented.
