### ISSUE TITLE
`save_all_pars` is not saved?

### ISSUE THREAD

**Issue by mattansb** [paul-buerkner/brms#660]
While this works:
````
library(brms)

mo1 <- brm(Sepal.Length ~ Species, data = iris, save_all_pars = TRUE)

bayes_factor(mo1,mo1)
````

Doing the following does not:
````
library(brms)

mo1 <- brm(Sepal.Length ~ Species, data = iris, save_all_pars = TRUE)

saveRDS(mo1,"mo1.rds")
## CLOSE R

## NEW SESSION
library(brms)

mo1<- readRDS("mo1.rds")

bayes_factor(mo1,mo1)
#> Error in cpp_object_initializer(.self, .refClassDef, ...) : 
#>   could not find function "cpp_object_initializer"
#> Error: Bridgesampling failed. Did you set 'save_all_pars' to TRUE when fitting your model?
````

What am I doing wrong?

**Comment by paul-buerkner** [comment]
This has nothing to do with `save_all_pars`, which is just the most common problem so I put it there as a *suggestion* what could be wrong. You also see the actual error message:

```R
#> Error in cpp_object_initializer(.self, .refClassDef, ...) : 
#>   could not find function "cpp_object_initializer"
```

loading brms also in the new session should fix this.

**Comment by mattansb** [comment]
marked as stupid question ^_^

Thanks!

**Comment by paul-buerkner** [comment]
No worries. Next time, when you are unsure if it is bug or more like a question, it's preferable to ask on https://discourse.mc-stan.org
