### ISSUE TITLE
Truncate the outcome distribution for a multivariate outcome

### ISSUE THREAD

**Issue by jrosen48** [paul-buerkner/brms#661]
I am trying to specify a truncated `(1, 4)` outcome distribution for a multivariate model. The (excellent) documentation specifies that: "With the exception of categorical, ordinal, and mixture families, the response distribution can be truncated using the trunc function in the addition part." However, when I try to specify such a model, i.e.:

`brm(mvbind(out1, out2) | resp_trunc(1, 4) ~ predictors)`

The following error is returned:

> Error in model.frame.default(bterms$allvars, data, na.action = na.action,  : 
  invalid type (list) for variable 'resp_trunc(1, 4)'

Is it not possible to specify a truncated outcome distribution for a multivariate outcome?

This seems like it may be related to this issue [here](https://github.com/paul-buerkner/brms/issues/396).

**Comment by paul-buerkner** [comment]
The correct error should be: 

```
Error: Only 'se', 'weights', 'mi' are supported addition arguments when 'rescor' is estimated. 
```

If this error is not returned in the current CRAN release version (2.8.0) you may want to use the latest dev version from github instead.
