### ISSUE TITLE
Some families with smooth and bs='gp' crash R

### ISSUE THREAD

**Issue by daskandalis** [paul-buerkner/brms#664]
I am trying to analyse non-Gaussian data with smooths. In the following example, the binomial and Poisson models crash R but the beta model does not. The Binomial and Poisson models run fine without bs='gp' (I am also curious as to whether a _Gaussian_ process is appropriate with such distributions). Binomial and Poisson models can be rescued by running them together, with or without beta. In my data the beta model crashes and the binomial is fine, but the beta can similarly be rescued by running with the binomial.

```r
require(brms)

N <- 100

n <- sample( 1:N, N, replace=TRUE )

binom <- rbinom(N, n, 0.6)
pois <- rpois(N, 1)
beta <- rbeta(N, 1,1)
t=seq(0,10,length.out=N)

dat <- data.frame(t=t, binom=binom, n=n, pois=pois, beta=beta)

pois.bf <- bf(pois~s(t,bs='gp'), family=poisson())
binom.bf <- bf(binom|trials(n)~s(t,bs='gp'), family=binomial())
beta.bf <- bf(beta~s(t,bs='gp'),family=zero_one_inflated_beta())

# crashes session
pois.mod <- brm( pois.bf, seed=1, chains=1, iter=100, data=dat )

# crashes session
binom.mod <- brm( binom.bf, seed=1, chains=1, iter=100, data=dat )

beta.mod <- brm( beta.bf, seed=1, chains=1, iter=100, data=dat )

mv.mod <- brm( binom.bf + pois.bf + beta.bf, seed=1, chains=1, iter=100, data=dat )
```

-------

> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)
Matrix products: default
locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
loaded via a namespace (and not attached):
[1] compiler_3.5.1 tools_3.5.1    yaml_2.2.0

**Comment by paul-buerkner** [comment]
Thanks for providing a reproducible example. Unfortunately, it runs for me just fine (on Windows, R 3.6, Rtools 3.5). I can't tell you what causes a problem but it is likely related to Stan itself (if at all) but not to brms, since the latter merely writes the Stan code.

**Comment by daskandalis** [comment]
Switched to R 3.6, Rtools 3.5, Rstudio 1.2.x and both models are now compiling.

**Comment by paul-buerkner** [comment]
Glad it works now!
