### ISSUE TITLE
Support for small precompiled models

### ISSUE THREAD

**Issue by phisanti** [paul-buerkner/brms#667]
I have been working with the `brms `package during the last year and it's a fantastic tool. However, the need for compilation each time supposes a huge drawback for small models. Therefore, I was wondering if it could be possible to add the possibility to use "precompiled" methods like `rstanarm` for simple models. It could look like:

`simple_model <- brm(Y ~ X1 + X2, data = d, family = gaussian, method = "precompiled")`

I don't know if such an implementation would be a nightmare to program or impossible, I keep using `rstanarm `for small cases, but I think it could be a very attractive addition for many users.

**Comment by paul-buerkner** [comment]
I know this would be nice, but building in some precompiled models into brms would not be worth the (immense!) effort since we already have rstanarm for this purpose.
