### ISSUE TITLE
Multivariate models and mi() + information criteria

### ISSUE THREAD

**Issue by ASKurz** [paul-buerkner/brms#668]
As per a thread on the [Stan forums](https://discourse.mc-stan.org/t/multivariate-models-and-mi/8670), brms 2.8.8+ now allows users to use the `mi()` syntax with multivariate models. E.g., this fits fine.

```
dat <-
  tibble(a = rnorm(100),
         b = c(NA, rnorm(99)))

bfa <- bf(a ~ 1)
bfb <- bf(b | mi() ~ 1)

fit4 <-
  brm(data = dat,
      mvbf(bfa, bfb, rescor = TRUE))
```

However, at present we don't get to compute information criteria with `waic()` or `loo()`. After your typo fix, trying to do so returns the following warning message:

> NAs were found in the log-likelihood. Possibly this is because some of your \*\*responses\*\* contain NAs. If you use 'mi' terms, try setting 'resp' to those response variables without missing values.Error in validate_ll(x) : NAs not allowed in input.

It'd be great if there was a way to return information criteria for these kinds of models.

**Comment by paul-buerkner** [comment]
@avehtari, would it be theoretically sensible to include "imputed" (i.e. estimated) response values in the computation of `loo`?

**Comment by jgabry** [comment]
I was thinking about that question. I guess it could make sense in certain cases but it would be pretty sensitive to the uncertainty in the imputations, right? 

Also, maybe I’ve just had one too many whiskeys but, if the model for the missing data points is the same as the model for the observed points (which it often is) then isn’t evaluating predictive performance on imputed points like asking how well the model predicts itself?

**Comment by jgabry** [comment]
That said there’s probably a coherent way of integrating over the uncertainty in the imputations just like we would anything else, and the additional uncertainty from that is probably justified.

**Comment by paul-buerkner** [comment]
Thanks @jgabry! I agree with your assessment. I think we have indeed two problems. A conceptual one about the model predicting itself, which it will alsways do when using `mi()` terms and a practical one that the large uncertainty in the missing value estimation will likely cause large khats.

Until we have a thorough understanding of these problems, I would be hesitant to implement it at this point.

**Comment by avehtari** [comment]
@jgabry is right. Asking how well the model predicts itself is same as looking at the sharpness, but it doesn't tell about calibration. It can be useful information, too, but for checking calibration of mi, we can use cross-validation, too.

**Comment by avehtari** [comment]
If the model is factorizable, then just drop NAs from log_lik

**Comment by paul-buerkner** [comment]
I will close this issue since I don't think there is a good fix for it.
