### ISSUE TITLE
restriction on par_ratio in horseshoe prior

### ISSUE THREAD

**Issue by topipa** [paul-buerkner/brms#669]
When using the horseshoe prior and defining the amount of global shrinkage through `par_ratio`, I encountered the following error: `Error: Argument 'par_ratio' must be within [0, 1].`. If it is the ratio of the expected number of non-zero coefficients to the expected number of zero coefficient (as opposed to the ratio of the expected number of non-zero coefficients to the *total number of coefficients*), is it really necessary to limit it between 0 and 1? Say that you expect two thirds of the coefficients to be non-zero, this would equal to `par_ratio = 2`, right?

I suppose it is common for the `par_ratio` to be quite low when using the horseshoe prior. I actually encountered this because I multiplied the `par_ratio` with the "pseudo-sigma" as explained in (https://arxiv.org/pdf/1707.01694.pdf), which made it exceed 1. As far as I understood, BRMS does not do this automatically unless the model has a parameter called `sigma`.

**Comment by paul-buerkner** [comment]
Thanks! I just fixed the incorrect check. 

brms will indeed not do any automatic scaling unless we have a "sigma" parameter. To make sure, I would still suggest to investigate the stan code and data.
