### ISSUE TITLE
the maximum number of DLLs reached

### ISSUE THREAD

**Issue by tankwin08** [paul-buerkner/brms#67]
Hey Paul,
The question I had is that when I run a lot times of nonllinear brm, it gave me an error.
_Compiling the C++ model
Error in inDL(x, as.logical(local), as.logical(now), ...) : 
  unable to load shared object 'C:/Users/tchow/AppData/Local/Temp/Rtmp8WKrZi/file12545c9f1785.dll':
  `maximal number of DLLs reached..._
This has been reported using Rstan, you can refer to http://stackoverflow.com/questions/24832030/exceeded-maximum-number-of-dlls-in-r/24834763#24834763
or https://groups.google.com/forum/#!msg/stan-users/D3p1FTu3U1M/mMtPdNO7i_cJ
I tried to make function of my model, it seems did not work. The solution seems works when you use stan. Not sure if this can be improved in the brms or not. If you have any thought, please let me know.
Thanks very much for your attention!

**Comment by paul-buerkner** [comment]
Does it occur when you compile the same model over and over again? If so, I strongly recommend using the `update` method. This will allow you the run the model again without any recompilation, thus avoiding this issue (and save the compilation time). You may even change some parts of the formula (e.g., fixed effects) without having to recompile the model:

```R
fit1 <- brm(count ~ Trt_c, data = epilepsy, family = poisson())
# same model just with more iterations
fit1 <- update(fit1, iter = 3000)
# different model but still no recompliation needed
# this code requires the latest dev version of brms from github
fit2 <- update(fit1, formula. = . ~ . + log_Age_c, newdata = epilepsy)
```

**Comment by tankwin08** [comment]
Thanks for your prompt response. Not same model. For example, in the first time, you may fit y ~ A1 * exp(-(x - u1)^2/(2 * sigma1^2)), and second time you need to fit y ~ A1 * exp(-(x - u1)^2/(2 * sigma1^2)) + A2 * exp(-(x - u2)^2/(2 * sigma2^2)) for different row data. or you may have third Gaussian compomnet. 
Does this looks like in your second case? I am still revising the code using update.

**Comment by paul-buerkner** [comment]
Unfortunately not. As soon as you change the *structure* of the non-linear formula, there is no way to avoid recompilation. However, if you just want to change the variables (i.e. data) than you can avoid it. 

Suppose that you have fitted a model with 2 components based on the variables `u1` and `u2`, but now you want to use the variables `v1` and `v2`, instead. Then you can just rename `v1` and `v2` to `u1` and `u2` in a new data.frame and pass this data.frame to the `newdata` argument of the `update` method.

**Comment by tankwin08** [comment]
It seems that there is no way to avoid the recompilation when you changed the structure. But update can make the code run faster. Thanks again for your advice.
