### ISSUE TITLE
Cumulative logit model drops factor values with zero observations

### ISSUE THREAD

**Issue by mathematiguy** [paul-buerkner/brms#670]
Hi there,

I'm currently using the development version of brms_2.8.0 on an ubuntu 18.04 machine.

I'm trying to model survey responses on an agree-disagree scale, and noticed that `brms` drops factors from the model if they don't occur in the data. There are many questions and a small enough sample in my survey that some people never pick one of the options. 

I put together a minimal reproducible example to demonstrate the point I'm trying to make.

```r
library(tidyverse)
library(brms)

# "A" is missing from the observations
d <- tibble(response = factor(c("B", "C", "D"), 
  ordered = TRUE,
  levels = c("A", "B", "C", "D")))

# We set 3 intercepts because there are 4 factor levels
inits <- list(`Intercept[1]` = -1,
              `Intercept[2]` = 0,
              `Intercept[3]` = 1)
inits_list <- list(inits, inits)

# Run the model
d_model <- brm(data = d, family = cumulative,
    response ~ 1,
    prior(normal(0, 10), class = Intercept),
    iter = 2000, warmup = 1000, chains = 2,
    inits = inits_list, seed = 11)
```

```
> d_model
 Family: cumulative 
  Links: mu = logit; disc = identity 
Formula: response ~ 1 
   Data: d (Number of observations: 3) 
Samples: 2 chains, each with iter = 2000; warmup = 1000; thin = 1;
         total post-warmup samples = 2000

Population-Level Effects: 
             Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
Intercept[1]    -1.20      1.49    -4.78     1.27        723 1.00
Intercept[2]     1.11      1.43    -1.60     4.25       1622 1.00

Samples were drawn using sampling(NUTS). For each parameter, Eff.Sample 
is a crude measure of effective sample size, and Rhat is the potential 
scale reduction factor on split chains (at convergence, Rhat = 1).
```

Note that although 3 intercepts are provided, only 2 are actually used. I'd like the model to use all 3, so it can at least consider cases with 0 observations as unlikely, rather than impossible.

I did some research to convince myself that someone else hadn't looked at this already, but if there is something I can do to solve it on my end please let me know.

Thanks for your work!

**Comment by paul-buerkner** [comment]
That's a good point. I will see if I can make this possible, but this requires some changes to ensure that unused levels are still dropped for other, non-response, factors. One alternative way is to code the response as numeric, and start with the smallest category at 1. If there are missing categories in between the smallest and the largest, they will continue to be represented even if no data in that category is provided. You may also control the maximal category by using the `cat` addition argument via `y | cat(<maximal category>) ~ ...`

**Comment by mathematiguy** [comment]
That’s awesome. I’m not expecting this to be treated as high priority, and my sample size is large enough that bumping up the empty categories with 1 observation in a small number of cases is a valid temporary solution so I’m planning to do that.

In my case there are a few questions with no strong disagree response (like the missing “A” class from the reprex), so the implicit zero is at the bottom end.

Anyway, thanks for your help - brms is awesome.

**Comment by paul-buerkner** [comment]
Thanks. In your case, you can use a numeric response which starts at 2. Then, the missing lower category (i.e., 1) will be automatically added to the thresholds. At least that's the intended behavior.

**Comment by mathematiguy** [comment]
Confirming that does work, thanks!

**Comment by paul-buerkner** [comment]
I have checked this issue again and decided that I wont try to fix this, since (a) we have a working alternative via numeric responses, (b) the effort in making this possible (via argument `xlev` in `stats::model.frame`) is quite high, and (c) it would break backwards compatibility of existing models or code where factor levels had previously been dropped.
