### ISSUE TITLE
customized covariances set via cov_ranef() cannot vary among groups using gr(…,by=) in multivariate model

### ISSUE THREAD

**Issue by mdahirel** [paul-buerkner/brms#674]
Hi,

(Config: Windows 10, R 3.5.3, `rstan` 2.18.2 , `brms` 2.9.0)

I’m currently using `brms` and the `cov_ranef()` argument to fit a quantitative genetic model (“animal model”) in order to understand how several traits of my study species are correlated at the genetic level, knowing the relatedness matrix among my individuals.
Specifically, I have individuals coming from two environments, and I want to know if the genetic variance-covariance matrix differs between the two environments (for instance due to selection)
It does not appear to be possible to fit such a multivariate model using `brms`. Trying to do it gives the following error message:

```
Error: Cannot combine 'by' variables with customized covariance matrices when fitting multiple group-level effects.
```

Univariate models for each trait work fine, a multivariate model with a common covariance matrix for both environments too, so I did not expect major problems (perhaps naively). 
Here’s a working example using the blue tit dataset in `MCMCglmm`, as in your multivariate vignette (using individual sex as our grouping variable for the sake of example):

```
library(brms)
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
library(MCMCglmm)
## use MCMCglmm to get dataset, pedigree, and convert pedigree to relatedness matrix A

data(BTdata)
data(BTped)

inv.A <- MCMCglmm::inverseA(BTped[, 1:3])
A <- solve(inv.A$Ainv)
rownames(A) <- rownames(inv.A$Ainv)


## multivariate model with group-(here sex-)specific genetic variances/covariances
bftarsus2 <- bf(tarsus ~ 1 + (1 | q | gr(animal, by = sex)))
bfback2 <- bf(back ~ 1 + (1 | q | gr(animal, by = sex)))

mod_m2 <- brm(bftarsus2 + bfback2, data = BTdata, cov_ranef = list(animal = A), iter = 100, chains = 2) # does NOT work
## gives error "Error: Cannot combine 'by' variables with customized covariance matrices when fitting multiple group-level effects."



### (For the record,
### univariate models are OK...
#mod_t2 <- brm(bftarsus2, data = BTdata, cov_ranef = list(animal = A), iter = 100, chains = 2) # works
#mod_b2 <- brm(bfback2, data = BTdata, cov_ranef = list(animal = A), iter = 100, chains = 2) # works
#
#
### ...so are models (uni- or multivariate) with a single shared VCV matrix
#bftarsus <- bf(tarsus ~ 1 + (1 | q | animal))
#bfback <- bf(back ~ 1 + (1 | q | animal))
#
### univariate
#mod_t <- brm(bftarsus, data = BTdata, cov_ranef = list(animal = A), iter = 100, chains = 2) # works
#mod_b <- brm(bfback, data = BTdata, cov_ranef = list(animal = A), iter = 100, chains = 2) # works
#
### multivariate
#mod_m <- brm(bftarsus + bfback, data = BTdata, cov_ranef = list(animal = A), iter = 100, chains = 2) # works)

```

I thought about splitting my response variables in 2 and fitting separate models for my 2 environments of interest, but I have some population- and group-level effects I need to be common to the whole dataset (eg spatial effects).
Anyway, thanks for your work on `brms`, it’s been incredibly helpful and useful so far and it will definitely continue to be

Maxime

**Comment by paul-buerkner** [comment]
I think it's time to rework the `cov_ranef` feature a little bit to make in more general in various directions, among others in the direction you mentioned.

**Comment by paul-buerkner** [comment]
Implemented on github.
