### ISSUE TITLE
Different ordinal thresholds for different subsets of the data

### ISSUE THREAD

**Issue by paul-buerkner** [paul-buerkner/brms#675]
For some complex ordinal data, for instance for data from different surveys, it is necessary to have different threshold vectors for different subsets of the data. We could specify this via the `cat` addition argument as follows:

```
y | cat(c(g1 = 3, g2 = 5, g2 = 7), gr = group) ~ ...
```

where, in this example, `group` is a grouping variable with levels `g1`, `g2`, and `g3` with 3, 5, and 7 categories respectively.

**Comment by jackobailey** [comment]
For clarity, as per your example, is this for cases where we have 1 outcome variable that is measured using 3-, 5-, and 7-point scales in 3 different surveys? Or for cases where the scales are the same but we just want unique thresholds for each group? Either way, sounds cool!

**Comment by paul-buerkner** [comment]
It's intended for both.

**Comment by paul-buerkner** [comment]
The feature is now working. Here is an example.

```R
dat <- data.frame(
  y = sample(1:6, 100, TRUE),
  gr = rep(c("a", "b"), each = 50),
  th = rep(5:6, each = 50),
  x = rnorm(100)
)

prior <- prior(normal(0,1), class = "Intercept", group = "b")

fit <- brm(
  y | thres(th, gr) ~ x, data = dat, 
  family = cumulative(), prior = prior
) 
```
