### ISSUE TITLE
User-defined thresholds for cumulative link?

### ISSUE THREAD

**Issue by jzelner** [paul-buerkner/brms#676]
Hi - 

I am hoping to implement a version of an ordered problit/logit/cauchit that allows the user to pre-define thresholds rather than having them be estimated. I am exploring doing this w/a custom family but wanted to see if there are any options for straightforwardly doing this by building off of existing code in `brms`?

Thanks!

-Jon Zelner

**Comment by paul-buerkner** [comment]
The brms issue tracker is reseved to feature requests and bug reports. General questions are better asked on https://discourse.mc-stan.org/. This time, I still answer it here.

The two possible options are (1) (as you mention) a custom family or (2) extracting and changing the generated stan code accordingly.
