### ISSUE TITLE
error when grouping terms (random effects) start with a dot

### ISSUE THREAD

**Issue by bnicenboim** [paul-buerkner/brms#679]
Hi!
brms cannot deal when I group by a variable that starts with a dot. But these names are legal names, and in fact `tibble` now adds dots to fix bad names of columns, for example `tibble("1",.name_repair="universal")`.

Here a reprex of my problem:
```
tbl <- tibble::tibble(.x=rep(c(1,2),5),.y=rnorm(10))
brm(.x ~ 1+ (1|.y), data =tbl)
# Error: Illegal grouping term '.y'. It may contain only variable names combined by the symbol ':'

brm(.x ~ 1+ (1|`.y`), data =tbl)
# Error: Illegal grouping term '.y'. It may contain only variable names combined by the symbol ':'

brm(.x ~ .y, data =tbl)
# works
```
The problem seems to be specific of grouping terms.

**Comment by paul-buerkner** [comment]
thanks! Should be fixed now.
