### ISSUE TITLE
Option to have`marginal_effects.brmsfit` return predicted data (instead of plotting)

### ISSUE THREAD

**Issue by stefanherzog** [paul-buerkner/brms#68]
Hi Paul! Great package!

Maybe I'm missing something, but is there (already) an option so that `marginal_effects.brmsfit` returns the predicted data (i.e., point estimate and specified credible interval) instead of plotting the data?

My use case is: I already have a `ggplot`-object where I'm adding different things and now I'd like to add posterior predictives. Currently `marginal_effects.brmsfit` creates a new plot. When using `rstanarm`, I would work with `rstanarm::posterior_predict`.

Thanks!

**Comment by paul-buerkner** [comment]
Thanks! 

You can just do
```R
list_of_data <- marginal_effects(<your arguments>)
```
This should do the trick (at least with the dev version from github, but I am almost sure also with the CRAN version).

**Comment by stefanherzog** [comment]
Thanks for the clarification! I now realize that I should have asked the following:

Is it possible to get the full posterior distribution(s) from `marginal_effects` in the way that we can get them from `brms::predict` and `brms::predict` by setting `summary = FALSE`?

**Comment by paul-buerkner** [comment]
Unfortunately not. This reason is that the marginal effects plots only need the summary statistics to that it makes no sense to allow `summary = FALSE` in `marginal_effects`. However, as our `list_of_data` contains everything we need to call `predict` (or `fitted`) directly, you could to the following (explained on an example):

```R
fit <- brm(count ~ log_Age_c + log_Base4_c * Trt_c, 
           data = epilepsy, family = poisson())
list_of_data <- marginal_effects(fit)
predict(fit, newdata = list_of_data$Trt_c, summary = FALSE)
```

**Comment by stefanherzog** [comment]
Ah, very nice! Thanks!

**Comment by paul-buerkner** [comment]
Did this answer your question? If so, I think we can close this issue.

**Comment by stefanherzog** [comment]
Yes, it did. Thanks!
