### ISSUE TITLE
Feature request: Standalone latent gaussian process/spline parameters for custom families

### ISSUE THREAD

**Issue by jzelner** [paul-buerkner/brms#681]
Opening up a feature request for smooth parameter terms (GP/spline) not tied to specific observations, i.e. latent GP, that can be passed to custom families. A motivating example for this would be to implement the baseline hazard for a model along the lines of a Cox Proportional Hazards model. For more information, see this thread:

https://discourse.mc-stan.org/t/gaussian-process-distributional-parameter-in-brms/9117/7

**Comment by paul-buerkner** [comment]
To make this a proper feature, I can actually implement, we need two more things: (1) A proper mathematical formulation of the model class and (2) a way to include this in brms formula syntax.

I am happy to come up with something for (2), but I would appreciate you making a proposal for (1).
At least for a specific example to make sure that, mathematically, we are on the same page of what we want to achieve.

**Comment by jzelner** [comment]
I'm working on this and have a version up and going that fits data, but am getting stuck on how to make posterior predictions/simulations from the model. Specifically, the time-varying term needs to be passed into the predict function, and I've been doing something of a hack where I pass it as a variable rather than a dpar so that I can pass the whole vector rather than being limited to passing a single real as it seems like I am if I make it a dpar. As a result, in the `draws` object I need for the posterior predictions, I don't have the proper information in either dpars or data. Is there a clean way to do this that I'm missing? If I made a matrix in which each row was just the vector-valued parameter for the population level, repeated for each observation, could I then pass the individual rows to the predict function? Or, could I made predictions in generated quantities and then just feed them to the predict function in brms somehow?  Thanks!

**Comment by paul-buerkner** [comment]
Nice! I haven't seen a formal description though of how exactly you want to implement this feature. That is, neither a mathemetical formulation of the possible models nor a proposal for a user interface. Before you invest too much time in actually implementing it, it makes much more sense (I think) to talk about the exact feature specification first.

That said, I don't think there is a canonical way yet to make predictions possible, but again, this may not be the best next step to take anyway.

**Comment by paul-buerkner** [comment]
I have yet to see a proposal for a user API for this feature. Feel free to post in this issue, but since I am not seeing an API myself currently (and since and experimental version of the cox family is already part of brms), I will close this issue for the time being.
