### ISSUE TITLE
Proposed feature: passing modified output of stancode() to brm()

### ISSUE THREAD

**Issue by tatters** [paul-buerkner/brms#682]
Dear Paul,
Finding the correct format for specifying priors with `set_prior()` can be a little tedious. To try and find another solution, I modified the `brm()` function so it can accept a string containing the stan model, and it seems to work fine. This way the user can build a model, extract the model string with `stancode()`, modify priors in it (or perhaps make other small adjustments), and then feed it back into `brm()`. The currently available solution is of course to feed the modified model string into `rstan()`, but it would be nice to have the option to stay with brms after the modification. As far as I can see, the only necessary change is to add an argument like `brm(..., stancode = NULL)` , and then to change
```{r}
x$model <- make_stancode(formula, data = data, prior = prior, 
                               cov_ranef = cov_ranef, sample_prior = sample_prior, 
                               knots = knots, stanvars = stanvars, stan_funs = stan_funs, 
                               save_model = save_model)
```
to
```{r}
if (!is.null(stancode)) {
      x$model = stancode
    } else {
      x$model <- make_stancode(formula, data = data, prior = prior, 
                               cov_ranef = cov_ranef, sample_prior = sample_prior, 
                               knots = knots, stanvars = stanvars, stan_funs = stan_funs, 
                               save_model = save_model)
    }
```
Please find attached a toy example (I had to rename internal brms functions).
Best regards,
Andrey

[brms_modify_stancode.txt](https://github.com/paul-buerkner/brms/files/3264709/brms_modify_stancode.txt)

**Comment by paul-buerkner** [comment]
I am sceptical of such a feature as it is way to easy to pass stan code that does not fit the information provided in `formula`, `family` etc. or is even straight up incompatible with brms. 

Are you aware of the `stanvars` argument to pass Stan code to brms? You may also pass priors as pure stan code via `set_prior(..., check = FALSE)`.

**Comment by tatters** [comment]
I'm sure it's very easy to mess up the code this way, but sometimes this might offer a quick way to make small adjustments in the model. In my case, I was struggling to modify the default priors on group-level intercepts in a dirichlet model. They did not show up in prior_summary, and `set_prior(..., check = FALSE)` added new lines to the "priors" block without modifying what was there. 

Maybe I'm missing something obvious,  and maybe it is possible to achieve this with `stanvars`, but it can be annoying to see the model code and not be able to make a tiny change in it ;))  With this proposed method it worked like a charm, so i thought I'd share the thought, that's all!

**Comment by paul-buerkner** [comment]
I see, thanks for the explanation. I will need some time to think about this feature and its implications before I can decide whether I want to implement it or not.

**Comment by tatters** [comment]
Sure, thanks again!

**Comment by paul-buerkner** [comment]
Another approach may be

1.  create a dummy brmsfit object via `dummy_brmsfit <- brm(..., chains = 0)`
2.  extract the stancode and amend it
3. create a dummy stanfit object via `dummy_stanfit <- rstan(..., chains = 0)`
4. replace the `stanfit` object inside a dummy brmsfit object via `dummy_brmsfit$fit <- dummy_stanfit`
5. actually fit the model via `update(dummy_brmsfit, recompile = FALSE)`

I understand that this is a little bit more overhead than the proposal you have but it should work without any changes to brms that I am hesitant to make.

**Comment by tatters** [comment]
This is very elegant! After a bit of tinkering I think I got it to work (see the code below) :))  Basically I just followed your steps, except that in step 3 it's `rstan::stan()` and you need to create a datalist with `brms::make_standata()`, otherwise stan complains and crashes.
In case others might also find this a useful feature, could you just clarify exactly what kind of changes in the model code are acceptable? I presume nothing that would affect the formula part, or...?

```{r}
library(rstan)
library(brms)

d = data.frame(a = rep(c('a', 'b'), each = 50),
               b = c(rnorm(50, 10, 2), rnorm(50, 5, 2)))
head(d)
#   a         b
# 1 a 13.273355
# 2 a  9.601048
# 3 a 11.274566
# 4 a 10.929455
# 5 a 11.703958
# 6 a 11.057903

# create a dummy brmsfit object via dummy_brmsfit <- brm(..., chains = 0)
dummy_brmsfit = brm(b ~ a, data = d, prior = set_prior('normal(0, 2)'), chains = 0)

# extract the stancode and amend it (in this case just changed the prior on b)
stancode(dummy_brmsfit)

model_string = '
functions {
}
data {
  int<lower=1> N;  // number of observations
  vector[N] Y;  // response variable
  int<lower=1> K;  // number of population-level effects
  matrix[N, K] X;  // population-level design matrix
  int prior_only;  // should the likelihood be ignored?
}
transformed data {
  int Kc = K - 1;
  matrix[N, Kc] Xc;  // centered version of X
  vector[Kc] means_X;  // column means of X before centering
  for (i in 2:K) {
    means_X[i - 1] = mean(X[, i]);
    Xc[, i - 1] = X[, i] - means_X[i - 1];
  }
}
parameters {
  vector[Kc] b;  // population-level effects
  real temp_Intercept;  // temporary intercept
  real<lower=0> sigma;  // residual SD
}
transformed parameters {
}
model {
  vector[N] mu = temp_Intercept + Xc * b;
  // priors including all constants
  target += cauchy_lpdf(b | 0, 5);  // MODIFIED PRIOR
  target += student_t_lpdf(temp_Intercept | 3, 8, 10);
  target += student_t_lpdf(sigma | 3, 0, 10)
    - 1 * student_t_lccdf(0 | 3, 0, 10);
  // likelihood including all constants
  if (!prior_only) {
    target += normal_lpdf(Y | mu, sigma);
  }
}
generated quantities {
  // actual population-level intercept
  real b_Intercept = temp_Intercept - dot_product(means_X, b);
}'

# create data for stan
data_stan = brms::make_standata(b ~ a, data = d)

# create a dummy stanfit object via 
dummy_stanfit = stan(model_code = model_string, data = data_stan, chains = 0)

# replace the stanfit object inside a dummy brmsfit object 
dummy_brmsfit$fit = dummy_stanfit

# actually fit the model 
new_brmsfit = update(dummy_brmsfit, recompile = FALSE)
summary(new_brmsfit)  # Works! :))
```
Thanks again, I would never have thought of this workflow, and it solves the problem beautifully!
/ Andrey

**Comment by paul-buerkner** [comment]
Everything that changes only the prior, but not the likelihood should work.

I am closing this issue now, since your problems seems to be resolved.
