### ISSUE TITLE
brms::brm errors R 3.6.0 windows 10 "C++14 standard requested but CXX14 is not defined"

### ISSUE THREAD

**Issue by tphilippi** [paul-buerkner/brms#683]
I can't get the simplest examples to run on MS Windows 10 R-3.6.0 x64 brms_2.8.0.  Using the first example:
```
library(brms)
bprior1 <- prior(student_t(5,0,10), class = b) +
  prior(cauchy(0,2), class = sd)
fit1 <- brm(count ~ zAge + zBase * Trt + (1|patient),
            data = epilepsy, family = poisson(), prior = bprior1)
sessionInfo()
```
gives this error message:

> Compiling the C++ model
> Error in compileCode(f, code, language = language, verbose = verbose) : 
>   Compilation ERROR, function(s)/method(s) not created! Error in .shlib_internal(commandArgs(TRUE)) : 
>   C++14 standard requested but CXX14 is not defined
> Calls: <Anonymous> -> .shlib_internal
> Execution halted
> In addition: Warning message:
> In system(cmd, intern = !verbose) :
>   running command 'C:/R/R-3.6.0/bin/x64/R CMD SHLIB file2b607922c58.cpp 2> file2b607922c58.cpp.err.txt' had status 1
> Error in sink(type = "output") : invalid connection

> > sessionInfo()
> R version 3.6.0 (2019-04-26)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 18362)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_United States.1252 
> [2] LC_CTYPE=English_United States.1252   
> [3] LC_MONETARY=English_United States.1252
> [4] LC_NUMERIC=C                          
> [5] LC_TIME=English_United States.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] brms_2.8.0 Rcpp_1.0.1
> 
> loaded via a namespace (and not attached):
>  [1] mvtnorm_1.0-10       lattice_0.20-38      prettyunits_1.0.2   
>  [4] ps_1.3.0             zoo_1.8-5            gtools_3.8.1        
>  [7] assertthat_0.2.1     digest_0.6.19        mime_0.6            
> [10] R6_2.4.0             plyr_1.8.4           backports_1.1.4     
> [13] ggridges_0.5.1       stats4_3.6.0         coda_0.19-2         
> [16] ggplot2_3.1.1        colourpicker_1.0     pillar_1.4.1        
> [19] rlang_0.3.4          lazyeval_0.2.2       miniUI_0.1.1.1      
> [22] callr_3.2.0          Matrix_1.2-17        DT_0.5              
> [25] shinythemes_1.1.2    shinyjs_1.0          stringr_1.4.0       
> [28] htmlwidgets_1.3      loo_2.1.0            igraph_1.2.4.1      
> [31] munsell_0.5.0        shiny_1.3.2          compiler_3.6.0      
> [34] httpuv_1.5.1         rstan_2.18.2         pkgconfig_2.0.2     
> [37] base64enc_0.1-3      pkgbuild_1.0.3       rstantools_1.5.1    
> [40] htmltools_0.3.6      tidyselect_0.2.5     tibble_2.1.1        
> [43] gridExtra_2.3        threejs_0.3.1        matrixStats_0.54.0  
> [46] withr_2.1.2          crayon_1.3.4         dplyr_0.8.0.1       
> [49] later_0.8.0          grid_3.6.0           nlme_3.1-139        
> [52] xtable_1.8-4         gtable_0.3.0         magrittr_1.5        
> [55] StanHeaders_2.18.1   scales_1.0.0         cli_1.1.0           
> [58] stringi_1.4.3        reshape2_1.4.3       promises_1.0.1      
> [61] dygraphs_1.1.1.6     xts_0.11-2           fortunes_1.5-4      
> [64] tools_3.6.0          glue_1.3.1           shinystan_2.5.0     
> [67] markdown_0.9         purrr_0.3.2          crosstalk_1.0.0     
> [70] processx_3.3.0       rsconnect_0.8.13     abind_1.4-5         
> [73] parallel_3.6.0       inline_0.3.15        colorspace_1.4-1    
> [76] bridgesampling_0.6-0 bayesplot_1.6.0      Brobdingnag_1.2-6   
> > 
> 

The exact same test code runs fine on the same computer under R-3.5.3 brms_2.8.0 with the same 79 packages loaded via a namespace, and the same Rutils 3.5 in case that matters.

**Comment by paul-buerkner** [comment]
Other's had the same issues. There are multiple threads on https://discourse.mc-stan.org/, for instance https://discourse.mc-stan.org/t/rstan-wont-compile-with-r3-6/9105/2 that solve the problem or point to a solution.
