### ISSUE TITLE
Chains does not stop, random effects models (Docker environment)

### ISSUE THREAD

**Issue by thorvall** [paul-buerkner/brms#684]
Symptom:
One or more chains does not stop within reasonable time (+10x the fastest chain)

First I'm not knowledgeable  enough to tell if this is a brms, stan, or docker problem, or something in between. 
But with different models, both with and without future set to TRUE, to see if that did make a difference, I have chains 'hanging' with no visible progress but full cpu usage.  
And terminating the process does result is loss of information from the other chains. 

Platform: Docker containers, (earthlab/r-greta:latest, methodsconsultants/tidyverse-h2o:latest)
![image](https://user-images.githubusercontent.com/5535902/59269220-dcb99b80-8c4e-11e9-83fb-592298ff2f61.png)
The image show the latest try with the following code
```
chains = 8
model5 <- brm(formula = y  ~ -1 + antal_0 + antal_1 + antal_2 + antal_3 + antal_4 + antal_5
+ antal_6 + antal_7 + antal_8 + antal_9 + antal_10 + antal_11 + antal_12 + antal_13
+ antal_14 + antal_15  + antal_16 + (1 | omNavn) + (1 | monthNr)
, chains = chains, iter = 50000,
data = brmData, control = list(max_treedepth = 20, adapt_delta = 0.9999),
inits = initfun, prior = set_prior("exponential(0.1)"), cores = chains)
```
nr of rows 84, dim(omNavn) = 7, dim(monthNr) = 12. 

Selected output:
Fastes:
Chain 6:  Elapsed Time: 612.074 seconds (Warm-up)
Chain 6:                35.4076 seconds (Sampling)
Chain 6:                647.482 seconds (Total)
Slowest (but finished)
Chain 5:  Elapsed Time: 1687.63 seconds (Warm-up)
Chain 5:                196.166 seconds (Sampling)
Chain 5:                1883.79 seconds (Total)
Non completed chains (last message): (all before the first chain completed)
Chain 3: Iteration:     1 / 50000 [  0%]  (Warmup)
Chain 1: Iteration: 15000 / 50000 [ 30%]  (Warmup)
Chain 4: Iteration: 25000 / 50000 [ 50%]  (Warmup) (the second chain to reach sampling)
Chain 4: Iteration: 25001 / 50000 [ 50%]  (Sampling)

I hope you can help me clarify, where to search for the cause, and if there are ways to end a chain without loosing information from completed chains (or is there some model problems, if the slower chains are from hard to diagnose areas of the distribution)

I have seen the problem with these models, but also with other types of models, but searching the net does not give any real idea as why some chains 'dies' on me.

Kind regards

**Comment by paul-buerkner** [comment]
This sometimes happens for more complex Stan models. It it not a bug, but I wouldn't necessarily call it desired behavior. 

One quick comment. With Stan, you don't need 50k+ samples as Stan tends to sample very efficienctly. A few thousand samples are usually enough for most purposes. Also, do you realy need `max_treedepth` and `adapt_delta` that high? Anyway, I suggest you open an thread on https://discourse.mc-stan.org/ to further discuss these issue.
