### ISSUE TITLE
brms license

### ISSUE THREAD

**Issue by BrashEQLibrium** [paul-buerkner/brms#686]
I work for one of the largest technology companies in the world. We have many use cases for Stan, which would be much more efficient if we could also use rstan, or PyStan, or brms as an interface to Stan. Stan is licensed under BDS. Yet brms, like rstan and PyStan, is licensed under GPLv3. My organization prohibits the usage of GPLv3-licensed software for anything other than internal projects on personal machines. Is there any chance that you could provide a more permissively-licensed version?

**Comment by paul-buerkner** [comment]
For CRAN packages, GPL3 is to my knowledge the current standard license, which I don't want to change.
Is there any chance you can get your tech company to open up for such licenses? I mean, under this restriction, you are basically not allowed to use R itself if I understand the text of `license()` correctly.
