### ISSUE TITLE
Explanation of brms-generated Stan code for nested versus non-nested multi-level models?

### ISSUE THREAD

**Issue by ssp3nc3r** [paul-buerkner/brms#687]
`brms` underlying `Stan` code for a non-nested multi-level model,

`brm(y ~ 1 + (1 | A) + (1 | B) + (1 | C), ...)`

Looks identical to the `Stan` code for a nested model,

`brm(y ~ 1 + (1 | A/B/C), ...)`

I'm assuming the difference is in how `brms` indexes the random effects ... Is there a paper or other explanation on how they differ programmatically?

**Comment by paul-buerkner** [comment]
Please ask brms/stan related questions on https://discourse.mc-stan.org/ rather than on github.
