### ISSUE TITLE
Number of multiple imputation in "missing values" vignette

### ISSUE THREAD

**Issue by zutr** [paul-buerkner/brms#688]
In the vignette "Handle Missing Values with brms", section "Imputation before model fitting", there are m = 5 multiply imputed datasets used for mixing their posterior draws. However, according to the paper cited below, m = 5 is not enough for reliable posterior inferences. The authors recommend to choose a larger number of multiply imputed datasets. They don't recommend a specific number meant by "large", but m = 100 is doing well in their simulation study. In contrast, m = 20 is not enough.

Xiang Zhou & Jerome P. Reiter (2010) A Note on Bayesian Inference After Multiple Imputation, The American Statistician, 64:2, 159-163, DOI: 10.1198/tast.2010.09109

I understand that m = 100 increases the computational burden heavily, but perhaps a remark should be added to the vignette that m = 5 might not be enough for reliable posterior inferences.

**Comment by paul-buerkner** [comment]
Good point, thank you! I incorporated your suggestion.
