### ISSUE TITLE
Feature Request: Support for clustermq as backend?

### ISSUE THREAD

**Issue by jzelner** [paul-buerkner/brms#690]
Is there any possibility of adding support for `clustermq` as a backend in addition to future for running parallel chains? This would make deploying multi-chain jobs to a cluster easier, and would also make it easier for brms to play nicely with drake pipelines running in parallel by submitting jobs to a common queue. 

Thanks!

-Jon

**Comment by paul-buerkner** [comment]
I think future is able to handle clusters as well, but I haven't tried it out myself. Here is the doc that at least mentions clusters: https://cran.r-project.org/web/packages/future/vignettes/future-1-overview.html

The **clustermq** package looks to specific to me to be natively supported in brms, but you can use it together with brms by running a set of brm calls each with a single chain and later combine them via `combine_models`.

**Comment by jzelner** [comment]
Oh that’s perfect; easy to write a function to make each chain its own
target in the drake pipeline and then combine them all. Wasn’t aware of the
combine_models function before! May contribute a function for brms that
will create  these targets automatically, if that is of interest?

**Comment by paul-buerkner** [comment]
I am not sure I fully understand, sorry.

**Comment by jzelner** [comment]
No problem - almost have a working version up and going, that I will post
when it is ready. However, the overhead of compiling many stan models at
once has been crashing my server, since it is trying to compile for each
individual chain. Is there any reason one can't edit the `brm` function to
stop at the compilation step and return a `brmsfit` object with no samples,
and then pass it back to the `brm` function to avoid this recompilation
step? Basically, this would replicate the behavior in the future loop in
the brm function or the way that rstan does it with mclapply, but let you
do it outside the function, so that it could easily be nested in a drake
pipeline.

Thanks!

-Jon

**Comment by paul-buerkner** [comment]
Compile brm once with chains = 0 then pass it to the notes and fit the
model via update(...).

Jon Zelner <notifications@github.com> schrieb am Fr., 21. Juni 2019, 04:40:
