### ISSUE TITLE
Feature request: pMCMC Values

### ISSUE THREAD

**Issue by Benambridge** [paul-buerkner/brms#695]
Hi Paul, thanks for such a great package! I like to report pMCMC values as I think they're useful for readers who are new to Bayesian statistics (most people in my field!), as a better version of the familiar frequentist p values (i.e., values that can [sort of] be legitimately interpreted how people want to - and incorrectly do - interpret frequentist p values). At the moment, I use code like that shown below (very inelegant, sorry!), but it would be neat if brms could automatically include these in the summary output table:

Table=as.data.frame(summary(MYMODEL)$fixed)
samps = as.matrix(as.mcmc(MYMODEL))
pMCMC=data.frame()
for(i in 1:length(Table[,1])) {
  temp=mean(samps[,i] < 0)
  if(Table[i,1] < 0) {temp=mean(samps[,i] > 0)}
  pMCMC[i,1]=temp
  colnames(pMCMC)="pMCMC"
}
Table=cbind(Table, pMCMC)

Thanks
Ben

**Comment by paul-buerkner** [comment]
Thanks for the suggestions! So what you are proposing are inverse posterior probabilities > or < 0 depending on the sign of the mean? If prefer that users explicitely think of the expected directions and then compute the related posterior probabilities via `hypothesis` (the relvant column is called `Post.Prob`). Perhaps this is already what you want?

**Comment by Benambridge** [comment]
Thanks! I've just tried that and, yes, it gives the same value as my code. For my purposes it would still be more convenient if these were just added to the summary table automatically, though I can see why you'd want users to think more explicitly about the direction- thanks!

**Comment by paul-buerkner** [comment]
Glad to hear that!
