### ISSUE TITLE
Elicit warning if sample_prior = TRUE but prior was not sampled?

### ISSUE THREAD

**Issue by lindeloev** [paul-buerkner/brms#696]
It seems that there are cases when prior samples are not collected even though `sample_prior = TRUE`. For example when the default priors are used, but also for intercept-only models as [noted on Twitter](https://twitter.com/MichiganWater2/status/1146519717256953856). 

I suggest throwing an informative warning in `brm` when `sample_prior = TRUE` is not obeyed for one or several parameters in the model? For example: "Prior sample were not collected for [list of parameters here]. Specify a proper prior for these."

Either mention `hypothesis` in the warning above, or explicitly elicit a warning when testing a point hypothesis on a parameter with unsampled prior, e.g., `hypothesis(fit, 'Intercept = 0').

Relates to #566

**Comment by paul-buerkner** [comment]
I added this information to the doc of `sample_prior` a few minutes ago. Would you mind taking a loo if this is sensible and understandable. Then we can think of whether an additional warning needs to be thrown.

**Comment by lindeloev** [comment]
I was just about to do a pull request on an alternative formulation, but maybe we should clarify a potential bug first: `hypothesis` use the prior on `b` for the Intercept:

```
data = data.frame(
  y = rnorm(50),
  x = 1:50
)


library(brms)
fit = brm(
  formula = y ~ x,
  data = data,
  prior = set_prior('normal(2, 1)', class='b'),
  sample_prior = TRUE
)
```

```
> head(prior_samples(fit))
         b     sigma
1 3.271250 11.919315
2 1.802418  9.679331
3 3.117318  2.309235
4 1.078793 12.128314
5 2.730517  7.998656
6 2.799320 13.723959
```

```
plot(hypothesis(fit, 'Intercept = 0'))
```
![image](https://user-images.githubusercontent.com/1439417/60655515-282a2880-9e4e-11e9-92d7-0e8ce1dc7ffe.png)

**Comment by paul-buerkner** [comment]
I can confirm this is a bug, I will try to fix it asap.

**Comment by lindeloev** [comment]
I just created a pull request, (hopefully!) improving even more on your updated doc. I tried being more explicit about not sampling from improper default priors. This was just an easier way to propose it than pasting it here, so feel free to reject and make other improvement.

I would definitely vote for a warning in `hypothesis` when testing point hypotheses on parameters without prior samples. I would guess that the amount of time spent figuring and giving up on the `Evid.Ratio = NA` is vastly greater than that spent looking at the warning for users who just want the CI.

I see there's a bit more of a trade-off in `sample_prior = TRUE` in `brm`. I would personally appreciate it, but that's very much because I'm lazy and don't always read the doc for all arguments I use. So it would be great for novices. But I see how it could be slightly annoying for expert users who set proper priors on just the parameters that they want priors samples from.

**Comment by paul-buerkner** [comment]
I just fixed the bug. It now also issues a warning when trying to get prior samples from the intercept, but I won't add a general warning. If peopel get `Evid.Ratio = NA` they have to read the documentation and specify proper priors. I don't want to add annoying warnings for a case where it often does not apply.

Can you explain what you mean by the third paragraph. I didn't quite to what trade-off you are referring to? Do you mean the warning message?

**Comment by lindeloev** [comment]
Space-warping bug-fixing speed!

The "trade-off" was that warnings would do positive things for some (less time debugging why prior samples were not saved) and negative things for others (annoying if it doesn't apply to what you're doing).

I see your point regarding needing to know `sample_prior` behavior when testing point hypotheses using `hypothesis`. I just thought that `Evid.Ratio` was "used" much more frequently than the CI.

**Comment by paul-buerkner** [comment]
I see. But note that also evid.ratio is only affected by sampling from the
prior in point hypotheses which I suggest to replace by directed hypotheses
anyway whenever reasonable.

Jonas Kristoffer Lindeløv <notifications@github.com> schrieb am Do., 4.
Juli 2019, 14:40:

**Comment by paul-buerkner** [comment]
I hope that all issues (both the bug and the documentation) has been resolved so I am closing this issue. Thanks for your time and suggestions!

**Comment by lindeloev** [comment]
Yes, all good. The pleasure is all mine!
