### ISSUE TITLE
Error in `marginal_effects` when passing `conditions`

### ISSUE THREAD

**Issue by tomwallis** [paul-buerkner/brms#70]
I'm getting the following error:

```r
> conditions <- expand.grid(A = unique(dat$A),
+                          B = unique(dat$B),
+                          C = "level1",
+                          D = 0)
> model_dat <- marginal_effects(fit, effects = "E",
+                                conditions = conditions)
Error in `[<-.data.frame`(`*tmp*`, , missing_vars, value = -2.72140957446809) : 
  replacement has 1 row, data has 4
```

where A, B and C are factors, and D and E are covariates. As far as I can see the `conditions` dataframe is valid and contains all valid levels. I have a similar code showing the marginal effect of C (i.e. setting E to zero) which works fine, so I'm not sure what's going wrong here.

Sorry, don't have time to try for a reproducible example right now, but maybe you see quickly where the error is. If not I can try coming up with a reproducible example later (sorry!).

**Comment by paul-buerkner** [comment]
Which version of brms are you using? I am currently working on restructuring some of the backend code (which affects marginal_effects), but when I am done, I will try to find out what's happening.

**Comment by tomwallis** [comment]
I'm using `brms_0.8.0.9000`. A dev version from maybe two weeks ago.

**Comment by paul-buerkner** [comment]
You could try out downloading the latest version again, but I am skeptical that it will change something. I will investigate this in more detail within the next few days.

**Comment by tomwallis** [comment]
Updated to `0.9.0`; same error. Thanks for taking a look.

**Comment by tomwallis** [comment]
Potentially useless update: so far I've been unable to create a minimal example, sorry. This works:

```r
# Minimal example
library(brms)

dat <- expand.grid(A = c("a1", "a2"), 
                   B = c("b1", "b2", "b3"),
                   C = c("c1", "c2"),
                   D = seq(-1, 1, length.out = 10), 
                   E = seq(-1, 1, length.out = 10),
                   rep = 1)

X <- model.matrix(~ A * B * C * D * E, data = dat)
betas <- runif(ncol(X), min = -1, max = 1)
dat$y = X %*% betas + rnorm(nrow(X))

fit <- brm(y ~ A * B * C * D * E, data = dat,
           iter = 500, chains = 4, cluster = 4)

conditions <- expand.grid(A = unique(dat$A),
                         B = "b1",
                         C = unique(dat$C), 
                         D = 0)
model_dat <- marginal_effects(fit, effects = "E",
                               conditions = conditions)

```

**Comment by tomwallis** [comment]
I just sent you an email with data and fitted model that reproduces the error.

**Comment by paul-buerkner** [comment]
It should be working correctly now. Thanks for helping me to fix this issue!
