### ISSUE TITLE
Structured thresholds in ordinal models similar to Andrich & Luo (2003)

### ISSUE THREAD

**Issue by doebler** [paul-buerkner/brms#702]
In an IRT context Andrich and Luo (2003; Journal of Applied Measurement, 4(3), 205-221) suggest to reduce the number of threshold parameter by assuming the thresholds are given by a fourth order polynomial of the category index. The method is available in commercial IRT software such as WinSteps and is reported to work for up to 100 threshold parameters. In stan code A&L (2003) employ the following polynomials, where `thresh[i,n]` is the `n`th **cumulated** threshold of the `i`th item,  `m` is the number of categories (= index of the maximum category - 1) and the matrix `threshpar` contains the four threshold parameters per item:

```stan
thresh[i,n] = threshpar[i,1] * (-n) + 
              threshpar[i,2] * n * (m - n) +
              threshpar[i,3] * n * (m - n) * (2*n - m) + 
              threshpar[i,4] * n * (m - n) * (2*n - m) * (5*n*n - 5*n*m + m*m +1);
```
Note that these polynomials can be interpreted as a kind of functional PCA of the thresholds, so that the while A&L (2003)'s name "principal components" is somewhat justified. Obviously, if there is just one item (=ordinal regression) the approach still has its appeal.

Employing a minimally modified version of the function `acat_logit_lpmf` from brms (`row_vector` instead of `vector`), I was able to produce some code that compiles, though the choice of starting values and maybe priors for `threshpar` could make a great difference for the actual usability. Code is found below.

```stan
functions {
  /* acat-logit log-PDF for a single response
  * Args:
    *   y: observed response category
  *   mu: linear predictor (in the absence of covariates this is the person parameter)
  *   thres: ordinal thresholds 
  *   disc: discrimination parameter (will be 1 in the pcm)
  * Returns:
    *   a scalar to be added to the log posterior
  */
    real acat_logit_lpmf(int y, real mu, row_vector thres, real disc) {
      int ncat = num_elements(thres) + 1;
      vector[ncat] p;
      p[1] = 0.0;
      for (k in 1:(ncat - 1)) {
        p[k + 1] = p[k] + disc * (mu - thres[k]);
      }
      p = exp(p);
      return log(p[y] / sum(p));
    }
}
data {
  int<lower=1> N;  // number of observations
  int<lower=1> J; // number of persons
  int<lower=1> I; // number of items
  int<lower=1,upper=I> item[N]; // item index
  int<lower=1,upper=J> person[N]; // person index 
  int<lower=2> ncat;  // number of categories
  int<lower=1> m;  // = ncat -1 = number of thresholds
  int Y[N];  // response variable
}

parameters {
  vector[J] theta; // person parameters
  matrix[I, 4] threshpar; // parameters for item threshold curves
  real<lower=0>sigma;  // latent standard deviations
}

transformed parameters {
  matrix[I,m] thresh; // threshholds computed from threshpar
  matrix[I,m] threshdiff; // threshholds-differences computed from thresh

    // compute the thresholds
  for(i in 1:I) {
    for(n in 1:m){
      thresh[i,n] = threshpar[i,1] * (-n) + threshpar[i,2] * n * (m - n) + threshpar[i,3] *  n * (m - n) * (2*n - m) + threshpar[i,4] * n * (m - n) * (5*n*n - 5*n*m + m*m +1);
    }
  }
  for(i in 1:I) {
    for(n in 1:m){
      if(n == 1){
        threshdiff[i,n] = 0;
      }else{
        threshdiff[i,n] = thresh[i,n] - thresh[i,(n-1)];
      }
     }
  }
}

model {
  // priors including all constants
  
  // are priors for the weights really needed?
  // for(i in 1:I){
  //   for(j in 1:4){
  //     target += normal_lpdf(threshpar[i,j] | 0 , 100);
  //   }
  // }
    target += cauchy_lpdf(sigma|0,5);
  for(j in 1:J){
    target += normal_lpdf(theta[j]|0,sigma);
  }
  // likelihood including all constants
    for (n in 1:N) {
      target += acat_logit_lpmf(Y[n] | theta[person[n]], threshdiff[item[n],], 1); // disc set to 1
    }
}
```

EDIT (21/07/2019): There was an error in the code as I mixed up the cumulative thresholds with the thresholds in acat_logit_lpmf.

**Comment by paul-buerkner** [comment]
I will close this issue since I think it is a bit too specific of a feature to be worth implementing at this point of brms' development.
