### ISSUE TITLE
measurement error with grouping factors

### ISSUE THREAD

**Issue by tatters** [paul-buerkner/brms#706]
Hi Paul,
I'm having some issues when using me(..., gr = something). In particular, (1) marginal_effects() doesn't seem to be working, while fitted() works for the original dataset but not for its subset or (some) new data. Here is an example:
```{r}
library(brms)  # 2.9.5, installed from github July 11

n_groups = 10
n_obs_per_group = 20
dat = data.frame(
  y = rnorm(n_groups * n_obs_per_group), 
  x1 = rep(rnorm(n_groups), each = n_obs_per_group),
  sdx = rep(abs(rnorm(n_groups, 1)), each = n_obs_per_group),
  group = rep(paste0('group', 1:n_groups), each = n_obs_per_group)
)

# fit a simple error-in-variables model 
fit1 = brm(y ~ me(x1, sdx, gr = group), data = dat, 
           save_mevars = TRUE, chains = 2, cores = 2, iter = 1000)
summary(fit1)  # fine
marginal_effects(fit1)  
# Error: Measured values and measurement error should be unique for each group. 
# Occured for level 'group1' of group 'group'. 

# Now for fitted():
a1 = fitted(fit1, newdata = dat)  # fine
a2 = fitted(fit1, newdata = data.frame(x1 = 5, sdx = .5, group = 'group1'))  # fine
a2 = fitted(fit1, newdata = data.frame(x1 = 5, sdx = .5, group = 'group2'))  # error
# Error in draws$Xme[[k]][, Jme] : subscript out of bounds

# Same error if we take a subset of the original dataset:
a3 = fitted(fit1, newdata = dat[1:(nrow(dat) / 2), ])  # error
# Error in draws$Xme[[k]][, Jme] : subscript out of bounds

# Also:
a4 = fitted(fit2, newdata = data.frame(x1 = 5, sdx = .5))  # error
# Error in get(g, data) : object 'group' not found
# But what if we are interested just in the effect of x1?
```
A possibly related issue: #636. 
Also: intriguingly, in #698 you say that mi() could replace me(). Could you provide an example of how that might work? I've used mi() with missing values, but I don't see anything about measurement error in mi() documentation... Thank you!
Kind regards,
Andrey

**Comment by paul-buerkner** [comment]
Thanks for reporting this issue and for providing a minimal reproducible example! I will fix it as soon as possible.

With regard to #698, you can specify measurement error in mi terms via `bf(y | mi(sdy) ~ ...)` and if you then use `mi(y)` somewhere else in the model the measurement error will be taken into account in addition to missing values (if there are some). In the multiple imputation literature this is called "overimputation", but not sure if the term also applies for missing values estimated on the fly.

**Comment by paul-buerkner** [comment]
The problems should now be fixed.

**Comment by tatters** [comment]
Fantastic, problem solved! Thank you, Paul!
