### ISSUE TITLE
Feature request: Implement generalized aterms for use with custom families

### ISSUE THREAD

**Issue by dhalpern** [paul-buerkner/brms#707]
Implement an addition argument that takes in vectors of values without checking them, which could be used inside a custom family. For instance
y | real(z) ~ x
where z is a (real) addition variable to be used in the custom family. 
See discussion here: https://discourse.mc-stan.org/t/using-multiprocessing-for-kfold-with-custom-families/9420/4

**Comment by paul-buerkner** [comment]
This feature should now be working in the github version of brms. I have added the addition arguments `vreal` and `vint` for this purpose. An example of how to apply them is given in https://github.com/paul-buerkner/brms/blob/master/vignettes/brms_customfamilies.Rmd

**Comment by dhalpern** [comment]
Thank you!
