### ISSUE TITLE
Censored observations in multivariate model possible?

### ISSUE THREAD

**Issue by poppymiller** [paul-buerkner/brms#709]
I can't find any examples, but brms has so many (awesome!) features that I may have missed it. I want to model protein concentrations for many different proteins measured on the same samples. I would prefer a multivariate model because many protein types are correlated. A not-trivial number of concentrations are left censored (below the detectable limit). The detectable limit varies by protein type.

**Comment by paul-buerkner** [comment]
For greater visibility by the community, please ask brms related questions on https://discourse.mc-stan.org/ using the Interfaces - brms tag. You may also want to explain your question in a bit more detail and in particular how far you got already in trying to get this working.

**Comment by poppymiller** [comment]
Thanks, will do.
