### ISSUE TITLE
Zero-one inflated beta models 

### ISSUE THREAD

**Issue by adamdsmith** [paul-buerkner/brms#71]
Hi Paul.  Great package!  

Any interest in accommodating zero-one inflation in beta models?  

The parameterization [in this post](http://mbjoseph.github.io/2014/02/06/beta.html) seems handy, and makes more intuitive sense than the [parameterization used in the `gamlss` package](http://www.inside-r.org/packages/cran/gamlss.dist/docs/BEINF).

Thanks!

**Comment by paul-buerkner** [comment]
Hi Adam,

this is already implemented. Try `family = zero_inflated_beta()`.

**Comment by adamdsmith** [comment]
Thanks Paul.  Completely glanced over that one.  Does it also handle one inflation in addition to zeros?

**Comment by paul-buerkner** [comment]
At the moment not, because it would require a more differentiated syntax. Please note that zero-inflated models use a sort of "multivariate" syntax, which is explained in detail in the documentation of `brm`.
