### ISSUE TITLE
Include BYM2 autocorrelation structures

### ISSUE THREAD

**Issue by paul-buerkner** [paul-buerkner/brms#710]
As discussed in https://discourse.mc-stan.org/t/bym-and-besag-models-in-brms/9531/10 there are several extentions of the standard ICAR model. Specifically, the BYM model (usually with a poisson likelihood) arises when we add a non-spatial component. This can already be done in brms via

```R
brm(y ~ ... + (1 | obs), family = poisson(), autocor = cor_icar(...))
``` 

where `obs` is a unique indicator of the observations. However, this model tends to have convergence problems as the spatial and non-spatial residuals are barely identified separately without a joint prior on them. The latter is exactly what the BYM2 model suggests. See, for instance, @mitzimorris case study (https://mc-stan.org/users/documentation/case-studies/icar_stan.html#bym2-improving-the-parameterization-of-the-besag-york-and-mollie-model) for details. I think this BYM2 model could be worth implementing in brms in the form of an (I)CAR variant.

Second, allowing for disconnected sub-regions as described in https://www.sciencedirect.com/science/article/abs/pii/S1877584517301600?via%3Dihub seems to be a worthwhile extention to the existing CAR structures.

**Comment by mitzimorris** [comment]
hi @paul-buerkner  - please remind me - what happened to the BYM2 implementation?

**Comment by mitzimorris** [comment]
nevermind - found the answer - cor_car function!

**Comment by paul-buerkner** [comment]
I realize, we already have a new issue about disconntect sub-regions (#733) so there is nothing left in this issue to implement that is not described elsewhere.
