### ISSUE TITLE
underscores in outcome names lead to error message for categorical model

### ISSUE THREAD

**Issue by tfjaeger** [paul-buerkner/brms#713]
Perhaps it's obvious, but it took me a good 20 minutes to figure out what the source of the problem was. Here's a replicable example. Perhaps it's worth putting a warning about this somewhere in a help file? (apologies if I missed it. Fwiw, I just re-read the help for formula and brm and didn't see any notes about it).

```
ir$Species = factor(paste0(ir$Species,"_", ir$Species))
b2 <- brm(Species ~ 1 + Petal.Length + Petal.Width + Sepal.Length + Sepal.Width,            
        data=ir, family="categorical", prior=c(set_prior("normal(0, 8)")),
        chains=3, iter=1000, warmup=600)
```

**Comment by paul-buerkner** [comment]
Thanks! It should be fixed in the github version of brms already.

tfjaeger <notifications@github.com> schrieb am Di., 23. Juli 2019, 22:59:

**Comment by tfjaeger** [comment]
Thank you!
