### ISSUE TITLE
Allow for sqrt link function for sigma

### ISSUE THREAD

**Issue by achetverikov** [paul-buerkner/brms#715]
Sometimes it's useful to model variance of the distribution instead of standard deviation, because unlike standard deviations, a sum of two variances equals to the variance of a sum. An easy way to implement this would be to allow for sqrt link function for sigma.

**Comment by paul-buerkner** [comment]
The sqrt link likely leads to a bimodel posterior due to the symmetry of
the square function. You may still do it already by using an identity link
for sigma combined with a nonlinear formula in which you specify the square
transform.

Andrey Chetverikov <notifications@github.com> schrieb am Fr., 26. Juli
2019, 11:37:

**Comment by achetverikov** [comment]
Given that both sigma and variance are positive, is bimodality really an issue? You have to restrict (put priors on) the predictors anyway. Thanks for the tip about the nonlinear formula!

**Comment by paul-buerkner** [comment]
Try it out and see if it becomes an issue.

Andrey Chetverikov <notifications@github.com> schrieb am Fr., 26. Juli
2019, 12:14:

**Comment by achetverikov** [comment]
there seems to be some problem with make_stancode checks:
```
# generate the data
n_subj = 18
n_i = 700

fe_sigma_i = 5
fe_v1 = 0.7
fe_v2 = -0.5

mydt_fe <- data.table(subj_id = rep(1:n_subj, each = n_i))
mydt_fe[,V1:=runif(.N, 0,2)]
mydt_fe[,V2:=runif(.N, -0.7, 1)]
mydt_fe[,var_j:=fe_sigma_i+fe_v1*V1+fe_v2*V2]
mydt_fe[,dv:=rnorm(.N, 0, sqrt(var_j)), by = .(subj_id)]

make_stancode(bf(
    dv ~ 0, 
    sigma ~  sqrt(varest),
    varest ~ 1 + V1 + V2, 
    nl = TRUE), 
  data = mydt_fe, 
  family = brmsfamily('gaussian', link_sigma = 'identity') 
  )
```

The code throws an error:
```
Error: The parameter 'varest' is not a valid distributional or non-linear parameter. Did you forget to set 'nl = TRUE'?
```

If I use the same formula for dv instead of sigma, it works. 

In addition, I'm not quite sure if `1+V1+V2` is going to be interpreted as a regression equation, is it?   And what would be the prior names then? In the examples in brms_nonlinear it seems that every regressor specified manually, which is a bit of a hassle for multilevel models.

**Comment by paul-buerkner** [comment]
You didnt make sure sigma is handled as nonlinear. Wrap the sigma formula
in nlf().

Andrey Chetverikov <notifications@github.com> schrieb am Fr., 26. Juli
2019, 12:49:

**Comment by achetverikov** [comment]
OK, thanks! So this works:
```
make_stancode(bf(
    dv ~ 0, 
    nlf(sigma ~  sqrt(varest)),
    varest ~ 1+V1+V2, 
    nl = TRUE), 
  data = mydt_fe, 
  family = brmsfamily('gaussian', link_sigma = 'identity') ,
  prior = c(prior(student_t(7, 0, 8), class='b', coef = 'V1', nlpar = 'varest'),
            prior(student_t(7, 0, 8), class='b', coef = 'V2', nlpar = 'varest'))
  )
```

and generates the following code:
```
// generated with brms 2.9.0
functions {
}
data {
  int<lower=1> N;  // number of observations
  vector[N] Y;  // response variable
  int<lower=1> K_varest;  // number of population-level effects
  matrix[N, K_varest] X_varest;  // population-level design matrix
  int prior_only;  // should the likelihood be ignored?
}
transformed data {
}
parameters {
  vector[K_varest] b_varest;  // population-level effects
}
transformed parameters {
}
model {
  vector[N] nlp_varest = X_varest * b_varest;
  vector[N] mu;
  vector[N] sigma;
  for (n in 1:N) {
    // compute non-linear predictor
    mu[n] = 0;
    // compute non-linear predictor
    sigma[n] = sqrt(nlp_varest[n]);
  }
  // priors including all constants
  target += student_t_lpdf(b_varest[2] | 7, 0, 8);
  target += student_t_lpdf(b_varest[3] | 7, 0, 8);
  // likelihood including all constants
  if (!prior_only) {
    target += normal_lpdf(Y | mu, sigma);
  }
}
generated quantities {
}
```
But there a still a few differences with the usual regression model approach in the generated code:
- the intercept is not added 
- the predictors are not centred

Also the code doesn't seem to take advantage of vectorization.

So I still think sqrt link might be a good thing.

**Comment by paul-buerkner** [comment]
You don't mean an sqrt link do you? Rather sqrt is the inverse link in your
case which you then apply on top of the log link that makes sure things are
positive in the first place. So the situation is more complex. I don't see
a point in adding anything to brms for this as you can use the non-linear
syntax. You can activate auto centering also in nonlinear models so there
is not limitation.

Andrey Chetverikov <notifications@github.com> schrieb am Fr., 26. Juli
2019, 13:05:

**Comment by paul-buerkner** [comment]
Edit: the intercept is included as part of X in your case. I suggest you
carefully fit this model to get some experience with how it works.

Paul Buerkner <paul.buerkner@gmail.com> schrieb am Fr., 26. Juli 2019,
13:09:

**Comment by achetverikov** [comment]
OK, I see your point, thank you very much for your help. In my case, In the code above I'm avoiding log (by setting link_sigma to identity), and ultimately taking sqrt of the estimate to go from variance to sigma (so you're right that the link in question is square, the inverse link is sqrt).
