### ISSUE TITLE
Prior Robustness plot

### ISSUE THREAD

**Issue by TarandeepKang** [paul-buerkner/brms#716]
Hi Paul,

As a new user of bayesian statistics, and of your package, I apologise if this request is in the wrong place, or indeed idiotic. I think that a new plotting feature showing how parameter values in models change as a function of different prior widths would be useful. I recently posted in the Stan forum and was advised that no such method is yet packaged.

Best Wishes

**Comment by paul-buerkner** [comment]
This is indeed a good idea. We are actively working on developing new ways to make it easier for users to understand the influence of their priors and your proposal fits in there well. Once we have a good idea how such plots good look like, I will implement them in brms.

**Comment by TarandeepKang** [comment]
Hi Paul,

The JASP team, led by EJ Wagenmakers at the University of Amsterdam seem to have a good implementation. It might be worth a look? 

Best,


Tarandeep

**Comment by paul-buerkner** [comment]
Their implementation is not general enough for use in brms but it may be a start, thanks!

**Comment by paul-buerkner** [comment]
I think such plots are better suited for our https://github.com/n-kall/priorsense package. Closing this issue here.
