### ISSUE TITLE
Hypothesis function returns negative evidence ratio

### ISSUE THREAD

**Issue by JAQuent** [paul-buerkner/brms#717]
I've run the following model: 
These are the priors:
```
                 prior     class               coef group resp dpar nlpar bound
1  normal(0.466,0.024) Intercept                                               
2 normal(-0.048,0.023)         b objLocTargetRating  
```

This is the model:
```
recall_case1_model <- brm(accRecall ~ objLocTargetRating +  
                     I(objLocTargetRating*objLocTargetRating) +
                     (1 | subNum) +
                     (1 | objNum),
                   data = recall_case1_data,
                   cores = cores2use,
                   family = bernoulli(),
                   save_all_pars = TRUE,
                   sample_prior = TRUE,
                   prior = recall_case1_priors
```
When I try to calculate the evidence ratio against a point null
`hypothesis(recall_case1_model, "IobjLocTargetRatingMUobjLocTargetRating = 0")`

I get the following output:
```
Hypothesis Tests for class b:
                Hypothesis Estimate Est.Error CI.Lower CI.Upper Evid.Ratio Post.Prob Star
1 (IobjLocTargetRat... = 0     0.38      0.07     0.25     0.51          0         0    *
---
'*': The expected value under the hypothesis lies outside the 95%-CI.
Posterior probabilities of point hypotheses assume equal prior probabilities.
```

When I access the evidence ratio
```
hypothesis(recall_case1_model, "IobjLocTargetRatingMUobjLocTargetRating = 0")$`hypothesis`$Evid.Ratio
```
I get this `-2.98799e-17`.  How can the  Dickey Savage density ratio be negative? Is that a bug? 

Also as two possibly unrelated question: 

Is it possible to have a CI that doesn't include zero but still a low evidence ratio (BF10 =  1.055396) with a CI (-0.094, -0.004)?
Fixed effects in that case:
```
                   Estimate Est.Error   Q2.5  Q97.5
Intercept             0.466     0.024  0.418  0.514
objLocTargetRating   -0.048     0.023 -0.094 -0.004
```
My second question is how can a BF01 be 19.83 with an CI of 0.24  and  0.97?
```
Hypothesis Tests for class b:
   Hypothesis Estimate Est.Error CI.Lower CI.Upper Evid.Ratio Post.Prob Star
1 (xhigh) = 0     0.61      0.19     0.24     0.97      19.83      0.95    *
---
'*': The expected value under the hypothesis lies outside the 95%-CI.
Posterior probabilities of point hypotheses assume equal prior probabilities.
```

I am not sure what informatioon is needed but I am using brms_2.8.0. Please tell me if you need other information.

**Comment by paul-buerkner** [comment]
This value is not actually negative but a floating point representation of
0 that happend to be (very very minimally) negative. So there is nothing to
worry about.

Jörn Alexander Quent <notifications@github.com> schrieb am Mo., 29. Juli
2019, 20:34:

**Comment by JAQuent** [comment]
How do I then report such a value? Do I just take the absolute value? The only other thing that is worrying me is that I get a BF01 of 19.83 with an CI of 0.24 and 0.97. Why does it show support of H0?

**Comment by paul-buerkner** [comment]
Just report it as zero cause it *is* zero.

Because the BF depends strongly on the prior. In particular you shouldn't
use wide priors for BFs. There is a rich literature on this available.

Jörn Alexander Quent <notifications@github.com> schrieb am Di., 30. Juli
2019, 08:48:
