### ISSUE TITLE
use nsamples() generic from rstantools?

### ISSUE THREAD

**Issue by mcol** [paul-buerkner/brms#719]
`nsamples()` is one of the generics defined in `rstantool`, but it's being defined again in`generics.R`. Shouldn't the `rstantool` version be imported (similarly for what it's done for, say, `posterior_linpred` and `predictive_error`)?

I don't think it really matters either way, but if you want a patch for consistency I'll be happy to contribute it.

**Comment by paul-buerkner** [comment]
Yeah will do I just did not know it was part of the rstantools release
already.

Marco Colombo <notifications@github.com> schrieb am Mi., 31. Juli 2019,
14:57:

**Comment by mcol** [comment]
It's there since 1.5.1, released in August 2018. PR coming as soon as tests complete.

**Comment by paul-buerkner** [comment]
Thanks! I am on holiday and will look at it in a few days.

Marco Colombo <notifications@github.com> schrieb am Mi., 31. Juli 2019,
16:09:
