### ISSUE TITLE
posteriors for mu, eta and residuals

### ISSUE THREAD

**Issue by schmettow** [paul-buerkner/brms#72]
# Situation 

brms features a command to retrieve the fitted values, from which one can indirectly also get residuals as $\epsilon_i = Y_i - \mu_i$.

# Problem:

1. `fitted`returns point and interval estimates. In some situations one wants to retrieve the full posterior, for example, when one prefers the posterior mode over posterior mean.
2. There is no easy way to retrieve the linear predictor $\eta$. Again, being able to retrieve the full posterior is preferred.

Currently, the situation forces me to use `standata` and `stancode`, then run rstan. As of version 0.9.0, this approach is getting less comfortable, as parameters in the stancode no longer have "speaking" names.

# Possible solutions

1. Add parameters `monitor.eta`, `monitor.mu`, `monitor.epsilon` to optionally store the pd in the brmsfit object. This is the approach of MCMCglmm.

2. Add a parameter, e.g. `monitor` as in JAGS or `pars` as in rstan, that takes a list of characters denoting parameter classes. The default would be something like: `list("b", "r", "sigma", "cor")`. With `list("b", "r", "sigma", "cor", "eta")` the user could store the pd of the linear predictor

# Result

The user would be able to control the parameters that are being stored and retrieve them from the brmsfit object. Especially, with solution 2, that can go either way: sometimes additional parameters, like eta, are needed, with the result of more memory consumption. Another example is that, often, the random effects are not required, but only the group level effects.

**Comment by paul-buerkner** [comment]
If I understand you correctly, extracting these samples should already be possible. For instance:

```R
# full posterior distribution of the fitted values
fitted(fit, summary = FALSE)
# full posterior distribution of the linear predictor (i.e. fitted values before applying the link function)
fitted(fit, summary = FALSE, scale = "linear")
#  full posterior distribution of the residuals
residuals(fit, summary = FALSE)
```

It this what you wanted?

**Comment by paul-buerkner** [comment]
@schmettow Just a quick follow up to ask you if you were able to extract the required information using my suggestions?

**Comment by schmettow** [comment]
Thank you, that was exactly what I needed. And btw: your package is just awesome!

**Comment by paul-buerkner** [comment]
Great! I will close this issue now.
