### ISSUE TITLE
Formula error with variables beginning with a number

### ISSUE THREAD

**Issue by ryanholbrook** [paul-buerkner/brms#721]
`brm` throws an error when trying to read a formula given by `y ~ .` when one of the predictors has a name beginning with a number. The error came up in a situation like this:

```
X <- read_csv("a, 1b\n5, 6\n7, 8\n")
lm(a ~ ., data=X)
brm(a ~ ., data=X)


Y <- read_csv("a, 1b\n5, 6\n7, 8\n") %>%
    as_tibble(.name_repair="universal")
brm(a ~ ., data=Y)
```

`lm` is able to evaluate the formula on `X`, but `brm` complains of a syntax error; `brm` does fine (as on `Y`) after repairing the column names. The trouble is that `readr` defaults to parsing non-syntactic column names as strings, instead of just repairing them as `read.csv` would.

Thank you!

I have `brms` version 2.9.0 and R version 3.5.1.

**Comment by paul-buerkner** [comment]
Thanks! Since brms requires proper variable names in too many places, I decided to throw an informative error rather than allowing non-standard variable names.
