### ISSUE TITLE
Error multinomial logit:  At least 2 response categories are required.

### ISSUE THREAD

**Issue by CommonEconomist** [paul-buerkner/brms#725]
Trying to fit a multinomial model I get  a peculiar error.
Running the following

    library(brms)
    library(Zelig)
    data(mexico)
    logit.m<-brm (vote88 ~ pristr + othcok + othsocok, 
              data=mexico,family="multinomial")

will produce:

 `Error: At least 2 response categories are required.`

Yet the outcome variable does have more that two categories. 
There are no problems when using

    logit.o<-brm (vote88 ~ pristr + othcok + othsocok, 
                  data=mexico,family="categorical")

And `length(logit.o$family$cats)` will tell that the length is indeed more than 2. 
I am not sure if this is a bug or whether I am completely misunderstanding the syntax for multinomial logit?

**Comment by paul-buerkner** [comment]
The multinomial family requires a matrix as input for the response, with one column per category. There are some examples of how to use the multinomal family on https://discourse.mc-stan.org/
