### ISSUE TITLE
poly() does not retain its 'coefs' across model fitting and predict()

### ISSUE THREAD

**Issue by brockf** [paul-buerkner/brms#73]
With most R model fitting functions, e.g., lm() and lmer(), the original-data poly() coefficients are used in predict(). This is critical because it means that the variable of interest is transformed consistently across original and prediction data.

With brms, however, the coefficients do not appear to carry over between fitting and prediction.

**Comment by paul-buerkner** [comment]
You are right with both the bug and its cause. Many thanks for reporting this issue! 
It should be fixed now in the latest dev version on github, which can be installed via `devtools::install_github("paul-buerkner/brms")`. 

I would be grateful, if you could test it on some of your models and verify that it also works correctly for you.

**Comment by brockf** [comment]
Looks like it's working great, @paul-buerkner . I *really* appreciate the quick fix!

**Comment by paul-buerkner** [comment]
Great! Thanks again for reporting this issue!
