### ISSUE TITLE
A few minor bugs in the brmsfit summary

### ISSUE THREAD

**Issue by lindeloev** [paul-buerkner/brms#730]
Here are two minor bugs relating to the first "chunk" of the brmsfit summary. The double-pipe of variance-only effects (`||`) does not make it into the fit summary. I had

    fit = brm(y ~ condition + (0 + condition || id), data)

But only a single pipe makes it into the summary:

```
> fit
 Family: gaussian 
  Links: mu = identity; sigma = identity 
Formula: y ~ condition + (0 + condition | id) 
...
```

I haven't tested whether this generalizes to `condition|p|id` etc. 

Also, the default arguments for `shifted_lognormal` is `link_sigma = 'log'` and `link_ndt = 'log'`. Yet, when I run it

    fit = brm(y ~ condition + (0 + condition | id), data, family=shifted_lognormal())

the top of the fit summary says that they were fit using `identity`

```
> fit
 Family: shifted_lognormal 
  Links: mu = identity; sigma = identity; ndt = identity
...
```

The same is true for `skew_normal()` and `exgaussian()`. I haven't tested others.

(Yes, I am modeling reaction times, and brms continues to be such a pleasure to use. Thank you again!)

**Comment by paul-buerkner** [comment]
The behavior of `||` is not what I see in my examples so I will need a minimal reproducible example from you.

The thing with the links is intentional and correct. The links only apply if those parameters are **predicted** (by a formula in the model) as per documentation of the arguments. That is, if they are just assumed constant across observations, the parameter is on the natural scale, i.e. has identity link.

**Comment by lindeloev** [comment]
You are right on both accounts! I'll close this issue now.

For future googlers, the documentation for `?brmsfamily` does indeed say, e.g., 

    link_sigma: Link of auxiliary parameter sigma if being predicted.

One reason I got confused was the fact that the "log-transformation" is applied in the family `shifted_lognormal` independently of the link function. So when links are `identity`, `mu` and `sigma` priors and parameters are on the log-scale with respect to the raw data while `ndt` is still on the "raw" scale.
