### ISSUE TITLE
Allow fixing non-linear parameters

### ISSUE THREAD

**Issue by paul-buerkner** [paul-buerkner/brms#734]
See https://discourse.mc-stan.org/t/syntax-to-fix-a-nonlinear-parameter-to-a-constant-value/10487/5 for the proposal.

**Comment by jackobailey** [comment]
Is this something you could incorporate into the prior argument?

For example, you might consider using an argument such as `fix(n)` where `n` is the value we want to fix some coefficient to? I imagine that this would be easier than adding a whole new implementation. It would allow you to extend it to _all_ parameters and not just those in non-linear models, which might help when you come to implement latent variable models.

Anticipating pushback, I'd argue that there is little difference between placing a prior and placing a constraint on a parameter. Indeed, the latter is just a special version of the former where we assume that our uncertainty about a parameter's true value is zero.

**Comment by paul-buerkner** [comment]
I agree. It will mostly be a question of which interface is more intuitive
to users and which requires less work for me. Not sure about both yet but
in any case this is a feature worth implementing.

Jack Bailey <notifications@github.com> schrieb am Mi., 9. Okt. 2019, 18:40:

**Comment by paul-buerkner** [comment]
With the new `constant` prior feature (#783), fixing non-linear parameters is now straightforward. Here is an example:

```R
x <- rnorm(100)
y <- rnorm(100, mean = 2 - 1.5^x, sd = 1)
dat <- data.frame(x, y)

bprior <- prior(constant(2), nlpar = a1) +
  prior(constant(1.5), nlpar = a2)

fit <- brm(bf(y ~ a1 - a2^x, a1 + a2 ~ 1, nl = TRUE),
            data = dat, prior = bprior)

summary(fit)
conditional_effects(fit)
conditional_effects(fit, method = "pp")
```
