### ISSUE TITLE
Rename 'marginal_effects' to 'conditional_effects'

### ISSUE THREAD

**Issue by paul-buerkner** [paul-buerkner/brms#735]
The name `marginal_effects` is one of the biggest still existing misnomers in brms. As `marginal_effects` really computes effects conditional on (fixed values of) other predictors it should be named appropriately. The old name will rename in brms but will be deprecated.

**Comment by jackobailey** [comment]
Paul, are you planning on including a marginal_effects function? I have rough working copies of functions to calculate average marginal effects for continuous variables and factors and was planning to turn them into a small package at some point. If you're going to work on this, I won't bother.

**Comment by paul-buerkner** [comment]
I have some issues open in this regard, but really computing marginal effects is not trivial in general. In particular, over what do we marginalize and how? I am open for any ideas and suggestions in this regard.

**Comment by jackobailey** [comment]
In my attempted, I've basically ported some of the functions of the margins package by @leeper.

If you're interested, [here's a gist](https://gist.github.com/jackobailey/0982c89326c36b12d6fa6d6f182189be).

**Comment by paul-buerkner** [comment]
Thank you @jackobailey! Would you mind open a new issue for this as I am about to close this one here?

**Comment by jackobailey** [comment]
Done!
