### ISSUE TITLE
Possibility to set seed in kfold.brmsfit

### ISSUE THREAD

**Issue by annahake** [paul-buerkner/brms#736]
Hi Paul, 

is there a way to pass a seed directly to the kfold.brmsfit function?

**Comment by paul-buerkner** [comment]
There is not, but you can set the seed yourself right before calling kfold. Or is there any reasons why this wouldn't work?

**Comment by annahake** [comment]
No, that is fine as well. 
I just wasn't sure if setting the seed before kfold was enough if several random steps are happening inside the function (stratification, dividing into folds, computing the chains) or if you need to set the seed before each separate step (internally) or maybe that another seed is set internally. 

But I think you are right, and there should be no difference.

**Comment by paul-buerkner** [comment]
I would think setting it outside should be fine.

**Comment by annahake** [comment]
The reason I asked initially is because of the definition of the brm function. There you can pass the seed, and in the documentation it is said that 

> The seed for random number generation to make results reproducible. If NA (the
> default), Stan will set the seed randomly

Just of curiosity, would a seed set outside the brm function always lead to the same seed setting done by Stan, if not passed explicitly to the brm function?

**Comment by paul-buerkner** [comment]
Good point. No it would not lead to the same seet as Stan does not simply use the R seed. But now that I think of it, you should be able to use the `seed` argument in `kfold` and it should be passed to brm and then to Stan behind the scenes. Or is there any error occuring during that process?

**Comment by annahake** [comment]
I haven't tried (I ended up not using the function because of other reasons). 
From the definition, I guessed that it is not just taken from the global scope. The question was if the given seed s1 in R, would always lead to the same seed setting in Stan:  s2=set.seed(rnorm(1)) (unfortunately I am not familiar with the Stan language). 

Thanks for the clarification!

**Comment by annahake** [comment]
Add-on: I think you are right and there is no error with passing the seed.
