### ISSUE TITLE
pp_check with censored data

### ISSUE THREAD

**Issue by andymilne** [paul-buerkner/brms#744]
Should it be possible to run pp_check with censored data? The following example results in the following error

```
fit3 <- brm(time | cens(censored) ~ age * sex + disease + (1|patient),
            data = kidney, family = lognormal())
pp_check(fit3)

Using 10 posterior samples for ppc type 'dens_overlay' by default.
Error in !cens : invalid argument type
In addition: Warning messages:
1: In drawGTree(x) : reached elapsed time limit
2: Censored responses are not shown in 'pp_check'. 
```

**Comment by paul-buerkner** [comment]
thanks! Should be fixed now

**Comment by lymanmark** [comment]
Seems to work with a numeric censoring variable, but a character variable ("right", "none", etc.) still has the same issue.

kidney <- kidney %>%
  mutate(censored_alt = if_else(censored == 1, "right", "none"))

fit3 <- brm(time | cens(censored_alt) ~ age * sex + disease + (1|patient),
                    data = kidney, family = lognormal())
pp_check(fit3)

**Comment by paul-buerkner** [comment]
You are right. Should be fixed now.
