### ISSUE TITLE
create brmsfit object with empty $fit slot without need to compile model

### ISSUE THREAD

**Issue by TedwardErker** [paul-buerkner/brms#745]
brms provides the great feature of outputting Stan code and Stan data which can be run via CmdStan.  But once the posterior samples are saved from CmdStan there is not efficient way to read them back into a brmsfit object so that brmsfit methods can be used to understand the samples.  A workaround is to run 

```
model <- brm(<your arguments>, chains = 0)
model$fit <- read_stan_csv(...)
model <- brms:::rename_pars(model)
summary(model)
```
quoted from:  https://discourse.mc-stan.org/t/using-brms-functionality-for-data-generated-in-cmdstan/6278/4

Unfortunately the model still compiles, which can take considerable time.  

Feature request: add an argument to the `brm` function which would create a brmsfit object with an empty $fit slot, but won't compile the model in doing so.  This would essentially fill all the other slots of brmsfit object from the arguments to the function and then stop there.

**Comment by davidfoxcroft** [comment]
This is very useful for me using latest version of cmdstan and cmdstanr. Would be good to have the nocompile feature as well - that would be the icing on the cake!

**Comment by paul-buerkner** [comment]
This feature should now be supported. Here is an example:

```
# fit a model manually via rstan
scode <- make_stancode(count ~ Trt, epilepsy)
sdata <- make_standata(count ~ Trt, epilepsy)
stanfit <- rstan::stan(model_code = scode, data = sdata)
# feed the Stan model back into brms
fit8 <- brm(count ~ Trt, epilepsy, empty = TRUE)
fit8$fit <- stanfit
fit8 <- rename_pars(fit8)
summary(fit8)
```

**Comment by potash** [comment]
I am trying to do this using the return value of `cmstandR::cmdstan_model` instead of `rstan::stan` and I get the following error:

```
> summary(fit8)
Error in summary.brmsfit(fit8) : 
  trying to get slot "sim" from an object (class "CmdStanMCMC") that is not an S4 object 
```

I would prefer to use cmdstanR for various reasons. Is this possible?

**Comment by paul-buerkner** [comment]
Not yet. At least not like this. only in version 3.0 will brms start
storing also cmdstanr fit objects in $fit. For the time being they are
converted to rstan fit objects.

Eric Potash ***@***.***> schrieb am Mo., 3. Juni 2024, 20:49:
