### ISSUE TITLE
Make it possible to choose what random effects to save

### ISSUE THREAD

**Issue by jonsjoberg** [paul-buerkner/brms#746]
Currently the `save_ranef` argument either saves all random effects or none, it would be great if it was possible to choose what random effects to save.

My usecase for this is that I'm running IRT models on data that have quite a lot of "users" (1000 - 10 000) but I'm actually only interested in the parameters for the "items", so it would make my life easier if the "user" parameters where discarded.

**Comment by franzsf** [comment]
Just to double down on this request, maybe with a different spin. 

I'm working with a lot of health-related insurance claim and survey data. In modeling outcomes jointly, brms is fantastic in being able to estimate group-level correlations (e.g., within people, having hypertension as an outcome is likely correlated with that person having an outcome of heart disease, diabetes, etc.). 

However, I'd also like to discard the random effects (for both privacy and memory issues)  while preserving the estimated group-level sds and correlations in order to better simulate new people.

If this is already possible, that'd be good to know (happy to stand corrected here), but so far I've found that models where save_ranef = FALSE also refuse to predict new levels. 

Minimally-reproducible example:

```
library(data.table)
library(brms)


sim_data <- data.table("Person" = paste0("person_",seq(1,100,1)),
                       "out1" = 0,
                       "out2" = 0,
                       "out3" = 0)

sim_data[,RowNum := 1:.N]

sim_data[RowNum %% 2 == 0, out1 := 1]
sim_data[RowNum %% 2 == 0, out2 := 1]
sim_data[RowNum %% 2 == 0, out3 := 1]

out1_f <- bf(out1 ~ 1 + (1 | p | Person))
out2_f <- bf(out2 ~ 1 + (1 | p | Person))
out3_f <- bf(out3 ~ 1 + (1 | p | Person))

get_prior(out1_f+out2_f+out3_f,family = "bernoulli", data = sim_data)

mv_out <- brm(out1_f+out2_f+out3_f,
              family = "bernoulli",
              data = sim_data,
              prior = c(prior(normal(0,4), class = 'Intercept', resp = "out1"),
                        prior(normal(0,1), class = 'sd', resp = "out1"),
                        prior(normal(0,4), class = 'Intercept', resp = "out2"),
                        prior(normal(0,1), class = 'sd', resp = "out2"),
                        prior(normal(0,4), class = 'Intercept', resp = "out3"),
                        prior(normal(0,1), class = 'sd', resp = "out3"),
                        prior(lkj(2), class = "cor")),
              iter = 2000,
              warmup = 1000,
              save_ranef = FALSE,
              chains = 4,
              cores = 1)

new_data <- data.table("Person" = paste0("person_",seq(101,200,1)))

new_data_preds <- dcast(as.data.table(predict(mv_out,
                                        newdata = new_data,
                                        allow_new_levels = TRUE,
                                        nsamples = 1,
                                        summary = FALSE)),
                        V2 ~ V3, value.var = "value")

Error: Group-level effects for each level of group 'Person' not found. Please set 'save_ranef' to TRUE when fitting your model.
```

Thanks again for all your work on this package. It's truly changed how we do public policy work here.

**Comment by paul-buerkner** [comment]
Sds and Cors are store anyway. To get predictions for new levels without
old levels you have to change the sample_new_levels argument of predict.

franzsf <notifications@github.com> schrieb am Mi., 23. Okt. 2019, 17:35:

**Comment by franzsf** [comment]
Figured it was already implemented and I was just ignorant of this. Thanks!

**Comment by franzsf** [comment]
Attempted to change the sample_new_levels in the predict function to "gaussian" but still getting the same error.

```
new_data_preds <- dcast(as.data.table(predict(mv_out,
                                              newdata = new_data,
                                              re_formula = ~ (1 | p | Person),
                                              sample_new_levels = "gaussian",
                                              allow_new_levels = TRUE,
                                              nsamples = 1,
                                              summary = FALSE)),
                        V2 ~ V3, value.var = "value")
```

**Comment by franzsf** [comment]
... also, even with save_ranef = TRUE and allowing new levels, not having any luck reproducing things with new data. Works fine using the original levels and data.

Continuing the example:
```
# Use same data to predict
old_data_preds <- predict(mv_out,
                          nsamples = 1,
                          summary = FALSE)

old_data_preds_dt <- dcast(as.data.table(old_data_preds),V2 ~ V3)

# Correlations between outcomes among individuals look reasonable
cor(old_data_preds_dt[,.(out1,out2,out3)])

# Use new data to predict
new_data <- data.table("Person" = paste0("person_",seq(101,200,1)))

new_data_preds <- predict(mv_out,
                          newdata = new_data,
                          allow_new_levels = TRUE,
                          nsamples = 1,
                          summary = FALSE)

new_data_preds_dt <- dcast(as.data.table(new_data_preds),V2 ~ V3)

# Correlations not showing up
cor(new_data_preds_dt[,.(out1,out2,out3)])
```

**Comment by paul-buerkner** [comment]
I see. The current code structure always required the old random effects to be present. So allowing "gaussian" to work is basically a new feature. Can you please open a separate issue for it?

**Comment by paul-buerkner** [comment]
This feature is now implemented via function `save_pars()`.
