### ISSUE TITLE
add a few words for the new effective sample size statistics

### ISSUE THREAD

**Issue by ASKurz** [paul-buerkner/brms#747]
The new `Bulk_ESS` and `Tail_ESS` columns in the `print()` output starting with 2.10.0 seem like a big change. It might be helpful to add a couple of words about them in the *Reference manua*l or perhaps add the citation for your rank-normalization paper.

**Comment by paul-buerkner** [comment]
Good point. I will add that!

**Comment by ASKurz** [comment]
Thanks, Paul.

**Comment by paul-buerkner** [comment]
Added a citation to our new Rhat paper which also contains high level recommendations for users.
