### ISSUE TITLE
double tildes work but cause errors later

### ISSUE THREAD

**Issue by rubenarslan** [paul-buerkner/brms#749]
I fit a model with a formula like the following (accidentally duplicated tildes):

```r
outcome ~~ s(days) + (1 | group)
```

This model fit fine, but when I wanted to use `fitted` with the argument `re_formula` set to `NA`, I got the error 

> Error in terms.formula(as.formula(x)) : invalid model formula

This took me a while to debug (Thanks `options(error = recover)`!). Obviously it's an error on my part, but maybe brms could stop me from fitting a model with invalid syntax in the first place?

PS.: I could hotfix this by overwriting the relevant `model$formula$forms`, which was nice, because the model took days to fit.

**Comment by paul-buerkner** [comment]
This is an intersting bug I must say! I will check for the use of `~~` and throw an informative error if it occurs.

**Comment by paul-buerkner** [comment]
Should be fixed now.
