### ISSUE TITLE
zero inflated beta: link specs inconsistent

### ISSUE THREAD

**Issue by balthasarbickel** [paul-buerkner/brms#751]
When I fit a `brm` model with `family = zero_inflated_beta()`, the `summary` of the model fit reports `Links: mu = logit; phi = identity; zi = identity`, while `?zero_inflated_beta()` stipulates `link = "logit", link_phi = "log", link_zi = "logit"` as defaults. The summary output does not change when I manually set the links in `zero_inflated_beta()` to a non-default, e.g. `link_phi = "identity"`. If I understand `stancode` correctly, `zi` is eventually estimated with a logit link, as given in the default, so perhaps the `zero_inflated_beta()` specs are correct, and this is all only a low-lever error in the `summary` report? But I am not sure about `phi`. Any help or fix is greatly appreciated!

**Comment by paul-buerkner** [comment]
As per documentation the link applies only if the parameter it predicted
(using predictors) which by default zi is not.

Balthasar Bickel <notifications@github.com> schrieb am Sa., 14. Sep. 2019,
14:25:

**Comment by balthasarbickel** [comment]
Ah, yes, right! Sorry for the misinterpretation and many thanks for the fast response!
