### ISSUE TITLE
resp_se() for Dirichlet models

### ISSUE THREAD

**Issue by elliottmorris** [paul-buerkner/brms#754]
Are there plans to implement the resp_se function for Dirichlet regression?

As in:

```
brm(y | se(x) ~ x,
    family = dirichlet(link = "logit", link_phi = "log"))`
```

I am trying to compute a time-series of variables that sum to 1 but also have (sometimes) significant measurement error. Maybe there’s another way to do this?

Related question: can I specify a number in the se() function to pass the model a predetermined standard error?

Thanks,
Elliott

**Comment by paul-buerkner** [comment]
Please excuse my slow response on discourse. The last couple of weeks have been too busy for me.

I don't have any idea how to incorporate known standard errors into a dirichlet distribution,
so this is not about planning to implement it but about the lack of an appropriate statistical model.
Accordingly, I currently don't see a way to implement this feature.

I don't understand your related question but I assume you can simply try out what you have in mind and see if it works.

**Comment by elliottmorris** [comment]
Thanks very much.
