### ISSUE TITLE
can't change the prior for a model where the sigma is also a parameter

### ISSUE THREAD

**Issue by bnicenboim** [paul-buerkner/brms#758]
I would assume that I'm setting all the priors in the following model:
```
brms(bf(X ~ Y, sigma ~ Y),data= tibble(Y=rnorm(10), X= rnorm(10)),
              prior= c(
                  prior(normal(0, 10), class = Intercept),
                  prior(normal(0, 1), class = b)
              ))
```
However, when I check this:

```
make_stancode(bf(X ~ Y, sigma ~ Y),data= tibble(Y=rnorm(10), X= rnorm(10)),
              prior= c(
                  prior(normal(0, 10), class = Intercept),
                  prior(normal(0, 1), class = b)
              ))
```
There is no prior for `b_sigma` and, `Intercept_sigma` gets a default `student_t`.

Doing `get_prior` tells me that I should be able to change all the priors by setting the classes "b" and "Intercept".

Maybe related to #213 ?

**Comment by bnicenboim** [comment]
ok, I see that I can de
` prior(normal(0,10), class = Intercept, dpar= sigma)` and it will work, but I assumed that setting a value for the class would be enough

**Comment by paul-buerkner** [comment]
In some cases, it is enough, it some cases it is not. This is admittedly inconsistent and I will make is more consistent as part of brms 3.0. Are you ok with closing this issue?

**Comment by bnicenboim** [comment]
I know I'm driving you crazy with this, but please consider adding a message (or warning :) ) for the priors that are being used with their default value. I discovered that I wasn't setting a prior on sigma, completely by chance: A typo on another prior led me to do `make_stancode` and surprise student-t!

**Comment by paul-buerkner** [comment]
I will look out for an elegant way to check if default prior are applied and then think of a good way of informing the user. If I spam them with warnings, they will just learn to ignore them, so there needs to be a better way (and throwing an error is too strong of a reaction in general).

**Comment by bnicenboim** [comment]
I would do it like the `_join`  or read_*` family. Maybe just a couple of lines saying for which parameters the model is using default priors, no need to tell which priors these are (if you think it's too much).
Anyway, these are my two cents as a user :)

**Comment by paul-buerkner** [comment]
Yeas this sounds very reasonable and helpful.

Bruno Nicenboim <notifications@github.com> schrieb am Mi., 18. Sep. 2019,
16:42:

**Comment by lindeloev** [comment]
I also have to double-check which priors I actually set. Could `get_prior` be extended to also take manually specified priors and update the list with those? So you could check the priors doing something like

    formula = y ~ x + ( stuff | group)
    priors = c(set_prior('normal(0, 1)', coef='b'), 
                     set_prior('gamma(4, 7)', coef='sd'))
    get_prior(formula, data, family=normal(), prior=priors)


I currently hack this behavior by making the sampling run for 1 iteration and then look at `fit$prior`.

**Comment by paul-buerkner** [comment]
With brms 2.10.0 you can use

```
c(get_prior(...), <your priors>, replace = TRUE)
```

and it should update the priors returned by get_prior
