### ISSUE TITLE
brm is trying to allocate a very big memory

### ISSUE THREAD

**Issue by fanne-stat** [paul-buerkner/brms#759]
I was trying to use brm on server. And I tried the example in the documentation, then there is an error. I don't know why brm is trying to allocate such a big vector.

```
> fit1 <- brm(count ~ zAge + zBase * Trt + (1|patient),
+             data = epilepsy, family = poisson(), prior = bprior1)
Compiling the C++ model
recompiling to avoid crashing R session
Start sampling
Error: cannot allocate vector of size 1040903.7 Gb
```

**Comment by paul-buerkner** [comment]
I don't know either. You may want to ask your server admin about this.

Yifan Zhu <notifications@github.com> schrieb am Mi., 18. Sep. 2019, 22:55:
