### ISSUE TITLE
Error using launch_shinystan when using options(encoding = "UFT-8")

### ISSUE THREAD

**Issue by willemvdb42** [paul-buerkner/brms#760]
Hi,

I'm trying to launch shinystan on a `brmsfit` model: `launch_shinystan(myModel)`. However this produces the following error:

> Warning in readLines(path, warn = FALSE, encoding = "UTF-8") :
  invalid input found on input connection 'html/mcse.html'
Warning: Error in sub: input string 1 is invalid UTF-8
  [No stack trace available]

The problem is solved by first setting the encoding to the native system encoding using `options(encoding = "native.enc")` and then using `launch_shinystan(myModel)` again.

I can reproduce this problem simply by changing the encoding back to UTF-8, i.e. first running `options(encoding = "UTF-8")` and then using `launch_shinystan(myModel)`.

I'm not sure where but my suspicion is that an `encoding` argument in a function call is not properly set. (But I could be wrong.)

**Comment by paul-buerkner** [comment]
Hi, can you open this issue on the shinystan page https://github.com/stan-dev/shinystan as I don't think this is actually related to brms.

**Comment by willemvdb42** [comment]
Done: https://github.com/stan-dev/shinystan/issues/171

**Comment by paul-buerkner** [comment]
Thanks a lot! Closing this issue here.
