### ISSUE TITLE
brms should show a message when it uses default priors

### ISSUE THREAD

**Issue by bnicenboim** [paul-buerkner/brms#761]
I think the less invasive way would be that a `brm()` call shows in a message all the priors that are left unspecified and are taking the default values (maybe showing the default PDFs or not.) 

This could be done in a similar way as the `_join`  and the `read_` family.

**Comment by ishisht** [comment]
I am not sure whether this should be a separate issue, but it is at least related:
If I understand correctly, functions showing prior specifications (e.g., get_prior and prior_summary) show a blank line both when no prior is specified (and no default prior has been imposed), and when a (vectorized?) prior from a previous parameter is used. I think it would be very helpful if this could be made explicit (e.g., 'v' for vectorized, '-' for no prior, and perhaps also 'd' for default).

**Comment by paul-buerkner** [comment]
That is a good idea. I will have to think about this a little more and then provide a proposal here.

**Comment by ishisht** [comment]
Ok, sounds good!

**Comment by edwardabraham** [comment]
Personally, I would prefer not to have messages shown as a result of the call to brm(), as I prefer to only get messages when there is a warning or an error hat I really need to pay attention to. But, I like the idea of @ishisht that the information shows up in get_prior() and prior_summary() calls.

**Comment by paul-buerkner** [comment]
I extended brmsprior objects to show the source of the priors when printed. For example:

```R
prior1 <- prior(normal(0,10), class = b) +
  prior(cauchy(0,2), class = sd)
fit1 <- brm(count ~ zAge + zBase * Trt + (1|patient),
            data = epilepsy, family = poisson(), prior = prior1)
prior_summary(fit1)
### output
                   prior     class       coef   group resp dpar nlpar bound       source
1          normal(0, 10)         b                                                  user
2          normal(0, 10)         b       Trt1                               (vectorized)
3          normal(0, 10)         b       zAge                               (vectorized)
4          normal(0, 10)         b      zBase                               (vectorized)
5          normal(0, 10)         b zBase:Trt1                               (vectorized)
6 student_t(3, 1.4, 2.5) Intercept                                               default
7           cauchy(0, 2)        sd                                                  user
8           cauchy(0, 2)        sd            patient                       (vectorized)
9           cauchy(0, 2)        sd  Intercept patient                       (vectorized)
```

Comments are welcome! 

I am hesistant to show messages about default priors to be honest, although I understand the motivation behind it. For the time being, no messages about default prior will be shown.

**Comment by bnicenboim** [comment]
Hey, that looks great. But consider adding a verbose option maybe? It could be that if options(brms.verbose = TRUE) then the output is pedantic and tells you that you didn't set all the priors. Something like

```
The following prior was automatically added to the model:
prior(student_t(3, 1.4, 2.5), class = Intercept)
```
And then one can always copy&pasted to avoid getting it. But it's just an idea...

**Comment by paul-buerkner** [comment]
Yeah, that is a good idea.

**Comment by paul-buerkner** [comment]
I added this feature (using `brms.verbose` option) but note that this is an experimental implementation that is not officially supported or documented for now. 

It may yield false positives, that is, default priors which are unused because all the lower level priors have been specified.  I am too tired to solve this now but may give it a try later on .
