### ISSUE TITLE
compatibility with modified stan-code

### ISSUE THREAD

**Issue by Raoul-Kima** [paul-buerkner/brms#763]
Today I had a BRMS model where I wanted to test a Prior that BRMS didn't seem to support. (target+=1/sigma).

BRMS made it mostly easy for me, by providint the make_stancode() and make_standata() functions, such that I could just change it myself and fit the model with rstan::stan().

The problem then was that rstan::stan() of course gives back a stanfit object, not a brmsfit object.

At first I thought this wouldnt be a problem as I was using the package tidybayes for acessing the model, which is compatible with both stanfit and brmsfit objects.

However, it turned out that In this stanfit object all the variables had different names than in the brmsfit-object. so extracting the data would have required me to to a lengthy hand-written variable name extraction and conversion.

It might be a good idea to have a way to make such a transition easier, e.g. by having a function to convert the stanfit back to a brmsfit (with corresponding variable name changes) or by allowing to specify modified stancode when calling brm().

**Comment by paul-buerkner** [comment]
We have an issue for this already, which also provides a link to the currently recommended approach: #745
