### ISSUE TITLE
extract stanfit from brmsfit

### ISSUE THREAD

**Issue by Raoul-Kima** [paul-buerkner/brms#764]
stanfit objects provide some useful funcionality that brmsfit objects are lacking (e.g. a method for pairs()). Therefore it would be great if the underlying stanfit object coud be extracted from a brmsfit object.

**Comment by mvuorre** [comment]
If your brms model is called `fit`, then `fit$fit` contains the stanfit object.

**Comment by paul-buerkner** [comment]
But what methods do you need from Stanfit exactly because pairs does work
for brmsfit objects as well.

Matti Vuorre <notifications@github.com> schrieb am Di., 24. Sep. 2019,
19:55:

**Comment by Raoul-Kima** [comment]
Uh, how could I miss that! (both things you mentioned!)

In this case I retract my suggestion.

I'm not sure why I couldn't figure it out in this case. Usually I'm smart enougth fo find these things. But still, it would be useful to have an accessor function for that. Digging around in the internals of big complex objects makes me feel somewhat uneasy, as usually the documentation does not explicitly state that these internals will remain the same in future package versions.

About which methods I was thinking:
Mostly pairs(), but this was also just a general Idea, as anyone could potentially write methods for stanfit objects in any package.

(Is it my job to close this issue now? I'm not so familiar with the github way of things)

**Comment by paul-buerkner** [comment]
No worries, it happens to all of us. :-) 

I will think of whether an extractor method makes sense to add.

**Comment by Raoul-Kima** [comment]
Just another comment:
After trying pairs() on a complicated brms-model where it always crashed, I today tried with a simpler one, where it did work. I turned out, though, that the pairs methods for brms-objects is not the same as the one for stanfit objects.

**Comment by paul-buerkner** [comment]
Yeah, that is actually true. brms uses bayesplot::mcmc_pairs for computing the pairs plot.

```R
function(x, pars = NA, exact_match = FALSE, ...) {
  if (!is.character(pars)) {
    pars <- default_plot_pars(x)
    exact_match <- FALSE
  }
  samples <- posterior_samples(
    x, pars, add_chain = TRUE, exact_match = exact_match
  )
  samples$iter <- NULL
  bayesplot::mcmc_pairs(samples, ...)
}
```

**Comment by Raoul-Kima** [comment]
Just to add:
I encountered the following situation:
Assuming "model" is a brmsfit object:
plot(model$fit) didn't work.
launch_shinystan(model) didn't include warmup samples
launch_shinystan(model$fit) had the warmup, but was missing model parameters.
