### ISSUE TITLE
  'scale' of the data must be specified

### ISSUE THREAD

**Issue by fishextinction** [paul-buerkner/brms#765]
I am running the first example in: 
https://cran.r-project.org/web/packages/brms/vignettes/brms_distreg.html

and I get the following error:
```
group <- rep(c("treat", "placebo"), each = 30)
symptom_post <- c(rnorm(30, mean = 1, sd = 2), rnorm(30, mean = 0, sd = 1))
dat1 <- data.frame(group, symptom_post)
fit1 <- brm(bf(symptom_post ~ group, sigma ~ group), data = dat1, family = gaussian())
Error in bf(symptom_post ~ group, sigma ~ group) : 
  'scale' of the data must be specified
```

**Comment by paul-buerkner** [comment]
Have you loaded other packages that also have a bf() function? Was does it
tell you when you just type bf in the console?

fishextinction <notifications@github.com> schrieb am Mi., 25. Sep. 2019,
08:50:

**Comment by fishextinction** [comment]
Thanks for the fast response Paul!

Opening a fresh instance of R, and tossing brms::: in front of brm and bf gets me a new error:
`Error: Parameter names should not contain dots or underscores.`

Quickly rewriting the code so that the variable is "symptompost" instead of "symptom_post" gets me the following error:
`Error: The parameter 'symptompost' is not a valid distributional or non-linear parameter. Did you forget to set 'nl = TRUE'?`

Then I changed sigma(symptompost) to just sigma:
```
fit1 <- brms:::brm(brms:::bf(symptompost ~ group, 
                             sigma ~ group),
            data = dat1, family = gaussian())
```
and the model appears to run! Slightly unfortunate though, because there's real value in specifying sigma of a particular variable, I think.

**Comment by paul-buerkner** [comment]
Can you give me a minimal reproducible example please?

**Comment by fishextinction** [comment]
```{r}
require(brms)
group <- rep(c("treat", "placebo"), each = 30)
symptom_post <- c(rnorm(30, mean = 1, sd = 2), rnorm(30, mean = 0, sd = 1))
dat1 <- data.frame(group, symptom_post)
fit1 <- brm(bf(symptom_post ~ group, sigma(symptom_post) ~ group), 
            data = dat1, family = gaussian())
```
Error: Parameter names should not contain dots or underscores.


```{r}
require(brms)
group <- rep(c("treat", "placebo"), each = 30)
symptompost <- c(rnorm(30, mean = 1, sd = 2), rnorm(30, mean = 0, sd = 1))
dat1 <- data.frame(group, symptompost)
fit1 <- brm(bf(symptompost ~ group, sigma(symptompost) ~ group), 
            data = dat1, family = gaussian())

```
Error: The parameter 'symptompost' is not a valid distributional or non-linear parameter. Did you forget to set 'nl = TRUE'?

```{r}
require(brms)
group <- rep(c("treat", "placebo"), each = 30)
symptompost <- c(rnorm(30, mean = 1, sd = 2), rnorm(30, mean = 0, sd = 1))
dat1 <- data.frame(group, symptompost)
fit1 <- brm(bf(symptompost ~ group, sigma ~ group), 
            data = dat1, family = gaussian())

```
(which works)

**Comment by paul-buerkner** [comment]
Oh I am sorry you did already in the first post. Sorry, I didn't see it. 

I would say there is not bug just a not supported syntax which throws unexpected error.
The latter of the three calls is the intended correct syntax. 

The syntax `sigma(symptompost) ~ ...` is not supported.

**Comment by fishextinction** [comment]
Weird, must have copy-pasted from the vignette incorrectly. Sorry about that!

In any case, I am pretty sure the original issue stemmed from package 'bridgesampling' being loaded at the same time with brms.
