### ISSUE TITLE
Ability to drop specified effects for fitted/predict/marginal_effects

### ISSUE THREAD

**Issue by andymilne** [paul-buerkner/brms#766]
It would be useful to be able to drop specified effects from the model by using an argument in fitted() or predict(). A particular use case would be a model with sum-coded predictors. The marginal effects plot of the main effect of interest is conditioned to the reference levels of the other categorical predictors. If would be useful to get those marginal effects conditioned on those other categorical variables at zero (i.e., not there), rather than at their reference levels. Maybe this is already possible (without refitting the model), but I couldn't see a way to do this.

**Comment by paul-buerkner** [comment]
This is already possible. As described in the doc of `marginal_effects` is says

NA values within factors in conditions, are interpreted as if all dummy variables of this factor are zero. This allows, for instance, to make predictions of the grand mean when using sum coding.

I think this is what you mean, right? The same functionality applies to fitted and predict.

**Comment by andymilne** [comment]
That's exactly what I mean -- thank you, sorry I didn't see that.

**Comment by andymilne** [comment]
Part of the reason I missed it is because there is no mention of this in the "conditions" part of the help file. Maybe it could be briefly mentioned there.

**Comment by paul-buerkner** [comment]
good point. I changed it accordingly.
