### ISSUE TITLE
Confusing output from prior_summary

### ISSUE THREAD

**Issue by sam-crawley** [paul-buerkner/brms#768]
When specifying a model with a prior applied to all parameters in a class, except for one parameter which has a different prior, the output of prior_summary is confusing.

e.g. this model should apply a normal(0,1) prior to cyl and hp predictors, but a normal(0,10) prior to disp predictor:

```
model <- brm(mpg ~ cyl + disp + hp, mtcars, family = gaussian, chains = 2, prior = c(
  prior(normal(0, 1), class = b),
  prior(normal(0, 10), class = b, coef = disp)
))
```
Looking at stancode output, the priors have been applied as expected:

```
model {
  // priors including all constants
  target += normal_lpdf(b[1] | 0, 1);
  target += normal_lpdf(b[2] | 0, 10);
  target += normal_lpdf(b[3] | 0, 1);
  target += student_t_lpdf(Intercept | 3, 19, 10);
  target += student_t_lpdf(sigma | 3, 0, 10)
    - 1 * student_t_lccdf(0 | 3, 0, 10);
  // likelihood including all constants
  if (!prior_only) {
    target += normal_id_glm_lpdf(Y | Xc, Intercept, b, sigma);
  }
}
```
However, the output of prior_summary suggests that the normal(0,10) prior has been applied to hp:

```
prior_summary(model)
                 prior     class coef group resp dpar nlpar bound
1         normal(0, 1)         b                                 
2                              b  cyl                            
3        normal(0, 10)         b disp                            
4                              b   hp                            
5 student_t(3, 19, 10) Intercept                                 
6  student_t(3, 0, 10)     sigma   
```
It looks like some sorting on coef is happening in the output when it shouldn't be.

**Comment by paul-buerkner** [comment]
`prior_summary` merely shows the `$prior` slot of brmsfit objects, which is ordered alphabetically. As explained in `?set_prior` the prior specification of brms is hierarchical in the specified arguments and so the order in the output does not matter. In some cases ordering after prior usage as you suggest may even not be uniquely possible due in more complex models. Accordingly, I would like to stick to the current alphabetical ordering. That said, I may restructure the brms prior system a little bit in brms 3.0 in which case things may change to the better.
