### ISSUE TITLE
multilevel mixture models

### ISSUE THREAD

**Issue by paoloeusebi** [paul-buerkner/brms#774]
It would be great to use brms to estimate multilevel mixture models. This would provide a useful tool in several applications. One example is interventional and diagnostic meta-analysis.
I developed a method for which Bayesian code would be helpful.
https://bmcmedresmethodol.biomedcentral.com/articles/10.1186/1471-2288-14-88
I was able to write WinBUGS code
WinBUGS14 code for the Latent Class Bivariate Model.

model 	
{                  			   
    # likelihood 
for( i in 1:n ) {
		# distribution of latent memberships (equation 4)
		T[i] ~ dcat(p[i,1:K]) 		
		# distribution of observed sensitivity and specificity (equation 5)			
		tp[i] ~ dbin(tpr[i],n1[i])  					
		tn[i] ~ dbin(tnr[i],n0[i])
		# logistic model for sensitivity and specificity (equation 6)
		logit(tpr[i]) <- logit.se[T[i]]+m[i,T[i],1]					
		logit(tnr[i]) <- logit.sp[T[i]]+m[i,T[i],2]
		#  distribution of random effects (equations 7-8)
		m[i,1,1:2] ~ dmnorm(mu.0[1,1:2],sigma.inv[1,1:2,1:2])	
		m[i,2,1:2] ~ dmnorm(mu.0[2,1:2],sigma.inv[2,1:2,1:2])
		# logistic model class proportions with covariate (here test) effects (equation 9)
		for (k in 1:K) {									
			p[i,k] <- ebx[i,k]/sum(ebx[i,])
			ebx[i,k]<-exp(b0[k]+b1[k]*test[i])
		}
	}
	# prior distributions
	b0[1]<-0
	b1[1]<-0
	for (k in 2:K) {
		b0[k] ~ dnorm(0,0.25)
		b1[k]~ dnorm(0,0.25)
	}
	for (k in 1:K) {
		logit.se[k] ~ dnorm(0,0.25)
		logit.sp[k] ~ dnorm(0,0.25)
		sigma.inv[k,1:2,1:2] ~ dwish(Omega[1:2,1:2],2)
		mu.0[k,1] <-0
		mu.0[k,2] <-0
	}
	# computation of sensitivities and specificities at value 0 of random effects by marginalizing over classes
	# class-specific sensitivity and specificity and class proportions depending on the test
  	for (k in 1:K) {
		se[k]<-exp(logit.se[k])/(1+exp(logit.se[k]))	
		sp[k]<-exp(logit.sp[k])/(1+exp(logit.sp[k]))
		p0[k] <- eb0[k]/sum(eb0[])
		eb0[k]<-exp(b0[k]+b1[k]*0)
		p1[k] <- eb1[k]/sum(eb1[])
		eb1[k]<-exp(b0[k]+b1[k]*1)
	}
	# pooling results across K=2 classes for both tests
	se.test0<-se[1]*p0[1]+se[2]*p0[2]		
	se.test1<-se[1]*p1[1]+se[2]*p1[2]
	sp.test0<-sp[1]*p0[1]+sp[2]*p0[2]		
	sp.test1<-sp[1]*p1[1]+sp[2]*p1[2]
}
    #data
    #n (number of studies)
    #K (number of latent classes)
    #test (covariate for the index test, 0=CT 1=MRI).
    #tp=true positives, tn=true negatives, n0=non disease, n1, n1=disease
list(n=108,K=2,test=c(0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,1,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1),
tp=c(25,57,17,64,7,12,12,73,52,20,13,21,18,77,9,42,31,62,42,11,59,33,58,16,17,29,28,11,29,18,19,72,
101,12,28,19,16,18,19,43,11,42,17,97,32,30,56,20,33,11,25,18,20,47,69,35,15,15,3,179,43,75,13,18,
88,244,139,41,106,31,38,30,32,4,38,15,62,8,66,56,42,16,17,25,53,38,12,34,40,49,43,35,25,41,42,10,
14,13,66,29,104,55,50,116,32,44,76,32),
tn=c(19,79,44,32,1,1,8,22,142,51,5,3,7,16,23,30,26,46,39,17,6,5,70,48,6,13,35,35,10,13,9,16,
106,6,12,30,23,10,9,28,33,7,16,18,12,9,18,13,8,25,40,27,60,20,35,33,2,3,12,119,9,65,8,48,
12,73,115,20,18,17,12,21,24,52,23,13,18,5,43,31,34,53,43,9,42,27,21,8,30,15,123,28,50,47,56,7,
15,35,50,28,20,43,22,33,6,37,20,23),
n1=c(25,59,17,64,7,15,12,73,55,20,14,25,19,84,9,54,33,66,49,11,60,36,59,17,19,35,29,11,30,22,20,85,
102,13,28,19,16,18,21,45,17,47,17,113,34,34,60,22,34,13,26,26,21,47,71,36,16,16,3,191,43,77,15,18,
88,246,163,51,106,31,38,35,32,5,39,18,62,9,66,60,47,17,17,25,54,40,13,36,40,49,43,41,26,42,51,11,
15,13,66,31,108,55,51,118,36,45,77,34),
n0=c(23,91,44,36,2,4,10,27,172,52,6,3,7,29,24,34,29,51,41,18,7,7,128,50,7,24,37,44,10,18,10,26,
141,7,12,36,24,12,12,30,41,22,18,36,18,18,43,24,16,27,42,42,67,20,43,38,4,4,12,136,18,70,14,52,
16,114,128,31,21,20,13,23,25,55,29,13,18,6,50,36,39,60,60,10,46,30,27,14,36,52,125,36,55,58,62,8,
15,37,54,29,30,45,27,35,12,40,23,28),
Omega=structure(.Data=c(1,0,0,1),.Dim=c(2,2)))

**Comment by paul-buerkner** [comment]
Thank you! Could you check whether your model is already supported via the mixture modeling approach of brms you can access via family `mixture`?

**Comment by paul-buerkner** [comment]
Did you check out the `mixture` feature yet on whether it allows you to fit the model you have in mind?

**Comment by paul-buerkner** [comment]
I haven't heard anything back from you so I will close this issue for the time being.
