### ISSUE TITLE
Enable combining censored (response) data with (fixed) correlation matrix

### ISSUE THREAD

**Issue by BenJohannes** [paul-buerkner/brms#776]
Currently, it seems brms is not able to combine censoring with a fixed correlation matrix:

```
require(brms)
set.seed(1234)
# 1. Start with the given example from ?brms::cor_fixed
dat <- data.frame(y = rnorm(3))
V <- cbind(c(0.5, 0.3, 0.2), c(0.3, 1, 0.1), c(0.2, 0.1, 0.2))
fit <- brm(y~1, data = dat, autocor = cor_fixed(V))
summary(fit)
# All fine
```

```
# 2. Enhance 'y'
dat$y <- dat$y + 2
fit_2 <- brm(y~1, data = dat, autocor = cor_fixed(V))
summary(fit_2) # no surprise; nearly the same, but +2
```

```
# 3. Introduce Independent Variable 'x'
dat$x <- sqrt(dat$y)
fit_3 <- brm(y~x, data = dat, autocor = cor_fixed(V))
summary(fit_3) # still all fine
```

```
# 4. Introduce censoring
dat$censoring <- c(0, 1, 0)
fit_4 <- brm(y|cens(censoring)~x, data = dat, autocor = NULL)
# OK, some warnings related to sample size and divergent transitions, which is understandable; massive estimation error, but no computation error:
summary(fit_4)
```

```
# 5. Combining censoring and autocor matrix:
fit_5 <- brm(y|cens(censoring)~x, data = dat, autocor = cor_fixed(V))
# And there we have it: "Error: Invalid addition arguments for this model"
```

The request is to make the combination of |cens(q) and autocor=cor_fixed(V) work without error.

**Comment by paul-buerkner** [comment]
The reason is that cor_fixed implies a multivariate normal distribution but we currently don't have the CDF of the multivariate normal available in Stan. However, the latter is required for censored models.

**Comment by BenJohannes** [comment]
OK, understandable. My autocorrlation data is at case level, estimated from observations outside of the parameters in the model (or in fact, based on another model with its own parameters).

I suspect that for now my workaround will be as follows:
1. Make multiple imputations (m) of censored (survival) data, so as to have m datasets with imputed times to event E for right-censored data, all cases having event E (either real or imputed), and no more censoring. The variance between these m datafiles should reflect the uncertainty caused by the censoring.
2. Apply brms::brm(..., autocor=cor_fixed(my_autocor_matrix)) to all imputed files.
3. Combine these with brms::combine_models() to have one final estimate per parameter.

In that way, I should have a reasonable approach of reflecting censoring uncertainty whilst also having autocorrelation corrections.

**Comment by paul-buerkner** [comment]
I believe this feature request is not implementable for the same reason as in #910. Closing this now.
