### ISSUE TITLE
Hypothesis with monotonic effects

### ISSUE THREAD

**Issue by jublaher95** [paul-buerkner/brms#778]
Hello,

Here is the problem I have found in brms library.

When performing a bayesian model with monotonic effects:

bprior1 <- prior(student_t(5,0,10), class = b) +    prior(cauchy(0,2), class = sd)
fit1 <- brm(count ~ mo(Age) + zBase * Trt + (1|patient), data = epilepsy, family = poisson(), prior = bprior1)

If we then try to test any hypothesis over the parameter of moAge, R cannot find it. Here is the error that the program shows:

hypothesis(fit1, "moAge=0")
Error: Some parameters cannot be found in the model: 'b_moAge'

How should I do this?

**Comment by paul-buerkner** [comment]
Thanks for opening this issue. This is because the prefix of `mo` parameters is `bsp` not `b`, an unfortunate design mistake I made that I aim to correct in brms 3.0. See #543 for details.

**Comment by jmgirard** [comment]
In case anyone else wants to do this before brms 3.0, you can recreate the hypothesis "by hand" using `posterior_samples()`. Using your example above and the `bayestestR` package, we can test your hypothesis pretty easily:

```r
samples <- brms::posterior_samples(fit1, pars = "bsp_moAge")
bayestestR::describe_posterior(samples)
```
