### ISSUE TITLE
Autoregressive Distributive Lag (ADL) model addition proposal

### ISSUE THREAD

**Issue by mansillo** [paul-buerkner/brms#781]
I would like to implement an autoregressive distributive lag model and from what I can tell at the moment, an ADL cannot be implemented with brms at the moment. These models are used a fair bit in ecology and [economics](https://www.econometrics-with-r.org/14-6-llsuic.html). The addition of the ADL model to the package would not be unappreciated. Perhaps including it in the `cor_ar` function?

… and by [`ADL(p,q)` model ](https://link.springer.com/content/pdf/10.1007%2F978-0-387-32348-0_6.pdf)I mean a model which assumes that a time series, `Y(t)` , can be represented by a linear function of `p` of its lagged values and `q` lags of another time series, `X(t)` .

Thanks!

**Comment by DoktorMike** [comment]
This is also related to the functionality I'm trying to achieve in #1127

**Comment by paul-buerkner** [comment]
I will close this issue for now to clean up the issue tracker a bit since this isn't high priority.
