### ISSUE TITLE
can't install brms

### ISSUE THREAD

**Issue by bholden7** [paul-buerkner/brms#784]
I get this error message when trying to install brms on my macbook pro (R, RStudio, everything is 100% up to date):
Compiling the C++ model
running command ''/Library/Frameworks/R.framework/Resources/bin/R' CMD config CXX14 2>/dev/null' had status 1C++ compiler not found on system. If absent, see
 https://github.com/stan-dev/rstan/wiki/RStan-Getting-Startedrunning command '/Library/Frameworks/R.framework/Resources/bin/R CMD SHLIB file145373b67f40.cpp 2> file145373b67f40.cpp.err.txt' had status 1Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Error in sink(type = "output") : invalid connection

**Comment by paul-buerkner** [comment]
This is not a brms related error. There are multiple threads on https://discourse.mc-stan.org/ that deal with such kinds of erros and if you can't find a solution in the existing threats, you can open a new one there.
