### ISSUE TITLE
still can't run bmrs

### ISSUE THREAD

**Issue by bholden7** [paul-buerkner/brms#785]
I installed xcode and I still can't run brms. Here is the code and error message:

library(rstan)
library(brms)

m0 <- brm(Sepal.Length ~ 1,
          data = iris, save_all_pars = TRUE)
m1 <- brm(Sepal.Length ~ Petal.Length,
          data = iris, save_all_pars = TRUE)
m2 <- brm(Sepal.Length ~ Species,
          data = iris, save_all_pars = TRUE)
m03 <- brm(Sepal.Length ~ Species + Petal.Length,
          data = iris, save_all_pars = TRUE)
m0 <- brm(Sepal.Length ~ Species * Petal.Length,
          data = iris, save_all_pars = TRUE)

Error in compileCode(f, code, language = language, verbose = verbose) : Compilation ERROR, function(s)/method(s) not created! clang: warning: no such sysroot directory: '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk' [-Wmissing-sysroot] In file included from file16464efd38fa.cpp:8: In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/StanHeaders/include/src/stan/model/model_header.hpp:4: In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/StanHeaders/include/stan/math.hpp:4: In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/StanHeaders/include/stan/math/rev/mat.hpp:4: In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/StanHeaders/include/stan/math/rev/core.hpp:4: In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/StanHeaders/include/stan/math/rev/core/autodiffstackstorage.hpp:4: In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/StanHeaders/i
Error in sink(type = "output") : invalid connection

**Comment by paul-buerkner** [comment]
I don't see the point of opening a second issue just 1 hour after opening the first one.

**Comment by bholden7** [comment]
The point was that I installed Xcode and still can’t get brms to run.


Billy Holden, PhD
email: billyholden7@gmail.com
mobile: 917.515.4227
