### ISSUE TITLE
Response's standard error when using skew_normal family

### ISSUE THREAD

**Issue by hrlai** [paul-buerkner/brms#786]
Hi Paul, I want to incorporate measurement errors into the response variable `y_i` that is left-skewed. Considering the simple example `yi | se(sei) ~ 1` when `family = skew_normal`, should `sei` be the standard error/deviation of `yi` or that of `log(yi)`? Thanks!

**Comment by paul-buerkner** [comment]
brms related questions are best asked on https://discourse.mc-stan.org using the Interfaces - brms tag, not as github issues.
