### ISSUE TITLE
Measurement error vignette? How to handle ordinal variables of a binned continuous variable where temporal measurement error is known.

### ISSUE THREAD

**Issue by mansillo** [paul-buerkner/brms#787]
I was hunting for a [vignette](https://cran.r-project.org/web/packages/brms/index.html) on using the measurement error feature in `brms` for the `me` function.
I have a series of cross-section surveys of a number of decades with family income as a measure. Income was measured in some cross-sections with the same exact measures while in other years the measures were different to better measure the income distribution as it changed through changes in the economy and inflation. I would like to standardise the measures to pool the data. I know the measurement error due to inflation thanks to the [central bank's data](https://www.rba.gov.au/calculator/). Is it possible to use the `me` function with an ordinal measurement, rather than say using the median of the lower and upper income thresholds of the categories, to correct for inflation?

For illustration...

**In 1993:**
Less than $3000
$3001 to $5000
$5001 to $8000
$8001 to $12000
$12001 to $16000
$16001 to $20000
$20001 to $25000
$25001 to $30000
$30001 to $35000
$35001 to $40000
$40001 to $50000
$50001 to $60000
$60001 to $70000
More than $70000

**In 2016:**
Less than $10,000 per year 
$10,001 to $15,000 per year 
$15,001 to $20,000 per year 
$20,001 to $25,000 per year 
$25,001 to $30,000 per year 
$30,001 to $35,000 per year 
$35,001 to $40,000 per year
$40,001 to $45,000 per year 
$45,001 to $50,000 per year 
$50,001 to $60,000 per year
$60,001 to $70,000 per year
$70,001 to $80,000 per year 
$80,001 to $90,000 per year 
$90,001 to $100,000 per year 
$100,001 to $110,000 per year 
$110,001 to $120,000 per year
$120,001 to $130,000 per year
$130,001 to $140,000 per year 
$140,001 to $150,000 per year
$150,001 to $160,000 per year 
$160,001 to $180,000 per year 
More than $180,000 per year

**Comment by paul-buerkner** [comment]
Currently not but this may become possible in brms 3 via structural equation models. In the future, please aks brms related questions on https://discourse.mc-stan.org/ using the Interfaces - brms tag ans github is reserved for feature requests and bug reports.
