### ISSUE TITLE
Multi-chain sampling progression

### ISSUE THREAD

**Issue by alireza202** [paul-buerkner/brms#79]
Is there a way to print out the sampling progression with multi chains? It's only printed when I have one chain.

**Comment by paul-buerkner** [comment]
You can use argument `cores` instead of `cluster`. This way you call the built in parallel code of rstan and when using RStudio, you can see the progress in the 'Viewer' panel. The only drawback of this is that you can also use the `PSOCK` cluster type.

**Comment by alireza202** [comment]
Thanks, it works!
