### ISSUE TITLE
Minor requests related to bayes_R2 and loo_R2

### ISSUE THREAD

**Issue by andymilne** [paul-buerkner/brms#793]
At present, it is possible to add Bayes R2 to a model `mdl` with 
`mdl <- add_criterion(mdl, "R2") `
and the R2 can be obtained with
`bayes_R2(mdl)`

Three minor things that might be worth considering are
1. It is slightly confusing that in add_criterion, it is called "R2", but the function applied is called "bayes_R2"
2. Maybe this is currently possible, but it is not documented, can `loo_R2` also be added to a fitted model? It would be useful if this were possible, given the amount of time it can take to calculate `loo_R2`.
3. Should there be `add_bayes_R2` and `add_loo_R2` aliases for `add_criterion`?

**Comment by paul-buerkner** [comment]
Those are good point. I will rename `R2` to `bayes_R2` and add `loo_R2`. I am not happy with the aliases of `add_criterion` in general and thought of deprecating the existing ones so I am hesitant to add new aliases at that point.

**Comment by paul-buerkner** [comment]
`loo_R2` can now be stored via `add_criterion` and `R2` has been renamed to `bayes_R` but continues to work with a deprecation warning.
