### ISSUE TITLE
Log file overflow on travis

### ISSUE THREAD

**Issue by dmenne** [paul-buerkner/brms#795]
Not an issue, just an info:

After a chaotic Wanderlust through dozens of variants for travis.yml (check rstan's jungle!), I reverted to your's, for package dmenne/breathteststan,  because it is slick and lean. It almost worked. I needed: 

`  -fext-numeric-literals`

to avoid log-overflow errors on travis.

**Comment by paul-buerkner** [comment]
Thank you for the info!
