### ISSUE TITLE
consider adding  brms.open_progress to options

### ISSUE THREAD

**Issue by bnicenboim** [paul-buerkner/brms#796]
I'm using a bunch of `brm()` calls in a bookdown, and every time I compile it I get the browser open. It would be nice if I could set globally to have `open_progress` set to FALSE.
In `rstan`, I solve it with `formals(stan)$open_progress <- FALSE` but I can't do it in brms because `open_progress` is not an argument of `brm()`,  (`open_progress` is accepted as part of the  `...` of the call).

**Comment by paul-buerkner** [comment]
It is strange that this happens. In rstan, the default for `open_progress` is

```
open_progress = interactive() && !isatty(stdout()) &&
                  !identical(Sys.getenv("RSTUDIO"), "1")
```

It seems, bookdown should somehow be called in a way that `open_progress` was `FALSE` by default anyway? At least, this is how it works with rmarkdown documents.

**Comment by bnicenboim** [comment]
mhhh, I think it works in Rstudio, but not in emacs when I do `render_book(...)`

**Comment by paul-buerkner** [comment]
Would that perhaps be an indication of changing the default in rstan? Also, since brms uses rstan::sampling. Changing the formals of that function should change the default for brm as well.

**Comment by bnicenboim** [comment]
I can't change the formals of `rstan::sampling`, because it has no arguments: just  `(object, ...)`

**Comment by paul-buerkner** [comment]
It is an S4 generic, you need to target the corresponding S4 method. Not sure if this is possible though...

**Comment by bnicenboim** [comment]
no idea how to do that

**Comment by paul-buerkner** [comment]
Me neither. I can add open_progress to brm but that put another maintenance burden on me if the default in rstan changes. Would it make sense for you to propose a change of defaults in rstan that captures your situation?

**Comment by bnicenboim** [comment]
https://github.com/stan-dev/rstan/issues/720
