### ISSUE TITLE
Potentially confusing syntax/behavior with "mixed" censoring of data

### ISSUE THREAD

**Issue by RaoulWolf** [paul-buerkner/brms#799]
Hi, I've recently started using `brms`' functionality to work with censored data. I have a data set with mixed censoring; it contains uncensored data (`"none"`), left-censored data (`"left"`), and interval-censored data (`"interval"`) in the same data set. I *think* I figured out a way to handle this correctly with `brms`, but it's quite clumsy; and involves manually picking arbitrary censoring values. A small regex to illustrate:

    library(brms)
    
    ## Defining censoring points
    left_point <- 0.01 # values below 0.01 are left-censored
    interval_point <- 0.1 # values below 0.1 (but above 0.01) are interval-censored
    
    ## Simulating lognormal data
    regex_data <- data.frame(y = rlnorm(n = 100, meanlog = -4, sdlog = 2))
    
    ## Creating "censored" column
    regex_data$censored <- ifelse(regex_data$y <= interval_point & regex_data$y > left_point, "interval", ifelse(regex_data$y <= left_point, "left", "none"))
    
    ## Updating y column to reflect censoring
    regex_data$y <- ifelse(regex_data$censored == "left", left_point, ifelse(regex_data$censored == "interval", left_point, regex_data$y))
    
    ## Adding y2 column for interval-censored data
    regex_data$y2 <- ifelse(regex_data$censored == "interval", interval_point, NA_real_)

Running a `brm` gives me the following warning:

    regex.brm1 <- brm(bf(y | cens(censored, y2) ~ 1, family = lognormal), data = regex_data)
    
    Warning messages:
    1: Rows containing NAs were excluded from the model. 

Checking for the model data, I see that some rows have indeed been omitted (71 instead of 100).

    nrow(regex.brm1$data)
    [1] 71

I then updated the `y2` column for left-censored data, using the same censoring value, which intuitively feels very odd! I reran the model, checking for missing rows.

    regex_data$y2 <- ifelse(regex_data$censored == "left", left_point, regex_data$y2)
    regex.brm2 <- brm(bf(y | cens(censored, y2) ~ 1, family = lognormal), data = regex_data)
    nrow(regex.brm2$data)
    [1] 76

This time, more rows were included, but 14 rows are still missing. These rows are from uncensored data (`"none"`). I updated the `y2` column again, this time using the `y` values for the uncensored data; which again feels intuitively odd.

    regex_data$y2 <- ifelse(regex_data$censored == "none", regex_data$y, regex_data$y2)
    regex.brm3 <- brm(bf(y | cens(censored, y2) ~ 1, family = lognormal), data = regex_data)
    nrow(regex.brm3$data)
    [1] 100

Finally! All the data was used during model fitting, which is reassuring. However, this leaves me with two questions:

* **Am I doing the right thing with my `y2` specifications for `"left"`- and `"none"`-censored data?**
* **Is `brms` actually doing what I *think* it is doing, i.e., is treating all three cases of censoring correctly?**

Thanks in advance, and in general thanks for the awesome package!

p.s.: for full disclosure, my data also contains missing `y` values I'd very much like to impute using `mi()`, which also throws off the behavior of `cens()`, as the `y2` data in these cases is also missing (`y | cens(censored, y2) + mi()`). But that's a challenge for another time ;)

**Comment by paul-buerkner** [comment]
For technical reasony, y2 needs to be specified for *all* observations even if they are unused, for left and none, for instance. In the future brms will be better at selectively checking whether variables are actually used in a specific case but this is hard. So for now: Any variable that you use in your data should be non NA for all observation you want to include, even if some of the values are actually unused in the model.

In the future please ask brms related questions on https://discourse.mc-stan.org for greater visibility by the community.
