### ISSUE TITLE
Predict multilevel models with interaction between two levels fails

### ISSUE THREAD

**Issue by alireza202** [paul-buerkner/brms#8]
Thanks for the great work!

My model looks like this:

>brm(formula = y ~ x1 + x2 + x3 + 
>                         (1 | cat:subcat) +
>                         (x1 + x2 + x3 || cat), 
>    data = df,
>    family = "gaussian",
>    n.chains = 4,
>    n.cluster = 4,
>    cluster_type = "FORK") -> model1

It runs fine, but when I try to predict it using:

> new_pred = predict(object = model1, newdata = newData, probs = c(0.005, 0.995))

It give an error:

> Error in get(gnames[i], newdata): object 'cat:subcat' not found.

I tried creating a column "cat:subcat", but it gives another error:

> Error in amend_newdata(newdata, fit = object, re_formula = re_formula, : levels 813, 1346, 1397, 2517, 2003, 1439, 1373, 1329, 2322, 2247, 919, 2320, 1451, 1146, 2578, ..., 2679 of grouping factor 1346 not found in the fitted model.

What's the solution?

Also, it seems like we can't use "1 | cat/subcat" to denote the hierarchy. Is "1 | cat:subcat" gonna do the same thing?

**Comment by alireza202** [comment]
I tried concatenating cat and subcat using sep="_", and named the column "cat:subcat", and I got this error:

> Error in expand_matrix(Z, gf): x must contain positive integers only

**Comment by paul-buerkner** [comment]
Thanks for reporting this! It definitely looks like a bug and I will try to fix it in the next few days.

(1 | cat / subcat) will be expandend to (1 | cat) + (1 | cat:subcat) by lme4 and you can specify the second formula in brms. I just didnt have the time to implement the short form with /.

**Comment by paul-buerkner** [comment]
I just pushed a commit to github that should fix this issue. Please tell me if it also works for your model.

**Comment by alireza202** [comment]
Thanks! That solved the problem! But I get a warning message:

> In amend_newdata(newdata, fit = object, re_formula = re_formula, : Validity of factors cannot be checked for fitted model objects created with brms <= 0.5.0

Also when I try "(1 | cat) + (1 | cat:subcat)", I got an error:

> Error in get_prior(formula = formula, data = data, family = family(family, : Duplicated random effects detected for group cat

**Comment by paul-buerkner** [comment]
Great! You can safely ignore the warning. It just means that you have to make sure that factors in your newdata have exactly the same levels as in the original data. To get rid of this warning, refit your model with the brms version from github, as factor levels can be automatically checked in this case.

When I look at your original model, I see the random effect (x1 + x2 + x3 || cat), which is the same as
(1 + x1 + x2 + x3 || cat). That is, you already have the (1 | cat) effect in your model and brms complains when you try to specify the same random effect twice.

**Comment by alireza202** [comment]
Awesome, thanks!
