### ISSUE TITLE
Strange result with Categorical?

### ISSUE THREAD

**Issue by wfolta** [paul-buerkner/brms#80]
I was dusting off a simple illustration of categorical regression on `brms`, and am getting an odd result:

```
library (brms)
ir <- data.frame (scale (iris[, -5]), Species=iris[, 5])

system.time (b2 <- brm (Species ~ Petal.Length + Petal.Width + Sepal.Length + Sepal.Width, data=ir,
                       family="categorical", chains=3, iter=3000, warmup=600,
                       prior=c(set_prior ("normal (0, 8)"))))
```

This actually runs a bit faster than it did back in the day. But when I predict (in sample), the last 100 points (the last two categories) all split the vote 50/50 between the last two categories, which I believe means it can't differentiate the last two categories.

I have to admit that I'm not sure if I looked at the prediction back then. (The code was a part of a larger presentation and I only plotted the trace, not the prediction.) Maybe the predictions were the same as now. But maybe there's been a change that I didn't track and now my `brm` call is wrong -- I remember a change in non-linear regression -- or maybe it's an issue?

**Comment by paul-buerkner** [comment]
In brms 0.9.0, I changed the implementation of categorical models to be more flexible (but a bit slower with respect to sampling speed). See my latest comment on your blog post: https://thinkinator.com/2016/01/12/r-users-will-now-inevitably-become-bayesians/.

**Comment by wfolta** [comment]
Ah, I was misremembering then. I thought that was non-linear. Sorry!

**Comment by paul-buerkner** [comment]
No problem. Would you mind amending you blog post to use the new syntax? Otherwise people may wonder what's happening if they try out your code.

**Comment by wfolta** [comment]
I changed it in one place right after your post, but didn't do it everywhere. I'll be more careful to catch all of them... (And I assume this is related to my last post, so in the future we'll get a "This will produce pooled results, which is probably not what you want. Consider using `trait`.)

**Comment by paul-buerkner** [comment]
Absolutely, I already implemented such a warning in the dev version of brms.

**Comment by paul-buerkner** [comment]
@wfolta Are you ok if I close this issue?

**Comment by wfolta** [comment]
I'll take care of it, thanks!
