### ISSUE TITLE
Specify dispersion parameter as observation-level random intercept

### ISSUE THREAD

**Issue by StaffanBetner** [paul-buerkner/brms#801]
It might be useful to model the scale parameter (for distribution families with such parameters) as an observation-level random effect (OLRE) as a way to enable "residual" correlation between different distribution familes. (Albeit I am not sure whether this is a flawed reasoning or not).

As an example, one might want to model the correlation between the Poisson OLRE and the standard deviation of a gaussian model, like this:
bf(poisson_mean ~ 1 + x + (1|c|obs))+poisson()+
bf(gaussian_mean ~ 1 + x + (1|c|obs))+gaussian()

One workaround today is to fix the gaussian sigma to 1 (adding sigma ~ 1). I suppose that this is a valid approach since the correlation is independent of the size of the standard deviations of both random intercepts. 

My suggestion is to add some kind of special response term for the sigma to note that the correlation between that parameter and the random intercept for the Poisson model should be modeled, something like this:
bf(poisson_mean ~ 1 + x + (1|c|obs))+poisson()+
bf(gaussian_mean ~ 1 + x, sigma|cor(c)~1)+gaussian()

I suppose that would be possible to extend to correlation of other response terms as well.

**Comment by paul-buerkner** [comment]
This is a reasonable request. I am not sure yet how to implement this in a consistent way though or how to design the user interface. I will need some more time to think of this feature.

**Comment by paul-buerkner** [comment]
I am not sure if the proposed syntax would be any simpler than the currently possible approach, which is basically what you wrote above, just with a minor fix (`sigma = 1` not `sigma ~ 1`):

```
form1 <- bf(y1 ~ 1 + x + (1|c|obs), sigma = 1) + gaussian()
form2 <- bf(y2 ~ 1 + x + (1|c|obs)) + poisson()
```

I have added this example to the doc of `brmsformula`.

Adding a special syntax to it would be a lot of work without any benefit to my understanding.
Specifically, how do we ensure explicit residuals (in the poisson case) being correlated with implicit residuals (in the Gaussian) case, if not by making the residuals in the Gaussian case explicit with the above syntax? 

I will close this issue for now, but if anyone has suggestions for how to handle this case, please feel free to post it here (and I may reopen this issue if there a viable solution comes up).
