### ISSUE TITLE
Model sum of independent random variables

### ISSUE THREAD

**Issue by j-baldock** [paul-buerkner/brms#802]
I am relatively new to brms so I apologize if this is not the appropriate posting location.

I am attempting to model an observed count of fish in a stream (R) as the sum of two independent, discrete random variables: the number of actual fish detected (A) plus the the number of false identifications (F). 

R = A + F

The simplest assumption regarding the detection of an actual fish is that each fish has an independent and equal chance of being detected; this implies that observed actual fish will be binomially distributed. 

A ~ Binomial( T, p )
Where: T = the total number of actual fish, p = detection probability

The simplest assumption for false identifications is that each increment of stream length has an equal and independent probability of holding a false identification; which implies that false identifications should have a Poisson distribution
 
F ~ Poisson( lambda * d )
Where: d = stream distance surveyed
------------------------------------------
Predictor data: T, d
Estimated parameters: p, lambda

My understanding is that in order to model R, I need to multiply the likelihoods of A and F (or sum in the case of log-likelihoods). Others have suggested using implementing a mixture model (using function mixture() ), but I cannot find examples that use distributions other than gaussian. My other thought would be to use the customfamily() function, but I'm not sure how to incorporate two existing distributions. 

Any insight you can provide on how to implement this type of model in brms would be greatly appreciated. Thanks

**Comment by paul-buerkner** [comment]
Hi, please ask brms-related questions on https://discourse.mc-stan.org/ using the interfaces - brms tag.
