### ISSUE TITLE
brm( ) without a `data=` argument

### ISSUE THREAD

**Issue by petrelharp** [paul-buerkner/brms#804]
Currently, running `brm( )` without a `data=` argument produces a rather inscrutible error. Both of these calls to `brm( )`:
```
a <- rnorm(10)
b <- rnorm(10)
brm(b ~ a, family=gaussian)
xy <- data.frame(x=a, y=b)
brm(xy$y ~ xy$x, family=gaussian)
```
results in
```
Error in deparse(out) : argument "out" is missing, with no default
```

However, this works:
```
brm(y ~ x, data=xy, family=gaussian)
```

It would be nice if one didn't need to pass in `data=`, but at least a better error message should be provided.

**Comment by petrelharp** [comment]
I am not very familiar with these aspects of R, but in simple tests, inserting
```
    if (missing(data)) {
        data <- stats::model.frame(formula, environment())
    }
```
into the `brm( )` function right [here](https://github.com/paul-buerkner/brms/blob/master/R/brm.R#L377) works.  (note: I think that the call to `environment()` is not the right way to do this, but something similar might be...)

**Comment by paul-buerkner** [comment]
Brms used to allow data to be missing but this created all sorts of
problematic edge cases that I wanted to get rid off. I will see if I can
improve the error message though.

Peter Ralph <notifications@github.com> schrieb am Mi., 11. Dez. 2019, 01:53:

**Comment by petrelharp** [comment]
Perhaps
```
if (missing(data)) {
   stop("Data must be passed in as a data frame, using the 'data' argument.")
}
```

**Comment by paul-buerkner** [comment]
Thanks should be fixed now. Both error messages (with respect to data missing and missing some variables) were alredy present, but the data was evaluated once before that checks were called leading to the weird error message.

**Comment by petrelharp** [comment]
That was quick! Thanks!
