### ISSUE TITLE
Probabilities as kfold output in ordinal models

### ISSUE THREAD

**Issue by giulianonetto** [paul-buerkner/brms#807]
Hi Paul! 

First of all, thank you so much for such an awesome package! The work you and all the Stan dev team do is definitely inspiring!

I do have a small suggestion, which is something I am currently struggling with and could not find any obvious solution to. When running k-fold cross-validation, it would be really nice to get back the class probabilities (rather than the entire draws? I am not sure I totally understand the output and how to handle it). That is because that's an easy place to start with ordinal models if I want to validate several aspects of the predictions  (e.g. assess predicted P(Y > k), P(Y <= k), P(Y = k) itself, or even derived expected values for outcomes with "continuous interpretation" - e.g. fig 14 in [this paper](https://onlinelibrary.wiley.com/doi/abs/10.1002/sim.7433)).

Once again, thank you for your work and patience with all of us learners!

Best wishes

Giuliano

**Comment by paul-buerkner** [comment]
You can use `fitted` for that purpose rather than predict, or use `predict(summary = TRUE)`. In the future, please ask brms related questions on https://discourse.mc-stan.org as github issues are reserved for feature requests and bug reports.
