### ISSUE TITLE
plot(hypothesis(...)) repeats plots when labels are long

### ISSUE THREAD

**Issue by andymilne** [paul-buerkner/brms#809]
If you do a hypothesis test where the first 36 or so characters of two of the hypotheses are identical (such as might happen when testing interactions), then use print(hypothesis(...)) everything works as expected. However, running plot(hypothesis(...)), only one of the two hypotheses gets plotted and it is plotted twice.

For example, in the following hypothesis test

```
h <- c(
       "a_rather_long_but_reasonable_variable_01 > 0",
       "a_rather_long_but_reasonable_variable_01:a_factor_I_happen_to_interested_in + 
       a_rather_long_but_reasonable_variable_01 > 0")
```

`plot(hypothesis(my_model, h))`

plots only the first hypothesis twice.

**Comment by paul-buerkner** [comment]
The plot method has as "chars" argument to control the number of displayed characters. This should solve your problem.

**Comment by andymilne** [comment]
Confirmed that works! Thank you.
