### ISSUE TITLE
prior nested in another prior

### ISSUE THREAD

**Issue by zhengjiji456** [paul-buerkner/brms#814]
# mydata
tree <- gl(3,100)
d0<-rnorm(300,5,1)
t<-5
dt<-d0^(1/3)*rnorm(300,0.5,0.1)*t+d0
mydat<-data.frame(tree,d0,dt)

fit_mydat <- brm(
  bf(dt ~ (beta * (1 - alpha) * 5 + d0^(1-alpha))^(1/(1-alpha)),
     beta ~ 1, alpha ~ 1, 
     nl = TRUE),
  data = mydat, family = gaussian(),
  prior = c(
    prior(lognormal(0.5, 0.05), nlpar = "beta"),
    prior(normal(0.3, 0.01), nlpar = "alpha")
  ),
  control = list(adapt_delta = 0.95)
)

# In my case, the nlpar alpha belongs to a normal (0.3, 0.01) distribution, I want to replace the sd (i.e. 0.01) with randomed samples from a different distribution, such as normal (0.01, 0.005). Is it possible to do this in brms?

Thanks and Merry Christmas

**Comment by paul-buerkner** [comment]
Questions should rather be asked on https://discourse.mc-stan.org/ while github issues are reserved for bug reports and feature requests.

And merry christmas to you too!
