### ISSUE TITLE
Problem with reloo with a BYM2 model

### ISSUE THREAD

**Issue by jdselwyn** [paul-buerkner/brms#816]
When adding loo to a model with a bym2 correlation structure if `reloo = FALSE` the output is normal and what is expected. However if `reloo = TRUE` the model is refit the right number of times but after the following error is produced and nothing is saved to the model file or stored in the model variable. The same error happens with kfold either with random groups or using it as leave-group-out cv.

>  Error: Cannot handle new locations in CAR models.

Is this the expected behaviour? Below is some code to hopefully reproduce the error.
Thanks!

```
# Create data - copied from cor_car documentation
set.seed(1234)
east <- north <- 1:10
Grid <- expand.grid(east, north)
K <- nrow(Grid)

distance <- as.matrix(dist(Grid))
W <- array(0, c(K, K))
W[distance == 1] <- 1 	

x1 <- rnorm(K)
x2 <- rnorm(K)
theta <- rnorm(K, sd = 0.05)
phi <- rmulti_normal(
  1, mu = rep(0, K), Sigma = 0.4 * exp(-0.1 * distance)
)
eta <- x1 + x2 + phi
prob <- exp(eta) / (1 + exp(eta))
size <- rep(50, K)
y <- rbinom(n = K, size = size, prob = prob)
dat <- data.frame(y, size, x1, x2)

dat$space_struct <- as.factor(1:nrow(dat))
rownames(W) <- dat$space_struct

# fit a CAR model
fit <- brm(y | trials(size) ~ x1 + x2, 
           data = dat, 
           family = binomial(), 
           cores = 4,
           autocor = cor_car(W, formula = ~ 1 | space_struct, type = 'bym2'),
           seed = 1234) 
fit2 <- add_criterion(fit, criterion = "loo", reloo = FALSE) #Works
fit3 <- add_criterion(fit, criterion = "loo", reloo = TRUE) #Error
fit4 <- add_criterion(fit, criterion = "kfold", K = 5) #Error
```

**Comment by paul-buerkner** [comment]
This is expected behavior. When you hold out some parts of the data via exact loo or kfold, some locations may end up only being in the test but not in the training data. As a result, we have no estimate for their corresponding parameter and cannot use that one for predictions. There may be some equations in the literature to compute estimates of new locations based on W and the existing locations in closed form but I am not enough of an expert in CAR models. @mitzimorris may know more about this.

**Comment by mitzimorris** [comment]
Paul is entirely correct.  in a BYM model, the ICAR prior describes a known spatial structure which comes in as fixed data - it's not a generative model, and therefore not amenable to cross-validation via loo or k-fold testing.

**Comment by jdselwyn** [comment]
Thank you both for these answers. Is it right to assume this also applies when the spatial structure is multiple disconnected subgraphs and leave-group-out where the groups is an entire disconnected subgraph? Thank you again.

**Comment by paul-buerkner** [comment]
Thank you @mitzimorris! I am closing this issue now.
