### ISSUE TITLE
multivariate autoregressive model with non-guassian/student family possible? 

### ISSUE THREAD

**Issue by mabarbour** [paul-buerkner/brms#817]
Is it possible to fit this type of model in brms? Below is a reproducible example:

Test data:
`test_df <- cbind.data.frame(Cage = rep(1:20, each = 5),
                            Week_match = rep(0:4, 20),
                            BRBR_t1 = rpois(n = 100, lambda = 100), 
                            LYER_t1 = rpois(n = 100, lambda = 100), 
                            Ptoid_t1 = rpois(n = 100, lambda = 100),
                            BRBR_t = rpois(n = 100, lambda = 100), 
                            LYER_t = rpois(n = 100, lambda = 100), 
                            Ptoid_t = rpois(n = 100, lambda = 100))`

This works fine:
`brm(mvbind(BRBR_t1, LYER_t1, Ptoid_t1) ~ log(BRBR_t) + log(LYER_t) + log(Ptoid_t),
    data = test_df,
    autocor = cor_ar(formula = ~I(1 + Week_match) | Cage, p = 1, cov = FALSE))`

I see that I cannot model the residual covariance matrices via 'autocor' when estimating 'rescor'
`brm(mvbind(BRBR_t1, LYER_t1, Ptoid_t1) ~ log(BRBR_t) + log(LYER_t) + log(Ptoid_t),
    data = test_df,
    autocor = cor_ar(formula = ~I(1 + Week_match) | Cage, p = 1, cov = TRUE))`

If I try this, I get a syntax error:
`brm(mvbind(BRBR_t1, LYER_t1, Ptoid_t1) ~ log(BRBR_t) + log(LYER_t) + log(Ptoid_t),
    data = test_df,
    family = poisson,
    autocor = cor_ar(formula = ~I(1 + Week_match) | Cage, p = 1, cov = TRUE))`

Do you have any suggestions?

**Comment by paul-buerkner** [comment]
The last model works for me in the latest github version of brms.
