### ISSUE TITLE
[FR] Do posterior predict in parallel?

### ISSUE THREAD

**Issue by SteveBronder** [paul-buerkner/brms#819]
Looking at posterior predict is most of the time spent in the lapply [here](https://github.com/paul-buerkner/brms/blob/d34c3d3a36005fddabfb6b8c991e6127e4eeacba/R/posterior_predict.R#L131)?

```R
out <- lapply(seq_len(N), pp_fun, draws = object, ...)
```

could we just use mclapply there if `getOption("mc.cores", 2L)` is > 1?

**Comment by paul-buerkner** [comment]
That is a good idea. Although, we need an extended wrapper that also covers windows machines which do not support mclapply natively.

**Comment by VLucet** [comment]
This would be especially helpful for me, I am struggling to predict over large datasets (over 1 million rows). I have tried to fork and experiment with the following code replacing the call to `lapply`:
```r
if (getOption("mc.cores", 2L) > 2){
    print("Testing parallel::mclapply")
    print(paste0("Number of cores: ", getOption("mc.cores")))
    out <- parallel::mclapply(seq_len(N), pp_fun, draws = object, ...)
    } else {
    out <- lapply(seq_len(N), pp_fun, draws = object, ...)
  }
```
I am not seeing any improvement, I must be misunderstanding something. Would be happy to contribute a pull request but might need a few pointers here.

**Comment by paul-buerkner** [comment]
Thanks for checking it out! Can you (or someone else) profile a parallel code version to see where the bottlenecks are? 

I assume it is not only the `lapply` call but also the call to `get_dpar` earlier, in which the linear predictor matrix (S x N) is computed.

**Comment by vkehayas** [comment]
As a side-note, [future.apply](https://github.com/HenrikBengtsson/future.apply) is a cross-platform parallel engine.

**Comment by paul-buerkner** [comment]
Thank you! Yes, I was thinking of using future.apply for this purpose since I make use of future in other places anyway. I am not sure how well this plays with the idea of using the global mc.cores option though. Have to check it out.

**Comment by paul-buerkner** [comment]
This feature is now implemented in the github version of brms
