### ISSUE TITLE
[Perf] Use Raw indexing instead of head for cor_arma

### ISSUE THREAD

**Issue by SteveBronder** [paul-buerkner/brms#822]
I'm using a [`heaptrack`](https://github.com/KDE/heaptrack) right now to look at how much memory a brms model I have is allocating. I can email you the results of the run, but one thing was that `head()` actually makes a copy. For cor_arma. Looking at the function in math for `head()` it just does `x.head(n)`. Does regular old multi indexing 1:Kma goof something here? That seems to get rid of a few copies

```stan
  // include ARMA terms
  for (n in 1:N) {
    mu[n] += Err[n, 1:Kma] * ma;
    err[n] = Y[n] - mu[n];
    for (i in 1:J_lag[n]) {
      Err[n + 1, i] = err[n + 1 - i];
    }
    mu[n] += Err[n, 1:Kar] * ar;
  }
```

**Comment by paul-buerkner** [comment]
Thank you! I don't see why I used `head` in the first place and will change it accordingly.

**Comment by paul-buerkner** [comment]
Should be fixed now. If there is anything else that makes sense to change, please let me know! I highly appreciate your input!

**Comment by SteveBronder** [comment]
Ty my man I appreciate the package!
