### ISSUE TITLE
Using brms for parameter estimation of a multinomial-dirichlet process

### ISSUE THREAD

**Issue by nerafiee** [paul-buerkner/brms#831]
Dear All,
I am doing bayesian inference on a series of categorical data and I want to estimate parameters of a multinomial distribution using Dirichlet prior. I see that in the brmsfamily:multinomial(), inside the parenthesis, I have to define a link function. However, I am not doing a modeling and so I do not have any link function!
 I would like to know if still I can use brms for my purpose ?
Thanks in advance.
Neda

**Comment by paul-buerkner** [comment]
I am afraid, brms is not designed for that model. In the future, please ask brms specific questions on https://discourse.mc-stan.org
