### ISSUE TITLE
Flip traversal in arma?

### ISSUE THREAD

**Issue by SteveBronder** [paul-buerkner/brms#833]
Right now the arma code looks like

```stan
  matrix[N, max_lag] Err = rep_matrix(0, N, max_lag);
  for (n in 1:N) {
    mu[n] += Err[n, 1:Kma] * ma;
    err[n] = Y[n] - mu[n];
    for (i in 1:J_lag[n]) {
      Err[n + 1, i] = err[n + 1 - i];
    }
    mu[n] += Err[n, 1:Kar] * ar;
  }
```

so while the outer loop is over N, within the loop it looks like we traverse `Err` like (assuming `Kma` and `Kar` are 4

Edit: I also have 4 rows which looked dumb so added one

| row/col |    |    |    |    |
|---------|----|----|----|----|
|         | 1  | 2  | 3  | 4  |
|         | 5  | 6  | 7  | 8  |
|         | 9  | 10 | 11 | 12 |
|         | 13 | 14 | 15 | 16 |
|         | 17 | 18 | 19 | 20 |

I know it looks weird but if `Err` was flipped I think it would give a better access pattern since we do column major order

| row/col |   |   |    |    |
|---------|---|---|----|----|
|         | 1 | 6 | 11  | 16 |
|         | 2 | 7 | 12 | 17 |
|         | 3 | 8 | 13 | 18 |
|         | 4 | 9 | 14 | 19 |
|         | 5 | 10 | 15 | 20 |

I think these dot products make sense?

```stan
  matrix[max_lag, N] Err = rep_matrix(0, max_lag, N);
  for (n in 1:N) {
    mu[n] += dot_product(Err[1:Kma, n], ma) ;
    err[n] = Y[n] - mu[n];
    for (i in 1:J_lag[n]) {
      Err[i, n + 1] = err[n + 1 - i];
    }
    mu[n] += dot_product(Err[1:Kar, n], ar);
  }
```

**Comment by paul-buerkner** [comment]
In a quick evaluation of it, the `dot_product` version seems to be slower (by a factor of 2 roughly) for an arma(2, 2) process with 1000 observations. Any idea of why that could be the case?

**Comment by paul-buerkner** [comment]
Ok, I realize some chains did not converge. I will run some more extensive tests.

**Comment by paul-buerkner** [comment]
Ok, wenn I run the old and the proposed version on

```R
library(brms)

set.seed(1234)
y <- arima.sim(list(ar = c(0.7, -0.2), ma = c(-0.3, 0.5)), 1000)
fit <- brm(y ~ arma(p = 2, q = 2), data = list(y = y),
           inits = 0)
```

I get 13-14 seconds per chain with the old version and 15-16 seconds with the newly proposed version with very similiar effective sample size. So the new version seems to be a little slower for the investigated condition.

**Comment by SteveBronder** [comment]
Hmm this is interesting I'm going to close this for now and run some checks on the lower level code. I think there might be a weird interaction with the `rvalue` function in `Stan` and the dot product making a copy. Thanks for checking it out!

**Comment by paul-buerkner** [comment]
Thank you for looking at the details on this!

Steve Bronder <notifications@github.com> schrieb am Sa., 18. Jan. 2020,
19:59:
