### ISSUE TITLE
fitted.brmsfit now fails for the second response in a multivariate model

### ISSUE THREAD

**Issue by mdahirel** [paul-buerkner/brms#834]
Hi,

(Config: Windows 10, `R` 3.6.2, `rstan` 2.19.2, `brms` 2.11.0)

I've recently updated `brms` to the most recent CRAN version, and noticed it causes a problem that didn't exist before. When you have a multivariate model and you use `fitted.brmsfit` to get predictions while specifiying a `re_formula` argument, you can only get back predictions for the "first" response, and you now get an error for the second one (and presumably the third, fourth...).

Here is an example using the blue tit dataset:

``` r
data("BTdata", package = "MCMCglmm")
bf1 <- bf(back~(1|1|fosternest))
bf2 <- bf(tarsus~(1|1|fosternest))
mod <- brm(mvbf(bf1 + bf2),data=BTdata,iter=100,chains=2)
fitted(mod,re_formula=~(1|fosternest),resp="back")
fitted(mod,re_formula=~(1|fosternest),resp="tarsus")
```
The `fitted()` call for tarsus results in the following error:

```
Error in (function (A, x, max_level = max(x), weights = 1)  : 
  length(x) == nrow(A) is not TRUE
```
Inverting bf1 and bf2 in mvbf() makes `fitted()` fail for back instead of tarsus; the error only appears if a re_formula argument is given.

Anyway, thanks again for your great work on this package!

Maxime

**Comment by paul-buerkner** [comment]
Thanks! I apparently introduced this when fixing another bug in the same place. Sorry for that. Should be working again now.

**Comment by mdahirel** [comment]
Hi again,

sorry to re-open the issue, but it looks like the fix is not having the intended effect, but instead does something that looks like copying the first response prediction when calling for the second one. See (with original example):

```r
plot(
fitted(mod,re_formula=~(1|fosternest),resp="back")[,1], 
fitted(mod,re_formula=~(1|fosternest),resp="tarsus")[,1]
)
```
Gives a near-perfect 1 correlation, when it's clear from the model summary that the actual correlation should be much weaker.

**Comment by paul-buerkner** [comment]
You are right. I will take a look again.

**Comment by paul-buerkner** [comment]
Ok, next try. Can you check if it works correctly now?

**Comment by mdahirel** [comment]
Perfect,  that's fixed now, thanks very much!
