### ISSUE TITLE
Slight error in conditional effects plot when trials is a sum

### ISSUE THREAD

**Issue by StaffanBetner** [paul-buerkner/brms#839]
The default behavior of conditional_effects is that trials are set to 1 if the regression family is binomial, however, when the trials consists of sum of two variables it sets both variables to 1 yielding 2 as the maximum which messes up the scale.

Fairly simple to reproduce:

```{r}
library(brms)
ucb.df <- data.frame(gender=rep(c("Male","Female"),c(6,6)),
                    dept=rep(LETTERS[1:6],2),
                    yes=c(512,353,120,138,53,22,89,17,202,131,94,24),
                    no=c(313,207,205,279,138,351,19,8,391,244,299,317))

brm(formula=yes|trials(yes+no)~gender*dept, family = binomial, data=ucb.df) -> fit

conditional_effects(fit)
```

![image](https://user-images.githubusercontent.com/8129424/73137880-0b10ad80-405d-11ea-8fb0-ab974dfae449.png)

**Comment by paul-buerkner** [comment]
This is a good point but I unfortunately don't know how to fix it without considerable effort. I recommend manually setting `yes` and `no` via the `conditions` argument so that the y-scale is as desired for you.

**Comment by paul-buerkner** [comment]
I have now changed the message to more accurately reflect what happens internally.
