### ISSUE TITLE
posterior_linpred(transform = TRUE) => pp_expect(?)

### ISSUE THREAD

**Issue by strengejacke** [paul-buerkner/brms#841]
Hi Paul,
`posterior_linpred()` is now deprecated and in fact an alias of `pp_expect()`, where `scale = "linear"`. So, `pp_expect()` uses `transform = FALSE` by default - can this be changed? Is there an equivalent to `posterior_linpred(transform = TRUE)`?

**Comment by paul-buerkner** [comment]
I am confused. `pp_expect` does not even have a `transform` parameter and always returns the mean of the posterior predictive distribution, which is exactly what you want from `posterior_linpred(transform = TRUE)`.

**Comment by strengejacke** [comment]
Ok, than maybe I confused something?

The docs from `?posterior_linpred` state that "transform = FALSE" by default, and that "If FALSE, scale is set to "linear"". So I thought that when `posterior_linpred(transform = TRUE)`, it does _not_ equal `pp_expect()`.

**Comment by strengejacke** [comment]
I just checked, and indeed it seems that `pp_expect()` equals `posterior_linpred()´ with `transform = TRUE`:

``` r
library(brms)
#> Loading required package: Rcpp
#> Loading 'brms' package (version 2.11.1). Useful instructions
#> can be found by typing help('brms'). A more detailed introduction
#> to the package is available through vignette('brms_overview').
m <- insight::download_model("brms_ordinal_1")

p1 <- posterior_linpred(m, transform = TRUE)
#> Warning: posterior_linpred(transform = TRUE) is deprecated.Please use
#> pp_expect() instead.
p2 <- pp_expect(m)
head(p1)
#> [1] 0.1175683 0.2837131 0.2680512 0.3718487 0.3612892 0.1307886
head(p2)
#> [1] 0.1175683 0.2837131 0.2680512 0.3718487 0.3612892 0.1307886
all.equal(p1, p2)
#> [1] TRUE


p1 <- posterior_linpred(m, transform = FALSE)
p2 <- pp_expect(m)
head(p1)
#>           [,1]      [,2]      [,3]      [,4]      [,5]      [,6]      [,7]
#> [1,] -41.08320 -41.08320 -44.60461 -41.86573 -36.58361 -35.40980 -27.97570
#> [2,] -51.64349 -51.64349 -56.07008 -52.62718 -45.98730 -44.51177 -35.16676
#> [3,] -58.49788 -58.49788 -63.51198 -59.61213 -52.09097 -50.41960 -39.83427
#> [4,] -53.13365 -53.13365 -57.68797 -54.14572 -47.31425 -45.79615 -36.18149
#> [5,] -53.33389 -53.33389 -57.90536 -54.34977 -47.49256 -45.96873 -36.31784
#> [6,] -56.01185 -56.01185 -60.81287 -57.07875 -49.87722 -48.27688 -38.14140
#>           [,8]      [,9]     [,10]     [,11]     [,12]     [,13]     [,14]
#> [1,] -47.73476 -44.60461 -37.56178 -34.82290 -32.08402 -33.84473 -29.73641
#> [2,] -60.00482 -56.07008 -47.21691 -43.77401 -40.33111 -42.54440 -37.38005
#> [3,] -67.96897 -63.51198 -53.48378 -49.58392 -45.68406 -48.19111 -42.34132
#> [4,] -61.73624 -57.68797 -48.57934 -45.03710 -41.49485 -43.77201 -38.45864
#> [5,] -61.96890 -57.90536 -48.76241 -45.20682 -41.65123 -43.93696 -38.60357
#> [6,] -65.08044 -60.81287 -51.21084 -47.47671 -43.74259 -46.14310 -40.54191
#>          [,15]     [,16]     [,17]     [,18]     [,19]     [,20]     [,21]
#> [1,] -20.34596 -20.34596 -28.75824 -63.38550 -59.47282 -66.32002 -42.06137
#> [2,] -25.57582 -25.57582 -36.15044 -79.67853 -74.76010 -83.36735 -52.87310
#> [3,] -28.97038 -28.97038 -40.94852 -90.25387 -84.68265 -94.43229 -59.89069
#> [4,] -26.31381 -26.31381 -37.19356 -81.97764 -76.91729 -85.77290 -54.39874
#> [5,] -26.41297 -26.41297 -37.33372 -82.28657 -77.20715 -86.09613 -54.60374
#> [6,] -27.73920 -27.73920 -39.20830 -86.41829 -81.08383 -90.41913 -57.34547
#>          [,22]     [,23]     [,24]     [,25]     [,26]     [,27]     [,28]
#> [1,] -30.32331 -29.73641 -26.01936 -37.56178 -53.40816 -50.86491 -59.47282
#> [2,] -38.11782 -37.38005 -32.70754 -47.21691 -67.13654 -63.93956 -74.76010
#> [3,] -43.17701 -42.34132 -37.04866 -53.48378 -76.04724 -72.42595 -84.68265
#> [4,] -39.21770 -38.45864 -33.65131 -48.57934 -69.07375 -65.78452 -76.91729
#> [5,] -39.36549 -38.60357 -33.77813 -48.76241 -69.33405 -66.03243 -77.20715
#> [6,] -41.34208 -40.54191 -35.47417 -51.21084 -72.81541 -69.34801 -81.08383
#>          [,29]     [,30]     [,31]     [,32]
#> [1,] -30.91021 -38.53995 -29.34514 -41.86573
#> [2,] -38.85558 -48.44651 -36.88821 -52.62718
#> [3,] -44.01269 -54.87658 -41.78420 -59.61213
#> [4,] -39.97675 -49.84443 -37.95261 -54.14572
#> [5,] -40.12740 -50.03226 -38.09563 -54.34977
#> [6,] -42.14225 -52.54445 -40.00847 -57.07875
head(p2)
#> [1] 0.1175683 0.2837131 0.2680512 0.3718487 0.3612892 0.1307886
all.equal(p1, p2)
#> [1] "Lengths: 128000, 384000"                                          
#> [2] "Attributes: < Length mismatch: comparison on first 1 components >"
#> [3] "Attributes: < Component \"dim\": Numeric: lengths (2, 3) differ >"
#> [4] "target is matrix, current is array"
```

<sup>Created on 2020-01-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by paul-buerkner** [comment]
Yes, these two are the same by definition of the code (see https://github.com/paul-buerkner/brms/blob/master/R/pp_expect.R).

**Comment by strengejacke** [comment]
But then the docs (for posterior_linpred) are not correct, right?

**Comment by paul-buerkner** [comment]
posterior_linpred returns the linear predictor (that is transform = FALSE). pp_expect return the mean of the posterior predictive distribution (that is, transform = TRUE if you will). Is that inconsistent with the docs? Sorry if I am missing something.

**Comment by paul-buerkner** [comment]
Just to clarify, scale = "linear" means linear predictor (that is no transformation).

**Comment by paul-buerkner** [comment]
I have updated the deprecation warning, which now says "posterior_linpred(transform = TRUE) is deprecated. Please use pp_expect() instead, without the 'transform' argument.

**Comment by strengejacke** [comment]
According to the docs from `?posterior_linpred`:

1. `transform = FALSE` is the default in `posterior_linpred()`
2. If  `transform = FALSE`, `scale` is set to `"linear"`
3. "This method _[i.e. posterior_linpred()]_ is an alias of pp_expect.brmsfit with scale = "linear".
4. Thus, I would expect the same results for `posterior_linpred(transform = FALSE)` and `pp_expect()`. Actually, `pp_expect()` is an alias for `posterior_linpred(transform = TRUE)`, but if `transform = TRUE` means `scale` is set to `"response"`, then the description in 3) is not correct...

Does this make sense, or am I missing something?

**Comment by paul-buerkner** [comment]
It makes sense now. I will fix the doc to avoid further confusion. Thank you.

**Comment by paul-buerkner** [comment]
I realize the problem was the kind of copy and paste error of relating `posterior_linpred` to `pp_expect` which was there just for historical reasons of the `fitted` method. This should now be fixed. Thank you again for helping me understand this issue.
