### ISSUE TITLE
`save_ranef = TRUE` and `add_criterion()`

### ISSUE THREAD

**Issue by torkar** [paul-buerkner/brms#842]
Hi

latest `brms` github version (today). OS X 10.15.3 updated today.

I run a simple model on the data (which worked last week):
```
m1 <- brm(n_bugs ~ 1 + (1 | language_id),
          family = negbinomial(),
          data=toplas.data,
          cores = 4,
          seed = SEED)
```
I then run `add_criterion` and now all of a sudden it bails?
```
> m1 <- add_criterion(m1, "loo", reloo = TRUE)
Error: Group-level effects of group 'language_id' not found. Please set 'save_ranef' to TRUE when fitting your model.
```

According to `?brm` I see that `save_ranef = TRUE` is default. And sure enough, adding `save_ranef = TRUE` to my call above does not change anything,`add_criterion()` still bails with the same error message. @paul-buerkner did you change something recently? Or could this somehow be connected to me upgrading to 10.15.3 today?

**Comment by paul-buerkner** [comment]
I did make changes in that regard to the github version of brms. Let me check what is going wrong.

**Comment by torkar** [comment]
Yes! That might mean that the error is in `brms` for once! ;)

**Comment by paul-buerkner** [comment]
Should be fixed now. The bug was surprisingly far away from where it showed. Glad we found it before it went into the release version.
