### ISSUE TITLE
Fitted values differ depending on order of variables in re_formula - bug?

### ISSUE THREAD

**Issue by ferberkl** [paul-buerkner/brms#844]
brms version: 2.11.1
OS: Mac

When specifying the same formula to re_formula, but with the variables in a different order, the fitted values differ. I assume this is a bug?

See reproducible example below:

```
library(brms)
library(tidyverse)

set.seed(123)
sim_data <- data.frame(y = rnorm(100),
                       x1 = sample(c("GroupA", "GroupB"), size=100, replace=T),
                       x2 = rnorm(100),
                       x3 = sample(paste0("Gene", 1:10), size=100, replace=T))

fit <- brm(y ~ 0 + x1 + x2 + (0 + x1 + x2 | x3),
           data=sim_data,
           chains = 1,
           warmup = 500,
           iter = 2000,
           seed = 123)

fittedvals1 <- sim_data %>% 
  distinct(x3, x1) %>% 
  mutate(x2 = 0) %>% 
  fitted(fit,
         newdata=.,
         re_formula = . ~ (0 + x1 + x2 | x3))

fittedvals2 <- sim_data %>% 
  distinct(x3, x1) %>% 
  mutate(x2 = 0) %>% 
  fitted(fit,
         newdata=.,
         re_formula = . ~ (0 + x2 + x1 | x3))

all.equal(fittedvals1, fittedvals2)
# [1] "Mean relative difference: 0.4210601"
```

**Comment by paul-buerkner** [comment]
Is this bug still present in the latest github version of brms?

ferberkl <notifications@github.com> schrieb am Fr., 31. Jan. 2020, 18:25:

**Comment by ferberkl** [comment]
Yes - just installed github version (2.11.5) and got the same result for all.equal

**Comment by paul-buerkner** [comment]
Thanks for testing it. I will take a look today.

**Comment by paul-buerkner** [comment]
Ok should be fixed now in the form of preventing term orders in `re_formula` that do not match the original order. In the future, this may be relaxed again to allow for arbitrary term orderings but this requires considerable refactoring and will likely not happen before brms 3.0

**Comment by ferberkl** [comment]
Thanks, Paul. I can confirm after re-installing the Github version, the line in my example `fittedvals2 <- ` returns the error: 
`Error: Order of terms in 're_formula' should match the original order.`
