### ISSUE TITLE
Predicted probability >1 using categorical fit on toy data

### ISSUE THREAD

**Issue by annahake** [paul-buerkner/brms#845]
brms.version = 2.9.0
OS = Linux

Hi Paul, 

I was trying out the categorical family on toy data to check the format of the prediction output of a categorical fit using the following code:

`df<-data.frame(y=c('A','A', 'P', 'P', 'X'), A1 = c(1,1,0,0,0), A2 = c(0,1,0,1,1))
fit<-brm(y ~ A1 + A2, data = df, family = 'categorical', chains = 2)`

I am aware that the data is crap and that this is a bad fit (not mixed chains, etc) and the posteriors are unreliable. I was still puzzled that the predicted probabilities can be larger than 1 as for the second test sample here: 
`preds <- predict(fit, newdata=data.frame(A1=c(0,1), A2 = c(1,0)))
> preds
     P(Y = A) P(Y = P) P(Y = X)
[1,]        0      0.6      0.4
[2,]       80      0.0      0.0

`

Could you explain this behaviour?
Is this a bug in the code (should there be an error instead)?

Thanks!

**Comment by paul-buerkner** [comment]
This problem is initially caused by numerical instability and resulting `NA` values due to extremly large numbers passed to `exp`. These NAs were weirdly handled in subsequent summarizing functions. This should now be fixed and a warning issued when NAs are summarized.

**Comment by annahake** [comment]
Thanks!
