### ISSUE TITLE
Expose arguments in function conditional_effects

### ISSUE THREAD

**Issue by StaffanBetner** [paul-buerkner/brms#846]
It would be good if the arguments for the conditional_effects function would be exposed. E.g. for tab completion (in RStudio) of arguments.

**Comment by paul-buerkner** [comment]
I understand. However, this drastically increases the maintainence burden as arguments and defaults needs to be stored at multiple places. I am thus afraid to say, that some arguments continue to need to be looked up in `?pp_expect` and `?validate_newdata`.
