### ISSUE TITLE
Preserve group name and variable type in hypothesis()

### ISSUE THREAD

**Issue by mvuorre** [paul-buerkner/brms#847]
Currently, when you estimate a multilevel model where the grouping factor is an R factor, `hypothesis()` returns an object where the grouping factor is always called `Group`, and its values are R characters:

```
library(rio)  # Read csv from URL
library(brms)
dat <- import(
  "http://www.intensivelongitudinal.com/ch4/ch4R.zip", 
  setclass = "tibble", 
  colClasses = c("id" = "factor", "treatment" = "factor")
)
# Subset data for this example
dat <- dat[1:100, ]
fit <- brm(
  intimacy ~ 1 + (1 | id),
  family = gaussian(),
  data = dat,
  file = "~/Downloads/intimacymodel.rds"
)
```

1. The grouping factor is called `Group` -- but it is `id` in data

```
h <- hypothesis(fit, "Intercept = 0", group = "id", scope = "coef")
h
#> Hypothesis Tests for class :
#>   Group      Hypothesis Estimate Est.Error CI.Lower CI.Upper Evid.Ratio
#> 1     1 (Intercept) = 0     3.23      0.32     2.59     3.85         NA
#> 2     2 (Intercept) = 0     2.96      0.34     2.28     3.62         NA
#> 3     3 (Intercept) = 0     3.10      0.32     2.46     3.73         NA
#> 4     4 (Intercept) = 0     3.72      0.31     3.12     4.33         NA
#> 5     5 (Intercept) = 0     3.83      0.31     3.23     4.45         NA
#> 6     6 (Intercept) = 0     4.32      0.37     3.59     5.03         NA
#> 7     7 (Intercept) = 0     3.23      0.53     2.14     4.22         NA
```

That one is pretty easy to change in source (see [my fork](https://github.com/paul-buerkner/brms/compare/master...mvuorre:master)).

2. `id` is factor in data, but character in `h`

```
str(h$hypothesis)
#> 'data.frame':    7 obs. of  9 variables:
#>  $ Group     : chr  "1" "2" "3" "4" ...
#>  $ Hypothesis: chr  "(Intercept) = 0" "(Intercept) = 0" "(Intercept) = 0" "(Intercept) = 0" ...
#>  $ Estimate  : num  3.23 2.96 3.1 3.72 3.83 ...
#>  $ Est.Error : num  0.324 0.341 0.322 0.311 0.313 ...
#>  $ CI.Lower  : num  2.59 2.28 2.46 3.12 3.23 ...
#>  $ CI.Upper  : num  3.85 3.62 3.73 4.33 4.45 ...
#>  $ Evid.Ratio: num  NA NA NA NA NA NA NA
#>  $ Post.Prob : num  NA NA NA NA NA NA NA
#>  $ Star      : chr  "*" "*" "*" "*" ...
```

This one I wasn't comfortable editing in source, but optimally `Group` would be a factor with the same levels (and ordering) than the corresponding variable in `fit$data` (or whatever is passed to `hypothesis()`, I struggled with implementing the latter.)

The current behavior may be a little confusing to beginning users. As an example, see the [processing I had to do](https://vuorre.netlify.com/post/2020/02/06/how-to-calculate-contrasts-from-a-fitted-brms-model/index.html#hierarchical-hypotheses) in order to draw a forest plot out of the results.

**Comment by paul-buerkner** [comment]
Thanks for opening this issue! I agree that `Group` should be a factor with the same levels as in `data`. I am hesitant to change the column name from `Group` to the grouping factor name, though, as the output structure should be consistent across inputs and changing the column name changes the output structure.

**Comment by paul-buerkner** [comment]
After taking a quick look, the levels and orderings are directly taken from the stored random-effects levels in `attr(fit$ranef, "levels")` and should stay that way, as they provide a reference for their ordering all over brms. However, storing `Group` as a factor in the `hypothesis` output should be no problem and I just changed it accordingly.

**Comment by mvuorre** [comment]
Brilliant, works like a charm. Two thumbs up!
