### ISSUE TITLE
Update brmsfit model with more iterations

### ISSUE THREAD

**Issue by agila5** [paul-buerkner/brms#849]
Hi! First of all thank you very much for all your work. I'm not sure this is the right place to ask this type of question but I decided to create this issue since it's more related to brms wrt stan. 

I was wondering if there was any update on this question: https://groups.google.com/forum/#!topic/brms-users/rAuBi-8-9Ws, i.e. use `update.brmsfit` function to create more samples based on an initial and existing model. I face more or less the same issues as the OP since the model I'm trying to estimate takes ages to run and it has several convergence problems.

**Comment by paul-buerkner** [comment]
Hey, brms related questions should preferably be asked at the Stan forums https://discourse.mc-stan.org/ using the Interfaces - brms tag.
