### ISSUE TITLE
auto_prior() does not work for parameter names with spaces

### ISSUE THREAD

**Issue by PCK1992** [paul-buerkner/brms#858]
I have encountered a potential bug in the `auto_prior()` function handling of categorical variables that contain spaces

For example when I use `auto_prior(data)` and the data contains a factor variable with spaces in the individual categories (e.g. `outcome 1` instead of `outcome_1`) priors are assigned but when you plug in the priors into `brm()` I get the following error: 
`The following priors do not correspond to any model parameter: 
outcome 2 ~ normal(0, 1)
outcome 3 ~ normal(0, 1)
Function 'get_prior' might be helpful to you.`

The reference category is not mentioned. When I change the coding of the variable to `outcome_2` by replacing the space everything works as expected.

I'm curious if this is expected behavior or a bug. Hope this description helps!

**Comment by paul-buerkner** [comment]
I don't know where the `auto_prior` function is coming from. It does not seem to be part of brms. Can you please provide a minimal reproducible example?

**Comment by PCK1992** [comment]
After checking, I realized that this is part of the `sjstats` package. Sorry about the confusion, I will post this in the appropriate repository!
