### ISSUE TITLE
Predict with summary=FALSE

### ISSUE THREAD

**Issue by ygechn** [paul-buerkner/brms#860]
Hi,

Thank you for your package.

I am trying to understand the predict function. I want to know how I can start from summary=FALSE to get the results the same as the result of summary=TRUE.

like: predict(mod, newdata, summary = FALSE)  --->?  predict(mod, newdata, summary = TRUE)

I find it related to the function of predict_internal which builds on extract_draws and predict_internal function. But I cannot found a function named as predict_internal in the package.

Could you help me figure out how to connect results by  summary=TRUE/FALSE?

Thank you.

**Comment by paul-buerkner** [comment]
Please ask brms related questions on https://discourse.mc-stan.org/ using the Interfaces - brms tag.
