### ISSUE TITLE
Box-Cox and Yeo-Johnson transformations

### ISSUE THREAD

**Issue by StaffanBetner** [paul-buerkner/brms#862]
It would be useful to have Box-Cox and Yeo-Johnson transformations implemented.

**Comment by paul-buerkner** [comment]
In what context and for what purpose should they be implemented?

**Comment by paul-buerkner** [comment]
I am closing this issue now to keep the tracker clean. Feel free to reopen it, if you have a specific suggestions for the purpose of their implementation in brms.
