### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by dataning** [paul-buerkner/brms#863]
Hi Paul, 

I was wondering if you had received incidents where running a simple multilevel model would crash R. In my RStudio (version 3.6.3), I run the basic example of brms (epilepsy example) and it crashed with "R abort session". I thought it's something to do with the R version so I went to RStudio.cloud and run it with version 3.6. I only installed brms and nothing else on the RStudio.cloud. However, it's still crashed and gave me the following feedback. This is the first time over 2 years I run into an incidents in brms. I am a little bit puzzled about this. Hopefully you might give me some hints on the solution. 

Best wishes

Lawrence   

**************************************************************************************************

> library(brms)
> fit1 <- brm(count ~ zAge + zBase * Trt + (1|patient), data = epilepsy, family = poisson())

Compiling the C++ model
Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! filec79223dc100.cpp:6:36: warning: ISO C++11 requires whitespace after the macro name
 #define STAN__SERVICES__COMMAND_HPP#include <boost/integer/integer_log2.hpp>
                                    ^
In file included from /home/rstudio-user/R/x86_64-pc-linux-gnu-library/3.6/BH/include/boost/smart_ptr/shared_ptr.hpp:28:0,
                 from /home/rstudio-user/R/x86_64-pc-linux-gnu-library/3.6/BH/include/boost/shared_ptr.hpp:17,
                 from /home/rstudio-user/R/x86_64-pc-linux-gnu-library/3.6/BH/include/boost/date_time/time_clock.hpp:17,
                 from /home/rstudio-user/R/x86_64-pc-linux-gnu-library/3.6/BH/include/boost/date_time/posix_time/posix_time_types.hpp:10,
                 from /home/rstudio-user/R/x86_64-pc-linux-gnu-library/3.6/rstan/include/rstan/stan_fit.hpp:13,
                 from /home/rstudio-user/R/x86_64-pc-linux-gnu-library/3.6/rstan/include/rstan/rstaninc.hpp:3,
                 f
In addition: Warning message:
In system(cmd, intern = !verbose) :
  running command '/opt/R/3.6.0/lib/R/bin/R CMD SHLIB filec79223dc100.cpp 2> filec79223dc100.cpp.err.txt' had status 1
Error in sink(type = "output") : invalid connection

**Comment by paul-buerkner** [comment]
This happens at a deeper level than brms and I recommend you check https://discourse.mc-stan.org/ for answers or post your problem there.
