### ISSUE TITLE
Error in Sink when running brm()

### ISSUE THREAD

**Issue by Bertramhojer** [paul-buerkner/brms#866]
I'm new to using brms and am getting an error when calling brm() to test the priors specified for a specific model. I have no issue defining my priors using get_prior() with a specified formula, but when I call brm() with a specified formula, data, family, prior and sample_prior = "only I get the following error-message.
Error in close.connection(zz) : cannot close 'message' sink connection

I've gone through various instructions and have made sure that my c++ compiler works so that shouldn't be the issue. How do I fix this?

best regards

**Comment by paul-buerkner** [comment]
Does restarting R help? If not can you please provide a minimal
reproducible example?

Bertramhojer <notifications@github.com> schrieb am So., 22. März 2020,
15:02:

**Comment by Bertramhojer** [comment]
I actually managed to fix the issue, turned out it was a stupid syntax-issue. When specifying the prior in brm() I had set it to prior(normal(mean = 4, sd = 1)) - which apparently isn't right. I rewrote this to say normal(4, 1) instead and now it runs with no issues. Sorry for inconvenience, and thank you for the quick response!

**Comment by abhsarma** [comment]
I actually encountered the same issue myself. I had misspecified the prior, but it took me a really long time to figure that out. Is it possible to have an error message which points to the fact that the brms is unable to create the stanmodel:

the error that I get is:

```
Error in close.connection(zz) : cannot close 'message' sink connection
Error in stanc(model_code = paste(program, collapse = "\n"), model_name = model_cppname, : c++ exception (unknown reason)
Error in close.connection(zz) : cannot close 'message' sink connection
```
