### ISSUE TITLE
Using `std_normal` in `prior` fails

### ISSUE THREAD

**Issue by bgoodri** [paul-buerkner/brms#867]
It seems like this should be legal
```
brm(count ~ zAge + zBase * Trt + (1|patient), data = epilepsy, family = poisson(),
         prior = prior(std_normal(), class = "b"))
```
but it yields

> PARSER EXPECTED: <probability function argument>
Error in stanc(model_code = paste(program, collapse = "\n"), model_name = model_cppname,  : 
  failed to parse Stan model 'file1f1226f1241d' due to the above error.
SYNTAX ERROR, MESSAGE(S) FROM PARSER:
 error in 'model1f121d423f10_file1f1226f1241d' at line 46, column 27
    44:   }
    45:   // priors including all constants
    46:   target += std_normal_lpdf(b | );
                                  ^
    47:   target += student_t_lpdf(Intercept | 3, 1, 10);
  -------------------------------------------------

So, the generation of the Stan code would need to be tweaked.

**Comment by paul-buerkner** [comment]
Thanks. I will fix that. In what version of rstan/stanHeaders was `std_normal` added. I am asking because I want to use it in brms and want to enforce the right package versions.

**Comment by bgoodri** [comment]
Can't remember, but it was probably 2.18 or so.

**Comment by paul-buerkner** [comment]
Thanks. This bug should be fixed now.
