### ISSUE TITLE
[Vignette] Inconsistent method names (conditional/marginal)

### ISSUE THREAD

**Issue by rpsychologist** [paul-buerkner/brms#868]
Just stumbled over this, but in the brms_multilevel vignette the `conditional_* `methods are sometimes referred to as `marginal_*`, e.g., page 12:

![brms-multilevel](https://user-images.githubusercontent.com/1629860/78011766-50df4000-7344-11ea-9572-0d18df7b7f19.PNG)

**Comment by paul-buerkner** [comment]
Thanks! Should be fixed.
