### ISSUE TITLE
Differing runtimes based (possibly) on processor type

### ISSUE THREAD

**Issue by justbennet** [paul-buerkner/brms#869]
We are running the same model on the same data on two machines, the newer with Skylake processor and the older with Haswell processor.  The newer machine is taking almost twice as long to produce results.  From first glance, it appears that everything is running normally, just that it takes longer.

The newer machine has R 3.6.1 built with GCC 8.2.0 on Skylake gold processor.

The older machine has R 3.6.1 built with GCC 7.2.0 on Sandybridge (but run on Haswell).

I would mostly like advice on how to track down this discrepancy, since it seems like the Skylake should produce results faster.

The layering of software here is posing a problem, so I am starting my inquiries with this issue to ask whether there is a way to get `brms` to print out what it gives to `rstan` which in turn (I think) gives to `Rcpp`?  If I need to move this from being a `brms` issue to `rstan` or even to `Rcpp`, I would like to be able to move closer to the code that each is really using.

Iinitially, though, is there a way to inject into the model compilation compiler flags that we might think would address this issue?

Alas, I am neither an R programmer nor a statistician; I am part of the group that maintains the machines.  Please forgive my fumbling with `brms`, `R`, and the statistics.

**Comment by paul-buerkner** [comment]
Hey. I cannot tell what exactly is the problem but it is definitely happening deeper than brms. I recommend you ask the question at https://discourse.mc-stan.org/
