### ISSUE TITLE
Use simpler regularize horseshoe parameterization

### ISSUE THREAD

**Issue by avehtari** [paul-buerkner/brms#873]
There are different regularized horseshoe parameterizations. Two of them with Stan code are presented in Appendix C of https://projecteuclid.org/euclid.ejs/1513306866

The current brms code is using parameterization shown in Appendix C.2. This parameterization was chosen as it seemed to be useful for non-regularized horseshoe.

Appendix C.1 has a simpler parameterization which has D+1 less parameters where D is the number of regression coefficients. This simpler parameterization is faster as the posterior dimensionality is smaller. We also now have lot of experimental experience that it works well with regularized horseshoe and thus it would be good to switch to the simpler parameterization.

Corresponding rstanarm issue stan-dev/rstanarm#427

**Comment by paul-buerkner** [comment]
Should now be changed accordingly.

**Comment by avehtari** [comment]
Did you do any performance test?

**Comment by paul-buerkner** [comment]
With the ovarian cancer data, inference is about 15% faster on average with the C.1 parameterization on my machine and shows similar convergence in terms of divergent transition behavior, Rhat and ESS.

**Comment by avehtari** [comment]
Excellent. The speed difference is likely to be bigger for bigger number of covariates as there start to be more memory cache misses.
