### ISSUE TITLE
Allowing the correlation between random effects to vary by group

### ISSUE THREAD

**Issue by StaffanBetner** [paul-buerkner/brms#875]
This is in a bit similar to #365. It would be useful to allow for separate correlations between different groups by groups. In my setting I have survey data where 20 experts have placed a set of countries on two likert scales, so I model it by something like:

```{r}
bf(scale1 ~ (1|c|country) + (1|s|survey))+bf(scale2 ~ (1|c|country) + (1|s|survey))
```

I am interested to see how the correlation between the scales differs between different countries (allowing for separate correlations by expert/survey as well would probably render the model unidentifiable I guess).

**Comment by paul-buerkner** [comment]
Can you explain in a little more detail, what mathematical model you have in mind?

**Comment by StaffanBetner** [comment]
After thinking a bit about it, the idea is probably just weird. I haven't seen any mathematical formulation of this at all, it was just an idea I had.
