### ISSUE TITLE
Rename 'pp_expect' to 'posterior_epred'

### ISSUE THREAD

**Issue by paul-buerkner** [paul-buerkner/brms#876]
I know `pp_expect` was basically just introduced to brms but we, that is, @bgoodri, @jgabry, @avehtari, and @andrewgelman have decided that a better and more consistent name would be `posterior_epred`. So this needs to be changed in brms and `pp_expect` drepecated.

**Comment by andymilne** [comment]
What does "posterior_epred" stand for -- It's not at all obvious (posterior expected prediction)?

**Comment by paul-buerkner** [comment]
Yes. It's draws from the expected value for the posterior predictive
distribution just like pp_expect is.

Andrew Milne <notifications@github.com> schrieb am Fr., 10. Apr. 2020,
01:29:
