### ISSUE TITLE
add_criterion and "loo_subsample" fails with categorical family

### ISSUE THREAD

**Issue by jackobailey** [paul-buerkner/brms#877]
Running R 3.6.3 and brms 2.12.0.

Minimal reproducible example:

    library(brms)

    test <- 
      data.frame(
        y = sample(letters[1:3], 100, replace = T),
        x = rnorm(100)
      )

    m1 <- 
      brm(
        formula = y ~ 1 + x,
        family = categorical(link = "logit", refcat = "a"),
        data = test,
        chains = 2,
        cores = 2
      )

    m1 <- add_criterion(m1, criterion = "loo_subsample")

This gives the following error:

` Error in insert_refcat(eta, family = draws$family) : 
  is.matrix(eta) is not TRUE`

**Comment by paul-buerkner** [comment]
Thank you! Should be fixed now.
