### ISSUE TITLE
Increase speed of hurdle models

### ISSUE THREAD

**Issue by joekroese** [paul-buerkner/brms#880]
First of all, a massive thank you for this project. I appreciate that developing and maintaining such a strong project and community takes a lot of time and effort. I recently started using Bayesian analysis in my projects and brms is allowing me to focus on the interesting parts - thank you!

For my issue, I am working on a gamma hurdle model with a large dataset that is taking a long time to fit. The Stan user's guide advises [speeding up hurdle models by counting non-zero entries 'ahead of time'](https://mc-stan.org/docs/2_22/stan-users-guide/zero-inflated-section.html#hurdle-models). It suggests that this can decrease execution time by around a factor of 10.

From my Stan-novice eyes, the compiled Stan code from brms hurdle models are not using this approach. Would it be possible to implement this method in brms?

**Comment by paul-buerkner** [comment]
This only works, if observations have the same likelihood contribution, which is of course the case for simple models but becomes less of a thing for complex regression models. However, you can always optimize the model yourself in that direction by using weights. See `?brmsformula` and `?resp_weights` for details.
