### ISSUE TITLE
Bug in Stan code when response is truncated AND weighted

### ISSUE THREAD

**Issue by apollostream** [paul-buerkner/brms#884]
Hi Paul,

Thank you for such a well-written and powerful tool as package `brms`. 

Unfortunately, I believe function `brm()` creates Stan code that has an error when the response variable is simultaneously truncated and weighted, as in the following:
`brm( formula = y_avg | trunc(0,100) + weights(n) + se(y_se,sigma=TRUE) ~ x, data = df_xyn )`

The resulting Stan code for the log-likelihood seems to be missing parentheses around the numerator and denominator terms capturing the truncation when multiplying by the weight, n:
`target += weights[n] * normal_lpdf(Y[n] | mu[n], ...) -
        log_diff_exp(normal_lcdf(ub[n] | mu[n], ...), normal_lcdf(lb[n] | mu[n], ...));`

Shouldn't the correct expression be the following, capturing all terms after "*" within parentheses?:
`target += weights[n] * ( normal_lpdf(Y[n] | mu[n], ...) -
        log_diff_exp(normal_lcdf(ub[n] | mu[n], ...), normal_lcdf(lb[n] | mu[n], ...)) );` 

I've checked this with the R script code I've attached as a .TXT file:
[brms_bug_tr_wt.txt](https://github.com/paul-buerkner/brms/files/4530883/brms_bug_tr_wt.txt)
 
Curiously, the inclusion of enclosing parentheses seems to have **no effect** upon the results or the mixing behavior of the HMC MCMC. Baffled.

Any suggestions on specifying/reparameterizing the simple model in that script?

Thanks again,
-Michael

**Comment by paul-buerkner** [comment]
You are right, it should be put in parentheses. I am going to fix this. I cannot tell you for sure why you don't see any differences in your example but it is probably because the truncation boundaries are not effecting the likelihood much for the given data.

**Comment by paul-buerkner** [comment]
The bug should be fixed now. Thanks again for reporting this issue!

**Comment by apollostream** [comment]
Thank you!
I think you're right about no difference in the result. It appears that for the parameters of this case, the difference of the cumulative distributions in the denominator is one and the log of that is zero, so there's no effect.
