### ISSUE TITLE
feature request: logistic growth curve with different families for each non-linear parameter

### ISSUE THREAD

**Issue by drjhw** [paul-buerkner/brms#885]
The logistic growth curve can be written:

y = Asym/(1+exp((xmid-input)/scal))

where Asym is the upper asymptote, xmid is the time taken to reach half of Asym, scal is the maximal rate of growth.

Many systems show a particular form of growth - either positive or negative (e.g. trees do not reduce their circumference). However, the presence of noise in real data can result in mathematical ambiguity. So, if the parameters all have gaussian distributions, then the model may estimate that some units are shrinking when they should be growing (very slowly). But, these apparent anomalies actually result solely from noise.

Is it possible to allow this model (and other non-linear models) to use different families for each non-linear parameter, to constrain some parameters (notably, scal) to be positive (or negative)?

Thanks
JW

**Comment by paul-buerkner** [comment]
I think are are confusing likelihood distribution ("families") with prior distributions. What you want is already possible in brms and you can find some examples in this preprint: https://arxiv.org/abs/1905.09501

As turns out to be a question not a feature request, I will close this issue.
