### ISSUE TITLE
I got this error when running the Bayesian model. Will let me know what the real issue is? I tried various suggestions in other websites with a similar problem. But the suggestions are not working. Thank you. 

### ISSUE THREAD

**Issue by karthy257** [paul-buerkner/brms#890]
library(brms); library(wooldridge); data(affairs) 
 brm(affair~educ + occup + naffairs , data = affairs, chains = 4, iter = 1000)
Compiling the C++ model
Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! In file included from <built-in>:1:
In file included from /Users/karthy/Library/R/4.0/library/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp:4:
In file included from /Users/karthy/Library/R/4.0/library/RcppEigen/include/Eigen/Dense:1:
In file included from /Users/karthy/Library/R/4.0/library/RcppEigen/include/Eigen/Core:535:
/Users/karthy/Library/R/4.0/library/RcppEigen/include/Eigen/src/Core/util/ReenableStupidWarnings.h:10:30: warning: pragma diagnostic pop could not pop, no matching push [-Wunknown-pragmas]
    #pragma clang diagnostic pop
                             ^
In file included from <built-in>:1:
In file included from /Users/karthy/Library/R/4.0/library/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp:4:
In file included from /Users/karthy/Library/R/4.0/library/RcppEigen/include/Eigen/Dense:2:
In file included from /Users/karthy/Library/R/4.0/library/RcppEigen/include/Eigen/LU:47:
/Users/karthy/Librar
In addition: Warning message:
In system(cmd, intern = !verbose) :
  running command '/Library/Frameworks/R.framework/Resources/bin/R CMD SHLIB file12c6c3678e76c.cpp 2> file12c6c3678e76c.cpp.err.txt' had status 1
Error in sink(type = "output") : invalid connection

**Comment by paul-buerkner** [comment]
I am sorry, but this is not a brms related problem and comes down to the C++ toolchain with R 4.0. So those questions should be asked at https://discourse.mc-stan.org/

**Comment by karthy257** [comment]
Thanks for the reply. I will post the question in the Stan Forum. I guess the problem is with the recent R update.
