### ISSUE TITLE
Support "cmdstanr" as additional backend

### ISSUE THREAD

**Issue by paul-buerkner** [paul-buerkner/brms#891]
Due to restrictions of CRAN, rstan moves more slowely than the development of Stan itself. For this reasons, I think it would be good to support the cmdstanr as a second backend in brms

**Comment by rok-cesnovar** [comment]
Any preference on how one would select the backend? Separate command or an argument?

**Comment by paul-buerkner** [comment]
Argument, as brms has only one primary fitting function. 

Btw. what is the best way to transform the output of cmdstanr into a stanfit object? Not that I like stanfit objects in particular but it would make so much more code reusable.

**Comment by rok-cesnovar** [comment]
Right now its using rstan's read csv function. `stanfit <- rstan::read_stan_csv(fit$output_files())` where fit is the return of $sample().

**Comment by paul-buerkner** [comment]
Ok sounds easy enough. I will see if I can work on this laer on.

**Comment by paul-buerkner** [comment]
Closed via #900
