### ISSUE TITLE
conditional_effects fails when smooth contains a by=interaction term

### ISSUE THREAD

**Issue by andymilne** [paul-buerkner/brms#894]
Six models (ignore the divergences):
```
dat <- mgcv::gamSim(4, n = 20, scale = 1)
dat$fac2 <- as.factor(rep(c(1,2), each = 10))

test_fit_1 <- brm(y ~ fac + fac2 + s(f1, by=fac) + s(f1, by=fac2), data = dat, cores = 4, iter = 400)
test_fit_2 <- brm(y ~ fac * fac2 + s(f1, by=fac) + s(f1, by=fac2) + s(f1, by=interaction(fac,fac2)), data = dat, cores = 4, iter = 400)
test_fit_3 <- brm(y ~ s(f1, by=x0) + s(f1, by=x1), data = dat, cores = 4, iter = 400)
test_fit_4 <- brm(y ~ s(f1, by=x0) + s(f1, by=x1) + s(f1, by=interaction(x0,x1)), data = dat, cores = 4, iter = 400)
test_fit_5 <- brm(y ~ fac + s(f1, by=fac) + s(f1, by=x0), data = dat, cores = 4, iter = 400)
test_fit_6 <- brm(y ~ fac + s(f1, by=fac) + s(f1, by=x0) + s(f1, by=interaction(fac,x0)), data = dat, cores = 4, iter = 400)
```
`conditional_effects` for `test_fit_4` and `test_fit_6` give `Error: New factor levels are not allowed`. These two models have a continuous term in the `interaction` argument to `s`.  Note that `test_fit_2`, which works, has an interaction term with only factors.

**Comment by paul-buerkner** [comment]
Interaction is designed to input and output factors, not continuous variables. As you can see in the summary output of these models, the by variable is indeed treated like a factor. conditional_effects and similar functions cannot handle transformations from or to factors inside the formula argument, because they can only choose and validate one of the two representations not both. If you want to compute the interaction between the continus variables, the easier thing is to store their product as a new variable and use that in `by`.

**Comment by andymilne** [comment]
Thanks -- that makes sense!

**Comment by andymilne** [comment]
But, if I do that, is there a way to "bind" together the interaction with its main effects, so both are incorporated into the values shown in the conditional_effects plot? Similar to how it is possible to "bind" polynomial terms with I(X) + I(X^2) + I(X^3)?

**Comment by paul-buerkner** [comment]
Not automatically. You have to make those plots manually in this case.

Andrew Milne <notifications@github.com> schrieb am Fr., 8. Mai 2020, 12:18:

**Comment by andymilne** [comment]
OK. Can I change this to a FR to allow for linear combinations of predictors to be entered into the effects argument of conditional_effects?

**Comment by paul-buerkner** [comment]
Unfortunatelty, this is out of scope for conditional_effects. you need to
define your own new data, pass it to posterior_epred (or friends) and
create the plot yourself from there. The tidybayes package should be very
helpful in the regard.

Andrew Milne <notifications@github.com> schrieb am Fr., 8. Mai 2020, 12:49:

**Comment by andymilne** [comment]
Thanks for the advice.
