### ISSUE TITLE
Lower bound on sum of fixed and random effect for same covariate

### ISSUE THREAD

**Issue by seanmlb** [paul-buerkner/brms#896]
I am running an autoregressive model predicting a future proportion with its three lags. I have correlated random effects grouped by individual ID. Something like this:

```
brm(current_period_logit ~ me(lag_1_logit, se_1) + me(lag_2_logit, se_2) + 
     me(lag_3_logit, se_3) +
     (1 + me(lag_1_logit, se_1) + me(lag_2_logit, se_2) + me(lag_3_logit, se_3) | IndividualID), 
                      data = test_data,
                      prior = c(set_prior("normal(0.5, 3)", class = "b"),
                                set_prior("normal(-2, 2)", class = "Intercept"),
                                set_prior("student_t(3, 0, 2)", class = "sd"),
                                set_prior("student_t(3, 0, 2)", class = "sdme")),
                      control = list(adapt_delta = 0.95),
                      iter = 3000,
                      seed = 7)
```

The fixed effects of the lags all have positive coefficients, but the random effects can lead to the lags having negative coefficients for an individual. I did a search and found this issue from 2016:

https://github.com/paul-buerkner/brms/issues/86

Is this still the best advice on this issue? Essentially, transform to ensure positivity and also use stronger priors?

Thanks for all the hard work on brms ... it's fantastic!

**Comment by paul-buerkner** [comment]
Yes, this is still the only option although the syntax of nonlinear models has changed since #86. In the future. Please ask brms related questions on https://discourse.mc-stan.org/ using the Interfaces - brms tag.

**Comment by seanmlb** [comment]
Thanks, @paul-buerkner! Noted for the future.
