### ISSUE TITLE
small typo in the reference manual

### ISSUE THREAD

**Issue by ASKurz** [paul-buerkner/brms#899]
Hey Paul, there's a small typo on page 155 of the brms reference manual in the `pp_average.brmsfit` section. When defining the `weights` argument, you used a double "be" in the final sentence: "Some some method, weights may also be be a numeric vector of pre-specified weights."

**Comment by paul-buerkner** [comment]
Thanks! Should be fixed now.

**Comment by ASKurz** [comment]
Well look at that. We were so focused on the "be be" that we didn't notice how that sentence starts with at double "Some some."

**Comment by paul-buerkner** [comment]
Haha. This is fixed now as well

Am Sa., 16. Mai 2020 um 16:17 Uhr schrieb A. Solomon Kurz <
notifications@github.com>:
