### ISSUE TITLE
Predict function doesn't work in developmental version

### ISSUE THREAD

**Issue by alireza202** [paul-buerkner/brms#9]
I get this error when I want to predict new data:

>Error: C stack usage 8037119 is too close to the limit

but when I revert to Cran version, it works fine.

**Comment by paul-buerkner** [comment]
Thanks for reporting! It is hard to tell why this happens without more information.

How large is your new data? Does this happen for every (subset of) new data. You may try only one or two rows of new data and see if the error still occurs.

Can you also show me the traceback of the error (write traceback() after the error ocurred)?

**Comment by alireza202** [comment]
The new data is pretty small, ~ 100. For now I have reverted to the old version, but I'll check again, and let you know.

This is the model:

data { 
  int<lower=1> N;  # number of observations 
  real Y[N];  # response variable 
  int<lower=1> K;  # number of fixed effects 
  matrix[N,K] X;  # FE design matrix 
  # data for random effects of ASIN 
  int<lower=1> J_1[N];  # RE levels 
  int<lower=1> N_1;  # number of levels 
  int<lower=1> K_1;  # number of REs 
  real Z_1[N];  # RE design matrix 
} 
transformed data { 
} 
parameters { 
  vector[K] b;  # fixed effects 
  vector[N_1] pre_1;  # unscaled REs 
  real<lower=0> sd_1;  # RE standard deviation 
  real<lower=0> sigma;  # residual SD 
} 
transformed parameters { 
  vector[N] eta; # linear predictor 
  vector[N_1] r_1;  # REs 
  # compute linear predictor 
  eta <- X*b; 
  r_1 <- sd_1 * (pre_1);  # scale REs 
  # if available add REs to linear predictor 
  for (n in 1:N) { 
    eta[n] <- eta[n] + Z_1[n]*r_1[J_1[n]]; 
  } 
} 
model { 
  # prior specifications 
  sigma ~ cauchy(0,5); 
  sd_1 ~ cauchy(0,5); 
  pre_1 ~ normal(0,1); 
  # likelihood contribution 
  Y ~ normal(eta,sigma); 
}

**Comment by paul-buerkner** [comment]
Thanks for the model code, but I rather ment the function call brm(formula, data, etc.) so that I can replicate your model with dummy data and see if the same error occurs (sorry that my formulation was misleading).

**Comment by alireza202** [comment]
Sure, here it is:

>brm(formula = y ~ x1 + x2 + x3 + (1 | subcat), 
data = df,
family = "gaussian",
n.chains = 4,
n.cluster = 4)

**Comment by alireza202** [comment]
I solved it, but I'm not sure how. It had something to do with my factor levels. When I refactored them again, it worked. Factors in R are much like wildcards... you never know what's gonna happen with them...

**Comment by paul-buerkner** [comment]
I am glad to hear that, although it would have been interesting to understand what was really causing this issue. ;-)
