### ISSUE TITLE
Changing the reference level of predictor variable

### ISSUE THREAD

**Issue by dkatsimpokis** [paul-buerkner/brms#902]
Hi!

In categorical predictors of more than two levels, the models takes one level as a reference and it compares the rest of the levels with the reference (thus showing N_of_levels - 1 posterior estimates in the end). Nevertheless, the output of the model does not show all possible comparisons of the levels within the categorical variable. One way around it is to relevel() the factor and refit the model. But if the models takes an hour to fit for example, this comes at computational cost. Is there another way around it which would not require refitting the model or re-leveling a factor? 

thank you!

**Comment by paul-buerkner** [comment]
Please ask brms related questions on https://discourse.mc-stan.org/ using the Interfaces - brms tag.
