### ISSUE TITLE
Position of code added via stanvars has changed

### ISSUE THREAD

**Issue by singmann** [paul-buerkner/brms#903]
As you might remember, Quentin Gronau and I have developed an interface for fitting models using linear models with `brms` using the JZS prior in our `bfrms` package: https://github.com/bayesstuff/bfrms/

However, a more or less recent change in `brms` has broken our code. The problem is that the way `brms` has created the transformed parameters block has changed and now the position of our addition to this block via `stanvars` does not work anymore.

Let me demonstrate with a short example based on:
```r
## devtools::install_github("bayesstuff/bfrms")
library(bfrms)
data(Machines, package = "MEMSS")
Machines <- droplevels(Machines[Machines$Machine %in% c("A", "C"),])
make_stancode_bfrms(score ~ Machine + (Machine||Worker), Machines)
```

In particular, in older versions of `brms` (e.g., 2.10) we get:
```stan
transformed parameters {
  // actual group-level effects
  vector[N_1] r_1_1 = (sd_1[1] * (z_1[1]));
  vector[N_1] r_1_2 = (sd_1[2] * (z_1[2]));
  r_1_1 = r_1_1 * sqrt(sigmaSQ);
  r_1_2 = r_1_2 * sqrt(sigmaSQ);                   
}
```

However, in the current `brms` version we now get:
```stan
transformed parameters {                       
  vector[N_1] r_1_1;  // actual group-level effects
  vector[N_1] r_1_2;  // actual group-level effects
  r_1_1 = r_1_1 * sqrt(sigmaSQ);
  r_1_2 = r_1_2 * sqrt(sigmaSQ);
  r_1_1 = (sd_1[1] * (z_1[1]));
  r_1_2 = (sd_1[2] * (z_1[2]));
}
```

Note that the part we add via `stanvars(..., block = "tparameters")` pasted below has moved and thus the model does not work anymore.
```
r_1_1 = r_1_1 * sqrt(sigmaSQ);
r_1_2 = r_1_2 * sqrt(sigmaSQ); 
```

Ideally, there would be and argument that allows specifying where a code segment added via `stanvar()` gets added in a code block. Either at the beginning (i.e., after definitions, as seems to be the case now) or at the end.

**Comment by paul-buerkner** [comment]
The reason to separate definition and initialization was because of a technical detail to enable setting priors to constants and is unfortunately necessary from what I remember. I think the option to write stanvars at the beginning or the end is very reasonable of a block. I will take a look at it now.

**Comment by paul-buerkner** [comment]
This feature should now be supported in the dev version via argument `position` of function `stanvars`.

**Comment by singmann** [comment]
Thanks a lot for the fast response. I can confirm that this works.
