### ISSUE TITLE
Recommendation of Bernoulli over binomial

### ISSUE THREAD

**Issue by jerlich** [paul-buerkner/brms#904]
In the [families](https://github.com/paul-buerkner/brms/blob/master/vignettes/brms_families.Rmd) vignette it says:

> binomial and bernoulli families are distinguished in brms as the bernoulli distribution has its own implementation in Stan that is computationlly more efficient.

This suggests (at least it did to me when I was learning about `brms` and Stan) that it is preferred to use Bernoulli over binomial. We have a data set with many repeated choices and binomial versions of our models fit more than 20x faster than the Bernoulli versions. So, I think I would recommend removing or rewording this statement. 

Note: there is also an **a** missing from _computationlly_.

**Comment by paul-buerkner** [comment]
You are right, the statement is misleading when read from a certain perspective. Thank you! What I ment is that `brm(y | trials(1) ~ ..., family = binomial())` is less efficient than `brm(y ~ ..., family = bernoulli())`. Of course, binomial is more efficient when there are more than 1 number of trials. I will clarify that statement in the vignette.

**Comment by paul-buerkner** [comment]
I have removed the statement in question.
