### ISSUE TITLE
Alternatives to cov_ranef() for modeling covariance and distance

### ISSUE THREAD

**Issue by jonnations** [paul-buerkner/brms#905]
Hi Paul,

In the 2nd edition of Statistical Rethinking, Ch. 14, McElreath lays out two alternative ways to model covariance and distance (phylogenetic or spatial), calling them L1 (the OU process kernel) and L2 (the quadratic kernel). The commands in the ```rethinking``` package are ```cov_GPL1``` and ```cov_GPL2```.  

From what I can tell, I believe that ```cov_ranef``` models a linear decay between covariance and distance, similar to the "Brownian Motion" model that is commonly used. These alternative processes allow for different rates of decay, creating potentially much more realistic biological (or other) models of trait covariance. Though these can easily be implemented in ```rethinking```, or directly in Stan, it would be very cool to have them available in brms. I think this would generate a lot of interest from evolutionary biologists.

**Comment by jonnations** [comment]
Sorry! I have since discovered the exponential quadratic kernel in the ```gp``` command in ``brms```. It looks like the L1 / OU kernel could possibly be implemented by modifying the ```gp``` code, however it would be great to have it supported in the package.

**Comment by paul-buerkner** [comment]
I would need more mathematical details about these methods but don't have the 2nd edition of statistical rethinking at my hands right now. Any place where I can read about the methods you suggest adding?

**Comment by jonnations** [comment]
Searching for L1 and L2 didn't yield much for me, but the two processes are very similar. The L2 method is currently implemented in the ```cov_exp_quad``` method in ```gp()``` in brms. There is a detailed discussion on this between you and @ASKurz in his [issue # 8](https://github.com/ASKurz/Statistical_Rethinking_with_brms_ggplot2_and_the_tidyverse/issues/8)  in his rethinking/brms bookdown repository. The L2 method is discussed in some detail in Rethinking v.1. 

According to Rethinking 2, the OU/L1 process is a exponential distance kernel rather than a quadratic distance kernel. Therefore the only difference between the L2 (```cov_exp_quad```) process and the L1 is the squaring of the distance matrix. So changing the equation in Rethinking v.1  page 410 from 
$\mathbf{K}{ij} = \eta^2exp(-\rho^2D^2{ij})
to 
$\mathbf{K}{ij} = \eta^2exp(-\rho^2D{ij}) 

In stan code, from [rethinking package](https://github.com/rmcelreath/rethinking/blob/f9c16bb7faec8a9883d976a769824b1764d12540/R/ulam_templates.R):
```cov_GPL2``` =  ...```K[i, j] = sq_alpha * exp(-sq_rho * square(x[i,j]) )```...
vs 
```cov_GPL1``` = ...```K[i, j] = sq_alpha * exp(-sq_rho * x[i,j] )```...
The remainder of the kernels is the same.

From what I understand (which admittedly isn't much), perhaps changing the  ```cov_exp_quad``` kernel from 
```out <- sdgp^2 * exp(-diff_quad / (2 * lscale[1]^2))``` 
to 
```out <- sdgp^2 * exp(-diff_quad / (2 * lscale[1]))```
may produce the L1 kernel, though the math here may actually be more complicated.

Another possible issue is that it seems like ```cov_exp_quad``` uses two points to calculate the euclidean distance on the fly using $||x_{i} - x_{j}||$ (i.e., the Euclidian norm). In [Ch 13.4, equation 13.7](https://bookdown.org/connect/#/apps/1850/access) @ASKurz uses two spatial points in the gp formula like ```total_tools ~ 1 + gp(lat, lon2) + logpop```. I am not sure if/how the kernel would calculate this distance with a dendrogram as an input value to gp(). It seems like a distance matrix would need to be the input. 

What would ultimately be very cool for users like me would be to run models using ```cov_ranef``` (I realize that will be deprecated soon) and the L1 gaussian kernel, and then do some posterior predictive checks and model comparison. 

I hope this gives you some direction. McElreath points out in Rethinking 2 that the gaussian process nature of these "phylogenetic corrections" has largely failed to be recognized by biologists, and unfortunately I don't have any primary sources to share with you. 

Thanks for taking a look! I know you're busy.

**Comment by jonnations** [comment]
Thanks Paul! I'll keep my eye on updates to [#234](https://github.com/paul-buerkner/brms/issues/234)
