### ISSUE TITLE
different loglikelihood for lmm with monotonic effects between 2.10 and 2.12

### ISSUE THREAD

**Issue by bnicenboim** [paul-buerkner/brms#911]
Hi,
I got very different kfold and loo results between versions 2.10 and 2.12. I've just calculated kfold "by hand" in 2.12 just relying on the log-likelihood calculated by brms and I get the same results as with brms::kfold. So I have to assume that there is or there was a problem with the way log likelihood is calculated for this type of model (`( y ~ mo(x) | mo(x) | group, family =lognormal)`).  (The results didn't change for lmm without monotonic effects).

I'm still investigating if I can identify the problem with a minimal example, but @paul-buerkner , are you aware of any major change related to this (loglikelihood/monotonic effects) between 2.10 and 2.12?

I'll be happy if you can take a look at this soon, the results for the model comparison for my paper (about to be submitted) are upside down between versions! 

Thanks!

**Comment by paul-buerkner** [comment]
I think I fixed one thing about monotonical random effects at some point
but I cant remember with certainty right now. Does anything appear in the
news file?

Bruno Nicenboim <notifications@github.com> schrieb am Do., 28. Mai 2020,
13:41:

**Comment by paul-buerkner** [comment]
In 2.12, I fixed a bug with regard to that. The news file says:

"Fix a bug in the Stan code of models with multiple monotonic 
varying effects across different groups thanks to Julian Quandt."

**Comment by bnicenboim** [comment]
so that means that I can't trust the loglikelihood of 2.10 for a model like 
(( y ~ mo(x) | mo(x) | group, family =lognormal))
right?

**Comment by paul-buerkner** [comment]
I think so yes. I am sorry, I cannot remember what exactly was wrong but I remember this bug was found also by looking at loo results. So the new version should be correct.

**Comment by bnicenboim** [comment]
Ok, found it:

https://github.com/paul-buerkner/brms/commit/9fbcc5fa042a1008a798998ef5551247e9e34a2e
And 
https://discourse.mc-stan.org/t/failure-to-recover-simulated-group-means-in-cross-classified-lmm-with-monotonic-predictor/12978/5

Oh :/ So the paper changes....

**Comment by paul-buerkner** [comment]
I am sorry :-( hope you didnt publish it yet.

Bruno Nicenboim <notifications@github.com> schrieb am Do., 28. Mai 2020,
15:18:
