### ISSUE TITLE
`brm` returns 'blank' object and segfaults on large three-level model

### ISSUE THREAD

**Issue by mcmahanp** [paul-buerkner/brms#913]
I've been struggling with a strange problem for a few days now estimating a model with `brm`. I have a somewhat complex model on a large data set (>3M observations). Whenever I try to estimate this model, the returned object is somehow blank or empty. When I try to print it or call any function on it, the R console just gives me another prompt without doing anything else. R will also usually crash with a "Segmentation fault: 11" eventually if I try to keep working with that session.

I have tried this on two different machines, with two OSs (Mac using clang, and Ubuntu using gcc), and have tried on R 3.6.3 and 4.0. I have also tried both pre-built and source installations of Rcpp, RStan, and brms with a variety of compilation flags, always getting the same basic result.

I have managed to pare it down into a seemingly reproducible script with simulated data that triggers the issue consistently for me:
```r
library(brms)

# simulate some data
n3 <- 1000
n2 <- 150000
k2 <- sample(15:25,n2,replace=TRUE)
n1 <- sum(k2)
d <- data.frame(
    y = rpois(n1,1.5),
    x0 = rpois(n1,0.01),
    x1 =rnorm(n1),
    x2 = rnorm(n1),
    x3 = rnorm(n1),
    id2 = rep(seq(n2),k2)
)
d$id3 <- sample(n3,n2,replace=TRUE)[d$id2]


# model
m <- y ~ x0 + x1 + x2 + x3 + (1 + x0 + x1 + x2 | id2) + (1 + x3 | id3)

# fit
f <- brm(m,family='negbinomial',data=d,
        prior = c(set_prior("normal(0,5)", class = "b"),
                  set_prior("lkj(2)", class = "cor")),
        chains=1,warmup=1,iter=10,refresh=1)

print(f)
```
The returned object `f` acts the same on both OSes I have tried this on: printing nothing and seemingly completely ignored by the interpreter, with no way to access any kind of summaries or samples. There aren't even the expected warnings about R-hat and sample size. The estimation behavior is somewhat different though. On Mac (10.14.4) using clang, it will run through the 10 iterations after compiling the model. On Ubuntu (18.04 LTS) using gcc it will return to the command prompt immediately after compiling the model, apparently without even trying to sample. I'm very curious to see if other people are able to run this script and get a usable `f`.

I'm at a complete loss here. This may be an issue with either RStan or Stan rather than brms, but I am not sure quite how to track it down. Any help or advice would be very welcome!

**Comment by paul-buerkner** [comment]
Do the functions `make_stancode` and `make_standata` work ok for this model?

**Comment by mcmahanp** [comment]
Both of these seem to work fine.

```r
make_stancode(m,family='negbinomial',data=d,
        prior = c(set_prior("normal(0,5)", class = "b"),
                  set_prior("lkj(2)", class = "cor")))
sd <- make_standata(m,family='negbinomial',data=d,
        prior = c(set_prior("normal(0,5)", class = "b"),
                  set_prior("lkj(2)", class = "cor")))
```

**Comment by mcmahanp** [comment]
Followup:

If I run this directly in rstan with
```r
library(rstan)

m <- y ~ x0 + x1 + x2 + x3 + (1 + x0 + x1 + x2 | id2) + (1 + x3 | id3)

sd <- make_standata(m,family='negbinomial',data=d,
        prior = c(set_prior("normal(0,5)", class = "b"),
                  set_prior("lkj(2)", class = "cor")))

sc <- make_stancode(m,family='negbinomial',data=d,
        prior = c(set_prior("normal(0,5)", class = "b"),
                  set_prior("lkj(2)", class = "cor")))

fit_stan <- stan(model_code=sc,data=sd,chains=1,warmup=1,iter=10,refresh=1)
```

Then the returned object fit_stan looks like an exact copy of the `sd` `standata` object, rather than the expected `stanfit`.

**Comment by paul-buerkner** [comment]
Thank you for investigating this further. Your results suggest that this is not a brms issue but rather happens somewhere deeper in rstan or stan. I guess it would make most sense if you asked the question on https://discourse.mc-stan.org/ then.
