### ISSUE TITLE
Default priors for fixed effects in mixed-effects logistic regression?

### ISSUE THREAD

**Issue by quantumlinguist** [paul-buerkner/brms#917]
Hi, 
I'm using the brms package for the first time and I was now trying to find out what the default priors are for the fixed effects of my model via the prior_summary() function but I don't quite understand the output. It looks like the random effects have student-t priors (3,0,10) but the fixed effects don't show any priors. What does this mean? Below is the output for the fixed effects. 
Thanks. 

    
<img width="761" alt="Screenshot 2020-06-06 at 15 08 58" src="https://user-images.githubusercontent.com/65797612/83944983-cd404480-a807-11ea-9e9b-447148f86266.png">

**Comment by torkar** [comment]
Hi,

```{r}
?set_prior
```

> The default prior for population-level effects (including monotonic and category specific effects) is an improper flat prior over the reals.

**Comment by quantumlinguist** [comment]
Ok, thanks!
