### ISSUE TITLE
How to use ggplot to customize Conditional Effects plot?

### ISSUE THREAD

**Issue by quantumlinguist** [paul-buerkner/brms#918]
I'm trying to customize the conditional effects plot with ggplot2 but I can't, even though the vignette says "The corresponding plot method returns a named list of ggplot objects, which can be further customized using the ggplot2 package."

This is an example of what I'm doing and the error I get no matter what ggplot function I use (ylim(), ggtitle(), geom_point(), etc). 

<img width="490" alt="Screenshot 2020-06-07 at 07 45 34" src="https://user-images.githubusercontent.com/65797612/83961387-efcb6f80-a892-11ea-9520-da9215c91ff9.png">

**Comment by paul-buerkner** [comment]
Please ask brms related questions on https://discourse.mc-stan.org/ using the Interfaces - brms tag.
I also suggest to read the doc conditional_effects more carefully as your question is answered there.
