### ISSUE TITLE
Default prior on intercept when using offset

### ISSUE THREAD

**Issue by fweber144** [paul-buerkner/brms#923]
Initially, I thought it might be good to post [this issue](https://discourse.mc-stan.org/t/prior-on-intercept-when-using-offset-in-brms/15713) in the Stan Forums, but it seems like it is too specific there. So perhaps this GitHub issue tracker is a better place, although I'm still not sure if its really a bug or if I am just misunderstanding something.

**Comment by paul-buerkner** [comment]
I am not sure I would call it a bug. Rather, the default prior on the intercept is not elaborate enough yet to take the offset into account. I cannot provide any guarantee that the brms default priors are sensible in all cases. It is up to the user to specify appropriate priors. That said, I think it should not be too difficult to adjust the default priors on the intercept according to the offset, so this may be implemented at some point.

**Comment by paul-buerkner** [comment]
This should now be implmented.
