### ISSUE TITLE
se(sigma = FALSE) returns samples for sigma & throws warnings for Rhat/ESS

### ISSUE THREAD

**Issue by wpetry** [paul-buerkner/brms#928]
When fitting a meta-analysis model, the default syntax for fitting a residual standard deviation term `se(..., sigma = FALSE)` throws warnings & still includes posterior samples for `sigma`. It's confusing to return samples for a term not in the model (incl. in `summary()` and `plot()` output.

**Could** `sigma` **be suppressed in output by default when** `se(..., sigma = FALSE)`**?** I suspect this may have been the behaviour of previous versions based on other resources [[html](https://bookdown.org/MathiasHarrer/Doing_Meta_Analysis_in_R/bayesian-meta-analysis-in-r-using-the-brms-package.html)] [[html](https://vuorre.netlify.app/post/2016/09/29/meta-analysis-is-a-special-case-of-bayesian-multilevel-modeling/)]. My apologies if I inadvertently missed the explanation of this behaviour in the [NEWS.md](https://github.com/paul-buerkner/brms/blob/master/NEWS.md) or other docs.

reprex following example code from `?addition-terms`:
```
# set up dummy data
nstudies <- 20
true_effects <- rnorm(nstudies, 0.5, 0.2)
sei <- runif(nstudies, 0.05, 0.3)
outcomes <- rnorm(nstudies, true_effects, sei)
data1 <- data.frame(outcomes, sei)

# fit example model WITHOUT residual standard deviation term
fit <- brm(outcomes | se(sei, sigma = FALSE) ~ 1,
            data = data1)
summary(fit)  # shows entry for `sigma`
plot(fit)  # includes traceplot for `sigma`
posterior_samples(fit)  # returns a vector of 0s for `sigma`

```
↳ warnings:
```
Warning messages:
1: The largest R-hat is NA, indicating chains have not mixed.
Running the chains for more iterations may help. See
http://mc-stan.org/misc/warnings.html#r-hat
2: Bulk Effective Samples Size (ESS) is too low, indicating posterior means and medians may be unreliable.
Running the chains for more iterations may help. See
http://mc-stan.org/misc/warnings.html#bulk-ess
3: Tail Effective Samples Size (ESS) is too low, indicating posterior variances and tail quantiles may be unreliable.
Running the chains for more iterations may help. See
http://mc-stan.org/misc/warnings.html#tail-ess

```

**Comment by paul-buerkner** [comment]
The posterior samples for `sigma` are `0` which is exactly what `sigma = FALSE` implies. The reason I am now using this formulation is because it requires the least amount of special case coding. Currently, I don't see that supressing `sigma` in this case would be worth the effort.

The warnings are issued by `rstan` (not by brms) and we will update these warnings in the future so that they are hopefully less confusing to users.
