### ISSUE TITLE
Should the zero inflated beta distribution be zero hurdle beta?

### ISSUE THREAD

**Issue by ConorGoold** [paul-buerkner/brms#929]
I apologise if this is better asked on the Stan discourse forums, but I thought it would fit best here first. 

I'd imagine it is mainly historical convention, but wouldn't fun_zero_inflated_beta.stan (https://github.com/paul-buerkner/brms/blob/master/inst/chunks/fun_zero_inflated_beta.stan) (and the functions therein) be better named fun_hurdle_beta.stan? And the zero_one_inflated_beta would be zero_one_hurdle_beta?

Because the beta distribution has support for ```(0,1)``` only, it seems confusing that zero-one-augmented beta distributions are referred to as 'inflated' distributions, because inflated distributions generally indicate mixtures (e.g. the zero-inflated Poisson). This would be more inline with the Stan manual too (https://mc-stan.org/docs/2_23/stan-users-guide/zero-inflated-section.html), although I appreciate that other R packages refer to these models as zero-inflated.

**Comment by paul-buerkner** [comment]
I agree with you the *_hurdle_beta would be a mathematically better name. There are even places in the (internal) doc and implementation of these families in brms where I point to this fact. However, not only do other packages use 'zero-inflated' but also all the relevant literature and I came to the conclusion that the improve mathematical exactness is not worth the confusion the different naming creates in users (not to mention the dozens of emails and discourse questions I would receive from people asking where the differences are).
