### ISSUE TITLE
Request: allow for mi() in distributional models

### ISSUE THREAD

**Issue by karldw** [paul-buerkner/brms#930]
Thanks again for the wonderful package!

I'm running into an issue where [`vars_keep_na.brmsterms`](https://github.com/paul-buerkner/brms/blob/9c71c68b0fe10cef732a8d1500c6076a9ea4f247/R/formula-sp.R#L202) is unhappy with the specification when I try to use the imputed value of a missing variable to model one of the other parameters in a univariate estimation.
In the example below, I'm basically combining the missing values and distributional modeling vignettes. For instance, I would like to use the imputed `bmi` as an explanatory variable for `sigma`.

Apologies if I've misunderstood the `mi` docs. I think this syntax currently isn't supported in brms, but let me know if this question is better directed at the stan forum.

```r
library(brms)
data("nhanes", package = "mice")

bform1 <- bf(
  bmi | mi() ~ age,
  sigma ~ mi(bmi)
)

brm(bform1, data = mice::nhanes)
# Error: Variables in 'mi' terms should also be specified as response variables in
# the model. See ?mi. Error occured for 'bmi'.


# Same story if we wanted to use bmi in a mixture model:
bf_mix <- bf(bmi | mi() ~ age, theta1 ~  mi(bmi), family=mixture(gaussian, gaussian))
brm(bf_mix, data = mice::nhanes)
# Error: Variables in 'mi' terms should also be specified as response variables in
# the model. See ?mi. Error occured for 'bmi'.

# Adding the same outcome variable again is wrong:
bform2 <- bform1 + bf(bmi | mi() ~ age)
# Cannot use the same response variable twice in the same model.
```

**Comment by paul-buerkner** [comment]
Can you explain why you would like to use the response variable to predict itself (or it's residual standard deviation)? It seems like a pretty non-standard model to me.

**Comment by karldw** [comment]
I mentioned modeling `sigma` because it seemed easier to discuss, but the model I'm trying to estimate is a hurdle model. I'm imagining a latent variable approach where the hurdle probability `hu` is allowed to depend on the imputed value of the outcome.
I think it is non-standard (and it's certainly possible I'm thinking about it incorrectly). Let me know if it's too niche to include in brms!

**Comment by paul-buerkner** [comment]
If you want this kind of model, you could duplicate and rename your response variable, in which case brms wouldn't notice that you are using the same response variable twice in a multivariate model. Please make sure to `set_rescor(FALSE)` in this case to avoid additional trouble.

**Comment by karldw** [comment]
Thank you!
