### ISSUE TITLE
Conditional_effects fails with categorical model when using scale.

### ISSUE THREAD

**Issue by JamieCranston** [paul-buerkner/brms#933]
Thanks so much for your work on this package, its been really useful to my work.

I'm just wondering if there may be an issue in the plotting of conditional_effects for categorical models.
It seems like scaling a variable directly in the formula, which works for linear models doesn't for categorical models. It's quite easy to work around by scaling else where but thought I'd post it here just in case.

R 4.0.0
brms 2.13.0

```data(mtcars)
testCategorical<- brm(gear ~ hp,
    data = mtcars,
    family = categorical())
plot(conditional_effects(testCategorical)) #Works
![image](https://user-images.githubusercontent.com/36704853/85414120-9ab27d80-b563-11ea-9df8-2c05dd3a6b3d.png)

testScaleCategorical  <- brm(gear ~ scale(hp),
            data = mtcars,
            family = categorical())

plot(conditional_effects(test2)) #Fails

#Error in data.frame(..., check.names = FALSE) : 
#  arguments imply differing number of rows: 100, 300

testScaleLinear <- brm(gear ~ scale(hp),
            data = mtcars,
            family = gaussian())
plot(conditional_effects(testScaleLinear )) #Works
![image](https://user-images.githubusercontent.com/36704853/85414139-a1d98b80-b563-11ea-87cb-473cdf70f474.png)


```

**Comment by paul-buerkner** [comment]
Thanks! The problem should now be fixed.

**Comment by JAQuent** [comment]
Hey I use version.string R version 4.1.0 (2021-05-18) plus brms_2.16.3 but I also get the following issue:

`conditional_effects(model_schemaVR1_AFC,  spaghetti = TRUE)`

This leads to this problem: 
`Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 100, 11200000`

The model is 

`Family: bernoulli 
  Links: mu = logit 
Formula: accAFC ~ sExp + I(scale(sExp^2)/2) + (1 | subNum) + (1 | objNum) `

Is this a related bug?

**Comment by paul-buerkner** [comment]
could you please provide a minimal reproducible example for this problem?

Jörn Alexander Quent ***@***.***> schrieb am Fr., 21. Jan.
2022, 03:31:

**Comment by JAQuent** [comment]
# Lib
library(brms)

# Create data
n <- 40
data   <- data.frame(x = rnorm(n))
xb     <- 0.1 + 0.5*data$x + 2*data$x^2 + rnorm(n)
p      <- 1/(1 + exp(-xb))
data$y <- rbinom(n = n, size = 1, prob = p)

# Model fit
mfit <- brm(y ~ poly(x, 2), data = data, family = bernoulli())

# Create plot
conditional_effects(mfit, spaghetti = TRUE)

**Comment by paul-buerkner** [comment]
Thanks! The default are 95% credible intervals of the "prediction line" (mean of the posterior predictive distribution computed via `posterior_epred`).

**Comment by paul-buerkner** [comment]
This issue should now be fixed on github.
