### ISSUE TITLE
Return posteriors with conditional_effects

### ISSUE THREAD

**Issue by AlexHmann** [paul-buerkner/brms#934]
Hi!

I have a simple suggestion, which probably takes few minutes to implement, but which I didn't manage to achieve when trying around with the source code:
Is there a way conditional_effects could return posteriors as a separate list (so far it only returns the summary table)? I would be interested in displaying the posterior of the difference between two estimates I produce via conditional_effects. It would be very straight-forward if I could just substract two posteriors returned by conditional_effects. I am kind of reluctant to producing these posteriors separately with posterior_predict et al. because I am afraid I won't be doing the exact same as conditional_effects.
I read someone having the same problem in one of the brms Stan forums...

Thanks a lot (for this, but also the amazing R package)!
Alex

**Comment by paul-buerkner** [comment]
You can do this already by using `spaghetti = TRUE` and extracting the `spaghetti` argument per element of the output. Yeah, it is a workaround but it does the job and makes it not worth to implement a new option that does essentially the same.

**Comment by AlexHmann** [comment]
Oh, super nice! Thanks!!
