### ISSUE TITLE
Problem with rskew_normal function

### ISSUE THREAD

**Issue by bbbales2** [paul-buerkner/brms#936]
On the Stan forums @famuvie pointed out there is a problem with the rskew_normal function ([here](https://discourse.mc-stan.org/t/discrepancy-between-nominal-and-realised-prior-predictive-distributions/16145)).

Here are densities of some skew normal random numbers generated by sampling a posterior in Stan, `rsn` in the `sn` package, generating random numbers in the generated quantities block, and the `rskew_normal` function.

![rskew](https://user-images.githubusercontent.com/4742424/85633226-d2debc80-b646-11ea-92b9-739d87fc7f67.png)

The implementation in math is [here](https://github.com/stan-dev/math/blob/develop/stan/math/prim/prob/skew_normal_rng.hpp#L55)

Stan code:
```
parameters {
  real b;
}

model {
  target += skew_normal_lpdf(b | -1, 1, -4);
}

generated quantities {
  real g = skew_normal_rng(-1, 1, -4);
}
```

R code:
```
library(tidyverse)
library(cmdstanr)
library(brms)
library(sn)

model = cmdstan_model("skew_normal.stan")

fit = model$sample()

rng_sn = rsn(4000, xi = -1, omega = 1, alpha = -4)
rng_rskew = rskew_normal(4000, mu = -1, sigma = 1, alpha = -4)

df = tibble(rng_stan_sampling = fit$draws() %>% posterior::as_draws_df() %>% pull(b),
            rng_sn = rng_sn,
            rng_rskew = rng_rskew,
            rng_stan_gq = fit$draws() %>% posterior::as_draws_df() %>% pull(g))

df %>%
  gather(which, value) %>%
  ggplot(aes(value)) +
  geom_density(aes(color = which))
```

**Comment by bbbales2** [comment]
Ooo, this looks like maybe an issue where the interface is written in terms of `mu`/`sigma` but the code is written in terms of `xi`/`omega`.

I suspect this line: https://github.com/paul-buerkner/brms/blob/3c1f217c0d5484c8cf88fe4b2fe11a2daaf2a525/R/distributions.R#L343

Should be:
```
args <- cp2dp(mu, sigma, alpha, xi = mu, omega = sigma)
```

**Comment by bbbales2** [comment]
Or I dunno. ```rskew_normal(4000, xi = -1, omega = 1, alpha = -4)``` produces the desired distribution though.

**Comment by paul-buerkner** [comment]
I am a little confused. I don't see a problem at this point. brms uses a special mean-SD-skewness parameterization that is not equal to the standard parameterization, unless you specify `xi` and `omega` as you did above.

**Comment by bbbales2** [comment]
The first couple arguments are 'mu' and 'sigma' and they are unused.

This makes `rskew_normal(4000, -1, 1, -4)` not be the same thing as "skew_normal(-1, 1, 4)" in the priors.

**Comment by bbbales2** [comment]
Oh that `cp2dp` thing does something. Ignore the first thing then. The second thing still seems confusing (that these wouldn't have comparable signatures).

**Comment by paul-buerkner** [comment]
As I said, the brms parameterization of skew_normal is not the one in Stan. You have to use the `xi` and `omega` arguments to make them equal. But I may be missing something here.

**Comment by bbbales2** [comment]
> As I said, the brms parameterization of skew_normal is not the one in Stan.

But `prior(skew_normal(-1, 1, -4), class = "b")` uses Stan's parameterization, right?

At least that's what I'm seeing when I do code generation (it makes the line `target += skew_normal_lpdf(b | -1, 1, -4);`). Is that right?

**Comment by famuvie** [comment]
Dear Paul and Ben, thanks for your help.

To wrap up, there is no bug, but a confusion in parameterisation. One has to be aware that `brms::set_prior()` uses the parameterisation in the __Stan language__ (as stated in the doc, by the way), not the default parameterisation in `brms` itself. Brief illustration below.

You can close the issue from my side. Thank you both.

``` r
library(brms, quietly = TRUE)
library(tidyverse, quietly = TRUE)

pred_sn <-
  brm(
    y ~ 1,
    sample_prior = "only",
    prior = c(
      ## Watch out! parameterisation skew_normal: xi, omega, alpha
      set_prior("skew_normal(-1, 1, -4)", class = "Intercept")
    ),
    data = data.frame(y = rep(0, 5e3)),
    iter = 5e3,
    refresh = FALSE
  )
#> Compiling the C++ model
#> Start sampling


pred_sn %>%
  posterior_samples(pars = "b_Intercept") %>%
  add_column(
    nominal_off = rskew_normal(nrow(.), -1, 1, alpha = -4),
    nominal_ok = rskew_normal(nrow(.), xi = -1, omega = 1, alpha = -4)
  ) %>%
  gather(sample, value) %>%
  ggplot(aes(value, colour = sample)) +
  geom_vline(xintercept = 0, colour = "grey80") +
  geom_density() +
  scale_x_continuous(limits = c(-10, 10))
```

![](https://i.imgur.com/CDizP7w.png)

<sup>Created on 2020-06-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by paul-buerkner** [comment]
Yes, I agree that this is confusing. Hadn't thought about that earlier. Thanks for the discussion about the topic.
