### ISSUE TITLE
loo.brmsfit: Cholmod error 'problem too large'

### ISSUE THREAD

**Issue by anirban-mukherjee** [paul-buerkner/brms#937]
Hi,

When I run a model with 5000 iterations (1000 warmup) and 4 chains, loo.brmsfit works fine on the returned brmsfit object. When I run the same model on the same data with the same number of iterations (5000 iterations, 1000 warmup) but with 16 chains, I get:

Error in .local(x, y, ...) : 
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105

The only difference is the number of chains (4 vs. 16). The data and the model are identical. ZZZ$fit, where ZZZ is the returned brmsfit object, has size 4000 x 16 x 1713 in the case of 16 chains.

Is the above error coming from ZZZ$fit being too large for Cholesky factorisation when using 4000 iterations and 16 chains? I can reduce the number of iterations and/or reduce the number of chains (both work fine for my model and data).

Thanks,
Anirban

**Comment by torkar** [comment]
Hi, why would you need 16 chains? Is there a particular reason for this since I've never seen a reason to use more than four (to calculate $\widehat{R}$ reliably).

**Comment by anirban-mukherjee** [comment]
In one of the models, brm returned a warning that the Bulk ESS was low. As the server had extra cores, I both increased the number of iterations and the number of chains. I know 16 is excessive but as long as the number of cores is > number of chains, the performance implications are minimal. In the current model: 2000 iterations and 4 chains is fine. However, the error is bugging me as I am not sure if my C++ toolchain is broken or if there is some problem with the code or I am hitting a size limitation of one of the packages.

I will try to come up with a MWE as otherwise it may not be possible to debug this. I can't replicate with the stock examples from the documentation if I just increase the number of iterations and chains.

**Comment by torkar** [comment]
Well, if you increase the samples from 16000 to 64000, and it's trying to convert to a dense object it shouldn't hit the roof that early (my guesstimate). Paul should know better the limitations. 

You can read more about it [here](https://stackoverflow.com/questions/58302449/what-does-the-cholmod-error-problem-too-large-means-exactly-problem-when-conv)

**Comment by anirban-mukherjee** [comment]
Thank you for the link! Reading that, here is a conjecture. Perhaps this is due to the feature space + iterations + chains. When estimating the model, I specify 6 factors in brmsformula as explanatory variables. These 6 factors have many levels (hence 1713 parameters). If there is a cast from a 64000 * 1713 sparse matrix to a dense matrix then that would do it.  (16000 * 1713 * 8)/1e6 = 219 GB. (64000 * 1713 * 8)/1e6 = 877 GB. This particular server has ~300 GB of RAM. If this is the case, then this information is very useful as I have been stability problems and I could not work out why I kept running out of memory on my various computers. The above suggests an explanation. At the least, I will now be more careful when calling loo if the explanatory factors have many levels.

**Comment by torkar** [comment]
Voilà, as the French say :)

**Comment by paul-buerkner** [comment]
You could use pointwise = TRUE in loo to reduce memory requirements at the
expense of speed.

Richard Torkar <notifications@github.com> schrieb am Fr., 26. Juni 2020,
10:36:

**Comment by anirban-mukherjee** [comment]
Thanks both!
