### ISSUE TITLE
gp returns scaled length-scales without documentation

### ISSUE THREAD

**Issue by topipa** [paul-buerkner/brms#938]
According to the documentation of `gp`, the `scale` argument is true by default for improved speed and convergence, giving the impression of having no visible differences. However, scaling the predictors also changes the magnitude of the length-scale parameters, which are not scaled back when returned. This does not seem to be documented anywhere and is confusing, especially because the predictors in the `fit$data` object are kept unchanged.

I think a mention of the effects of scaling on the length-scales in the documentation of the `scale` argument would be really helpful. My suggestion would be to also scale the length-scales back to the scale of the original data when returned.

Below is a quick script for illustration

```
library(brms)
set.seed(1289)
N <- 30

X <- matrix(rnorm(N)) * 3
family <- gaussian()
y <- X + 0.1*rnorm(N)
data <- data.frame(y = y, x = X)

S <- 500

fit_gp <- brm(y ~ gp(x), data = data, family = family, chains = 1, iter = 2 * S,  control = list(adapt_delta = 0.9, max_treedepth = 13))
fit_gp_noscale <- brm(y ~ gp(x, scale = FALSE), data = data, family = family, chains = 1, iter = 2 * S, control = list(adapt_delta = 0.9, max_treedepth = 13))

lengthscales <- as.matrix(fit_gp$fit)[,grep("lscale", colnames(as.matrix(fit_gp$fit)))]
lengthscales_noscale <- as.matrix(fit_gp_noscale$fit)[,grep("lscale", colnames(as.matrix(fit_gp_noscale$fit)))]

# length-scales very different
print(mean(lengthscales))
print(mean(lengthscales_noscale))

# still data scale stays the same
print(sd(fit_gp$data$x))
print(sd(fit_gp_noscale$data$x))
```

**Comment by paul-buerkner** [comment]
You are right, this should be documented better. The issue of rescaling the lengthscale is not straight forward to resolve for reasons of backwards compatibility so changing the doc to be more explicit about it is probably the best choice at the moment.
