### ISSUE TITLE
monotonic effect vignette

### ISSUE THREAD

**Issue by ASKurz** [paul-buerkner/brms#939]
In your (2020; [https://doi.org/10.1111/bmsp.12195](https://doi.org/10.1111/bmsp.12195)) paper with Charpentier, y’all do a nice job pointing out how “if the monotonic effect is used in a linear model, *b* can be interpreted as the expected average difference between two adjacent categories of *x*.” (p. 6).  Would it be possible to explicitly make this point in your vignette, [*Estimating monotonic effects with brms*](https://CRAN.R-project.org/package=brms/vignettes/brms_monotonic.html)?

**Comment by paul-buerkner** [comment]
Good point. I added this sentence to the vignette.
