### ISSUE TITLE
inits with cmdstanr backend

### ISSUE THREAD

**Issue by gbiele** [paul-buerkner/brms#940]
Maybe this is only a documentation issue:

With rstan as backend one can use a list of lists to submit init arguments.
With cmdstanr this does not work. Instead following error message is returned:

> Error: If specified 'init' must be numeric or a character vector.

As described for cmdstanr, I wrote init values to a json file (https://mc-stan.org/cmdstanr/reference/write_stan_json.html),
but then i got following error:

> Error in get(inits, mode = "function", envir = parent.frame()) : 
  object 'init1.json' of mode 'function' was not found

Is it possible that brm is not set up yet to deal with cmdstanr-like init files?

### making init-files for cmdstanr ###
```
init_f = function(){
  return(list(Intercept = rnorm(1,mean = .2,sd = .025), # initialize high intercept to avoid negative mu
              shape = rnorm(1,mean = 2, sd = .05)))
}

init_files = c()
for (k in 1:4) {
  f = paste0("init",k,".json")
  write_stan_json(init_f,file = f)
  init_files = c(init_files,f)
}
```

**Comment by paul-buerkner** [comment]
That is likely indeed. Can you post a fully reproducible example? That would make it easier for me to fix this issue.

**Comment by gbiele** [comment]
Simulate data
```
library(brms)
library(cmdstanr)
options(mc.cores = 4)

set.seed(123)
x = scale(rnorm(100))
y = as.numeric(x > rnorm(100))
dt = data.frame(x,y)
```

Make initialisation files

```
init_files = c()
for (k in 1:4) {
  f = paste0("init",k,".json")
  write_stan_json(list(Intercept = rnorm(1),
                       b = rnorm(1)),
                  file = f)
  init_files = c(init_files,f)
}
```
Fit brms model with cmdstan as backend
```
fit_no_init = 
  brm(y~x,
      data = dt,
      family = bernoulli,
      backend = "cmdstanr",
      seed = 123)
```
Fit directly in cmdstan and use initialisations from files
```
cat(fit_no_init$model,file = "tmp.stan")
cmdstan_model = cmdstan_model("tmp.stan")
standatalist = 
  make_standata(y~x,
                data = dt)
attr(standatalist,"class") = "list"
fit_init_cmdstan =
  cmdstan_model$sample(data = standatalist,
                       seed = 123,
                       init = init_files)
```
Try init files with brms and cmdstan backend (does currently not work)
```
fit_init = 
  brm(y~x,
      data = dt,
      init = init_files,
      family = bernoulli,
      backend = "cmdstanr",
      seed = 123)
```

**Comment by jgabry** [comment]
I think we should also eventually allow lists of inits in cmdstanr. I'll open an issue for that.

**Comment by paul-buerkner** [comment]
Thanks! Should now be fixed.

**Comment by jgabry** [comment]
We just merged https://github.com/stan-dev/cmdstanr/pull/233 so it should also be possible to use a list of inits with CmdStanR now.

**Comment by paul-buerkner** [comment]
Thank you!

Jonah Gabry <notifications@github.com> schrieb am Mi., 1. Juli 2020, 17:22:

**Comment by gbiele** [comment]
I appreciate very much how you quickly you are implementing things!
I hope you are getting the recognition you deserve for your work!!

**Comment by jgabry** [comment]
@paul-buerkner If using the `init` argument as a list of lists with brms, is the intent for the user to name the parameters the way they're named in the underlying Stan code brms generates or the way they're named in R? For example, 

```r
  brm(
    count ~ zAge,
    data = epilepsy,
    backend = "cmdstanr",
    chains = 1,
    init = list(
      list("(Intercept)" = 1, "zAge" = 1) 
     # or is it something like list("Intercept" = 1, "b[1]" = 1)?
    )
  )
```

CmdStanR won't error if the the inits include parameters not used in the Stan program (it will just ignore them), so it's not totally clear what the specification should be. I can add something about this to https://github.com/paul-buerkner/brms/pull/944 if you want, just let me know.

**Comment by paul-buerkner** [comment]
inits should be named after the variables in the unterlying stan code at the moment. If you like, feel free to add that info in #944. Thank you!
