### ISSUE TITLE
Installation from github fails

### ISSUE THREAD

**Issue by Robinlovelace** [paul-buerkner/brms#941]
Reproducible example:

```r
remotes::install_github("paul-buerkner/brms")
```

Generates 

```
Error : (converted from warning) namespace ‘brms’ is not available and has been replaced
by .GlobalEnv when processing object ‘brmsfit_example1’
ERROR: unable to build sysdata DB for package ‘brms’
* removing ‘/usr/local/lib/R/site-library/brms’
Error: Failed to install 'brms' from GitHub:
  (converted from warning) installation of package ‘/tmp/Rtmp5BlChV/filef8baf376d/brms_2.13.3.tar.gz’ had non-zero exit status
```

on a couple of computers tested.

**Comment by paul-buerkner** [comment]
You may need to install rstantools from github first via 

```
remotes::install_github("stan-dev/rstantools")
```

**Comment by Robinlovelace** [comment]
Sorted, many thanks. Worth adding this as a `Remotes:` in the `Description`? Possibly not if it's just a one-off and if `rstantools` will be updated on CRAN soon.

**Comment by paul-buerkner** [comment]
rstantools 2.1 was on CRAN but got reversed back to 2.0 by the CRAN team after it showed some incompatibilities with other packages. Usually, I don't require any github versions for the brms main branch to work. I will revert the dependency on rstantool 2.1 until it is on CRAN again.

**Comment by Robinlovelace** [comment]
Many thanks Paul. Off topic I've just taken a read of Bayesian Item Response Modeling in R with brms and Stan and I'm impressed at the flexibility of your approach, not least in terms of the formulae. I'm looking to develop models to estimate 'mode shift', from cars to bikes and walking for example, and I think the new support for compositional responses in `brms` is a promising way forward that I've demonstrated in a prototype mode of ~100 cities worldwide as described here.

Unfortunately the code is failing now for reasons I do not understand. Is here a good place to ask about this or should I ask on the stan Discourse community? For the record (and before I forget to post it) here is a reproducible example highlighting the issue on my computer:

```r
library(brms)
library(dplyr)
library(sf)

d = readRDS(url("https://github.com/ATFutures/who3/blob/master/global-data/cities-101-osm-bus.Rds?raw=true"))
names(d)
# no zeros allowed: how to allow zero values?
d %>% sf::st_drop_geometry() %>% select(walking:cycling) %>% summary()
d = d %>% 
  st_drop_geometry() %>%
  # filter(cycling != 0) %>% 
  # filter(other != 0) %>% 
  mutate_at(vars(other, cycling), ~case_when(. == 0 ~ runif(n = 1, min = 0, max = 0.5), TRUE ~ .)) %>%
  ungroup() %>%
  select(-bb_poly) %>% 
  mutate(Density = Population / Area)
totals = d %>% select(walking:other, -City) %>% rowSums() - 100
d$car = d$car - totals
modes_matrix = d %>% select(walking:other) %>% as.matrix()
summary(rowSums(modes_matrix))
d = d %>% select(-(walking:other))
modes_matrix[modes_matrix == 0] = 0.01
d$mode = modes_matrix / 100
names(d)
head(d)
m = brm(mode ~ Density + bus_stops_per_1000 + has_tram, data = d, family = dirichlet(), inits = 0, iter = 10e4)
```

The issue is that the program seems to take forever to run after reporting on the first chain, which I imagine completed:

```
SAMPLING FOR MODEL 'd773a2adb8c851f51db3f2617c2657be' NOW (CHAIN 1).
Chain 1: 
Chain 1: Gradient evaluation took 0.000252 seconds
Chain 1: 1000 transitions using 10 leapfrog steps per transition would take 2.52 seconds.
Chain 1: Adjust your expectations accordingly!
Chain 1: 
Chain 1: 
Chain 1: Iteration:     1 / 100000 [  0%]  (Warmup)
```

I'm sure I got it working though, the result of that model run obtained using a previous version of your package can be found here: https://github.com/ATFutures/who3/releases/download/0.0.1/model-result-brms-density-bus-stops-101.Rds

Happy to report this elsewhere, let me know the best way forward.


All the best and thanks again for an amazing package!

**Comment by Robinlovelace** [comment]
Update: that code has has been running for more than 2 hours now making me think there is something wrong...

**Comment by paul-buerkner** [comment]
This is a question for https://discourse.mc-stan.org/


Am Mi., 1. Juli 2020 um 12:31 Uhr schrieb Robin <notifications@github.com>:

**Comment by Robinlovelace** [comment]
Update and heads-up @paul-buerkner, taking your previously posted advice on-board I have posted this question with more detail here: https://discourse.mc-stan.org/t/using-stan-via-brms-to-model-compositional-response-taking-forever/16320
