### ISSUE TITLE
One-inflated Beta distribution

### ISSUE THREAD

**Issue by brendanf** [paul-buerkner/brms#942]
Although it's possible to model a one-inflated Beta distribution using the zero-one-inflated Beta and allowing `coi` to go to 1 (possibly helped along by an informative prior), or alternatively by fitting `1 - response` using the zero-inflated Beta, it would be nice to have the strictly one-inflated Beta, which I expect would be faster than using the zero-one-inflated Beta, and produce more readily interpreted output than the inverted zero-inflated Beta.

**Comment by brendanf** [comment]
I'd be happy to give this a try myself and submit a pull request.  If I understand correctly, this would mean adding definitions of the Stan functions to `/inst/chunks/on_inflated_beta.stan` and a `one_inflated_beta` function to `R/families.R`?

**Comment by paul-buerkner** [comment]
Adding this would also involve more functions as documend at the end of the brms_customfamilies vignette.

You can also just fix `coi = 1` via `bf(..., coi = 1)` if you like. The speed decrease as compared to a pure one-inflated should be very small. Alternatively, the 1 - response option with zero-inflated beta will be as fast as the pure one-inflation implementation. Accordingly, I doubt it is worth adding a pure one-inflated beta distribution to brms at this point.

**Comment by brendanf** [comment]
I didn't realize that I could set a distributional parameter to a fixed value.  That helps, and you're right, on my test case the speed is almost as good as the `1-response` zero-inflated version.  However, I get warning messages: 
```
Warning messages:
1: The largest R-hat is NA, indicating chains have not mixed.
Running the chains for more iterations may help. See
http://mc-stan.org/misc/warnings.html#r-hat 
2: Bulk Effective Samples Size (ESS) is too low, indicating posterior means and medians may be unreliable.
Running the chains for more iterations may help. See
http://mc-stan.org/misc/warnings.html#bulk-ess 
3: Tail Effective Samples Size (ESS) is too low, indicating posterior variances and tail quantiles may be unreliable.
Running the chains for more iterations may help. See
http://mc-stan.org/misc/warnings.html#tail-ess
```

Traces for the other parameters look fine, it looks like the problem is just the zero variance in the `coi` chain.

**Comment by paul-buerkner** [comment]
You can safely ignore this message as it is a false positive.

brendanf <notifications@github.com> schrieb am Do., 2. Juli 2020, 13:42:
