### ISSUE TITLE
auto-saving criteria is broken

### ISSUE THREAD

**Issue by rubenarslan** [paul-buerkner/brms#943]
I think you changed the structure of the brmsfit object, but forgot to change it in one place in add_criterion. You used to store it in `x$loo` etc. Now, it is
`x$criteria$loo`.

But this line still checks `x$loo`.
https://github.com/paul-buerkner/brms/blob/70265e82f392f0b0286a3e468a7ecbff2b329a3c/R/loo.R#L508

I guess it should be

```r
new_criteria <- criterion[ulapply(x$criteria[criterion], is.null)]
```

**Comment by paul-buerkner** [comment]
You are right, thank you! Will fix it asap.

**Comment by paul-buerkner** [comment]
Thanks! Should now be fixed.
