### ISSUE TITLE
compile user-specified stan-model instead of automatically built stan-model

### ISSUE THREAD

**Issue by gbiele** [paul-buerkner/brms#945]
In the past I've found a few times that I would like brms to use a slightly modified version of the a stan-model brms generated, which cannot be implemented with the stanvars function. 

In this case I used this "hack" to produce a brmsfit object: 

1. Fit an initial standard brms model 
2. Modify model code (from step 1.) as needed
3. Generate new stanfit-object with updated model code
4. Replace stanfit object in original brmsfit (from step 1.) object with the new stanfit object
5. Update the now modified brmsfit model to obtain samples from the updated model (with compile = F).

Now it occurred to me that this could be made much easier if there would be a way to have a "custom_stan_model" option for brm, which takes as argument a complete model and compiles this instead of the Stan code brms generates from the model formula etc.
I think such a "custom_stan_model" would be in addition to the other options (formula, family, ...) which the user would still need to define.

I realise that such an option is dangerous, because lots of things can go wrong if the custom Stan code no longer matches the model as specified with the model formula, family, .... On the other hand, this would be an easy way to allow for more customisation of brms models. I also hope that this would be easy to implement.

I also understand if such an option is to unsafe to implement for general use. In that case I'd be glad about a pointer to a more "elegant" way to "hack" a brm so that It directly compiles a custom model.

**Comment by paul-buerkner** [comment]
Not sure if it is related, but have you tried the `empty` argument of brms for this purpose already?

**Comment by gbiele** [comment]
I had not tried `empty` yet because I had not seen it.
I think that makes it sufficiently easy to use custom Stan models.
Thanks again for the speedy response!

**Comment by paul-buerkner** [comment]
Good. So can we close this issue then or is there more to it we should
think about?

Guido Biele <notifications@github.com> schrieb am Fr., 3. Juli 2020, 14:25:

**Comment by gbiele** [comment]
From my point of view the issue can be closed.
