### ISSUE TITLE
Help on non-linear models in BRMS

### ISSUE THREAD

**Issue by baldwaprateek** [paul-buerkner/brms#946]
Hi Paul,

I have started using BRMS from last couple of weeks. However, the data that I am working upon can be fitted using non-linear models. I have gone through several blogs on internet but I am finding difficult to get wholistic level explanation on Non-linear models using BRMS. 

I am unable to understand bf() and lf() functions and their usage in non-linear models. Appreciate your help if you can provide some explanation on non-linear models using BRMS with some examples.

Thanks,

**Comment by paul-buerkner** [comment]
Please ask brms related questions on https://discourse.mc-stan.org/ and provide more details so that people will actually be abe to help you.
