### ISSUE TITLE
brms formula: intercept or Intercept?

### ISSUE THREAD

**Issue by JackCaster** [paul-buerkner/brms#947]
Hi Paul,
I noticed that in the beginning of `help(set_prior)` it reads 
> To treat the intercept as an ordinary population-level effect and avoid the centering parameterization, use 0 + intercept on the right-hand side of the model formula.

with `intercept` in small letters. 

In `help(brmsformula)`, however, it is written 
>This behavior can be avoided by using the reserved (and internally generated) variable Intercept. Instead of y ~ x, you may write y ~ 0 + Intercept + x.

with `Intercept` in capital letter. 

Is the difference `intercept` vs. `Intercept` important?

**Comment by paul-buerkner** [comment]
both work but (capital) `Intercept` is recommended. In the future, please ask brms related questions on https://discourse.mc-stan.org/

**Comment by JackCaster** [comment]
Sure I will. I opened the issue here because I thought it was a typo in the docs :)

**Comment by paul-buerkner** [comment]
Good point. in the latest versions of brms, using `intercept` should actually be deprecated (with a warning) and at some point, only `Intercept` will be supported.
