### ISSUE TITLE
conditional_effects re_formula does not work with older cov_ranef models

### ISSUE THREAD

**Issue by jonnations** [paul-buerkner/brms#948]
Hi Paul,

I am plotting some  brms models I ran before version 2.13. These are phylogenetic models that used the `cov_ranef  =` argument, just like the older brms phylogenetic vignettes. I get an error if I try to plot `conditional_effects( model, re_formula = NULL)`

Example, from phylogenetic vignette in brms version < 2.13, running in brms < 2.13
`model_simple <- brm(`
  `phen ~ cofactor + (1|phylo),`
  `data = data_simple,`
`  family = gaussian(),`
 ` cov_ranef = list(phylo = A)`
`)`

Then if you open the model in brms v. 2.13, and try:
`conditional_effects(model_simple, re_formula = NULL)`
you get the error: `Error: The following elements of 'cov_ranef' are unused: 'phylo'`

It seems like `conditional_effects` requires the new `gr()` argument to properly plot the random effects in phylogenetic models.

Thanks!

**Comment by paul-buerkner** [comment]
Thanks. I will fix it.

**Comment by paul-buerkner** [comment]
I cannot reproduce the error when fitting the model with brms 2.12. Can you check the output of `model_simple$version` and tell me which brms version was used to fit the model?

**Comment by paul-buerkner** [comment]
And could you try the latest github version of brms to see if this fixes it already?

**Comment by jonnations** [comment]
`model_simple$version` is brms 2.8.0, however when I ran the model again and tried to plot using the dev version 2.13.3 it seems to work fine. Thanks for checking into it!

**Comment by paul-buerkner** [comment]
Great. Closing this issue now.
