### ISSUE TITLE
Argument to fit all subset models?

### ISSUE THREAD

**Issue by nahorp** [paul-buerkner/brms#950]
Hello,

I have 3 categorical predictors (A, B, and C) and I am fitting a maximal model - y ~ A * B * C + (A * B * C | id). However, I want to go via the route of Bayesian Model Averaging (to incorporate model uncertainty) and then run the `bayesfactor_inclusion` function (from the `bayestestR` package). For this, I would need to have all lower order models [e.g., y ~ A * B + (A * B | id), y ~ A + (A | id) etc.] and instead of fitting them individually, I was wondering if there was an argument to `brm` that could do this? I realise that this would take a lot of time and that the corresponding random effect structure would have to change as well but thought I'd ask at least.

Thank you for reading :)

**Comment by paul-buerkner** [comment]
You have to fit all of them manually. In the future, please ask brms related questions on https://discourse.mc-stan.org/
