### ISSUE TITLE
Problem with brms on R4.0.2 / Windows 10.

### ISSUE THREAD

**Issue by wolski** [paul-buerkner/brms#954]
Just upgraded from R3.6.3 to 4.0.2 on my Windows machine and installed package brms from CRAN.
The code snipped shows that although brms::brm runs without errors trying to access the fited model produes

```
> fit1
Error: object 'fit1' not found
````

Any suggestions where to start looking at a fix would be highly appreciated. I guess my R install is broken. 
I am running the example code from the brm function documentation.

```{r}
> install.packages("brms")
Installing package into ‘C:/Users/wolski/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/brms_2.13.0.zip'
Content type 'application/zip' length 5821425 bytes (5.6 MB)
downloaded 5.6 MB

package ‘brms’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\wolski\AppData\Local\Temp\RtmpasA6pn\downloaded_packages
> library(brms)
Loading required package: Rcpp
Loading 'brms' package (version 2.13.0). Useful instructions
can be found by typing help('brms'). A more detailed introduction
to the package is available through vignette('brms_overview').

Attaching package: ‘brms’

The following object is masked from ‘package:stats’:

    ar

> bprior1 <- prior(student_t(5,0,10), class = b) +
+     prior(cauchy(0,2), class = sd)
> fit1 <- brm(count ~ zAge + zBase * Trt + (1|patient),
+             data = epilepsy, family = poisson(), prior = bprior1)
Compiling the C++ model
> 
> fit1
Error: object 'fit1' not found
```

Tested on two (2) up to date Windows 10 Systems (laptop and desktop). 

I tried to get more information by setting `silent = FALSE` but nothing is being printed.

```
> brm(count ~ zAge + zBase * Trt + (1|patient),
+     data = epilepsy, family = poisson(), prior = bprior1, silent=FALSE)
Compiling the C++ model
>
```

**Comment by paul-buerkner** [comment]
This is a caused by a problem in the current rstan CRAN version on Windows and is not related to brms. You can find various threads that deal with that topic on https://discourse.mc-stan.org/. For now, it may be easiest to revert to rstan 2.19.3.

**Comment by wolski** [comment]
@paul-buerkner Thank you for your reply. I did post this issue also on r-help. (sorry for any inconvenience).
