### ISSUE TITLE
micro-macro multilevel analysis

### ISSUE THREAD

**Issue by TMax66** [paul-buerkner/brms#955]
Hi all, 
it's possible to use brms for micro-macro multilevel analysis?
I mean analysis where individual-level predictors are using to predict a  group-level outcome variable and in particular I need to predict a dichotomic variable. 

Thanks a lot
Massimo

**Comment by paul-buerkner** [comment]
Please ask brms related questions on https://discourse.mc-stan.org/ and provide some more detail to you question so that people can help you more easily.

**Comment by TMax66** [comment]
Thanks , I  will do.
Massimo
