### ISSUE TITLE
Add website to GitHub metadata / "About" section

### ISSUE THREAD

**Issue by mikemc** [paul-buerkner/brms#959]
This is just a minor suggestion to help users more quickly find the website - Many R packages on Github link to the package website through the GitHub metadata (see https://github.com/tidyverse/purrr/ for an example). Previously the place to set this was below the repo name, but now it is in the "About" section. This is always where I look look for the package website to view vignettes and function references and I think this would make the Brms website much easier to find than the current situation of having to spot the website link mid-way through a list in the Readme.

**Comment by paul-buerkner** [comment]
Good idea. Do you have any idea from where the "About" section takes the link?

**Comment by paul-buerkner** [comment]
Nevermind. Found it :-D
