### ISSUE TITLE
How to specify gr in CAR models

### ISSUE THREAD

**Issue by jgellar** [paul-buerkner/brms#960]
I was playing around with fitting CAR models, following your example in `?car`. I fit the model that is in your example:

```
fit <- brm(y | trials(size) ~ x1 + x2 + car(W), 
           data = dat, data2 = list(W = W),
           family = binomial(),
           iter = 5000) 
```

The model fits, but I get a warning message:

`Using CAR terms without a grouping factor is deprecated. Please use argument 'gr' even if each observation represents its own location.`

However, I can't figure out how to correctly specify the `gr` argument in `car`. For example, I tried the following:

```
rownames(W) <- 1:100
fitg <- brm(y | trials(size) ~ x1 + x2 + car(W, gr = factor(1:100)), 
           data = dat, data2 = list(W=W),
           family = binomial(),
           iter = 5000) 
```

And I get the following error message:

`Error: The following variables are missing in 'data': 'W'`

Every variation I try results in similar issues where the function can no longer find different aspects of the data. What am I doing wrong?

**Comment by paul-buerkner** [comment]
Please ask brms related questions on https://discourse.mc-stan.org/
