### ISSUE TITLE
Progress not shown with update to rstantools (2.1.1)

### ISSUE THREAD

**Issue by JCruk** [paul-buerkner/brms#961]
I updated `rstantools` to 2.1.1 this week, and it seems `brms` no longer displays progress.

Previously, I would get a message staying the model was being compiled, then each worker/chain being initialized, then each chain's progress through the warmup and sampling interations.

Now I only get a `start sampling` message until the run is finished and takes me back to a cursor.

This is with `brms_2.13.4` and  `Rcpp_1.0.5`, `R 4.0.2`, `Ubuntu 20.04 64-bit` 

I have tried the following arguments without success:
```
silent = FALSE,
refresh = 1,
open_progress = TRUE,
verbose = TRUE,
```

Is there a way to bring progress monitoring back to the console?

**Comment by paul-buerkner** [comment]
This issue is unrelated to brms but to some rstan issue (?) I suppose. Please check out https://discourse.mc-stan.org/ for potential solutions.
