### ISSUE TITLE
Cox model: intercept for baseline hazard

### ISSUE THREAD

**Issue by fweber144** [paul-buerkner/brms#962]
I really like the (experimental) implementation of the Cox model in brms. However, I have a question concerning the intercept in the I-splines for the baseline hazard function: Argument `intercept` of `splines2::iSpline()` defaults to `TRUE` and the corresponding help page says:

>  Notice that when using I-Spline for monotonic regression, `intercept = TRUE` should be set even when an intercept term is considered additional to the spline bases in the model.

So I was wondering if there was a specific reason why brms sets `intercept` to `FALSE` by default (see `brms:::.brmsfamily()` and `brms:::bhaz_basis_matrix()`). For the M-splines, setting `intercept` to `FALSE` might be appropriate (as it defaults to `FALSE` in `splines2::mSpline()`).

EDIT: Using different values for argument `intercept` in `splines2::iSpline()` and `splines2::mSpline()` is a bad idea here: This would result in an M-spline and an I-spline which don't match, in the sense that the M-spline is then not the first derivative of the I-spline (or the other way round, the I-spline is then not the integrated M-spline). See also [my post](https://github.com/paul-buerkner/brms/issues/962#issuecomment-661679291) below.

**Comment by paul-buerkner** [comment]
I had a reason. It is a shame, I didn't document well enough. Essentially, I remember it had something to do with how the spline intercepts interacts with the "actual" intercept. The latter should be present for the cox model to behave as all the other models. I think there were problems occuring with having both intercept but I can't remember that exactly. If you like and have time I would appreciate you experimenting with this option and see what happens (e.g., by making a branch of brms and changing the intercept setting).

**Comment by fweber144** [comment]
Yes, I know that problem of forgetting to document. Before following your advice of finding the problem empirically, I took some time to read more about the underlying maths. Sorry, I should have done that in the first place. So it turns out that a spline intercept should be used by setting argument `intercept` to `TRUE` for both, `splines2::iSpline()` and `splines2::mSpline()`:
* A spline intercept is needed because otherwise, the baseline hazard would be constrained to be zero at the minimum observed value for `y` (the survival or censoring time). In [rstanarm's yet unpublished survival feature](https://github.com/stan-dev/rstanarm/tree/feature/survival), the M-spline also has an intercept on its own (see also [this preprint by Brilleman et al. (2020)](https://arxiv.org/abs/2002.09633), section 2.2 "Model formulations", paragraph "M-splines model (the default)" on pp. 5-6). Note that in the preprint by Brilleman et al. (2020), they say the M-spline was constrained at the *origin*. I will have to figure out how they implemented the M-spline.
* Different values for argument `intercept` in `splines2::iSpline()` and `splines2::mSpline()` should not be used here as this would result in an M-spline and an I-spline which don't match, in the sense that the M-spline is then not the first derivative of the I-spline (or the other way round, the I-spline is then not the integrated M-spline).

To illustrate both of these points, consider the following code which is a modified version of the code from [this vignette of the splines2 package](https://cran.r-project.org/web/packages/splines2/vignettes/splines2-intro.html):
```r
library(splines2)
x <- seq(10, 11, 0.01)

#-----------------------------------------------------------------------
# Differing values for argument "intercept"

# M-spline:
msMat <- mSpline(x, df = 5L, intercept = FALSE) # The default for argument "intercept" is FALSE.
# The M-spline is constrained to be zero at the minimum of x:
matplot(x, msMat, type = "l", ylab = "y")

# I-spline:
isMat <- iSpline(x, df = 5L, intercept = TRUE) # The default for argument "intercept" is TRUE.
matplot(x, isMat, type = "l", ylab = "y")

# Now, the M-spline is not the first derivative of the I-spline:
stopifnot(identical(msMat, deriv(isMat)))

#-----------------------------------------------------------------------
# Same values for argument "intercept"

# M-spline:
msMat <- mSpline(x, df = 5L, intercept = TRUE) # The default for argument "intercept" is FALSE.
# The M-spline is not constrained to be zero at the minimum of x:
matplot(x, msMat, type = "l", ylab = "y")

# I-spline:
isMat <- iSpline(x, df = 5L, intercept = TRUE) # The default for argument "intercept" is TRUE.
matplot(x, isMat, type = "l", ylab = "y")

# Now, the M-spline is indeed the first derivative of the I-spline:
stopifnot(identical(msMat, deriv(isMat)))

```

However, using a spline intercept has further consequences in brms:
* To still have 1 internal knot, brms's default for argument `df` of `splines2::iSpline()` and `splines2::mSpline()` (see `brms::.brmsfamily()`) needs to be increased from `4L` to `5L`.
* In rstanarm's yet unpublished survival feature, the M-spline coefficients are constrained to a simplex (see again the preprint by Brilleman et al. (2020) linked above). Non-negativity is already implemented in brms, but the sum-to-one constraint is currently missing. When using an ordinary intercept (i.e. as part of the linear predictor), I think this simplex constraint makes sense since this constrains the integral over the whole M-spline to be 1. (As each basis spline of an M-spline integrates to 1, the whole M-spline integrates to the sum of the spline coefficients.) The ordinary intercept then scales this normalized M-spline. (Note that I would recommend this simplex constraint even if no spline intercept was used, although I think excluding the spline intercept (as currently done) is not appropriate, as explained above.) With the code below, I tested the behavior of `brms` for the `kidney` data when using a spline intercept, an ordinary intercept, and the current default half-normal(0, 1) prior for the spline coefficients, but I didn't encounter any problems. I think this may be due to the half-normal(0, 1) being quite narrow which is essentially a different way to constrain the magnitude of the spline coefficients and therefore their sum. (Though I think the simplex constraint is preferable.)

An alternative solution might be to use no ordinary intercept (but still a spline intercept) and no simplex constraint for the spline coefficients, but then the prior on the spline coefficients should not be too narrow so that the baseline hazard may be scaled to higher values as well. The half-normal(0, 1) prior might be too narrow.

So this raises another question: Do you want to include the ordinary intercept in the linear predictor? The traditional Cox model doesn't have one (but rstanarm's yet unpublished survival feature has one). Your post above suggested that you want to include the ordinary intercept for reasons of compatibility with other models in brms.

Note that the use of an B-spline instead of the M-spline might be more straightforward since the B-spline doesn't need an intercept on its own (see again the preprint by Brilleman et al. (2020) linked above).

Here is the code for testing the behavior of `brms` for the `kidney` data with a spline intercept, an ordinary intercept, and the current default half-normal(0, 1) prior for the spline coefficients:
```r
library(brms)
options(mc.cores = parallel::detectCores())

kidney_fit <- brm(formula = time | cens(censored) ~ age * sex + disease + (1|patient),
                  data = kidney,
                  family = brms:::cox(bhaz = list(df = 5L, intercept = TRUE)),
                  prior = NULL,
                  seed = 45546L,
                  silent = FALSE,
                  save_model = "kidney_code.stan",
                  file = "kidney_fit")

```

**Comment by paul-buerkner** [comment]
Thank you for your detailed investigation! I will make more experiments myself and see how, for example, the simplex parameterization works out. 

In experiments I have done when initially implementing the cox model, I could only reproduce results of `survival::coxph` when including the model intercept as the spline intercept does not fully replace the former. I should be able to dig out these experiments again to take another look.

**Comment by paul-buerkner** [comment]
Ok, after some more experiments, I am convinced of adding a spline intercept and using a simplex for the spline coefficients. I pushed the corresponding changes to github. 

Would you mind running some of your tests as well and verify that things work as you would expect?

**Comment by fweber144** [comment]
Great, thanks. My tests are fine.

**Comment by paul-buerkner** [comment]
Thank you! I realize that now be actually a good time to export the cox family and make it an official feature of brms. 

Is there anything else you think that needs to be addressed before doing that?

**Comment by fweber144** [comment]
I don't see any further problems. A posterior predictive check would be a nice new feature, but that's a different story and I'll open a new issue for that.

**Comment by paul-buerkner** [comment]
The Cox proportional hazards model is now offically supported via family cox.
