### ISSUE TITLE
Cox model error: Internal knots must be set inside of boundary knots.

### ISSUE THREAD

**Issue by proshano** [paul-buerkner/brms#963]
Hello,

Sorry I don't have reproducible example because my problem occurs with my specific (and at this time confidential) dataset:

Basically I do the standard form of the experimental brms Cox model call:

fit_brm <- brm(timetofirstevent | cens(1 - status) ~ 1 + treatment, data = data, family = brmsfamily("cox"))

I get:
Error in rcpp_mSpline_basis(x = xx, df = df, degree = degree, internal_knots = knots,  : 
  Internal knots must be set inside of boundary knots.

Any suggestions?

Thank you for considering and for making a great package!

**Comment by paul-buerkner** [comment]
Unfortunately not, but it would help a lot if you tried to create a simulated data set that also triggers the error.

**Comment by paul-buerkner** [comment]
Can you check whether it does work now with the latest brms version from github?

**Comment by proshano** [comment]
It does work! Thank you!
