### ISSUE TITLE
Model starts compiling but doesn't returning a model object

### ISSUE THREAD

**Issue by nateweller1** [paul-buerkner/brms#968]
When running the code it outputs "Compiling Stan program...", runs for about five minutes, and then stops. There are no other messages or errors, and it does not return a model object. I have tried running multiple models and codes from online examples with same issues, so it doesn't appear to be code related.

Any idea what may be causing this?

**Comment by paul-buerkner** [comment]
This is likely the same rstan issue a lot of people see at the moment. See also https://github.com/paul-buerkner/brms/issues/965
