### ISSUE TITLE
no object from the brm function 

### ISSUE THREAD

**Issue by filpir** [paul-buerkner/brms#969]
running the first example of the brm function

fit1 <- brm(count ~ zAge + zBase * Trt + (1|patient),
            data = epilepsy, family = poisson(), prior = bprior1, silent=F, empty=F, refresh=1)
summary(fit1)

the following was returned:

summary(fit1) : object "fit1" not found

what can be the reason, since this did not occour a few days ago?

**Comment by filpir** [comment]
R version  4.0.2 on windows 10.  The OS was updated the day the brm function worked normally

**Comment by vrballotin** [comment]
I have the same problem no object from the brm function have been created.

**Comment by paul-buerkner** [comment]
This is an rstan issue. See, for example, https://discourse.mc-stan.org/t/stan-not-running-after-updating-to-r-version-4-0-2-and-stan-updated-from-2-19-3-to-2-21/16519

**Comment by kirimaru-jp** [comment]
> 
> 
> running the first example of the brm function
> 
> fit1 <- brm(count ~ zAge + zBase * Trt + (1|patient),
> data = epilepsy, family = poisson(), prior = bprior1, silent=F, empty=F, refresh=1)

To see the log when building Stan model, add the parameter `stan_model_args = list(verbose=T)`  : 

` fit1 <- brm(count ~ zAge + zBase * Trt + (1|patient), data = epilepsy, 
                    family = poisson(), prior = bprior1, silent=F, empty=F, refresh=1,
                    stan_model_args = list(verbose=T) )
`
