### ISSUE TITLE
STAN warning in multivariate, sampling progress not printed

### ISSUE THREAD

**Issue by tatters** [paul-buerkner/brms#970]
Hi Paul,
I ran into a little issue while running multivariate models. For example, running the code from the vignette on multivariate models (https://cran.r-project.org/web/packages/brms/vignettes/brms_multivariate.html), I get:
```r {
devtools::install_github('paul-buerkner/brms')
library(brms)
packageVersion('brms')  # tried 2.13.3 and 2.13.5

data("BTdata", package = "MCMCglmm")
fit1 <- brm(
  mvbind(tarsus, back) ~ sex + hatchdate + (1|p|fosternest) + (1|q|dam),
  data = BTdata, chains = 2, cores = 2
)

# Setting 'rescor' to TRUE by default for this model
# Compiling Stan program...
# /tmp/Rtmpn8V3ui/file1c6b6d192a4a.stan:53:36: warning: missing terminating ' character
#    53 |     Y[n] = [Y_tarsus[n], Y_back[n]]';
#       |                                    ^
# /tmp/Rtmpn8V3ui/file1c6b6d192a4a.stan:81:45: warning: missing terminating ' character
#    81 |   r_1 = (diag_pre_multiply(sd_1, L_1) * z_1)';
#       |                                             ^
 #   etc. - more lines like these
}
```

Despite the warning, the model seems to run OK, and non-multivariate models do not throw this warning. However, for some mysterious reason the sampling progress or indeed any messages at all are not printed for any models, even with `silent = FALSE`, although rstan behaves as expected if I call it directly. I think both issues appeared after I upgraded to R 4.0.
Thanks in advance!
Best regards,
Andrey

**Comment by paul-buerkner** [comment]
I don't get this warning. Which operating system etc are you using? The reason is that, in Stan, `'` is used as the transpose operator while, in R, it is one of two quote symbols. Somewhere in the process, R is confused by this and complains but doesn't really do anything about it so runs fine. You can safely ignore the warnings. 

With regard to the output printing, can you try the latest github version of brms and see if there is any change?

**Comment by tatters** [comment]
Updating from brms 2.13.5 to 2.13.7 from github has resolved the issue with output printing, except in multivariate models, where I'm still getting the error messages and no further info from stan after "Start sampling". The iterations count is printed normally when running via rstan::stan(), but not when stan is called from brms. Complete output:
``` {r}
library(brms)
packageVersion('brms')  # 2.13.7
packageVersion('rstan') # 2.21.2
data("BTdata", package = "MCMCglmm")
fit1 <- brm(
   mvbind(tarsus, back) ~ sex + hatchdate + (1|p|fosternest) + (1|q|dam),
   data = BTdata, chains = 2, cores = 2, iter = 200
 )
Setting 'rescor' to TRUE by default for this model
Compiling Stan program...
/tmp/Rtmp3cFyDg/file1687281b08cd.stan:53:36: warning: missing terminating ' character
   53 |     Y[n] = [Y_tarsus[n], Y_back[n]]';
      |                                    ^
/tmp/Rtmp3cFyDg/file1687281b08cd.stan:81:45: warning: missing terminating ' character
   81 |   r_1 = (diag_pre_multiply(sd_1, L_1) * z_1)';
      |                                             ^
/tmp/Rtmp3cFyDg/file1687281b08cd.stan:85:45: warning: missing terminating ' character
   85 |   r_2 = (diag_pre_multiply(sd_2, L_2) * z_2)';
      |                                             ^
/tmp/Rtmp3cFyDg/file1687281b08cd.stan:96:51: warning: missing terminating ' character
   96 |   vector[nresp] sigma = [sigma_tarsus, sigma_back]';
      |                                                   ^
/tmp/Rtmp3cFyDg/file1687281b08cd.stan:109:39: warning: missing terminating ' character
  109 |     Mu[n] = [mu_tarsus[n], mu_back[n]]';
      |                                       ^
Start sampling
Warning messages:
1: In the future, 'rescor' will be set to FALSE by default for all models. It is thus recommended to explicitely set 'rescor' via 'set_recor' instead of using the default. 
2: The largest R-hat is 1.08, indicating chains have not mixed.
Running the chains for more iterations may help. See
http://mc-stan.org/misc/warnings.html#r-hat 
3: Bulk Effective Samples Size (ESS) is too low, indicating posterior means and medians may be unreliable.
Running the chains for more iterations may help. See
http://mc-stan.org/misc/warnings.html#bulk-ess 
4: Tail Effective Samples Size (ESS) is too low, indicating posterior variances and tail quantiles may be unreliable.
Running the chains for more iterations may help. See
http://mc-stan.org/misc/warnings.html#tail-ess 
> 
```
System info: Kernel: 5.4.0-42-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 4.6.6  wm: muffin dm: LightDM Distro: Linux Mint 20 Ulyana base: Ubuntu 20.04 focal 
R version: 4.0.2 
Since the model is working, this is a minor problem really, don't waste time on it! I just thought you might like to know.
Regards,
Andrey

**Comment by paul-buerkner** [comment]
thanks! I cannot replicate this problem on any of my machines and there is really nothing in place that would stop `stan::sampling` to from returning messages anymore so I assume it is not really a brms issue despite showing in brms. Accordingly, and because this seems like a minor problem as you say, I will close this issue.
