### ISSUE TITLE
BS variance modeling capabilities similar to existing WS variance modeling capabilities

### ISSUE THREAD

**Issue by madelinecraft** [paul-buerkner/brms#972]
I often fit models allowing the within-subject variance sigma to be a function of predictors and allow the intercept to vary across individuals using brms. I would also like to be able to use brms to model the between-subject (BS) variance as a function of predictors. More specifically, I'd like to allow the BS variance to be a function of both level 1 and level 2 predictors as in:
Dzubur, E., Ponnada, A., Nordgren, R., Yang, C. H., Intille, S., Dunton, G., & Hedeker, D. (2020). MixWILD: A program for examining the effects of variance and slope of time-varying variables in intensive longitudinal data. Behavior Research Methods, 1-25.
I think that understanding the influence of predictors on the BS variance can be just as interesting as understanding the influence of predictors on the WS variance even though it is most common to model the WS variance.

**Comment by paul-buerkner** [comment]
I agree but this will require some deeper changes to brms and it may take some time until I manage to implement this feature.

**Comment by paul-buerkner** [comment]
I think this may become possible with the SEM syntax in brms to hopefully arrive this year. I am closing this issue here.
