### ISSUE TITLE
launch_shinystan.brmsfit(): Incorrect default for maximum tree depth (11)

### ISSUE THREAD

**Issue by fweber144** [paul-buerkner/brms#974]
In `brms:::launch_shinystan.brmsfit()`, the maximum tree depth stored in `max_td` defaults to 11. It should default to 10, see [https://github.com/stan-dev/shinystan/issues/183](https://github.com/stan-dev/shinystan/issues/183).

**Comment by paul-buerkner** [comment]
Thanks! I have changed it accordingly.
