### ISSUE TITLE
`pp_check` after imputing missing values during model fitting

### ISSUE THREAD

**Issue by niklasjohannes** [paul-buerkner/brms#975]
I'm relatively new to `brms`. Tried out imputing missing values during model fitting and wanted to inspect posterior predictive checks afterwards with the `pp_check` function. The code below yields an error:
```
library(brms)

dat <- 
  data.frame(
    y = c(1:9, NA),
    x = rnorm(10)
  )

model <- 
  brm(
    y | mi() ~ x,
    data = dat
  )

pp_check(model)
```

```
Error: NAs not allowed in 'y'.
```

Do I need to manually remove NAs from the raw data and pass those to the `pp_check` function?

**Comment by paul-buerkner** [comment]
I just made a small change to that NA values will be automatically removed (with a warning).
