### ISSUE TITLE
Feature request: Argument "robust" for summary.brmsfit()

### ISSUE THREAD

**Issue by fweber144** [paul-buerkner/brms#976]
It would be nice if `summary.brmsfit()` also had an argument `robust` similar to e.g. `coef.brmsfit()`: If `FALSE` (should be the default, for consistency with the other `robust` arguments), the mean is used as the measure of central tendency and the standard deviation as the measure of variability. If `TRUE`, the median and the median absolute deviation (MAD) are applied instead. [This was mainly copied from `?coef.brmsfit`.]

Another possibility would be to *add* the robust measures when this argument is set to `TRUE` but in that case, this argument should probably get a different name in `summary.brmsfit()`. Perhaps something like `add_robust`? For this `add_robust` argument, the default could then be `TRUE` (which I would personally prefer over `FALSE`).

**Comment by paul-buerkner** [comment]
Good idea. I added the `robust` argument to `summary.brmsfit`.
