### ISSUE TITLE
get_prior function problems with sigma

### ISSUE THREAD

**Issue by PCK1992** [paul-buerkner/brms#979]
When I try to use the `get_prior` function in this way 
```
test_prior <- get_prior(count ~ zAge + zBase * Trt + (1|patient), 
          data = epilepsy)

fit1 <- brm(count ~ zAge + zBase * Trt + (1|patient), 
            data = epilepsy,prior = test_prior, family = poisson())
```

I get the following error message:
```
Error: The following priors do not correspond to any model parameter: 
sigma ~ student_t(3, 0, 4.4)
Function 'get_prior' might be helpful to you.
```

I tested it with both `brms 2.13.9` and `brms 2.13.5` and I get the same error. Am I something doing wrong or is this a bug?

**Comment by paul-buerkner** [comment]
It seems you have forgotten the `family` argument in the `get_prior` function.
