### ISSUE TITLE
Offset in formula

### ISSUE THREAD

**Issue by alireza202** [paul-buerkner/brms#98]
Is there a way to use offset in brms? Say I want a variable to have a known coefficient of 1. How can I force it to be 1?

https://stat.ethz.ch/R-manual/R-devel/library/stats/html/offset.html

**Comment by alireza202** [comment]
I searched issues and I found out that you have already implemented it:

https://github.com/paul-buerkner/brms/issues/7

But I can't find how it can be used. It's not mentioned in the reference manual.

**Comment by paul-buerkner** [comment]
You can just use the offset function as in other model fitting function, e.g:

```R
fit <- brm(y ~ x + offset(z), ...)
```

**Comment by alireza202** [comment]
Awesome!
