### ISSUE TITLE
Warning from cmdstanr: write_stan_tempfile is deprecated

### ISSUE THREAD

**Issue by StaffanBetner** [paul-buerkner/brms#981]
When using cmdstanr as a backend I get this warning:
```
Warning message:
write_stan_tempfile() is deprecated. Please use write_stan_file() instead.
```

**Comment by paul-buerkner** [comment]
Will fix it soon.

**Comment by jgabry** [comment]
Yeah we changed it to `write_stan_file()`. I can submit a PR to avoid this warning in brms.

**Comment by paul-buerkner** [comment]
I was just about to do it myself :-D In which version did you change it?

**Comment by jgabry** [comment]
I just realized we didn't bump the version number when we did that. I can bump it now in CmdStanR and then I can submit a PR to brms that requires that version. Does that work?

**Comment by jgabry** [comment]
I'll also add it to mc-stan.org/r-packages so it can be installed by brms
