### ISSUE TITLE
"Compiling stan program..." for very very long time.

### ISSUE THREAD

**Issue by kilasuelika** [paul-buerkner/brms#983]
Recently I have a very strange problem.

When I use `brm()` for a model of only 5 variables, the message **"Compiling stan program..."** shows for some hours without progress. I use `top` command to check and never see `c1plus`. If I stop the R program(not quit r session), and then run the same single statement once more, It quickly compiles after some seconds and then begins to sample.  But I doesn't know how much time should I wait, sometimes I wait for 20 mins and run again however no luck.

I used brms before and doesn't encounter any problem. This problem only occurs recently. I am doubt that maybe there are some changes in recent versions of `brms` or `rstan` as I reinstalled them before this problem occurred.

I am also very curious about what is it doing when **"Compiling stan program..."**.

I'm using R in a Ubuntu 20.04 server. In my windows laptop, there is also the same problem.

**Comment by paul-buerkner** [comment]
This is not related to brms but to lower levels of the toolchain as brms doesn't compile but rather writes Stan code which then compiles. I suggest you post this issue on https://discourse.mc-stan.org/ and provide a bit more detail about your model(s) and your setup.
