### ISSUE TITLE
(Some) ggplot objects generated by brms do not accept further ggplot tweaks

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [paul-buerkner/brms#985]
Consider a small dataframe (RData in the attached file) containing a time series  with a strong "seasonal" (weekly) component : 

[D1.zip](https://github.com/paul-buerkner/brms/files/5112781/D1.zip)

``` r
> class(D1)
[1] "data.frame"
> dim(D1)
[1] 179   4
> sapply(D1, class)
     Date     NCoro     nDate       JdS 
   "Date" "integer" "numeric"  "factor" 
> head(D1)
        Date NCoro nDate  JdS
1 2020-02-24     1 18316 lun.
2 2020-02-25     1 18317 mar.
3 2020-02-26     0 18318 mer.
4 2020-02-27    19 18319 jeu.
5 2020-02-28    31 18320 ven.
6 2020-02-29    37 18321 sam.
```
(`nDate` is of course `as.numeric(Date)` and JdS is `weekdays(Date)`, both duplicated for ease of use ; the former is needed to get `gam` (and `brms`'s `s()` to work, since they do not accept `Date` values...).

Getting an estimation of the smoothed data is easy : 

- via `mgcv::gam` :
 ```r
system.time(S1 <- gam(NCoro ~ JdS + s(nDate), data=D1, family=poisson))
plot(gee)
```

- via `brms` : 
```r
library(brms)
options(mc.cores=parallel::detectCores())
## Damn slow...
system.time(foo <- brm(NCoro ~ JdS + s(nDate), data=D1, family=poisson,
                       control=list(max_treedepth=15), ##, adapt_delta=0.9),
                       seed=1723))
```

Obtaining a plot is easy

```
> Sfoo <- conditional_smooths(foo)
> Sfoo    ## Displays with the default theme
```

But trying to modify this plot *doesn't work* : 
> Sfoo + theme_classic()  ## Displays with the default theme
NULL                                 ## and returns a visible value (!)
```

Contrast that with "native"  `ggplot` objects : 

``` r
> RawPlot  <-  ggplot(D1, aes(x=nDate, y=NCoro)) + geom_line()
> RawPlot                                ## Displays with the default theme
> RawPlot + theme_classic()  ## Displays with  the "classic" theme, and
>                                              ## doesn't return any visible value
```

This in fact a "minimal non working example" : what I really want to do is to transform the scales of the `brms`-generated plot to : 
- exponentialize the effect tpo get the mean expected `NCoro` and its credible interval, and
- display human-readable dates rather than days-since-Unix-epoch...

This can be done, in theory, by using `ggplot2::scale_x_continuous` and "suitable" transformations (totally non-obvious to me ATM). But since I'm stuck at step one...

The alternative is to get raw data from the `brms` fit and wrangle my own, *i.e* rewriting (badly) what you wrote (right).

**Comment by paul-buerkner** [comment]
See the doc of `conditional_effects` for how to get the ggplot object and add other ggplot stuff to it.
