### ISSUE TITLE
Moment matching LOO doesn't work with cmdstanr

### ISSUE THREAD

**Issue by StaffanBetner** [paul-buerkner/brms#986]
When I try to use moment matching LOO on a model that I used cmdstanr as a backend for, I get this error: 
> Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘sampling’ for signature ‘"CmdStanModel"’

Code:
```
# tidyverse loaded as well as brms
mtcars %>% mutate(gear = gear %>% factor) -> mtcars

brm(data=mtcars, formula=bf(mpg~gear, sigma ~ gear), cores = 4, backend="cmdstanr") -> model

model %>% loo(moment_match=TRUE)
```

**Comment by paul-buerkner** [comment]
Yes, I am sorry, it won't work until cmdstan(r) adds some required features. I will add a proper error message.

**Comment by paul-buerkner** [comment]
Oh, I did already add a better warning message. Could you check if the error is better in the github version of brms?

**Comment by rok-cesnovar** [comment]
Hey, just curious what would cmdstan(r) have to add for this?

**Comment by paul-buerkner** [comment]
Since this issue requires only changes in cmdstanr and then later on in loo. I will close this issue here.
