### ISSUE TITLE
fit criteria description

### ISSUE THREAD

**Issue by mansillo** [paul-buerkner/brms#987]
This is perhaps a bit pedantic but could the documentation for the [function](http://paul-buerkner.github.io/brms/reference/model_weights.html) `model_weights` please be clarified to distinguish what the difference is between "LOO" and "LOO2".
IT currently says

> For the former three options, Akaike weights will be computed based on the information criterion values returned by the respective methods. For "loo2", method loo_model_weights will be used to obtain weights. 

The [loo_model_weights](https://mc-stan.org/loo/reference/loo_model_weights.html) function uses stacking as the default which

> combines all models by maximizing the leave-one-out predictive density of the combination _(sic.)_ distribution. That is, it finds the optimal linear combining weights for maximizing the leave-one-out log score.

Is there any practical difference in doing one over the other in inferences? Is there a best practice for when to use the LOO to derive Akaike weights or when to use maximising the LOO predictive density of the combined distribution?

I've got a set of models with the loo, loo_R2, bayes_R2 and waic criteria computed, would there be a computational advantage to calculating the loo criterion for each before estimating the loo2 weights?

**Comment by paul-buerkner** [comment]
LOO2 is almost always to be preferred as discussed in the stacking paper linked to in the loo_model_weights doc. I will try to improve the doc. There is no computational advantage having other criteria calculated first.

**Comment by mansillo** [comment]
Thanks @paul-buerkner !

**Comment by paul-buerkner** [comment]
Reopening this issue until I have actually changed the doc :-D

**Comment by paul-buerkner** [comment]
I updated the doc of `model_weights`.
