### ISSUE TITLE
cmdstanr backend: specifying path for executable

### ISSUE THREAD

**Issue by gbiele** [paul-buerkner/brms#988]
On some systems (like at my work) permissions management is restrictive such that one can execute models generated with cmdstanr only when they were saved in a specific location.

When compiling a model with cmdstanr, one ca set a `dir` option to specify the desired directory.
(https://rdrr.io/github/stan-dev/cmdstanr/man/model-method-compile.html).

It appears that this option can currently not be used when specifying cmdstanr as a backend for `brm` (additional arguments to `cmdstanr::sample` or `cmdstanr::variational` are possible)

It would be nice if one could also with brms specify the path to which the executable is saved.

(
I could try to make a pull request for this, but I am not sure if the following would be enough:

1) Add one more argument to the `brm` function (I understand you might be hesitant to add one more argument here) and add the path to `compile_args` 
2) modify `.compile_model_cmdstanr` to also submit the path when doing `do_call(cmdstanr::cmdstan_model, args)` 
)

**Comment by jgabry** [comment]
> I could try to make a pull request for this, but I am not sure if the following would be enough:
> 
> 1. Add one more argument to the `brm` function (I understand you might be hesitant to add one more argument here) and add the path to `compile_args`
> 2. modify `.compile_model_cmdstanr` to also submit the path when doing `do_call(cmdstanr::cmdstan_model, args)`

Yeah I think that should be sufficient to get it working. If @paul-buerkner is OK with adding an argument to `brm()` then that would be fine, but an alternative could be to use `...` for this too and internally split up the arguments that need to be passed to `sample()` from the ones that need to get passed to `compile()` (I don't think there are any name clashes). The upside is that the `brm()` function wouldn't need to add an argument that is only relevant for cmdstanr, but it's a bit messy to do different things with different arguments included in `...`.

**Comment by paul-buerkner** [comment]
I will need to check what is the best way to pass this argument.

**Comment by rok-cesnovar** [comment]
Cmdstanr could also read an env variable or a global option like `cmdstan_exe_dir` and this would not have to be a part of the brms interface. If @jgabry agrees with that we can transfer this issue there.

**Comment by jgabry** [comment]
Yeah good idea, I'm ok with that. We could have the `dir` argument default to the value of an environment variable or global option if it has been set.

**Comment by paul-buerkner** [comment]
You should be able to use argument `stan_model_args` for the purpose of passing arguments to the compile functions of the backend. I will close this issue, since I think it is resolved via `stan_model_args` but please feel free to reopen it if I end up being wrong.
