### ISSUE TITLE
Stan folks have invited you to write a blog post

### ISSUE THREAD

**Issue by wfolta** [paul-buerkner/brms#99]
Paul, this has appeared on Andrew Gelman's blog, under an [article on Stan](http://andrewgelman.com/2016/07/12/29511/):

> I added brms and added asterisks to indicate that brms and rethinking are not packages that we (the Stan dev team) wrote or are maintaining. If whoever wrote brms (or someone else) wants to write a blog post and mail to the stan-users list about what it does, you can send it to me (carp@alias-i.com) and I can post it here on Andrew’s blog.

**Comment by paul-buerkner** [comment]
Thanks Wayne! I have talked to Bob and will prepare a blog post in the next few weeks.

**Comment by jgabry** [comment]
Indeed. The link to Wayne's blog post on brms and rstanarm was put on the
blog a while back but I think you've added a bunch to brms since then so
maybe time for an update! No rush, but anytime you have something written
up that could work as a blog post let me know and I can put it in the blog
queue (but we can skip Andrew's standard 2-3 month delay). Sounds like
Bob's happy to do it too, so feel free to let either or both of us know.

**Comment by paul-buerkner** [comment]
I want to wait until brms 0.11 is released because then I can also talk about distributional regression (i.e. also predicting family specific parameters such as the residual standard deviation 'sigma'). Additionally, I can mention the Bayesplot package in this case so that it gets some initial awareness.

**Comment by wfolta** [comment]
Ooo, you keep on impressing me. I realize `rstanarm` has the mission of acting a lot like the default functions that people already use, but `brms` is so incredibly flexible. I hadn't fully though through the implications of the mixed ordinal logistic regression that I've been doing lately, and how specialized that really is -- but simple with `brm`.

**Comment by jgabry** [comment]
Yeah our goal with rstanarm really is about providing robust defaults, with
moderate flexibility, abd a particular focus on guiding people through the
transition to the Bayesian workflow.

What Paul has done is to provide a legitimate alternative to
manually programming in Stan a wide (and growing) array of fairly
complicated models, along with convenient and familiar methods for working
with the results. It's such a cool package and really an awesome addition
to the Stan universe.

Jonah

**Comment by wfolta** [comment]
Jonah, Yes, `rstanarm` provides an excellent bridge. As another example, it starts sampling immediately -- pre-compiled models -- which saves the 30-45-second compile that `brm` has. For someone just starting, extra compile time (particularly for a simple model) could be off-putting, so `rstanarm` does well there. (And its complex models do some impressive tricks as well to maximize performance.) The flip-side is that `brm` can do most anything, and you can take `brm`'s code and build on it or learn from it.

Both excellent projects, thanks to all involved! (I just want to make sure `brms` gets some press as well.)

**Comment by jgabry** [comment]
On Thursday, July 14, 2016, Wayne Folta <notifications@github.com> wrote:
>
> Both excellent projects, thanks to all involved! (I just want to make sure
> brms gets some press as well.)
>
Absolutely. The more attention we can bring to projects like brms that
make Stan and the perspective on statistics we promote accessible to a
wider audience the better!

And personally, it's a great feeling to see the Stan community expanding in
this way. That is, to know that we have people like Paul and Richard
(rethinking)  -- and everyone else who is developing Stan-related tools or
materials for teaching Stan (including your blog posts Wayne!) -- who value
what we're doing and want to help bring it to as many people as possible.

>

**Comment by jgabry** [comment]
Also, Paul I plan on recommending brms when Andrew and I teach our
intensive Bayes and Stan short course next week here in NYC. Anything in
particular you want me to mention that I might not know about (eg new
features coming soon)?

**Comment by jgabry** [comment]
Feel free to email me separately about that as I guess this is a github
issue I'm commenting on and this isn't an "issue".

**Comment by paul-buerkner** [comment]
Thanks for mentioning brms in you short course! I think that distributional regression will be the main new feature this month apart from incorporating the bayesplot package.

**Comment by jgabry** [comment]
I didn't even end up doing a single rstanarm example (we just entirely
focused on Bayesian concepts and writing Stan programs) but I put brms and
rethinking with rstanarm on the list I gave people with recommendations for
what packages and materials to check out after the course.

**Comment by paul-buerkner** [comment]
Thank you @jgabry!

**Comment by paul-buerkner** [comment]
The blog post is now available at http://andrewgelman.com/2017/01/10/r-packages-interfacing-stan-brms/

Thanks @jgabry for making this possible!

**Comment by jgabry** [comment]
No problem. Glad we go the post up. Keep up the great work!
