### ISSUE TITLE
CAR Model Output

### ISSUE THREAD

**Issue by Ksatkins** [paul-buerkner/brms#991]
Hi Paul. I am new to using this package and have a question regarding the Conditional Auto-Regressive modeling function in the BRMS formula. I tried running the example from the[ CAR page](http://paul-buerkner.github.io/brms/reference/car.html#see-also) with a "gr" term added to bring it up to the current practice. From what I understand of the documentation, I should have an output of the "car_term" that is then passed to BRMS. However, the sample model's "car_term" is NULL. I tried comparing the same model (loo) with and without the CAR term and the models look different from one another. However, I'm not sure if the CAR model is being passed onto BRMS properly. How can I see the output of the CAR portion of the model?

Operating System: Windows10
brms Version: 2.13.0

Thank you for your time and for this wonderful package.

**Comment by paul-buerkner** [comment]
Hi, please ask brms related questions on https://discourse.mc-stan.org/
