### ISSUE TITLE
Checking for existing path an save file in temp dir instead of terminating brm

### ISSUE THREAD

**Issue by Famondir** [paul-buerkner/brms#992]
Dear Mr. Buerkner,
I ran in some frustrating modelling failures in my starting phase and sometime even now when I'm using the jobs function of RStudio and forget to set the right working directory for the job. These failures occured when I set a path for the RDS save file that didn't already existed. This discarded models with hours and days of calculation time.

I would be happy if you can implement a check for the path at the start and throw an error before fitting or maybe even handier for jobs with multiple models to fit: to create a temp dir where the RDS files get saved if the specified path does not exist (due to typo or wrong working directory).

I would be happy to see this feature implemented in the official build.

Sincerely, Simon

**Comment by paul-buerkner** [comment]
Brms now checks whether the directory exists before fitting the model.
