### ISSUE TITLE
pointwise loo not working with custom beta_binomial2 example

### ISSUE THREAD

**Issue by DataDan01** [paul-buerkner/brms#998]
I'm working off these two links to reproduce the beta-binomial model out of Statistical Rethinking 2nd ed:
1) [Book converted to brms, tidyverse, and ggplot2](https://bookdown.org/content/4857/monsters-and-mixtures.html#over-dispersed-counts)
2) [brms guide on defining custom distribution](https://cran.r-project.org/web/packages/brms/vignettes/brms_customfamilies.html#the-beta-binomial-distribution)

I'm able to generate a lot of the output in the second link. However, when I to run either `loo` or `waic` pointwise I get this error: `Error in prep$dpars$mu[, i] : incorrect number of dimensions`

Using the latest versions of all packages, just did a fresh install today. Running on Windows 10. Still get the same error if I run the exact code in the second link. 

Am I doing something wrong?

Here's the exact code I'm trying to run:

```
library(rethinking)
library(dplyr)

data(UCBadmit) 

d <- UCBadmit %>% 
  mutate(gid = ifelse(applicant.gender == "male", "1", "2"))

#

rm(UCBadmit)
detach(package:rethinking, unload = T)
library(brms)

#

beta_binomial2 <- custom_family(
  "beta_binomial2", dpars = c("mu", "phi"),
  links = c("logit", "log"), lb = c(NA, 2),
  type = "int", vars = "vint1[n]"
)

#

stan_funs <- "
  real beta_binomial2_lpmf(int y, real mu, real phi, int T) {
    return beta_binomial_lpmf(y | T, mu * phi, (1 - mu) * phi);
  }
  int beta_binomial2_rng(real mu, real phi, int T) {
    return beta_binomial_rng(T, mu * phi, (1 - mu) * phi);
  }
"

stanvars <- stanvar(scode = stan_funs, block = "functions")

#

b12.1 <-
  brm(data = d, 
      family = beta_binomial2,  # here's our custom likelihood
      admit | vint(applications) ~ 0 + gid,
      prior = c(prior(normal(0, 1.5), class = b),
                prior(exponential(1), class = phi)),
      iter = 2000, warmup = 1000, cores = 4, chains = 4,
      stanvars = stanvars,  # note our `stanvars`
      seed = 12,
      file = "fits/b12.01")

#

expose_functions(b12.1, vectorize = TRUE)

log_lik_beta_binomial2 <- function(i, prep) {
  mu <- prep$dpars$mu[, i]
  phi <- prep$dpars$phi
  trials <- prep$data$vint1[i]
  y <- prep$data$Y[i]
  beta_binomial2_lpmf(y, mu, phi, trials)
}

posterior_predict_beta_binomial2 <- function(i, prep, ...) {
  mu <- prep$dpars$mu[, i]
  phi <- prep$dpars$phi
  trials <- prep$data$vint1[i]
  beta_binomial2_rng(mu, phi, trials)
}

#

print(b12.1)

loo(b12.1)
waic(b12.1)

loo(b12.1, pointwise = TRUE)
waic(b12.1, pointwise = TRUE)

#



```

**Comment by paul-buerkner** [comment]
The code presented in the vignette is not made to work with pointwise computation. See https://github.com/paul-buerkner/brms/blob/master/R/log_lik.R for how built-in families compute stuff via `get_dpar` (which is internal and needs to be called via `brms:::get_dpar`.

**Comment by DataDan01** [comment]
@paul-buerkner Thank you for the reply. I must admit I'm a new `brms` user so I'm not exactly sure how to code around the error above. Can you please generate a code example of how to extract log_lik data so it is possible to compute WAIC/PSIS pointwise? It seems weird to be able to compute it across the entire dataset but not for individual points.

I've come across the beta-binomial multiple times in my work and it would be very useful to use that likelihood in model comparison/averaging. I think having a generic example  of extracting these pointwise estimates for custom distributions would be broadly helpful to many others.

**Comment by paul-buerkner** [comment]
```
log_lik_beta_binomial2 <- function(i, prep) {
  mu <- brms:::get_dpar(prep, "mu", i = i)
  phi <- brms:::get_dpar(prep, "phi", i = i)
  trials <- prep$data$vint1[i]
  y <- prep$data$Y[i]
  beta_binomial2_lpmf(y, mu, phi, trials)
}
```

should do.

**Comment by paul-buerkner** [comment]
Adjusted the vignette accordingly.

**Comment by DataDan01** [comment]
@paul-buerkner Thank you! That is very helpful. I know the vignette update is coming in the next release. But in the meantime, if anybody is having the same issue, try the code below.

Also, is there a reason not to just make the standard example `log_lik_beta_binomial2` (~line [243](https://github.com/paul-buerkner/brms/blob/master/vignettes/brms_customfamilies.Rmd)) already include the `brms::` lines? That way pointwise PSIS/WAIC just automatically works.

```
library(rethinking)
library(dplyr)

data(UCBadmit) 

d <- UCBadmit %>% 
  mutate(gid = ifelse(applicant.gender == "male", "1", "2"))

#

rm(UCBadmit)
detach(package:rethinking, unload = T)
library(brms)

#

beta_binomial2 <- custom_family(
  "beta_binomial2", dpars = c("mu", "phi"),
  links = c("logit", "log"), lb = c(NA, 2),
  type = "int", vars = "vint1[n]"
)

#

stan_funs <- "
  real beta_binomial2_lpmf(int y, real mu, real phi, int T) {
    return beta_binomial_lpmf(y | T, mu * phi, (1 - mu) * phi);
  }
  int beta_binomial2_rng(real mu, real phi, int T) {
    return beta_binomial_rng(T, mu * phi, (1 - mu) * phi);
  }
"

stanvars <- stanvar(scode = stan_funs, block = "functions")

#

b12.1 <-
  brm(data = d, 
      family = beta_binomial2,  # here's our custom likelihood
      admit | vint(applications) ~ 0 + gid,
      prior = c(prior(normal(0, 1.5), class = b),
                prior(exponential(1), class = phi)),
      iter = 5e3, warmup = 2e3, cores = 4, chains = 4,
      stanvars = stanvars,  # note our `stanvars`
      seed = 12,
      file = "./Tests/fits/b12.01")

#

expose_functions(b12.1, vectorize = TRUE)

log_lik_beta_binomial2 <- function(i, prep) {
  mu <- brms:::get_dpar(prep, "mu", i = i)
  phi <- brms:::get_dpar(prep, "phi", i = i)
  trials <- prep$data$vint1[i]
  y <- prep$data$Y[i]
  beta_binomial2_lpmf(y, mu, phi, trials)
}

posterior_predict_beta_binomial2 <- function(i, prep, ...) {
  mu <- prep$dpars$mu[, i]
  phi <- prep$dpars$phi
  trials <- prep$data$vint1[i]
  beta_binomial2_rng(mu, phi, trials)
}

#

print(b12.1)

loo(b12.1)
waic(b12.1)

pointwise_loo <- loo(b12.1, pointwise = TRUE)

pointwise_loo$pointwise %>%
  data.frame() %>%
  arrange(desc(influence_pareto_k))
```

**Comment by paul-buerkner** [comment]
Using internal functions via `:::` is not generally recommended as they may change without prior notice or deprecation warnings. Hence, I prefer not showing this as the primary option in a vignette.
